### ISSUE TITLE
Submit Custom Function to Marketplace

### ISSUE THREAD

**Issue by BlazorDashboard** [OfficeDev/office-js-docs-pr#1000]
I have developed a Custom Excel function. May I know where do I submit it to? Or am I missing something. Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@BlazorDashboard: Thanks for asking.

@mscharlock, @davidchesnut: Could you take a look? Thanks.

**Comment by mscharlock** [comment]
Yep, I will check it out and get back to you as soon as I hear from folks. Thanks! Also, it is really awesome that you have been developing custom functions, @BlazorDashboard!

**Comment by keyur32** [comment]
Hi, Custom Functions are apart of an Office Add-ins.  You can find instructions on how to submit add-ins to the Office Store here: https://docs.microsoft.com/en-us/office/dev/store/submit-to-the-office-store

Note: there specific policies you need to adhere to when submitting your add-in to the store if it contains custom functions. This is contained here:
https://docs.microsoft.com/en-us/office/dev/store/validation-policies#15-add-ins-with-excel-custom-functions

thanks

**Comment by mscharlock** [comment]
@BlazorDashboard did @keyur32's answer adequately answer your question? I'm going to leave this issue open for the moment to give you time to respond, but will likely close it tomorrow. You can always reopen the issue if you need to!

**Comment by BlazorDashboard** [comment]
@keyur32 Yes! Thanks for your fast and detailed reply. I will be able to get on with the submission now. Please close the issue. Have a great day!

**Comment by keyur32** [comment]
Awesome!  Curious, what is the name of the add-in you are submitting?

**Comment by mscharlock** [comment]
Will keep this open if you want to reply to @keyur32 :)

**Comment by BlazorDashboard** [comment]
We have an existing App for Office add in call ConnectCode Barcode Fonts Encoder that creates barcodes using custom fonts. The Excel custom functions version we plan to submit contains a list of all the available barcode functions. For examples, =ConnectCode.EncodeCode128A(A1) or =ConnectCode.EncodeCode39(A1,1) etc...For all the barcodes that we support.

**Comment by keyur32** [comment]
Thanks! If it is an existing addin you will not want to not add that requirement set listed in the manifest. Instead you will need to offer a graceful experience and make sure your addin works in both versions without custom functions and versions with them.

Good luck on the validation!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mscharlock** [comment]
@BlazorDashboard sounds like a very cool add-in, glad that custom functions is helpful in your development of it! I am going to close this issue for now, but feel free to reopen if you need additional help or have other questions. Thanks!
