### ISSUE TITLE
Unstable behaviour of onSelectionChanged

### ISSUE THREAD

**Issue by mm90849491** [OfficeDev/office-js-docs-pr#1007]
I followed this page to register an onSelectionChanged event handler, which mimics the behaviour of cell picker, on current active worksheet in a Taskpane application, but the handler is occasionally triggered. 

I tried to debug with F12/IEChooser and found once the tool is open, the event handler is triggered perfectly fine 100% of time. The same behaviour happens even when the handler is registered on workbook.

I also notice that it helps to trigger event handle to move mouse cursor back to the application Taskpane.

Is this an expected behaviour? or I missed something to properly implement the handler.

Here is the code snippet:

```
if (typeof Excel !== 'undefined') {
      try {
        Excel.run(
          this.eventResult ? this.eventResult.context : null,
          async (context: Excel.RequestContext) => {
            if (this.eventResult) {
              this.eventResult.remove();
              await context.sync();
              this.eventResult = null;
            }

            this.eventResult = context.workbook.worksheets
              .getActiveWorksheet()
              .onSelectionChanged.add(
                async (event: Excel.WorksheetSelectionChangedEventArgs) => {
                  this.setState({ address: event.address });
                }
              );
            await context.sync();
          }
        );
      } catch (error) {
        console.log(error);
      }
    }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52542c44-015a-746d-5d6f-c43f6e4e6774
* Version Independent ID: dfe8c9fb-4107-e19b-972a-c5a58eeb2646
* Content: [Work with Events using the Excel JavaScript API - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-events#feedback)
* Content Source: [docs/excel/excel-add-ins-events.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/excel-add-ins-events.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by mm90849491** [comment]
Update:
I tested the application in Excel on Mac, iPad, and online. It works perfectly fine.
This unstable behaviour only happens in Excel on Windows (I tested Win 7 & 10).

**Comment by mscharlock** [comment]
@mm90849491 Hello and thank you for trying out Office Add-ins and writing in to our docs team! I'll go ahead and route your question to our Excel folks and get back to you on this!

**Comment by mscharlock** [comment]
Just wanted to check in here for you and let you know that I am still working on getting an answer from the Excel folks! :)

**Comment by 4tti** [comment]
Hello, 
just be aware of this: https://github.com/OfficeDev/office-js/issues/521
The events on Windows seem to have some troubles...

**Comment by mscharlock** [comment]
@kbrandl can you refile this on office-js and tag @catchingyu? Thank you! 
@4tti Awesome, thanks for the heads up! We'll move this one over so there's record of more than one person hitting this issue, hopefully that can help speed along development. :)

**Comment by catchingyu** [comment]
@mm90849491 , i create an issue https://github.com/OfficeDev/office-js/issues/533 to track it. Is it possible for you to provide us more info on this issue?

**Comment by kbrandl** [comment]
I'm going to go ahead and close this issue here in the docs repo (instead of transferring it), since @catchingyu already created a corresponding issue in the OfficeDev/office-js repo ([# 533](https://github.com/OfficeDev/office-js/issues/533)).
