### ISSUE TITLE
Function Names

### ISSUE THREAD

**Issue by smozgur** [OfficeDev/office-js-docs-pr#1008]
Thanks for this great documentation!

In the [Best Practices](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-naming#best-practices) section, GETZIPCODE is recommended against to ZIPCODE function name. However, custom functions / UDFs are not "action" functions, but "calculate/transform and return" functions.  All Excel functions have a return purpose, user simply GETs something from all Excel functions, but none of the Excel native functions (except GETPIVOTDATA as I can see) have this rule applied. 
In my opinion, ZIPCODE looks to be the right usage as the best practice in the documentation. Otherwise we should be prefixing almost all user defined functions with GET.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 714da1e2-6053-0328-b31e-0bf514ecc774
* Version Independent ID: be1e524c-1198-c288-f71e-f9d7f84abeb7
* Content: [Naming guidelines for custom functions in Excel - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-naming)
* Content Source: [docs/excel/custom-functions-naming.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/custom-functions-naming.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by mscharlock** [comment]
Hi @smozgur - thanks for your suggestion! I definitely see your point - all custom functions do technically return something. (And even Excel's built in functions, "SHEET" would return information without saying "GETSHEET"). However, in a lot of cases I think it is helpful to add a verb that says what the function is going to do so your user is clear on what kind of calculation is occurring, particularly if you have multiple things being done to or returned from one noun. For example, "ADDTOBANKACCOUNT" is quite different than "DISPLAYBANKACCOUNT" and "SUBTRACTFROMBANKACCOUNT". Just "BANKACCOUNT" might be confusing on it's own. Built-in functions in Excel use varied approaches ("SHEET" is just a noun but there's also "GETPIVOTDATA" using both noun and verb and then just verb like "ADD"). 
That being said, these are just guidelines, so feel free to name your functions the way that you thinks makes the most sense for you! If we hear more feedback like this, we can definitely look into changing the best practices page. Thanks!

**Comment by smozgur** [comment]
Thanks for the reply, @mscharlock. 

I totally agree about using the descriptive names in any kind of procedure in coding as it is the best practice to use long function names in applications as the first rule of efficient programming.

Actually I am particularly against to GET prefix as I tried to explain. Some other prefixes are indeed very useful, and I agree with you on that.

However, readability is more important when it comes to use those function names inside a small editor, so I am also not very sure about using really long names for the functions as I also thought that Excel native functions are mostly short considering this limit. Long names containing more than 2 words will cause difficulty to read the entire formula with multiple functions in it. Especially when they are all uppercase as in Excel. 

I was reading the docs and wanted to share my ideas on this. Hope I am not bothering you :) You are doing really great! Thank you.

**Comment by mscharlock** [comment]
No, definitely not a bother at all, I totally welcome the feedback! We have debated as a team about how long names should be and even whether or not a namespace is necessary (because it adds a lot of length). Also, we have found that some of our partners who are trying out custom functions tend to name things with really short abbreviations (even as short as two letters!) instead of using two or more word phrases. Just depends on your user base :) Many thanks for sharing your ideas and contributing! I definitely think your point about GET is a good one - I will put an item on my to do list to change it to a different verb. Let me know if you need anything else or have other feedback about the docs, we definitely want to hear what you have to say! I will go ahead and close this issue for now, but feel free to reopen if you have additional feedback :)
