### ISSUE TITLE
helpUrl example link is broken

### ISSUE THREAD

**Issue by TheWass** [OfficeDev/office-js-docs-pr#1011]
The helpUrl example link in the functions section (http://contoso.com/help/convertcelsiustofahrenheit.html) goes to a 404 page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc9afc49-47bc-c0b4-249f-5c66a9421747
* Version Independent ID: ae89f268-e83d-1a08-babe-3f1c3dc11796
* Content: [Metadata for custom functions in Excel - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-json)
* Content Source: [docs/excel/custom-functions-json.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/custom-functions-json.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@TheWass: Sorry this caused you some confusion but that behavior is by design. Throughout the article, contoso is used to give an example of how your URL might be structured but should be replaced with your own domain. You can also read the [Wikipedia article](https://en.wikipedia.org/wiki/Contoso) about this fictional company/domain.

**Comment by TheWass** [comment]
Ah, I understand.  From the wording and the active link, it seemed like that link was directing the reader to view an example of what the contents of the help task pane would look like.

**Comment by kbrandl** [comment]
@TheWass I can certainly understand how this fake URL being a clickable link in the article would lead to confusion. I've reformatted the link such that it's no longer clickable (PR #1021). You'll see that change applied to the article later this week (the next time we publish doc updates). Thanks for the feedback!
