### ISSUE TITLE
The browser might show an invalid certificate error that you will need to bypass.

### ISSUE THREAD

**Issue by SaiKoduri3** [OfficeDev/office-js-docs-pr#1016]
It will be better if you could tell how to bypass this. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f544127-c7ed-2cee-c7eb-744dc1ce2675
* Version Independent ID: a6474b7d-1f80-f675-331b-640882bd25c5
* Content: [Debug add-ins in Office Online - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-add-ins-in-office-online#feedback)
* Content Source: [docs/testing/debug-add-ins-in-office-online.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/debug-add-ins-in-office-online.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
I've added some guidance. This will probably appear in the published article by tonight Pacific Time Zone. 
The guidance has to be very general because the process is different from one browser to another and there are multiple ways of doing it.
