### ISSUE TITLE
Debugging startup errors

### ISSUE THREAD

**Issue by Noino** [OfficeDev/office-js-docs-pr#1018]
As far as i can figure out, i have to actually open the add-in pane for it to show up in the F12Chooser window, and starting the debugger then is too late when the error happened on startup.
How do i go about debugging add-ins that fail on startup, or actions that do not open a pane?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b6ad3bb-b3fe-e8c6-4a38-f6df85dbabf4
* Version Independent ID: 194afc55-e012-edc5-da88-9858f1d52f34
* Content: [Debug add-ins using F12 developer tools on Windows 10 - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-add-ins-using-f12-developer-tools-on-windows-10#feedback)
* Content Source: [docs/testing/debug-add-ins-using-f12-developer-tools-on-windows-10.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/debug-add-ins-using-f12-developer-tools-on-windows-10.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by kbrandl** [comment]
@Noino seems like the information in [Use runtime logging to debug your add-in](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/troubleshoot-manifest#use-runtime-logging-to-debug-your-add-in) may be useful in the scenarios you've described. Please check out those instructions and let me know if they provide the type of information you're needing.

**Comment by Noino** [comment]
@kbrandl This method did not produce any information related to my add-in. Doubt it is a manifest related issue anyway, since it works fine in the browser. 
In outlook the sidebar thingy (Action:ShowTaskPane) opens but remains empty, and popup/modal window (Action:ExecuteFunction->Office.context.ui.displayDialogAsync) fails to open and i'm only getting a infinite "add-in is working on your request".

**Comment by Noino** [comment]
with "browser" i was referring to anything other then IE, but it seems that is exactly what outlook is working with and looks like its the root of my problem.. Indeed the choice of compatibility tool to run this functionality on is shocking, seeing that the web app itself has trouble working in IE, but that is beyond the scope of this article and ticket. 
I've found a way to debug using developer console, by doing it on the webapp using IE, and I've found the source of this to be incompatible syntax. Oh how i wish there was a way to disable the js add-in on the desktop version of outlook.

**Comment by kbrandl** [comment]
@Noino thanks for the update; glad to hear that you've figured out the problem.

For future reference, [runtime logging](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/troubleshoot-manifest#use-runtime-logging-to-debug-your-add-in) can be helpful in debugging various types of add-in issues (not just manifest-related issues). I realize that current placement of the information about runtime logging in the docs is misleading (since it implies that runtime logging is only useful in debugging manifest-related issues), and we'll likely be looking to address this soon.
