### ISSUE TITLE
XHR example

### ISSUE THREAD

**Issue by smozgur** [OfficeDev/office-js-docs-pr#1020]
In the[ XHR Sample code](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-web-reqs#xhr-example), setRequestHeader, open and send methods of xhttp are not supposed to be placed in onreadystatechange callback function.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 667d1e98-4a95-318f-0df1-182722370ac8
* Version Independent ID: f8265387-ba9d-a5db-ef44-8409441b2ece
* Content: [Receive and handle data with custom functions - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-web-reqs)
* Content Source: [docs/excel/custom-functions-web-reqs.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/custom-functions-web-reqs.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by mscharlock** [comment]
Hi @smozgur - thanks for letting me know, appreciate the feedback! Let me confer with the team on getting an updated sample. :)

**Comment by mscharlock** [comment]
Hi @smozgur, a sample is coming. Team wanted to figure out if more people were using fetch vs. XHR and what would be the best approach in the docs, which is why this has taken a little longer to address than usual. Anyway, wanted to update you so you know that we haven't forgotten about this!

**Comment by mscharlock** [comment]
Hi @smozgur, a new sample should be up on the docs tomorrow. (PR has been approved and we're just waiting to merge in batched changes on our usual Tues/Thurs cycle). Thanks! I'm going to close this issue but let me know if you need anything else by commenting on this issue again.
