### ISSUE TITLE
yo office requires git

### ISSUE THREAD

**Issue by davidchesnut** [OfficeDev/office-js-docs-pr#1026]
Tutorials and quick starts that use Yo Office don't currently list **git** as a required prerequisite-- but Yo Office requires it.

## Article URL
(All quick starts and tutorials that use Yo Office)
e.g., https://docs.microsoft.com/office/dev/add-ins/tutorials/excel-tutorial-create-custom-functions

## Issue
Yo Office requires git to operator correctly. You'll see this if you follow the steps on a brand new computer with nothing already installed.
 
All articles that contain guidance about using Yo Office should be updated to list Git as a required prerequisite.

**Comment by kbrandl** [comment]
@davidchesnut FYI, I've updated the description of this issue to indicate that this issue applies to any article that contains guidance for Yo Office (not just the Custom Functions tutorial). I'll fix this issue today.

**Comment by kbrandl** [comment]
Submitted PR #1029 to address this issue. Changes will be visible in the live docs later this week, after the PR is merged and doc updates are published.
