### ISSUE TITLE
Naming streaming functions

### ISSUE THREAD

**Issue by jakobpn** [OfficeDev/office-js-docs-pr#1027]
Do you have a recommendation on how to name streaming functions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 714da1e2-6053-0328-b31e-0bf514ecc774
* Version Independent ID: be1e524c-1198-c288-f71e-f9d7f84abeb7
* Content: [Naming guidelines for custom functions in Excel - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-naming#feedback)
* Content Source: [docs/excel/custom-functions-naming.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/custom-functions-naming.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by mscharlock** [comment]
Hi @jakobpn! :) What kind of information would you be looking for? Having consulted with our editor and @keyur32 on naming we didn't think guidance around streaming was necessary (I guess I would assume people would add STREAM to the end of a function if necessary), but maybe you are looking for something specific or have an idea in mind? Let me know, happy to update these docs with some guidance if you have a suggestion!

**Comment by mscharlock** [comment]
Just wanted to let you know that I've put a note in about this into our naming article! I'm going to go ahead and close this issue but let me know if you need further assistance, happy to reopen this issue for you.
