### ISSUE TITLE
@customfunction id property

### ISSUE THREAD

**Issue by smozgur** [OfficeDev/office-js-docs-pr#1030]
[Documentation](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-json-autogeneration#section-1) says: 

The characters allowed are limited to: A-Z, a-z, 0-9, and period (.).

However, I am able to use underscore for the id property, just like the name.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be178996-8552-f246-7adf-58cecb58a0f9
* Version Independent ID: cfe4f29e-87ea-6332-8e17-e858392c1961
* Content: [Autogenerate JSON metadata for custom functions - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-json-autogeneration#section-1)
* Content Source: [docs/excel/custom-functions-json-autogeneration.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/custom-functions-json-autogeneration.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by kbrandl** [comment]
@smozgur thanks for the feedback! We'll look into this and update the docs accordingly.

(@mscharlock can you please look into this when you have a chance? Thanks!)

**Comment by mscharlock** [comment]
Yep, will do!

**Comment by mscharlock** [comment]
@smozgur are you seeing an underscore allowed in Script Lab or on a project that is up and running? Script Lab does not have complete parity with the registration mechanism used by custom functions, so it allows _s while regular custom functions projects do not. I'm working to file a bug (and figure out which one engineering actually wants) but wanted to update you and ask.

**Comment by smozgur** [comment]
@mscharlock, both of them. 
As a sample, following function works in custom Office add-in as well as Script Lab:

```
/**
 * Calculates the average of two numbers
 * @customfunction AVERAGE_1
 * @param {number} first_number First number
 * @param {number} second_number Second number
 * @returns {number} The average of the two numbers.
 */
function average (first_number, second_number) {
	return (first_number + second_number) / 2;
}
CustomFunctions.associate("AVERAGE_1", average)
```

Metadata is successfully generated as same for both.

**Comment by smozgur** [comment]
Actually I don't know if it is a bug. I would expect underscore is accepted by the id. That's why I tested a custom function with underscore in the first place actually.

**Comment by mscharlock** [comment]
Awesome, thanks for letting me know. I'll be able to get back to you once @keyur32 is back in the office (should be Tuesday). :)

**Comment by mscharlock** [comment]
Ok, I got some clarity from people. Turns out underscores are supposed to be allowed in both id and name. I'll have a fix out here shortly! Thanks for reporting this issue. :)

**Comment by mscharlock** [comment]
Going to go ahead and close this issue now that a fix has been implemented in the docs - thanks again for the suggestion @smozgur! Feel free to leave a comment to the issue if you need any further assistance, but I'll close for now!
