### ISSUE TITLE
COM Add-in

### ISSUE THREAD

**Issue by jhnd7710** [OfficeDev/office-js-docs-pr#1034]
Hello!

Could you please tell if there are any possible options for promoting MS Outlook COM add-in?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42faa32c-446b-0209-4a24-9a29b4921ea1
* Version Independent ID: a5f0fc77-a881-df1e-1f49-aa0e555022e0
* Content: [Office Add-ins platform overview - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/overview/office-add-ins#feedback)
* Content Source: [docs/overview/office-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/overview/office-add-ins.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by kbrandl** [comment]
@jhnd7710 thanks for reaching out! I'd be happy to provide some guidance, but I'm not quite sure what type of information you're seeking. Can you please clarify what you mean by _promoting MS Outlook COM add-in_?

**Comment by jhnd7710** [comment]
Hi, @kbrandl!! 8) Well, first I came up with an idea to add it to MS Appsource but VSOT/COM add-ins are not supported, damn.. ( Obviously they're not supported at all. Then I thought probably there should be other ways to get listed somewhere related closely to Microsoft. We thought we could enroll their Partners Program but there's no certainty we would have an option to add our software as it is VSOT. 
I mean if we out of Appsourse, perhaps, another online apps library exists for such unfortunate cases like ours. Please help. )

**Comment by kbrandl** [comment]
@jhnd7710 thanks for the clarification! As you've indicated, [AppSource](https://appsource.microsoft.com) only accepts [Office (web) Add-ins](https://docs.microsoft.com/office/dev/add-ins/overview/office-add-ins) and unfortunately, there's no longer a Microsoft-owned marketplace for VSTO / COM add-ins. I realize this isn't the answer you were hoping for, but you'll need to promote/market your VSTO add-in in another way (on your own).
