### ISSUE TITLE
Samples desired

### ISSUE THREAD

**Issue by jakobpn** [OfficeDev/office-js-docs-pr#1043]
Would be great to have a couple of sample functions on this page that show how the @tags are used together and to what effect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be178996-8552-f246-7adf-58cecb58a0f9
* Version Independent ID: cfe4f29e-87ea-6332-8e17-e858392c1961
* Content: [Autogenerate JSON metadata for custom functions - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-json-autogeneration)
* Content Source: [docs/excel/custom-functions-json-autogeneration.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/custom-functions-json-autogeneration.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by kbrandl** [comment]
@jakobpn thanks for reaching out with this suggestion. @mscharlock FYI, assigning to you for consideration. Thanks!

**Comment by mscharlock** [comment]
Thanks, I can add some :) Thanks for the suggestion, @jakobpn!

**Comment by mscharlock** [comment]
Just wanted to let you know @jakobpn that we've pushed in changes to address this, so samples should be in the docs next Tuesday when we do our next update! I'm going to close this issue for now but let me know if you need anything else with a comment on this thread. Thanks!
