### ISSUE TITLE
How to provide a function description

### ISSUE THREAD

**Issue by jakobpn** [OfficeDev/office-js-docs-pr#1044]
How do I provide a description to the function using the @tags?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be178996-8552-f246-7adf-58cecb58a0f9
* Version Independent ID: cfe4f29e-87ea-6332-8e17-e858392c1961
* Content: [Autogenerate JSON metadata for custom functions - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-json-autogeneration)
* Content Source: [docs/excel/custom-functions-json-autogeneration.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/custom-functions-json-autogeneration.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by kbrandl** [comment]
@jakobpn thanks for reaching out with this question. @mscharlock are you able to provide some feedback here (and update the docs if necessary)? Thanks!

**Comment by mscharlock** [comment]
Yep, can do. Thanks for pointing that out - just for your reference in the meantime, it is the first sentence you enter in the JSDOC *s that isn't accompanied by a tag, typically right after @customfunction. So, something like: 
```
/**
/*@customfunction
/*a function that sums two numbers
…
```
I will put a fix in today! :)

**Comment by mscharlock** [comment]
Ok, I've put a fix in (took a while in editing as our team is quite busy). I'm going to close this issue for now, but feel free to comment on this issue again if you need anything else and I can reopen it. Thanks!
