### ISSUE TITLE
Custom Functions add-in on Excel (Mac platform) - custom functions are not visible.

### ISSUE THREAD

**Issue by Himanshusingh01** [OfficeDev/office-js-docs-pr#1053]
## Article URL
https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/excel-tutorial-create-custom-functions?tabs=excel-windows

## Issue
The custom function is not available though the add-in is sideloaded successfully. The problem is observed on Excel (version 16.23) on Mac platform. 
<img width="641" alt="Screen Shot 2019-06-04 at 12 26 23 PM" src="https://user-images.githubusercontent.com/3669278/58858057-520ff400-86c4-11e9-894d-50c24d14d8c6.png">

**Comment by mscharlock** [comment]
Hi @Himanshusingh01 - thanks for reading the docs about custom functions and trying them out! Have you tried clearing the Office cache? [Instructions here](https://docs.microsoft.com/office/dev/add-ins/testing/troubleshoot-manifest?branch=master#clear-the-office-cache) on how to do that. I would also make sure that your code is [associating functions properly](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-best-practices). If neither of those is the case, let me know and I can investigate! Thanks.

**Comment by Himanshusingh01** [comment]
Hi @mscharlock - Thanks for the revert.

Tried the suggestions but the problem is still there.

Folder ~/Library/Containers/com.Microsoft.OsfWebHost/Data/  doesn't exist in my system so as suggested in the post I deleted files from ~/Library/Containers/com.microsoft.Excel/Data/Library/Caches/ and 
com.microsoft.Office365ServiceV2/Data/Library/Caches/com.microsoft.Office365ServiceV2 folders.

I have also verified the association of functions and it looks fine. I have attached the json file for reference. 
[functions.txt](https://github.com/OfficeDev/office-js-docs-pr/files/3255661/functions.txt)

Just in case if it help in isolating the issue my OS is macOS High Sierra version 10.13.2 and the excel version is 16.23.

**Comment by Himanshusingh01** [comment]
Additional Info - I also did a quick check to see if it works on windows platform. 

I used network share drive to sideload the add in and test as described in the link https://docs.microsoft.com/en-us/office/dev/add-ins/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins 

The Add-in didn;t appear in the shared folder tab unless I remove following lines from manifest.

<Requirements>
    <Sets DefaultMinVersion="1.1">
      <Set Name="CustomFunctionsRuntime" MinVersion="1.1"/>
    </Sets>
  </Requirements>

The error in the log file is : Add-in has declared requirements that current host does not support. 

Windows OS: Windows 7 with Excel 2016

**Comment by keyur32** [comment]
Hi @Himanshusingh01, you will need update your build of Mac to be at least 16.24 or later. 

Here are the requirements to put in Custom Functions: https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/excel-api-requirement-sets#custom-functions

@mscharlock  -  can we put a cross link from the custom functions topic so it is clear?

**Comment by mscharlock** [comment]
@keyur32 Yes, can do!

**Comment by Himanshusingh01** [comment]
It worked after upgrading the Excel to 16.25. Thanks @keyur32 @mscharlock
