### ISSUE TITLE
Troubleshoot user errors with Office Add-ins

### ISSUE THREAD

**Issue by HeatherAllemang** [OfficeDev/office-js-docs-pr#1057]
suggestions
add the location of the debug log for internet explorer.
Can you add anything for when users get 'Access denied'?
Otherwise great article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6cb5f52-dfc5-4fa2-6508-194d6f1c674a
* Version Independent ID: 8f3caf2d-fba3-166f-43bc-1d3e4007abab
* Content: [Troubleshoot user errors with Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/testing-and-troubleshooting)
* Content Source: [docs/testing/testing-and-troubleshooting.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/testing-and-troubleshooting.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by mscharlock** [comment]
Hi @HeatherAllemang - Thanks for reading our docs and for the suggestions! We will go ahead and take them into consideration and add appropriate work items to our backlog. Are you having an "access denied" error that you need assistance with? If so, to help troubleshoot it would be great if you can give me some more details about the situation in which you get this message (what action are you trying to perform, what product are you using, etc). Thanks!

**Comment by HeatherAllemang** [comment]
Hello,
I have the fix for this now.  The users need to have the ‘Read/Write’ mailbox permissions role, which is talked about here:
https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/add-ins-for-outlook/specify-who-can-install-and-manage-add-ins
We get a fair amount of tickets where users cannot use add-ins.

thanks
Heather

**Comment by mscharlock** [comment]
@HeatherAllemang glad that you were able to find a fix for the issue. Let me know if you need any further assistance - I'm going to close this thread for now, but if you comment on it in the future and ask me to reopen it, I will do! Thanks :)

**Comment by HeatherAllemang** [comment]
thanks. Adding the mailbox role perms of 'read/write' which is needed for some office apps resolves the issue where users get the error 'access denied' when trying to use an office add-in.  At least this is one of the scenarios where it fixes the issue.
