### ISSUE TITLE
Custom Functions Tutorial needs to be updated

### ISSUE THREAD

**Issue by keyur32** [OfficeDev/office-js-docs-pr#1058]
## Article URL
https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/excel-tutorial-create-custom-functions?tabs=excel-windows

## Issue
- Tutorial talks about calling stock prices.
- We need to update to reflect new stock end point and API key is required so the function calls continue to work as the underlying API changes to reflect new model

**Comment by keyur32** [comment]
We should update:
 var url = "https://api.iextrading.com/1.0/stock/" + ticker + "/price";

with 
//Note: you will need to register for an account to get a token on https://iexcloud.io/ 
 var url = "https://cloud.iexapis.com/stable/stock/" + ticker + "/quote/latestPrice?token=<YOUR_TOKEN_HERE>"

**Comment by mscharlock** [comment]
API key fix is in and a PR is being prepped with some samples that use an alternative API. Thank you for reporting this and using the p1 tag - that helps us keep track of what's the most important fix. :) Apologies that this fix went in later than we anticipated.
