### ISSUE TITLE
Document links to a non-existing .json file in its note

### ISSUE THREAD

**Issue by PeterBrodersen** [OfficeDev/office-js-docs-pr#1064]
The document specifies:

> A complete sample JSON file is available in the [OfficeDev/Excel-Custom-Functions](https://github.com/OfficeDev/Excel-Custom-Functions/blob/master/src/functions/functions.json) GitHub repository.

However it links to a non-existing .json file:
https://github.com/OfficeDev/Excel-Custom-Functions/blob/master/src/functions/functions.json

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc9afc49-47bc-c0b4-249f-5c66a9421747
* Version Independent ID: ae89f268-e83d-1a08-babe-3f1c3dc11796
* Content: [Metadata for custom functions in Excel - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-json)
* Content Source: [docs/excel/custom-functions-json.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/custom-functions-json.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by kbrandl** [comment]
@PeterBrodersen thanks for reporting this issue; we'll look into it and update doc as needed.

@mscharlock can you please look into this issue when you have a chance? Looks like the functions.json file is no longer included in the sample project (OfficeDev/Excel-Custom-Functions), presumably since it's being autogenerated from the JSDoc comments. Thanks!

**Comment by mscharlock** [comment]
@kbrandl oh right! Yes, sure thing. :) Thanks for pointing this out, @PeterBrodersen. We have switched up the yo office template a couple times, so this is an out of date link. I'll go ahead and update it.

**Comment by mscharlock** [comment]
@PeterBrodersen a fix is in the docs and should go out tomorrow when we do our latest pull in of all our updates. Thank you for reporting this and hope you are enjoying developing with custom functions! I'm going to close this issue but let me know if you would like me to reopen this issue by commenting on it. Thank you again!
