### ISSUE TITLE
Broken (external) links

### ISSUE THREAD

**Issue by kbrandl** [OfficeDev/office-js-docs-pr#1065]
The June CATS report flagged the following two broken links. For each of these links, either replace the link with a valid link, or remove the link altogether (and revise article as needed).

**Broken link # 1:**
- Article: [Naming guidelines](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-naming)
- Source file: https://github.com/OfficeDev/office-js-docs-pr/blob/live/docs/excel/custom-functions-naming.md
- Broken link in the article: https://www.microsoft.com/en-us/download/details.aspx?id=1465

**Broken link # 2:**
- Article: [Autogenerate JSON metadata for custom functions](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-json-autogeneration)
- Source file: https://github.com/OfficeDev/office-js-docs-pr/blob/live/docs/excel/custom-functions-json-autogeneration.md
- Broken link in the article: https://usejsdoc.org/tags-param.html

**Comment by kbrandl** [comment]
@mscharlock can you please look into this issue when you have time? I did a quick internet search for new/replacement links but didn't find anything ideal; so probably best for you (as someone who's more familiar with this content) to find replacement links. Thanks!

**Comment by mscharlock** [comment]
Ok, can do!

**Comment by mscharlock** [comment]
Fixed! Thanks for the flag, appreciate it.
