### ISSUE TITLE
Invalid bookmark

### ISSUE THREAD

**Issue by kbrandl** [OfficeDev/office-js-docs-pr#1066]
The June CATS report flagged the following broken bookmark. Need to either update the bookmark to point to a valid location, or remove the bookmark altogether (and revise surrounding content in article as needed).

**Broken bookmark**
- Article: [Custom functions metadata](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-json)
- Source file: https://github.com/OfficeDev/office-js-docs-pr/blob/live/docs/excel/custom-functions-json.md
- Link with invalid bookmark: /office/dev/add-ins/excel/custom-functions-overview#determine-which-cell-invoked-your-custom-function

**Comment by kbrandl** [comment]
@mscharlock can you please look into this issue when you have time? I did a quick search of the docs to see if I could find the correct link/bookmark to use here, but didn't find anything; so probably best for you (as someone who's more familiar with this content) to update with the correct link/bookmark. Thanks!

**Comment by mscharlock** [comment]
Sure, will do. I'll look into it and update. Sorry for the delay. Thanks!

**Comment by mscharlock** [comment]
Closing this issue as I've updated the link! Thanks for the flag :)
