### ISSUE TITLE
Need clarification of "same domain" in Dialog overview

### ISSUE THREAD

**Issue by Rick-Kirkham** [OfficeDev/office-js-docs-pr#107]
## Article URL
https://docs.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins

## Issue
Need to make clear what "same domain" means in note about opening dialog in page from the same domain as parent page. See https://github.com/OfficeDev/office-js/issues/73#issuecomment-370204722

**Comment by AlexJerabek** [comment]
Updated in [PR 384](https://github.com/OfficeDev/office-js-docs-pr/pull/384). Should be live soon. Closing the issue.
