### ISSUE TITLE
missing TOC entry

### ISSUE THREAD

**Issue by kbrandl** [OfficeDev/office-js-docs-pr#1088]
There's no TOC entry for this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2520e2b8-0845-ac29-8de8-4d7f39049802
* Version Independent ID: 3fda6834-a5c1-d45e-51a8-4f61714aaf2b
* Content: [COM add-in and XLL UDF requirements - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/xll-compatibility-requirements#feedback)
* Content Source: [docs/excel/xll-compatibility-requirements.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/xll-compatibility-requirements.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by kbrandl** [comment]
@mscharlock FYI, I noticed today that this article doesn't exist in the TOC. Can you please update the TOC to add an entry for this article in the appropriate location? Thanks!

**Comment by mscharlock** [comment]
Sure, can do

**Comment by mscharlock** [comment]
This should be addressed in a recent PR! Thanks for the flag, I appreciate it! :)
