### ISSUE TITLE
Custom Functions Information needs to be more clear about the versions of Office Custom Functions can run in

### ISSUE THREAD

**Issue by keyur32** [OfficeDev/office-js-docs-pr#1092]
## Article URL
https://aka.ms/customfunctions

## Issue

 
We have many reports from customers who cannot find the correct information to build custom functions.
-  Often they will try on 2019 and hit issues.  We should be clear this does not work on 2019. 
- Our documentation still states 1810 or earlier. For production, we should stay 1904 as specified in the [custom functions requirements article here](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/excel-api-requirement-sets#custom-functions)

The information is here:
-  https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-requirements
-  https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/excel-api-requirement-sets#custom-functions

But customers are not discovering it, because it is not linked via the quickstart
https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-custom-functions-quickstart?tabs=excel-windows

**Comment by mscharlock** [comment]
In a PR, thanks for the flag!

**Comment by mscharlock** [comment]
Should go up in documentation tomorrow, when the latest changes are pulled in. Going to close this issue for now, but notify me on this thread if you want me to reopen and change things. Happy to help!
