### ISSUE TITLE
Dead link for complex manifest file

### ISSUE THREAD

**Issue by PeterBrodersen** [OfficeDev/office-js-docs-pr#1098]
The text phrase "which you can compare on this Github repository." links to
https://github.com/OfficeDev/Excel-Custom-Functions/blob/generate-metadata/manifest.xml
However this page is not found.

The real link might be:
https://github.com/OfficeDev/Excel-Custom-Functions/blob/master/manifest.xml

(this might be related to #1064 ?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94ad7803-d4f7-a700-7c7f-204cd8f34e4a
* Version Independent ID: 9c485bae-cab1-bdad-4c8e-baad2b12b22d
* Content: [Create custom functions in Excel - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-overview#feedback)
* Content Source: [docs/excel/custom-functions-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/custom-functions-overview.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by mscharlock** [comment]
Gosh darn it, sorry about that. I will update this for you - I thought I had the right URL. Thanks for keeping me honest! :)

**Comment by mscharlock** [comment]
Should be up to date now! I am going to close this issue but let me know if you need anything else by commenting on this thread.
