### ISSUE TITLE
Incorrect name in XML sample

### ISSUE THREAD

**Issue by jakobpn** [OfficeDev/office-js-docs-pr#1099]
We have a partner reporting that the element currently named ProgID should be named ProgId.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e01562c5-ae22-8345-83f5-c1159bbb7cf0
* Version Independent ID: 70835436-060e-807f-3cee-a8ca0f7b6959
* Content: [Make your Office Add-in compatible with an existing COM add-in - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/make-office-add-in-compatible-with-existing-com-add-in#feedback)
* Content Source: [docs/develop/make-office-add-in-compatible-with-existing-com-add-in.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/make-office-add-in-compatible-with-existing-com-add-in.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
@jakobpn Are you able to verify that information? If so, it's an easy enough documentation change.

**Comment by kbrandl** [comment]
@jakobpn thanks for reporting this issue; it's been addressed by PR #1103.
