### ISSUE TITLE
[Warning] [blocked] The page at https://localhost:3000/index.html?_host_Info=Word$Mac$16.01$en-US was not allowed to run insecure content from http://localhost:1234/

### ISSUE THREAD

**Issue by 12s** [OfficeDev/office-js-docs-pr#1100]
Hello,

I am trying to fetch data from localhost:1234 to localhost:3000 where the add-in is hosted. 

I have tried all the conventional ways unsuccessfully before coming across this page and trying the jsonP method.  The script tag gets added the the head node, but no network request is made and I get the blocked warning in seen in the title.

No request is made in the network part of the inspector and I can't reach my express app to return my data (with or without formatting it with a callback)

Is there a repo with a simple fetch request (or equivalent) demonstrating CORS for an add-in, ideally for a word add-in?

I am on Mac Mojave with Word for mac 16.01 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e24dccf5-3758-3d59-f896-c0a16306a238
* Version Independent ID: 0950c3fd-cdce-9f58-bcfe-baf9930dcd5f
* Content: [Addressing same-origin policy limitations in Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/addressing-same-origin-policy-limitations)
* Content Source: [docs/develop/addressing-same-origin-policy-limitations.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/addressing-same-origin-policy-limitations.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by 12s** [comment]
Also, I have added the AppDomain to the manifest. I'm guessing now that the localhost:1234 app needs to be https:// .. I'll try and get that checked too

**Comment by 12s** [comment]
.. so to answer my own question, I was able to get the correct responses from the https://localhost after creating and trusting my own certs on the server. Looked like this:

var credentials = {key: privateKey, cert: certificate};
var httpsServer = https.createServer(credentials, app);
httpsServer.listen(8443);

**Comment by kbrandl** [comment]
@12s thanks for updating this issue with your solution; I'll go ahead and close this issue now.
