### ISSUE TITLE
Link to modified manifest mail app schema is dead

### ISSUE THREAD

**Issue by nbaolong48** [OfficeDev/office-js-docs-pr#1114]
When following the article to setup SSO in add-in for .net, the link to "Modified MailAppVersionOverrides Schema" is dead.

## Article URL
https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/create-sso-office-add-ins-aspnet.md

## Issue

 Workaround for Outlook: Copy this modified version of the file into the folder: <link>Modified MailAppVersionOverrides Schema</link> -> link is dead here.

**Comment by Rick-Kirkham** [comment]
Thanks for catching this. I'll get that fixed. The correct URL is: 
https://github.com/OfficeDev/outlook-add-in-attachments-demo/blob/master/manifest-schema-fix/MailAppVersionOverridesV1_1.xsd

**Comment by Rick-Kirkham** [comment]
This is fixed in the source file and the corrected version should publish tonight I the Pacific Time Zone (USA).
