### ISSUE TITLE
JQuery related errors in Word Add-in

### ISSUE THREAD

**Issue by oaltun** [OfficeDev/office-js-docs-pr#1124]
On Visual Studio 2019 Community Edition, I started with the C# Word Web Add-in template. The template runs fine directly. Then I followed the steps in this page, except step 13, as step 13 is related to the Excel template.

When I push the Start button on Visual Studio, I get following errors:

Severity	Code	Description	Project	File	Line	Suppression State

Error		Build:Cannot find namespace 'Sizzle'.	WordWebAddIn1Web	jQuery.d.ts	27	
Error		Build:Cannot find namespace 'Sizzle'.	WordWebAddIn1Web	jQuery.d.ts	35	
Error		Build:Cannot find namespace 'Sizzle'.	WordWebAddIn1Web	jQuery.d.ts	43	
Error		Build:Cannot find name 'JQueryStatic'.	WordWebAddIn1Web	jQuery.d.ts	6535	
Error		Build:Cannot find name 'JQueryStatic'.	WordWebAddIn1Web	jQuery.d.ts	6536	
Error	TS2503	(TS) Cannot find namespace 'Sizzle'.	WordWebAddIn1Web	jQuery.d.ts	27	Active
Error	TS2503	(TS) Cannot find namespace 'Sizzle'.	WordWebAddIn1Web	jQuery.d.ts	35	Active
Error	TS2503	(TS) Cannot find namespace 'Sizzle'.	WordWebAddIn1Web	jQuery.d.ts	43	Active
Error	TS2304	(TS) Cannot find name 'JQueryStatic'.	WordWebAddIn1Web	jQuery.d.ts	6535	Active
Error	TS2304	(TS) Cannot find name 'JQueryStatic'.	WordWebAddIn1Web	jQuery.d.ts	 6536	 Active

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b888399c-fe96-0934-00ce-86db8fa8cf5b
* Version Independent ID: 2c5d24e8-5639-42b1-4d12-119f89591550
* Content: [Convert an Office Add-in project in Visual Studio to TypeScript - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/convert-javascript-to-typescript#feedback)
* Content Source: [docs/develop/convert-javascript-to-typescript.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/convert-javascript-to-typescript.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@oaltun Sorry to hear that you're hitting these errors. We're digging into this and should give you an update soon. Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@oaltun Unfortunately I'm unable to repro the build errors you reported. While I am seeing the TS errors, on F5 Word is opened and the add-in is working. Can you share some more info about your VS configuration? I installed VS Community 2019 version 16.1.3. Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@oaltun I'll close this issue now. However, if you're still blocked, let us know and we'll reactivate it. Thanks again for reporting this!
