### ISSUE TITLE
Troubleshooting guide needs to have a section for "Error loading Add-in" message in the status bar.

### ISSUE THREAD

**Issue by keyur32** [OfficeDev/office-js-docs-pr#1128]
## Article URL
https://docs.microsoft.com/en-us/office/dev/add-ins/testing/testing-and-troubleshooting

## Issue

Customer Report on error that they saw during install. Advice was to re-install and install again.

While I think that is OK, we should ask users to submit feedback so our team can capture telemetry and logs.

**Comment by keyur32** [comment]
Error was "Error loading add-in".  We need to find some additional telemetry so we can make this error more meaningful.

**Comment by Reezaali** [comment]
[Internal task.](https://office.visualstudio.com/e853b87d-318c-4879-bedc-5855f3483b54/_workitems/edit/3449304)

**Comment by Rick-Kirkham** [comment]
Fixed in source. Should be in published version in the next 48 hours.
