### ISSUE TITLE
Two things the article doesn't mention 

### ISSUE THREAD

**Issue by plmayfield** [OfficeDev/office-js-docs-pr#1142]
For this to work properly I had to add the following ...
1. Debug didn't work. It complained about missing symbols. I added the sourcemap line to the tsconfig.json file. 

    ```
    {
      "compilerOptions": {
        "skipLibCheck": true,
        "lib": [ "es5", "dom", "es2015.promise" ],
        "sourceMap": true
      }
    }
    ```

2. After converting to .ts, all the Microsoft reference documentation change the calls to something like this ...

    ```
    // Run a batch operation against the Excel object model
    await Excel.run(async  (ctx) => {
        // Create a proxy object for the active sheet
        const sheet = ctx.workbook.worksheets.getActiveWorksheet();
    
        // Queue a command to write the sample data to the worksheet
        sheet.getRange("B3:D5").values = values;

        // Run the queued-up commands, and return a promise to indicate task completion
        await ctx.sync();
    })
    ```

This threw Javascript errors 'promise' is undefined. I found this link ... https://stackoverflow.com/questions/44461312/office-addins-file-in-its-typescript-version-doesnt-work

which fixed it, note that you have to scroll all the way to the bottom as the solution wasn't posted correctly at first. The short version is to add the line "(window as any).Promise = OfficeExtension.Promise;" right after Office.initialize. 

```
// The initialize function must be run each time a new page is loaded.
Office.initialize = function (reason) {
        
  (window as any).Promise = OfficeExtension.Promise;

  $(document).ready(function () {
```

It would be super helpful if this article was updated to include these two items as they took hours to sort out. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b888399c-fe96-0934-00ce-86db8fa8cf5b
* Version Independent ID: 2c5d24e8-5639-42b1-4d12-119f89591550
* Content: [Convert an Office Add-in project in Visual Studio to TypeScript - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/convert-javascript-to-typescript)
* Content Source: [docs/develop/convert-javascript-to-typescript.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/convert-javascript-to-typescript.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by kbrandl** [comment]
@plmayfield thank you for providing this feedback, and apologies that the article didn't provide all the information you needed. We'll look into updating the article to incorporate this info.

**Comment by plmayfield** [comment]
It is impressive that you updated this so quickly. Thanks.

**Comment by kbrandl** [comment]
@plmayfield we appreciate you reporting this issue so that we could update the docs -- thank you! FYI, you'll see the updates reflected in the live docs later today (when the next batch of doc updates gets published).
