### ISSUE TITLE
Debugging add-in loaded with Edge engine

### ISSUE THREAD

**Issue by RoelVB** [OfficeDev/office-js-docs-pr#1145]
This article only tells how to debug using IE, but what if the add-in is loaded with Edge.
[Browser used by Office Add-ins](https://docs.microsoft.com/nl-nl/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins)

It also looks like there is a way to force Office to use IE for your add-in, because Microsoft's Insights add-in is still using IE while others don't.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b6ad3bb-b3fe-e8c6-4a38-f6df85dbabf4
* Version Independent ID: 194afc55-e012-edc5-da88-9858f1d52f34
* Content: [Debug add-ins using F12 developer tools on Windows 10 - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-add-ins-using-f12-developer-tools-on-windows-10)
* Content Source: [docs/testing/debug-add-ins-using-f12-developer-tools-on-windows-10.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/debug-add-ins-using-f12-developer-tools-on-windows-10.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
Thanks for pointing this out. I'll get the article fixed. In the meantime, for Edge debugging, we recommend this tool: [Microsoft Edge Devtools](https://www.microsoft.com/p/microsoft-edge-devtools-preview/9mzbfrmz0mnj?activetab=pivot%3Aoverviewtab).

**Comment by Rick-Kirkham** [comment]
Fixed in the source. Should be published in the next 48 hours.
