### ISSUE TITLE
Tutorial Not working 

### ISSUE THREAD

**Issue by stavidawg** [OfficeDev/office-js-docs-pr#1162]
Hello, I am running Windows 10 and using Visual Studio 2019 (16. and Excel Office 365. Visual Studio Installer shows I have every package under "Office/SharePoint Development" installed except the optional "windows Identity Foundation 33.5". I have run through/re-completed the steps listed now over 3 times. I do not get any errors when I run, but there is no option to "show task pane" in excel and the developer tab shows a greyed out "add-ins" button.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c4ddde7-f1fd-44ba-fba1-0ae9d0131df7
* Version Independent ID: d946ffe6-f29f-1563-b679-121090ba60a1
* Content: [Build your first Excel task pane add-in - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-jquery?tabs=visual-studio#feedback)
* Content Source: [docs/quickstarts/excel-quickstart-jquery.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/quickstarts/excel-quickstart-jquery.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by mscharlock** [comment]
Hi @stavidawg- Thanks for trying out Office Add-ins and apologies that you've run into an issue. Thanks for reporting it! I have just tried to reproduce your issue but as of yet haven't been able to. I'll go ahead and flag this for my team though and see if collectively we can repro it and get back to you.

**Comment by davidchesnut** [comment]
Hi @stavidawg Is it possible maybe add-ins got disabled? You can check by:
1. Go to File > Options
2. Choose **Trust Center** (left side), then **Trust Center Settings** button.
3. Choose **Trusted Add-in Catalogs** (left side).
There's a checkbox **Don't allow any web add-ins to start.** Be sure it is unchecked.

Cheers,
David

**Comment by mscharlock** [comment]
Hi @stavidawg - just wanted to check to see if you were able to troubleshoot using the steps given by @davidchesnut? Let us know when you get a chance. Thanks!

**Comment by mscharlock** [comment]
Hi @stavidawg - let us know if you need any other assistance. I'm going to go ahead and close this issue but feel free to comment on the thread again and then I will reopen it if you need. Thanks!
