### ISSUE TITLE
How Long before this is GA?

### ISSUE THREAD

**Issue by GermanEZI** [OfficeDev/office-js-docs-pr#1164]
This would prove very useful for our group.   Do you have a general idea of when this will be ready?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb06c24b-9d11-9cc5-2e98-561601452638
* Version Independent ID: abda21d9-6e80-8319-c56f-004658014e3c
* Content: [Enable single sign-on for Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/sso-in-office-add-ins#feedback)
* Content Source: [docs/develop/sso-in-office-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/sso-in-office-add-ins.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @GermanEZI,
We're glad you're eager to use SSO. I don't think we have an official timeline for the GA of this feature. Tagging @Rick-Kirkham to see if he has any insight.

**Comment by Rick-Kirkham** [comment]
At one time it was scheduled for the period July - September, 2019, but it has been delayed before and could be again.

**Comment by bhushanshelke** [comment]
Delayed again?

**Comment by ArriaGitHub** [comment]
Do you have an updated timeline for the GA?

**Comment by saberone** [comment]
But this is quite important functionality, right? No SSO really degrades the user experience. Making the user login twice doesn't help with people adapting the new functionality.

**Comment by Rick-Kirkham** [comment]
@ArriaGitHub @saberone It is still in preview. The last estimate I heard for when it will release was the 2nd quarter of 2020.
