### ISSUE TITLE
Sample Codebase

### ISSUE THREAD

**Issue by acds** [OfficeDev/office-js-docs-pr#1177]
Hi, it would be good if the built codebase was available in a git repo such that we can compare if our steps (as followed) match that of the instructions...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea230e95-f483-6d19-8167-2341a03cf396
* Version Independent ID: 3846765f-7587-fec4-711e-84edfce9c30c
* Content: [Build an Excel task pane add-in using Vue - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-vue#feedback)
* Content Source: [docs/quickstarts/excel-quickstart-vue.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/quickstarts/excel-quickstart-vue.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by kbrandl** [comment]
@acds thanks for the feedback, I can see how this would be helpful. It's not currently our standard process to create a GitHub repo for each of the Office Add-ins quick starts, but we'll keep this suggestion in mind as we continue to evolve the quick starts in the days ahead.
