### ISSUE TITLE
using-motion-office-addins.md animations link redirects to non-existing page

### ISSUE THREAD

**Issue by lisli1** [OfficeDev/office-js-docs-pr#1189]
## Article URL

https://docs.microsoft.com/en-us/office/dev/add-ins/design/using-motion-office-addins

## Issue

The Fabric animations links under `Use expected motions` and `See also` redirect to https://developer.microsoft.com/en-us/fabric#/styles/web/motions, which doesn't exist. However, the page https://developer.microsoft.com/en-us/fabric#/styles/web/motion **does** exist (no 's' after 'motion'). Should the URL redirection be updated to link to the latter?

**Comment by ElizabethSamuel-MSFT** [comment]
@lisli1 Thanks for pointing this out. We'll update this. Thanks!

**Comment by ElizabethSamuel-MSFT** [comment]
@lisli1 This issue has been fixed and should be go live soon (likely next week). I'll go ahead and close this now.

Thanks.

**Comment by lisli1** [comment]
Thanks!
