### ISSUE TITLE
office-toolbox validation doesn't match sideloading validation for Office Web

### ISSUE THREAD

**Issue by plmayfield** [OfficeDev/office-js-docs-pr#1196]
My manifest will pass the office-toolbox validation described on this page. However, when I try to sideload the same manifest using Excel Web, it returns "Your add-in manifest is not valid". Note that my manifest also passes the validator built into Visual Stuido. Additionally, when trying to validate against a schema using xmllint, it returns "Schemas parser error : The XML document 'OfficeAppManifestV1_1.xsd' is not a schema document. WXS schema OfficeAppManifestV1_1.xsd failed to compile".

It is frustrating that my manifest can pass two methods of validation but fail when trying to sideload to Excel Web. Additionally, the error "Your addin manifest is not valid" is not helpful in rooting out the problem. Additionally, the documentation is then with regard to which schema should be used from https://github.com/OfficeDev/office-js-docs-pr/tree/master/docs/overview/schemas. I've read the documentation on github and I can't even find a reference to which schema should be used for each type of application. 

I've documented this at https://stackoverflow.com/questions/57136595/manifest-file-passes-visual-studio-test-but-fails-when-side-loading-to-office-we but thus far, I haven't received any helpful suggestions. My boss has given me till the end of this week to resolve this, if I can't he is going to make me rewrite the entire function for Google Sheets, which I really don't want to do. Any help would be appreciated. 

The following would be helpful.
1. A single document which specifies all the tags in the manifest, what they are for, are they required or optional, and what order (major issue right now) they must be in. 
2. Common validation of manifest between Visual Studio, office-toolbox, etc. 
3. Documentation on github or this page for which schema should be used for each type of addin. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a89c40a2-3e90-a295-7375-6d52ba597808
* Version Independent ID: 8cd2f086-5c18-ee17-9ced-ffeba1de0b78
* Content: [Validate and troubleshoot issues with your manifest - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/troubleshoot-manifest)
* Content Source: [docs/testing/troubleshoot-manifest.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/troubleshoot-manifest.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@plmayfield Sorry to hear that you're facing issues with this. The following are some links that I hope are helpful or point you in the right direction.

[Office Add-ins XML manifest](https://docs.microsoft.com/office/dev/add-ins/develop/add-in-manifests?tabs=tabid-1)
[How to find the proper order of manifest elements](https://docs.microsoft.com/office/dev/add-ins/develop/manifest-element-ordering)

We'll take a look at the lack of validation consistency across these areas.

Thanks for raising this!

**Comment by ElizabethSamuel-MSFT** [comment]
For internal folks, the item tracking validation inconsistency is OC\OPX\Content 3508629

**Comment by plmayfield** [comment]
Elizabeth,

Thank you for your response, but I believe the problem is more severe than you think. The schema TaskPaneAppVersionOverridesV1_0.xsd from doesn’t appear to be valid. Below are screen shots of both xmllint and W3C XSD Validation. They both fail to validate the schema file. Note that this has nothing to do with the xml, the schema itself is failing.

An example of the problem is in line 9 of TaskPaneAppVersionOverridesV1_0.xsd. It references the url http://schemas.microsoft.com/office/officeappbasictypes/1.0. When I try to load that url, my browser reports “The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.” If you read the screen shots below both xmllint and W3C are having the same problem. I tried https with the same link to no avail.

OfficeAppBasicTypesV1_0.xsd and OfficeAppBasicTypesV1_0.xsd also do not validate.  Is it possible that this schema problem is why my manifest is being rejected by Excel Web?

My problem is pretty obvious. How do I validate my xml when 2 of the 3 methods to validate (Visual studio and npx with office-toolbox) and the third method, validation against a schema, won’t work as the schema’s are invalid?



Xmllint errors
[cid:image002.png@01D54165.749398F0]

W3C XML Errors
[cid:image001.png@01D54164.38979190]



Best Regards,

Philip Mayfield

**Comment by ElizabethSamuel-MSFT** [comment]
@plmayfield Thanks for sharing this additional information about the schemas. However, could you include the errors images directly in GitHub? I think you added them by replying to the email but they don't show in the GitHub issue UI.

Also, could you share your manifest (or some version that you can safely share) so that we can also work on getting you unblocked while we get the larger issues resolved?

Thanks.

**Comment by plmayfield** [comment]
I posted it at https://github.com/OfficeDev/office-js/issues/635

I may have found two bugs. See ...
https://stackoverflow.com/questions/57169164/showheaders-false-results-in-unexpected-table-range-using-javascript
https://stackoverflow.com/questions/57172497/setsolidcolor-throwing-unexpected-error-in-excel-javascript-on-chart-series

Best Regards,

Philip Mayfield

**Comment by ElizabethSamuel-MSFT** [comment]
@plmayfield Thanks for taking the time to report these bugs and issues. I'll go ahead and close this. Depending on the resolution of the related issues, we'll update the documentation accordingly.

If you have any further questions on this, let us know and we can reopen this issue.

Thanks.
