### ISSUE TITLE
[Web Requests] Why no "Content-Type": "application/json" header?

### ISSUE THREAD

**Issue by danielgwilson** [OfficeDev/office-js-docs-pr#1200]
The docs say:

> You can also use a Content-Type header in simple CORS, provided that the content type is application/x-www-form-urlencoded, text/plain, or multipart/form-data.

Why can't Custom Functions accept "Content-Type": "application/json" headers? Sending JSON request bodies is the preferred web standards format.

https://stackoverflow.com/questions/477816/what-is-the-correct-json-content-type

**Comment by danielgwilson** [comment]
@keyur32

**Comment by keyur32** [comment]
Not yet implemented: https://github.com/OfficeDev/office-js/issues/523

**Comment by Reezaali** [comment]
@danielgwilson - since this isn't implemented yet, I'm going to go ahead and close this issue. If you'd like me to reopen it, let me know. Thanks!
