### ISSUE TITLE
Office.displayWebDialogOptions(...) should be OfficeRuntime.displayWebDialog(...)

### ISSUE THREAD

**Issue by danielgwilson** [OfficeDev/office-js-docs-pr#1201]
`Office.displayWebDialogOptions(...)` should be `OfficeRuntime.displayWebDialog(...)`.
https://docs.microsoft.com/en-us/javascript/api/office-runtime?view=office-js

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3437fe77-0051-1f7d-2131-770da0486e60
* Version Independent ID: 2221a38e-496e-f042-d5a4-ac6b95af6dff
* Content: [Display a dialog box from a custom function - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-dialog)
* Content Source: [docs/excel/custom-functions-dialog.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/custom-functions-dialog.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Fixed with PR #1205. Thanks for the contribution! 

The fix will be merged into the live branch soon. I'll close the issue.
