### ISSUE TITLE
[LOC] There is more than 3k broken links

### ISSUE THREAD

**Issue by OfficeGlobal** [OfficeDev/office-js-docs-pr#1203]
There is more than 3k broken links in source topics based on our cats testing [here](https://contentqacats.azurewebsites.net/CheckResults/2019072400063/Report/).
We have exported the links to excel. Could you please go through the attached excel and fix the broken links ?
[ResultFor[2019072400063].2953.xlsx](https://github.com/OfficeDev/office-js-docs-pr/files/3435352/ResultFor.2019072400063.2953.xlsx)

Thank you.

**Comment by kbrandl** [comment]
FYI @AlexJerabek -- all of these 'broken' links (pointing to Excel API reference articles) exist within the various Excel requirement sets articles of **office-js-docs-pr**. The last CATS report I reviewed (a few weeks ago) didn't report any of these broken links, so seems like this is a new issue introduced fairly recently.

**Comment by AlexJerabek** [comment]
This was addressed with #1204. Thanks for reporting the broken links. Closing the issue.
