### ISSUE TITLE
Page is incredibly dense making it hard to find desired info

### ISSUE THREAD

**Issue by danielgwilson** [OfficeDev/office-js-docs-pr#1218]
This is a very useful primary reference for Dialog API topics. However, it is 4078 words on a single page.

Perhaps there's a better way to break this up into a top level document directing readers to subpages based on what they're looking for?

E.g.

---

Dialog API

The Dialog API allows you to display a popup dialog window in your Add-in. This is especially useful for auth scenarios.

Useful links:
- Dialog API reference
- Dialog Options reference (does this have to be a separate page?)
- Dialog API scenarios
- Handling errors and events
- Passing information to the dialog box
- Using the Dialog API for authentication
- Using the Dialog API with single-page applications and client-side routing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a714626a-058a-789e-6add-5e9dfb21fd1f
* Version Independent ID: 1b88a28c-fc36-4518-2808-7246f08d9753
* Content: [Use the Dialog API in your Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins)
* Content Source: [docs/develop/dialog-api-in-office-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/dialog-api-in-office-add-ins.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by mscharlock** [comment]
Hi @danielgwilson - Thanks for the feedback - totally agree on the length. We'll have a look as a docs team and see if we can get this on the backlog. Incidentally, are you still the PM who would be the right person to contact should we need to clarify anything RE: Dialog? Thanks. :)

**Comment by mscharlock** [comment]
Wanted to let you know that we've put this on our backlog, captured under VSO item 3543685. For now, I'll close this issue but let me know if you would like me to re-open.
