### ISSUE TITLE
How to creat simple project typescript?

### ISSUE THREAD

**Issue by TheGridLock** [OfficeDev/office-js-docs-pr#1231]
in fact i think typescript Suitable for custom functions than js but in this page, You give an example of using ts to create functions that are too difficult to understand. It's too long for beginners to do.
Thanks!

---
#### Chi tiết tài liệu

⚠ *Không chỉnh sửa phần này. Điều này là bắt buộc cho docs.microsoft.com ➟ Vấn đề khi liên kết GitHub.*

* ID: b83cf91a-6bc9-3adc-67cc-d2c6bd6e6cdd
* Version Independent ID: 97b920fa-e705-5041-d6c0-870179013e2f
* Content: [Batching custom function calls for a remote service - Office Add-ins](https://docs.microsoft.com/vi-vn/office/dev/add-ins/excel/custom-functions-batching#feedback)
* Content Source: [docs/excel/custom-functions-batching.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/custom-functions-batching.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by wamaina** [comment]
Thanks @TheGridLock for your feedback!

@mscharlock, we have a request for a smaller example. Could you please follow-up?

**Comment by mscharlock** [comment]
Thanks for the request, definitely great to get feedback on what is working or not working for people - I can put this on our backlog for the upcoming quarter. :)

**Comment by mscharlock** [comment]
Ok, this is on the backlog under VSO item 3543291. In the meantime, I'm going to close this issue for now while we work on it, but I can also go ahead and update this issue when we publish a new sample if you'd like. If you have other concerns in the meantime, @TheGridLock, go ahead and comment on this issue and I can re-open it. Thanks!
