### ISSUE TITLE
how to host excel add-in?

### ISSUE THREAD

**Issue by Ballzer0** [OfficeDev/office-js-docs-pr#1232]
I have used Yoman generator to generate an excel task pane add-in. I have spent considerable time writing this add-in and i cant seem to find a guide for how to host a project generated by the "yo office" command

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a6812c3-fbf6-1a89-6305-8da71f83b5a3
* Version Independent ID: 614c2c5a-f3e7-fa28-6e4a-8ad68634c0d9
* Content: [Host an Office Add-in on Microsoft Azure - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/publish/host-an-office-add-in-on-microsoft-azure)
* Content Source: [docs/publish/host-an-office-add-in-on-microsoft-azure.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/publish/host-an-office-add-in-on-microsoft-azure.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
An Office add-in created with Yo Office is just a node.js based web application. It can be hosted like any other node web app. I recommend that you search for "How to host node app on Azure" in your favorite search engine.
