### ISSUE TITLE
Still in preview?

### ISSUE THREAD

**Issue by Joel-Intact** [OfficeDev/office-js-docs-pr#1233]
Hi, is this still in preview?  Any word on a official release date?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c51a742c-4ddb-dd5e-7f67-3242a158378a
* Version Independent ID: b5d96164-bec6-7732-79ad-8c6beef7e0c4
* Content: [Create a Node.js Office Add-in that uses single sign-on - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/create-sso-office-add-ins-nodejs)
* Content Source: [docs/develop/create-sso-office-add-ins-nodejs.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/create-sso-office-add-ins-nodejs.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by niteshgolchha85** [comment]
@Joel-Intact Thanks for your patience. We are actively working to GA SSO API. May I know how do you plan to use the SSO API? Do you need it to access Graph? Also, how do your users expect to get your add-in - via store or centralized deployment?

**Comment by Joel-Intact** [comment]
Hi @niteshgolchha85, thanks for responding to my inquiry.  It's good to hear that this is being actively worked on!  We're planning on using the SSO API to get an access token for the logged on user, and call our web services to send/receive data.  For Graph, I would just call the "me" endpoint passing the token to get data.  For deployment, both, mostly store and centralized deployment for clients with restrictions.

**Comment by niteshgolchha85** [comment]
Thanks @Joel-Intact for the info. As I've mentioned earlier, I do not have a specific date yet but we'll make a public announcement once we plan to go GA
