### ISSUE TITLE
Guidelines for supporting environment-specific values in an add-in's manifest.xml

### ISSUE THREAD

**Issue by jaebradley** [OfficeDev/office-js-docs-pr#1236]
When side-loading an add-in in a local environment, the values in the `manifest.xml` might be specific to that local environment (e.g. the `IconUrl` has a default value that is points to a `localhost` url or the set of `AppDomain`s may change).

Do you have a recommended way of supporting these differences? Is it to support potentially multiple `manifest.xml`s?

**Comment by wamaina** [comment]
Hi @jaebradley,

Thank you for reaching out! It would be helpful to gain a little more understanding around your scenario. In the case described above, is the question around the recommendation between using a manifest for developing vs. when the add-in is complete and you want to move to a production version? Or is that not the challenge in your scenario?

**Comment by jaebradley** [comment]
@wamaina sorry, I should've been more specific!

I think my question is around if there's a best practice for supporting both local development as well as deploying a production add-in when it comes to the `manifest.xml` file.

It seems to me (and I could definitely be missing something) that in order to support local feature development as well as supporting publishing a production add-in that one would have two `xml` files (like a `manifest.local.xml` and then a `manifest.xml`).

This way, local add-in feature development could leverage a locally running server, for example.

**Comment by Rick-Kirkham** [comment]
Yes. You need multiple manifests. Typically, add-ins are developed with a localhost server. When put in production, the URLs in the manifest must change to match the production server. The changed manifest is uploaded to AppSource or a corporate catalog or some other publication point. You can maintain two manifests and keep one for development with a localhost server. Does this answer your question?

**Comment by jaebradley** [comment]
@Rick-Kirkham thanks for verifying! 

And are there any best practices you can share about supporting multiple manifest files? 

Do you keep a template for the underlying XML and then dynamically build the relevant `manifest.xml` file depending on the environment / environment variables?

Or generally, are the changes usually infrequent enough / easy enough to diff that it's not worth the time to do this type of dynamic generation?

**Comment by Rick-Kirkham** [comment]
To be honest, I think our docs assume that development completes and only then do you go to production, after changing the URLs in the manifest. We further assume that when you're ready to develop Vnext, you make a branch/fork of the project and change the manifest URLs back to localhost. So, you're always working with just one manifest. So, we don't have any best practices for maintaining two manifests. But I definitely think that the changes are too infrequent to justify automating them.

**Comment by jaebradley** [comment]
@Rick-Kirkham thanks for sharing, I'll close this issue!
