### ISSUE TITLE
Vue example uses the deprecated vue-cli

### ISSUE THREAD

**Issue by SimonSiefke** [OfficeDev/office-js-docs-pr#1239]
It would be great if the Vue example could be updated to use `@vue/cli` instead of the deprecated `vue-cli`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea230e95-f483-6d19-8167-2341a03cf396
* Version Independent ID: 3846765f-7587-fec4-711e-84edfce9c30c
* Content: [Build an Excel task pane add-in using Vue - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-vue)
* Content Source: [docs/quickstarts/excel-quickstart-vue.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/quickstarts/excel-quickstart-vue.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
Good idea. I'll create a work item for this. In the meantime, if it is an easy fix and you know how to do it, you're welcome to submit a pull request with the needed changes. 
Internal item number is OC 3550303.
