### ISSUE TITLE
How can I change the embedded browser loaded in Outlook desktop?

### ISSUE THREAD

**Issue by yanli0303** [OfficeDev/office-js-docs-pr#1254]
Through a terminal command, or registry?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00c430f1-bbf5-53b8-a225-4fbe8fc39c3b
* Version Independent ID: 0a069a0d-4d35-71ee-53af-8c55fe8548a0
* Content: [Browsers used by Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins)
* Content Source: [docs/concepts/browsers-used-by-office-web-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/concepts/browsers-used-by-office-web-add-ins.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by kbrandl** [comment]
@yanli0303 thanks for your interest in Office Add-ins development! It's not possible for you to control which browser an Office client uses to render an Office Add-in; the browser used will always be determined automatically depending on the operating system / platform where the add-in is running (per the information in this article).
