### ISSUE TITLE
We can't open this add-in from localhost

### ISSUE THREAD

**Issue by imba-tjd** [OfficeDev/office-js-docs-pr#1256]
I'm following the node.js version, but I got that message. And I'm not using Fiddler.

![图片](https://user-images.githubusercontent.com/24759802/63329493-a42bf180-c364-11e9-8790-eb1de2229628.png)

<details>
<summary>node.js log</summary>

```
You already have trusted access to https://localhost.
Certificate: C:\Users\xxx\.office-addin-dev-certs\localhost.crt
Key: C:\Users\xxx\.office-addin-dev-certs\localhost.key
i ｢wds｣: Project is running at https://localhost:3000/
i ｢wds｣: webpack output is served from /
i ｢wds｣: Content not from webpack is served from D:\test\my-office-add-in
i ｢wdm｣: Hash: 4b364c2005b7680ad9f4
Version: webpack 4.35.3
Time: 1873ms
Built at: 2019-08-20 16:01:58
                               Asset       Size    Chunks             Chunk Names
7f313c06a52dabe7267420021403d038.png   11.6 KiB            [emitted]
                       commands.html  519 bytes            [emitted]
                         commands.js    346 KiB  commands  [emitted]  commands
                     commands.js.map    397 KiB  commands  [emitted]  commands
                         polyfill.js    743 KiB  polyfill  [emitted]  polyfill
                     polyfill.js.map    713 KiB  polyfill  [emitted]  polyfill
                        taskpane.css   1.48 KiB            [emitted]
                       taskpane.html   2.56 KiB            [emitted]
                         taskpane.js    348 KiB  taskpane  [emitted]  taskpane
                     taskpane.js.map    397 KiB  taskpane  [emitted]  taskpane
Entrypoint polyfill = polyfill.js polyfill.js.map
Entrypoint taskpane = taskpane.js taskpane.js.map
Entrypoint commands = commands.js commands.js.map
[0] multi (webpack)-dev-server/client?https://localhost:3000 @babel/polyfill 40 bytes {polyfill} [built]
[1] multi (webpack)-dev-server/client?https://localhost:3000 ./src/taskpane/taskpane.js 40 bytes {taskpane} [built]
[2] multi (webpack)-dev-server/client?https://localhost:3000 ./src/commands/commands.js 40 bytes {commands} [built]
[./node_modules/@babel/polyfill/lib/index.js] 678 bytes {polyfill} [built]
[./node_modules/@babel/polyfill/lib/noConflict.js] 567 bytes {polyfill} [built]
[./node_modules/core-js/library/fn/global.js] 87 bytes {polyfill} [built]
[./node_modules/strip-ansi/index.js] 161 bytes {polyfill} {taskpane} {commands} [built]
[./node_modules/webpack-dev-server/client/index.js?https://localhost:3000] (webpack)-dev-server/client?https://localhost:3000 4.29 KiB {polyfill} {taskpane} {commands} [built]
[./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.51 KiB {polyfill} {taskpane} {commands} [built]
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.53 KiB {polyfill} {taskpane} {commands} [built]
[./node_modules/webpack-dev-server/client/utils/createSocketUrl.js] (webpack)-dev-server/client/utils/createSocketUrl.js 2.77 KiB {polyfill} {taskpane} {commands} [built]
[./node_modules/webpack-dev-server/client/utils/log.js] (webpack)-dev-server/client/utils/log.js 964 bytes {polyfill} {taskpane} {commands} [built]
[./node_modules/webpack-dev-server/client/utils/reloadApp.js] (webpack)-dev-server/client/utils/reloadApp.js 1.63 KiB {polyfill} {taskpane} {commands} [built]
[./src/commands/commands.js] 1.02 KiB {commands} [built]
[./src/taskpane/taskpane.js] 2.79 KiB {taskpane} [built]
    + 328 hidden modules
Child html-webpack-plugin for "commands.html":
     1 asset
    Entrypoint undefined = commands.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./src/commands/commands.html] 450 bytes {0} [built]
Child html-webpack-plugin for "taskpane.html":
                                   Asset      Size  Chunks             Chunk Names
    7f313c06a52dabe7267420021403d038.png  11.6 KiB          [emitted]
     + 1 hidden asset
    Entrypoint undefined = taskpane.html
    [./assets/logo-filled.png] 82 bytes {0} [built]
    [./node_modules/html-webpack-plugin/lib/loader.js!./src/taskpane/taskpane.html] 2.61 KiB {0} [built]
i ｢wdm｣: Compiled successfully.
```
</details>

---

Besides, I found when the folder contains white-spaces, the program fails. Although you have pointed out that `What do you want to name your add-in?` needs to be `my-office-add-in`, it frustrate me that the default name `My Office Add-in` won't work and you didn't mention about it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77e380a7-6e2e-ada8-d297-3fd5018a1958
* Version Independent ID: f23490e8-6eeb-f2d5-6c94-69e3c9ed83f4
* Content: [Build your first Word task pane add-in - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/word-quickstart?tabs=yeomangenerator)
* Content Source: [docs/quickstarts/word-quickstart.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/quickstarts/word-quickstart.md)
* Product: **word**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @imba-tjd, 
I'm sorry this problem frustrated you. The project name spacing issue is being tracked by the Yeoman Generator team with issue https://github.com/OfficeDev/generator-office/issues/476. I'll tag @TCourtneyOwen for awareness. Perhaps we can change the default project name if the fix for 476 requires significant investment.

**Comment by kbrandl** [comment]
@imba-tjd we're working on a fix for https://github.com/OfficeDev/generator-office/issues/476 and it should be released very soon. 

(FYI @TCourtneyOwen, the dev who's fixing this problem with Yo Office not permitting spaces in the project name or folder path)

**Comment by kbrandl** [comment]
@TCourtneyOwen I was just able to create an Excel add-in (using Yo Office 1.3.0) where the project name (folder path) contains spaces, and was able to start the add-in successfully. Correct to assume that you've fixed the issue described above, and project name (folder path) can now contain spaces? Please let me know; I'll need to update the docs (to remove the note I added about the issue) if the problem's been resolved. Thanks!

**Comment by TCourtneyOwen** [comment]
Yes that was fixed in the project repos and not in Yo Office itself
