### ISSUE TITLE
Schema location only shows examples for Outlook add-ins

### ISSUE THREAD

**Issue by AbidRahman-MSFT** [OfficeDev/office-js-docs-pr#1261]
The 'xmlns' attribute's description states that the schema location must be:

- 'http://schemas.microsoft.com/office/mailappversionoverrides' or
- 'http://schemas.microsoft.com/office/mailappversionoverrides/1.1' 

However, the schema location can be different for task pane add-ins and content add-ins. For eg. for a content add-in:

- 'http://schemas.microsoft.com/office/contentappversionoverrides/1.1' is a valid schema location.

We should include all of the different schema locations into the description of the attribute. A list can be found here of some of the different schema locations (Note: this may not include ALL of the possible schema locations): https://docs.microsoft.com/en-us/openspecs/office_file_formats/ms-owemxml/c6a06390-34b8-4b42-82eb-b28be12494a8

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9caa983-63bf-9ec7-6885-acc576f18747
* Version Independent ID: b7f72393-be3e-3237-7b2c-b43dc26a2061
* Content: [VersionOverrides element in the manifest file - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/versionoverrides#feedback)
* Content Source: [docs/reference/manifest/versionoverrides.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/manifest/versionoverrides.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
Thanks for pointing this out. I've created a work item: OC 3572980.
I'll close this issue since we are tracking the work internally.

**Comment by Rick-Kirkham** [comment]
This is fixed and the fixed page will be public tonight in Pacific Time Zone.
