### ISSUE TITLE
Sideloading URL feels like its going to the wrong page, Network Share

### ISSUE THREAD

**Issue by David-Tennant** [OfficeDev/office-js-docs-pr#1281]
https://docs.microsoft.com/en-us/office/dev/add-ins/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins

![Screen Shot 2019-09-03 at 16 04 42](https://user-images.githubusercontent.com/40059359/64180206-af9f1280-ce64-11e9-9243-7e390fd78d20.png)

| Method        | URL                                                                                                                                    |
| ------------- | -------------------------------------------------------------------------------------------------------------------------------------- |
| Sideloading   | `https://docs.microsoft.com/en-us/office/dev/add-ins/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins` |
| Network Share | `https://docs.microsoft.com/en-us/office/dev/add-ins/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins` |

When browsing the different publishing sections I noticed the Method `Sideloading` and `Network share` are the same going to the same URL. This is fine when clicking Network Share but when clicking Sideloading you feel that you clicked on the wrong link because the sideloading section is on the same page as network share, but off the screen at the bottom.

Can link to the header or possibly split the page.

`https://docs.microsoft.com/en-us/office/dev/add-ins/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins#sideload-your-add-in`

When browsing the different publishing sections I noticed path Links are going to the same URL. This is fine when clicking Network Share but when clicking Sideloading you feel that you clicked on the wrong link because the sideloading is on the same page as network share at the bottom.

Can link to the header or split the page.

`https://docs.microsoft.com/en-us/office/dev/add-ins/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins#sideload-your-add-in`
 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2677af5b-e9b8-f962-25ce-8aa285977c90
* Version Independent ID: c31c7ed9-0a0a-7a65-0d1b-70d6a8b33994
* Content: [Deploy and publish your Office Add-in - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/publish/publish#outlook-add-in-deployment)
* Content Source: [docs/publish/publish.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/publish/publish.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@David-Tennant Thanks for raising this issue. I've recommended a different page in your PR which I believe will help resolve this issue.

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@David-Tennant, I've merged the PR to master and the changes should be published soon.

Thanks again for raising this issue and taking the time to fix it.
