### ISSUE TITLE
Publishing on Mac

### ISSUE THREAD

**Issue by Radzell** [OfficeDev/office-js-docs-pr#1285]
How do I publish an add-in that was created on a mac?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2677af5b-e9b8-f962-25ce-8aa285977c90
* Version Independent ID: c31c7ed9-0a0a-7a65-0d1b-70d6a8b33994
* Content: [Deploy and publish your Office Add-in - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/publish/publish#feedback)
* Content Source: [docs/publish/publish.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/publish/publish.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
This article applies regardless of what kind of computer the add-in was created on.

**Comment by Radzell** [comment]
There doesn't seem to be office-js projects on visual studio for mac so how is this true?

**Comment by Rick-Kirkham** [comment]
Regardless of what kind of computer that you use to develop the add-in, when you have completed the add-in and are ready to publish it, you can host it on a web site and you can distribute the add-in's manifest in any of the ways described in the article.
