### ISSUE TITLE
fetch is undefined

### ISSUE THREAD

**Issue by g8up** [OfficeDev/office-js-docs-pr#1296]
Excel (1908)
I make a request use fetch() API, and got this issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 667d1e98-4a95-318f-0df1-182722370ac8
* Version Independent ID: f8265387-ba9d-a5db-ef44-8409441b2ece
* Content: [Receive and handle data with custom functions - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-web-reqs#feedback)
* Content Source: [docs/excel/custom-functions-web-reqs.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/custom-functions-web-reqs.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
We use the issues in this repo to track errors in the documentation. Please raise technical issues like this on StackOverflow. Be sure to tag your question `office-js`. Thanks.
