### ISSUE TITLE
Error: Unable to delete registry value "C:\Users\me\fodler\addin\manifest.xml" in key "HKCU\SOFTWARE\Microsoft\Office\16.0\Wef\Developer".

### ISSUE THREAD

**Issue by vmellos** [OfficeDev/office-js-docs-pr#1297]
Hello folks,

I followed the tutorial "Build an Excel task pane add-in", but when execute command ```npm start```,  I get this error:

Error: Unable to delete registry value "C:\Users\me\folder\addin\manifest.xml" in key "HKCU\SOFTWARE\Microsoft\Office\16.0\Wef\Developer".

Can you help me?

## Article URL

https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-jquery?tabs=yeomangenerator

**Comment by AlexJerabek** [comment]
Hi @vmellos,
Thanks for reporting this. I was unable to repro the issue. Could you please provide some information about your environment?

- Office version number: 
- Operating System: 
- Browser (if using Office Online):

**Comment by vmellos** [comment]
Hey @AlexJerabek ,

Thank you for the quick reply, but I have done addin with another tutorial.

* Office version number: Version 1902 - Build 11328.20392
* Operating System: Windows 10 64 bits
* Browser (if using Office Online): Edge and Chrome

**Comment by AlexJerabek** [comment]
@vmellos Glad to hear you're unblocked. If you encounter any other issues, pleae let us know. In the meantime, I'll keep trying to repro your issue.
