### ISSUE TITLE
MacOS Excel - After Inspect Element - error that Javascript is not enabled

### ISSUE THREAD

**Issue by acds** [OfficeDev/office-js-docs-pr#1300]
Per instruction here, I Inspect Element and get this....

I assume that Excel is running Safari in the IFrame (per docs), and for Safari Javascript is enabled.

I am running version 16.29 (19090802) on MacOS 10.14.6.
 
Perhaps the solution can also be posed to here https://docs.microsoft.com/en-us/office/dev/add-ins/testing/testing-and-troubleshooting for others.

Here is the error in the inspect window:
&lt;noscript&gt;
      &lt;strong&gt;We're sorry but my-add-in doesn't work properly without JavaScript enabled. Please enable it to continue.&lt;/strong&gt;
&lt;/noscript&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be179784-5839-3e8f-c131-1f4d89808b03
* Version Independent ID: 69bca101-91a2-3a5e-5177-493723504354
* Content: [Debug Office Add-ins on a Mac - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-office-add-ins-on-ipad-and-mac)
* Content Source: [docs/testing/debug-office-add-ins-on-ipad-and-mac.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/debug-office-add-ins-on-ipad-and-mac.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @acds,
It seems like the embedded version of Safari still has JavaScript disabled. Are you encountering these problems using Excel on the Web in your Safari browser?
