### ISSUE TITLE
How long are add-in manifests cached?

### ISSUE THREAD

**Issue by mattblodgett** [OfficeDev/office-js-docs-pr#1302]
## Article URL

https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/troubleshoot-manifest.md#clear-the-office-cache

## Issue

In the article above you describe how a user can delete the contents of their "Office cache" so to force re-download of an add-in manifest.

Is this "Office cache" periodically invalidated or purged on any kind of reliable schedule? In other words, how long are manifests persisted in the cache assuming no one has manually deleted them?

%LOCALAPPDATA%\Microsoft\Office\16.0\Wef\

**Comment by Rick-Kirkham** [comment]
The issues for this repo are meant to track problems with the documentation. For technical questions like this, please raise the question on Stack Oveflow where more knowledgeable people will see the question and the whole community can benefit from the answers that you get. Be sure to tag the question `office-js`.
