### ISSUE TITLE
When will the promise-based APIs be available for Outlook?

### ISSUE THREAD

**Issue by vijaypemmaraju** [OfficeDev/office-js-docs-pr#1305]
According to the docs, the promise-based API is currently only supported in Word and Excel. Are there any plans to implement this in Outlook? If so, is there a timeline for that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c223d75-70f3-ccdc-0137-4fc1a2aa885f
* Version Independent ID: c55660a6-136b-ef66-8be4-f7bf3b2968c1
* Content: [Asynchronous programming in Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/asynchronous-programming-in-office-add-ins#feedback)
* Content Source: [docs/develop/asynchronous-programming-in-office-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/asynchronous-programming-in-office-add-ins.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @vijaypemmaraju, 
Thanks for your question. Outlook currently only supports the callback model, not the promise-based model Excel and Word use. We have no concrete plans to switch Outlook to this model, but we will if there is enough interest from the community. To help influence that discussion, please head over to [UserVoice](https://officespdev.uservoice.com/). There, you can ask for promise-based Outlook APIs (or upvote an existing request).
