### ISSUE TITLE
Links broken

### ISSUE THREAD

**Issue by hemarajuc** [OfficeDev/office-js-docs-pr#1306]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fd8034d-77a8-c0cf-3d32-50c65494f0c4
* Version Independent ID: da528529-e44e-e386-3300-585b8a455fc5
* Content: [Authorize to Microsoft Graph without SSO - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/authorize-to-microsoft-graph-without-sso)
* Content Source: [docs/develop/authorize-to-microsoft-graph-without-sso.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/authorize-to-microsoft-graph-without-sso.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by keyur32** [comment]
Hi @hemarajuc - can you clarify the broken link please? I could not see what was not working or what specific link? On test most seemed fine.

**Comment by AlexJerabek** [comment]
Looks like it's these two links:

- [Office Add-in Microsoft Graph ASP.NET](https://github.com/OfficeDev/office-add-in-microsoft-graph-aspnet)
- [Outlook Add-in Microsoft Graph ASP.NET](https://github.com/OfficeDev/outlook-add-in-microsoft-graph-aspnet)

@davidchesnut, do we know what happened to those repos? Should they be pointing to PnP samples instead?

**Comment by lindalu-MSFT** [comment]
Replaced broken link with new content to [Get started with Microsoft Graph and ASP.NET](https://developer.microsoft.com/en-us/graph/get-started/asp.net).

**Comment by Rick-Kirkham** [comment]
@AlexJerabek Yes. They were moved to PnP. I've fixed the URLs in Lindalu's PR.

**Comment by lindalu-MSFT** [comment]
@Rick-Kirkham Should I add these samples to the Gallery too for visibility? They don't seem to be easy to find.

**Comment by AlexJerabek** [comment]
For now, let's take the gallery discussion to email. 

@hemarajuc, This issue has been addressed with #1311. The updates should be on the live site soon. Thank you again for reporting the problem.

I'll close this issue. Please let us know if you encounter any other issues.
