### ISSUE TITLE
Visual Studio 2019 is missing the onready command

### ISSUE THREAD

**Issue by Physeos-sys** [OfficeDev/office-js-docs-pr#1314]

**Comment by AlexJerabek** [comment]
Hi @Physeos-sys, 
Sorry for the delay. @akrantz, is the state of the Visual Studio project something you can clarify here?

**Comment by Physeos-sys** [comment]
Replaced class with one from an example elsewhere and it was accepted. Unsure why it would'nt work when copied from another example.
