### ISSUE TITLE
Seems strange that getSelectedDataAsync requires write permissions. 

### ISSUE THREAD

**Issue by wandyezj** [OfficeDev/office-js-docs-pr#1322]
Why does an API that is only reading data require Write permissions?

getSelectedDataAsync(coercionType, [options], callback) → {String}

ReadWriteItem

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5087f99-2e9c-3074-53dc-8507da1e74a4
* Version Independent ID: b9a838b9-1136-a3f2-14cb-d89d4b8672c1
* Content: [Office.context.mailbox.item - requirement set 1.7 - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/objectmodel/requirement-set-1.7/office.context.mailbox.item#feedback)
* Content Source: [docs/reference/objectmodel/requirement-set-1.7/office.context.mailbox.item.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/objectmodel/requirement-set-1.7/office.context.mailbox.item.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@wandyezj Thanks for your question.

@exextoc Can you confirm the permissions for this API?

Thanks.

**Comment by exextoc** [comment]
Hi @ElizabethSamuel-MSFT & @wandyezj, this appears to be just a mistake in the documentation. This API appears to work fine with ReadItem permissions. @wandyezj Are you actually seeing an issue?

**Comment by ElizabethSamuel-MSFT** [comment]
@exextoc I'll work on updating the docs. Thx.

**Comment by ElizabethSamuel-MSFT** [comment]
@wandyezj The changes have been published. I'll close this now but if you're seeing an issue let us know.

Thanks.
