### ISSUE TITLE
No extension point for the calendar view in Outlook.

### ISSUE THREAD

**Issue by vinaymundada27** [OfficeDev/office-js-docs-pr#1326]
I would like to have an add-in visible only when we click on the calendar view in Outlook. But currently I don't see any extension point for that. Or am I missing anything here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06e092f1-aa6a-45b5-50ce-a1afca772776
* Version Independent ID: fa9c31b7-b63a-9867-f298-4d579b899c30
* Content: [ExtensionPoint element in the manifest file - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/extensionpoint#messagecomposecommandsurface)
* Content Source: [docs/reference/manifest/extensionpoint.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/manifest/extensionpoint.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for asking @vinaymundada27.
@exextoc Is this an available Outlook feature?

**Comment by exextoc** [comment]
Hi @vinaymundada27, There are 2 extension points for Calendar:

* [AppointmentAttendeeCommandSurface](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/manifest/extensionpoint.md#appointmentattendeecommandsurface), which shows when a user views a meeting that they are invited to.
* [AppointmentOrganizerCommandSurface](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/manifest/extensionpoint.md#appointmentorganizercommandsurface), which shows when a user views a meeting that they created.

If you have a different scenario that you'd like to request, you're welcome to suggest it on [our UserVoice](https://officespdev.uservoice.com/forums/224641-general/category/131778-outlook-add-ins).

**Comment by vinaymundada27** [comment]
Yes these ones I am aware of. But these extension points are when a user/organizer opens the appointment form/window. I am looking for an extension point wherein, the add-in button should appear on the top ribbon as soon as I switch from my mailbox to the calendar view in Outlook.

**Comment by exextoc** [comment]
This is not possible today. We track Outlook add-in feature requests on [our UserVoice](https://officespdev.uservoice.com/forums/224641-general/category/131778-outlook-add-ins). It looks like the feature you want has been requested by others already. Please upvote the [existing request](https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/35849557-outlook-add-in-command-button-on-calendar-overview). Feature requests on user-voice are considered when we go through our planning process.

**Comment by AlexJerabek** [comment]
Thanks @exextoc and @vinaymundada27. I'm going to close this issue, since it's a feature request, not a documentation issue. Please upvote the [UserVoice](https://officespdev.uservoice.com/forums/224641-general/category/131778-outlook-add-ins) request.

**Comment by samantharamon** [comment]
Hi, @Ayko1595. Thanks for reaching out. This feature hasn't been implemented. We now use the [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions) for feature requests. Please try to search for the previous request there and upvote it. If you're unable to find the request, select **Submit an Idea** to create a new feature request.
