### ISSUE TITLE
Doesnot Show up in Mac

### ISSUE THREAD

**Issue by BSaivamani** [OfficeDev/office-js-docs-pr#1338]

**Comment by AlexJerabek** [comment]
Hi @BSaivamani, 
Could you please clarify what does not show up on a Mac?

**Comment by BSaivamani** [comment]
I created a testaddin -I have started the server.

<img width="573" alt="Screen Shot 2019-10-02 at 10 10 27 AM" src="https://user-images.githubusercontent.com/56049952/66056616-0435bc00-e4fd-11e9-8f76-3a6f49845da8.png">

I can't get the admin to show up in word.
<img width="1391" alt="Screen Shot 2019-10-02 at 10 10 46 AM" src="https://user-images.githubusercontent.com/56049952/66056740-36dfb480-e4fd-11e9-8b50-542b2fe4d0ba.png">

**Comment by AlexJerabek** [comment]
Thank you @BSaivamani. 

On Mac, there's an extra step for running your server:
![image](https://user-images.githubusercontent.com/38896772/66065290-ecaa0380-e4fb-11e9-9fee-23ae510d7049.png)

Please check out the [Try it Out](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/word-quickstart?tabs=yeomangenerator#try-it-out) instructions and let us know if things still aren't working.

**Comment by BSaivamani** [comment]
I got it!Thank you
