### ISSUE TITLE
I do not see the "manage my add-ins" option

### ISSUE THREAD

**Issue by Larryngolog** [OfficeDev/office-js-docs-pr#1351]
I want to remove an add-in that I have added. Instead of the "Manage my add-ins" menu with "My account" and "Upload my add-in" I just see an option "Upload my add-in".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ab35128-1e97-c6ad-babc-f696f2e7b0fe
* Version Independent ID: cd1bacb1-14d7-a38d-321c-ebc2a526e03b
* Content: [Sideload Office Add-ins in Office on the web for testing - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/sideload-office-add-ins-for-testing)
* Content Source: [docs/testing/sideload-office-add-ins-for-testing.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/sideload-office-add-ins-for-testing.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
Sorry that you're having troubles removing the add-in. It will help our engineers if you can tell us whether you are using Office on the Web, Desktop Office (subscription), or Desktop Office (non-subscription). Also, what the OS and its build number. Thanks.

**Comment by Larryngolog** [comment]
Hi! The issue is in Office on the Web.

**Comment by Larryngolog** [comment]
I'm using Edge on Chromium Dev on Windows 10. Version of the Word on the Web is 16.0.12214.32654.
