### ISSUE TITLE
OneNote sideload for Mac?

### ISSUE THREAD

**Issue by AADeLucia** [OfficeDev/office-js-docs-pr#1354]
Is there a way to test a OneNote add-in for Mac locally? I only see documentation for Word, Excel, PowerPoint, and Outlook.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 589820d2-9925-dc5e-76a7-83921a569137
* Version Independent ID: ab8bde36-096f-81f3-f4d1-9b25fc69e6ee
* Content: [Sideload Office Add-ins on iPad and Mac for testing - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/sideload-an-office-add-in-on-ipad-and-mac#feedback)
* Content Source: [docs/testing/sideload-an-office-add-in-on-ipad-and-mac.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/sideload-an-office-add-in-on-ipad-and-mac.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AADeLucia** [comment]
Never mind, I just read https://docs.microsoft.com/en-us/office/dev/add-ins/testing/sideload-an-office-add-in-on-ipad-and-mac and learned the add-ins for OneNote are only available on the web (pity).

The "testing for OneNote" link should have a note before redirecting to the sideloading pages, it's misleading. I'm referring to the link on this page https://docs.microsoft.com/en-us/office/dev/add-ins/onenote/

**Comment by Rick-Kirkham** [comment]
This page does not say anything about where OneNote add-ins are available. I think you probably saw that on the following page: https://docs.microsoft.com/en-us/office/dev/add-ins/overview/office-add-in-availability

The page https://docs.microsoft.com/en-us/office/dev/add-ins/onenote/ is a kind of landing page, with very high level information. It would not be appropriate to have a note about availability there. I'll close this as not actionable. If you think it should be reopened, just ask.
