### ISSUE TITLE
We should put a link or statement on this page to let developers know that onSelectionChanged is unstable

### ISSUE THREAD

**Issue by tong-1324** [OfficeDev/office-js-docs-pr#1356]
We should put a link or statement on this page to let developers know that onSelectionChanged is unstable. Discussion about the issue is here: https://github.com/OfficeDev/office-js/issues/533. The event is not trigger in Excel win32 as expected. The even worse thing is that the issue can't be repro in any debug mode (sideload manifest or attach F12 developer). It means that there's no way for developers to capture this issue while developing/testing their app, but the issue will constantly repro in production. And again, when developers see the issue in production, because they can't debug it, it's extremely hard for them to find out the root cause is from this API. It's really a very bad experience for developers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52542c44-015a-746d-5d6f-c43f6e4e6774
* Version Independent ID: dfe8c9fb-4107-e19b-972a-c5a58eeb2646
* Content: [Work with Events using the Excel JavaScript API - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-events)
* Content Source: [docs/excel/excel-add-ins-events.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/excel-add-ins-events.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
As I understand it, the request is to add a note telling people that if they use `onSelectionChanged`, they should add `<script> MutationObserver=null; </script> ` to the `<head>` section of the home page. Let us know if that's not what you are asking.

**Comment by AlexJerabek** [comment]
@Rick-Kirkham That sounds like a good solution to me. I'll draft up a PR.

**Comment by AlexJerabek** [comment]
Fixed with #1358. @tong-1324 Please let us know when the note can be removed.
