### ISSUE TITLE
Publishing this office add-in to sharepoint app catalog

### ISSUE THREAD

**Issue by suoko** [OfficeDev/office-js-docs-pr#1360]
I succesfully published a sharepoint webapp (the new modern script editor webpart) and now I'd like to publish an office add-in to my tenant too.
If I upload the manifest of this add-in, the local nodejs must run on the pc for this webap to run.
How can I put this on sharepoint app catalog ? Can I package it somehow ? Or, is there a nodejs session  running in sharepoint online ?
If I manage to create the sppkg package via "gulp package-solution --ship", will it work ?

**Comment by mscharlock** [comment]
Hi @suoko - Sorry to hear you've run into issues publishing to the SharePoint app catalog. I'm going to tag @niteshgolchha85 who may have some info for you. @niteshgolchha85 any thoughts?

**Comment by niteshgolchha85** [comment]
@suoko Can you share your Office manifest?

**Comment by suoko** [comment]
> @suoko Can you share your Office manifest?

Hi,
sorry for late reply.
I could share my manifest but that's not the issue.
My question is whethere an office add-in can be packaged in an sppkg file and uploaded to the sharepoint app catalog in order to make it available to all tenant users.
My goal would be that all tenant users have a task pane (like the one well documented here https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/word-quickstart?tabs=yeomangenerator) preinstalled in their word/excel/powerpoint software, both in their online and desktop versions.
I suspect gulp should be configured in the yeoman generated app repository, but I miss the requirements.
