### ISSUE TITLE
Need Debugger option for the outlook add-in development for desktop app

### ISSUE THREAD

**Issue by Harshagracy** [OfficeDev/office-js-docs-pr#1384]
## Article URL

https://docs.microsoft.com/en-us/outlook/add-ins/quick-start

## Issue
There is no debugger for the outlook add-in development for outlook desktop application like we have in word/powerpoint. Somethings which works in browser will not work in outlook desktop client. it would be really great if you could add this in your next release. 

**Please add the visual studio debugger option, else provide a way to debug them for the desktop app.**

**Comment by kbrandl** [comment]
@Harshagracy thanks for reaching out about this. @ElizabethSamuel-MSFT FYI, assigning to you for investigation / follow-up. (The information that @abdulkareemnalband provided earlier in this thread applies to debugging on the web, but @Harshagracy is looking for information about debugging Outlook desktop.) Thanks!

**Comment by Harshagracy** [comment]
Thanks, @kbrandl  for clarifying that. Yes, I am looking for debugger option like we have in word/excel/powerpoint. To be exact, as mentioned in this article. 
https://docs.microsoft.com/en-us/office/dev/add-ins/testing/attach-debugger-from-task-pane

It is easy for word add-in. Just click the arrow from top right corner of the task pane and select attach debugger. It gives the option to use visual studio and launch the debugger. For outlook, I don't see any arrow from the task pane as well as from the ribbon. I have setstate of a variable to see whats the error. ;) (I know it's bad). That's where I need help.

**Comment by Harshagracy** [comment]
Hi, 

Is there any update on this?

**Comment by ElizabethSamuel-MSFT** [comment]
@exextoc Can you provide any guidance on this?

Thanks.

**Comment by exextoc** [comment]
Thanks for your question.

For the two main debugging options, the information provided by @abdulkareemnalband is correct. You would use either Edge DevTools (for recent versions of Office and Windows where the task pane is rendered in Edge WebView) or the F12 Chooser, if either Office or Windows is an older version, where the task pane is rendered in IE.

Please check [this article](https://developer.microsoft.com/en-us/office/blogs/microsoft-edge-webview-for-office-add-ins/) for the specific Office and Windows versions where Edge WebView is used.

And once you determine which debugger to use, [this article](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-add-ins-using-f12-developer-tools-on-windows-10) describes how to attach both debuggers.

The second article you linked to describes one way of attaching the Visual Studio debugger, which is possible when rendering in IE. But the other two options are currently the preferred debuggers.

**Comment by Harshagracy** [comment]
@exextoc Thank you. I feel it is the same comment as @abdulkareemnalband . Still, I did not get my answer to the query. I am looking for information about debugging in Outlook desktop for outlook add-in.

**Comment by exextoc** [comment]
Outlook desktop does not have a debugger that can attach from the taskpane. The only options are the ones stated in our answer above: 
1. Edge DevTools or F12 Chooser (depending on your build)
2. Attaching the Visual Studio debugger

Both of these debuggers allow you to attach to your add-in for debugging. The articles linked in our last answer provide steps for attaching and debugging tips (such as how to set breakpoints).

**Comment by ElizabethSamuel-MSFT** [comment]
@Harshagracy Please take a few minutes to request Outlook desktop debugging for the task pane in [User Voice](https://officespdev.uservoice.com/forums/224641-general/category/131778-outlook-add-ins). The product team considers these requested features as they plan.

I'll go ahead and close this issue. If you have any further questions about this, do let us know and we'll reopen this issue.

Thanks.
