### ISSUE TITLE
Inspect elemnt is not appearing when Outlook is installed using Mac app store

### ISSUE THREAD

**Issue by abdulkareemnalband** [OfficeDev/office-js-docs-pr#1385]
I have installed outlook using Mac app store https://apps.apple.com/us/app-bundle/microsoft-office-365/id1450038993

I followed steps listed here https://docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-office-add-ins-on-ipad-and-mac

I'm still not able to debug addin

|**Application**   | Outlook for mac|
|--|--|
|**Type of Addin** | Task pane|
|**OS**            | macOS Catalina Version 10.15|
|**Outlook**       | 16.30.1 (19102002) from mac app store|

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be179784-5839-3e8f-c131-1f4d89808b03
* Version Independent ID: 69bca101-91a2-3a5e-5177-493723504354
* Content: [Debug Office Add-ins on a Mac - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-office-add-ins-on-ipad-and-mac)
* Content Source: [docs/testing/debug-office-add-ins-on-ipad-and-mac.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/debug-office-add-ins-on-ipad-and-mac.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by kbrandl** [comment]
@abdulkareemnalband sorry to hear that you've run into this problem. Please see the following issue in **OfficeDev/office-js** (the repo where product issues are tracked) for explanation of root cause and a proposed workaround.

https://github.com/OfficeDev/office-js/issues/506
