### ISSUE TITLE
Office.context.mailbox.item.getEntitiesByType(Office.MailboxEnums.EntityType.Contact) returns empty array

### ISSUE THREAD

**Issue by hectorAmaral** [OfficeDev/office-js-docs-pr#1395]
I'm trying to retrieve the email item contacts but the method returns an empty array.
I've tried bot methods:

`Office.context.mailbox.item.getEntitiesByType(Office.MailboxEnums.EntityType.Contact)`

and 

`Office.context.mailbox.item.getEntities().contacts`

none of them seems to work.

I'm using an Office 365 account and I can see the contact exists on the Outlook desktop app and the web version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5087f99-2e9c-3074-53dc-8507da1e74a4
* Version Independent ID: b9a838b9-1136-a3f2-14cb-d89d4b8672c1
* Content: [Office.context.mailbox.item - requirement set 1.7 - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/objectmodel/requirement-set-1.7/office.context.mailbox.item)
* Content Source: [docs/reference/objectmodel/requirement-set-1.7/office.context.mailbox.item.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/objectmodel/requirement-set-1.7/office.context.mailbox.item.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by mscharlock** [comment]
Hi @hectorAmaral - Thanks for using our docs. @ElizabethSamuel-MSFT can you have a look at this issue or pass to someone else on the Outlook team? Thanks!

**Comment by ElizabethSamuel-MSFT** [comment]
@hectorAmaral Looks like this is the same issue as the one reported on the office-js repo: https://github.com/OfficeDev/office-js/issues/807. I'll close this and make any updates to the docs based on the outcome of the investigation of the related issue.
