### ISSUE TITLE
messageBanner Issues

### ISSUE THREAD

**Issue by redcirkle** [OfficeDev/office-js-docs-pr#1398]
The file throws an exception when I try to use messageBanner. 
![image](https://user-images.githubusercontent.com/19576266/67802931-4e9d5080-fa49-11e9-96eb-330e7fcc5714.png)

I copied over Home.ts exactly as provided at the bottom of the article; the only change I made was to change the '1.1' string parameter in the `Office.context.requirements.isSetSupported(string, string)` method call to a number.
![image](https://user-images.githubusercontent.com/19576266/67803182-b81d5f00-fa49-11e9-8c34-11c0f1349678.png)

Do you know what the issue might be? Thanks!

## Article URL
https://docs.microsoft.com/en-us/office/dev/add-ins/develop/convert-javascript-to-typescript

**Comment by kbrandl** [comment]
@redcirkle sorry to hear that you've run into this problem. I've been working on some updates to this article and just submitted a PR that should fix the problem you've described: #1399. 

Essentially, you should make sure that the first few lines after `$(document).ready(function () {` are as shown here:

```
$(document).ready(function () {
    // Initialize the notification mechanism and hide it
    var element = document.querySelector('.MessageBanner');
    messageBanner = new components.MessageBanner(element);
    messageBanner.hideBanner();
```

The live docs should be updated later today (after PR #1399 is merged). I'll go ahead and close this issue now, but please feel free to comment here again if this doesn't resolve your problem.

**Comment by redcirkle** [comment]
This also causes compiler issues, where the file can't find "components". 
![image](https://user-images.githubusercontent.com/19576266/67813133-076d8a80-fa5e-11e9-9b1e-6f1e77b22062.png)

Do we need to declare this at the top of the file?

**Comment by kbrandl** [comment]
Please ensure you've completed all of the steps in the (just updated this afternoon) article: https://docs.microsoft.com/en-us/office/dev/add-ins/develop/convert-javascript-to-typescript. 

I'm guessing you probably haven't renamed the **./Scripts/MessageBanner.js** file to **MessageBanner.ts** yet (doing so should resolve the "cannot find name components" error), and there's likely another step or two in the article that you'll need to complete as well (e.g., editing the line `_onResize(null);` in **./Scripts/MessageBanner.ts** to be `_onResize();` instead). 

Now that it's been updated, [the article](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/convert-javascript-to-typescript) should contain complete/correct guidance to get everything working properly.
