### ISSUE TITLE
iOS Side Loading Directions Out of Date

### ISSUE THREAD

**Issue by michaelsaul** [OfficeDev/office-js-docs-pr#1407]
## Article URL
https://docs.microsoft.com/en-us/office/dev/add-ins/testing/sideload-an-office-add-in-on-ipad-and-mac

## Issue
Directions for side loading Add-ins on Excel of iOS are no longer current in either iTunes on Windows or macOS Catalina.

iTunes on Windows (installed from the Microsoft Store) does not have Apps under settings. Transferring a manifest.xml file via the File Sharing option does not seem to add the Add-in Developer heading in the Add-in menu in the Excel for iPad ribbon.

Similarly, iTunes no longer exists in macOS Catalina. Using the new Finder Files option under the iPad allows the manifest.xml to be transferred to the iPad, but the Add-in never shows up in Excel.

**Comment by ElizabethSamuel-MSFT** [comment]
@michaelsaul Thanks for raising this issue.

@davidchesnut Can you take a look?

Thanks.

**Comment by mscharlock** [comment]
Hi @michaelsaul - Apologies for the delay. I believe our [iOS side loading instructions](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/sideload-an-office-add-in-on-ipad-and-mac) were recently updated, which might help solve this issue. Let us know if these instructions aren't helpful for you and we can continue to troubleshoot.

**Comment by mscharlock** [comment]
I'm going to close this issue for now as I believe we have updated the instructions to address - but @michaelsaul let me know if you still encounter issues by commenting on this thread. I can then reopen it. Thanks!
