### ISSUE TITLE
How to support custom functions in older Excel versions?

### ISSUE THREAD

**Issue by coolcfxp** [OfficeDev/office-js-docs-pr#1411]
## Article URL
https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-overview

## Issue

I'm confused by the documentation, it says other than office 365, the "custom functions" is not supported. However as a solution vendor, my customers are using older and offline versions of Office, the documentation does not provide an alternative so that I can support other versions (I knew there must be some, but I need a link for the legacy support).

**Comment by AlexJerabek** [comment]
Hi @coolcfxp, 
Custom Functions are only supported for ExcelApi 1.9 and higher. Any legacy support would be through User-Defined Functions (UDFs). Assigning @davidchesnut for further guidance.

**Comment by davidchesnut** [comment]
Hi @coolcfxp, 
Yes, as @AlexJerabek says, If you need to run custom functions on older and offline versions of Office, you will need to use UDFs in an Excel XLL. You can build both an Excel XLL and custom function with the same functionality. This way you can provide a solution to older versions of Office, while also running cross-platform with custom functions. You can also specify the XLL to be used in place of the custom function on Windows if that is a better experience. You can see more about how to configure this in the article [Extend custom functions with XLL user-defined functions](https://docs.microsoft.com/office/dev/add-ins/excel/make-custom-functions-compatible-with-xll-udf)

Hope this helps!

**Comment by coolcfxp** [comment]
Thanks for your reply, I think I know where to start.
