### ISSUE TITLE
Link to further explanation regarding the term "entity highlighting"

### ISSUE THREAD

**Issue by adem** [OfficeDev/office-js-docs-pr#1412]
When reading an auto-generated manifest from top to bottom in order to understand their meaning, one will encounter the `DisableEntityHighlighting` property that is set to `false` as of today. The documentation page doesn't really clarify what's behind the term _entity highlighting_.

After doing a bit of googling, I suspect it has something to do with contextual add-ins and whether to highlight text fragments (entities?) that match the predefined regex, however I'm not too sure. If it indeed has something to do with contextual add-ins, then it shouldn't be part of the auto-generated manifest in my opinion, as the auto-generated manifest does not specify an `ExtensionPoint` with attribute `DetectedEntity`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 609bae71-6e55-153f-0ba4-1469272f9eca
* Version Independent ID: 63b55e12-3d3e-41df-93d2-d3b81d33e440
* Content: [DisableEntityHighlighting element in the manifest file - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/disableentityhighlighting#feedback)
* Content Source: [docs/reference/manifest/disableentityhighlighting.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/manifest/disableentityhighlighting.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@adem Thanks for your query. Yes, that property is related to Outlook contextual add-ins. Can you share how the manifest was generated? That will help us to determine next steps.

Thanks.

**Comment by adem** [comment]
@ElizabethSamuel-MSFT Hi, the manifest was generated via `yo office` with the options `Office Add-in Task Pane project using React framework`, `TypeScript`, and `Outlook`.

```
$ cat manifest.xml | grep Disable
<DisableEntityHighlighting>false</DisableEntityHighlighting>
```

Here are the versions:
```
$ npm list -g | grep "yo@"
└─┬ yo@3.1.0
$ npm list -g | grep "generator-office@"
├─┬ generator-office@1.4.0
```
Thanks!

**Comment by ElizabethSamuel-MSFT** [comment]
@adem Thanks for your response. We'll look into this.

@akrantz @TCourtneyOwen Can you take a look at this issue?

Thanks.

**Comment by TCourtneyOwen** [comment]
@adem @ElizabethSamuel-MSFT I will take a look at the Outlook manifest that yo-office uses

**Comment by TCourtneyOwen** [comment]
I think we can probably safely remove the DisableEntityHighlighting element from the Outlook manifest

**Comment by ElizabethSamuel-MSFT** [comment]
@TCourtneyOwen Thanks for investigating. Can you update this issue once it is fixed?

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@adem Can you confirm if this issue is now fixed for you?

Thanks.

**Comment by adem** [comment]
@ElizabethSamuel-MSFT The element still seems to be part of the manifest - tested with `generator-office@1.7.6`. However, I'm really not too bothered by it. It doesn't break anything and was just an initial point of confusion in our team. You can go ahead and close the issue.

Thanks!

**Comment by ElizabethSamuel-MSFT** [comment]
@adem Thanks for letting us know. Closing now.
