### ISSUE TITLE
How many DesktopFormFactor elements are allowed in a single Manifest file?

### ISSUE THREAD

**Issue by timothyhoffmann** [OfficeDev/office-js-docs-pr#1416]
How many DesktopFormFactor elements are allowed in a single Manifest file?  Possibly it's limited by each host type (e.g. Outlook vs. Excel?).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb3c39f4-bf7f-a54b-1671-a3a3a5a4ce92
* Version Independent ID: fa858a5c-a2a7-5cad-c312-f62bcfcd5115
* Content: [DesktopFormFactor element in the manifest file - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/desktopformfactor#feedback)
* Content Source: [docs/reference/manifest/desktopformfactor.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/manifest/desktopformfactor.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@timothyhoffmann Thanks for asking about this. I would say one per host you've defined for your add-in.

@Rick-Kirkham Can you take a look?

Thanks.

**Comment by Rick-Kirkham** [comment]
There can be a maximum of per host. See https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/overview/schemas/taskpane/TaskPaneAppVersionOverridesV1_0.xsd
