### ISSUE TITLE
why Office.context.mailbox.item.start.getAsync is async, can i get the start time for sync method?

### ISSUE THREAD

**Issue by hello-chenchen** [OfficeDev/office-js-docs-pr#1427]
I think sometimes, i do not need to get the start time by call async method, the sync will be a better way.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbb2ef5c-e278-6aba-6fe8-7a4cc0e357d5
* Version Independent ID: ebc95637-b567-86b8-4f6d-ee9c6afee19e
* Content: [Office.context.mailbox.item - requirement set 1.5 - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/objectmodel/requirement-set-1.5/office.context.mailbox.item#start-datetime)
* Content Source: [docs/reference/objectmodel/requirement-set-1.5/office.context.mailbox.item.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/objectmodel/requirement-set-1.5/office.context.mailbox.item.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@hello-chenchen Thanks for your question. Could you share a few situations where you think sync will be a better way?

Do note that in Read/Attendee mode, you can do something like `var start = Office.context.mailbox.item.start;` without calling getAsync.

Thanks.

**Comment by hello-chenchen** [comment]
Hi @ElizabethSamuel-MSFT , thank you for your reply.
Yeah, i think when i just want to get the start time propriety, the sync style like your demo `var start = Office.context.mailbox.item.start;` will be better than like this one: `Office.context.mailbox.item.start.getAsync( (result) => { return new Promise(result); }).then((data) => {})`(simple and intuitive).
Yeah, i notice the read mode, but when i try to use it. i found it is not work. maybe i don't use it in the right way. This is my setting in my manifest.xml below:
 ```
<FormSettings>
    <Form xsi:type="ItemRead">
      <DesktopSettings>
        <SourceLocation DefaultValue="https://localhost:8081/schedule"/>
        <RequestedHeight>250</RequestedHeight>
      </DesktopSettings>
    </Form>
  </FormSettings>

  <Permissions>ReadWriteItem</Permissions> 
  <Rule xsi:type="RuleCollection" Mode="Or">
  <Rule xsi:type="ItemIs" ItemType="Message" FormType="Edit" />
  <Rule xsi:type="ItemIs" ItemType="Appointment" FormType="Read" />
  <Rule xsi:type="ItemHasKnownEntity" EntityType="MeetingSuggestion" />
  </Rule>
  <DisableEntityHighlighting>false</DisableEntityHighlighting>  
```
I change the `<Rule xsi:type="ItemIs" ItemType="Appointment" FormType="Edit" />` from `FormType="Edit"` to `FormType="Read"`. But it is not worked. I don't know what's wrong. Can you give me some suggestion about how to setting the right mode.

And by the way, can i use both sync and async method in compose mode. For example, in my situation i  just want to read the start time and end time. And i also want to write the subject and the location though setAsync method?

Thanks a lot~
