### ISSUE TITLE
Links to "AuthOptions" is 404

### ISSUE THREAD

**Issue by timothyhoffmann** [OfficeDev/office-js-docs-pr#1428]
https://docs.microsoft.com/en-us/javascript/api/office/officeruntime.authoptions is not found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb06c24b-9d11-9cc5-2e98-561601452638
* Version Independent ID: abda21d9-6e80-8319-c56f-004658014e3c
* Content: [Enable single sign-on for Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/sso-in-office-add-ins)
* Content Source: [docs/develop/sso-in-office-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/sso-in-office-add-ins.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
We're working on this. The topic that is being linked to is temporarily here: [officeruntime.authoptions](https://docs.microsoft.com/javascript/api/office-runtime/officeruntime.authoptions?view=excel-js-preview). In a few days it should move to the URL in the article.

**Comment by Rick-Kirkham** [comment]
Fixed.
