### ISSUE TITLE
Office 365 Alert Interval

### ISSUE THREAD

**Issue by d4rth-v4d3r** [OfficeDev/office-js-docs-pr#1429]
In my case, I have to add the AlertInterval key in path: HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\WEF\AlertInterval

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00c430f1-bbf5-53b8-a225-4fbe8fc39c3b
* Version Independent ID: 0a069a0d-4d35-71ee-53af-8c55fe8548a0
* Content: [Browsers used by Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins#feedback)
* Content Source: [docs/concepts/browsers-used-by-office-web-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/concepts/browsers-used-by-office-web-add-ins.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by mscharlock** [comment]
Hi @d4rth-v4d3r, thanks for reading the docs and writing in. I'll make a note for our team to look into this. Would you be able to provide more specifics about what kind of system you are using (i.e. Office version, OS, etc)? Thanks!

**Comment by d4rth-v4d3r** [comment]
@mscharlock 
![image](https://user-images.githubusercontent.com/5044302/69933237-9de4ff80-1493-11ea-9f96-b1a2e888a6a6.png)

![image](https://user-images.githubusercontent.com/5044302/69933258-bc4afb00-1493-11ea-9d88-3cf3326e1322.png)

**Comment by mscharlock** [comment]
Hi @d4rth-v4d3r - Thank you for the updated information and sorry for my delayed response. I'm going to put this item into our backlog to investigate, although so far I have not been able to reproduce this issue. I'm going to close this issue for now but if you need anything else, please go ahead and reply on this thread and I will reopen the issue. Thanks and happy holidays!

**Comment by sanzoghenzo** [comment]
Same here, HKLM didn't work, HKCU did.
Excel 2016 MSO (16.0.11929.20436) 32 bit
Windows 10 Pro 1909 OS Build 18363.592
IIRC, and if it can help, office was installed when my login was a restricted user, but it was promoted later to admin.
