### ISSUE TITLE
VS and sharepoint should be installed before debugging office addin on windows

### ISSUE THREAD

**Issue by BuggMaker** [OfficeDev/office-js-docs-pr#1430]
In this document, we should have a clear description about how to debug office addins on Windows. There are four key points:

1. Visual Studio, version >= 2015
2. Office, version >= 2016
3. SharePoint Project installed in VS
4. Attach to process in VS

If we don't install SharePoint Project like key point 3, we couldn't see the source code in  VS and add break point when we attach to process.

So i think it'll be very useful to add the key point 3 in this document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8b1badd-9a43-6935-a6e6-76508e7f9741
* Version Independent ID: bdeabb00-8eeb-07a2-0de9-967f018a2c8a
* Content: [Attach a debugger from the task pane - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/attach-debugger-from-task-pane#feedback)
* Content Source: [docs/testing/attach-debugger-from-task-pane.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/attach-debugger-from-task-pane.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AbidRahman-MSFT** [comment]
Hey @BuggMaker, thanks for your suggestion. 

Could you provide more information regarding the platform and application of your add-in, as well as what error you were running into when attempting to debug without installing a SharePoint Project?

**Comment by BuggMaker** [comment]
project: create by `yo office` script
platform: windows 10
addin type: excel
debugger: [Attach a debugger from the task pane](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/attach-debugger-from-task-pane)
error: no error, but i can't see any source code in visual studio, so i can't add breakpoint and debug the code. 
----------------- split line --------------------
 Later, I installed SharePoint Project for visual studio, then attach to debugger once again, now i can see the source code and add breakpoint.

**Comment by mscharlock** [comment]
Hi @BuggMaker I will go ahead and see if I can repro this issue and get back to you. :) Thanks!

**Comment by mscharlock** [comment]
Hi @BuggMaker, you are right on this one - we will go ahead and get this item on our backlog to update the documentation here. I will go ahead and close this issue for now, but if you'd like to continue this conversation, just comment in this thread and I will re-open.
