### ISSUE TITLE
Code is Visual Studio project

### ISSUE THREAD

**Issue by ankugarg** [OfficeDev/office-js-docs-pr#144]
Code should be compatible with Visual Studio code.

## Article URL
https://github.com/OfficeDev/Excel-Add-in-Tutorial

## Issue
Code is Visual Studio project

**Comment by Rick-Kirkham** [comment]
@ankugarg  The sample is compatible with Visual Studio Code. In fact, it was created with Visual Studio Code. There is also a Visual Studio version in the VS_Solution folder.
