### ISSUE TITLE
bizarre

### ISSUE THREAD

**Issue by tanjb-msft** [OfficeDev/office-js-docs-pr#1441]
my users will need to run a web server to view my worksheets?  They will need to import xml files to their machines?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bac6469-78a6-dae9-e6c4-497c953a1576
* Version Independent ID: d860aff2-60ad-c008-2d10-b046f3198f44
* Content: [Custom functions quick start - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-custom-functions-quickstart?tabs=excel-windows#feedback)
* Content Source: [docs/quickstarts/excel-custom-functions-quickstart.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/quickstarts/excel-custom-functions-quickstart.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by slabereemsft** [comment]
Hi Tanj,

Per our offline discussion, the model for Web Add-ins/Custom Functions today is optimized around IT Admin deployed or Store deployed add-ins.  The recommended way to enable this within a tenant is Centralized Deployment (https://docs.microsoft.com/en-us/office/dev/add-ins/publish/centralized-deployment).  We're definitely looking to lower the barrier to entry here.

Thanks!
-Sean

**Comment by slabereemsft** [comment]
Closing now that I have access to close issues in this repo.
