### ISSUE TITLE
Add in won't stay in the ribbon

### ISSUE THREAD

**Issue by AlRosenthal** [OfficeDev/office-js-docs-pr#1443]
I've recently created a small Word add in for a client and this was the best method for publishing the app. But once a user has added the app to their Word for desktop and closes the application, they have to re add the add in. Is this supposed to be how that works?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94198cb6-3426-c33f-6ff9-88f2a327af49
* Version Independent ID: 99fc507e-dc87-9367-fb44-ff1016ec9fe2
* Content: [Publish task pane and content add-ins to a SharePoint app catalog - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/publish/publish-task-pane-and-content-add-ins-to-an-add-in-catalog)
* Content Source: [docs/publish/publish-task-pane-and-content-add-ins-to-an-add-in-catalog.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/publish/publish-task-pane-and-content-add-ins-to-an-add-in-catalog.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by slabereemsft** [comment]
Hi AlRosenthal,

The note in the linked article "App catalogs on SharePoint do not support add-in features that are implemented in the VersionOverrides node of the add-in manifest, such as add-in commands." explains the behaviour that you are seeing sadly.

The recommended way to deploy add-ins within an enterprise is to use Centralized Deployment. https://docs.microsoft.com/en-us/office/dev/add-ins/publish/centralized-deployment

**Comment by slabereemsft** [comment]
Closing per comment above.
