### ISSUE TITLE
Loading an enterprise Add-In for a closed user group

### ISSUE THREAD

**Issue by awoerl** [OfficeDev/office-js-docs-pr#1447]
We created an Add-In that should be only accessible for a closed list of customers. Also, the Add-In needs to load the content from the customer's application website, that we provide. This means the manifest will be different per customer. When I use the side loading here, the Add-In installation is a little bit cumbersome and what is a bigger problem, the Add-In disappears after each application start.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ddce0bd-5c66-c2cb-0640-ee4d5bd401c5
* Version Independent ID: b5d4bc26-a43e-4a85-e7d5-fe4fc4ec3d0d
* Content: [Sideload Office Add-ins for testing - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins#feedback)
* Content Source: [docs/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@awoerl Sorry to hear that you're facing these issues.

@Rick-Kirkham Is this something you can help with or take a look at?

Thanks.

**Comment by Rick-Kirkham** [comment]
The only way to have different manifests for different customers is to ship each customer their own manifest. They will then need to publish the manifest using [Centralized Deployment](https://docs.microsoft.com/en-us/office/dev/add-ins/publish/centralized-deployment) or using a [network share](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins#share-a-folder).
