### ISSUE TITLE
Set default URL

### ISSUE THREAD

**Issue by redcirkle** [OfficeDev/office-js-docs-pr#1451]
## Article URL
https://docs.microsoft.com/en-us/office/dev/add-ins/develop/add-in-manifests?tabs=tabid-1

## Issue

 
Looking at the Resources section of the manifest file, I see that "https://commandsimple.azurewebsites.net/" is used as the start of many URLs. Is there a way to set this at one place in the manifest (or, even better, outside of the manifest) so that other URLs can reference this beginning section? 

We want to be able to change our web app URL in one location and reference it all over the manifest. We were hoping to set it from a parameter outside the manifest so that we could update the URL without changing anything for the user. However, changing it one place in the manifest would also be a great improvement. 

Is there a way for us to accomplish this?

**Comment by ElizabethSamuel-MSFT** [comment]
@redcirkle Thanks for your question.

@Rick-Kirkham Can you help with this?

Thanks.

**Comment by Rick-Kirkham** [comment]
The manifest is XML and XML is not dynamic in the way that you want. You can't have a constant set in one place and then reference that constant in other places in the XML doc. Likewise, an XML file is not an executable. It can't call out to a setting somewhere outside itself. At least not in the way that you require. The closest you could come to what you want to do is create a script (perhaps using XSLT) that takes a URL parameter, then opens the manifest and inserts that URL in all the places that you want it. But you can do this by just opening the manifest in a text editor and using a global search 'n' replace. As for not "changing anything for the user", I don't think this would be possible. If the manifest changes, the old manifest, where it is deployed, will have to be replaced.

**Comment by redcirkle** [comment]
Thank your for getting back to us, this helps us immensely!
