### ISSUE TITLE
Older Production Library URL version

### ISSUE THREAD

**Issue by zakhan4** [OfficeDev/office-js-docs-pr#1452]
Isn't the latest cdn link for office js library have version 1.1? https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c7080b5-9791-e1ca-ff77-ae3dbe5f10cc
* Version Independent ID: 1207aec0-6183-53bb-2768-ebb39d09ed99
* Content: [Excel JavaScript API requirement sets - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/excel-api-requirement-sets)
* Content Source: [docs/reference/requirement-sets/excel-api-requirement-sets.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/requirement-sets/excel-api-requirement-sets.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @zakhan4, 
Thanks for the question. I'll look into the difference between the /1/ and /1.1/ CDN endpoints. Both are regularly updated and should have the libraries you need.
