### ISSUE TITLE
Which requirements set is supported in the different channels of Office 365 ProPlus?

### ISSUE THREAD

**Issue by stukey** [OfficeDev/office-js-docs-pr#1460]
Which requirements set is supported in the different channels of Office 365 ProPlus clients linked to an Office 365 subscription? Please update the documentation to make this clear. The comment “latest builds” in the above table isn’t helpful. For example if we’re on the latest version of the Semi-Annual Channel build (Nov 2019), which API requirements set does this build support? Is it 1.8 or still 1.7? What about the Monthly and the Semi-Annual Targeted channels? I assume 1.8 is only supported in the latest monthly channel build only? I reviewed the release notes for each different channel and couldn’t find any information on which API requirements set is supported. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8e26a32-7523-2211-bde3-938cf94a76ec
* Version Independent ID: 80ad76d1-8a12-348f-dd6a-2f9392ed1f95
* Content: [Outlook JavaScript API requirement sets - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/outlook-api-requirement-sets#feedback)
* Content Source: [docs/reference/requirement-sets/outlook-api-requirement-sets.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/requirement-sets/outlook-api-requirement-sets.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for your feedback @stukey. Assigning @ElizabethSamuel-MSFT to investigate.

**Comment by ElizabethSamuel-MSFT** [comment]
@stukey I'm working with the product team to pull this information together.

For now, consider the subscription details to relate to monthly channel builds.

Thanks.

**Comment by stukey** [comment]
@ElizabethSamuel-MSFT Thanks for the update. Any idea if/when API 1.8 will be available in SAC release?

**Comment by ElizabethSamuel-MSFT** [comment]
@stukey No idea yet. We'll update this issue as soon as we can with that info.

**Comment by stukey** [comment]
I see the page has been updated to state “latest build **(monthly channel)**”, which is great. Could you also document the API versions supported by the latest Semi-Annual Channel and Semi-Annual Channel Targeted releases too? This info is really useful for organistions like mine that only use SAC releases. We have two add-ins that are dependant on the version 1.8 release of the API and we really need to understand when it will be available in the SAC release.

**Comment by ElizabethSamuel-MSFT** [comment]
@stukey We're working on pulling this info together. Thanks.

Related PR: https://github.com/OfficeDev/office-js-docs-pr/pull/1639

**Comment by ElizabethSamuel-MSFT** [comment]
The page has been updated to include the minimum version and build. You should be able to tell when your channel support this or a newer version.

Thanks.
