### ISSUE TITLE
Control section should have a reference to the Control documentation page

### ISSUE THREAD

**Issue by aafvstam** [OfficeDev/office-js-docs-pr#1461]
There is no reference to the Control reference page on this page. As a result from this the developer is in the dark on what to use for Controls. There is just the little example, but that doesn't show what Control options are available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 540ad65e-a396-ce57-34fa-00e490028f0d
* Version Independent ID: d7807a56-e4d6-aa64-0dd8-3af677b9849d
* Content: [Group element in the manifest file - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/group#label)
* Content Source: [docs/reference/manifest/group.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/manifest/group.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by kbrandl** [comment]
@aafvstam thanks for the feedback! I've submitted a PR to add this info to the docs (#1463). 

This issue will automatically be closed when that PR gets merged, and the update will subsequently appear in the live docs with the next batch of doc updates that's published.
