### ISSUE TITLE
Icon Child element is required

### ISSUE THREAD

**Issue by aafvstam** [OfficeDev/office-js-docs-pr#1462]
Omitting the Icon Child Element will result in an error not loading the Add-in. Therefor the Icon element is a required element (i.e the Icon node with the three required Image child elements):

&lt;Icon&gt;
   &lt;bt:Image size="16" resid="Icon.16x16"/&gt;
   &lt;bt:Image size="32" resid="Icon.32x32"/&gt;
   &lt;bt:Image size="80" resid="Icon.80x80"/&gt;
&lt;/Icon&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 540ad65e-a396-ce57-34fa-00e490028f0d
* Version Independent ID: d7807a56-e4d6-aa64-0dd8-3af677b9849d
* Content: [Group element in the manifest file - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/group)
* Content Source: [docs/reference/manifest/group.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/manifest/group.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by kbrandl** [comment]
@aafvstam thanks for the feedback! Do I understand correctly that you're referring to [Icon](https://docs.microsoft.com/office/dev/add-ins/reference/manifest/icon) element that's specified within a Button control or Menu control?  If so, it seems like the documentation already specifies that this element is required -- i.e., the value of the **Required** column is **Yes** for the `Icon` element in the child elements tables for the Button control and Menu control, here in the docs:

- https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/control#button-control
- https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/control#menu-dropdown-button-controls

For example, here's the Child elements table for the Button control, where the `Icon` element is specified as required:

![image](https://user-images.githubusercontent.com/3019529/69988987-8ccdda00-14f7-11ea-8c4c-d33f8535e0eb.png)

Please let me know if the docs (as currently written) address your concern. If you think more information is needed in the docs, can you please clarify more precisely what you're hoping to see (and where) in the docs regarding the `Icon` element? Thanks!

**Comment by aafvstam** [comment]
The information is missing on the Group object, not the Button. That object currently only mentions two required items, Label and Control from the top of my head. Leaving out the Icon on Group makes it crash.

If you want to see how you can check the video from this morning on https://twitch.tv/maartenvanstam

Hope it helps,

Maarten


Sent using a smalle device, so ignore the typos 😎

________________________________

**Comment by kbrandl** [comment]
@aafvstam thanks for the clarification; I now understand the problem (and have confirmed via the manifest schema that the `Icon` element is indeed a required child element of the `Group` element). I'll submit a PR later today to update the docs accordingly. Thanks for bringing this to our attention!

**Comment by kbrandl** [comment]
@aafvstam thanks again for the feedback! I've submitted a PR to add this info to the docs (#1467). 

This issue will automatically be closed when that PR gets merged, and the update will subsequently appear in the live docs with the next batch of doc updates that's published.
