### ISSUE TITLE
Edge or Edgium? 

### ISSUE THREAD

**Issue by fowl2** [OfficeDev/office-js-docs-pr#1472]
For versions of Office that use Edge as the browser engine, is this EdgeHTML (aka Edge Legacy) or the new Chromium based Edge?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00c430f1-bbf5-53b8-a225-4fbe8fc39c3b
* Version Independent ID: 0a069a0d-4d35-71ee-53af-8c55fe8548a0
* Content: [Browsers used by Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins)
* Content Source: [docs/concepts/browsers-used-by-office-web-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/concepts/browsers-used-by-office-web-add-ins.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
It's whatever Edge is installed on the user's computer.

**Comment by dwittenberg** [comment]
I use Windows 1903 build 18362.628. Have upgraded Edge to Version 79.0.309.71, uninstall Internet Explorer in optional Features and made some reboots.
weiterhinn
But Outlook (Desktop) still renders my Plugin with Edge/18.18362. 

My Plugin is for productive use - but needs modern rendering. 
Please, what is my fault?

**Comment by Rick-Kirkham** [comment]
@dwittenberg This is more of a technical question (and possibly a bug) than an issue with documentation. Please create an issue on the [office-js repo](https://github.com/OfficeDev/office-js/issues).

**Comment by Rick-Kirkham** [comment]
@dwittenberg @fowl2 
I've got updated information. Merely installing the new Chromium-based Edge does NOT cause Office to use the Chromium renderer in Office Add-ins. The old pre-Chromium render is still installed on the computer and Office will continue to use it for Office Add-ins until we ship a build of Office that works with Chromium. That will likely happen to subscribers in the Insiders channel in the next few months. In the meantime, there is no way that you can specify that you want Chromium used.
