### ISSUE TITLE
Error code 9043 is undocumented

### ISSUE THREAD

**Issue by clavx** [OfficeDev/office-js-docs-pr#1492]
The Outlook add-in fails with code 9043 that is not documented here.
This occurs with the `getAttachmentContentAsync()` method implemented in Mailbox 1.8.

Could you please correct the document?
Also, would it be possible to tell me that what types of attachments will show error code 9043?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad14a1fc-e890-3292-0a53-8a755db35f6e
* Version Independent ID: 78e25f2a-c710-6c16-32d7-f16d28b08e31
* Content: [JavaScript API for Office error codes - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/javascript-api-for-office-error-codes)
* Content Source: [docs/reference/javascript-api-for-office-error-codes.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/javascript-api-for-office-error-codes.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@clavx Sorry that you've hit an error and thanks for letting us know.

@exextoc Can you provide this info? We can update the docs after that.

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@exextoc Any update on this? Thx.

**Comment by exextoc** [comment]
Thanks for your question. This error is currently returned by `getAttachmentContentAsync` when the attachment is an **item attachment** other than an email or calendar item. For example: Contact and task attachments.

@ElizabethSamuel-MSFT This error could be documented in the [list of error codes](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/javascript-api-for-office-error-codes) as well as in the docs for [getAttachmentContentAsync](https://docs.microsoft.com/en-us/javascript/api/outlook/office.messageread?view=outlook-js-1.8#getattachmentcontentasync-attachmentid--options--callback-).

This is the full error object returned, and I believe this string could be used in the documentation as well.

{"name":"AttachmentTypeNotSupported","message":"The attachment type is not supported.","code":9043}

**Comment by clavx** [comment]
Thank you for the answers.
Just to clarify, is the following description to explain the case of an [Exchange item type](https://docs.microsoft.com/en-us/javascript/api/outlook/office.mailboxenums.attachmenttype)?
> This error is currently returned by `getAttachmentContentAsync` when the attachment is an item attachment other than an email or calendar item. For example: Contact and task attachments.

And we found that the error occurs when embedding an image in Rich Text format.

![Embedding an image in Rich Text Format](https://user-images.githubusercontent.com/58804032/72976378-d959d580-3e15-11ea-8667-9be433af818a.png)

`getAttachmentsAsync(callback)`
callback: (asyncResult: Office.AsyncResult&lt;AttachmentDetails&gt;) =&gt; void[] 
```
{"value":[{"_data$p$0":{"id":"0","name":"Picture (Device Independent Bitmap)","size":0,"attachmentType":0,"isInline":false}}],"status":"succeeded"}
```

`getAttachmentContentAsync(attachmentId, callback)`
callback: (asyncResult: Office.AsyncResult&lt;AttachmentContent&gt;) =&gt; void 
```
{"value":null,"status":"failed","error":{"name":"AttachmentTypeNotSupported","message":"The attachment type is not supported.","code":9043}}
```

Thanks.

**Comment by exextoc** [comment]
Thanks for providing another example. You are right, the same error is returned in this case as well. For RTF specifically, the content of the image may not be returned by getAttachmentContentAsync.
