### ISSUE TITLE
What are the settings that are valid here?

### ISSUE THREAD

**Issue by DennisGaida** [OfficeDev/office-js-docs-pr#1494]
Same goes for TabletSettings and PhoneSettings.
Is any XML valid here? What are the source location and control settings referenced in the description? Please link to or create additional documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7590a7b5-a498-d258-3258-0283df814ad4
* Version Independent ID: 1dd3170b-63ce-9b28-bb88-5b6370802a41
* Content: [DesktopSettings element in the manifest file - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/desktopsettings)
* Content Source: [docs/reference/manifest/desktopsettings.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/manifest/desktopsettings.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Reezaali** [comment]
@exextoc Can you provide the missing element information please?

**Comment by Reezaali** [comment]
@DennisGaida thank you for reporting this issue.

**Comment by exextoc** [comment]
The `Form` element supports three elements in the following order. Each of those elements can have a `SourceLocation` element which must be a valid, fully qualified HTTPS address and `TabletSettings` and `DesktopSettings` also support a `RequestedHeight` element that can have a minimum height of 240px and a maximum height of 800px. These three extension points will appear in older versions of OWA and Outlook 2013 for Windows. The `DesktopSettings` extension point not supported in OWA for Office 365, or Desktop Outlook. `TabletSettings` and `PhoneSettings` will appear in Tablet and Mobile versions of OWA but is deprecated and will be removed from OWA in Office 365 soon (It will still be available in older versions of Exchange On-premise). `TabletSettings` and `PhoneSettings` are not supported in Outlook Mobile for Android or iOS however we support add-ins in these clients using the following [extension points](https://docs.microsoft.com/en-us/outlook/add-ins/outlook-mobile-addins)

```
<Form xsi:type="ItemRead">
          <DesktopSettings>
              <SourceLocation DefaultValue="https://website.html" />
              <RequestedHeight>360</RequestedHeight>
          </DesktopSettings>
          <TabletSettings>
              <SourceLocation DefaultValue="https://website.html" />
              <RequestedHeight>360</RequestedHeight>
          </TabletSettings>
          <PhoneSettings>
              <SourceLocation DefaultValue="https://website.html" />
          </PhoneSettings>
      </Form>
```
