### ISSUE TITLE
Missing documentation for error with code 9022

### ISSUE THREAD

**Issue by MortenSoerensen** [OfficeDev/office-js-docs-pr#1504]
## Article URL

https://docs.microsoft.com/en-us/office/dev/add-ins/reference/javascript-api-for-office-error-codes
## Issue

 There is no documentation for the error with error code 9022.
I get the error in Outlook when trying to save a mail item in compose mode using saveAsync.
The error name is: MessageInDifferentStoreError and the error description (translated from Danish) is: The EWS-id can not be fetched, because the message is saved in another storage.

**Comment by Reezaali** [comment]
@MortenSoerensen thank you for reporting this issue to us. 

@exextoc Can you review & provide the following information please:

Error.code 9022
Error.name MessageInDifferentStoreError
Error.message The EWS-id cannot be fetched, because the message is saved in another store.
Condition: ?

Thanks.
