### ISSUE TITLE
misusing "JSON struct"

### ISSUE THREAD

**Issue by Rick-Kirkham** [OfficeDev/office-js-docs-pr#1522]
What this article calls "JSON structs" is just Object Literal Notation. It is **not** JSON. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d4e5272-512f-7216-0632-e4ebffeb8f2f
* Version Independent ID: c0d3984c-f961-7055-6ef2-e99fa39d5fd9
* Content: [Common coding issues and unexpected platform behaviors - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/common-coding-issues#feedback)
* Content Source: [docs/develop/common-coding-issues.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/common-coding-issues.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks @Rick-Kirkham. I'll correct the article.
