### ISSUE TITLE
JS_Debug environment variable no longer needed

### ISSUE THREAD

**Issue by John-Hart** [OfficeDev/office-js-docs-pr#1539]
If you have installed Visual Studio 2019 Update 4, the command setx JS_DEBUG &lt;PackageFullName&gt; is no longer needed.  The issue was fixed.   See https://developercommunity.visualstudio.com/content/problem/740413/office-development-inconsistent-script-debugging-b.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce779f3a-6e8d-4126-264a-30691ba30df8
* Version Independent ID: 3e673570-f4fd-f6ad-9969-137a5b8c9747
* Content: [Debug Office Add-ins in Visual Studio - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/debug-office-add-ins-in-visual-studio)
* Content Source: [docs/develop/debug-office-add-ins-in-visual-studio.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/debug-office-add-ins-in-visual-studio.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by lindalu-MSFT** [comment]
@John-Hart Thanks for finding this! I've created a PR to update the document. It will be merged shortly.
