### ISSUE TITLE
SSO preview

### ISSUE THREAD

**Issue by erharvey** [OfficeDev/office-js-docs-pr#1551]
Hi,

The SSO feature works without any issues for us but still seems to be in preview. Last year, we had to download the "dev" javascript version to enable sso correctly and decided not to use it internally within the organization due to this. However, it doesn't seem to be the case anymore since keeping the default javascript api file now enable us to use sso directly. Therefore,  we assumed that it was production ready but was surprised that the preview warning is still on the documentation :
https://docs.microsoft.com/en-us/office/dev/add-ins/develop/sso-in-office-add-ins

The question is :  is it still in preview or the documentation is simple not up to date? 
For example, the out of the box power platform plugin uses SSO in production. Is it safe for us to use it internally? Is there any known issues?

If it is still in preview, is the production release date known ?

Thanks

**Comment by Rick-Kirkham** [comment]
SSO is still in preview. As a matter of policy, we don't recommend using preview features in production add-ins, even internal. Also, as a matter of policy, we're not allowed to give firm release dates in advance. The last estimate that I heard is that we hope to release it in the second quarter of this year (April - June); but SSO has had to be postponed in the past and that could happen again.
