### ISSUE TITLE
Unhandled exception after following "Insert Image" steps

### ISSUE THREAD

**Issue by jasonsue53** [OfficeDev/office-js-docs-pr#1559]
I've followed all the steps of "Insert Image".  Then when I show the Task Pane it slides out and I see my "Insert Image" button briefly but then I immediately get the unhandled exception below.    

I thought I perhaps missed a step or screwed something up so I tried it a second time from scratch.  As soon as the solution is created I found I can run it with no problems.  In other words, the default solution which shows the selected text works fine.  The exception starts occurring once I follow the first step under "update code" where the first changes are made to Home.html.  If I run the project directly after that step the exception happens exactly as described above.  Looks like it's parsing the DOM and looking for an element that is no longer there.  

I just installed VS2019 today and have Enterprise, version 16.4.3.  I'm running Office 365 ProPlus.

Unhandled exception at line 3850, column 3 in https://localhost:44320/Scripts/jquery-3.4.1.js
0x800a138f - JavaScript runtime error: Unable to get property 'querySelector' of undefined or null reference occurred

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18abb533-5be7-d533-8106-c52d458ddc1d
* Version Independent ID: 6af81176-d832-d3d5-5060-5218b2ba75ac
* Content: [PowerPoint add-in tutorial - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/powerpoint-tutorial#insert-an-image)
* Content Source: [docs/tutorials/powerpoint-tutorial.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/tutorials/powerpoint-tutorial.md)
* Product: **powerpoint**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by jasonsue53** [comment]
Just confirmed that if in the first step I leave all of the existing code for "content-main" and instead just add the Insert Image button within that existing DIV it works fine.  In other words, there's something else being run in the project that is looking for DOM elements in the existing code that is getting deleted in step 1.

**Comment by kbrandl** [comment]
@jasonsue53 thanks for reporting this issue; we'll investigate and report back here with the outcome.

**Comment by kbrandl** [comment]
@jasonsue53 I've been looking into this, but so far have been unable to reproduce the problem you've described. I am able to complete the tutorial from beginning to end (using Visual Studio Enterprise 2019) and everything works for me.

Given the error message you're reporting, I wonder if perhaps you inadvertently removed the **div** `<div class="MessageBanner" id="notification-popup">` from the end of `Home.html`, when you replaced the contents of the **div** `<div id="content-main">` at the beginning of the tutorial (i.e. in step 1 [here](https://docs.microsoft.com/office/dev/add-ins/tutorials/powerpoint-tutorial#update-code))?  

![image](https://user-images.githubusercontent.com/3019529/73386330-8784d580-4283-11ea-8cb9-0402f4194e2b.png)

**Comment by jasonsue53** [comment]
I’m sorry Kim to have wasted your time.  You’re absolutely right, I didn’t pay close enough attention to the nesting of the DIVs.  I just ran through the sample again making sure not to delete the footer and message banner and it worked fine!

**Comment by kbrandl** [comment]
No worries, @jasonsue53 -- happy to hear that it's working for you now! Please feel free to reach out again in the future, should you run into any new issues.
