### ISSUE TITLE
ADD-IN ERROR We can't open this add-in from localhost.

### ISSUE THREAD

**Issue by janseba** [OfficeDev/office-js-docs-pr#1566]
I've followed all steps in this tutorial. When I click the Show Taskpane button in the ribbon in Excel, I get the following error: ADD-IN ERROR We can't open this add-in from localhost.

I've done exactly the same yesterday and then it worked. Something is broken now, but I've no clue how to debug it. I can not attach F12 development tools to it.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 9c4ddde7-f1fd-44ba-fba1-0ae9d0131df7
* Version Independent ID: d946ffe6-f29f-1563-b679-121090ba60a1
* Content: [Build your first Excel task pane add-in - Office Add-ins](https://docs.microsoft.com/nl-nl/office/dev/add-ins/quickstarts/excel-quickstart-jquery?tabs=yeomangenerator#feedback)
* Content Source: [docs/quickstarts/excel-quickstart-jquery.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/quickstarts/excel-quickstart-jquery.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
Please clarify "I've done exactly the same yesterday and then it worked": Did you go through the entire quickstart twice (so you now have two different projects)? Or do you mean that the very same project that you created yesterday stopped working today? 

Verify that your localhost server is running: Paste the URL of the add-in into the address bar of a browser and see if the page opens.

**Comment by janseba** [comment]
I did go through the entire quick start 2, so indeed I have two projects now, both are not working.
The localhost server is running. If I paste the URL of my add-in into my browser the page will open.

To give a bit more context:
I was working on my own add-in on Friday and everything was working normally. Saturday I got the add-in error (without changing anything in the code). I always have a sample project that I created with the quick start for reference purposes. So first I checked if that add-in still worked. Got the same error. Then I created a new project from scratch (and in the proces upgrading node.js and yeoman generator including the office template to the latests versions) and unfortunately still got the error.

Error message:
![image](https://user-images.githubusercontent.com/6369573/73138752-afe3b880-4066-11ea-8202-f44fb12f1118.png)

wegpack dev server;
![image](https://user-images.githubusercontent.com/6369573/73138775-da357600-4066-11ea-95ba-9652c235d3c4.png)

Test if localhost server is running:
![image](https://user-images.githubusercontent.com/6369573/73138796-123cb900-4067-11ea-937b-256923ab1d15.png)

**Comment by Rick-Kirkham** [comment]
I wonder if Office was updated to a bad build overnight Friday-Saturday. 
1. Are you developing on a Mac or a Windows computer?
2. What is the full version and build number of Office? If you are on Windows it will have the form YYMM nnnnn.nnnnn. E.g., 2001 12330.20000
3. What is the full version of Windows? E.g. Windows 10 1903.
4. Try [sideloading one of the add-ins on Office on the web](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/sideload-office-add-ins-for-testing) and see if it runs there.
5. Run the Fiddler tool and see what the Response is in Fiddler when you launch the add-in.

**Comment by janseba** [comment]
Thanks for your reply!

I'm working on Windows on a Mac in a virtual machine (via Parallels).
I'm working with Microsoft Excel for Office 365 MSO (16.0.119292.20436) 32-bit
I'm working with Windows 10 Pro, Version 1903, Build 18362.592

I will try to side load the add-in to the web this evening and also run the Fiddler tool.

**Comment by janseba** [comment]
I just sideloaded the add-in to Excel online and everything is functioning normally.

In the desktop application, still the same error message.

**Comment by Rick-Kirkham** [comment]
OK. Let me know what Fiddler says when you launch the add-in in desktop.

**Comment by janseba** [comment]
Good news: add-ins are working again!
Bad news: I do not understand why :-(

I've never used Fiddler before. Downloaded, installed and ran it. Started localhost server with npm start and got these results in Fiddler:
<img width="732" alt="image" src="https://user-images.githubusercontent.com/6369573/73213566-b2bad800-4150-11ea-87d4-5793dc851ee4.png">

Found this article on the web: https://docs.microsoft.com/en-us/office/troubleshoot/error-messages/cannot-open-add-in-from-localhost

Tried the suggested command: CheckNetIsolation LoopbackExempt -a -n="microsoft.win32webviewhost_cw5n1h2txyewy" 

Tried my add-ins and now they work. I do not completely understand why. Also it's not clear for me why this changed overnight between Friday and Saturday. Nevertheless I'm happy.

I've a slight issue with the styling of my drop down and buttons:
![image](https://user-images.githubusercontent.com/6369573/73214109-cc105400-4151-11ea-94f8-4532d4dcb836.png)
But I should be able to solve that myself.

**Comment by Rick-Kirkham** [comment]
Glad it's working for you again. The only thing I can think of that might explain it is that on Friday your VM was using a version of Office pre 16.0.11629, which meant you were using IE in your task pane and didn't need the loopback check. Then your VM got upgraded to Office 16.0.119292 overnight and your task pane started using Edge, which requires the loopback check. See here for more info: [Browsers used by Office Web Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins).
