### ISSUE TITLE
Excel Add-in works online, but not on desktop

### ISSUE THREAD

**Issue by redcirkle** [OfficeDev/office-js-docs-pr#1570]
## Article URL
https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-jquery?tabs=yeomangenerator

## Issue
I tried following the steps for this tutorial to create a new Excel add-in (`npm install -g yo generator-office`, `yo office`, and stepping through the Office Add-in Generator). However, when I run `npm start` for the project, the add-in only loads to an error screen. 
![image](https://user-images.githubusercontent.com/19576266/73381341-68ce1100-427a-11ea-9e1a-5eaca2eee13d.png)
While leaving the project running, I added this local add-in to an Excel Online instance ([following this guide](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/sideload-office-add-ins-for-testing)). The add-in _does_ work in Excel Online, just not on desktop Excel.
![image](https://user-images.githubusercontent.com/19576266/73381785-307b0280-427b-11ea-8506-7abc484831c0.png)

Have you noticed similar behavior? Has there been an update to Excel recently that could've broken desktop custom add-ins but not online add-ins?

**Comment by AlexJerabek** [comment]
Hi @redcirkle, 
Thanks for reporting this. It is a known issue with Office.js that's being investigated. 

@kbrandl, who is on point for this investigation?

**Comment by kbrandl** [comment]
@redcirkle @AlexJerabek I observed this issue yesterday afternoon (Jan 28) but it has since been fixed and I'm no longer able to repro. 

@redcirkle I'd suggest you try the following:

1. Stop the local server (localhost), if it's running -- i.e., close the Node.js window. 
2. [Clear the Office cache](https://docs.microsoft.com/office/dev/add-ins/testing/clear-cache).
3. Run `npm start` (which will start localhost, open Excel desktop, and sideload the add-in). 
4. Click the **Show taskpane** button in the ribbon to open the task pane.

Please let us know the result.

**Comment by DmytryEmery** [comment]
^--- @kbrandl I had the same issue, but it was only resolved by the ['Outlook'](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/clear-cache#outlook-windows-10) steps in the article you linked.  Just clearing the add-ins was not enough.

It leads me to suspect it was a edge/web browser caching issue going on.

**Comment by kbrandl** [comment]
@DmytryEmery good to know -- thanks for chiming in here. I'll update the article you linked to, to indicate that the procedure for clearing the (Edge) cache on Windows 10 applies to all hosts -- not just Outlook.

**Comment by kbrandl** [comment]
@DmytryEmery please try the steps described in the following article, to clear the Edge cache using Edge DevTools, and let us know whether your add-in is working properly after doing so. Thanks!

https://docs.microsoft.com/en-us/office/dev/add-ins/testing/clear-cache#outlook-windows-10

**Comment by redcirkle** [comment]
Yeah, that did the trick! We were able to get it working again once we followed the Outlook steps. 😃 

Thank you @kbrandl for the quick response! And thank you @DmytryEmery for calling that out as well!

**Comment by kbrandl** [comment]
Awesome -- thanks for the confirmation @redcirkle!  And thanks again @DmytryEmery for providing the solution here!  I'll update the docs today to indicate that the procedure for clearing the (Edge) cache on Windows 10 applies to all hosts -- not just Outlook.

**Comment by redcirkle** [comment]
@kbrandl Do you think this issue is mostly related to add-in development? Or do you think this issue could arise for our end-customers if released our add-in? We won't be able to ask our customers to download Microsoft Edge Devtools and clear their caches (our add-in shouldn't require any expertise outside of Excel itself).

**Comment by kbrandl** [comment]
@redcirkle good question. Based on my understanding of the **office-js** bug behind this issue, and how/when it has been fixed, I don't believe this problem will affect end-users of your add-in. I'm am curious to know the following, however, if you wouldn't mind sharing:

- Are you using an **Office Insider** build of Office? And, if yes, what level (e.g., "Monthly Channel (Targeted)" or something else)?

- What's the version and build number of Excel where you observed this problem?

- Are you by chance a Microsoft employee (running your add-in within Microsoft corpnet)?

**Comment by redcirkle** [comment]
Yeah, no problem!

- Are you using an Office Insider build of Office? And, if yes, what level (e.g., "Monthly Channel (Targeted)" or something else)? _//We aren't using an Office Insider build of Office_
- What's the version and build number of Excel where you observed this problem? _// Version 20001 Build 12430.20170 Click-to-Run_
- Are you by chance a Microsoft employee (running your add-in within Microsoft corpnet)? _//Yes to both, I'm a Microsoft employee running the add-in within Microsoft corpnet. However, I'm not sure if our add-in will run within the Microsoft corpnet or outside of it (could be either)_

**Comment by kbrandl** [comment]
@redcirkle thanks for the info! It's my understanding that this issue shouldn't affect anyone running add-ins outside of Microsoft corpnet. My MSFT alias is kibrandl -- please reach out to me via email if you'd like additional information about the potential impact of this issue within Microsoft corpnet, and I can connect you with internal folks who can provide this type of info. (Not sharing here on GitHub, since the info isn't applicable to the general public). Thanks!
