### ISSUE TITLE
Excel API : losing event after click on a "select" dropdown of taskpane

### ISSUE THREAD

**Issue by erharvey** [OfficeDev/office-js-docs-pr#1612]
Hi,

I have a simple plugin that registers an onChange and onSelectionChanged event on a table as follow:

```
function subscribeHandlers(ctx, sheet, viewModel, selectedRange) {
        var entitiesTable = sheet.tables.getItem(TABLE_NAME);
        entitiesTable.onChanged.add(function (e) { entitiesChangeHandler(e) });
        entitiesTable.onSelectionChanged.add(function (e) { selectionChangeHandler(e) });

        ctx.runtime.enableEvents = true;
        return ctx.sync()
    }

```

**The code work as expected**. However, as soon as click a "select" html control. (without any onChange event), all excel events stop working.  I don't even have to change the selected value. The problem can be reproduced with the following select ( Or any select for that matter)

```
  <label for="cars">Choose a car:</label>
            <select id="cars" name="cars">
                <option value="volvo">Volvo</option>
                <option value="saab">Saab</option>
                <option value="fiat">Fiat</option>
                <option value="audi">Audi</option>
            </select>

```
The issue cannot be reproduced when using a uifabric js drowndown as follow:
```

 <div class="ms-Dropdown" tabindex="0">
                <label class="ms-Label"><strong>Applications</strong></label>
                <i class="ms-Dropdown-caretDown ms-Icon ms-Icon--ChevronDown"></i>
                <select class="ms-Dropdown-select" id="SourceSelector">
                </select>
            </div>
```

I am using excel build 2001.

![image](https://user-images.githubusercontent.com/17800696/74894868-24580180-535e-11ea-8dfd-06e251dc6a97.png)

Thanks,
Eric

**Comment by AlexJerabek** [comment]
Hi @erharvey, 

There is a known issue with `onSelectChanged`. We have documented in the [Work with Events using the Excel JavaScript API](https://docs.microsoft.com/office/dev/add-ins/excel/excel-add-ins-events) article. The full discussion of the issue can be found on the [OfficeDev/office-js](https://github.com/OfficeDev/office-js/issues/533) repo.

Please add the following code to the <head> section of your HTML home page:
```HTML
<script> MutationObserver=null; </script>
```

Let me know if that helps. Thanks!

**Comment by keyur32** [comment]
@erharvey  - I don't think we heardback on the workaround but closing this. Please reactivate if this continues to be na issue. thanks.
