### ISSUE TITLE
Do we support Office-addin on OWA/browser on Iphone or we only support Office-addin on Outlook client (Outlook for IOs) ? After update -https://techcommunity.microsoft.com/t5/outlook-blog/outlook-on-your-mobile-browser-is-being-upgraded/ba-p/1125816#  customers are unable to use Office-addin on OWA on Iphone

### ISSUE THREAD

**Issue by HinaMS** [OfficeDev/office-js-docs-pr#1615]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 564bc140-d31e-f042-bd30-b8140b7db416
* Version Independent ID: 9953764b-39ca-d5c0-c1f8-5ca44ec2f472
* Content: [Outlook add-ins for Outlook Mobile - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/outlook-mobile-addins?source=docs)
* Content Source: [docs/outlook/outlook-mobile-addins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/outlook/outlook-mobile-addins.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@HinaMS We'll dig into this and let you know.

@exextoc Can you take a look?

Thanks.

**Comment by exextoc** [comment]
Can you please share the screenshot of OWA on Iphone. One the new OWA add-ins are not supported.

**Comment by HinaMS** [comment]
Hello Team,

Please find screen shot from IOs device.  Could you please explicitly document on article - https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/outlook-mobile-addins that “On the new OWA experience Office-add-ins are not supported.” and is there a roadmap for future to support this or it will never be supported and recommended way to use Office addin is only via Outlook for Android or Outlook for Ios on mobile device?

With new OWA experience OFF, please see below (images from IOs)

[cid:image001.jpg@01D5ED33.29B06A00]
We have Dynamics 365 and third party addin Evernote middle of screen and it works.

[cid:image002.jpg@01D5ED33.29B06A00]

[cid:image003.jpg@01D5ED33.29B06A00]


With New Outlook experience ON

[cid:image004.jpg@01D5ED33.29B06A00]

None of the Office-addin is visible , see below screen shot.

[cid:image005.jpg@01D5ED33.29B06A00]

See middle of screen shot, no office-addin

[cid:image006.jpg@01D5ED33.29B06A00]

Regards,
Hina Sharma

**Comment by HinaMS** [comment]
Hello Team,

Please find screen shot from IOs device.  Could you please explicitly document on article - https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/outlook-mobile-addins that “On the new OWA experience Office-add-ins are not supported.” and is there a roadmap for future to support this or it will never be supported and recommended way to use Office addin is only via Outlook for Android or Outlook for Ios on mobile device?

With new OWA experience OFF, please see below (images from IOs)

[cid:image001.jpg@01D5ED34.8747F560]
We have Dynamics 365 and third party addin Evernote middle of screen and it works.

[cid:image002.jpg@01D5ED34.8747F560]

[cid:image003.jpg@01D5ED34.8747F560]


With New Outlook experience ON

[cid:image004.jpg@01D5ED34.8747F560]

None of the Office-addin is visible , see below screen shot.

[cid:image005.jpg@01D5ED34.8747F560]

See middle of screen shot, no office-addin

[cid:image006.jpg@01D5ED34.8747F560]

Regards,
Hina Sharma

**Comment by exextoc** [comment]
Currently this feature of add-ins in new OWA is not a part of the product. we track Outlook add-in feature requests on our [user-voice page](https://officespdev.uservoice.com/forums/224641-general/category/131778-outlook-add-ins). Please add your request there. Feature requests on user-voice are considered, when we go through our planning process.
