### ISSUE TITLE
Is Windows Outlook 2016 list of Requirement Sets correct?

### ISSUE THREAD

**Issue by JSSut** [OfficeDev/office-js-docs-pr#1616]
The Outlook client support table lists Outlook 2016 for Windows supporting up to 1.4. For Mac it's up to 1.6.
This page suggests that Outlook 2016 build 7628.1000 or later supports SupportsPinning, which is one of the main additions in requirement set 1.5:
https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/action#supportspinning
This page suggests that pinnable task panes are only available to Office 365 Subscribers:
https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/pinnable-taskpane
, but 1.5 is supported by Exchange on Premise (which it may not have been when the article was originally written).
It's all a bit confusing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8e26a32-7523-2211-bde3-938cf94a76ec
* Version Independent ID: 80ad76d1-8a12-348f-dd6a-2f9392ed1f95
* Content: [Outlook JavaScript API requirement sets - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/outlook-api-requirement-sets#feedback)
* Content Source: [docs/reference/requirement-sets/outlook-api-requirement-sets.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/requirement-sets/outlook-api-requirement-sets.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thank you for reporting this discrepancy @JSSut.  @ElizabethSamuel-MSFT, can you please investigate?

**Comment by ElizabethSamuel-MSFT** [comment]
@JSSut Sorry about the confusion. We'll dig into this and get back to you.

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@JSSut Sorry about the confusion. We'll dig into this and get back to you.

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@exextoc Can you help clarify this? I'll then update the docs if need be. Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@JSSut The pinnable task panes feature was introduced in Mailbox requirement set 1.5. As such, the clients/servers (except mobile) that support that requirement set support this feature.

We'll update the docs to clarify this.

Thanks.
