### ISSUE TITLE
Are `msexchuid` and `amurl` immutable even if end user migrate Exchange Server?

### ISSUE THREAD

**Issue by NT-D** [OfficeDev/office-js-docs-pr#1620]
Thank you for writing clear document. Our team understand definition, but let me ask one question.

Are `msexchuid` and `amurl` immutable even if end user migrate Exchange Server? For example, some end users may migrate their on-premises Exchange Server to Office 365. When they start to use Office 365, are `msexchuid` and `amurl` same?

The background is we refer [this document](https://docs.microsoft.com/en-us/outlook/add-ins/authenticate-a-user-with-an-identity-token#map-the-token-to-a-user-in-your-backend) and try to make UserId from Exchange IdToken for backend. If these parameter keep same, we want to use this logic. If these params changed to another after migration, we need to consider it for making UserId.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 709d2fe0-b7b5-5008-218c-6e84f5565998
* Version Independent ID: d2cb30ef-4ba0-1d0b-d681-74dbf35bb6d0
* Content: [Inside the Exchange identity token in an Outlook add-in - Outlook Developer](https://docs.microsoft.com/en-us/outlook/add-ins/inside-the-identity-token#targetText=An%20Exchange%20user%20identity%20token,server%20that%20issued%20the%20token.)
* Content Source: [docs/add-ins/inside-the-identity-token.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/inside-the-identity-token.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@exextoc Can you take a look? Thanks.

**Comment by exextoc** [comment]
No, amurl and msexchuid will not be the same between Office365 and on-premise after migration.  If you are considering using the amurl+msexchuid as the mapping for  your addin's backend id, you will need to re-create the mapping after the user migrates.

**Comment by comingzero** [comment]
hi @exextoc team

thanks for your response.
