### ISSUE TITLE
Is support for Windows 7 still a requirement for Office Add-ins?

### ISSUE THREAD

**Issue by mrkiffie** [OfficeDev/office-js-docs-pr#1624]
With Windows 7 having reached end of life last month, is supporting Windows 7 still a requirement for developing, running and publishing the add-in to AppSource? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc3fde38-9149-0403-bd89-e2bf0269749a
* Version Independent ID: 1063c9be-57a5-2d53-a9f1-6b43dc0a8a81
* Content: [Requirements for running Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/requirements-for-running-office-add-ins#feedback)
* Content Source: [docs/concepts/requirements-for-running-office-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/concepts/requirements-for-running-office-add-ins.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by mscharlock** [comment]
Hi @mrkiffie - thanks for reading the Office Add-in docs and writing in with a question! I personally do not know the answer to this one, but I will be tagging my colleague @smaremanda who will likely have more information on this. Thanks!

**Comment by mscharlock** [comment]
Hello @mrkiffie - I've checked with @smaremanda on this and yes, currently you will still need to support Windows 7. I'm going to close this issue for the moment but if you have any follow up questions, please let me know by commenting on this thread and I will reopen. Thanks!
