### ISSUE TITLE
getAttachmentsAsync method does not return contentType

### ISSUE THREAD

**Issue by vbabeast** [OfficeDev/office-js-docs-pr#1656]
When using getAttachmentsAsync method the contentType property is missing.

## Expected Behavior
The resulting Office.AttachmentDetails would include the contentType property

## Current Behavior
The resulting Office.AttachmentDetails does not include the contentType property

## Steps to Reproduce, or Live Example
1. Create a new email.
2. Add an attachment to that email e.g. a .docx file
3. In your addin call Office.context.mailbox.item.getAttachmentsAsync
4. Observe that the Office.AttachmentDetails in the callback does not contain the contentType property

## Context
I need the contentType to pass to a third party api along with the attached file. 

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: Surface Pro 5
* Host [Excel, Word, PowerPoint, etc.]: Outlook version 2002 Build 12527.20242
* Office version number: Office 365 Pro Plus 
* Operating System: Win 10 version 1909 build 18363.657
* Office Api version in manifest v1.8

## Useful logs
![image](https://user-images.githubusercontent.com/48421920/76171693-f47c7b00-61f2-11ea-8880-80b457cae9cf.png)

**Comment by ElizabethSamuel-MSFT** [comment]
Related PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43048

**Comment by ElizabethSamuel-MSFT** [comment]
The docs have been updated and should be published soon.

Thanks.
