### ISSUE TITLE
Property 'Error' does not exist on type 'typeof CustomFunctions'.

### ISSUE THREAD

**Issue by benj-spectory** [OfficeDev/office-js-docs-pr#1658]
i'm using version 1.5 and i'm getting the error: Property 'Error' does not exist on type 'typeof CustomFunctions'. when i try to do this: new CustomFunctions.Error(...)
i created a project using yo.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9129db27-b5f6-244b-cf8f-26e5053fb7a9
* Version Independent ID: 8146bce5-31d1-ba6d-df3f-dfde97aac2fd
* Content: [Handle and return errors from your custom function (preview) - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-errors#feedback)
* Content Source: [docs/excel/custom-functions-errors.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/custom-functions-errors.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @benj-spectory, 
Errors for custom functions are currently in public preview. You'll need to join [Office Insider](https://insider.office.com/join) to have access to this feature. What version of Excel are you running and for what platform?

**Comment by benj-spectory** [comment]
i'm running version 2002 on windows or on the web using chrome browser (on windows)

**Comment by AlexJerabek** [comment]
@benj-spectory, and just to be clear, you're in the Office Insider program?

Tagging @mscharlock to also follow up.

**Comment by benj-spectory** [comment]
@AlexJerabek I don't know what it is...
what is it? and why do i need it to use custom function errors

**Comment by AlexJerabek** [comment]
Hi @benj-spectory,

The Custom Function error feature is in public preview, meaning the feature is not available in standard builds of Office. You'll need to have a preview version of Office. [Office Insider](https://insider.office.com/en-us/join) is a program that allows developers to test out upcoming features and provide feedback before they are generally available. This also means that preview features are subject to change, and their use is not permitted in add-ins submitted to the store.

**Comment by mscharlock** [comment]
Hi @benj-spectory, 
Just wanted to check if @AlexJerabek's description helped you and if you need anything else from us on this issue. If so, let us know, otherwise we will go ahead and close the issue. Thanks :)

**Comment by benj-spectory** [comment]
@mscharlock he answered my question...
@AlexJerabek do you know when this feature will be available for use not as part of Office Insider?
thanks

**Comment by AlexJerabek** [comment]
@benj-spectory, We don't have a set release date at this time. I'll loop in the feature's PM, @RuoyingLiang to verify.

**Comment by keyur32** [comment]
Added "status: in backlog".   @benj-spectory  - I suggest you stayed tuned to our blog and Office Add-in monthly community call, for when this feature will roll out.  @RuoyingLiang - please update when rolled out. Thanks!

**Comment by RuoyingLiang** [comment]
Sure. The feature to return/throw CustomFunctions.Error hasn't released to production. I will update here once it's public.

**Comment by AlexJerabek** [comment]
Hi @benj-spectory, 

@alison-mk just checked in #2203, which adds information about the current error handling story for Custom Functions in Excel. I'm going to close this issue, but please open a new issue if you need more assistance. 

Thanks!
