### ISSUE TITLE
Add-In Icon not visible on macbook pro retina, 13inch early2015

### ISSUE THREAD

**Issue by mohammedshoib** [OfficeDev/office-js-docs-pr#1659]
Hello,

I followed this document and intalled the outlook add-in successfully on my macbook pro, i can also see the add-in on ribbon but for some reason i am not able to see icon on the ribbon only label I can see but same procedure I followed on my windows machine ribbon icon shows.

MAC outlook info
Version: 16.35 (20030802)

Do I need to format the icon specifically for mac book?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a59958d2-f428-9ca2-3440-a5af662386c0
* Version Independent ID: dcaf0b5b-08ea-c437-130b-342a1be62a16
* Content: [Tutorial: Build a message compose Outlook add-in - Office Add-ins](https://docs.microsoft.com/en-gb/office/dev/add-ins/tutorials/outlook-tutorial?view=outlook-js-preview#feedback)
* Content Source: [docs/tutorials/outlook-tutorial.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/tutorials/outlook-tutorial.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for reporting this issue.

@exextoc, Could you please investigate?

**Comment by exextoc** [comment]
@mohammedshoib Can you please screenshot from Macbook retina pro to understand this better?

**Comment by mohammedshoib** [comment]
<img width="646" alt="Screenshot 2020-03-12 at 11 25 35 AM" src="https://user-images.githubusercontent.com/797999/76491749-71f2f600-6454-11ea-8452-c845263c25ff.png">


@exextoc , you can find the screen shot, you can refer for "Show Task pane" add-in on ribbon.

**Comment by mohammedshoib** [comment]
<img width="646" alt="Screenshot 2020-03-12 at 11 25 35 AM" src="https://user-images.githubusercontent.com/797999/76491902-d9a94100-6454-11ea-867f-59f763451a5c.png">

@exextoc  you can check for "show taskpane" in ribbon. It has label but no icon

**Comment by exextoc** [comment]
Thanks @mohammedshoib for sharing the screenshot. We are looking into this.

**Comment by exextoc** [comment]
We were not able to repro this issue with Outlook 16.35. Can you please mention MacOS and Macbook model, so we can repro this issue. I have attached the screenshot of my MacBook. 
<img width="1920" alt="Screenshot 2020-03-19 at 10 16 18 PM" src="https://user-images.githubusercontent.com/28549921/77092244-99872700-6a2f-11ea-8f2b-90a985e3301c.png">

**Comment by exextoc** [comment]
We are not able to repro this. Can you share the icon dimension and size or the icon Url?
