### ISSUE TITLE
Root page of addin not reloaded

### ISSUE THREAD

**Issue by timothyhoffmann** [OfficeDev/office-js-docs-pr#1688]
Clicking the Clear Cache button does not force Outlook 365 64-bit to reload the taskpane.html file from the IIS server.  This results in out of date code running.  OWA properly reloads the taskpane.html file when it changes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e273e29-10ac-440e-634e-588b5208e484
* Version Independent ID: a5a6dc8a-b504-686e-80ce-45aabd6f832b
* Content: [Clear the Office cache - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/clear-cache#feedback)
* Content Source: [docs/testing/clear-cache.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/clear-cache.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by exextoc** [comment]
What Outlook build number are you on? Could you also share your windows version

**Comment by exextoc** [comment]
Newer versions of Outlook should be using Edge WebView and to refresh you could try using ctrl + F5

**Comment by timothyhoffmann** [comment]
A reboot seemed to fix the problem.  I've put up new versions of the AddIn and Outlook is properly fetching the updated JS files.
