### ISSUE TITLE
Deployment Steps

### ISSUE THREAD

**Issue by bwong199** [OfficeDev/office-js-docs-pr#1696]
Hi, 

It would be very nice to see some deployment steps to Azure.

https://github.com/OfficeDev/generator-office/issues/490

Because I just tried to deploy it and got  the following errors:

Error: Unable to start debugging.
Error: Unable to sideload the Office Add-in. 
Error: Platform not supported: linux. 

Thanks. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6ed3136-1d12-66c2-a8b1-1e7e43553aae
* Version Independent ID: 0e40308a-2d3d-a27b-04d5-1bdd7c09b501
* Content: [Build your first OneNote task pane add-in - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/onenote-quickstart#feedback)
* Content Source: [docs/quickstarts/onenote-quickstart.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/quickstarts/onenote-quickstart.md)
* Product: **onenote**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@bwong199 Thanks for asking about this. Please see if this article about [hosting an Office Add-in on Microsoft Azure](https://docs.microsoft.com/office/dev/add-ins/publish/host-an-office-add-in-on-microsoft-azure) helps.

I'll close this issue for now but if you hit further issues or have other feedback, let us know.

Thanks.
