### ISSUE TITLE
Internal Org Deployment

### ISSUE THREAD

**Issue by bwong199** [OfficeDev/office-js-docs-pr#1697]
It's also nice to have this supported by Centralized Deployment for internal use because when I go Office365 &gt; Admin &gt; Settings &gt; Add-ins &gt; Deploy Add-In, it says "The Centralized Deployment service lets you deploy ‎Office‎ Web add-ins to users of ‎Excel‎, ‎Outlook‎, ‎PowerPoint‎ and ‎Word‎." so unless it's for public usage, you really can't deploy this as an internal usage.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6ed3136-1d12-66c2-a8b1-1e7e43553aae
* Version Independent ID: 0e40308a-2d3d-a27b-04d5-1bdd7c09b501
* Content: [Build your first OneNote task pane add-in - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/onenote-quickstart#feedback)
* Content Source: [docs/quickstarts/onenote-quickstart.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/quickstarts/onenote-quickstart.md)
* Product: **onenote**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by bwong199** [comment]
https://www.advaiya.com/blog/create-deploy-word-add-sharepoint/

The workaround is to deploy to a sharepoint site.

**Comment by ElizabethSamuel-MSFT** [comment]
@bwong199 Seems like you have a resolution so I'll go ahead and close this issue.

This article also discusses [deployment options for Office Add-ins](https://docs.microsoft.com/office/dev/add-ins/publish/publish).

Thanks.
