### ISSUE TITLE
What to do when things go wrong

### ISSUE THREAD

**Issue by smrtRock** [OfficeDev/office-js-docs-pr#1698]
So loaded this up just for some quick demo and sadly got a certificate error.  

"Content was blocked because it was not signed by a valid security certificate" 

Now imaging this is probably solved by placing the self signed certificate into a trusted store or some other workaround, this would be nice if we could point to what happens when things don't just work

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6ed3136-1d12-66c2-a8b1-1e7e43553aae
* Version Independent ID: 0e40308a-2d3d-a27b-04d5-1bdd7c09b501
* Content: [Build your first OneNote task pane add-in - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/onenote-quickstart#feedback)
* Content Source: [docs/quickstarts/onenote-quickstart.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/quickstarts/onenote-quickstart.md)
* Product: **onenote**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @smrtRock 

Thanks for reporting this. I just went through the OneNote quickstart and did not see a certificate error. Could you confirm a few things for me?
- Are you using the latest version of yo office? Make sure to run `npm install -g yo generator-office` before starting the quickstart.
- Which browser are you using?
- When in the quickstart are you encountering the certificate error? Is it when you select **Show Taskpane** in OneNote?

**Comment by smrtRock** [comment]
Yes before running the quickstart I did the npm install -g yo generator-office and npm update

Browser does not matter either Edge or Chrome same results

The error happens when you select Show Taskpane in OneNote

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by AlexJerabek** [comment]
Thanks for the information @smrtRock. 

@TCourtneyOwen, can you please help investigate this issue?

**Comment by AlexJerabek** [comment]
Also, the information in this article may help unblock you: https://docs.microsoft.com/en-us/office/dev/add-ins/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins

It contains information on sideloading add-ins for testing and handling the certificates. Please let me know if that helps you.

**Comment by smrtRock** [comment]
So I figured it out though it could be better.  

When Webpack creates the cert it did not get registered so Saved it and loaded it to the trusted providers and all was well.

**Comment by smrtRock** [comment]
So one other thing:  while attempting to sideload on the desktop version I cannot seem to see the local share. 

Any suggestions?

**Comment by AlexJerabek** [comment]
Thanks @smrtRock. That last point might be related to #1717.

**Comment by AlexJerabek** [comment]
@smrtRock, the desktop client for OneNote doesn't support add-ins (here's the [availability page](https://docs.microsoft.com/en-us/office/dev/add-ins/overview/office-add-in-availability#onenote)). Are you referring to an add-in for a different host?

**Comment by ElizabethSamuel-MSFT** [comment]
@smrtRock Seems like your cert issues have been resolved and, as AlexJerabek noted, OneNote add-ins are only supported in browser. As such, closing this out.

Thanks.
