### ISSUE TITLE
npm run dev-server not working

### ISSUE THREAD

**Issue by quantrpeter** [OfficeDev/office-js-docs-pr#1706]
npm run dev-server not working, if i create a project with project type "Office Add-in Task Pane project supporting single sign-on"

/Users/peter/workspace/outlook-upload-attachment-to-sharepoint&gt;npm run dev-server
npm ERR! missing script: dev-server

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/peter/.npm/_logs/2020-03-28T04_07_24_982Z-debug.log

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 930ce4fc-c8b8-f756-f03f-a716f1ef7883
* Version Independent ID: 753a2e38-9430-25bb-5409-b7eed9c88e47
* Content: [Build your first Outlook add-in - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/outlook-quickstart?tabs=yeomangenerator#feedback)
* Content Source: [docs/quickstarts/outlook-quickstart.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/quickstarts/outlook-quickstart.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@quantrpeter Sorry you're facing this issue and thanks for letting us know.

@TCourtneyOwen Can you take a look?

Thanks.

**Comment by TCourtneyOwen** [comment]
@quantrpeter There isn't a "dev-server" script in the SSO project.  To start the server you need to run "npm run start:server"

**Comment by ElizabethSamuel-MSFT** [comment]
@quantrpeter Can you try [this quick start](https://docs.microsoft.com/office/dev/add-ins/quickstarts/sso-quickstart) instead? This should provide the guidance you need to work with yo office and the SSO template.

Thanks.
