### ISSUE TITLE
Developers need `Contained in` information

### ISSUE THREAD

**Issue by NT-D** [OfficeDev/office-js-docs-pr#1707]
Because this document doesn't have `Contained in` information, it's hard for developers to understand expected parent element.

Would you please consider to add `Contained in` information as like RequestedHeight element page ? 
https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/requestedheight

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af787b7c-c69c-762b-59c8-53bda7a56024
* Version Independent ID: 805c4596-7aff-f93a-bf35-61c01d570742
* Content: [RequestedWidth element in the manifest file - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/requestedwidth#feedback)
* Content Source: [docs/reference/manifest/requestedwidth.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/manifest/requestedwidth.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@NT-D Thanks for raising this issue.

@Rick-Kirkham Can you take a look?

Thanks.

**Comment by Rick-Kirkham** [comment]
This was fixed as a side effect of this commit: https://github.com/OfficeDev/office-js-docs-pr/commit/499f1417aae79173437e894f82f301cbc1c1ad5c#diff-5a8cac22d242af2f0179e0f7adf07d15

**Comment by NT-D** [comment]
thank you!
