### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by quantrpeter** [OfficeDev/office-js-docs-pr#1708]
C:\Users\Peter\Desktop\My Office Add-in&gt;npm run configure-sso

&gt; office-addin-taskpane-sso@0.0.0 configure-sso C:\Users\Peter\Desktop\My Office Add-in
&gt; office-addin-sso configure manifest.xml

(node:14720) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token  in JSON at position 980
    at JSON.parse (&lt;anonymous&gt;)
    at C:\Users\Peter\Desktop\My Office Add-in\node_modules\office-addin-sso\lib\configure.js:188:40
    at Generator.next (&lt;anonymous&gt;)
    at C:\Users\Peter\Desktop\My Office Add-in\node_modules\office-addin-sso\lib\configure.js:6:71
    at new Promise (&lt;anonymous&gt;)
    at __awaiter (C:\Users\Peter\Desktop\My Office Add-in\node_modules\office-addin-sso\lib\configure.js:2:12)
    at childProcess.exec (C:\Users\Peter\Desktop\My Office Add-in\node_modules\office-addin-sso\lib\configure.js:182:95)
    at ChildProcess.exithandler (child_process.js:285:7)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
(node:14720) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14720) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3020ff5d-ee3b-976b-f1ad-0ed378fdb47b
* Version Independent ID: 5de0010a-6435-154b-a7fd-fd2ea05ebc0b
* Content: [Use the Yeoman generator to create an Office Add-in that uses SSO (preview) - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/sso-quickstart)
* Content Source: [docs/quickstarts/sso-quickstart.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/quickstarts/sso-quickstart.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@quantrpeter Sorry that you're hitting this issue and thanks for letting us know.

@TCourtneyOwen Can you take a look?

Thanks.

**Comment by quantrpeter** [comment]
@TCourtneyOwen  no space in my tenant name, thx

**Comment by TCourtneyOwen** [comment]
@quantrpeter Did you make any modifications to the base template after creating it and before running "configure-sso"?  Also, could you please check the version of the office-addin-sso and see if it's running the latest version of the package - 1.0.12.  If it's not, please update the version of the package to the latest

**Comment by TCourtneyOwen** [comment]
One more thing, can you please provide all the output of the configure-sso process so I can determine at what stage it's failing for you? For example, here's my output that I just generated:

Opening browser for authentication to Azure. Enter valid Azure credentials
Login was successful!
Registering new application in Azure
Application was successfully registered with Azure
Setting identifierUri
Setting signin audience
Granting admin consent
Setting application secret
App secret is Bqs8H2I@/h2/K7@9qlL=FNkB/.UH2vQ:
Adding application secret for Office-Addin-NodeJS-SSO to Windows Credential Store
Updating source files with application ID and port
Logging out of Azure now
Application with id 1d90426e-5543-4b04-b4a2-22c1bdfc1b8c successfully registered in Azure.  Go to https://ms.portal.azure.com/#home and search for 'App Registrations' to see your application
