### ISSUE TITLE
in outlook, it popup a new browser

### ISSUE THREAD

**Issue by quantrpeter** [OfficeDev/office-js-docs-pr#1709]
in outlook, it popup a new browser rather than the dialog inside the original browser, it is normal?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a714626a-058a-789e-6add-5e9dfb21fd1f
* Version Independent ID: 1b88a28c-fc36-4518-2808-7246f08d9753
* Content: [Use the Office dialog API in your Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins)
* Content Source: [docs/develop/dialog-api-in-office-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/dialog-api-in-office-add-ins.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by exextoc** [comment]
@quantrpeter Can you provide us with the version of Outlook that you are using? Also, are you using Outlook on Windows or MacOS?
