### ISSUE TITLE
Can't resolve      Microsoft.Office.WebExtension.EventType.DialogMessageReceived

### ISSUE THREAD

**Issue by rougean** [OfficeDev/office-js-docs-pr#1710]
Following the Add-in Tutorial [https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/excel-tutorial](url)

The call to Microsoft.Office is not working correctly. Can't find the Microsoft object.

Is this correct?

dialog.addEventHandler(Microsoft.Office.WebExtension.EventType.DialogMessageReceived, processMessage);

**Comment by Rick-Kirkham** [comment]
The full name has been shortened to [Office.EventType.DialogMessageReceived](https://docs.microsoft.com/en-us/javascript/api/office/office.eventtype?view=common-js). I'm closing this, but feel free to ask that it be reopened if you continue to have trouble with the API.

**Comment by Rick-Kirkham** [comment]
Something went wrong with this issue. It should not have been closed as Not Actionable. The fully qualified name of the event should be corrected wherever it appears in the docs.

**Comment by Rick-Kirkham** [comment]
This is fixed in the source files and should be published in the next few days.

**Comment by redlab-chris** [comment]
I was following this example and noticed that this reference is not updated:

loginDialog.addEventHandler(Microsoft.Office.WebExtension.EventType.DialogMessageReceived, processMessage);

https://github.com/OfficeDev/PnP-OfficeAddins/blob/15e3bc864bdce40bc219b4b078fe6331a17adb0c/Samples/auth/Office-Add-in-NodeJS-SSO/Begin/public/javascripts/fallbackAuthTaskpane.js#L9

**Comment by davidchesnut** [comment]
Hi @redlab-chris,

Thanks for catching this. I'm reopening this issue and will update that sample code. 

Thanks!
David

**Comment by AlexJerabek** [comment]
@davidchesnut, should we transfer this issue to https://github.com/OfficeDev/Office-Add-in-samples?
