### ISSUE TITLE
Support for Blazor

### ISSUE THREAD

**Issue by bilalchraibi** [OfficeDev/office-js-docs-pr#1711]
Are you planning to add support for Blazor client-side when it will be released in May?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1eb88c1-06fc-dfb1-67ee-da88fa7e985a
* Version Independent ID: 8ed13e25-a7bd-25ef-5525-eb1000148578
* Content: [Excel add-ins overview - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-overview?source=docs#feedback)
* Content Source: [docs/excel/excel-add-ins-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/excel-add-ins-overview.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@bilalchraibi Thanks for asking about support for Blazor.

@sumurthy / @nokafor Can you answer this question?

Thanks.

**Comment by sturlath** [comment]
So @sumurthy and @nokafor! Any chance you can give us something on this topic?

**Comment by sturlath** [comment]
@ElizabethSamuel-MSFT any change to get some feedback on this? The issue was first raised in March (more than a half a year ago)... you surely must have a roadmap with Blazor either on or off it. It would be really helpful to have some idea where this is heading. 

The silence makes me want to believe that there is going to be some big (?)  reveal where Blazor as a plugin will be allowed.

**Comment by davidchesnut** [comment]
Hi @bilalchraibi and @sturlath 

Sorry for the slow delay in response here. We don’t have support for Blazor today as we’re currently focused on JavaScript. Please let us know more about this scenario on our UserVoice page at https://officespdev.uservoice.com/. There’s actually already a [Blazor request](https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/39203794-blazor-development-support) there you can upvote.

Thanks!

**Comment by robertmclaws** [comment]
Hello! It seems like this UserVoice site is down... is where do we vote for new features now?

**Comment by AlexJerabek** [comment]
Hi @robertmclaws,

Microsoft has transitioned from UserVoice to Tech Community as the ideas and suggestions platform. Here is the [Microsoft 365 Developer Platform Tech Community page](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform) where you can submit and upvote ideas.
