### ISSUE TITLE
unable to see my app in shared folder

### ISSUE THREAD

**Issue by davvit** [OfficeDev/office-js-docs-pr#1717]
I built my project from scratch using VS Excel office template. 
I did not make any change to the manifest file the project created.
I created new folder under c:\ and followed the instructions on this page.
Once i restarted Excel i dont see app under Shared Folder section.

![image](https://user-images.githubusercontent.com/4433698/78185225-57e37c80-7430-11ea-8183-acd5dbf0cb55.png)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ddce0bd-5c66-c2cb-0640-ee4d5bd401c5
* Version Independent ID: b5d4bc26-a43e-4a85-e7d5-fe4fc4ec3d0d
* Content: [Sideload Office Add-ins for testing - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins#feedback)
* Content Source: [docs/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@davvit Sorry you're hitting this issue and thanks for letting us know.

@AlexJerabek Can you take a look?

Thanks.

**Comment by davvit** [comment]
i have looked at this a little more since this question and the guide says  at the bottom to 
"Be sure to specify the URL in the SourceLocation element of the manifest file."

I believe currently the SourceLocation in the manifest is looking at the VS project path and when i move it to the shared location it is no longer valid. maybe the template should use absolute path instead of relative path for SourceLocation.

@ElizabethSamuel-MSFT

**Comment by AlexJerabek** [comment]
Hi @davvit, 
I'm adding @nokafor and @TCourtneyOwen to help investigate. A similar issue was reported in #1698 as well.

**Comment by ElizabethSamuel-MSFT** [comment]
@TCourtneyOwen Any update on this? Thx.

**Comment by davidchesnut** [comment]
Hi @davvit 

For Visual Studio, you need to use the manifest that gets built at *{projectpath}*\*{projectfolder}*\bin\Debug\OfficeAppManifests and copy that version to your shared add-ins folder. 

I'll add a note for Visual Studio users to the page. 

Thanks!

**Comment by NickDarvey** [comment]
We're also seeing this for a user we're trying to test our Add-in with, but not with others. Same manifest. Manifest passes a `office-addin-manifest validate`.
Our `SourceLocation` is a publicly addressable site, https. We can sideload it into the web version on their computer so the site is definitely accessible for them.

Are there any means of debugging so we can investigate why it might not show any Add-ins?

**Comment by davidchesnut** [comment]
Hi @NickDarvey,

You might try [using runtime logging to debug the loading issues.](https://docs.microsoft.com/office/dev/add-ins/testing/runtime-logging).
Also check the version of Office (between the one that works, and the one that doesn't) to see if maybe it is related to the version.
Finally, clearing the Office cache often resolves sideloading issues. See [Clear the Office cache](https://docs.microsoft.com/office/dev/add-ins/testing/clear-cache)

Hope this helps,
David
