### ISSUE TITLE
Examples for given actions would be very illuminating

### ISSUE THREAD

**Issue by naterush** [OfficeDev/office-js-docs-pr#1751]
Specifically the phrase "It also enables you to run code when the document opens, or to run code while the task pane is closed."

I've been trying to get my add-in to run code upon opening of an Excel document for a while now, so this feature is awesome for me! Are there any examples you could add to the documentation to explain how to do this? 

Thanks so much - this documentation has generally been great!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a1bb1ec-f7c0-61c7-bd50-4018a2726e3a
* Version Independent ID: dabd68f4-f474-1f01-0022-b2fe55eaafa3
* Content: [Configure your Excel add-in to share the browser runtime (preview) - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/configure-your-add-in-to-use-a-shared-runtime)
* Content Source: [docs/excel/configure-your-add-in-to-use-a-shared-runtime.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/configure-your-add-in-to-use-a-shared-runtime.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @naterush, 

Have you looked at the [Shared Runtime PnP sample](https://github.com/OfficeDev/PnP-OfficeAddins/tree/master/Samples/excel-shared-runtime-scenario)? I believe this should help explain how to use the new runtime APIs.

I'll look into highlighting this better from the documentation page this issue is associated with.

**Comment by AlexJerabek** [comment]
Hi @naterush,

I added better visibility to the PnP sample in the documentation, so the issue was closed. Please let me know if there's anything you need.

Thanks!

**Comment by naterush** [comment]
@AlexJerabek This is very helpful. Thank you for the quick response and updating - it is greatly appreciated!
