### ISSUE TITLE
Auto-update functions

### ISSUE THREAD

**Issue by Alex-Mann** [OfficeDev/office-js-docs-pr#1754]
Is there a way to auto-update functions without having to run `npm run build` and then go the Insert&gt;My Addins&gt;MY_ADDIN_NAME each time? This would be really useful when developing custom functions in realtime..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a30fb645-c853-a93a-4137-1e2bf7398a11
* Version Independent ID: 75fb99ac-72e8-7bdc-ff1b-85e7ed930d50
* Content: [Excel custom functions tutorial - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/excel-tutorial-create-custom-functions?tabs=excel-windows#feedback)
* Content Source: [docs/tutorials/excel-tutorial-create-custom-functions.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/tutorials/excel-tutorial-create-custom-functions.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Alex-Mann** [comment]
Additionally, using Script Lab online, it would be good to somehow have a smart refresh and not have to update / reload the plugin eachtime you change the underlying code for a function.

**Comment by AlexJerabek** [comment]
Hi @Alex-Mann, 

Thanks for submitting an issue. I'm tagging @mscharlock to address your first question.

As for Script Lab, I'd recommend creating an issue on the [Script Lab GitHub repo](https://github.com/OfficeDev/script-lab/issues). That's the best way to suggest new features for the add-in.

**Comment by Alex-Mann** [comment]
I guess it should be noted that I'm using MacOS at the moment, and by reading the Debugging section it seems like you can do this, but I wasn't able to get it working.

**Comment by mscharlock** [comment]
Nope - unfortunately dynamic debugging and loading of functions aren't possible at this time. Something we can definitely tell our PMs that folks are requesting though. I agree, it would be helpful. :) let me know if you have other questions.

**Comment by Alex-Mann** [comment]
Sounds good!

**Comment by mscharlock** [comment]
Great! I will close this issue :) If you need anything else related to this, feel free to comment and I can reopen. Thanks!
