### ISSUE TITLE
How to prevent an AddIn showing up in Outlook on Windows, only Web version should use it.

### ISSUE THREAD

**Issue by LokiMidgard** [OfficeDev/office-js-docs-pr#1758]
I have an Add-In that uses the SendTo Function.

This is supported by Exchange 2016 CU6 and works great in OWA. However the AddIn is also loaded in the Windows Version of Outlook. There it does not work and prevent the sending of mails. 

The feature was added in API set 1.8. But is supported on older Exchange servers as mentioned. So setting the API set to 1.8 will prevent us from roling it out to our currend Exchage Servers :/

I need a way to define that the Addin should only be loaded in the Web interface not the windows version of Outlook.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb3c39f4-bf7f-a54b-1671-a3a3a5a4ce92
* Version Independent ID: fa858a5c-a2a7-5cad-c312-f62bcfcd5115
* Content: [DesktopFormFactor element in the manifest file - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/desktopformfactor)
* Content Source: [docs/reference/manifest/desktopformfactor.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/manifest/desktopformfactor.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by mscharlock** [comment]
Hi @LokiMidgard, thanks for writing in and reading our docs! @ElizabethSamuel-MSFT do you happen to know on this one? I am less familiar with Outlook, but you might also know the right person to route this issue to.

**Comment by ElizabethSamuel-MSFT** [comment]
@exextoc Can you take a look? Thanks.

**Comment by exextoc** [comment]
This is not possible today. We track Outlook add-in feature requests on our user-voice page.
It looks like the feature you want has been requested by others already. Please upvote the [existing request](https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/5129669-allow-mail-apps-to-be-owa-only). Feature requests on user-voice are considered when we go through our planning process.

**Comment by LokiMidgard** [comment]
@exextoc Thank you.

I added my votes to this request.
