### ISSUE TITLE
Suspend calculation doesn't suspend all calculation?

### ISSUE THREAD

**Issue by naterush** [OfficeDev/office-js-docs-pr#1762]
I'm attempting to do the following operation: I have a Sheet1, Sheet2, and Sheet3. On Sheet2, there is a reference to a cell on Sheet1 (e.g. A1 on Sheet2 is defined as =Sheet1!A1, for example). I'd like to be able to 1) suspend calculation, 2) delete Sheet1, and then 3) rename Sheet3 to Sheet1, and finally 4) context.sync (or re-enable calculation). The goal of suspending calculation is so that the reference in Sheet2 to the cell in Sheet1 does not become undefined in the interim. When the computation terminates, the goal would be that the reference in Sheet2 points to the new Sheet1 (or the old Sheet3).

However, as far as I can tell, app.suspendApiCalculationUntilNextSync() doesn't actually suspend all calculation. If we perform the above steps, then before the reference in Sheet2 ends up being undefined.

Would it be possible to clarify what calculation is actually suspended? It'd be nice to know exactly what we can pause. 

More than that, if you have any suggestions about how to accomplish the above (e.g. deleting then replacing a sheet without destroying references to it), they would be greatly appreciated! Otherwise, I fear a month of work on our Add-in goes down the drain...

Thanks in advance for any clarification and feedback! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6604be51-c7ff-cc75-3721-4eb3cbd2bbb3
* Version Independent ID: 3ce7f707-86f9-f660-9a3b-55d2c7453cb7
* Content: [Excel JavaScript API performance optimization - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/performance#suspend-excel-processes-temporarily)
* Content Source: [docs/excel/performance.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/performance.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @naterush, 

I'll reach out to the product team and start looking into this issue. 

Off the top of my head, it seems like Excel is linking the references based on sheet ID (not name) and doing something to try to protect the references it thinks you want. Those reference adjustments might be treated as separate operations from the calculation engine. You can probably check this manually by going to the calculation options in the Excel UI (under the Formulas tab).

In case the suspend calculations APIs won't work in this capacity, have you considered using special cells as a workaround? [Range.getSpecialCells](https://docs.microsoft.com/en-us/javascript/api/excel/excel.range?view=excel-js-preview#getspecialcells-celltype--cellvaluetype-) can get all the formulas in a specific range. You could then store those values, perform your worksheet operations, then reapply the formulas to the original cells. Would that be viable? I'd hate for you to lose progress on your add-in.

**Comment by naterush** [comment]
Hi Alex, thanks so much for getting back to me. Yes, I assumed that it was linked based on ID rather than name as well - it'd be great to know if you could turn this off programmatically and temporarily have references to invalid sheet names.

Thanks for the suggestion. We'll use those functions to find all formulas, save them, and then reapply them at the end. We're not sure that will scalable enough for our needs, but in any case the suggestion is very helpful for now. 

Please do let me know if there is any development understanding exactly what goes on behind the scenes, or if there's anyway to programmatically stop this sort of updating temporarily. Thanks again for the help!

**Comment by AlexJerabek** [comment]
Hi @naterush, 

I'm glad this unblocks you for now. I saw your [StackOverflow post](https://stackoverflow.com/questions/61285393/delete-and-replace-sheet-without-destroying-references-to-it-in-excel-javascript/61299766#61299766) as well. The person responding, Raymond, is a member of product team.

I'll adjust the documentation to clarify what "calculations" imply and tag this thread in the resulting PR.

**Comment by AlexJerabek** [comment]
@naterush I've created PR #1777 to clarify this behavior. I'd also recommend heading to [User Voice](https://officespdev.uservoice.com/) to request the exact functionality you're looking for. That helps us track and prioritize feature requests.
