### ISSUE TITLE
Is Note about avalibility on Outlook connected to Exchange correct?

### ISSUE THREAD

**Issue by LokiMidgard** [OfficeDev/office-js-docs-pr#1763]
The note says

> The on-send feature is currently supported for Outlook on the web in Exchange Online (Office 365), Exchange 2016 on-premises (Cumulative Update 6 or later), and Exchange 2019 on-premises (Cumulative Update 1 or later). This feature is also available in the latest Outlook builds on Windows and Mac, connected to Exchange Online (Office 365). The feature was introduced in requirement set 1.8 (see current server and client support for details).

I understand it that way, that the `on-send` will not work, in Outlook 2016 connected to an Exchange 2016. Because it must be connected to Office 365.

However I have an Outlook addIn written and it uses the `on-send` feature and it works on an Outlook 2016 connected to Exchange 2016 CU 6.

Did I missinterprete the note?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e12d688-9620-e8f2-871d-922ec98008b5
* Version Independent ID: a8b409f3-44f7-97e5-d722-cbf04edc0653
* Content: [On-send feature for Outlook add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/outlook-on-send-addins?tabs=windows)
* Content Source: [docs/outlook/outlook-on-send-addins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/outlook/outlook-on-send-addins.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by mscharlock** [comment]
@ElizabethSamuel-MSFT can you route this to right person? Thanks!

**Comment by exextoc** [comment]
Outlook for Office 365 supports `on-send` add-ins when connected to Exchange 2016 CU6. Could you provide the version of Outlook you are using?

**Comment by LokiMidgard** [comment]
I use Outlook 2016 (Build 12228.20332) Connected to Exchange 2016 CU6 and it works (which I find great).

**Comment by exextoc** [comment]
It appears that version of Outlook is part of Office 365. We will update our documentation to make sure this is reflected

**Comment by ElizabethSamuel-MSFT** [comment]
@LokiMidgard We've updated the docs to clarify this. The changes should be published soon.

Let us know if you need further clarification or face some other issue.

Thanks!
