### ISSUE TITLE
Possible typo in the document

### ISSUE THREAD

**Issue by sumurthy** [OfficeDev/office-js-docs-pr#1764]
Is this a mistake. See one the bullet points in the document.
&gt; A PivotTable contains a PivotTableCollections that has multiple PivotHierarchies.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf942d54-3ee5-2476-e11f-0b658e0bb189
* Version Independent ID: 2a671958-54a3-f477-6624-f2bdc7c133e5
* Content: [Work with PivotTables using the Excel JavaScript API - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-pivottables?view=excel-js-preview#feedback)
* Content Source: [docs/excel/excel-add-ins-pivottables.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/excel-add-ins-pivottables.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @sumurthy, 
That does sound like a mistake. I'll make the correction soon.

**Comment by AlexJerabek** [comment]
Fixed with https://github.com/OfficeDev/office-js-docs-pr/pull/1766
