### ISSUE TITLE
Please provide details for Office 365 Pro Plus SAC and SAC-T releases

### ISSUE THREAD

**Issue by stukey** [OfficeDev/office-js-docs-pr#1772]
Please provide details of Office 365 Pro Plus version support for other channels. The example version number above - 16.0.11.629 - is the monthly Channel release from May 2019. Please advise when the change from IE11 to Edge was rolled-out to the Semi Annual Channel (SAC) and Semi Annual Channel Targeted (SAC-T) releases of Office 365 Pro Plus.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00c430f1-bbf5-53b8-a225-4fbe8fc39c3b
* Version Independent ID: 0a069a0d-4d35-71ee-53af-8c55fe8548a0
* Content: [Browsers used by Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins#feedback)
* Content Source: [docs/concepts/browsers-used-by-office-web-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/concepts/browsers-used-by-office-web-add-ins.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@stukey Thanks for asking about this. You should be able to determine this information from the [ProPlus update history page](https://docs.microsoft.com/officeupdates/update-history-office365-proplus-by-date).

Let us know if this helped or if you need any further clarification.

Thanks.

**Comment by stukey** [comment]
Thanks @ElizabethSamuel-MSFT unfortunately there’s nothing in the Office update history or release notes that indicates if or when the change of browser rendering from IE to Edge was added to the SAC or SAC-T releases. It’s not even mentioned in the referenced 16.0.11.629 monthly release notes either. So I’m not sure how anybody outside Microsoft is supposed to tell. Therefore I think this page still needs to be updated to address my original question. Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@stukey Thanks for responding. On the update history page, the build is truncated from 16.0.11629 to 11629.**** and all the channels use the same build series. As such, if the version for your channel uses a more recent build than the build you're interested in, then it should be available for you to download/use and the feature should be present. My team can't tell when the channels will be released so this is why I directed you to the update history page, as it will have the latest info from the teams responsible for those updates.

Let me know if this helped or you have further questions.

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@stukey In this case and as of April 22, all the channels except the oldest SAC should include this feature.

**Comment by stukey** [comment]
@ElizabethSamuel-MSFT Thanks again. So, if I understand you correctly, if the change of browser support was added in version 11629 (Version 1905) of the monthly channel, then it should also be in the next available SAC release? So Version 1808 (Build 10730.20348) for SAC and Version 1902 (Build 11328.20318) for SAC-T? Or does the build no. actually have to be higher? E.g. Version 1908 (Build 11929.20562) of SAC released January 14 2020 seems like the first one that’s higher for SAC?

**Comment by ElizabethSamuel-MSFT** [comment]
@stukey The build number has to be the same or higher. So version 1908 (with build 11929.20562) or a more recent version should include this feature.

**Comment by stukey** [comment]
Ok! Thank you! That makes sense.

**Comment by ElizabethSamuel-MSFT** [comment]
@stukey No problem, glad that helped! Thanks again for asking about this.
