### ISSUE TITLE
Typo in the Manifest example 

### ISSUE THREAD

**Issue by paulghodgson** [OfficeDev/office-js-docs-pr#1783]
Scale of 2 is used twice for size 32, expect it should be scale 2 and 3
     
`&lt;bt:Image resid="UiLessIcon" size="32" scale="2" /&gt;
&lt; bt:Image resid="UiLessIcon" size="32" scale="2" /&gt;`

Should be
`&lt;bt:Image resid="UiLessIcon" size="32" scale="2" /&gt;
&lt; bt:Image resid="UiLessIcon" size="32" scale="3" /&gt;`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52a55fe4-0fe1-858c-26a4-dddc3ee128ea
* Version Independent ID: 0a643291-936f-b374-37fd-7db497c73cce
* Content: [Create an Outlook mobile add-in for an online-meeting provider (preview) - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/online-meeting)
* Content Source: [docs/outlook/online-meeting.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/outlook/online-meeting.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@paulghodgson Thanks for raising this issue. The fix should be published soon.
