### ISSUE TITLE
Some guidance on reporting errors?

### ISSUE THREAD

**Issue by MrMichaelJKelly** [OfficeDev/office-js-docs-pr#1786]
Above, you say "End users will not see those error messages in the add-in task pane or anywhere in the host application."  OK - so what is the best practice here?  Is this just left to every person to figure out on their own?  Give some examples of what options are available for reporting errors that aren't software bugs (e.g. a server is not reachable, content is not in the correct format) to end-users.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 180b9c75-f4cb-f59a-5e7c-867eaa5d0fb9
* Version Independent ID: 6e1e7e0e-0a05-00e8-2797-11798d5ae022
* Content: [Error handling - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-error-handling)
* Content Source: [docs/excel/excel-add-ins-error-handling.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/excel-add-ins-error-handling.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@MrMichaelJKelly Thanks for asking about this.

@AlexJerabek Can you take a look and assign as appropriate?

Thanks.

**Comment by AlexJerabek** [comment]
Hi @MrMichaelJKelly, 

A believe the section you're referencing is about `console.log`, which is not displayed in the task pane an end-user would see. You can still display messages to users through dialogs or your add-in's taskpane. This logic should be in the `errorHandlerFunction` shown in the code snippet under [Best practices](https://docs.microsoft.com/office/dev/add-ins/excel/excel-add-ins-error-handling#best-practices).

As for guidance about communicating errors to users, there's basically three categories of error:

- Office service problems (such as the connectivity issue you mentioned). You should alert the user to the failure and recommend they retry the operation or report it if it persists.
- API misuse (such as InvalidOperation). This is probably an error in your add-in relating to how it's using the Office JavaScript APIs, such as trying to read a property before its loaded. This is something that should be fixed before releasing to a customer.
- Input errors (such as ItemAlreadyExists for creating a table). This is dependent on how you're handling user input to your add-in. If for the create-a-table example, you're asking the user to name the table, you should catch the error (or check if the name is used before trying to create the table) and report that information to the user. 

Is that information helpful? If so, I'll add that to the error handling article. If not, please let me know what's unclear and how I can better help. Thanks!

**Comment by MrMichaelJKelly** [comment]
Thanks a lot for the quick response!

Right, I know console.log is more for debugging than users – so that’s the gist of my question, your sample code on this page shows the right way to report errors for debugging but not the right way to do it for production, i.e. errors that I would want to show to a user.

Your answer below is “You should alert the user to the failure and recommend they retry the operation or report it if it persists.” – and my question is yes, but how?  What’s the recommended practice here?  Is this just a standard JavaScript alert method?  Or is there a way through the JavaScript Office add-in model to display a dialog stylized in Office style?  I guess I’m saying the sample code covers just the console.log example, not a more real-life example where I would want to report to a user.

Thanks!

Mike Kelly – CEO – Tech DNA<http://www.tech-dna.net/>
206-347-8820 (o)  |   425-894-1208 (m)

**Comment by Rick-Kirkham** [comment]
@MrMichaelJKelly How you report errors to users depends on the UI system you are using. It's good that you want the UI to be compatible with Office. If you are using React as the UI system, you can use the [Fabric React](https://docs.microsoft.com/office/dev/add-ins/design/using-office-ui-fabric-react) (in the process of being renamed "Fluent UI") components and design elements.  Pick out an appropriate control on this [Fluent UI page](https://developer.microsoft.com/fluentui#/controls/web). I would suggest that error messages are best conveyed with a [message bar](https://developer.microsoft.com/en-us/fluentui#/controls/web/messagebar), [dialog](https://developer.microsoft.com/en-us/fluentui#/controls/web/dialog), or [modal](https://developer.microsoft.com/en-us/fluentui#/controls/web/modal). This sample uses a MessageBar, but modifies it to take account of the personality menu in an add-in taskpane: [Office-Add-in-Microsoft-Graph-React](https://github.com/OfficeDev/PnP-OfficeAddins/tree/0706cc67645675a48747f1fec1b1e5722b575b11/Samples/auth/Office-Add-in-Microsoft-Graph-React)

If you're not using React for the UI, consider using the older [Fabric UI](https://docs.microsoft.com/office/dev/add-ins/design/office-ui-fabric) components implemented directly in HTML/Javascript. Some example templates are in this [Office-Add-in-UX-Design-Patterns-Code](https://github.com/OfficeDev/Office-Add-in-UX-Design-Patterns-Code/tree/master/templates) repo. Take a look especially in the dialog and navigation subfolders. This sample uses a message banner: [Excel-Add-in-SalesLeads](https://github.com/OfficeDev/Excel-Add-in-SalesLeads).

@AlexJerabek Maybe we should have a section of an article somewhere that explains all this and then this article can link to the new section. Let me know if you agree and I'll create an work item.

**Comment by AlexJerabek** [comment]
@Rick-Kirkham We should definitely add that section. Please create the appropriate internal work item.
