### ISSUE TITLE
Authentication options in Outlook add-ins

### ISSUE THREAD

**Issue by moshikonachmias** [OfficeDev/office-js-docs-pr#1792]
In this article: https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/authentication
you mention a number of options on how to do authentication.
But as what I understood from deep dive in your doc the first option SSO is not supported in AppSource add-ins and not recommended for production env.
If it's true I think you MUST put it in bold in this article.
It will save a lot of time for finding a solution for production add-ins.

**Comment by ElizabethSamuel-MSFT** [comment]
@moshikonachmias Thanks for raising this issue. We're updating the docs to indicate that preview/beta APIs shouldn't be used in production add-ins (see PR #1794).

Thanks.
