### ISSUE TITLE
Misleading information about using VS Code debugger for Excel Desktop

### ISSUE THREAD

**Issue by vikasm1720** [OfficeDev/office-js-docs-pr#1802]
Steps mentioned in [code debugger for Excel desktop](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-debugging#use-the-vs-code-debugger-for-excel-desktop) is incorrect. we do not have an option to choose **Excel Desktop** from the debug options. The VS code [document](https://code.visualstudio.com/docs/other/office#_debugging-your-office-addin) states VS Code does not currently support client-side debugging. Please update the document. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0bedd430-d224-565e-c1b1-15f90994aa52
* Version Independent ID: b41539c4-c9ec-c678-e44b-27bd456b9c0b
* Content: [Custom functions debugging - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-debugging#feedback)
* Content Source: [docs/excel/custom-functions-debugging.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/custom-functions-debugging.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by mscharlock** [comment]
Hi @vikasm1720 - Thanks for reading the custom functions documentation and letting us know about this oversight. I will have a look at it and update. Thanks!

**Comment by vikasm1720** [comment]
Please check the documentation for VS Code debugger for Excel in Microsoft Edge, I was unable to find Office Online (Microsoft Edge), mentioned in step 5, Thank you

**Comment by mscharlock** [comment]
Will do. Also, I wanted to let you know that there is a new option for debugging in VS Code which runs against the Edge runtime (this just came out on Monday). You can find details here: https://github.com/OfficeDev/vscode-debugger-extension-for-office-addins

**Comment by simpjack89** [comment]
i also check the documentation for VS code debugger but it always run me to https://Joker123gaming.co what should i do?

**Comment by vikasm1720** [comment]
Thank you, for pointing me to this extension. I am able to debug with vscode debugger

**Comment by mscharlock** [comment]
Excellent! I am going to close this issue given that, but if you need anything else feel free to comment on this thread and I will re-open it.

**Comment by jslatane** [comment]
I know this issue is closed so if I need to submit another issue for this I'd be happy to. But I just wanted to comment to echo @vikasm1720 's point. The documentation on this page does not mention anything about the Office Add-in Debugger that is referenced in the link https://github.com/OfficeDev/vscode-debugger-extension-for-office-addins so if you don't know to come look at the issues page for this, the instructions don't make any sense. Please either rewrite the instructions or provide a link to the updated instructions somewhere within the page.

**Comment by mscharlock** [comment]
No need to submit another issue - I can have a look at this page, it's possible that UI-less just needs links at this point to some of the other articles that have been added over time. Thanks for pointing this out, I will go ahead and re-open so that it is on my radar.

**Comment by mscharlock** [comment]
@alison-mk I am going to transition this to you given it requires changes to the CF debugging. Thanks!

**Comment by alison-mk** [comment]
Update: 

- The Custom functions debugging article was updated in #3461 to clarify which step to choose in the debug options. 
- The most up-to-date documentation article for the add-in debugger extension in VS Code is: [Microsoft Office Add-in Debugger Extension for Visual Studio Code](https://docs.microsoft.com/office/dev/add-ins/testing/debug-with-vs-extension). VS Code does support client-side debugging. 

Closing this issue as both reported problems have been resolved.
