### ISSUE TITLE
Need to save working excel into database.

### ISSUE THREAD

**Issue by PavanaKatta** [OfficeDev/office-js-docs-pr#1807]
I need to save opened excel file into my database. I tried to Office.Document.getFileAsync(). But, that also not working.

 Office.context.document.getFileAsync(Office.FileType.Compressed, { sliceSize: 65536 /*64 KB*/ },
       (result) => {
        console.log("callback start");

         if (result.status == "succeeded") {
           var sliceIndex = 0;
          var myFile = result.value;
          var sliceCount = myFile.sliceCount;
          
           myFile.getSliceAsync(sliceIndex, (asyncResult) => {
             if (asyncResult.status == "succeeded") {
               var v = asyncResult.value.data;
               myFile.closeAsync();
               var blob = new Blob([v], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
               var fd = new FormData();
               fd.append("myFile", blob, "thumb.xlsx");
            }
          });
        }
        else {
          console.log("Error:", result.error.message);
        }

        console.log("callback end");
      });

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6b16473-fffd-9ebf-ee91-2f0012a496ee
* Version Independent ID: 3f147de9-0138-9104-f462-c6f4097b1167
* Content: [Work with workbooks using the Excel JavaScript API - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-workbooks#feedback)
* Content Source: [docs/excel/excel-add-ins-workbooks.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/excel-add-ins-workbooks.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @PavanaKatta, 

Have you looked at this sample [Get file using slicing](https://github.com/OfficeDev/office-js-snippets/blob/master/samples/excel/26-document/get-file-in-slices-async.yaml). That should help you load the file into memory and create a new workbook with it. You can then use the new [Workbook.save](https://docs.microsoft.com/javascript/api/excel/excel.workbook?view=excel-js-preview#save-savebehavior-) to save the file locally, then use file APIs like [fs-extra](https://www.npmjs.com/package/fs-extra) to copy the file to your database.

Please let me know if that helps. Thanks!

**Comment by PavanaKatta** [comment]
@AlexJerabek , Thanks a lot for your quick response. I have been trying this from last couple of days, but with the help of your response, i could able to achieve my implementation. 

Thanks a lot once again Alex..
