### ISSUE TITLE
Persistent settings across documents?

### ISSUE THREAD

**Issue by Slidemagic** [OfficeDev/office-js-docs-pr#1810]
Is there a way to save a user token across documents, so the user can stay signed in when using the add-in of an Office app (PowerPoint in my case) across more than one file?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b683480b-a4fe-97ba-64f9-45ecfe829bf4
* Version Independent ID: a0993174-18dd-9594-9c3c-102d078e2217
* Content: [Persisting add-in state and settings - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/persisting-add-in-state-and-settings#feedback)
* Content Source: [docs/develop/persisting-add-in-state-and-settings.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/persisting-add-in-state-and-settings.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by mscharlock** [comment]
@Rick-Kirkham do you happen to know on this one? Thanks!

**Comment by Rick-Kirkham** [comment]
For the most part, an add-in lives in a universe where there's only one Office document: the one that's open. So, I'm not sure what you mean by using an add-in "across more than one file". If a user opens your add-in in a document, then closes the document and opens another one, (s)he has to relaunch the add-in.

There is a preview [Single Sign-on system](https://docs.microsoft.com/office/dev/add-ins/develop/sso-in-office-add-ins) (that shouldn't yet be used in a production add-in). Basically, your add-in could get a token of the current user logged into Office by calling the `getAccessToken` method. You could design the add-in to call this when the add-in launches. Each time the add-in is launched in a different document, the token would be fetched again. But it would not be stored anywhere in between. 

This is more a programming question, than a problem with the article, so I'm going to close this, but you can still add comments and we'll see them.

**Comment by Slidemagic** [comment]
Thank you @Rick-Kirkham. I brought this issue up, because my draft PowerPoint add-in was rejected because of this SSO issue. My add-in gives access to a slide template database, but the PowerPoint Javascript API has only 1 function at the moment: create a new presentation. So whenever a user picks a slide for download, I need to serve it as a new presentation in a new Window or browser tab. I will link to this discussion, and hopefully Microsoft will approve my add-in because on my end, I cannot do much about this behaviour.

Lifting the SSO option out of preview would be great, and even better: exposing an API method that allows you to add a single slide to an existing presentation.
