### ISSUE TITLE
Excel JS API - Support for CSS Grid?

### ISSUE THREAD

**Issue by thunter05** [OfficeDev/office-js-docs-pr#1817]
## Article URL
https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-jquery?tabs=yeomangenerator

## Issue
It appears that CSS Grid is not supported in the Excel add-in task pane window. It looks like flex-box is supported and is part of the base templates provided by the npm office generator project. Is that the case? If so then I hope CSS Grid can be added.

**Comment by AlexJerabek** [comment]
Hi @thunter05, 

Thanks for the question. @Rick-Kirkham, can you confirm the CSS support? Do we have any documentation around what is or is not supported by the task pane?

**Comment by Rick-Kirkham** [comment]
@thunter05 Can you provide a simple example that I can use to try to reproduce? Also, what platform are you using to develop? Desktop Windows? Desktop Mac? Excel on the web?

**Comment by thunter05** [comment]
Hello Rick-Kirkham!

Thanks for getting back to me. My use case is simple in that I have the code below. The `display: grid` does not work in the Excel panel window. `display: flex` does work.

```
<section\>
   <img .... />
   <h1>Welcome!<\h1>
<\section>

section {
  display: grid;
  grid-template-columns: 2% 1fr;
}
```

I’m running a ReactJs Excel API add-in project for the Windows desktop. Using this npm project generator: https://developer.microsoft.com/en-us/office/blogs/creating-office-add-ins-with-any-editor-introducing-yo-office/.

My editor is VSCode.

**Comment by Rick-Kirkham** [comment]
Thanks. I'm more a flexbox person than a grid person. What would you normally expect to see from `grid-template-columns: 2% 1fr;`?

**Comment by thunter05** [comment]
Grid is nice for page layout. It’s a much easier way to center content and place components with more control without using positioning and floats. Flex-box can do the same stuff but it’s more suited for laying out lists of items along an vertical/horizontal axis.

The css I wrote is a simple way to create a header where my img and h1 tags can be placed next to each other on the same line. Then I can use other grid properties to align/center the content.

**Comment by Rick-Kirkham** [comment]
OK. So you expect to see the img and h1 side-by-side and you're actually seeing the H1 below the img. Is that right?

**Comment by thunter05** [comment]
Yes that’s right. I ended up working around it by using flex box but ideally css grid is supported for more complex layout use cases

**Comment by Rick-Kirkham** [comment]
Thanks. One last (I hope) question: If you open the url of the add-in directly in a browser window, does it render as expected? (The add-in won't work, but the page should render.)

**Comment by thunter05** [comment]
That’s right.

It renders correctly in the browser. Does not render correctly in the excel add-in panel.

**Comment by Rick-Kirkham** [comment]
I tried to reproduce this in the [Script Lab](https://appsource.microsoft.com/product/office/wa104380862) tool. But it renders as expected. The elements are side-by-side. Do you find that it works in Script Lab?
