### ISSUE TITLE
Improve documentation for working with existing .Net web project

### ISSUE THREAD

**Issue by yowl** [OfficeDev/office-js-docs-pr#1821]
If you want to create custom functions that connect to a web project you have in asp.net (core or otherwise), the Yeoman approach is a pain as you end up with 2 web servers and then you have preflight/CORS issues to deal with.  It would be good to have a github repro, or section about how to integrate with an existing .Net web project.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a30fb645-c853-a93a-4137-1e2bf7398a11
* Version Independent ID: 75fb99ac-72e8-7bdc-ff1b-85e7ed930d50
* Content: [Excel custom functions tutorial - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/excel-tutorial-create-custom-functions?tabs=excel-windows#create-a-custom-function-that-requests-data-from-the-web)
* Content Source: [docs/tutorials/excel-tutorial-create-custom-functions.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/tutorials/excel-tutorial-create-custom-functions.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by mscharlock** [comment]
Hi @yowl, Thanks for this feedback! I will take it to our PM team and see what we can do about updating the documentation here. Given we have a full team devoted to developing Yeoman tooling, it will probably continue to get more attention (just as an FYI) but you bring up a good point about integration with an existing .Net project.

**Comment by mscharlock** [comment]
I'm going to close this issue for now, but wanted to let you know that your feedback has passed on! Thank you.
