### ISSUE TITLE
Visual Studio for Mac

### ISSUE THREAD

**Issue by hariharan605** [OfficeDev/office-js-docs-pr#1841]
Can we develop this Office add-in using Visual Studio for mac ?
If possible kindly share me the document link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 930ce4fc-c8b8-f756-f03f-a716f1ef7883
* Version Independent ID: 753a2e38-9430-25bb-5409-b7eed9c88e47
* Content: [Build your first Outlook add-in - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/outlook-quickstart?tabs=visualstudio#feedback)
* Content Source: [docs/quickstarts/outlook-quickstart.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/quickstarts/outlook-quickstart.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@exextoc Can you confirm about using Visual Studio for Mac?

Thanks.

**Comment by exextoc** [comment]
Visual Studio for Mac does not support Office Workload yet. Here is the [list of supported workloads](https://docs.microsoft.com/en-us/visualstudio/mac/workloads?view=vsmac-2019)

You can follow [Build your first Outlook add-in using Yeoman generator](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/outlook-quickstart?tabs=yeomangenerator) and use Visual Studio as editor.
