### ISSUE TITLE
Add-in dialog box cannot be displayed error in displayInFrame

### ISSUE THREAD

**Issue by aagamdoshi** [OfficeDev/office-js-docs-pr#1854]
The fix provided in the [Solution](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/testing-and-troubleshooting#add-in-dialog-box-cannot-be-displayed)

## Article URL
https://docs.microsoft.com/en-us/office/dev/add-ins/testing/testing-and-troubleshooting#add-in-dialog-box-cannot-be-displayed

## Issue
The solution of code should be 
`Office.context.ui.displayDialogAsync(startAddress, {displayInIframe:true}, callback);`

rather than
`Office.context.ui.displayDialogAsync(startAddress, {displayInFrame:true}, callback);`

Just convert from displayInFrame -> displayInIframe

**Comment by Rick-Kirkham** [comment]
Good catch. I'll try to fix this right away.

**Comment by Rick-Kirkham** [comment]
This has been fixed in the source and the fixed version will be public in the next few days.
