### ISSUE TITLE
issue with step2

### ISSUE THREAD

**Issue by stephane0007** [OfficeDev/office-js-docs-pr#1855]
Follow the instructions in Sideload Outlook add-ins for testing to sideload the add-in in Outlook. is not working for me ...the File&gt;Manage Addins button opens web Outlook but neither shows anything allowing me to add the manifest plugin created in previous steps..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 930ce4fc-c8b8-f756-f03f-a716f1ef7883
* Version Independent ID: 753a2e38-9430-25bb-5409-b7eed9c88e47
* Content: [Build your first Outlook add-in - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/outlook-quickstart?tabs=yeomangenerator#feedback)
* Content Source: [docs/quickstarts/outlook-quickstart.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/quickstarts/outlook-quickstart.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@stephane0007 Sorry you're getting this behavior. Can you look through the [sideloading article](https://docs.microsoft.com/office/dev/add-ins/outlook/sideload-outlook-add-ins-for-testing) to see if this helps your situation?

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@stephane0007 Does that mean you're seeing the classic UI when you open Outlook in a browser and you're following the instructions in the [Sideload an add-in in classic Outlook on the web](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/sideload-outlook-add-ins-for-testing#sideload-an-add-in-in-classic-outlook-on-the-web) section? Can you share a screenshot of what you're seeing?

Thanks.

**Comment by stephane0007** [comment]
Hello Elizabeth, i have actually solved this issue we can close this.

**Comment by ElizabethSamuel-MSFT** [comment]
@stephane0007 Glad to hear that. Do let us know if there's any we can make clearer in the docs.

Thanks.
