### ISSUE TITLE
"App error" should be changed to "add-in error" in "Common errors and troubleshooting steps" section

### ISSUE THREAD

**Issue by modestfake** [OfficeDev/office-js-docs-pr#1869]
I've noticed that the actual error is "Add-in error", not "App error".
Here's one of error messages:
![image](https://user-images.githubusercontent.com/16977959/82308089-f8cecc80-99c9-11ea-9bea-51116dbae8f8.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6cb5f52-dfc5-4fa2-6508-194d6f1c674a
* Version Independent ID: 8f3caf2d-fba3-166f-43bc-1d3e4007abab
* Content: [Troubleshoot user errors with Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/testing-and-troubleshooting#feedback)
* Content Source: [docs/testing/testing-and-troubleshooting.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/testing-and-troubleshooting.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by mscharlock** [comment]
Hi @modestfake - I will go ahead and look into this to repo and then update the docs as necessary. Thanks for writing in and letting us know, we appreciate it!

**Comment by mscharlock** [comment]
Hi @modestfake - just wanted to let you know that as this is on our backlog I am closing this issue. :) Thanks! You are welcome to re-comment on this thread at any time should you need anything else.
