### ISSUE TITLE
Not seeing "Show Inspector" on Outlook for Mac

### ISSUE THREAD

**Issue by binarykitchen** [OfficeDev/office-js-docs-pr#187]
I think few more instructions are missing
https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/debug-office-add-ins-on-ipad-and-mac.md

Did all that, those commands and when opening Outlook for Mac and attempt to right-click on my custom add-in, I see no such "Show Inspector" context menu entry.

Probably something else missing?

**Comment by smaremanda** [comment]
hi there - the instructions on the github docs work for me as-is. could you please share what version of OS you are running + the Office version?
-Sudheer

**Comment by binarykitchen** [comment]
Office 2016 on Mac OS

**Comment by smaremanda** [comment]
can you be a bit more specific? I'd like the versions from Apple Logo > About this Mac
and Outlook > About Outlook

**Comment by binarykitchen** [comment]
![screen shot 2018-05-30 at 11 17 38](https://user-images.githubusercontent.com/177641/40690424-2121a74a-63fb-11e8-96cd-909ea2c923ef.png)
![screen shot 2018-05-30 at 11 17 53](https://user-images.githubusercontent.com/177641/40690425-214b190e-63fb-11e8-99fe-db87a54600cc.png)

**Comment by smaremanda** [comment]
Great - thanks. It should work for your build. I just tested the instructions again on a new macbook. you should try restarting Outlook [if you havent already].

**Comment by binarykitchen** [comment]
No @smaremanda I still do NOT see such a context menu entry with "Show Inspector" inside Outlook Native. Can you do a screenshot on your side and show me here?

**Comment by smaremanda** [comment]
sure here it is ...
![image](https://user-images.githubusercontent.com/10138673/40752219-7a9e5214-6423-11e8-86ee-ad28b5a0489d.png)

**Comment by binarykitchen** [comment]
@smaremanda looks weird. Is this in Outlook Native? Can I see the whole app? Or is this a web page?

**Comment by smaremanda** [comment]
its outlook for Mac. version 16.14.
![image](https://user-images.githubusercontent.com/10138673/40752448-5d65610a-6424-11e8-8970-31d17ffa8ee8.png)

**Comment by binarykitchen** [comment]
Weird. Why am I not seeing that context-menu at all?

Really ran the command `defaults write com.microsoft.Outlook OfficeWebAddinDeveloperExtras -bool true` and restarted my machine.

Can you suggest other steps to find out what else is missing?

**Comment by binarykitchen** [comment]
I do not see a context menu at all. And what's an add-in frame? And yes I'm in read mode.

My office add-in is using `<ExtensionPoint xsi:type="MessageReadCommandSurface">` as an entry point by the way.

**Comment by smaremanda** [comment]
Ok. what happens when you click on that button? does it launch a taskpane or a "frame" like you saw in my screenshot above?

**Comment by binarykitchen** [comment]
No, clicking on my add-in button doesn't show any additional UI elements. It only moves the message around and forwards it to someone else.

**Comment by smaremanda** [comment]
Ok. so your add-in is a UI-less command. You will only see the context menu if you have UI displayed as part of your add-in [the context menu belongs to the web control that displays your add-in]. Are you able to display a blank page on your dev box to debug your add-in?

**Comment by binarykitchen** [comment]
Yes able to debug on my dev box but only via Office 365 online. Not on Outlook Native.

I think documentation should be corrected, saying elements in Outlook Native can only be inspected when add-in is NOT UI-less.

**Comment by smaremanda** [comment]
that's fair. I can follow up on that and make sure its updated.

**Comment by Reezaali** [comment]
The documentation has been updated. Thank you for pointing out this issue. 

I'll proceed to close this issue now because we resolved it. Thanks!
