### ISSUE TITLE
Content addin

### ISSUE THREAD

**Issue by mdhruv1** [OfficeDev/office-js-docs-pr#1884]
It would be great if we can get a simple hello world example for excel word and PowerPoint as a content addin. I see you have great examples for task panes but for content addin I do not see it. Would appreciate that since I can then socialize this in my department.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39d23706-196e-a6e8-4323-c116de27ae2f
* Version Independent ID: dd7cee92-5bc9-5bfe-1e2a-c05bc3810289
* Content: [Content Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/design/content-add-ins#feedback)
* Content Source: [docs/design/content-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/design/content-add-ins.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@mdhruv1 Thanks for requesting quick starts for content add-ins. We have added this request to our backlog and will get to it as soon as we can.

[Internal item](https://office.visualstudio.com/OC/_workitems/edit/4186300)

**Comment by mscharlock** [comment]
Hi @mdhruv1 - Thanks for reading the docs and writing in. Just wanted to check back in and give an update. We'll keep this on our backlog, but  at this time content add-ins are not the main focus for our team. :) Thank you for contacting us - I am going to close this issue for  now, but if you need anything else please comment on this thread and I can reopen it.

**Comment by ElizabethSamuel-MSFT** [comment]
We recently addressed this and there are now quick starts showing how to create content add-ins through Visual Studio.

- [Excel](https://learn.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-content?tabs=basic)
- [PowerPoint](https://learn.microsoft.com/en-us/office/dev/add-ins/quickstarts/powerpoint-quickstart-content)
