### ISSUE TITLE
Possibility for Exchange admin to provide pre-defined Roaming Settings

### ISSUE THREAD

**Issue by adem** [OfficeDev/office-js-docs-pr#1887]
This is just a question related to API functionality described on this page.

Is there a possibility for an Exchange Administrator to "prefill" Roaming Settings for a certain add-in ID? Suppose you have an add-in that works in conjunction with an on-premise server. Ideally, you would want to offer this add-in via App Source to a broader audience, but allow individual organizations to pre-define the URL to the on-premise server (while providing a fallback to a "demo" server of some sort).

In short, I'm looking for a way to define custom key-value pairs that applies to a single add-in of an Exchange admin's organization.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efdb5871-0293-beb6-a584-9401f4be8443
* Version Independent ID: 55687f2c-7649-5ca7-d090-aface4cd8a7e
* Content: [Manage state and settings for an Outlook add-in - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/manage-state-and-settings-outlook)
* Content Source: [docs/outlook/manage-state-and-settings-outlook.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/outlook/manage-state-and-settings-outlook.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@adem Thanks for inquiring about this.

@exextoc Can you provide any guidance here?

Thanks.

**Comment by exextoc** [comment]
This isn't possible with the Roaming Settings API today, since the API stores settings only on a per-user basis.

If you would like to suggest a feature, please add an idea to the Outlook add-ins [UserVoice](https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback?category_id=131778).

**Comment by adem** [comment]
Will do - thanks for the information!
