### ISSUE TITLE
Please provide sample add in / explanation how the join meeting UI is realized

### ISSUE THREAD

**Issue by rboen** [OfficeDev/office-js-docs-pr#1889]
Hi there,

the article  gives  extracts of code samples of a larger add in. A reference to the complete project / source would be very helpful. The screenshot of the "Join Meeting UI" shows the Join-Button for a Contoso Meeting but there is no explanation how this Join-Button has been realized.

Regards,

Ralf

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52a55fe4-0fe1-858c-26a4-dddc3ee128ea
* Version Independent ID: 0a643291-936f-b374-37fd-7db497c73cce
* Content: [Create an Outlook mobile add-in for an online-meeting provider - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/online-meeting)
* Content Source: [docs/outlook/online-meeting.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/outlook/online-meeting.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@rboen Thanks for asking about this. We've started creating walkthroughs using the quick start as the base (see the [event-based activation article](https://docs.microsoft.com/office/dev/add-ins/outlook/autolaunch) for an example). Would that help you in this case?

About the attendee's join meeting behavior, that should happen automatically for an online meeting.

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@rboen This item has been added to our backlog so we'll work on converting the article into a walkthrough, at the end of which you should have a complete sample add-in. I can't say when the work will be done but we'll get to it as soon as possible.

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@rboen The conversion update should be published soon. Thanks.
