### ISSUE TITLE
Local storage in Outlook

### ISSUE THREAD

**Issue by SunRift** [OfficeDev/office-js-docs-pr#1906]
Local storage example using OfficeRuntime.Storage (as shown in Excel sample code) is not working in Outlook. 
If this is because the Outlook API doesn't support promises, how would you access local storage instead?

**Comment by ElizabethSamuel-MSFT** [comment]
@SunRift Thanks for your question.

@jasonjoh Thanks for transferring.

@exextoc Can you take a look?

Thanks.

**Comment by exextoc** [comment]
[OfficeRuntime.Storage](https://docs.microsoft.com/en-us/javascript/api/office-runtime/officeruntime.storage?view=word-js-preview) is not currently supported in Outlook. It is in an API set that is not supported in Outlook. You can check if a method is supported by using the isSetSupported method with the name of the requirement set. This method determines, at runtime, whether the Office host running the add-in supports the requirement set. Documentation on this method can be found [here](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/specify-office-hosts-and-api-requirements#use-runtime-checks-in-your-javascript-code).

Local storage in Outlook can be accessed by using the [browser APIs](https://www.w3schools.com/jsreF/prop_win_localstorage.asp).

**Comment by ElizabethSamuel-MSFT** [comment]
@exextoc Thanks for your response.

@SunRift It seems like your question has been answered so I'll close this issue. If you have further questions, let us know by creating a new issue, or commenting on this one so we can reopen it.

Thanks.
