### ISSUE TITLE
Difference to OnSend

### ISSUE THREAD

**Issue by LokiMidgard** [OfficeDev/office-js-docs-pr#1910]
What exactly is the difference to the On-Send Feature. For me it looks like this is a subset of the On-Send feature.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28320183-499e-5a19-2925-31f73227766f
* Version Independent ID: e998c64b-dc57-fb8d-9959-c4095e32411a
* Content: [Implement append on send in your Outlook add-in (preview) - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/append-on-send)
* Content Source: [docs/outlook/append-on-send.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/outlook/append-on-send.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@LokiMidgard Thanks for asking about this.

@JuaneloJuanelo Can you respond?

Thanks.

**Comment by JuaneloJuanelo** [comment]
There are quite different. 

- AppendOnSend - with this one you can ONLY appends text or html to the message been sent. That's it. There is nothing else you can do with it.
- ItemSend, on the other hand, its basically an event. You can handle that event to do any logic your scenario requires, and more importantly you could cancel the send of the email if you need to. 

Hopefully that makes sense.

**Comment by ElizabethSamuel-MSFT** [comment]
@JuaneloJuanelo Thanks for your response, Juan.

@LokiMidgard Let us know if this helps or you need further clarification.

Thanks.

**Comment by LokiMidgard** [comment]
Ok, I think I understand.

And since it can do less it requires less privileges (If I remember correctly OnSend is not allowed in the store).

**Comment by JuaneloJuanelo** [comment]
@LokiMidgard  yes the item-send event is not allowed in the store.
