### ISSUE TITLE
Incorrect path on page?

### ISSUE THREAD

**Issue by jreed5** [OfficeDev/office-js-docs-pr#1913]
On the note it says to go to:
  com.microsoft.Office365ServiceV2/Data/Caches/com.microsoft.Office365ServiceV2/

However, we don't see that, we see:
  com.microsoft.Office365ServiceV2/Data/Library/Caches/com.microsoft.Office365ServiceV2/

Not sure if the path has changed or if it's different.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e273e29-10ac-440e-634e-588b5208e484
* Version Independent ID: a5a6dc8a-b504-686e-80ce-45aabd6f832b
* Content: [Clear the Office cache - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/clear-cache)
* Content Source: [docs/testing/clear-cache.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/clear-cache.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@jreed5 Thanks for asking about this. We'll investigate and update the docs as needed.

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@jreed5 For now, I'm adding the location you reported instead of replacing the previous location. I'll continue investigating and remove the previous location if it's no longer valid.

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@jreed5 Was your cache location under `~/Library/Containers`? Thanks.
