### ISSUE TITLE
Webservice call

### ISSUE THREAD

**Issue by Peteratrapporr** [OfficeDev/office-js-docs-pr#194]
I have this working and want to pull data from a remote server, but I can't get it working.

In the documentation, XHR is talked about but there is no example, just that there is a web service call. Have tried to use XMLHttpRequest, but get an N/A.

Would like some example code so I can then start building out my project

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94ad7803-d4f7-a700-7c7f-204cd8f34e4a
* Version Independent ID: 9c485bae-cab1-bdad-4c8e-baad2b12b22d
* Content: [Create custom functions in Excel (Preview)](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-overview)
* Content Source: [docs/excel/custom-functions-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/custom-functions-overview.md)
* Service: **unspecified**
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Reezaali** [comment]
@Peteratrapporr - the following code sample contains code that should be able to help: [Code](https://github.com/OfficeDev/Office-Add-in-JavaScript-FileDownload/blob/master/FileDownloadSampleWeb/Home.js). I'll go ahead and close this issue in the meantime. If the code doesn't meet your needs, please re-open this issue. Thanks!

**Comment by Peteratrapporr** [comment]
I have solved this already of getting the data for an address. [https://github.com/OfficeDev/Excel-Custom-Functions/issues/14](url)

The problem I have now is working the data.  What I'm getting back is JSON data and want to pull the data out of the reply to work on this information.

url is [https://xeronowfunctionsqa.appspot.com/v1/xero/organisation?sheetKey=qazwsx](url)
