### ISSUE TITLE
Not able to debug office add-ins on Mac with Word version 16.13.1

### ISSUE THREAD

**Issue by KeyurPatel268** [OfficeDev/office-js-docs-pr#195]
How can i debug Office Add-ins on Mac with word version 16.13.1? Above all commands doesn't work. I can't see inspect element menu option using all commands available on document. Is there any other way to debug issue?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be179784-5839-3e8f-c131-1f4d89808b03
* Version Independent ID: 69bca101-91a2-3a5e-5177-493723504354
* Content: [Debug Office Add-ins on iPad and Mac](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-office-add-ins-on-ipad-and-mac)
* Content Source: [docs/testing/debug-office-add-ins-on-ipad-and-mac.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/debug-office-add-ins-on-ipad-and-mac.md)
* Service: **unspecified**
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Reezaali** [comment]
@KeyurPatel268 - I've contacted our engineering team to ask for a follow up to your question.

**Comment by Reezaali** [comment]
#187 - Does any of this information help you?

**Comment by smaremanda** [comment]
could you please explain what you mean by "command dont work"? did you try to run the following command in Terminal:
defaults write com.microsoft.Word OfficeWebAddinDeveloperExtras -bool true

restart Word
and then right click in the add-in frame? you should see the context menu similar to below:
![image](https://user-images.githubusercontent.com/10138673/40814437-1a9c51cc-64f5-11e8-8c38-e8bff81d9d71.png)

**Comment by KeyurPatel268** [comment]
Command means set "OfficeWebAddinDeveloperExtras" using different options to enable inspect menu. I can able to see inspect menu in mac book but not on mac machine with Operating system OS X EI Capitan  and Version : 10.11.3. Word Version is 16.13.1. 

As per mentioned document, Is it enable only on Mac OS High Sierra operating system? Any workaround to see debug or inspect element on OS X EI Capitan Operating system?

**Comment by bplus** [comment]
Is there any equivalent to "defaults write com.microsoft.Word OfficeWebAddinDeveloperExtras -bool true" for seeing javascript console.log statements in Outlook 2016 for mac?

**Comment by smaremanda** [comment]
@bplus - sure. defaults write com.microsoft.Outlook OfficeWebAddinDeveloperExtras -bool true
Take a look at this article here:
https://docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-office-add-ins-on-ipad-and-mac

**Comment by Reezaali** [comment]
I'll go ahead and close the issue. If you need additional information, please reopen the issue, or create a new one. Thanks!

**Comment by 12s** [comment]
I am having the same issues. Not seeing 'inspect element'. not able to console log after:
 defaults write com.microsoft.Word OfficeWebAddinDeveloperExtras -bool true

**Comment by 12s** [comment]
.. was able to see console log..  please disregard comment above

**Comment by shcyiza** [comment]
@12s can you pleas tell me how you achieved this? cause I'm having this issue aswell right now. I don't have 'inspect element' when i right click and I don't know where to go to see the console.
<img width="401" alt="Screenshot 2019-08-14 at 18 01 51" src="https://user-images.githubusercontent.com/16632589/63036653-c2ee3c00-bebd-11e9-9011-d6308682b094.png">

**Comment by 12s** [comment]
@shcyiza I believe my correction was a simple error, like a path being wrong. I believe I had to click on that 'i' button in the top right to display the inspect element option too.

**Comment by shcyiza** [comment]
@12s I did all of this... nothing seems to work...

**Comment by makzr** [comment]
It doesn't work for me either. May it be related to macOS Catalina?

**Comment by Herz3h** [comment]
I'm running Mojave with Outlook 19.33 (Office Subscription) and it doesn't show up in the contextual menu.

I've typed ```defaults write com.microsoft.Outlook OfficeWebAddinDeveloperExtras -bool true````
 and no difference. Restarted outlook, nothing........

**Comment by FiddlersCode** [comment]
I'm running Catalina and the latest version of Word, can't get `inspect` to show up either. Any help much appreciated.

**Comment by kcchien** [comment]
I have same problem, too.
Follow the document but still can't see the inspect shows up :(
https://docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-office-add-ins-on-ipad-and-mac

environment:
macOS: catalina 10.15.6
excel: 16.40 build 20081021

**Comment by chintan-avnio** [comment]
I have the same problem. Not able to see the inspect. Where I'm on Latest BIG SUR 

![image](https://user-images.githubusercontent.com/72140171/101024348-fa449880-3599-11eb-8393-9585991ac200.png)

**Comment by GeorgeBalat** [comment]
Have a look here:
https://github.com/OfficeDev/office-js/issues/506

It says "don't use App store Microsoft"
