### ISSUE TITLE
Using Exchange User Identity Token to authenticate against MS Graph API 

### ISSUE THREAD

**Issue by davyarris** [OfficeDev/office-js-docs-pr#1960]
## Article URL
https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/authentication#exchange-user-identity-token

## Issue
Under the Exchange User Identity Token (EUIT) section of the above article, it clearly states:

>"...Use the Exchange user identity token:
>...As a fallback **authentication (and authorization to Microsoft Graph)** when the add-in is running on a version of Office that doesn't support SSO."
 
This gives the impression that the EUIT can be used to authenticate against Microsoft Graph API. Yet I can find no example of where this is done (and as SSO support for Add-ins in still in beta):

Is this even possible to authenticate against Graph using a EUIT? If not this should be updated.
If it is possible, how can this be achieved?
If it is not possible how can you authenticate the current user from an Outlook Add-in to access Graph API for this user context?

Thanks

David

**Comment by mscharlock** [comment]
@ElizabethSamuel-MSFT or @Rick-Kirkham can you have a look at this one? Also, this could be something Laura might have insight into. Thanks!

**Comment by Rick-Kirkham** [comment]
I think this sample, which is linked to in the Single Sign-on section of the same article (above the section that you quoted from), is supposed to illustrate how to do this: [Attachements Demo](https://github.com/OfficeDev/outlook-add-in-attachments-demo)

Please check it out.

**Comment by lindalu-MSFT** [comment]
@davyarris Closing issue, please reopen if you need additional info! Thanks, linda

**Comment by davyarris** [comment]
As stated in my original post, the SSO technique mentioned is currently in beta. This is stated here also:
https://github.com/OfficeDev/outlook-add-in-attachments-demo
"Note: The SSO token feature is in preview in Outlook 2016 for Windows only at this time.".

My query pertains to the document specifying that it is possible to authenticate against MS Graph API using an Exchange User Identity Token (I don't think this is possible and until SSO goes live I don't think you can access Graph from Add-ins using the current user context).

**Comment by Rick-Kirkham** [comment]
@davyarris You indicated that you couldn't find an example of how this was done. I provided a link to a sample that is supposed to show how it is done. Have you examined that sample?
