### ISSUE TITLE
IE11 Tooling requirements

### ISSUE THREAD

**Issue by TheWass** [OfficeDev/office-js-docs-pr#1962]
I tried the command to use the IE11 tooling, but it appears that it is still using Edge when viewed through Microsoft Edge DevTools.

Are there any additional steps to do in order to make command to work?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47b7b417-12e6-193f-6b89-37e088b31dbc
* Version Independent ID: df705bd2-5f2f-2c84-0519-fca9a3c45d71
* Content: [Internet Explorer 11 testing - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/ie-11-testing)
* Content Source: [docs/testing/ie-11-testing.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/ie-11-testing.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by mscharlock** [comment]
Hi @TheWass, I'll look into this! Thanks for your patience

**Comment by nokafor** [comment]
Are you on Office Insiders? You need to be in the beta level of Office for the runtime to switch. See this link for more details: https://insider.office.com/en-us/join

**Comment by nokafor** [comment]
@TheWass were you able to resolve?

**Comment by TheWass** [comment]
I misread the office insider requirement on the page.

At the moment, I am on the monthly to support clients, and I cannot readily switch over to Insiders.  If I have the opportunity, I'll reply and let you know.  For now, I'll close this issue, and open a new one if I do have an issue while I'm actually on Insiders.
Thanks for your help!
