### ISSUE TITLE
Article link missing from the TOC

### ISSUE THREAD

**Issue by kbrandl** [OfficeDev/office-js-docs-pr#1963]
Hi team! FYI, this article isn't currently included in the TOC.  (David Craig linked to it in a [blog post](https://theofficecontext.com/2020/06/17/office-web-add-in-debugging-in-vs-code) today, else I wouldn't have known it existed.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 614e6992-f9be-4ce5-1f15-0fc6bf285c43
* Version Independent ID: 1b37e38d-06ec-cd00-16bb-3324b1f0048f
* Content: [Microsoft Office Add-in Debugger Extension for Visual Studio Code - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-with-vs-extension)
* Content Source: [docs/testing/debug-with-vs-extension.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/debug-with-vs-extension.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by mscharlock** [comment]
Fixing! Thank you so much for pointing this out!! Also, hope you are well :)

**Comment by mscharlock** [comment]
Fixed! I'm going to close this issue. :)
