### ISSUE TITLE
Excel 2013 Does Not Support CompressedFile API

### ISSUE THREAD

**Issue by jdonohueAdemero** [OfficeDev/office-js-docs-pr#1964]
This page indicates that all versions of "Excel on Windows" support the CompressedFile API, which is incorrect.  Excel 2013 does not support this API, as confirmed both by testing and the add-in manifest validation performed by the AppSource Partner Center.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e78ee91-a35c-c982-aa31-11b9743c6373
* Version Independent ID: 7ab7a2af-d1de-2b97-8bd4-cda3783891a0
* Content: [Office Common API requirement sets - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/office-add-in-requirement-sets)
* Content Source: [docs/reference/requirement-sets/office-add-in-requirement-sets.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/requirement-sets/office-add-in-requirement-sets.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @jdonohueAdemero, 
Thanks for reporting this. It looks like all the Excel versions are ambiguous on that page. I'll investigate and update the supported requirement sets accordingly.

**Comment by AlexJerabek** [comment]
Hi @jdonohueAdemero, 
Thanks again for reporting this documentation error. It has been addressed and will be merge to the live site soon. Please let me know if you have any more questions or concerns. 
Thanks!
