### ISSUE TITLE
Passing information to the dialog

### ISSUE THREAD

**Issue by htryggva** [OfficeDev/office-js-docs-pr#197]
This article recommends passing information to the dialog by using localStorage as an intermediary. This method has some caveats though:
- This doesn't seem to work on Word Online on Safari (tested on macOS 10.3.5). The dialog seems to get it's own localStorage instance and therefore has no access to data set in the taskpane. This is when `displayInIframe` is false (default behavior).
- This method doesn't work when the user has disabled DOM Storage.

Query parameters have size limitations so that method is also not a universal solution.

An improved API to pass data to the dialog would help a lot here. There is already a UserVoice entry for this:
https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/17196659-improve-custom-dialog

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a714626a-058a-789e-6add-5e9dfb21fd1f
* Version Independent ID: 1b88a28c-fc36-4518-2808-7246f08d9753
* Content: [Use the Dialog API in your Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins#pass-information-to-the-dialog-box)
* Content Source: [docs/develop/dialog-api-in-office-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/dialog-api-in-office-add-ins.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Reezaali** [comment]
Hi @htryggva thanks for your feedback. I'm going to forward this information to our engineering team. If there's an alternative solution, we'll update the document.

**Comment by AlexJerabek** [comment]
Hi @htryggva, 
I've checked with the engineering team. The best workaround for passing information through the dialog is by using localStorage. I've relayed your concerns with that approach to them, so hopefully we can work towards a meaningful solution.
I'll close this issue. Please leave a comment if there's anything wrong with the documentation and we'll reopen the thread.
