### ISSUE TITLE
Mislabeled API requirement set info for ExcelApi 1.7 on Office on Mac

### ISSUE THREAD

**Issue by naterush** [OfficeDev/office-js-docs-pr#1973]
Requirement Set 1.7, on Office on Mac, says that this is supported on build 16.9 or later. I think this should be 16.09 -- as I don't think build 16.9 has even been released yet! See here:

<img width="678" alt="Screen Shot 2020-06-20 at 1 50 59 PM" src="https://user-images.githubusercontent.com/21002431/85208294-13fc6700-b2fd-11ea-9873-8a1d64d8a7a1.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c7080b5-9791-e1ca-ff77-ae3dbe5f10cc
* Version Independent ID: 1207aec0-6183-53bb-2768-ebb39d09ed99
* Content: [Excel JavaScript API requirement sets - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/excel-api-requirement-sets)
* Content Source: [docs/reference/requirement-sets/excel-api-requirement-sets.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/requirement-sets/excel-api-requirement-sets.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @naterush, 
Thanks for bringing this to our attention. I'll confirm the officially supported builds against the official "[source of truth](https://github.com/OfficeDev/Office-Js-Requirement-Sets)" and update this page.

**Comment by AlexJerabek** [comment]
Hi @naterush, 

I spoke with the product team about this issue. Excel on Mac version numbers use semantic versioning. This means the version number isn't a decimal, but rather two numbers concatenated with a dot. You read the version as <major_version>.<minor_version>. So, version 16.9 comes before 16.10.  

I hope this clears things up for you. I'm going to close the issue, but feel free to raise more if you encounter anything else in the documentation.
