### ISSUE TITLE
Step 4 = incorrect for Office 2013

### ISSUE THREAD

**Issue by jpro71** [OfficeDev/office-js-docs-pr#1974]
The Custom add-ins section at the bottom of the dialog and "Add a custom add-in" option does not appear in Outlook 2013 when hitting the Store button then "My add-ins"  as mentioned on this page for step 4.

_Locate the Custom add-ins section at the bottom of the dialog. Select the Add a custom add-in link, and then select Add from file._

![image](https://user-images.githubusercontent.com/67275083/85293348-344a3400-b46b-11ea-8222-5f0d07e6a566.png)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f364ae0-b7dd-edb3-b51b-8f6d0d99afbe
* Version Independent ID: 7dd1ce8f-16e7-88f8-f291-4afbe76baba7
* Content: [Sideload Outlook add-ins for testing - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/sideload-outlook-add-ins-for-testing)
* Content Source: [docs/outlook/sideload-outlook-add-ins-for-testing.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/outlook/sideload-outlook-add-ins-for-testing.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by exextoc** [comment]
Hi @jpro71 we are investigating this. Is it possible for you to provide a network trace of the full URL that is hit when opening Store? URL is of the form https://appsource.microsoft.com/...

You can use an app like Fiddler to trace HTTP requests (https://www.telerik.com/fiddler).

**Comment by exextoc** [comment]
Hi @jpro71 , this seems to be an error in our documentation. Outlook 2013 does not support custom add-ins. Thanks for bringing this to our attention, we will go ahead and fix it.

**Comment by ElizabethSamuel-MSFT** [comment]
@jpro71 We're updating the instructions Outlook 2013 (see linked PR #1989). Can you give them a try and let us know if they helped? Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@jpro71 We've added sideload instructions for Outlook 2013. Those changes should be published soon. Thanks.

**Comment by jpro71** [comment]
Excellent looking forward to it.
