### ISSUE TITLE
Shared runtime availability information seems outdated

### ISSUE THREAD

**Issue by sshukurov** [OfficeDev/office-js-docs-pr#1983]
The documentation reads _Shared runtime is currently only available in Excel on Windows._, but as far as I understand it is already available in Excel on the web and Mac. Moreover, there is no mention of this limitation in https://docs.microsoft.com/en-us/office/dev/add-ins/excel/configure-your-add-in-to-use-a-shared-runtime.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8280be11-91ad-cff1-1ac4-ff94126c915e
* Version Independent ID: fd69efcb-6718-d99a-c602-53327c9602ca
* Content: [Runtime in the manifest file - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/runtime)
* Content Source: [docs/reference/manifest/runtime.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/manifest/runtime.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by mscharlock** [comment]
Thanks for catching this - you are right that is not limited to Windows. :)

**Comment by mscharlock** [comment]
I have a bug fix in a pr so will close this issue - thanks! :)
