### ISSUE TITLE
Extend CustomTab in office add-ins with multiple add-ins

### ISSUE THREAD

**Issue by PrashanthReddy7** [OfficeDev/office-js-docs-pr#1987]
Issue: 
I have created a custom tab called "MyAddIns" in outlook, this was created with first add-in called "A" and its working fine.
Now, I have another outlook add-in called "B", I wants to add "B" add-in to exist/already created custom tab "MyAddIns".
How can I do that? Do I needs to use Office Tab or Custom Tab tag in manifest.xml ? If yes, how can we add exist tab reference?

I have also requested for the same in Microsoft UserVoice and GitHub too..
[Office Dev User voice](https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/40742086-extend-customtab-in-office-add-ins-with-multiple-a)

Thank you for your help in advance
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a893aaac-09c3-cce2-b606-291fdd823469
* Version Independent ID: e0fb83d8-2bd3-b92a-d1fe-5f4844f1b135
* Content: [OfficeTab element in the manifest file - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/officetab)
* Content Source: [docs/reference/manifest/officetab.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/manifest/officetab.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@PrashanthReddy7 Thanks for asking about this and adding to UserVoice.

@exextoc Any workaround you're aware of?

Thanks.

**Comment by exextoc** [comment]
No, we are not aware of workarounds to do this. UserVoice is the right place for this request. Thank you for adding!

**Comment by PrashanthReddy7** [comment]
Added into Uservoice 👍 

https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/40742086-extend-customtab-in-office-add-ins-with-multiple-a
