### ISSUE TITLE
Comments API doesn't work on Excel version 2006

### ISSUE THREAD

**Issue by dsonet** [OfficeDev/office-js-docs-pr#2006]
I tried this API on Excel, but got "This operation is not implemented." I use the latest beta API.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 992f7232-6aa0-b170-ff3b-009a273e7586
* Version Independent ID: 0fd9c00f-91d6-5036-48c9-e0e2e0690e78
* Content: [Work with comments using the Excel JavaScript API - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-comments)
* Content Source: [docs/excel/excel-add-ins-comments.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/excel-add-ins-comments.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @dsonet, 

Thank you for reporting this issue. Are you getting the error for all comment-related APIs? Or is it only happening for specific API calls, like when working with mentions?

If you have a [Script Lab](https://docs.microsoft.com/en-us/office/dev/add-ins/overview/explore-with-script-lab) snippet to share, that would also help us figure out what's happening.

**Comment by tvkien** [comment]
Hi @AlexJerabek,

var comments = workbook.comments;
"This operation is not implemented."

I still facing this issue when trying to add comments in Excel using Excel Javascript Api. You can see the error attachment image below for more detail. I'm getting the error for all comment-related API. Please help me to resolve this issue. Thanks

![image](https://user-images.githubusercontent.com/63444197/117239930-eb6c5580-ae59-11eb-913c-1129b1455b48.png)
