### ISSUE TITLE
set function return on the fly

### ISSUE THREAD

**Issue by botalla** [OfficeDev/office-js-docs-pr#202]
Regarding the return type of a custom function, is it possible to let the function choose whether it returns a string or a number ?
In the old XLL COM world we were able, using the XLOPER12 struct, to set the xltype field to xltypeStr or xltypeNum directly in the function process code, before returning the value.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94ad7803-d4f7-a700-7c7f-204cd8f34e4a
* Version Independent ID: 9c485bae-cab1-bdad-4c8e-baad2b12b22d
* Content: [Create custom functions in Excel (Preview)](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-overview)
* Content Source: [docs/excel/custom-functions-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/custom-functions-overview.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Reezaali** [comment]
Hi @botalla I've confirmed with engineering that this isn't currently supported.

**Comment by botalla** [comment]
Thank you for your response; do you know if it is part of the plan to support this one day ?

**Comment by keyur32** [comment]
Hi @botalla, apologies for the delay. We are planning to add support for a type: "any", which will allow the same behavior of the XLOPER12 type. Will reply when it is available. thanks!
