### ISSUE TITLE
I want to add my custom add-in into the create new event page, and it looks like it isn't possible. 

### ISSUE THREAD

**Issue by aman3011** [OfficeDev/office-js-docs-pr#2028]

**Comment by aman3011** [comment]
![Annotation 2020-07-17 142449](https://user-images.githubusercontent.com/40612714/87823627-5b610f00-c839-11ea-9755-f2ee06dc643f.png)

That's where I want my add in to show up as well. There's no supporting documentation on doing that.

**Comment by mscharlock** [comment]
@ElizabethSamuel-MSFT tagging you in case you might know

**Comment by ElizabethSamuel-MSFT** [comment]
@aman3011 Thanks for asking about this.

For an add-in to be available in a new event, you must define the [AppointmentOrganizerCommandSurface](https://docs.microsoft.com/office/dev/add-ins/reference/manifest/extensionpoint#appointmentorganizercommandsurface) in your add-in manifest. Also see [Add-in commands for Outlook](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/add-in-commands-for-outlook).

Let us know if this helped or you need more information.

Thanks.

**Comment by aman3011** [comment]
Thank you so much Elizabeth, I was able to make it show up on the new event page. But it isn't behaving the way it is when It fires in the Inbox. Do you know why it is doing so?

**Comment by ElizabethSamuel-MSFT** [comment]
@aman3011 Sure, no problem.

It seems that you maybe replaced the original command surface you had defined in your manifest? Note that you can define multiple command surfaces to support some combination (or all combinations) of Compose and Read modes for messages and appointments/meetings/events. See the available [Outlook extension points](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/extensionpoint#extension-points-for-outlook).

**Comment by aman3011** [comment]
No, I defined it as another extension point and basically copied and pasted whatever I had for my inbox and compose message extension point. It fires up but nothing shows up.

**Comment by ElizabethSamuel-MSFT** [comment]
@aman3011 We'll need some more info to help debug. Can you share some version of your manifest and a code sample (e.g., GitHub gist)? What is your add-in trying to do in each mode you're supporting?

Thanks.

**Comment by aman3011** [comment]
<ExtensionPoint xsi:type="AppointmentOrganizerCommandSurface">
            <OfficeTab id="TabDefault">
              <Group id ="apptOrganizerCmdGroup">
                <Label resid ="GroupLabel"/>
                <Control xsi:type="Button" id ="apptOrganizerInsertGist">
                  <Label resid ="TaskpaneButton.Label"/>
                  <Supertip>
                    <Title resid="TaskpaneButton.Label"/>
                    <Description resid="TaskpaneButton.Tooltip"/>
                  </Supertip>
                  <Icon>
                    <bt:Image size="16" resid="Icon.16x16"/>
                    <bt:Image size="32" resid="Icon.32x32"/>
                    <bt:Image size="80" resid="Icon.80x80"/>
                  </Icon>
                  <Action xsi:type="ShowTaskpane">
                    <SourceLocation resid="Taskpane.Url"/>
                  </Action>
                </Control>
              </Group>
              </OfficeTab> 
            </ExtensionPoint>
This is the part of my manifest.

**Comment by ElizabethSamuel-MSFT** [comment]
@aman3011 Thanks for sharing that portion of the manifest. Can you share how you've defined the "ShowTaskpane" action in your code/script?

Thanks.
