### ISSUE TITLE
Cannot view the sample fonts in dark mode theme.

### ISSUE THREAD

**Issue by chamih** [OfficeDev/office-js-docs-pr#2032]
[Enter feedback here]
Cannot view the sample fonts in dark mode theme.
![image](https://user-images.githubusercontent.com/46550766/88007147-6b426100-cb61-11ea-90ea-837a71b2baff.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9434ad18-1448-89e9-059d-04a5fed2ac4d
* Version Independent ID: 470f0cff-6870-1499-94b9-a3721cdf02f3
* Content: [Typography guidelines for Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/design/add-in-typography)
* Content Source: [docs/design/add-in-typography.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/design/add-in-typography.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@chamih Thanks for raising this issue. We'll investigate.

@Rick-Kirkham Can you take a look at this?

Thanks.
