### ISSUE TITLE
Error when trying  to npm start

### ISSUE THREAD

**Issue by u983101** [OfficeDev/office-js-docs-pr#2038]
[Enter feedback here]
Error when trying to npm start

> office-addin-taskpane-js@0.0.1 start C:\Users\jtam1\Documents\office-plug-in\word1\My Office Add-in
> office-addin-debugging start manifest.xml

'office-addin-debugging' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! office-addin-taskpane-js@0.0.1 start: `office-addin-debugging start manifest.xml`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the office-addin-taskpane-js@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jtam1\AppData\Roaming\npm-cache\_logs\2020-07-23T15_17_28_462Z-debug.log

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77e380a7-6e2e-ada8-d297-3fd5018a1958
* Version Independent ID: f23490e8-6eeb-f2d5-6c94-69e3c9ed83f4
* Content: [Build your first Word task pane add-in - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/word-quickstart?tabs=yeomangenerator)
* Content Source: [docs/quickstarts/word-quickstart.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/quickstarts/word-quickstart.md)
* Product: **word**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by mscharlock** [comment]
Hi @u983101 - Thanks for writing in. Can you let me know what the error log from that C drive file says? I am unable to reproduce this problem at the moment but will look into it with that info. 
Also, just curious when the last time you updated your copy of the yo office package? I wonder if this might have something to do with it. 
@TCourtneyOwen and @nokafor for FYI

**Comment by TCourtneyOwen** [comment]
We had a problem with our publishing process a couple days again and office-addin-debugging and other packages were broken by the publishing.  We published again yesterday and things should be working now.  If you update your office-addin-debugging package version to 3.0.33 in your project, I am betting this will fix things.

-Courtney
