### ISSUE TITLE
minor formatting issues in tutorial

### ISSUE THREAD

**Issue by safronau** [OfficeDev/office-js-docs-pr#204]
https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/word-tutorial?tutorial-step=6

has formatting issues on the page starting from 

``` 
```js function 
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65a8acc8-a2b2-4601-d705-269b11d95d10
* Version Independent ID: ec2b21d4-cae6-e1f4-a2ee-937af2ff5d06
* Content: [Word add-in tutorial](https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/word-tutorial?tutorial-step=6)
* Content Source: [docs/tutorials/word-tutorial.yml](https://github.com/OfficeDev/office-js-docs-pr/blob/live/docs/tutorials/word-tutorial.yml)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
Thanks. Fixed now.
