### ISSUE TITLE
Finding the development tools in Windows 10

### ISSUE THREAD

**Issue by bferreira** [OfficeDev/office-js-docs-pr#205]
I found them at C:\Windows\System32\F12\IEChooser.exe not C:\Windows\System32\F12\F12Chooser.exe

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b6ad3bb-b3fe-e8c6-4a38-f6df85dbabf4
* Version Independent ID: 194afc55-e012-edc5-da88-9858f1d52f34
* Content: [Debug add-ins using F12 developer tools on Windows 10](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-add-ins-using-f12-developer-tools-on-windows-10)
* Content Source: [docs/testing/debug-add-ins-using-f12-developer-tools-on-windows-10.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/debug-add-ins-using-f12-developer-tools-on-windows-10.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Reezaali** [comment]
Hi @bferreira thanks for reporting this. I've looked on my machine and I see the following (I'm using Windows 10). Can you share which operating system you're using please?
![image](https://user-images.githubusercontent.com/9439288/41245931-4f543cd8-6d5e-11e8-894f-a572411a599d.png)

**Comment by bferreira** [comment]
Hi, 
I am actually using one of your Vm from here: https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/
![image](https://user-images.githubusercontent.com/1233578/41281144-f92a3992-6e30-11e8-9555-9faba346bfdc.png)
Maybe it is just different from the normal Windows 10. This is what I get:
![image](https://user-images.githubusercontent.com/1233578/41281207-1c809760-6e31-11e8-95c6-63104cdc11e7.png)

**Comment by rvanlaak** [comment]
Same here, it's also `IEChooser.exe` for us on Windows 10 Pro

**Comment by Reezaali** [comment]
@bferreira @rvanlaak - the topic has been updated. Thank you!
