### ISSUE TITLE
Question for Microsoft teammembers about Office Add-In architecture & deployment strategy 

### ISSUE THREAD

**Issue by andrew-j-roberts** [OfficeDev/office-js-docs-pr#2052]
I didn't know where else to ask this question and hope this issue isn't unwelcome here—if it is let me know and I'll repost wherever is appropriate.

[Enter feedback here]

My team and I are attempting to build a plugin for Solace PubSub+ Event Broker that customers will be able to use to get live data feeds in their Excel sheets. The problem we're running into is that the payload schemas aren't uniform, so ideally we'd like end consumers to be able to add custom functions to our template for the plugin & then load the customized plugin into Excel.  It seems from the documentation that the only way to do this is to upload through the AppSource, or use some Microsoft hosted service; our understanding is that there's no way for an end user to upload unverified bundles into Excel.

Is there anyone from Microsoft that I'd be able to chat with about how best to design this style of Office Add-In to facilitate customizability by end users?

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdac492e-7568-9c6a-4ac4-1b0e48898141
* Version Independent ID: 8d1c8f9e-1256-8aa5-2b71-284f7b2ec906
* Content: [Excel JavaScript API overview - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/overview/excel-add-ins-reference-overview)
* Content Source: [docs/reference/overview/excel-add-ins-reference-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/overview/excel-add-ins-reference-overview.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by mscharlock** [comment]
Hi @andrew-j-roberts - Thanks for writing in! We can definitely help connect you with some folks on this issue. Let me ask our team of PMs who might be the right contact and get back to you. Thanks!

**Comment by keyur32** [comment]
Hi @andrew-j-roberts , interesting scenario.

Please give us a way to contact you, as we'd love to chat offline. An easy way you can give us your contact information securely is by sending feedback from within office. 

If you can, please send a smile from within the Office application, as detailed here: https://support.microsoft.com/en-us/office/how-do-i-give-feedback-on-microsoft-office-2b102d44-b43f-4dd2-9ff4-23cf144cfb11

In the notes: Please indicate "To Office Platform team: following up on Github Issue #2052". Please include the box to include your email.

thanks!

**Comment by andrew-j-roberts** [comment]
Thank you @mscharlock!

Hi @keyur32, thank you for getting back to me so quickly. I've gone ahead and sent a smile from my Office application and will be waiting to hear from you on the email address I provided. If you have a hard time accessing my feedback let me know and I'm happy to get you my email however you'd like.

**Comment by ElizabethSamuel-MSFT** [comment]
@keyur32 Can this be closed now?

Thanks.

**Comment by mscharlock** [comment]
Hi all, I am closing as it appears this issue is solved. If anyone needs more assistance, please comment on this thread and I will reopen. Thank you!
