### ISSUE TITLE
Web link issue  https://developer.microsoft.com/en-us/word --> https://docs.microsoft.com/en-us/office/dev/add-ins/develop/create-office-add-ins-in-visual-studio

### ISSUE THREAD

**Issue by csharp-reader** [OfficeDev/office-js-docs-pr#2054]
1. https://developer.microsoft.com/en-us/office
2. click on word icon:   https://developer.microsoft.com/en-us/word
3. click on Create Word add-ins with Visual Studio -- Learn more
4. result: We're sorry, we can't find the page you requested.  --- https://docs.microsoft.com/en-us/office/dev/add-ins/develop/create-office-add-ins-in-visual-studio
5. Of the links provided on the page, one goes back to :   https://docs.microsoft.com/en-us/office/dev/add-ins/develop/create-office-add-ins-in-visual-studio
6. The other link: https://developer.microsoft.com/en-us/office/docs

I am looking for options to program interaction between excel and word.  The user does some work in excel, then auto-creates a word document.  What are the options to do this?  VS c# -- build add-ins?  Python? Pros/cons?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52b9ec0b-74d3-ea1a-b052-54c99173c593
* Version Independent ID: 631afc49-dfa2-b968-8585-24a5e3006fc1
* Content: [We're sorry, we can't find the page you requested - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/create-office-add-ins-in-visual-studio)
* Content Source: [docs/404.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/404.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for reporting this @csharp-reader. I'm assigning @lindalu-MSFT to fix the broken link, which should probably go here: https://docs.microsoft.com/en-us/office/dev/add-ins/develop/develop-add-ins-visual-studio

I'll reach out to our PM team about your question for Excel/Word interactions. I think @keyur32 could provide some suggestions based on the scenario you're describing.

**Comment by AlexJerabek** [comment]
Hi @csharp-reader, 

I went back and checked the broken link you reported. It appears to have been fixed, so I'll be closing this issue.

As for your larger questions about platform choice, add-ins are probably the best choice for any user wanting to stay within Excel, but I'd have to know more specifics about your scenario. I'd recommend reaching out during the monthly community call. You can find the invite [here](https://aka.ms/officeaddinscommunitycall). You can ask questions [ahead of time](https://aka.ms/askofficeaddins) or in the call's chat and those questions will be answered by members of the product team.
