### ISSUE TITLE
Confused about requirement of a Sharepoint App Catalog 

### ISSUE THREAD

**Issue by dubeg** [OfficeDev/office-js-docs-pr#2056]
Concerning this paragraph:
>For content and task pane add-ins, in the supported Office host applications - Excel, PowerPoint, Project, or Word - you also need an app catalog on SharePoint to upload the add-in's XML manifest file.

I think this should be clarified to say that you either need an App Catalog on Sharepoint (for an on-premise SharePoint server), or use Centralized Deployment with Microsoft 365. What do you think?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc3fde38-9149-0403-bd89-e2bf0269749a
* Version Independent ID: 1063c9be-57a5-2d53-a9f1-6b43dc0a8a81
* Content: [Requirements for running Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/requirements-for-running-office-add-ins)
* Content Source: [docs/concepts/requirements-for-running-office-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/concepts/requirements-for-running-office-add-ins.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@dubeg Thanks for asking about this.

@Rick-Kirkham Is this something you can help with?

Thanks.
