### ISSUE TITLE
Tutorial gives error upon pressing F5

### ISSUE THREAD

**Issue by ChemMitch** [OfficeDev/office-js-docs-pr#2060]
Hello,

I followed the steps in the tutorial and pressed F5 to run the add-in.
A message box appears. 
"Value cannot be null.
Parameter name: input"

Can you provide some information on how to deal with this?

I'm using Visual Studio 2019 Community on Windows 10.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c4ddde7-f1fd-44ba-fba1-0ae9d0131df7
* Version Independent ID: d946ffe6-f29f-1563-b679-121090ba60a1
* Content: [Build your first Excel task pane add-in - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-jquery?tabs=visualstudio)
* Content Source: [docs/quickstarts/excel-quickstart-jquery.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/quickstarts/excel-quickstart-jquery.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by alison-mk** [comment]
Hi ChemMitch, thanks for reaching out! I’ve tested the steps in this quick start and don’t encounter the error you mentioned. Can you confirm that you’ve saved each of the files edited (Home.html, Home.js, Home.css, and the XML manifest file) before pressing F5 and launching Excel? 

If this isn’t the issue, could you respond with: 
1. Your version of Excel 
2. A copy of your Home.html and XML manifest files? 

Separately, have you run into trouble with the Yeoman path in this quick start, as well? 

Thanks again! 
Alison

**Comment by ChemMitch** [comment]
Hi Alison,
Thanks for responding! 
Yes; I've saved all the edited files. Just reopened the solution and ran again and got the same error.
1. Microsoft 365 32 bit

[Home.zip](https://github.com/OfficeDev/office-js-docs-pr/files/5019795/Home.zip)
Attached is a zip with Home.html and the XML manifest file.

Regards,
Mitch

**Comment by alison-mk** [comment]
Hi Mitch, 

Thank you for the additional info! I'm still not able to reproduce this issue, even when testing with your files. Could you check your Office version and build number and pass it along? That will help us narrow down potential causes. Here are directions for how to look up your version and build: https://docs.microsoft.com/en-us/office/dev/add-ins/develop/office-versions-and-requirement-sets

Have you tried the Yeoman generator path in this quick start? Perhaps that strategy will help you continue with the quick start while we work out this Visual Studio error. 

Cheers, 
Alison

**Comment by ChemMitch** [comment]
Hi Alison,

 

Here’s the version info – hoping this screenshot gets transmitted back to github.



 

Kind regards,

Mitch Miller, Scientific Thinking LLC

_________________

mitch.miller@thinkscience.us

**Comment by alison-mk** [comment]
Hi Mitch,

Heads up: the screenshot didn't make it through! Would you mind typing up the version + build info? 

Thanks! 
Alison

**Comment by ChemMitch** [comment]
Sure.

Version:  2006 (Build 13001.20384)

 

Kind regards,

Mitch Miller, Scientific Thinking LLC

_________________

mitch.miller@thinkscience.us

**Comment by alison-mk** [comment]
Hey Mitch, thanks for passing this along. Looks like your build meets the minimum requirements. A couple more questions for you: When you press F5 in Visual Studio, does it launch Excel? Where is the error message displayed (in Excel, in Visual Studio, etc)?

Thanks,  
Alison

**Comment by ChemMitch** [comment]
Hi Alison,

 

No, Excel is not launched.

The message is displayed in VS.

 

Thanks for working on this.

 

Kind regards,

Mitch Miller, Scientific Thinking LLC

_________________

mitch.miller@thinkscience.us

**Comment by alison-mk** [comment]
Hi Mitch, 

It seems like you may not have the Office/SharePoint development workload installed in Visual Studio (referenced in this tutorial's prerequisites). Can you confirm you have this workload installed? Here's an article you can use to check if it's installed, and install it if not: https://docs.microsoft.com/en-us/visualstudio/install/modify-visual-studio?view=vs-2019. In the installer Workloads pane, you'll find Office/SharePoint development under the 'Other toolsets' header. Let me know if this helps! 

Cheers, 
Alison

**Comment by ChemMitch** [comment]
Hi Alison,

 

Good idea to check.

Yes; the Office/SharePoint development workload installed – the box is checked on the installer.

 

Kind regards,

Mitch Miller, Scientific Thinking LLC

_________________

mitch.miller@thinkscience.us

**Comment by alison-mk** [comment]
Hi Mitch, 

Thanks for reporting back! We've checked nearly everything I can think of, and I'm still not able to reproduce the error you've reported. One more idea on my side: Can you send along your JS file, so I can test with that, as well? 

In addition to sending along your JS, at this point my main recommendations are that:
- You go through the Visual Studio tutorial steps again carefully, to see if there's something small that you missed (perhaps a typo in the JS?) 
- And you give the Yeoman generator path a try 

I'd like to help you complete this tutorial, even if we don't riddle out what's causing the error you see in Visual Studio. Since the Yeoman path doesn't require Visual Studio, perhaps it'll be a way around this mysterious error! 

Cheers, 
Alison

**Comment by ChemMitch** [comment]
Hi Alison,
Home.js is attached.  I did go through the tutorial twice to make sure.

[Home.js.zip](https://github.com/OfficeDev/office-js-docs-pr/files/5031700/Home.js.zip)

The Yeoman path works.

Thank you!
Mitch

**Comment by alison-mk** [comment]
Hi Mitch, 

Thank you for providing this additional file and information! I'm glad to hear that the Yeoman path does work for you. 

You've given me all the information I can think of, yet I still can't reproduce the error you reported on my machine, so at this point we are unable to move forward with a resolution. We'll keep track of this issue though, and we'll use the information you've provided here if anyone else reports a similar error in the future. 

Thank you for writing in and working with me to try and narrow this down, and thanks for using add-ins! We're very grateful for your efforts to resolve this error.

Alison
