### ISSUE TITLE
Url querying in the Manifest - Outlook Add In

### ISSUE THREAD

**Issue by aman3011** [OfficeDev/office-js-docs-pr#2074]
So, we are designing an add in for outlook for our product. The add in fires from different locales in the outlook interface, namely compose, read, new events parts of the outlook web interface. Now what I want is the ability to open the taskpane url with a query so that it renders different things from different areas it's fired from. 

All I found remotely similar to what I want is this :- 
https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/manifests#localization

I may be wrong or looking at the wrong place, therefore any guidance from the team will be appreciated.

Thanks in advance!

**Comment by ElizabethSamuel-MSFT** [comment]
@aman3011 Thanks for your interest in Outlook add-ins! If I understand correctly, I think what you need is to know more about extension points. In the manifest, you can have a button displayed in the ribbon for each mode. For example, AppointmentAttendeeCommandSurface where a ribbon button (or add-in command) is displayed on the appointment/meeting form for an attendee or in Read mode. Some other command surfaces are AppointmentOrganizerCommandSurface, MessageComposeCommandSurface, and MessageReadCommandSurface. This means that you may not need a query param to handle the various modes.

A couple of additional articles that may help:
- [Extension points for Outlook](https://docs.microsoft.com/office/dev/add-ins/reference/manifest/extensionpoint#extension-points-for-outlook)
- [Add-in commands (i.e., ribbon buttons)](https://docs.microsoft.com/office/dev/add-ins/outlook/add-in-commands-for-outlook)

Also, the localization section refers to supporting multiples languages and multiple countries by having text (like the add-in name and description) translated into those languages included in your manifest. So if a user opens your add-in with their locale (language/region) defined in your manifest, they should see the add-in text in their language.

Can you let us know if this addressed your question? If you need further information, let us know.

Thanks.

**Comment by aman3011** [comment]
Thank you for your reply Elizabeth, I understand Extension points and have used almost all of them for my add in, maybe a better question is how can I make the add in behave/render differently at these extension points. how do I make sure that in taskpane.js that I want to show the Calendar tab of my add in when I'm in the new event page, and the Mail tab of my add in, when I'm in the compose or read section of outlook.

**Comment by ElizabethSamuel-MSFT** [comment]
In that case, it may be that you define different URLs in the resources section of the manifest. Each extension point you've defined can have its own URL and maybe that's where you can try using the query param on the task pane URL.

- [Resources manifest element](https://docs.microsoft.com/office/dev/add-ins/reference/manifest/resources)

**Comment by aman3011** [comment]
So there is nothing I can do from my render function in my taskpane.js file, where I can tell it what to fire based on where the taskpane is being accessed from? going back to query params or something close to that?

**Comment by ElizabethSamuel-MSFT** [comment]
I'll add the product team to see if they have some guidance on this.

@JuaneloJuanelo @exextoc Any thoughts on what @aman3011 can do in this case?

Thanks.

**Comment by aman3011** [comment]
Thank you so much Elizabeth, really appreciate it.

**Comment by exextoc** [comment]
Using query parameters is what we suggest on similar situations. There is not an API that tells the addin which extension point the addin is launched from. As you hinted at already, you can use different source url, which could be different html, or just different query parameters, for each extension point. If parameters don't work well in your scenario, please do tell us more.

**Comment by aman3011** [comment]
So I get the point where I can set different source URL's at the manifest side but now for my taskpane.js how I do access these url's in my individual components. Is there a way I can access url's from the manifest

**Comment by exextoc** [comment]
I assume taskpane.js is referenced by resource the source URL is pointing to? Would document.location https://developer.mozilla.org/en-US/docs/Web/API/Document/location be sufficient to get the current source URL that is currently loaded?

**Comment by aman3011** [comment]
Thanks, I'll keep probing into this and will holler at you guys for more. But thank you again!!
