### ISSUE TITLE
Can we use wildcards in manifests?

### ISSUE THREAD

**Issue by glr0221** [OfficeDev/office-js-docs-pr#2078]
Hello Microsoft,

A good day to you all. 

Currently, referring to this documentation https://docs.microsoft.com/en-us/office/dev/add-ins/develop/localization, there seems to be no way to use wildcards for manifests. Or am i mistaken?

Just to give an example, outlook (OWA) supports over 100++ english locales(codes). And assuming our addin's manifest default locale is not english, then this means i have to provide override values to all 100+ english locales in my manifest to support all english locale codes. Correct? This of course makes the manifest file, lengthy and kinda difficult to debug/verify honestly.

So point being, is there any way where we can use wildcards? where override can be "en-*" to cover all english locales? Or may I request that feature from your good office? This would most likely, also fix issues if your team decided to add new locales in the future. 

My suggestion is. the following :
```
      <Override Locale="en-au" Value="My AU AddIn"/>
      <Override Locale="en-US" Value="My US AddIn"/>
      <Override Locale="en-gb" Value="My GB AddIn"/>
      <Override Locale="en-*" Value="My Super AddIn"/>
```

So in the above case, it will still lookup if the current locale matches an "exact" value, and if it doesn't it will use the "en=*" partial match value.

I hope that makes sense. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80b2525b-823a-7d51-f4b6-6bc7803a3217
* Version Independent ID: 744ec80b-eadd-2819-c8d4-e8d77169c522
* Content: [Localization for Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/localization)
* Content Source: [docs/develop/localization.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/localization.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by glr0221** [comment]
@Rick-Kirkham sorry to mention you on this ticket but is there any way to do this right now? If none, is there any possibility we can mark this as a feature request for MS developers? thank you very much, we really appreciate it.

**Comment by glr0221** [comment]
Hi everyone, so today, I found out that using 2 character (language only) locale-code will actually act like a wildcard in overrides.

So for example, if i wanted to support all spanish regardless of where they are then all i do in the override is as follows : 
`    <Override Locale="es" Value="My Spanish AddIn" />`

For french : 
`<Override Locale="fr" Value="My French AddIn" />`

And if i want an override for French-Canada, but still support all other french regions : 
```
<Override Locale="fr-CA" Value="My French Canadian AddIn" />
<Override Locale="fr" Value="My French AddIn" />
```

I would like to confirm if the above usage is officially supported by the backend?

**Comment by glr0221** [comment]
@erayc-msft @smaremanda no update on this? thank you

**Comment by glr0221** [comment]
anyone here? @erayc-msft @smaremanda

**Comment by AlexJerabek** [comment]
@glr0221, I'll ping some people internally and try to get you a response.

**Comment by glr0221** [comment]
thank you @AlexJerabek  .. really appreciated.

**Comment by AlexJerabek** [comment]
Hi @glr0221, 

Here's the answer from our product team:
> Wildcards are not supported. The alternative is using just the language, but is not supported across all endpoints.

Please create a request for this feature on [UserVoice](https://officespdev.uservoice.com/). There, we can prioritize new feature requests based on community demand.

I'm going to close the issue now, as there's nothing actionable we can do in the docs. Feel free to create a new issue in the https://github.com/OfficeDev/office-js repo if the manifest is not properly honoring localization overrides.

**Comment by glr0221** [comment]
Thank you @AlexJerabek. Sorry for the late reply.
