### ISSUE TITLE
Closing tag for <EquivalentAddins> element in the example provided misses a slash

### ISSUE THREAD

**Issue by sshukurov** [OfficeDev/office-js-docs-pr#2083]
There is a typo in the xml example provided. Closing tag for `<EquivalentAddins>` must look like:
`</EquivalentAddins>`
instead of:
`<EquivalentAddins>`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e6816e9-a82d-012d-de66-5f802b02dba5
* Version Independent ID: 87992af8-d49e-337a-253c-922d56e1281b
* Content: [Extend custom functions with XLL user-defined functions - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/make-custom-functions-compatible-with-xll-udf)
* Content Source: [docs/excel/make-custom-functions-compatible-with-xll-udf.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/make-custom-functions-compatible-with-xll-udf.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for catching this @sshukurov. I'll get a PR going for this fix right now.
