### ISSUE TITLE
How Safe to Use Identity Token for Authentication?

### ISSUE THREAD

**Issue by vigen-b** [OfficeDev/office-js-docs-pr#2084]
Generally this is question!
The page describes how to use identity token for the authentication. Basically it suggests to keep associate user identity context with internal user and later use identity token as a proof for authentication. But other documentation related to identity token, also tests shows that identity token is the same for all add-ins (if they provide the same `appurl`). Feels like we can have security issue here. If attacker will provide the url from our add-in as me, and will add dns record to the computer (e.g. in `/etc/hosts` file). Then he can successfully generate identity token which will be valid for our system (even checking `aud` value will not help here). Is my thoughts right? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb4018a5-e2f4-e9c0-342e-ee3860e1c57f
* Version Independent ID: 2b96c6bb-fab4-7f4d-f472-6af63ba79a24
* Content: [Authenticate a user with an identity token in an add-in - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/authenticate-a-user-with-an-identity-token)
* Content Source: [docs/outlook/authenticate-a-user-with-an-identity-token.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/outlook/authenticate-a-user-with-an-identity-token.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Tagging @ElizabethSamuel-MSFT and @exextoc to investigate.

**Comment by vigen-b** [comment]
`appctx` identifies user. Which field identifies my add-in? As I understand `appctx` will have the same value for different add-ins. How I can make sure that token send from my add-in?

**Comment by vigen-b** [comment]
@exextoc can you please look to the above comment?

**Comment by exextoc** [comment]
The audience of the Exchange identity token is the SourceLocation URL in the base section of the manifest.

Validation is described here:
https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/validate-an-identity-token

And the structure of the token is described here:
https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/inside-the-identity-token

In this way, the token is add-in specific. A token from one add-in cannot be used for another.
One thing that could help, is because all Outlook add-ins are hosted on https, if an attacker overrides a user's host file, this shouldn't be enough to get the add-in to load. The attacker would also need to present a valid certificate for the add-in's URL (or also install certificate(s) on the user's machine).

**Comment by vigen-b** [comment]
@exextoc thank you, that make sense. 
Also one question. In the [Inside the Exchange identity token](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/inside-the-identity-token) page `aud` field described as 
```
The URL of the add-in that requested the token. A token is only valid if it is sent from the add-in that is running in the client's browser. If the add-in uses the Office Add-ins manifests schema v1.1, this URL is the URL specified in the first SourceLocation element, under the form type ItemRead or ItemEdit, whichever occurs first as part of the FormSettings element in the add-in manifest.
```
What if we have both `ItemRead` and `ItemEdit` and first one with my url, and generate token in the second mode? I checked, in that case token `aud` field will contain first (wrong) url.

**Comment by exextoc** [comment]
The audience claim returned in the token payload will be the url specified in the first SourceLocation element under ItemRead or ItemEdit (whichever is specified first in the manifest). So, if you have both ItemRead and ItemEdit, and ItemRead is specified first, the audience claim returned by `getUserIdentityTokenAsync` will be the url of the SourceLocation under ItemRead.

**Comment by vigen-b** [comment]
yes, I mean if `ItemRead` defined first and we generate token in edit mode it will contain url defined for `ItemRead`, which is not always equal to the url defined for `ItemEdit`. So what we will have in this case, if in attacker add-in for `IteamRead` specified my add-in url, and for `ItemEdit` his valid url. He can generate token for my url in edit mode?

**Comment by ElizabethSamuel-MSFT** [comment]
@exextoc Any further comment here? Thx.

**Comment by exextoc** [comment]
The situation described above is mitigated for AppSource add-ins because we validate that there are no duplicate Source Location metadata. Thereby, add-ins deployed via AppSource do not have this issue.

**Comment by vigen-b** [comment]
Cool, thanks for the explanation
