### ISSUE TITLE
app.js doesn't exist in the generated package

### ISSUE THREAD

**Issue by stephenb159** [OfficeDev/office-js-docs-pr#209]
The yeoman generator doesn't create a file call app.js. Can you clarify where we are supposed to add the javascript text? Is there a different filename, or should we be creating the app.js file? Thanks for your help!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6ed3136-1d12-66c2-a8b1-1e7e43553aae
* Version Independent ID: 0e40308a-2d3d-a27b-04d5-1bdd7c09b501
* Content: [Build your first OneNote add-in](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/onenote-quickstart)
* Content Source: [docs/quickstarts/onenote-quickstart.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/quickstarts/onenote-quickstart.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Reezaali** [comment]
@stephenb159 thanks for reporting this issue. We discovered this recently and will be updating the documentation to reflect the correct information.

**Comment by AlexJerabek** [comment]
This was corrected with [PR 249](https://github.com/OfficeDev/office-js-docs-pr/pull/249). Closing the issue. Thanks again for reporting this.
