### ISSUE TITLE
The shared javascript runtime does't work

### ISSUE THREAD

**Issue by uangyydev** [OfficeDev/office-js-docs-pr#2092]
[Enter feedback here]

I followed the instructions in the page of "Configure your Excel add-in to use a shared JavaScript runtime". 
But the function CONTOSO.ADD(1,1) returns #N/A. I have tried the instructions both on macos and online version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a1bb1ec-f7c0-61c7-bd50-4018a2726e3a
* Version Independent ID: dabd68f4-f474-1f01-0022-b2fe55eaafa3
* Content: [Configure your Excel add-in to share the browser runtime - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/configure-your-add-in-to-use-a-shared-runtime)
* Content Source: [docs/excel/configure-your-add-in-to-use-a-shared-runtime.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/configure-your-add-in-to-use-a-shared-runtime.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @uangyydev, 

Thanks for reporting this issue. I'm assigning @mscharlock to follow-up and investigate.
