### ISSUE TITLE
I need instructions to attach the DevTool Console to the Office Word Add-in Task Panel to observe JavaScript console.log output.

### ISSUE THREAD

**Issue by ConwayMagee** [OfficeDev/office-js-docs-pr#2095]
Instructions are needed to attach the Edge and/or Chrome DevTools  to the Office Word Add-in Task Panel to observe JavaScript console.log output.

At issue is that the Visual Studio JavaScript console was  removed  some time ago. The only tool which works is an older Microsoft Edge DevTools Preview product. All steps in the MS doc will not connect to my Word Add-in Task Pane. Cleare document would be helpful.

**Comment by AlexJerabek** [comment]
Hi @ConwayMagee 

Thanks for raising this issue. Have you checked out these documents about debugging: 
- [Debug add-ins using developer tools on Windows 10](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-add-ins-using-f12-developer-tools-on-windows-10)
- [Microsoft Office Add-in Debugger Extension for Visual Studio Code](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-with-vs-extension)

Please let me know if those are insufficient or there is some other place that you expected to discover this information. Thanks!

**Comment by ConwayMagee** [comment]
Sorry but family matters interviened. I truly feel lack of interest to support Office Add-ins using JavaScript. It seems the push is with c# and React
