### ISSUE TITLE
How to scope the add in to only the event clicked on from the ApptOrganizer Extension Point

### ISSUE THREAD

**Issue by aman3011** [OfficeDev/office-js-docs-pr#2097]
I want to get calendar event details of only a particular event on the add in, I have been only been able to retrieve all the calendar events at once, but I want my add in to have the capability of just displaying the details of the event it is scoped on. 

![Annotation 2020-08-17 151703](https://user-images.githubusercontent.com/40612714/90440462-e2a1dc80-e09c-11ea-80c6-8e3f27c58377.png)

As you see in the screenshot, I only want the details of that particular event to be displayed on my add-in

**Comment by nkkinariwala** [comment]
Hi @aman3011 , In order for us to triage this issue, we need more information like environment details as per the Template. Can you please complete and then I can assign to our product team to investigate?

**Comment by aman3011** [comment]
Hi @nkkinariwala, what kind of environment details are you asking for, I'm developing this using React and currently running the app on our dev server if that answers your question.

**Comment by exextoc** [comment]
Properties of the current item in focus are on Office.context.mailbox.item. For example if you want the subject in an AppointmentRead object, you can access Office.context.mailbox.item.subject 

https://docs.microsoft.com/en-us/javascript/api/outlook/office.appointmentread?view=outlook-js-preview

Appointment Compose functions and properties: 

https://docs.microsoft.com/en-us/javascript/api/outlook/office.appointmentcompose?view=outlook-js-preview

**Comment by aman3011** [comment]
Thank you so much, I was able to use Office.context.mailbox.item in my rest API and retrieve my information
