### ISSUE TITLE
The documentation should mention all manditory scopes

### ISSUE THREAD

**Issue by massonj** [OfficeDev/office-js-docs-pr#2109]
I got an error message validatign my addin which says that I don't have all the manditory scopes defined. THe documentation mentions "profile" at the only alwasy required scope, but the validation tool also says that I need openid. 

```
❯ npm run validate

> office-addin-taskpane-sso@0.0.0 validate ...
> office-addin-manifest validate manifest.xml

The manifest is not valid.

Error # 1: 
WebApplicationInfo mandatory Scopes not defined: WebApplicationInfo Scope field does not contain all mandatory values. Please see https://docs.microsoft.com/en-us/office/dev/add-ins/develop/sso-in-office-add-ins for details.
  - Details: Provided Scopes 'User.Read, profile' does not contain all mandatory scopes 'profile, **openid**'

Additional information: 
Package Type Identified: Package of your add-in was parsed successfully.
```

The documentation and the validation tool should agree :-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb06c24b-9d11-9cc5-2e98-561601452638
* Version Independent ID: abda21d9-6e80-8319-c56f-004658014e3c
* Content: [Enable single sign-on for Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/sso-in-office-add-ins)
* Content Source: [docs/develop/sso-in-office-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/sso-in-office-add-ins.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
@mattgeim Is it correct that openid is now mandatory? Or is this a bug in the validation tool?

**Comment by mattgeim** [comment]
> @mattgeim Is it correct that openid is now mandatory? Or is this a bug in the validation tool?

Mandatory @Rick-Kirkham - I'm updating the overview docs and will have a PR shortly.

**Comment by mattgeim** [comment]
We've updated the documentation with PR 2110, I will close the issue with the merge that happened today.  Please feel free to reopen if you have any questions.
