### ISSUE TITLE
Sideload is not supported.

### ISSUE THREAD

**Issue by mug-cat** [OfficeDev/office-js-docs-pr#2114]
I am following the tutorial tagged below on a Mac.

I am getting this error message with npm start:

\> office-addin-taskpane@0.0.1 start /Users/dean/Outlook add-in tutorial
\> office-addin-debugging start manifest.xml

Debugging is being started...
App type: desktop
The dev server is already running on port 3000.
Sideloading the Office Add-in...
Error: Unable to start debugging.
office-addin-debugging: Unable to sideload the Office Add-in. 
Error: Sideload is not supported.

I have already tried the fix suggested in the issue https://github.com/OfficeDev/office-js-docs-pr/issues/1321 to no avail.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b2e062e-1a7a-1861-bf20-c23ac64d0d37
* Version Independent ID: ae2d1395-2a87-1bda-00fb-1b30f8e27b66
* Content: [Outlook add-ins overview - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/outlook-add-ins-overview)
* Content Source: [docs/outlook/outlook-add-ins-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/outlook/outlook-add-ins-overview.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@hthjthtrh Thanks for asking about this.

@TCourtneyOwen Can you take a look?

Here are the links to the tutorial and quick start for your convenience.
- [Outlook tutorial](https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/outlook-tutorial#test-the-generated-add-in)
- [Outlook quick start](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/outlook-quickstart?tabs=yeomangenerator#try-it-out)

Thanks.

**Comment by TCourtneyOwen** [comment]
Sideloading is not supported for Outlook. To sideload for Outlook, you need to follow these steps:  https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/sideload-outlook-add-ins-for-testing.  I think we should update the tutorial instructions to say "npm run dev-server" instead, as this will skip sideloading for unsupported hosts.

**Comment by hthjthtrh** [comment]
That page honestly needs a complete revision. There are too many redundant and confusing steps and erroneous codes that makes it a less frustrating learning journey to just learn everything by yourself than to follow this tutorial.

**Comment by ElizabethSamuel-MSFT** [comment]
@hthjthtrh Thanks for sharing your feedback! We're always open to hearing how we can improve the user experience.

Also, I'm curious if you had tried the [Outlook quick start](https://docs.microsoft.com/office/dev/add-ins/quickstarts/outlook-quickstart?tabs=yeomangenerator)? If so, how was that experience for you?

Thanks.

**Comment by tsolman** [comment]
Why is this issue closed?
Still, the documentation is not complete and i get the same error on Mac.

**Comment by samantharamon** [comment]
Hi @tsolman. Thanks for reporting this issue. Are you referring to the [Sideload Outlook add-ins for testing](https://learn.microsoft.com/office/dev/add-ins/outlook/sideload-outlook-add-ins-for-testing?tabs=windows) article by any chance? To help us troubleshoot the issue further, what Office, macOS, Node.js, and npm versions are you using?

**Comment by samantharamon** [comment]
Hi @tsolman,

As we haven't heard back from you, I will go ahead and close this issue. Should you require further assistance, please [open a new issue](https://github.com/OfficeDev/office-js-docs-pr/issues/new) so that we can assist you.

Thank you.
