### ISSUE TITLE
Mention 12009 error in "Errors and events in the dialog window" section

### ISSUE THREAD

**Issue by nikolay-borzov** [OfficeDev/office-js-docs-pr#212]
Excel Online allows ignoring dialog box. It produces the event:
```
code: 12009
message: "The user chose to ignore the dialog box."
name: "Display Dialog Error"
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a714626a-058a-789e-6add-5e9dfb21fd1f
* Version Independent ID: 1b88a28c-fc36-4518-2808-7246f08d9753
* Content: [Use the Dialog API in your Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins)
* Content Source: [docs/develop/dialog-api-in-office-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/dialog-api-in-office-add-ins.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Reezaali** [comment]
@nikolay-borzov thanks for reporting this issue. Let me speak to engineering and update the document.

**Comment by kbrandl** [comment]
@nikolay-borzov We've added error code **12009** to the docs and those changes will be published within the next few days. Thanks again for reporting this issue!
