### ISSUE TITLE
 Programmatically Update Calendar Events from User from taskpane in React 

### ISSUE THREAD

**Issue by aman3011** [OfficeDev/office-js-docs-pr#2120]
So, I have an events component which is scoped to a single event by using the event id. I am able to retrieve the details of that event by using the REST API.

Now what I want to do with that is, update the calendar event on Outlook by taking user input from the taskpane. I am at a loss on what to use to achieve that since there is no clear documentation that specifies the resources I need to do this. 

I am attaching a screenshot to show what I currently have

![Annotation 2020-08-25 103227](https://user-images.githubusercontent.com/40612714/91195107-5ad05980-e6be-11ea-94fb-583aab4e7143.png)

**Comment by ElizabethSamuel-MSFT** [comment]
@aman3011 Thanks for asking about this. From the screenshot, it seems like the user is an attendee on this meeting? If that's the case, then, for the most part, the user can't edit the appointment. For properties and methods available on an appointment in read/attendee mode, see [AppointmentRead](https://docs.microsoft.com//javascript/api/outlook/office.appointmentread?view=outlook-js-1.8).

For properties and methods available on an appointment in compose/organizer mode, see [AppointmentCompose](https://docs.microsoft.com/javascript/api/outlook/office.appointmentcompose?view=outlook-js-1.8).

**Comment by aman3011** [comment]
Thanks for your response, so I can't have a user whether attendee or not change calendar event details from the taskpane?

**Comment by ElizabethSamuel-MSFT** [comment]
How the user can interact with an event in the Outlook UI is usually replicated by the available API. So if the user is the organizer/creator of an event, they can usually change details, similar to the UI behavior in Outlook. You can see available members on the AppointmentCompose page.
