### ISSUE TITLE
Office Addin Vue js quickstart TYPO

### ISSUE THREAD

**Issue by ramalva92** [OfficeDev/office-js-docs-pr#2124]
[Enter feedback here]
in reference to: https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-vue

There is a TYPO in part 3 in the HTML code is presented.
SHOULD not be id="content-main", it should be class="content-main"
since it is defined as a class in the styles.

 .content-main {
    background: #fff;
    position: fixed;
    top: 80px;
    left: 0;
    right: 0;
    bottom: 0;
    overflow: auto;
  }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea230e95-f483-6d19-8167-2341a03cf396
* Version Independent ID: 3846765f-7587-fec4-711e-84edfce9c30c
* Content: [Build an Excel task pane add-in using Vue - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-vue#secure-the-app)
* Content Source: [docs/quickstarts/excel-quickstart-vue.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/quickstarts/excel-quickstart-vue.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by lindalu-MSFT** [comment]
Fixed, submitted PR to merge fix to live. Check back tomorrow!

**Comment by lindalu-MSFT** [comment]
@ramalva92 P.S. THANK YOU very much!
