### ISSUE TITLE
When is the shared runtime environment changing to use Edge instead of IE11? 

### ISSUE THREAD

**Issue by astak15** [OfficeDev/office-js-docs-pr#2133]
Now that Microsoft is discontinuing IE support, can you tell me when the shared runtime feature be migrated to use Edge instead of IE11? It will also improve the usability of the application. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc89eff2-1c69-c80f-2cfb-43746309f2b7
* Version Independent ID: af86e11c-93ec-c0d9-bccd-cdd993fce37c
* Content: [Run your add-in code in a shared JavaScript runtime - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-shared-overview)
* Content Source: [docs/excel/custom-functions-shared-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/custom-functions-shared-overview.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by mscharlock** [comment]
Hi @astak15 - I can't share any timelines with you at this point, but if we develop new things with shared runtime (such as the change you suggest), I will be updating the docs and an update would go into our developer newsletter! Sorry I cannot provide any more information for you. Thanks!

**Comment by astak15** [comment]
I guess my followup question would be whether the add-in would work with Mac OS as well even if using the IE11 engine? My add-in works in MacOS without shared runtime as of now

**Comment by mscharlock** [comment]
So long as the version of Office is up to date on Mac (16.35 or later), shared runtime will work. The IE11 engine is only used on Windows 32-bit. Let me know if you have any other questions!
