### ISSUE TITLE
UX Pattern Sample

### ISSUE THREAD

**Issue by ChristopherHButler** [OfficeDev/office-js-docs-pr#215]
The link to the UX pattern sample is not working. It points to a VSTS page and I get a 404 error saying I do not have access. Is this meant to be a public link? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c50f3482-ada7-b54a-392f-73b7524cd9dc
* Version Independent ID: 36f8730a-c373-b4da-dbbb-917a7ac54235
* Content: [Dialog boxes in Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/design/dialog-boxes)
* Content Source: [docs/design/dialog-boxes.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/design/dialog-boxes.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Reezaali** [comment]
I've made an update to the topic, which should be reflected in the live document later today/tomorrow. I'll go ahead and close the issue. Thank you!
