### ISSUE TITLE
CORS errors calling Outlook API from Outlook add-in

### ISSUE THREAD

**Issue by brianthemike** [OfficeDev/office-js-docs-pr#2166]
This appears to be good info, however I can't get Outlook API calls to work properly due to CORS errors.  Is there a way to set CORS for Outlook 365 to allow other origins? The API calls I have in place work fine in Postman, after I get the item ID and bearer token, as it is not a browser implementation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fde53b2d-39f8-5b6d-5e37-068b4d93f049
* Version Independent ID: 9c7ff3ef-a188-bd28-65bb-1d620d4a8842
* Content: [Use the Outlook REST APIs from an Outlook add-in - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/use-rest-api)
* Content Source: [docs/outlook/use-rest-api.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/outlook/use-rest-api.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for the question @brianthemike. 

@exextoc and @ElizabethSamuel-MSFT, can you please provide some guidance here?

**Comment by exextoc** [comment]
Which client are you seeing this issue on (win-32, OWA, mac)?

Have you added all domains you are calling in the [AppDomains ](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/appdomain) element the manifest?

**Comment by brianthemike** [comment]
This is occurring on win-32 and OWA.  Domains were added in the AppDomains element in the manifest, as:
`<AppDomains>`
   `<AppDomain>https://mymail.mycompany.com</AppDomain>`
`</AppDomains>`
I am getting the itemId (converted to RestId) and the Office.context.mailbox.restUrl value is `https://mymail.mycompany.com/api` to which I am appending `/v2.0/me/messages/myItemIdVariable`
This is also occurring when running the add-in from either localhost or when the add-in is deployed to a remote server. 
The add-in works fine up until the Rest call, where function`.fail(function(error){ ... }` which shows  the error as:
`{"readyState":0,"status":0,"statusText":"error"}` 
and the console log has the CORS error:
`Access to XMLHttpRequest at 'https://mymail.mycompany.com/api/v2.0/me/messages/AAMkADEyMGZlZGVlLTllNjktNGFmMC1hZjBhLThiMmViOThmMTUxOABGAAAAAAAlWKmEQ96rQZNhqRDEqkxiBwCSzio4QtJ0QZ8BUgEg3TZWAAAAAAEMAACSzio4QtJ0QZ8BUgEg3TZWAAAvKXVeAAA=' from origin 'https://myserver.mycompany.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`
I have also added an AppDomain entry for where the add-in is hosted, trying both `https://myserver.mycompany.com` and for my localhost server but as expected that did not resolve the issue.

**Comment by exextoc** [comment]
What version of Exchange are you using? Calling REST APIs from add-ins are only supported in Exchange Online or in [hybrid environments](https://docs.microsoft.com/en-us/graph/hybrid-rest-support).

**Comment by brianthemike** [comment]
Currently on 15.1.2044.4 of Exchange for my mailbox, another test account I am using is on whatever version the 365 tenant is running which I believe is the latest since none of the regular user's mailboxes are not in 365 yet.  I will have to verify that version.

**Comment by exextoc** [comment]
Adding some more information about using [REST in an on-premise Exchange deployment](https://techcommunity.microsoft.com/t5/exchange-team-blog/on-premises-architectural-requirements-for-the-rest-api/ba-p/605609): The REST token can be used from an add-in backend but not from the client since CORS is not supported in that scenario (as you noticed here).

For a mailbox in O365, CORS should work in that scenario, so the REST call can be made directly from add-in client code.
