### ISSUE TITLE
Incorrect instructions for updating webpack.config.js causes error

### ISSUE THREAD

**Issue by dxs-dbest** [OfficeDev/office-js-docs-pr#2179]
The instructions in section 'Update webpack config settings' need to be updated.  When I updated the plugins array and ran 'npm run build' I encountered an error.  I resolved the error by entering the dialog.css pattern in the patterns array.

The final resulting plugins array was:

`    plugins: [
      new CleanWebpackPlugin(),
      new HtmlWebpackPlugin({
        filename: "taskpane.html",
        template: "./src/taskpane/taskpane.html",
        chunks: ["polyfill", "taskpane"]
      }),
      new CopyWebpackPlugin({
        patterns: [
          {
            to: "taskpane.css",
            from: "./src/taskpane/taskpane.css"
          },
          {
            to: "dialog.css",
            from: "./src/settings/dialog.css"
          },
          {
            to: "[name]." + buildType + ".[ext]",
            from: "manifest*.xml",
            transform(content) {
              if (dev) {
                return content;
              } else {
                return content.toString().replace(new RegExp(urlDev, "g"), urlProd);
              }
            }
          }
        ]
      }),
      new HtmlWebpackPlugin({
        filename: "commands.html",
        template: "./src/commands/commands.html",
        chunks: ["polyfill", "commands"]
      }),
      new HtmlWebpackPlugin({
        filename: "dialog.html",
        template: "./src/settings/dialog.html",
        chunks: ["polyfill", "dialog"]
      })
    ],`

contents of package.json:

`{
  "name": "office-addin-taskpane-js",
  "version": "0.0.1",
  "repository": {
    "type": "git",
    "url": "https://github.com/OfficeDev/Office-Addin-TaskPane-JS.git"
  },
  "license": "MIT",
  "config": {
    "app-to-debug": "outlook",
    "app-type-to-debug": "desktop",
    "dev-server-port": 3000
  },
  "scripts": {
    "build": "webpack -p --mode production --https false",
    "build:dev": "webpack --mode development --https false",
    "build-dev": "webpack --mode development --https false && echo . && echo . && echo . && echo Please use 'build:dev' instead of 'build-dev'.",
    "dev-server": "webpack-dev-server --mode development",
    "lint": "office-addin-lint check",
    "lint:fix": "office-addin-lint fix",
    "prettier": "office-addin-lint prettier",
    "start": "office-addin-debugging start manifest.xml",
    "start:desktop": "office-addin-debugging start manifest.xml desktop",
    "start:web": "office-addin-debugging start manifest.xml web",
    "stop": "office-addin-debugging stop manifest.xml",
    "validate": "office-addin-manifest validate manifest.xml",
    "watch": "webpack --mode development --watch"
  },
  "dependencies": {
    "jquery": "^3.5.1",
    "showdown": "^1.9.1",
    "urijs": "^1.19.2"
  },
  "devDependencies": {
    "@babel/core": "^7.10.2",
    "@babel/polyfill": "^7.10.1",
    "@babel/preset-env": "^7.10.2",
    "@types/find-process": "1.2.0",
    "@types/office-js": "^1.0.108",
    "@types/office-runtime": "^1.0.14",
    "babel-loader": "^8.1.0",
    "clean-webpack-plugin": "^3.0.0",
    "copy-webpack-plugin": "^6.0.3",
    "eslint-config-office-addins": "^1.0.15",
    "find-process": "^1.4.3",
    "file-loader": "^4.2.0",
    "html-loader": "^0.5.5",
    "html-webpack-plugin": "^4.3.0",
    "office-addin-cli": "^1.0.10",
    "office-addin-debugging": "^3.0.31",
    "office-addin-dev-certs": "^1.5.2",
    "office-addin-lint": "^1.0.23",
    "office-addin-manifest": "1.5.0",
    "office-addin-prettier-config": "^1.0.12",
    "source-map-loader": "^0.2.4",
    "ts-loader": "^6.2.2",
    "typescript": "^3.9.5",
    "webpack": "^4.43.0",
    "webpack-cli": "^3.3.12",
    "webpack-dev-server": "^3.11.0"
  },
  "prettier": "office-addin-prettier-config"
}
`
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a59958d2-f428-9ca2-3440-a5af662386c0
* Version Independent ID: dcaf0b5b-08ea-c437-130b-342a1be62a16
* Content: [Tutorial: Build a message compose Outlook add-in - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/outlook-tutorial)
* Content Source: [docs/tutorials/outlook-tutorial.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/tutorials/outlook-tutorial.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@dxs-dbest Thanks for letting us know about this issue.

@TCourtneyOwen Can you take a look?

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@TCourtneyOwen Any update here? Thx.

**Comment by TCourtneyOwen** [comment]
I can look into this tomorrow. Deciphering webpack issues is never simple and requires focused attention. Not something I can just quickly determine without setting aside some time to look at this. 

-Courtney

**Comment by mehmetkaradeniz** [comment]
Might be related to this #2234

**Comment by TCourtneyOwen** [comment]
Indeed I hit an error too when following the tutorial and then trying "npm run build":

ValidationError: Invalid options object. Copy Plugin has been initialized using an options object that does not match the API schema.
 - options[0] misses the property 'patterns'. Should be:
   [non-empty string | object { from, to?, context?, globOptions?, filter?, toType?, force?, flatten?, transform?, cacheTransform?, transformPath?, noErrorOnMissing? }, ...] (should not have fewer than 1 item)
    at validate (C:\outlooktutorial\node_modules\copy-webpack-plugin\node_modules\schema-utils\dist\validate.js:98:11)
    at new CopyPlugin (C:\outlooktutorial\node_modules\copy-webpack-plugin\dist\index.js:32:30)
    at module.exports (C:\outlooktutorial\webpack.config.js:63:7)
    at handleFunction (C:\outlooktutorial\node_modules\webpack-cli\bin\utils\prepareOptions.js:21:13)
    at prepareOptions (C:\outlooktutorial\node_modules\webpack-cli\bin\utils\prepareOptions.js:9:5)
    at requireConfig (C:\outlooktutorial\node_modules\webpack-cli\bin\utils\convert-argv.js:117:14)
    at C:\outlooktutorial\node_modules\webpack-cli\bin\utils\convert-argv.js:123:17
    at Array.forEach (<anonymous>)
    at module.exports (C:\outlooktutorial\node_modules\webpack-cli\bin\utils\convert-argv.js:121:15)
    at C:\outlooktutorial\node_modules\webpack-cli\bin\cli.js:71:45
    at Object.parse (C:\outlooktutorial\node_modules\yargs\yargs.js:576:18)
    at C:\outlooktutorial\node_modules\webpack-cli\bin\cli.js:49:8

Updating the webpack plugins as @dxs-dbest does appear to fix the build problem. Now I just need to try and complete the tutorial

**Comment by TCourtneyOwen** [comment]
I am not having luck completing the tutorial however.  When I click on the Done button in this dialog to configure my GitHub user name nothing happens and I believe that prevents me from proceeding further on with the scenario:

![image](https://user-images.githubusercontent.com/38081557/94627721-229ad880-0273-11eb-97a1-e3e0a56ee541.png)

**Comment by ElizabethSamuel-MSFT** [comment]
@dxs-dbest Thanks again for sharing these updates.

@TCourtneyOwen Thanks for taking the time to verify these changes.

I'm making these webpack config revisions to the tutorial's instructions and the changes should be published soon.

@TCourtneyOwen Also, I'm not able to repro your issues with the tutorial so it seems independent of the build changes. Feel free to follow up with me if you'd like to debug offline.

Thanks.
