### ISSUE TITLE
Incorrect type in library `office-js`, `interface RemoveHandlerOptions`

### ISSUE THREAD

**Issue by MrChe** [OfficeDev/office-js-docs-pr#2182]
![image](https://user-images.githubusercontent.com/9495532/93316770-4bec4b00-f815-11ea-91c3-2758b946a35e.png)
I guess it's a huge mistake, need change to `any` because need added a link to the handler
https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/bind-to-regions-in-a-document-or-spreadsheet.md#remove-an-event-handler - in this example correct way, but an interface to library `office-js` - incorrect

**Comment by Rick-Kirkham** [comment]
@MrChe Thanks for catching this. I think instead of `any`, maybe it should be narrowed to a function. I think something like `handler?: () => {}` has that effect, but I'll research it.
