### ISSUE TITLE
Selection of Email Message or Calendar appointment is mandatory to see Outlook Add-In

### ISSUE THREAD

**Issue by PrashanthReddy7** [OfficeDev/office-js-docs-pr#2183]
## Article URL
https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/outlook-add-ins-overview#mailbox-items-available-to-add-ins

## Issue
Selection of Email Message or Calendar appointment is mandatory to see Outlook Add-In ?

1. We have created a Add-In called "ABC"
2. To view or perform some action on add-in, selection of email or appoutnment is mandatory.
3. Without selection of meesages, the add-in is greyed out.

Means, we want to see or perform action on add-in without selecting of any email or appoitnmnet, means the add-in should not be associated with any email.

This is missed in documentation , please confirm?

**Comment by AlexJerabek** [comment]
@ElizabethSamuel-MSFT, could you please investigate?

**Comment by ElizabethSamuel-MSFT** [comment]
@PrashanthReddy7 Thanks for asking about this. Yes, a message or appointment should be open/selected for the add-in to activate. We're clarifying this in the documentation.

If you would like to see features like add-in activation at the mailbox/calendar level, please go to [UserVoice](https://officespdev.uservoice.com/) to find and upvote an existing feature request (e.g., [Outlook add-in command button on calendar overview](https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/35849557-outlook-add-in-command-button-on-calendar-overview)), or add a new request. The product team considers UserVoice requests when they plan upcoming features.

Thanks.
