### ISSUE TITLE
npm install missing install

### ISSUE THREAD

**Issue by davyarris** [OfficeDev/office-js-docs-pr#2193]
The  command to install office-addin-manifest in missing the install flag:

```
npm -g office-addin-manifest
````

should be

``` 
npm install -g office-addin-manifest
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a89c40a2-3e90-a295-7375-6d52ba597808
* Version Independent ID: 8cd2f086-5c18-ee17-9ced-ffeba1de0b78
* Content: [Validate an Office Add-in's manifest - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/troubleshoot-manifest)
* Content Source: [docs/testing/troubleshoot-manifest.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/troubleshoot-manifest.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@davyarris Thanks for pointing this out. We're fixing this issue and the update should be published soon.

Thanks.
