### ISSUE TITLE
Step 4 -- should add that the reading pane needs to be enabled in outlook

### ISSUE THREAD

**Issue by lmccord** [OfficeDev/office-js-docs-pr#2199]
I spent hours trying to figure out what was wrong because my taskpane buttons were there but greyed-out.  I didn't realize my reading pane was not enabled, and didn't know to look for that. I did find that information in a separate help document (but now I can't find it again, sorry...)
Anyway, now that I've enabled my reading pane, everything works as documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 930ce4fc-c8b8-f756-f03f-a716f1ef7883
* Version Independent ID: 753a2e38-9430-25bb-5409-b7eed9c88e47
* Content: [Build your first Outlook add-in - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/outlook-quickstart?tabs=yeomangenerator)
* Content Source: [docs/quickstarts/outlook-quickstart.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/quickstarts/outlook-quickstart.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for reporting this @lmccord. 

@ElizabethSamuel-MSFT, can you please take a look at this issue and update the quick start accordingly? Thank you!

**Comment by ElizabethSamuel-MSFT** [comment]
@lmccord We're clarifying this and the change should be published this week.

If you need further clarification or have other questions, let us know.

Thanks.
