### ISSUE TITLE
Improve "F12 developer tool ..." help page for Outlook plugins

### ISSUE THREAD

**Issue by binarykitchen** [OfficeDev/office-js-docs-pr#220]
This one page only has examples for Word

https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/debug-add-ins-using-f12-developer-tools-on-windows-10.md

But doesn't have an example for Outlook add-ins. Our problem is that, in the F12Chooser, we never see a target to choose for Outlook add-ins. They just never appear there. Also there is no UI control from that developer tool to select a file. Hence would be good to document more here. We're in the dark here.

Thanks!

**Comment by Reezaali** [comment]
@binarykitchen sorry to hear this is blocking you. Let me sync with engineering and get back to you.

**Comment by exextoc** [comment]
The steps on that page you linked should work for Outlook add-ins using task panes. Unfortunately, the F12Chooser is known to not work with add-ins using Execute Functions. If you are trying to test an add-in with Execute Functions, we suggest that you attach to VisualStudio in script mode or to some other script debugger.

**Comment by binarykitchen** [comment]
@exextoc I see. Can you add this to the documentation?

**Comment by kbrandl** [comment]
@binarykitchen thanks for raising this question. We've added a note to [this article](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-add-ins-using-f12-developer-tools-on-windows-10) per the feedback received in this thread.
