### ISSUE TITLE
Deprecated Edge Functionality Reference?

### ISSUE THREAD

**Issue by Starscade** [OfficeDev/office-js-docs-pr#2200]
In the section describing how to "Allow localhost loopback" on the "about:flags" page in Edge, _about:flags_ is redirected to _edge://flags_ which doesn't contain a reference to "Allow localhost loopback." As it stands, I'm unable to figure out how to sideload Add-ins for office apps in Edge without this functionality by reading the dev docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ab35128-1e97-c6ad-babc-f696f2e7b0fe
* Version Independent ID: cd1bacb1-14d7-a38d-321c-ebc2a526e03b
* Content: [Sideload Office Add-ins in Office on the web for testing - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/sideload-office-add-ins-for-testing)
* Content Source: [docs/testing/sideload-office-add-ins-for-testing.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/sideload-office-add-ins-for-testing.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for reporting this @Starscade. 

@Rick-Kirkham, could you please take a look at this issue? Thank you!

**Comment by Rick-Kirkham** [comment]
@Starscade If you just skip that bullet, can you sideload in Office on the web anyway?

**Comment by Rick-Kirkham** [comment]
@Starscade The product team reports to me that both bullets in that note should be replaced with a note saying that you should run the following command at a command prompt:

**npx office-addin-dev-settings appcontainer EdgeWebView --loopback --yes**

I'll update the documentation.
