### ISSUE TITLE
Availability of `Office.context.mailbox.displayNewMessageForm` is inconsistent in the docs

### ISSUE THREAD

**Issue by adem** [OfficeDev/office-js-docs-pr#2201]
The [method overview page for `Office.context.mailbox`](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/objectmodel/requirement-set-1.8/office.context.mailbox#methods) states that `displayNewMessageForm` is available in both `Read` and `Compose` mode.

This, however, is not consistent with the [method documentation](https://docs.microsoft.com/en-us/javascript/api/outlook/office.mailbox?view=outlook-js-1.8&preserve-view=true#displaynewmessageform-parameters-), which states `Read` as the only applicable Outlook mode. This is consistent with the behavior of Office.js, which returns `undefined` for `Office.context.mailbox.displayNewMessageForm` while in `Compose` mode.

That being said, I think having the possibility to create a new message while in `Compose` mode does make sense, e.g. when you want your `Compose` add-in to also provide a "Feedback" button, which prepares a new feedback email to the developer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a3d1251-72d5-7739-5b5e-54b8a2d74206
* Version Independent ID: 5f20282e-acf7-2a4e-fcb9-55ed98b532fe
* Content: [Office.context.mailbox - requirement set 1.6 - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/objectmodel/requirement-set-1.6/office.context.mailbox)
* Content Source: [docs/reference/objectmodel/requirement-set-1.6/office.context.mailbox.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/objectmodel/requirement-set-1.6/office.context.mailbox.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for pointing this out @adem. 

@ElizabethSamuel-MSFT, could you please take a look at this issue? Thanks!

**Comment by ElizabethSamuel-MSFT** [comment]
@adem  Thanks again for letting us know. We're correcting the supported modes and the changes should be published this week.

If you'd like this API to be available in Compose mode, you can upvote an existing Outlook feature request on [UserVoice](https://officespdev.uservoice.com/) (or create a request).

Thanks.
