### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by choatehall** [OfficeDev/office-js-docs-pr#222]
Documents/Sample/Demo from Microsoft sites usually don't work.  This one the same.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73aacbba-c4fa-7930-3b2a-125b8cb123dc
* Version Independent ID: fc8c7849-b52d-2387-8fe0-ca2469746f1b
* Content: [Create and debug Office Add-ins in Visual Studio](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/create-and-debug-office-add-ins-in-visual-studio)
* Content Source: [docs/develop/create-and-debug-office-add-ins-in-visual-studio.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/create-and-debug-office-add-ins-in-visual-studio.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Reezaali** [comment]
@choatehall sorry to hear that this is blocking you. Was there a particular step that didn't work?

**Comment by choatehall** [comment]
I went to the link of Office Developer Tools, I can only download vs 2017 from there. So I download and install vs2017, and have the office developer tools installed.  I then started a outlook add-in project, but I find neither  home folder nor app.js.  I only have messageRead.html, js. css file... 

Then I put our owa outlook url, I got 401 unauthorized... Don't know where to find Exchange web service url either...

**Comment by Reezaali** [comment]
@ElizabethSamuel-MSFT - this might be related to the other issues we're investigating.
https://github.com/OfficeDev/outlook-dev-docs/issues/272

**Comment by ElizabethSamuel-MSFT** [comment]
I think the issue here is that the article is targeting VS 2015 or earlier while VS 2017 has a different template. @choatehall we'll look into updating this article. Thanks.

In the meantime, consider signing up for the [Office 365 developer program](https://developer.microsoft.com/office/dev-program) where you can receive an Office 365 subscription for development (which should give you more admin control over your tenant).

**Comment by kbrandl** [comment]
@choatehall thanks for raising this issue; the article has been updated.
