### ISSUE TITLE
Formatting is off on this the Custom Functions JSON metadata page

### ISSUE THREAD

**Issue by keyur32** [OfficeDev/office-js-docs-pr#2222]
Formatting is off on this the Custom Functions JSON metadata page. Scroll to bottom and everything seems like one big hyperlink. Markdown issue?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be178996-8552-f246-7adf-58cecb58a0f9
* Version Independent ID: cfe4f29e-87ea-6332-8e17-e858392c1961
* Content: [Autogenerate JSON metadata for custom functions - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-json-autogeneration)
* Content Source: [docs/excel/custom-functions-json-autogeneration.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/custom-functions-json-autogeneration.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@keyur32 Thanks for letting us know about this. We'll take a look.

Thanks.
