### ISSUE TITLE
Invocation Parameter address code sample improvement suggestion

### ISSUE THREAD

**Issue by keyur32** [OfficeDev/office-js-docs-pr#2223]
The parameter address / invocation sample doesn't seem super useful.  I was hoping to use it to provide an example of the caller.address (I think we had one), but it doesn't exist.

Currently we're not showing what you could do in the snippet. Suggest that we show an example function that users the @requiresAddress parameter, and returns the invocation.address back to as a return value (vs the generic 1+2)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17035fc0-ca69-03f2-fe37-8189ff870cc7
* Version Independent ID: 2d43e719-043b-7a62-04bb-66b2cce7bf1d
* Content: [Options for Excel custom functions - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-parameter-options?tabs=javascript)
* Content Source: [docs/excel/custom-functions-parameter-options.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/custom-functions-parameter-options.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by alison-mk** [comment]
Confirmed with @keyur32 that this issue was resolved in PR #2352, so closing this ticket.
