### ISSUE TITLE
[!Note] appears in plain text

### ISSUE THREAD

**Issue by keyur32** [OfficeDev/office-js-docs-pr#2224]
Some invalid markdown on this page below

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db285f50-5770-e426-47f6-a9f78536cab3
* Version Independent ID: 55778f17-2bdd-898b-41fc-e3f4e5517197
* Content: [Runtime for UI-less Excel custom functions - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-runtime)
* Content Source: [docs/excel/custom-functions-runtime.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/custom-functions-runtime.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@keyur32 Thanks for pointing this out. We'll take a look.

Thanks.
