### ISSUE TITLE
Custom Functions / Call Office.js article should be more specific on pattern 

### ISSUE THREAD

**Issue by keyur32** [OfficeDev/office-js-docs-pr#2225]
## Article URL
https://docs.microsoft.com/en-us/office/dev/add-ins/excel/call-excel-apis-from-custom-function

## Issue
The article is correct in that we should not write to the grid, but there are a set of scenarios and a pattern folks can follow here that I think would be worth calling out.

By using the 'onCalculate' event, combined with the invocation.address property, developers can perform write operations for different formating and spill options

**Comment by mscharlock** [comment]
An fyi to @alison-mk - I believe a previous version of the params article has some copy on invocation.address that might be helpful on this.

**Comment by alison-mk** [comment]
Closing this issue as it is tracked internally. [Internal work item link](https://office.visualstudio.com/OC/_workitems/edit/4106715/).
