### ISSUE TITLE
npm run build error and solution

### ISSUE THREAD

**Issue by mehmetkaradeniz** [OfficeDev/office-js-docs-pr#2234]
In [this](https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/outlook-tutorial#update-webpack-config-settings) section on step 4 "npm run build" command might give this error depending on the webpack version user have installed.
![image](https://user-images.githubusercontent.com/24903574/94561028-22e3a580-026c-11eb-93a1-1a30f14eca6e.png)

In this case applying the solution [here](https://stackoverflow.com/a/62680933/6671523) solves the issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a59958d2-f428-9ca2-3440-a5af662386c0
* Version Independent ID: dcaf0b5b-08ea-c437-130b-342a1be62a16
* Content: [Tutorial: Build a message compose Outlook add-in - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/outlook-tutorial)
* Content Source: [docs/tutorials/outlook-tutorial.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/tutorials/outlook-tutorial.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
Looks like this issue should be resolved with the fixing of issue https://github.com/OfficeDev/office-js-docs-pr/issues/2179 so closing.

@mehmetkaradeniz Let us know if that's not the case and we can reopen this issue.

Thanks.
