### ISSUE TITLE
Is an Empty VersionOverrides1_0  acceptable?

### ISSUE THREAD

**Issue by glr0221** [OfficeDev/office-js-docs-pr#2236]
This document talks about the VersionOverrides element. However in the scheme of things, even before VersionOverrides1_0 is defined in the manifest, a default mode of operation/behavior is already defined. Something like this : 

```
  ...
  <Hosts>
    <Host Name="Mailbox" />
  </Hosts>
  <Requirements>
    <Sets>
      <Set Name="MailBox" MinVersion="1.1" />
    </Sets>
  </Requirements>
  <FormSettings>
    <Form xsi:type="ItemRead">
      <DesktopSettings>
        <SourceLocation DefaultValue="..."/>
        <RequestedHeight>250</RequestedHeight>
      </DesktopSettings>
    </Form>
  </FormSettings>
  <Permissions>ReadWriteMailbox</Permissions>
  <Rule xsi:type="RuleCollection" Mode="Or">
    <Rule xsi:type="ItemIs" ItemType="Message" FormType="Read" />
  </Rule>
  ...

  <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides" xsi:type="VersionOverridesV1_0">
    ....
    <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides/1.1" xsi:type="VersionOverridesV1_1">
      ....
```

So in effect, we do have three modes of operation correct? 1_1, 1_0 and the default operation. So in my understanding if the "Requirements" are not met. for overrides 1_1 and 1_0, overrides will never be used and the default operation will be used. In this light, and in consideration of the manifest snippet below, I would like to ask 2 things : 

```
  ....
  <Hosts>
    <Host Name="Mailbox" />
  </Hosts>
  <Requirements>
    <Sets>
      <Set Name="MailBox" MinVersion="1.1" />
    </Sets>
  </Requirements>
  <FormSettings>
    <Form xsi:type="ItemRead">
      <DesktopSettings>
        <SourceLocation DefaultValue="..."/>
        <RequestedHeight>250</RequestedHeight>
      </DesktopSettings>
    </Form>
  </FormSettings>
  <Permissions>ReadWriteMailbox</Permissions>
  <Rule xsi:type="RuleCollection" Mode="Or">
    <Rule xsi:type="ItemIs" ItemType="Message" FormType="Read" />
  </Rule>
  <DisableEntityHighlighting>false</DisableEntityHighlighting>

  <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides" xsi:type="VersionOverridesV1_0">
    <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides/1.1" xsi:type="VersionOverridesV1_1">
      <Requirements>
        <bt:Sets DefaultMinVersion="1.5">
          <bt:Set Name="Mailbox" />
        </bt:Sets>
      </Requirements>
   ....
```

1. Making VersionOverrides1_0 empty, will force environment that do not support mailbox version 1.5 to use the default mode of operation. Correct? The drop-down list box type of UI. 
2. And corollary to that, manifests with empty VersionOverrides1_0 (intentionally done), are perfectly valid manifests right?

Thank you very much.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9caa983-63bf-9ec7-6885-acc576f18747
* Version Independent ID: b7f72393-be3e-3237-7b2c-b43dc26a2061
* Content: [VersionOverrides element in the manifest file - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/versionoverrides)
* Content Source: [docs/reference/manifest/versionoverrides.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/manifest/versionoverrides.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@glr0221 Thanks for asking about this.

@Rick-Kirkham Can you take a look and direct as appropriate?

Thanks.

**Comment by glr0221** [comment]
@JuaneloJuanelo any updates on this? thank you so very much!

**Comment by glr0221** [comment]
@JuaneloJuanelo any updates for this item? thanks again.

**Comment by glr0221** [comment]
@ElizabethSamuel-MSFT 

Seems like @JuaneloJuanelo may not have the time to answer my inquiry. Any chance somebody else can take my question on? Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@glr0221 Apologies for the wait. We're checking for an appropriate person who can look into this issue. Thx.

**Comment by glr0221** [comment]
@ElizabethSamuel-MSFT thank you always for your support. This inquiry is a bit critical for us, that is why there is some sense of urgency. Thank you very much for understanding.

**Comment by ElizabethSamuel-MSFT** [comment]
@glr0221 Understood. Working on getting you the help you need.

@exextoc Is this something you can help with? Can you take a look?

Thanks.

**Comment by exextoc** [comment]
1. That is correct. From our documentation regarding support of [requirement sets on clients](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/outlook-api-requirement-sets), the only clients that do not support 1.5 is 2016 one-time purchase and 2013 one time purchase (MSI versions). Are you trying your target for the addin to only the clients that use those builds of Outlook? 1.5 will be supported for other clients, say MAC and Browser.
2. Yes, an empty versionOverrides1_0 is totally valid.

**Comment by glr0221** [comment]
Thank you @exextoc ... you saved me a lot of trouble.

Yes you are correct. I am trying to custom our manifests based on supported mailbox versions. Thank you so very much. 

@ElizabethSamuel-MSFT Thank you and I am closing this ticket.
