### ISSUE TITLE
Excel online add-in deploy only to thin client - Configuration 

### ISSUE THREAD

**Issue by ramnaresh** [OfficeDev/office-js-docs-pr#2239]
Hello,  Is there any configuration in central deployment or in the manifest to target the excel add-in appears only for thin client (excel online), not for the desktop excel ?

Thank you!

**Comment by ElizabethSamuel-MSFT** [comment]
@ramnaresh Thanks for your question. I believe that's not available right now. You likely need to use the [DesktopFormFactor](https://docs.microsoft.com/office/dev/add-ins/reference/manifest/desktopformfactor) which configures online, Windows, and Mac all together.

If that is a feature you'd like to see, please upvote or create a feature in [UserVoice](https://officespdev.uservoice.com/). Our product teams take these into consideration when they're planning.

I'll close this now but if you have any further questions, let us know.

Thanks.
