### ISSUE TITLE
Missing item

### ISSUE THREAD

**Issue by skycommand** [OfficeDev/office-js-docs-pr#224]
So, to sum it up, Office Add-ins are unavailable for perpetually licensed copies of Office 2016 and earlier, and are unavailable for the mentioned OneNote apps, regardless of the licensing scheme. But one app is missing: The UWP version of the OneNote app, once included with Windows 10.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7c255e4-d0f9-5b35-bec0-fdd690bdeff1
* Version Independent ID: dae8b049-0f53-ea13-9998-cfb4362b7553
* Content: [Office Add-in host and platform availability](https://docs.microsoft.com/en-us/office/dev/add-ins/overview/office-add-in-availability#onenote)
* Content Source: [docs/overview/office-add-in-availability.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/overview/office-add-in-availability.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @skycommand,
The UWP version of OneNote is not listed in the platform availability section because it is not supported. Office Add-ins for OneNote are only supported on Office Online.
I'll close this issue since the documentation is correct. Please reopen it if I've misinterpreted your concerns.

**Comment by skycommand** [comment]
@AlexJerabek Hello. Thanks for attending. Unfortunately, I must say that you indeed misinterpreted my concern. I think it is urgent that this case is reopened. Let me see if I can make it clear.

Assuming that your sentence ("The UWP version of OneNote [...] is not supported") is correct, it is the job of the document in question to tell me this, not you. In other words, a document called "Office Add-in host and platform availability" (this document which we are discussing) is the first and the legitimate choice of customer who wishes to have an answer to the question of "Is the UWP version of OneNote a supported host for Office Add-ins?"

If this document does not answer said question, it brings about a problem very similar to [Warnock's dilemma](https://en.wikipedia.org/wiki/Warnock%27s_dilemma).

**Comment by AlexJerabek** [comment]
Hi @skycommand,

Just to be clear, the concern is the documentation only lists what **is** supported, not what **isn't** supported. Is that correct?

The intention of the document is to list a positive set of supported hosts and platforms (from the opening paragraph: "The following tables contain the available platform, extension points, API requirement sets, and common API requirement sets that are currently supported for each Office application.")  We chose to list the set of supported hosts and platforms for several reasons.

Having the list this way makes it smaller and easier to search. If we had both supported and not supported, customers using a browser search bar 'ctrl+f' might jump between sections without seeing the supported-unsupported header. 

Relatedly, we're optimizing for search engine queries with the supported platforms. If a customer wants to make an add-in for Excel Online, they should arrive at our documentation. However, if they are making something targeting UWP, having them arrive at a page with that term might be misleading (the "not supported" line would probably be clipped for the text displyed in the search result).

I think the relevant analogy would be an ingredient list on food packaging. If I'm allergic to peanuts, I need to know if the granola bar I'm buying has peanuts. I'll read the package and scan for that word. If I see it, I'm done; back on the shelf it goes. I wouldn't expect a full list of ingredients not in the granola bar.

Now, if you'd like us to support UWP with Office Add-ins, please visit [UserVoice](https://officespdev.uservoice.com/) and either request the feature or upvote and existing request.

Thanks!

**Comment by skycommand** [comment]
@AlexJerabek 

1. When the article says "The following tables contain the available platform...", that's what I would expect. OneNote Desktop and OneNote UWP are two examples of available platforms. If you omit them from a table that claims to list available platforms, the reader does not take the omission to mean lack of support. In programming parlance, `$null -ne $false`. (Null is not equal to false.) You can replace "available" with "supporting" and the problem is solved.
2. Are you sure OneNote UWP does **not** support Office Add-ins? If yes, how do you explain this: [Gem Menu for Windows 10 OneNote (UWP) 4.0.0.9](https://www.onenotegem.com/gem-menu-for-onenote-uwp.html)

Also, I find it disturbing that you compare software development for a Microsoft platform with a potentially deadly allergy to peanuts that one must avoid! And since I don't avoid software development the way I avoid food hazard, it is quite clear that I don't go about doing it they way you go about buy granola bars.

**Comment by Rick-Kirkham** [comment]
I'm locking this conversation. For anyone reading this, please note that although the Gem tool calls itself an "add-in", it is not an "add-in" in the sense of Office Web Add-ins, which is the what this article is about.
