### ISSUE TITLE
Why doesn't Windows 10's File Explorer use these monoline icons?

### ISSUE THREAD

**Issue by Poopooracoocoo** [OfficeDev/office-js-docs-pr#2242]
Why doesn't Windows 10's File Explorer use these monoline icons?

in b4
>uSE THe FEEdBaCK HUB
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 476d0e20-d8e8-4d38-ac46-39a117adcd02
* Version Independent ID: b68f0dee-0635-ecfe-c5a1-1fae4c6406a1
* Content: [Monoline style icon guidelines for Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/design/add-in-icons-monoline)
* Content Source: [docs/design/add-in-icons-monoline.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/design/add-in-icons-monoline.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
The monoline style was developed for Microsoft 365. It is not used across all Microsoft products, such as the Windows File Explorer. Please check with Windows Help to see if they have any information about the icon style used by File Explorer.
