### ISSUE TITLE
Question regarding a phrase in the documentation

### ISSUE THREAD

**Issue by CypherX** [OfficeDev/office-js-docs-pr#2243]
## Article URL
https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/privacy-and-security

## Issue
Apologies if this is the wrong place to ask this. In the "Add-in integrity in AppSource" section of the article at the above link is the line:

- Ensures that the source of add-ins is accessible in read-only mode.

I'm having trouble understanding what this requirement means. Is it referring to the source code of the add-in being open source? It would be great if someone could elaborate on this.

Thanks!

**Comment by ElizabethSamuel-MSFT** [comment]
@mikeald Can you help clarify this statement?

I can update the documentation after that if needed.

Thanks.
