### ISSUE TITLE
webserver started and created a cert.  I deleted them and it recreated them in ~/.office_addin_dev_certs.  Even so, I keep getting unsigned cert error in both local excel and web excel.  That doesn't appear to be addressed anywhere.

### ISSUE THREAD

**Issue by eskoviak** [OfficeDev/office-js-docs-pr#2244]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c4ddde7-f1fd-44ba-fba1-0ae9d0131df7
* Version Independent ID: d946ffe6-f29f-1563-b679-121090ba60a1
* Content: [Build your first Excel task pane add-in - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-jquery?tabs=yeomangenerator)
* Content Source: [docs/quickstarts/excel-quickstart-jquery.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/quickstarts/excel-quickstart-jquery.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
@eskoviak Please rewrite your issue so that the details are in the text, not the title. It appears that only the last part of the problem description is here.
