### ISSUE TITLE
Get the subtitiles of the selected slides

### ISSUE THREAD

**Issue by Sam2243** [OfficeDev/office-js-docs-pr#225]
* There is no information available in the docs that's y I am posting a technical question here *

Hi,

I am making an add-in for powerpoint and one of the use case is a user selects a slide or multiple slides and I want to extract the text of the selected slides. I am using the following code but I just get the title, id and index information of the slide and not the subtitles. Can anyone please help me? :) here's the code. 

```
 Office.context.document.getSelectedDataAsync(Office.CoercionType.SlideRange, function (asyncResult) {
            if (asyncResult.status == "failed") {
                console.log("Action failed with error: " + asyncResult.error.message);
            }
            else {
                console.log(asyncResult.value.slides[0]); // This just returns an object with information (id, index and title)
            } 
        });
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 207b73ed-7aeb-0cf3-34f8-9644af986017
* Version Independent ID: cdac769b-ee13-4d6a-118d-e52fc28d5e0d
* Content: [PowerPoint add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/powerpoint/powerpoint-add-ins#feedback)
* Content Source: [docs/powerpoint/powerpoint-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/powerpoint/powerpoint-add-ins.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by keyur32** [comment]
Hi there, thanks for the issue.

I don't think this capability exists in the API, please enter the request on user voice @ https://officespdev.uservoice.com.  Right now the PowerPoint functionality is limited to a few scenarios (inserting images or displaying dynamic text), and we're watching votes from the community to understand what scenarios we should invest in, when we do visit PowerPoint support.

thanks

**Comment by keyur32** [comment]
also to clarify above, while the API exists, it doesn't support subtitles yet
