### ISSUE TITLE
when i authorise an App addin am i approving the app or just a specific version?

### ISSUE THREAD

**Issue by bakerels** [OfficeDev/office-js-docs-pr#2254]
[Enter feedback here]

If I authorise an app to specific group of users - am i authorising the app as a whole or a specific version.
thus does each app version need approval or is the app ever green.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41508035-2045-1706-9917-cd2da1e99cc7
* Version Independent ID: ea51ce32-18e2-68ed-ddc5-74f0d3d8a3d1
* Content: [Publish Office Add-ins using Centralized Deployment via the Microsoft 365 admin center - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/publish/centralized-deployment)
* Content Source: [docs/publish/centralized-deployment.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/publish/centralized-deployment.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
It depends on what you mean by "version". You can change the files hosted in the server side, without changing the manifest. The manifest and Office don't know about that kind of version change, so the original approval still applies. However, if by version change, you mean a changed manifest, then that new manifest would have to be deployed and reapproved. Does this answer the question?
