### ISSUE TITLE
Limitations of working with multiple ranges

### ISSUE THREAD

**Issue by jwhite-venacorp** [OfficeDev/office-js-docs-pr#2255]
Could we have some additional details about what the limitations of working with multiple ranges are? I've noticed that some of the longer comma-delimited address strings I pass to `Worksheet.getRangeAreas()` fail, while others with the same argument length or same/greater number of addresses within the string will pass. It would be helpful to know what address strings will work and when they will start failing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec11ff3f-a9d7-1042-9dd9-b865c14a4980
* Version Independent ID: dade8e53-60c4-0da1-c8a4-a52bb61fd968
* Content: [Work with multiple ranges simultaneously in Excel add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-multiple-ranges)
* Content Source: [docs/excel/excel-add-ins-multiple-ranges.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/excel-add-ins-multiple-ranges.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by alison-mk** [comment]
Hi @jwhite-venacorp, sorry for the delay, and thank you for taking the time to submit this issue. The issue you describe may be a bug. Can you provide the code you're using, so I can reproduce it? A copy of 2-3 address strings that fail, and 1 or more that do not fail would be very helpful. If you can provide code as a link to a Github gist that works in Script Lab, that will help me continue researching the issue most quickly. If you're unfamiliar with that process, you can also respond to this issue with the strings pasted into the body of your comment.

Thanks again, 
Alison

**Comment by jwhite-venacorp** [comment]
Hi @alison-mk, I made a [ScriptLab gist](https://gist.github.com/jwhite-venacorp/fb6209d18fb3b5124acfc110624ddcbc). This code creates 152 named ranges, then uses the names to get the values. When all the names are passed, an exception is thrown. When either half of the names are passed, the values are returned. I pulled the named ranges' addresses from an actual file we were testing with and randomized the names so they are the same number of characters. On our actual file, there are data in these ranges, but the test fails when the file is completely empty.

**Comment by keyur32** [comment]
Assigning to @lumine2008 to help investigate. Thanks.

**Comment by lumine2008** [comment]
Thanks @jwhite-venacorp for reporting this issue, Yes, there is a limitation for getRange() and getRanges() API, the limitation is 8192 characters. I am asking the content team to document this limitation. therefore you could refer to our document in the future.

**Comment by alison-mk** [comment]
As of PR #2355, the character limit is now documented. Closing this issue. Thanks again for taking the time to submit the issue, @jwhite-venacorp!
