### ISSUE TITLE
On-send for The new Outlook

### ISSUE THREAD

**Issue by moshikonachmias** [OfficeDev/office-js-docs-pr#2258]
## Article URL
https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/outlook-on-send-addins

## Issue
Hello, I'm trying to understand if the on-send add-in is supported in the new outlook for mac.
According to both articles, I can not find any reference to this.
https://support.microsoft.com/en-us/office/the-new-outlook-for-mac-6283be54-e74d-434e-babb-b70cefc77439 
https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/outlook-on-send-addins

I hope to get a better understanding of that issue.
Thank you

**Comment by ElizabethSamuel-MSFT** [comment]
@moshikonachmias Thanks for your question. The on-send feature is not supported on the new Mac UI yet (see the section [New Outlook on Mac](https://docs.microsoft.com/office/dev/add-ins/outlook/compare-outlook-add-in-support-in-outlook-for-mac#new-outlook-on-mac-preview)). As we add support, we'll continue updating this section.

I'll go ahead and close this issue. However, if you have any further questions or comments, let us know.

Thanks.
