### ISSUE TITLE
Outlook Issue

### ISSUE THREAD

**Issue by scottyak12** [OfficeDev/office-js-docs-pr#2260]
Trying to create an Outlook SSO add-in based on this. The article says after running yo office prompts, to run "npm run dev-server", but this command does not get added to package.json by the CLI tool. I added manually ("dev-server" : "webpack-dev-server --mode development"), and while this works and I am able to see the add-in when composing a new email, I get "Add-In Error: We can't open this add-in from localhost".

Any ideas?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3020ff5d-ee3b-976b-f1ad-0ed378fdb47b
* Version Independent ID: 5de0010a-6435-154b-a7fd-fd2ea05ebc0b
* Content: [Use the Yeoman generator to create an Office Add-in that uses SSO - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/sso-quickstart)
* Content Source: [docs/quickstarts/sso-quickstart.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/quickstarts/sso-quickstart.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@scottyak12 Thanks for asking about this.

@davidchesnut @Rick-Kirkham Can you help with this issue?

Thanks.

**Comment by Rick-Kirkham** [comment]
If there's no `dev-server` command in the package.json, then this is likely a bug in the Yo Office tool.

**Comment by TCourtneyOwen** [comment]
This must be a documentation error. The Yo Office tells the correct steps to perform after creating the project. This is the yo office output:

      1. Go the directory where your project was created:

         cd C:\foo

      2. Configure your SSO taskpane add-in:

         npm run configure-sso

      3. Start the local web server and sideload the add-in:

         npm start

      4. Open the project in VS Code:

         code .

         For more information, visit http://code.visualstudio.com.

      Please visit https://docs.microsoft.com/office/dev/add-ins for more information about Office Add-ins.

What is the documentation the user is referring to?

**Comment by ElizabethSamuel-MSFT** [comment]
@TCourtneyOwen The user is referring to the SSO quick start page and I'm supposing using the Outlook steps in the **Try it out** section:
https://docs.microsoft.com/office/dev/add-ins/quickstarts/sso-quickstart#outlook

As I understand, for Outlook `npm start` is not recommended and `npm run dev-server` should be used instead, which is what the docs show.

**Comment by scottyak12** [comment]
@ElizabethSamuel-MSFT Yes, that's correct, I'm attempting to follow the Outlook specific instructions, which say to use npm run dev-server, rather than npm start, but the yo office CLI output does not include a npm run dev-server script in the package.json. I was able to successfully follow the steps for an Excel add-in, but something must be missing for the Outlook version. Any advice would be appreciated, thanks for taking a look!

**Comment by scottyak12** [comment]
@TCourtneyOwen @ElizabethSamuel-MSFT 

Hi Team, anything further here? Thanks!

**Comment by TCourtneyOwen** [comment]
Please use these steps:

  1. Go the directory where your project was created:

     cd C:\foo

  2. Configure your SSO taskpane add-in:

     npm run configure-sso

  3. Start the local web server and sideload the add-in:

     **npm start**

  4. Open the project in VS Code:

     code .

     For more information, visit http://code.visualstudio.com.

  Please visit https://docs.microsoft.com/office/dev/add-ins for more information about Office Add-ins.

The tutorial is incorrect and need to be updated.

-Courtney

**Comment by ElizabethSamuel-MSFT** [comment]
@scottyak12 Did @TCourtneyOwen's steps help you resolve your issue?

We'll work on updating the tutorial instructions.

Thanks.
