### ISSUE TITLE
When "Let users access the Office Store is disabled" sideload is prevented

### ISSUE THREAD

**Issue by bakerm00** [OfficeDev/office-js-docs-pr#2261]
please make clear in documentation 
When "Let users access the Office Store" is disabled;   developers report that sideload is prevented

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ddce0bd-5c66-c2cb-0640-ee4d5bd401c5
* Version Independent ID: b5d4bc26-a43e-4a85-e7d5-fe4fc4ec3d0d
* Content: [Sideload Office Add-ins for testing from a network share - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins)
* Content Source: [docs/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@bakerm00 Thanks for asking about this.

@mscharlock Can you help with this?

Thanks.

**Comment by mscharlock** [comment]
@ElizabethSamuel-MSFT let me check that this is expected and then will doc. Thanks!

**Comment by bakerm00** [comment]
Any update on this ?

Mike Baker

________________________________

**Comment by mscharlock** [comment]
Thanks for your patience. I heard back from a PM on the expected behavior. Apparently, sideloading may be disabled by the Trust Center or via a group policy, but disabling the store doesn’t explicitly disable sideloading from a network share. Let me know if this helps - I can get more details to clarify if you need. :)
