### ISSUE TITLE
Broken Table (ja-jp)

### ISSUE THREAD

**Issue by hyoshioka0128** [OfficeDev/office-js-docs-pr#2262]
・ja-jp: https://docs.microsoft.com/ja-jp/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins
![browsers-used-by-office-web-add-ins_j](https://user-images.githubusercontent.com/40815708/95736235-eaf34e00-0cc0-11eb-9670-e22decdc3fd8.png)

・en-us:https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins
![browsers-used-by-office-web-add-ins_e](https://user-images.githubusercontent.com/40815708/95736242-ee86d500-0cc0-11eb-8e0f-8aa8d3e16f90.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00c430f1-bbf5-53b8-a225-4fbe8fc39c3b
* Version Independent ID: 0a069a0d-4d35-71ee-53af-8c55fe8548a0
* Content: [Browsers used by Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins)
* Content Source: [docs/concepts/browsers-used-by-office-web-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/concepts/browsers-used-by-office-web-add-ins.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thank you for reporting this @hyoshioka0128. I'll pass this along to our localization team and see if we can get this fixed soon.

**Comment by Rick-Kirkham** [comment]
@AlexJerabek The upper left most cell of the table also looks like it has been mistranslated. The English has "OS" (short for operating system), but the Japanese has "HP-UX".

**Comment by AlexJerabek** [comment]
Hi @hyoshioka0128, 
Our localization team will investigate and fix the issue soon. In the meantime, are you able to get the necessary information from the "en-us" table?

_Internal tracking [here](https://dev.azure.com/GlobalCollaborationService/Global%20Collaboration%20Service%20Project/_workitems/edit/44647)_

**Comment by hyoshioka0128** [comment]
Q(@AlexJerabek)   ＜Are you able to get the necessary information from the "en-us" table?＞
A(@hyoshioka0128)  None. Thanks.

**Comment by AlexJerabek** [comment]
The table appears to be properly rendered for the "ja-jp" version.  @hyoshioka0128, can you please confirm that everything looks as expected? Thank you.

**Comment by AlexJerabek** [comment]
Also, since the issue appears to be fixed, I'll close the issue. Please comment on the thread if that is not the case. Thanks!
