### ISSUE TITLE
Needs update of npm code (deprecated)

### ISSUE THREAD

**Issue by Geradav** [OfficeDev/office-js-docs-pr#2269]
Hello,

Please update that page as the npm request code is deprecated.
See https://github.com/request/request/issues/3142

Thanks

David

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a30fb645-c853-a93a-4137-1e2bf7398a11
* Version Independent ID: 75fb99ac-72e8-7bdc-ff1b-85e7ed930d50
* Content: [Excel custom functions tutorial - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/excel-tutorial-create-custom-functions?tabs=excel-windows)
* Content Source: [docs/tutorials/excel-tutorial-create-custom-functions.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/tutorials/excel-tutorial-create-custom-functions.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@Geradav Thanks for pointing out this issue. However, can you clarify where this `request` module is being used by this tutorial?

Thanks.
