### ISSUE TITLE
Updated UI doesn't reflect in the documentation.

### ISSUE THREAD

**Issue by julio177** [OfficeDev/office-js-docs-pr#2275]
[Enter feedback here]
Step 9.
Admin consent title and User consent title have changed to be Admin consent display name and equivalent.

Step 13.
There is no longer a dropdown.
Instructions are also missing click on "Add platform".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79094327-e4d3-da9a-e152-18408c0ffde2
* Version Independent ID: 120ecfb2-3d09-21bf-211e-e1e89050b52c
* Content: [Register an Office Add-in that uses SSO with the Azure AD v2.0 endpoint - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/register-sso-add-in-aad-v2)
* Content Source: [docs/develop/register-sso-add-in-aad-v2.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/register-sso-add-in-aad-v2.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks @julio177.

@davidchesnut, can you please investigate this and adjust the docs as needed?

**Comment by davidchesnut** [comment]
Thanks @julio177!

I submitted PR #2378 to fix this.
