### ISSUE TITLE
Manifests targeting ExcelApi > 1.1 still attempt to support Excel for Mac 2016

### ISSUE THREAD

**Issue by chucklay** [OfficeDev/office-js-docs-pr#2287]
Hi, under the "Excel / Office 2016 on Mac (one-time purchase)" section of this page, it's indicated that Excel for Mac 2016 only supports ExcelApi 1.1. I'm currently working on an add-in that requires features from ExcelApi 1.8. Despite changing my manifest to list ExcelApi 1.8 as the minimum version, `npm run validate`, as well as the Partner Center submission page still lists Excel for Mac 2016 as a valid target. **This is a blocker issue for us as it's preventing us from submitting our add-in, as it's being tested on Excel for Mac 2016 and failing validation.** 

For context, this is the `Requirements` section of my manifest:
```
  <Requirements>
    <Sets DefaultMinVersion="1.1">
      <Set Name="CustomFunctionsRuntime" MinVersion="1.1"/>
      <Set Name="ExcelApi" MinVersion="1.8"/>
    </Sets>
  </Requirements>
```

I'm not sure if the problem lies in the documentation or if this is an actual bug with manifest validation, but in the short term, I'm REALLY in need of a way to indicate that this add-in does not support Excel for Mac 2016.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7c255e4-d0f9-5b35-bec0-fdd690bdeff1
* Version Independent ID: dae8b049-0f53-ea13-9998-cfb4362b7553
* Content: [Office client application and platform availability for Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/overview/office-add-in-availability)
* Content Source: [docs/overview/office-add-in-availability.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/overview/office-add-in-availability.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for reporting this @chucklay. 

I'll look into the actual API surface that's supported for Excel for Mac 2016 and report back to you.

**Comment by jeremy-msft** [comment]
This is a known issue with our version strings; please see additional details in https://github.com/OfficeDev/Office-Addin-Scripts/issues/332.

**Comment by AlexJerabek** [comment]
Thanks @jeremy-msft. 

@chucklay, we'll continue to track the issue in https://github.com/OfficeDev/Office-Addin-Scripts/issues/332. I'll close this issue, since this repo is for tracking documentation issues. If anything further is needed in the documentation, please reply back to this thread. Thanks!
