### ISSUE TITLE
It seams ios also support,please update the support platform and add the support version(such as, system version and outlook version)

### ISSUE THREAD

**Issue by hello-chenchen** [OfficeDev/office-js-docs-pr#2303]
[Enter feedback here]
i found ios > 14.1 and outlook > 4.61.1, have support this feature.

and another question: i want to confirm is ios 14.0.1 support this feature? after my test, it seams not support, right?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52a55fe4-0fe1-858c-26a4-dddc3ee128ea
* Version Independent ID: 0a643291-936f-b374-37fd-7db497c73cce
* Content: [Create an Outlook mobile add-in for an online-meeting provider - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/online-meeting)
* Content Source: [docs/outlook/online-meeting.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/outlook/online-meeting.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@hello-chenchen Thanks for your query. However, can you clarify which feature you're referring to?

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@hello-chenchen Also, can you include the documentation page that you think should be updated?

Thanks.

**Comment by hello-chenchen** [comment]
@ElizabethSamuel-MSFT , right now, outlook ios latest version have support this feature, so it should be update for have support ios, not only android. and i hope there is a table for which min version they are supported this feature.

**Comment by ElizabethSamuel-MSFT** [comment]
@hello-chenchen Thanks for your response. However, you talk about "this feature" but can you let us know which feature?

Thanks.

**Comment by hello-chenchen** [comment]
@ElizabethSamuel-MSFT ,sorry it seams i delete the most important thing when report this issue.
this feature.
https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/online-meeting

**Comment by ElizabethSamuel-MSFT** [comment]
@hello-chenchen Thanks for the update. We are working on supporting this feature so it may be available but not officially supported yet. I'll check with the feature crew for the status on iOS then update this thread and the documentation as applicable.

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@hello-chenchen I checked with the team and we are in the process of rolling out the feature for iOS. Once that process is complete, we'll update the documentation accordingly with supported build info and other details as needed. Unfortunately, I don't have an ETA at this time for when that will be. I'll go ahead and close this but if you have any further questions, let us know and we can reopen it.

Also, we welcome your feedback on the feature so feel free to let us know how it's working for you.

Thanks.
