### ISSUE TITLE
Description for options.requiresAddress seems outdated

### ISSUE THREAD

**Issue by sshukurov** [OfficeDev/office-js-docs-pr#2306]
It reads "To get the address of the cell that invoked your custom function, use context.address in your custom function.", but no `context` object is available in the global scope in the custom functions runtime.

I was able to access the `address` property by defining an additional parameter in my custom function, which according to my finding by debugging - should be placed at the end of the function parameter list. The type of parameter is `CustomFunctions.Invocation`.

An code sample or a link to a working solution would be brilliant.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc9afc49-47bc-c0b4-249f-5c66a9421747
* Version Independent ID: ae89f268-e83d-1a08-babe-3f1c3dc11796
* Content: [Create JSON metadata for custom functions in Excel - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-json)
* Content Source: [docs/excel/custom-functions-json.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/custom-functions-json.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for the feedback @sshukurov. 

@alison-mk, could you please take a look at this? Thanks!

**Comment by alison-mk** [comment]
Hi @sshukurov, thanks again for this feedback. I'm working on an update to this article, and I will definitely incorporate your suggestion. Are you blocked, or have you found a solution that allows you to continue working? If you're blocked, can you provide the code sample you're working with (either directly in a comment, or via a link to a Github gist)? I'll be happy to help out here in the interim, before the article update is complete.

**Comment by sshukurov** [comment]
Hi @alison-mk, thank you for your response. I'm not blocked, I've already figured out how to get the address property as I wrote above.

**Comment by alison-mk** [comment]
Closing this issue as the clarifications and suggestions recommended by @sshukurov have been incorporated into the [Manually create JSON metadata for custom functions](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-json#options) and [Custom functions parameter options](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-parameter-options?tabs=javascript#invocation-parameter) articles. Thank you for taking the time to submit feedback!
