### ISSUE TITLE
I can't sideload outlook addins for desktop, on office 365

### ISSUE THREAD

**Issue by jfoclpf** [OfficeDev/office-js-docs-pr#2307]
I can't sideload outlook addins for desktop, on office 365

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ddce0bd-5c66-c2cb-0640-ee4d5bd401c5
* Version Independent ID: b5d4bc26-a43e-4a85-e7d5-fe4fc4ec3d0d
* Content: [Sideload Office Add-ins for testing from a network share - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins)
* Content Source: [docs/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @jfoclpf,
Thanks for reporting this. Can you please share where the process is failing?  Are you able to see your add-in in the "My Add-ins" list? Is the add-in showing an error in the task pane? Any details and screenshots would be appreicated.

**Comment by jfoclpf** [comment]
hi @AlexJerabek 
When I open Outlook 365 for desktop, I get this greyed out

![image](https://user-images.githubusercontent.com/3984909/98291767-f11cd780-1fab-11eb-9c75-b4c875673b56.png)

The "Enable Optional Connected Experience" option was already selected, but still (after restarting again Outlook) the Get Addin button is greyed out.

![image](https://user-images.githubusercontent.com/3984909/98291810-04c83e00-1fac-11eb-815e-bb56dffb6f21.png)

I can sideload the `manifest.xml` on Word, but on Outlook I really can't and I don't know why

**Comment by AlexJerabek** [comment]
Thank you @jfoclpf. 

@ElizabethSamuel-MSFT, could you please continue the investigation?

**Comment by ElizabethSamuel-MSFT** [comment]
@exextoc Can you take a look? Thx.

**Comment by exextoc** [comment]
Could you share the Outlook build number you are testing this on? Also, after booting outlook, select an email so the email shows up in the reading pane, then in the Home tab on the ribbon do you see the Get Add-ins button? Is this enbaled/disabled? Sharing a screenshot of this scenario will help us. Also, it's worth trying a couple of emails in the inbox to confirm if the Get Add-inss button on the Home tab of the ribbon is enabled or not

**Comment by jfoclpf** [comment]
@exextoc thanks for your reply
> Could you share the Outlook build number you are testing this on? 

![image](https://user-images.githubusercontent.com/3984909/98661115-5d019600-2346-11eb-84c5-77a9b80cb740.png)
![image](https://user-images.githubusercontent.com/3984909/98661212-77d40a80-2346-11eb-9649-80b3a187d587.png)


> Also, after booting outlook, select an email so the email shows up in the reading pane, then in the Home tab on the ribbon do you see the Get Add-ins button? Is this enbaled/disabled? Sharing a screenshot of this scenario will help us. 

The Get Add-ins button was not in the Home tab, I had to add it manually to a new tab by manually customizing the Ribbon, though it is also deactivated

![image](https://user-images.githubusercontent.com/3984909/98661339-9f2ad780-2346-11eb-99eb-4be01efc123d.png)
<br><br>
![image](https://user-images.githubusercontent.com/3984909/98661476-c71a3b00-2346-11eb-9f8d-ab8b93d3eb0b.png)


> Also, it's worth trying a couple of emails in the inbox to confirm if the Get Add-inss button on the Home tab of the ribbon is enabled or not

The previous screenshots are indeed from the Inbox

I think this might be related with the fact that the administrator of the Office (really big organization here) blocked this feature. Does this ring a bell to you?

Thanks in advance

**Comment by exextoc** [comment]
Are you able to sideload add-ins using [Outlook on the web](https://support.microsoft.com/en-gb/office/using-add-ins-in-outlook-on-the-web-8f2ce816-5df4-44a5-958c-f7f9d6dabdce)? Is the Get Add-ins button also disabled for Outlook on the web?

**Comment by jfoclpf** [comment]
> Are you able to sideload add-ins using [Outlook on the web](https://support.microsoft.com/en-gb/office/using-add-ins-in-outlook-on-the-web-8f2ce816-5df4-44a5-958c-f7f9d6dabdce)? Is the Get Add-ins button also disabled for Outlook on the web?

No, I am not.

**Comment by exextoc** [comment]
To be able to install/manage/access Outlook add-ins, the My Marketplace Apps role needs to be set for your account. Please see [this](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/add-ins-for-outlook/specify-who-can-install-and-manage-add-ins) documentation for further details.

**Comment by jfoclpf** [comment]
Thank you, I am contacting the admin but this here is a huge organisation and I need to follow the procedure. But you already pointed in the right direction, so if I understood correctly my user Role has to be within **My Custom Apps**. Is that correct @exextoc ?

Just for the correct assessment, which kind of administrator are we talking about? What is the correct denomination of the person I need to contact? Exchange administrator? Outlook administrator?

**Comment by exextoc** [comment]
Correct, you need 'My Custom Apps' role in order to be able to sideload an addin.
Just to double check that there are no other issues - is the Get Add-ins button enabled for Outlook on the web?  If it is enabled, and you have My Custom Apps role, you should be able to sideload addins from Outlook on the web, and the sideloaded addins will be available in Outlook desktop.

For the 'Get Add ins' button in desktop Outlook, depending on Exchange version, you may also need "My Marketplace Apps" role for the button to be available.

Additionally, if your addin will be using ReadWriteMailbox permissions, you will also need "My ReadWriteMailbox Apps" as well.

These roles are configured in Exchange, so I expect it will require administrator with the necessary exchange access and permissions.

**Comment by jfoclpf** [comment]
> Just to double check that there are no other issues - is the Get Add-ins button enabled for Outlook on the web?

Yes, correct, I don't see any option to sideload addins on my web platform of Office

I will contact the admin then. Thanks for the support

**Comment by ElizabethSamuel-MSFT** [comment]
@jfoclpf Thanks for the update. I'll go ahead and close this issue but if you're still facing problems even after working with your admin, you can respond on this thread or create a new issue.

Thanks.
