### ISSUE TITLE
spelling error in title

### ISSUE THREAD

**Issue by Rick-Kirkham** [OfficeDev/office-js-docs-pr#2310]
The last word of the title should be "runtime" not "runtimes"

![image](https://user-images.githubusercontent.com/9088056/98425891-b79ba900-204b-11eb-8201-88a533cc2830.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc89eff2-1c69-c80f-2cfb-43746309f2b7
* Version Independent ID: af86e11c-93ec-c0d9-bccd-cdd993fce37c
* Content: [Run your add-in code in a shared JavaScript runtime - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-shared-overview)
* Content Source: [docs/excel/custom-functions-shared-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/custom-functions-shared-overview.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@Rick-Kirkham Thanks for opening this issue.

@alison-mk Can you address?

Thanks.

**Comment by alison-mk** [comment]
@Rick-Kirkham @ElizabethSamuel-MSFT this title is fixed in [PR #2312](https://github.com/OfficeDev/office-js-docs-pr/pull/2312)! :)

**Comment by mscharlock** [comment]
Fixed!
