### ISSUE TITLE
Screenshots and description do not match actual workflow

### ISSUE THREAD

**Issue by glatzert** [OfficeDev/office-js-docs-pr#2318]
The screenshots seem not to depict the current state of outlook.

I use version "Microsoft Outlook for Microsoft 365 MSO (16.0.13328.20262) 32-Bit", which will open a web-page, when I click on the Add-In button - the webpage is: https://appsource.microsoft.com/de-de/marketplace/apps?product=office%3boutlook&page=1&src=office&corrid=44f1107b-2cdc-4c76-9769-b288c00536c8&omexanonuid=c682f60f-85c5-44fd-b0e9-cb0cad42491b&referralurl= and sideloading seems not possible from there.

How do I sideload an add-in?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f364ae0-b7dd-edb3-b51b-8f6d0d99afbe
* Version Independent ID: 7dd1ce8f-16e7-88f8-f291-4afbe76baba7
* Content: [Sideload Outlook add-ins for testing - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/sideload-outlook-add-ins-for-testing)
* Content Source: [docs/outlook/sideload-outlook-add-ins-for-testing.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/outlook/sideload-outlook-add-ins-for-testing.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@glatzert Thanks for raising this issue. Can you access Outlook on the web and try the related instructions on that same page to sideload in that client?

Let us know if that helped or if we can help further.

Thanks.

**Comment by glatzert** [comment]
Hi there,

my observations so far:
 - Outlook Desktop goes to that Store Page mentioned above, with no way of sideloading
 - outlook.com does not work for the user I tried (it's a corporate login and I seem to have no outlook license for outlook online)
 - mail.domain.com is an on-prem OWA, which has some settings regarding Add-Ins (did not have time to see, if I can load one or not)
 - outlook.com with a personal user will show the add-in button below the "new Mail"-Window (which is really an odd placement, but that's probably another UX issue).

I'll try the latter one and report back to you. Nevertheless for Outlook Desktop the Screenshots do not add up.

**Comment by ElizabethSamuel-MSFT** [comment]
@glatzert Thanks for sharing this info.

@exextoc Can you take a look?

Thanks.

**Comment by exextoc** [comment]
1. If I understand your description correctly, your Exchange account is on-premise. Is that right? 

2. In desktop Outlook, do you see a "Manage Add-ins" option in 'File', under the 'Info' tab? The "Manage Add-ins" button should open "Get-Addins" interface in OWA and the experience should be similar to "Sideload an add-in in classic Outlook on the web" in https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/sideload-outlook-add-ins-for-testing#sideload-an-add-in-in-classic-outlook-on-the-web

**Comment by ElizabethSamuel-MSFT** [comment]
@exextoc Thanks for your response.

@glatzert Can you try this out and let us know if it helped?

Thanks.

**Comment by glatzert** [comment]
@ElizabethSamuel-MSFT and @exextoc thanks - I could sideload it via the OWA of my company.
I think the docs could be improved by mentioning, the "File" > "Manage Add-Ins" for my Outlook Version

**Comment by ElizabethSamuel-MSFT** [comment]
@glatzert Thanks for letting us know the outcome. We discuss this option in the [Outlook 2013 section](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/sideload-outlook-add-ins-for-testing#outlook-2013) of the article. I'll update the 'Outlook 2016 and later' section to indicate the 2013 instructions as an alternative. PR will follow soon.
