### ISSUE TITLE
Clarity improvement

### ISSUE THREAD

**Issue by yowl** [OfficeDev/office-js-docs-pr#2322]
In point 8 
![image](https://user-images.githubusercontent.com/2720041/99015478-1a48e500-2523-11eb-9646-eb1d7a2e352c.png)
It refers to `HtmlWebpackPlugin`.  There could be 3 of these objects, the picture shows the one for `taskpane.html` but its not clear if that is the only one that needs changing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a1bb1ec-f7c0-61c7-bd50-4018a2726e3a
* Version Independent ID: dabd68f4-f474-1f01-0022-b2fe55eaafa3
* Content: [Configure your Excel add-in to share the browser runtime - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/configure-your-add-in-to-use-a-shared-runtime)
* Content Source: [docs/excel/configure-your-add-in-to-use-a-shared-runtime.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/configure-your-add-in-to-use-a-shared-runtime.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@yowl Thanks for asking about this.

@alison-mk Can you take a look?

Thanks.

**Comment by alison-mk** [comment]
Hi @yowl, thanks for this feedback! I've looked into your question and I _think_ taskpane.html is the only file in webpack.config.js that needs the `chunks` array updated to include functions, but I'm having trouble debugging to confirm. @davidchesnut can you take a look? We'll update the docs accordingly once we've confirmed.

**Comment by davidchesnut** [comment]
Hi @yowl, the documentation is not clear, and you should also remove the HtmlWebpackPlugin section that generates function.html (basically remove the following):
```json
 new HtmlWebpackPlugin({
        filename: "functions.html",
        template: "./src/functions/functions.html",
        chunks: ["polyfill", "functions"]
      }),
```
The original functions.html is no longer needed in the project when using shared runtime.

And then you add the functions chunk to the taskpane.html plugin as specified in the note:
```json
 new HtmlWebpackPlugin({
        filename: "taskpane.html",
        template: "./src/taskpane/taskpane.html",
        chunks: ["polyfill", "taskpane","functions"]
      }),
```

I'll check in a PR to update the article on this soon. Thanks!

**Comment by davidchesnut** [comment]
Hi @yowl, 
These steps were updated so should be clear now. Please let us know if you spot any other issues. Thanks!
