### ISSUE TITLE
Incorrect file paths for certain Mac folders in these instructions

### ISSUE THREAD

**Issue by lizafurr-leanix** [OfficeDev/office-js-docs-pr#2323]
In the section "Clear the Office cache on Mac", in the second purple Note box there's a list of folders. The first two folders listed have complete file paths; the second two folders are partial file paths, missing the beginning of the path. (Are they also in ~/Library/Containers/ , or somewhere else?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e273e29-10ac-440e-634e-588b5208e484
* Version Independent ID: a5a6dc8a-b504-686e-80ce-45aabd6f832b
* Content: [Clear the Office cache - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/clear-cache)
* Content Source: [docs/testing/clear-cache.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/clear-cache.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@lizafurr-leanix Thanks for pointing this out. They may also be in `~/Library/Containers`. We'll update the docs to note this.

Thanks.
