### ISSUE TITLE
Clarification on "Line Of Business" update

### ISSUE THREAD

**Issue by nikki9696** [OfficeDev/office-js-docs-pr#2328]
> Line-of-business add-in: If an admin explicitly uploaded a manifest file when implementing Centralized Deployment via the Microsoft 365 admin center, the admin must upload a new manifest file that contains the desired changes. After the updated manifest file has been uploaded, the next time the relevant Office applications start, the add-in will update.

We can either manually upload an xml file (browse), or we can specify a url. Is the above also true when we specified a url? That is, is selecting a manifest url instead of a file also considered "upload"?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41508035-2045-1706-9917-cd2da1e99cc7
* Version Independent ID: ea51ce32-18e2-68ed-ddc5-74f0d3d8a3d1
* Content: [Publish Office Add-ins using Centralized Deployment via the Microsoft 365 admin center - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/publish/centralized-deployment)
* Content Source: [docs/publish/centralized-deployment.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/publish/centralized-deployment.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@nikki9696 Thanks for asking about this. We'll respond with an answer soon.

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@nikki9696 I've confirmed with the team that you can also point to the URL of the manifest file to update the add-in. I'll work on clarifying this in the article.

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@nikki9696 Do take a look at the linked PR to see if that helps clarify this for you.

Thanks.
