### ISSUE TITLE
XSD file link is not working

### ISSUE THREAD

**Issue by ziyaaktas** [OfficeDev/office-js-docs-pr#2335]
https://github.com/OfficeDev/office-js-docs-pr/blob/master/openspecs/office_file_formats/ms-owemxml/c6a06390-34b8-4b42-82eb-b28be12494a8  throws 404

**Comment by mscharlock** [comment]
Hi @ziyaaktas - Thanks for writing in and reading the docs! Can you let me know where this broken link is located in our docs? Happy to change it. Thanks!

**Comment by ziyaaktas** [comment]
@mscharlock this one here, https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/troubleshoot-manifest.md#validate-your-manifest-against-the-xml-schema

**Comment by mscharlock** [comment]
Hi again - Can you tell me if you can see it on [this docs page](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/troubleshoot-manifest#validate-your-manifest-against-the-xml-schema)? I believe the reason the link isn't showing up is that the link doesn't work on Github itself, but will work if viewed on docs.microsoft.com. Let me know if that works!

**Comment by ziyaaktas** [comment]
> Hi again - Can you tell me if you can see it on [this docs page](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/troubleshoot-manifest#validate-your-manifest-against-the-xml-schema)? I believe the reason the link isn't showing up is that the link doesn't work on Github itself, but will work if viewed on docs.microsoft.com. Let me know if that works!

That works, but don't we have to fix the one on github somehow as well?

**Comment by mscharlock** [comment]
Unfortunately Github does not recognize the relative link, although docs does. Otherwise we would definitely fix, but this is the recommended approach. Let me know if you have other questions. I'm going to close this issue now, but I will go ahead and reopen if you need anything else and comment on this thread :)
