### ISSUE TITLE
How do remove this add-in?

### ISSUE THREAD

**Issue by ken444** [OfficeDev/office-js-docs-pr#2338]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bac6469-78a6-dae9-e6c4-497c953a1576
* Version Independent ID: d860aff2-60ad-c008-2d10-b046f3198f44
* Content: [Custom functions quick start - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-custom-functions-quickstart?tabs=excel-windows)
* Content Source: [docs/quickstarts/excel-custom-functions-quickstart.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/quickstarts/excel-custom-functions-quickstart.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @ken444, 

You should be able to remove everything by clearing the Office cache. Instructions on how to do that can be found here: https://docs.microsoft.com/office/dev/add-ins/testing/clear-cache

Please let me know if those instructions help. Thanks!

**Comment by ken444** [comment]
That worked!
Thanks

**Comment by AlexJerabek** [comment]
Awesome! Glad to hear it. I'll close the issue,, but please feel free to open any others as you continue to learn the platform.
