### ISSUE TITLE
Unable to get user information when "Get my user profile information" click

### ISSUE THREAD

**Issue by Faiqrana** [OfficeDev/office-js-docs-pr#2360]
I have followed the documentation of sso addin thoroughly. created the sso, configured the sso, registered the addin on azure portal. but when i click the button. i does not work.

**taskpane.js file**
const ssoAuthHelper = require("./../helpers/ssoauthhelper");

Office.onReady(info => {
  if (info.host === Office.HostType.Outlook) {
    document.getElementById("getGraphDataButton").onclick = ssoAuthHelper.getGraphData;
  }
});

ssauthelper.js file

const documentHelper = require("./documentHelper");
const fallbackAuthHelper = require("./fallbackAuthHelper");
const sso = require("office-addin-sso");
let retryGetAccessToken = 0;

export async function getGraphData() {
  try {
    let bootstrapToken = await OfficeRuntime.auth.getAccessToken({ allowSignInPrompt: true });
    let exchangeResponse = await sso.getGraphToken(bootstrapToken);
    if (exchangeResponse.claims) {
      let mfaBootstrapToken = await OfficeRuntime.auth.getAccessToken({ authChallenge: exchangeResponse.claims });
      exchangeResponse = sso.getGraphToken(mfaBootstrapToken);
    }

    if (exchangeResponse.error) {
      handleAADErrors(exchangeResponse);
    } else {
      const response = await sso.makeGraphApiCall(exchangeResponse.access_token);
      documentHelper.writeDataToOfficeDocument(response);
      sso.showMessage("Your data has been added to the document.");
    }
  } catch (exception) {
    if (exception.code) {
      if (sso.handleClientSideErrors(exception)) {
        fallbackAuthHelper.dialogFallback();
      }
    } else {
      sso.showMessage("EXCEPTION: " + JSON.stringify(exception));
    }
  }
}

function handleAADErrors(exchangeResponse) {
  if ((exchangeResponse.error_description.indexOf("AADSTS500133") !== -1) && (retryGetAccessToken <= 0)) {
    retryGetAccessToken++;
    getGraphData();
  } else {
    fallbackAuthHelper.dialogFallback();
  }
}

**Comment by ElizabethSamuel-MSFT** [comment]
@Faiqrana Thanks for raising this issue.

@davidchesnut Can you take a look?

Thanks.

**Comment by davidchesnut** [comment]
Hi @Faiqrana 

Can you please provide a link to the documentation page you followed? Also what is the error or behavior you are seeing?

Thanks!
David
