### ISSUE TITLE
Approach doesn't work with modern SharePoint

### ISSUE THREAD

**Issue by andrew-lovatt-BHL** [OfficeDev/office-js-docs-pr#2364]
Instructions are fine for Classic SharePoint. However for Modern SharePoint pages (which we are being pushed to use) there is no Script Editor, so no way to use the JS APIs, so can't even do something as basic as select which sheet of the Visio file to show when embedded.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cd19f0c-1f29-9d7f-aa8f-de4d76ef49fa
* Version Independent ID: fc17f697-1143-f7e3-5672-6da627874273
* Content: [Visio JavaScript API overview - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/overview/visio-javascript-reference-overview)
* Content Source: [docs/reference/overview/visio-javascript-reference-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/overview/visio-javascript-reference-overview.md)
* Product: **visio**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
I'm trying to get answers internally.
