### ISSUE TITLE
Is it possible for developer to publish a template application in app registrations page. In order to let customer use their application directly.

### ISSUE THREAD

**Issue by hello-chenchen** [OfficeDev/office-js-docs-pr#2368]
For this document, if we want to integrate Microsoft's sso, our customer need new an application on their own Azure portal. And configure their own office365 add-in manifest.xml.

We want to provide more easily options for our customer.

For example, we can publish an application template on app registrations page(which have a fixed and unique Client ID such as: 3521aa47-c584-473e-ae97-d28ed2c22ec7). our customer can new registration though search and use our template(we have already configured, but not include security key, they can add them by themself). And we can public use the fixed and unique client id on our production manifest.xml. so that, our customer will don't need to do so much things on their side. just use our app template and add security key.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c51a742c-4ddb-dd5e-7f67-3242a158378a
* Version Independent ID: b5d96164-bec6-7732-79ad-8c6beef7e0c4
* Content: [Create a Node.js Office Add-in that uses single sign-on - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/create-sso-office-add-ins-nodejs)
* Content Source: [docs/develop/create-sso-office-add-ins-nodejs.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/create-sso-office-add-ins-nodejs.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@hello-chenchen Thanks for asking about this.

@davidchesnut Can you take a look?

Thanks.

**Comment by hello-chenchen** [comment]
This problem have found solution here: [Azure Active Directory consent framework](https://docs.microsoft.com/en-us/azure/active-directory/develop/consent-framework)
and [Quickstart: Sign in users and get an access token in a Node web app using the auth code flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-v2-nodejs-webapp-msal?WT.mc_id=Portal-Microsoft_AAD_RegisteredApps) or [Quickstart: Add sign-in with Microsoft to a Java web app](https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-v2-java-webapp)

![image](https://user-images.githubusercontent.com/1878089/101756259-cd036780-3b10-11eb-9ffb-983ea9cb57dd.png)

@ElizabethSamuel-MSFT  I think, if you can put these guide in the document, it will be better. [Create a Node.js Office Add-in that uses single sign-on](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/create-sso-office-add-ins-nodejs) -> **Register the add-in with Azure AD v2.0 endpoint** -> **5. Select Authentication under Manage.**

**Comment by ElizabethSamuel-MSFT** [comment]
Reopening so we can take a look at updating the guide. Thx.

**Comment by ElizabethSamuel-MSFT** [comment]
@davidchesnut Can you check on this? Thanks.

**Comment by davidchesnut** [comment]
I think this is taken care of. Recent updates made to the Office SSO documentation link more prominently to the Microsoft identity documentation (which is the primary source of info on the Azure portal and registration). Also the registration steps in the walkthrough were updated with additional information and images to help add clarity. So I think it's all good, but happy to reopen this if anyone still thinks there is more info needed in the walkthrough.
