### ISSUE TITLE
Clearer documentation for Enabled manifest tag platform support

### ISSUE THREAD

**Issue by brianthemike** [OfficeDev/office-js-docs-pr#2376]
As the title states, I am getting an XML validation error when uploading my manifest that contains the Enabled tag. If I remove the Enabled tag, it loads fine.  Here is my XML for the control:

` <Control xsi:type="Button" id="ActionButton">`
` <Label resid="ActionButton.Label"/>`
`<Supertip>`
`<Title resid="ActionButton.Label"/>`
`<Description resid="ActionButton.Tooltip"/>`
`</Supertip>`
`<Icon>`
`<bt:Image size="16" resid="Icon.16x16"/>`
`<bt:Image size="32" resid="Icon.32x32"/>`
`<bt:Image size="80" resid="Icon.80x80"/>`
`</Icon>`
`<Action xsi:type="ExecuteFunction">`
`<FunctionName>sendSecure</FunctionName>`
`</Action>`
`<Enabled>false</Enabled>`
`</Control>`

The error being received is:
This app can't be installed. The manifest file doesn't conform to the schema definition. The element 'Control' in namespace 'http://schemas.microsoft.com/office/mailappversionoverrides/1.1' has invalid child element 'Enabled' in namespace 'http://schemas.microsoft.com/office/mailappversionoverrides/1.1'... The element 'Control' in namespace 'http://schemas.microsoft.com/office/mailappversionoverrides/1.1' has invalid child element 'Enabled' in namespace 'http://schemas.microsoft.com/office/mailappversionoverrides/1.1'.

Is this an issue with 1.1 versionoverrides?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c20c6831-2f89-5744-f1c3-5283ac6eb12e
* Version Independent ID: 400d9811-d5cc-1783-68a0-068358c37722
* Content: [Enabled element in the manifest file - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/enabled)
* Content Source: [docs/reference/manifest/enabled.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/manifest/enabled.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for reporting this @brianthemike. 

@exextoc, could you please investigate?

**Comment by exextoc** [comment]
The Enabled manifest element is [only available in Excel](https://docs.microsoft.com/en-us/office/dev/add-ins/design/disable-add-in-commands#office-application-and-platform-support-only). Currently the Enabled element, is not supported in Outlook. We track Outlook add-in feature requests on our [user-voice page](https://officespdev.uservoice.com/forums/224641-general/category/131778-outlook-add-ins). Please add your request there. Feature requests on user-voice are considered, when we go through our planning process.

**Comment by brianthemike** [comment]
Thank you for the clarification. I would recommend putting this info on the [manifest reference page](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/enabled) for this element.  It can still be confusing to those who don't necessarily want to enable programmatically and may just want to disable a button, etc. instead of commenting out lines in their manifest or webpack.config.

**Comment by AlexJerabek** [comment]
@brianthemike We will update the docs accordingly. I'll reopen and rename the issue to track the necessary changes.
