### ISSUE TITLE
Outlook v2.0 REST API deprecation inquiries

### ISSUE THREAD

**Issue by glr0221** [OfficeDev/office-js-docs-pr#2382]
Inquiries on impact of the Outlook REST v2.0 API Deprecation 

## Article URL

https://docs.microsoft.com/en-us/previous-versions/office/office-365-api/api/version-2.0/use-outlook-rest-api

## Issue

 Hello Microsoft,

Recently, we found out that the Outlook V2.0 REST APIs will be deprecated and will not be supported anymore. This is according to this documentation : https://docs.microsoft.com/en-us/previous-versions/office/office-365-api/api/version-2.0/use-outlook-rest-api

That being said, I would just like to confirm my understanding :

1. Starting November 17, 2020, there will be no more support/bug-fixes/updates for the Outlook V2.0 REST APIs. Correct? So if a bug was found in one of the V2.0 APIs, it will not be fixed anymore even if a github ticket was filed for it. Is my understanding correct?

2. On November 30, 2022, all add-ins and applications using the Outlook V2.0 REST APIs, will not work anymore because of the decommissioning of the APIs. Is my understanding correct?

3. Finally, how about the Exchange Web Service (EWS) SOAP APIs? Are they affected by this deprecation? Or will the support for EWS-APIs be continued? If these too were to be deprecated, what is the timeline for such?

Thank you very much and more power.

**Comment by ElizabethSamuel-MSFT** [comment]
@glr0221 Thanks for asking about this. Assigning to @JuaneloJuanelo to take a look.

Thanks.

**Comment by glr0221** [comment]
@ElizabethSamuel-MSFT. before anything else, Happy new year to all of you!!! As for this ticket, it seems that @JuaneloJuanelo is a bit busy. Any chance we can ask somebody else knowledgeable of this? Thank you.

**Comment by AlexJerabek** [comment]
@exextoc, could you please investigate?

**Comment by JuaneloJuanelo** [comment]
@glr0221  thanks for your inquiry. 
Answer is yes for 1 and 2.  Also: 

The recommendation on that page is exactly the same for any client consuming Outlook v2.0 REST API, that included Outlook Add-ins, so basically you need to move to the Graph all such calls using Outlook REST APIs v2.0. Please  check our documents and samples (i.e. script lab)  on how to do this.  

In addition to this, we also recommend you to [use our SSO auth feature](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/sso-in-office-add-ins). in case you need to call APIs other than the Outlook scope. 

Finally, this has no relationship whatsoever with our EWS Services, that is not affected by this issue.

**Comment by JuaneloJuanelo** [comment]
@ElizabethSamuel-MSFT  can you please close the issue?

**Comment by glr0221** [comment]
Thank you very much @JuaneloJuanelo Thank you very much @ElizabethSamuel-MSFT and @AlexJerabek. Your answers have enlightened me and have significant impact to our future plans. Thank you again.
