### ISSUE TITLE
Where is the documentation for Office.ui.messageChild method?

### ISSUE THREAD

**Issue by david-ps** [OfficeDev/office-js-docs-pr#2388]
Cannot find details about [documentation ](https://docs.microsoft.com/en-us/javascript/api/office/office.ui?view=excel-js-preview)for Office.ui.messageChild method
Is this still in preview. It appears that Dialog 1.2 is in a GA Requirement Set.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f3b62b6-b625-e444-82e3-8f5e2b324a28
* Version Independent ID: 40beb714-8d9d-60ca-7690-0402a23718b0
* Content: [Dialog API requirement sets - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/dialog-api-requirement-sets)
* Content Source: [docs/reference/requirement-sets/dialog-api-requirement-sets.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/requirement-sets/dialog-api-requirement-sets.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @david-ps, 

Thanks for pointing out that mistake. I suspect that's either supposed to reference {Office.ui.messageParent)(https://docs.microsoft.com/en-us/javascript/api/office/office.ui?view=excel-js-preview#messageParent_message_) or [Office.Dialog.messageChild](https://docs.microsoft.com/en-us/javascript/api/office/office.dialog?view=excel-js-preview#messageChild_message_). Let me tag some people from the feature crew to confirm.

In the meantime, the article [Use the Office dialog API in Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins?view=excel-js-preview) should offer some guidance on how to use the Dialog APIs in your add-in.

**Comment by david-ps** [comment]
Thanks @AlexJerabek 

I am still unclear about [messageParent(message) ](https://docs.microsoft.com/en-us/javascript/api/office/office.ui?view=excel-js-preview#messageParent_message_ ) which "Delivers a message from the dialog box to its parent/opener page" which I assume the TaskPane in most cases? Other examples?

In **Remarks** the doc mentions **Requirement set: DialogAPI** but does not identify the DialogApi version?

Can you please confirm/clarify the above.

**Comment by AlexJerabek** [comment]
Hi @david-ps, 

I checked the [version history of the UI API page](https://github.com/OfficeDev/office-js-docs-reference/commits/master/docs/docs-ref-autogen/office/office/office.ui.yml) and the entry for `message Parent`. It looks like that method predates DialogAPI 1.2, so it must be part of 1.1 (or else something's really wrong in the documentation).

I believe the parent is always the task pane and that the entry in more general to allow for future extensions. I'll confess this isn't my area of expertise; the people assigned to the issue will provide better help once they return from their holidays.

**Comment by david-ps** [comment]
Hi @AlexJerabek 

The DialogAPI version is important to us. We have assumed it is 1.2, so we look forward to clarifying that dependency and  updated documentation. 

Note that [messageChild](https://docs.microsoft.com/en-us/javascript/api/office/office.dialog?view=excel-js-preview#messageChild_message_) Remarks indicate 1.2 so it would be strange if the reverse predates it.

**Comment by Rick-Kirkham** [comment]
messageParent is part of DialogApi 1.1. For a few years there wasn't any equivalent messageChild, but messageChild was added in DialogApi 1.2.  The parent page of a dialog can be a task pane or a UI-less FunctionFile that is launched from a custom ribbon button (an Add-in Command). 

As @AlexJerabek suggested, the DialogApi 1.2 page should link to https://docs.microsoft.com/en-us/javascript/api/office/office.dialog?view=excel-js-preview#messageChild_message_. I'll fix that.
