### ISSUE TITLE
Identity API still not supported for iOS

### ISSUE THREAD

**Issue by frasparacio** [OfficeDev/office-js-docs-pr#2389]
I do understand from [here](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/identity-api-requirement-sets) that Identity API is still not available on ipad (so I guess on iOS as I'm not able to get an access token in iOS outlook app).

It could be really helpful to update the documentation listing this api as not supported in current mobile outlook support page or having a specific section for this as this could represent an important limitation in add in development and distribution

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e5e66e3-2a60-8258-a97e-01e9b3f2edce
* Version Independent ID: 25de6241-1808-1a62-c670-cddf56f4fe8f
* Content: [Add mobile support to an Outlook add-in - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/add-mobile-support)
* Content Source: [docs/outlook/add-mobile-support.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/outlook/add-mobile-support.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for the suggestion @frasparacio. @davidchesnut, could you please update this documentation accordingly?

**Comment by ElizabethSamuel-MSFT** [comment]
@frasparacio We're updating the requirement set support page to include IdentityAPI 1.3 where available (see linked PR).

Let us know if you have any other concerns/feedback.

Thx.
