### ISSUE TITLE
Windows Server 2016 still use Internet Explorer (TerminalServer)

### ISSUE THREAD

**Issue by cyril-iselin** [OfficeDev/office-js-docs-pr#2391]
Windows Server 2016 still use Internet Explorer (TerminalServer). You only talk about win10 and win8.1 what's about windows server? How wie force Windows Server 2016 to use Edge instead of Internet Explorer?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00c430f1-bbf5-53b8-a225-4fbe8fc39c3b
* Version Independent ID: 0a069a0d-4d35-71ee-53af-8c55fe8548a0
* Content: [Browsers used by Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins)
* Content Source: [docs/concepts/browsers-used-by-office-web-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/concepts/browsers-used-by-office-web-add-ins.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for the question @cyril-iselin. @Rick-Kirkham, could you please investigate?

**Comment by smaremanda** [comment]
@cyril-iselin - you should be able to download the new Edge browser to Windows Server 2016. See here for Microsoft Edge supported OSs: https://docs.microsoft.com/en-us/deployedge/microsoft-edge-supported-operating-systems
If you are referring to the Webview2 runtime, please see here https://docs.microsoft.com/en-us/microsoft-edge/webview2/ for supported OSs [Windows Server 2016 is included].
Could you give this a try and let us know how things work?

**Comment by cyril-iselin** [comment]
We installed webview2 and edge but Outlook  is still loading IE11... 😭

**Comment by mscharlock** [comment]
@ElizabethSamuel-MSFT just a heads up, may need to reassign this issue?

**Comment by AlexJerabek** [comment]
@slabereemsft, can you please take a look?

**Comment by slabereemsft** [comment]
Hi Cyril,

Sorry for the delayed response. Is this still an issue for you?  

Generally if you are using Server 2016 Microsoft 365 ver. >= 16.0.13530.204241 you will get the new Edge WebView2 runtime.  This was rolling out at the time this was logged so you might have had a different experience then.
