### ISSUE TITLE
Admin permissions missing?

### ISSUE THREAD

**Issue by giterdn** [OfficeDev/office-js-docs-pr#2393]
[Enter feedback here]
As I don't see Settings > Services & add-ins at the admin console (I can access Settings but Services & add-ins is no longer listed) I don't know if something is wrong with the portal or if I don't have the permissions needed to see this option.  I suggest all articles advise what minimum admin privs are needed to perform the configuration steps.  I am an Office admin but not a Global Admin (although I do have Global reader, so I should at least see Services & add-ins, shouldn't I?)

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41508035-2045-1706-9917-cd2da1e99cc7
* Version Independent ID: ea51ce32-18e2-68ed-ddc5-74f0d3d8a3d1
* Content: [Publish Office Add-ins using Centralized Deployment via the Microsoft 365 admin center - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/publish/centralized-deployment)
* Content Source: [docs/publish/centralized-deployment.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/publish/centralized-deployment.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for the question @giterdn. Assigning @exextoc to investigate (or reassign as needed).

Just to clarify, were you seeing the "Services and add-ins" option previously? Is this a recent behavior change?

**Comment by giterdn** [comment]
Hi,

I used to see this option previously (Nov 2020) and now cannot see it.  Thanks,
Steve
STEVE KISH | Manager - Desktop, Mobility & Telecom

CITY OF SURREY
Corporate Services, IT Division
13450 104 Ave, Surrey, BC, Canada V3T 1V8
T 604.591.4878 | C 604.345.0288  www.surrey.ca<http://www.surrey.ca/>

**Comment by AlexJerabek** [comment]
Including @ElizabethSamuel-MSFT to help drive this investigation from the documentation side.

**Comment by exextoc** [comment]
There is a recent change that only Global admins or Exchange admins can see “Services & add-ins” option.
In case you are one of the above and still not seeing this option then possibly you would be seeing "Integrated Apps" under "Settings"  in admin portal which is new Centralized Deployment experience.

**Comment by giterdn** [comment]
Thank you for your reply.

Add-ins are for Office, yet an Office Admin role can’t manage these.  I manage Office, not Exchange and certainly not the entire tenant.  Where can I send my feedback that this is a bad design change that needs to be reversed?

Thanks again,

Steve

On Jan 7, 2021, at 8:44 PM, Outlook Add-ins Team - MSFT <notifications@github.com<mailto:notifications@github.com>> wrote:



There is a recent change that only Global admins or Exchange admins can see “Services & add-ins” option.
In case you are one of the above and still not seeing this option then possibly you would be seeing "Integrated Apps" under "Settings" in admin portal which is new Centralized Deployment experience.

**Comment by ElizabethSamuel-MSFT** [comment]
@exextoc Can you provide guidance re: giving feedback on this design change?

Thanks.

**Comment by exextoc** [comment]
Please share your feedback via User Voice https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback?category_id=20890

**Comment by giterdn** [comment]
Thank you for addressing this

**Comment by ElizabethSamuel-MSFT** [comment]
@giterdn Thanks again for your interest in Outlook add-ins! If you have any further questions, concerns, or feedback, let us know.

I'll go ahead and close this issue now.

Thanks.
