### ISSUE TITLE
Add Rows to a Table - Warning Required

### ISSUE THREAD

**Issue by david-ps** [OfficeDev/office-js-docs-pr#2412]
Please add a critical warning for developers.

The documentation fails to disdplay a Note warning that Adding Rows to a Table when undertaken from a Content Pane Add-in has a fatal memory flaw. 

The fix is not yet available and it is yet unclear as to impacts on Requirements Sets. 
See comment: "Oldest version we can port back is 16.0.13127.*(semiannual version which is released on July 2020). New Excel version should support ExcelApi 1.9."

See Open Issue: [Fatal Memory Issue - Excel Content Pane updating a Table #1415](https://github.com/OfficeDev/office-js/issues/1415)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d58d1b1e-7871-0323-b292-f4082e4fb39d
* Version Independent ID: 7f2f35d4-9424-808e-03a0-7dfef4d2e63a
* Content: [Work with tables using the Excel JavaScript API - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-tables#add-rows-to-a-table)
* Content Source: [docs/excel/excel-add-ins-tables.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/excel-add-ins-tables.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks @david-ps. We'll update the documentation to alert developers to the linked issue.

@alison-mk , can you please make the requested changes? Thanks!

**Comment by alison-mk** [comment]
Hi @david-ps, thank you for submitting this feedback! We've updated the Table article to mention the memory problem and link to the open office-js issue. Since this documentation update has been merged (and will be pushed live soon), I will close this issue. Please let us know if you have any additional documentation feedback or questions. -Alison
