### ISSUE TITLE
Outlook add-in cannot pass the attachments of a selected item directly to the remote service

### ISSUE THREAD

**Issue by parilla** [OfficeDev/office-js-docs-pr#2414]
What is the rationale behind the statement _'Outlook add-in cannot pass the attachments of a selected item directly to the remote service'_?

e.g. Is this due to a technical limitation, or merely the transfer of attachments directly via the Outlook add-in is not recommended?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dda6b13f-f452-8f7a-bd89-63ad43d06511
* Version Independent ID: b60f95f2-ac6b-88dd-ac5e-35c5197b2528
* Content: [Get attachments in an Outlook add-in - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/get-attachments-of-an-outlook-item)
* Content Source: [docs/outlook/get-attachments-of-an-outlook-item.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/outlook/get-attachments-of-an-outlook-item.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@parilla Thanks for asking about this.

@exextoc Can you take a look?

Thanks.

**Comment by exextoc** [comment]
To some extent, this is to avoid a situation where you are pushing potentially a large file through the service. If you are going to end up with the file on your backend anyway, you might as well retrieve it directly from there. 

However, it is worth nothing that GetAttachmentContentAsync, does allow you to get the Base64 content of some attachments into your add-in directly. (https://docs.microsoft.com/en-us/javascript/api/outlook/office.attachmentcontent?view=outlook-js-preview) Which I believe didn't exist when this document was written. (and is also only available on updated clients)

**Comment by ElizabethSamuel-MSFT** [comment]
@exextoc That's a good point. I'll take a pass through the article and bring it up to date.
