### ISSUE TITLE
Can non visual add ins be created?

### ISSUE THREAD

**Issue by GobbaFish** [OfficeDev/office-js-docs-pr#242]
Is it possible to create an add in that simply responds to any document or email being opened or closed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42faa32c-446b-0209-4a24-9a29b4921ea1
* Version Independent ID: a5f0fc77-a881-df1e-1f49-aa0e555022e0
* Content: [Office Add-ins platform overview](https://docs.microsoft.com/en-us/office/dev/add-ins/overview/office-add-ins#how-are-office-add-ins-different-than-com-and-vsto-add-ins)
* Content Source: [docs/overview/office-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/overview/office-add-ins.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
The issues on this repo are intended to report errors in the documentation. Please ask technical questions on StackOverflow and tag them office-js.
