### ISSUE TITLE
Webview2 is not used to host Addin on Outlook 365 desktop ver. 16.0.13530.20368

### ISSUE THREAD

**Issue by paodecode** [OfficeDev/office-js-docs-pr#2429]
According to page "Browsers used by Office Add-ins"(https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins)
Webview2 (Edge Chromium) should be used to render our Addin but is using Webview.(legacy Edge)
Is this expected or a bug?

My environment details:
- Windows 10 64 bit ver. 1909 build 18363.1256
- Microsoft 365 MSO (16.0.13530.20368) 64-bit
- Microsoft Edge 87.0.664.75
- Microsoft Edge WebView2 Runtime 87.0.664.75
- My Addin manifest.xml does not include Runtimes element
- WebView2 control does work in a test .Net Framwork 4.8 application on the same PC (User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36 Edg/87.0.664.75)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00c430f1-bbf5-53b8-a225-4fbe8fc39c3b
* Version Independent ID: 0a069a0d-4d35-71ee-53af-8c55fe8548a0
* Content: [Browsers used by Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins)
* Content Source: [docs/concepts/browsers-used-by-office-web-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/concepts/browsers-used-by-office-web-add-ins.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
I've been advised that WebView2 has not been turned on in non-Insider channels yet. That should happen very soon. In the meantime, can you try using moving your Microsoft 365 subscription to be on the [Current Channel (Preview)](https://insider.office.com/join/windows) [formerly called "Monthly Channel (Targeted)" or "Insider Slow"]?

**Comment by paodecode** [comment]
Thanks for the quick turnaround. I can't easily try preview channel at the moment.
My feedback is that switching to WebView2 cannot come too soon. Any Addin authored with modern tooling needs it now (polyfill 
 backward compatibility is never quite right and very costly to maintain).
Could you provide a time frame for "should happen very soon"? Thanks!

**Comment by Rick-Kirkham** [comment]
I think this was connected to a serious bug we discovered only after the WebView2 enabling was released to non-Insider channels. The release had to be pulled back. It has now been fixed and rereleased. Please wait a couple of days and see if it starts working in non-insider channels. In the meantime, I'm checking with the engineers.

**Comment by Rick-Kirkham** [comment]
@paodecode It turns out that there was some internal miscommunication here. The build that you need for WebView2 is actually 16.0.13530.20**424**, not 16.0.13530.20316 . I will fix the documentation page tonight.
