### ISSUE TITLE
unclear instruction

### ISSUE THREAD

**Issue by lousilver** [OfficeDev/office-js-docs-pr#2430]
For someone either completely new or returning after several years (decades?) there was a step that was unclear on this page, namely how to access the manifest. The prior steps clearly identified which files to modify, but for the final code change there was no file with "manifest" in the name, there were many xml files in the project folder, and there was no readily apparent dropdown in the developer menus.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c4ddde7-f1fd-44ba-fba1-0ae9d0131df7
* Version Independent ID: d946ffe6-f29f-1563-b679-121090ba60a1
* Content: [Build your first Excel task pane add-in - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-jquery?tabs=visualstudio#update-the-manifest)
* Content Source: [docs/quickstarts/excel-quickstart-jquery.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/quickstarts/excel-quickstart-jquery.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by lousilver** [comment]
also googling about manifests talked about adding a new (manifest) file, but nothing about identifying an existing project file (a single clue about project.manifest, but no such file existed in the folder)

**Comment by ElizabethSamuel-MSFT** [comment]
@lousilver Thanks for bringing this to our attention!

@alison-mk Can you take a look?

Thanks.

**Comment by mscharlock** [comment]
I think you can tag me on this, I believe I was the last to touch these files.

**Comment by alison-mk** [comment]
Hi @lousilver, thank you for taking the time to submit feedback! With PR #2432, I updated this article based on your suggestion and clarified how to access the manifest XML file in Visual Studio 2019. 

If you used the default name for your add-in project, then your manifest file can be found in Solution Explorer, in the **ExcelWebAddIn1** > **ExcelWebAddIn1Manifest** directory, and the manifest will be titled **ExcelWebAddIn1.xml**. I will close this issue now, but please feel free to let us know if you have any additional questions. Cheers, -Alison 

@mscharlock Let me know if you have any suggestions on the PR that addresses this (#2432)!
