### ISSUE TITLE
Excellent idea

### ISSUE THREAD

**Issue by Didierma92** [OfficeDev/office-js-docs-pr#2434]
Giving Project a task Pane is a great idea

Didier
Project and Power BI certified consultant
+33682465535

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a52c1541-5247-c530-c627-2789f5792719
* Version Independent ID: 5bab04a0-b84e-0f0c-01e1-5d8bb69029ef
* Content: [Build your first Project task pane add-in - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/project-quickstart)
* Content Source: [docs/quickstarts/project-quickstart.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/quickstarts/project-quickstart.md)
* Product: **project**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks @Didierma92! We're glad you like the feature. 

Just so you know, Project uses the [Common API model](https://docs.microsoft.com/office/dev/add-ins/develop/office-javascript-api-object-model) and has fewer APIs than Excel or Outlook. If you need more functionality for your add-in, please request new features on [UserVoice](https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback). There, you can create and upvote feature requests for Office Add-ins.
