### ISSUE TITLE
Excel custom functions is not working for excel online.

### ISSUE THREAD

**Issue by Mansi20** [OfficeDev/office-js-docs-pr#244]
## Issue

 
It looks like support for Excel online was added on May 7, 2018, but I couldn’t get the CONTOSO example to either work or show any JS errors on Excel Online. I see build 16.0.10703.37951 if it helps. Appreciate any guidance.

**Comment by TCourtneyOwen** [comment]
Hi,

Sorry you are having problems with Custom Functions in Excel Online.  Which browser are you using to try and load custom functions in Excel Online (e.g. Chrome, Edge)?  If you haven't seen the **Sideload an Office Add-in on Office Online** instructions yet, please give them a try, and pay particular attention to the note about using Edge as your browser:  https://docs.microsoft.com/en-us/office/dev/add-ins/testing/sideload-office-add-ins-for-testing.  

Please let us know if we can be of futher help.

Thanks,

Courtney

**Comment by AlexJerabek** [comment]
Hi @Mansi20 
We have updated the custom function support for the CONTOSO example, as per the discussion here. https://github.com/OfficeDev/office-js-docs-pr/issues/258

Please try again with the updated code and reopen this issue if you are still encountering problems.
