### ISSUE TITLE
Wrong unit

### ISSUE THREAD

**Issue by andre-visma** [OfficeDev/office-js-docs-pr#2446]
> Add-ins that activate based on events are designed to be short-running, up to 330 seconds only.

I'm pretty sure it should say milliseconds.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 193780ba-aa43-dc5c-fc28-adc96a0fdeda
* Version Independent ID: da41da2b-207e-e976-3491-61672d1e3493
* Content: [Configure your Outlook add-in for event-based activation (preview) - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/autolaunch)
* Content Source: [docs/outlook/autolaunch.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/outlook/autolaunch.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for catching this @andre-visma. 

@ElizabethSamuel-MSFT, can you please confirm and implement the correction?

**Comment by ElizabethSamuel-MSFT** [comment]
@andre-visma I confirmed that the unit (seconds) is correct. This represents all the time available to the add-in to do all its processing. If your add-in only needs milliseconds to do what it needs to, then the add-in stops at that point.

Hope that helps. Let us know if you need more info or clarification about this.

Note that in the article, we're adjusting the actual length of time from 330 seconds to approximately 300 seconds. This change should be published soon.

Thanks.
