### ISSUE TITLE
Docs Applicable only to Edge Legacy?

### ISSUE THREAD

**Issue by bgausden** [OfficeDev/office-js-docs-pr#2453]
1. I appear to have a launch config out of the box after installing the office addin debugging extension in VS Code. Adding another appears unnecessary
2. It might add value to make it clear that the proposed launch config is for Edge Legacy and to provide a launch config for Edge Chromium (where a user has installed webview2.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 614e6992-f9be-4ce5-1f15-0fc6bf285c43
* Version Independent ID: 1b37e38d-06ec-cd00-16bb-3324b1f0048f
* Content: [Microsoft Office Add-in Debugger Extension for Visual Studio Code - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-with-vs-extension)
* Content Source: [docs/testing/debug-with-vs-extension.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/debug-with-vs-extension.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for raising this issue @bgausden. 

@mscharlock, could you please investigate?

**Comment by mscharlock** [comment]
Yes, thanks for the suggestion @bgausden. I am working on a doc about how to specifically add configs for webView2, so will let folks know that this one is just for legacy.

**Comment by mscharlock** [comment]
Hi @bgausden - just wanted to let you know that the webView2 docs are out here: https://docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-desktop-using-edge-chromium. I'm going to close this thread for now, but let me know if you have any other comments or issues by commenting and I will reopen this thread. Thanks!
