### ISSUE TITLE
Updates?

### ISSUE THREAD

**Issue by elthombre** [OfficeDev/office-js-docs-pr#2457]
The samples referenced in this article point to .sln projects. It would be nice if these samples were updated to the newer OfficeJS / Office web add-in project type(s).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a714626a-058a-789e-6add-5e9dfb21fd1f
* Version Independent ID: 1b88a28c-fc36-4518-2808-7246f08d9753
* Content: [Use the Office dialog API in your Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins)
* Content Source: [docs/develop/dialog-api-in-office-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/dialog-api-in-office-add-ins.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for raising this issue @elthombre. I assume you're referring to the links to [this sample](https://github.com/OfficeDev/Office-Add-in-Dialog-API-Simple-Example), right? 

@Rick-Kirkham, can you please take a look at improving this and advise if there are other relevant samples. Thanks!

**Comment by elthombre** [comment]
Yes:

https://github.com/OfficeDev/Excel-Add-in-JavaScript-SalesTracker

https://github.com/OfficeDev/Office-Add-in-Dialog-API-Simple-Example

both are .sln projects vs. something created with with Yeoman Generator, for example.

**Comment by Rick-Kirkham** [comment]
I will add a list of samples to the article. But please note that the logic of the `displayDialogAsync` method is the same regardless of whether the add-in is created with Yo Office or Visual Studio or some other way. Similarly, whether the server side is NodeJS or IIS or Apache, or whatever, doesn't matter. The code that calls `displayDialogAsync` is entirely client side. Whether the client side is Angular or React or vanilla JS has some effect on the structure of the add-in and where the Office JavaScript libraries are called, but here too, the code for calling `displayDialogAsync` and handling its callbacks is the same. Basically, any sample is going to teach how to use the method regardless of whether the sample matches the frameworks that you want to use.
