### ISSUE TITLE
Functionality not working

### ISSUE THREAD

**Issue by dlurk97** [OfficeDev/office-js-docs-pr#246]
Hi- this loads correctly for me; however, the functionality of adding the text to the onenote page does not work. Selecting the button does nothing. Is there a reference to app.js missing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f988b661-2048-e17e-f909-ea83f1dfbe09
* Version Independent ID: adcaffba-438f-c3a2-775d-9b54d5855b61
* Content: [Build your first OneNote add-in](https://docs.microsoft.com/en-us/office/dev/add-ins/onenote/onenote-add-ins-getting-started)
* Content Source: [docs/onenote/onenote-add-ins-getting-started.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/onenote/onenote-add-ins-getting-started.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @dlurk97 
I went through the quickstart as well and hit the same issue. I'm looking into this with our engineering team.

**Comment by AlexJerabek** [comment]
Hi @dlurk97,

If you remove the `app.initialize();` line from the .js file, the add-in should work fine. Please let me know if that works and I'll update the documentation accordingly.

**Comment by dlurk97** [comment]
This does not seem to solve the problem. I assume you are talking about the app.js file. I should add that I have to create app.js. It is not automatically built for me. Perhaps it is not being referenced properly?

**Comment by AlexJerabek** [comment]
The file to edit is src/index.js. app.js was the file in an older version of yo office.

We'll get the yo office steps updated too.

**Comment by AlexJerabek** [comment]
And here's the documentation fix for the file name. Thanks for finding this issue.
https://github.com/OfficeDev/office-js-docs-pr/pull/249
