### ISSUE TITLE
Sample Does Not Use displayDialogAsync

### ISSUE THREAD

**Issue by elthombre** [OfficeDev/office-js-docs-pr#2461]
This article:

https://docs.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins

references this sample in the context of displayDialogAsync but when I open the sample, I am not able to find use of that method.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a714626a-058a-789e-6add-5e9dfb21fd1f
* Version Independent ID: 1b88a28c-fc36-4518-2808-7246f08d9753
* Content: [Use the Office dialog API in your Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins)
* Content Source: [docs/develop/dialog-api-in-office-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/dialog-api-in-office-add-ins.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
If you mean the Excel-Add-in-JavaScript-SalesTracker sample, that is intended to be a sample of a tabbed task pane, not a sample that uses the dialog. I'll clarify this in the text.

**Comment by elthombre** [comment]
Hi, ideally, an add-in that runs within OWA (Outlook web app), that pushes a dialog whereby an external website is used for auth and, if successful, redirects to the add-in taskpane.

**Comment by Rick-Kirkham** [comment]
I think you should add that comment to your other Issue: the one where you requested a new sample.
