### ISSUE TITLE
I did update to Outlook for Microsoft 365 MSO Version 2101 (16.0.13628.20274) 64bit (current channel). WebView2 is not used to open Add-in.

### ISSUE THREAD

**Issue by paodecode** [OfficeDev/office-js-docs-pr#2464]
I did update to Microsoft 365 MSO Version 2101 (16.0.13628.20274) 64bit (current channel). WebView2 is not used by the host (Outlook) to open Add-in. WebView (legacy Edge) is used.
According to documentation (https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins) WebView2  should be used.
When will WebView2 be enabled?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00c430f1-bbf5-53b8-a225-4fbe8fc39c3b
* Version Independent ID: 0a069a0d-4d35-71ee-53af-8c55fe8548a0
* Content: [Browsers used by Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins)
* Content Source: [docs/concepts/browsers-used-by-office-web-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/concepts/browsers-used-by-office-web-add-ins.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by exextoc** [comment]
Bug 1931069<https://o365exchange.visualstudio.com/959adb23-f323-4d52-8203-ff34e5cbeefa/_workitems/edit/1931069>: [OfficeDev/office-js-docs-pr] I did update to Outlook for Microsoft 365 MSO Version 2101 (16.0.13628.20274) 64bit (current channel). WebView2 is not used to open Add-in. (#2464)


Created using VSTS Outlook add-in<https://www.owiki.ms/wiki/VSTS_Add-In_for_Outlook>

**Comment by exextoc** [comment]
Instructions for getting onto WebView2 can be found [here](https://developer.microsoft.com/en-us/office/blogs/announcing-webview2-for-office-add-ins-platform/).

One step you might be missing is installing the Edge WebView2 runtime (step 3).

**Comment by neville-jones** [comment]
seems similar to my issue #2521

**Comment by exextoc** [comment]
@neville-jones thanks for linking. Yes, this is the same issue as https://github.com/OfficeDev/office-js/issues/1670
