### ISSUE TITLE
The documentation appears stale.

### ISSUE THREAD

**Issue by xstos** [OfficeDev/office-js-docs-pr#2467]
I just ran the latest yeoman generator for SSO. Your tutorial has drifted from the scripts available

```
"scripts": {
    "build": "webpack -p --mode production --https false",
    "build:dev": "webpack --mode development --https false",
    "configure-sso": "office-addin-sso configure manifest.xml",
    "lint": "office-addin-lint check",
    "lint:fix": "office-addin-lint fix",
    "prettier": "office-addin-lint prettier",
    "sideload": "office-addin-debugging start manifest.xml",
    "start": "npm run build:dev && concurrently \"npm run start:server\" \"npm run sideload\"",
    "start:server": "office-addin-sso start manifest.xml",
    "validate": "office-addin-manifest validate manifest.xml",
    "watch": "webpack --watch --mode development"
  },
  ```
  Not only that but i get errors right out of the box after npm install.
  ```
  npm run configure-sso

> office-addin-taskpane-sso-js@0.0.0 configure-sso C:\SSO365
> office-addin-sso configure manifest.xml

(node:17100) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token  in JSON at position 3324
    at JSON.parse (<anonymous>)
    at C:\SSO365\node_modules\office-addin-sso\lib\configure.js:188:40
    at Generator.next (<anonymous>)
    at C:\SSO365\node_modules\office-addin-sso\lib\configure.js:6:71
    at new Promise (<anonymous>)
    at __awaiter (C:\SSO365\node_modules\office-addin-sso\lib\configure.js:2:12)
    at C:\SSO365\node_modules\office-addin-sso\lib\configure.js:182:95
    at ChildProcess.exithandler (child_process.js:299:7)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:17100) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:17100) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
_You may want to put some FAQ stuff in the guide to deal with these issues._
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a52c1541-5247-c530-c627-2789f5792719
* Version Independent ID: 5bab04a0-b84e-0f0c-01e1-5d8bb69029ef
* Content: [Build your first Project task pane add-in - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/project-quickstart)
* Content Source: [docs/quickstarts/project-quickstart.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/quickstarts/project-quickstart.md)
* Product: **project**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@xstos Thanks for raising this issue. We'll take a look. However, I noticed that you created this issue from the Project quick start. Are you trying to use SSO with Project? If so, that is not supported as SSO is currently supported only in Excel, Outlook, PowerPoint, and Word. See the [SSO quick start](https://docs.microsoft.com/office/dev/add-ins/quickstarts/sso-quickstart) for more.

@mscharlock Can you help clarify the yo office info here?

Thanks.

**Comment by xstos** [comment]
@ElizabethSamuel-MSFT I was actually trying the SSO demo for word. I may have been on the wrong page though, my bad if that was the case...

I actually opened an issue for the errors. https://github.com/OfficeDev/generator-office/issues/599

It would still be helpful if there were more docs concerning the types of errors that might occur when doing the yeoman stuff.

**Comment by ElizabethSamuel-MSFT** [comment]
@xstos Thanks for this info and for opening the other issue. We'll take a look at these issues.

 We appreciate your sharing your thoughts and feedback.

@mscharlock Is this request something that we can put on the backlog if it's not already there?
"It would still be helpful if there were more docs concerning the types of errors that might occur when doing the yeoman stuff."

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
+ @davidchesnut re: SSO aspect

**Comment by xstos** [comment]
Forgot to mention. The reason I'm using yeoman is we sell an Office 365 addin that was built over a year and a half ago and has drifted/gone stale concerning SSO and office-js, so I was trying to reconcile our package environment with the yeoman package. I'm trying to test an empty addin out against our company azure AAD infrastructure and also verify OWIN stuff in ASP.net. Most of that is motivated by recurring CORS issues to do with login.microsoftonline.com. Auth integration stuff is super frustrating as you probably already know :)

**Comment by mscharlock** [comment]
@davidchesnut - Just pinging you on this one. I'll discuss internally with the DevX folks about a yeoman errors article. Thanks!

**Comment by davidchesnut** [comment]
Hi @xstos 

It looks like the article, [Use the Yeoman generator to create an Office Add-in that uses single sign-on](https://docs.microsoft.com/office/dev/add-ins/quickstarts/sso-quickstart), is up-to-date with what yo office generates. 

Also looks like [OfficeDev/generator-office#599](https://github.com/OfficeDev/generator-office/issues/599) was resolved. So there shouldn't be any yo office sso errors popping up when you create new projects and configure them for SSO. I'm going to go ahead and close this issue, but please reopen if there are still any issues with the articles or yo office.

Thanks!
David
