### ISSUE TITLE
ExtendedPermissions tag not appending 

### ISSUE THREAD

**Issue by inderjitkr** [OfficeDev/office-js-docs-pr#2471]
Hi, I am trying to add the <ExtendedPermissions></ExtendedPermissions> tag in my manifest but it is not working. can you pls help me out in this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b4fe445-986c-45b4-8c1e-18c67b6806d9
* Version Independent ID: 59ba3ad4-6dd7-20a0-00c6-a5facb7dc08b
* Content: [ExtendedPermissions element in the manifest file - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/extendedpermissions)
* Content Source: [docs/reference/manifest/extendedpermissions.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/manifest/extendedpermissions.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @inderjitkr, 

Can you please provide some more information for us? Are you getting a schema validation error when adding the tag? Is `AppendOnSend` not working properly in the associated add-in?
