### ISSUE TITLE
First Outlook Add-In fail

### ISSUE THREAD

**Issue by sgperlman** [OfficeDev/office-js-docs-pr#2486]
[Enter feedback here]
I'm not able to get past the step where we "start" the solution for local testing. I have entered my outlook credentials (it's an Office 365 account) and have also enabled MFA (as per the initial error message).

I'm stuck at this error: 

> Request Id:  d7018367-d0fb-48a7-8a1b-31715cf32000 
>  
> Correlation Id:  376bba71-76e9-4409-afb3-3eb60bf15c51 
> 
> Timestamp:  2021-02-09T18:05:37Z 
>  
> Message:  AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: '47d3699f-952e-4eaa-a839-dcb2baaaaf0a'.  

I tried to register the application [here](https://aad.portal.azure.com/) but I still can't get past this error.
    

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 930ce4fc-c8b8-f756-f03f-a716f1ef7883
* Version Independent ID: 753a2e38-9430-25bb-5409-b7eed9c88e47
* Content: [Build your first Outlook add-in - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/outlook-quickstart?tabs=yeomangenerator)
* Content Source: [docs/quickstarts/outlook-quickstart.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/quickstarts/outlook-quickstart.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@sgperlman Thanks for letting us know about this. Did you try this in Visual Studio or Yeoman Generator (yo office)?

Thanks.

**Comment by sgperlman** [comment]
@ElizabethSamuel-MSFT I was using Visual Studio.

**Comment by ElizabethSamuel-MSFT** [comment]
@sgperlman Can you try creating a [Microsoft account](https://account.microsoft.com/account) and using it to test your add-in?

Also, the error you're hitting is external to Office Add-ins. Can you search online for "AADSTS50011" and see if there are existing solutions for your particular situation? If there aren't, consider asking a question about this AAD error on [Microsoft Q&A](https://docs.microsoft.com/answers/products/).

Let us know the outcome from trying any of these options or some alternative so we can update the quick start if needed.

Thanks.
