### ISSUE TITLE
npm run configure-sso fails with error: Unable to determine if user is tenant admin

### ISSUE THREAD

**Issue by Roleofm** [OfficeDev/office-js-docs-pr#2503]
I'm following the tutorial on https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/sso-quickstart#configure-sso
I have generated a Office add in for word with the SSO template in typescript. I'm using node version 14.15.5 and windows 10

At the step when I run npm run configure-sso the script fails.
I was logged in as a tenant admin

this is the log with the error:
```
C:\Users\Roelof>cd WordTSSSOAddIn

C:\Users\Roelof\WordTSSSOAddIn>npm run configure-sso

> office-addin-taskpane-sso@0.0.0 configure-sso C:\Users\Roelof\WordTSSSOAddIn
> office-addin-sso configure manifest.xml

Opening browser for authentication to Azure. Enter valid Azure credentials
Login was successful!
Registering new application in Azure
Application was successfully registered with Azure
Setting identifierUri
Setting signin audience
(node:10008) UnhandledPromiseRejectionWarning: Error: Unable to determine if user is tenant admin:
ERROR: Bad Request({
  "error": {
    "code": "Request_BadRequest",
    "message": "Invalid object identifier 'members'.",
    "innerError": {
      "date": "2021-02-13T18:04:44",
      "request-id": "9ba58306-e689-4a9c-84c1-89f3977a05c4",
      "client-request-id": "9ba58306-e689-4a9c-84c1-89f3977a05c4"
    }
  }
})

    at Object.<anonymous> (C:\Users\Roelof\WordTSSSOAddIn\node_modules\office-addin-sso\lib\configure.js:155:19)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\Roelof\WordTSSSOAddIn\node_modules\office-addin-sso\lib\configure.js:4:65)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:10008) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:10008) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

C:\Users\Roelof\WordTSSSOAddIn>
```

**Comment by nkkinariwala** [comment]
@Roleofm - Thank you for posting a question. Can you please provide these additional details?

Your Environment
Platform: ______
Host: Word
Office version number:______
Operating System: ______
Browser (if using Office on the web): ______

**Comment by Roleofm** [comment]
Hi Nisarg,



Sorry, you can close this issue. I just created a new project and the command "npm run configure-sso" went successful! Was there an update in the script?



Anyway the this is my environment
Platform: Windows 10 pro
Host: Word
Office version number:18.2008.12711.0______
Operating System: Microsoft Windows version 10.0.18363.1379___
Browser (if using Office on the web): ______

Many thanks,



Roelof Meijer




Van: Nisarg Kinariwala - MSFT <notifications@github.com>
Verzonden: dinsdag 16 februari 2021 21:01
Aan: OfficeDev/office-js-docs-pr <office-js-docs-pr@noreply.github.com>
CC: Roelof Meijer <roelof.meijer@live.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [OfficeDev/office-js-docs-pr] npm run configure-sso fails with error: Unable to determine if user is tenant admin (#2503)


@Roleofm<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FRoleofm&data=04%7C01%7C%7C517e8e27ef134fda1cd608d8d2b594b7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637491024609411264%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=jvpZckVovU8KakoQV%2FOv5Yq1oCKd6EjsPkSEbnfY35Q%3D&reserved=0> - Thank you for posting a question. Can you please provide these additional details?

Your Environment
Platform: ______
Host: Word
Office version number:______
Operating System: ______
Browser (if using Office on the web): ______

-
