### ISSUE TITLE
Doesnt provide a linkt to a tutorial showing how to publish the various add-ins to MS Store

### ISSUE THREAD

**Issue by stewa11** [OfficeDev/office-js-docs-pr#2504]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2677af5b-e9b8-f962-25ce-8aa285977c90
* Version Independent ID: c31c7ed9-0a0a-7a65-0d1b-70d6a8b33994
* Content: [Deploy and publish Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/publish/publish)
* Content Source: [docs/publish/publish.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/publish/publish.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for raising this issue @stewa11. 

@mscharlock, could you please investigate the discoverability of the Store publishing docs?

**Comment by stewa11** [comment]
Hi Alex,
I am particularly interested in how to publish MS-Project Add-In.
A tutorial could cover a very basic Visual Studio project template, publish. Visible in MS store.

Please note that I have successfully published UWP Windows 10 App to MS Store.

When in MS Project, you can see other published add-in in MS-Store. That is the end result I am looking for.

Happy to support this action.

Stew

**Comment by AlexJerabek** [comment]
@stewa11 Is this the information you're looking for? [Make your solutions available in Microsoft AppSource and within Office](https://docs.microsoft.com/en-us/office/dev/store/submit-to-appsource-via-partner-center). I don't think there's anything different between Project and the other Office applications in terms of store submissions, but @mscharlock can help verify.

**Comment by stewa11** [comment]
In UWP, it’s right click publish to get your App into Windows Store. But there is no MS Store option in Project Add-in project to publish to MS Store.
Hence my suggestion for a clear tutorial please.

**Comment by AlexJerabek** [comment]
You can find a step-by-step guide to publishing an Office Add-in here: https://docs.microsoft.com/en-us/office/dev/store/add-in-submission-guide

The earlier link I provided gives instructions for getting a developer account and handling settings in Partner Center. Here's the starting instructions:

> - [Create a developer account](https://partner.microsoft.com/dashboard/account/v3/enrollment/introduction/office). After you create your account, it goes through an approval process.
>  - For details about the registration process, see [Opening a developer account](https://docs.microsoft.com/en-us/office/dev/store/open-a-developer-account).
>  - For details about managing settings and additional users in your Partner Center account, see [Manage account users](https://docs.microsoft.com/en-us/office/dev/store/manage-account-settings-and-profile).
>- [Submit your solution to Microsoft AppSource via Partner Center](https://docs.microsoft.com/en-us/office/dev/store/use-partner-center-to-submit-to-appsource).

Is that the information you're looking for?

**Comment by mscharlock** [comment]
I'm going to assume that this issue can be closed, but @stewa11 let us know if it should be reopened with a comment. Thanks!

**Comment by stewa11** [comment]
michelle, i could only publish my add in if i have a none public email. my add in is free and it helps all small businesses around the world.

please help me publsih my add in

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by mscharlock** [comment]
Hi @stewa11 - Unfortunately we require a business email for the publishing of add-ins, it is just part of the rules. I know it is a sore point for people, so I will pass along the feedback that this is a problem to our program managers. Again, sorry I am unable to help.

**Comment by mscharlock** [comment]
I'm going to close this issue but let me know if you encounter any other issues. Thank you!
