### ISSUE TITLE
Usage scenario questions for the removeAttachmentAsync function

### ISSUE THREAD

**Issue by clavx** [OfficeDev/office-js-docs-pr#2514]
About the following sentence

> You should only remove attachments that the same add-in has added in the same session. Similar to the `addFileAttachmentAsync` and `addItemAttachmentAsync` methods, `removeAttachmentAsync` is an asynchronous method.

https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/add-and-remove-attachments-to-an-item-in-a-compose-form#remove-an-attachment

Is this linked to the description below?

>  Note
> As a best practice, you should use the attachment ID to remove an attachment only if the same add-in has added that attachment in the same session. In Outlook on the web and mobile devices, the attachment ID is valid only within the same session. A session is over when the user closes the add-in, or if the user starts composing in an inline form and subsequently pops out the inline form to continue in a separate window.

https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/add-and-remove-attachments-to-an-item-in-a-compose-form#attach-a-file-or-outlook-item

It's in the section about how to remove and I'm confused, so let me check if my understanding of the following is correct.
- This description is a reminder that the value of the ID obtained by `addFileAttachmentAsync` changes for Outlook on the web and mobile devices.
- When the session changes, it is expected that the `getAttachmentsAsync` function will be used to reacquire the ID and the `removeAttachmentAsync` function will be used.
- As a concrete case, using the On-Send function to remove all attachments is a perfectly fine and expected usage scenario.

If this understanding is correct, it would be great if the documentation could be clearer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03b32859-121b-cab9-78b9-923fd57628be
* Version Independent ID: c7ac8b7f-0b2a-9389-8d12-8aa0c87817ac
* Content: [Add and remove attachments in an Outlook add-in - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/add-and-remove-attachments-to-an-item-in-a-compose-form)
* Content Source: [docs/outlook/add-and-remove-attachments-to-an-item-in-a-compose-form.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/outlook/add-and-remove-attachments-to-an-item-in-a-compose-form.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @clavx, 

Thank you for raising this issue with the documentation. @ElizabethSamuel-MSFT and @exextoc, could you please help confirm if this information is correct and help update the documentation?

**Comment by ElizabethSamuel-MSFT** [comment]
@clavx Thanks for asking about this. We're working on updating the article so expect a PR on this soon.

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@clavx We've updated the article to provide clarification on the points you've raised. We expect to publish soon but in the meantime do take a look at the pull request and let us know if there are still areas of confusion.

Thanks.
