### ISSUE TITLE
Word on the Web does not seem to support Svg as indicated

### ISSUE THREAD

**Issue by theboyknowsclass** [OfficeDev/office-js-docs-pr#2515]
[Enter feedback here]

i receive an error -> Action failed with error: The enumeration isn't supported in the current host application.

https://gist.github.com/7fccdcd27f776d8a5468877b5b544d5d

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e311eed-7b47-ea60-6698-87193a50beef
* Version Independent ID: 1e0f5de4-d4e3-cc00-81bd-52b4d332fae6
* Content: [Image Coercion requirement sets - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/image-coercion-requirement-sets)
* Content Source: [docs/reference/requirement-sets/image-coercion-requirement-sets.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/requirement-sets/image-coercion-requirement-sets.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @theboyknowsclass, 

I tried out your gist in ScriptLab and successfully inserted the SVG. Could you please share which build of Word you are using? You can find that information under **File** > **Account**.

![image](https://user-images.githubusercontent.com/38896772/108536975-e9025280-7291-11eb-9799-976e9bf728ba.png)

**Comment by theboyknowsclass** [comment]
Hi Alex, thanks for the quick response this is for Word on the Web as below ->

[cid:image001.png@01D706E2.68B9EDB0]



Returns -> Action failed with error: The enumeration isn't supported in the current host application.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by theboyknowsclass** [comment]
![image](https://user-images.githubusercontent.com/2139941/108537910-11ac3b80-72d6-11eb-8bd8-a270f076e1a9.png)

**Comment by AlexJerabek** [comment]
Thanks for the information @theboyknowsclass. It looks like `ImageCoercion 1.2` is not supported by Word on the web. If you change the `getApiSupport` method to the following, you'll get conformation:

````
function getApiSupport() {
  var apiVersion;
  var apiName;
  apiName = "ImageCoercion";
  apiVersion = "1.2";

  console.log(`${apiName} ${apiVersion} isSupported: ${ Office.context.requirements.isSetSupported(apiName, apiVersion)}`);
}
```

This means the documentation on this requirement set is likely inaccurate. I'll confirm with the product team and update things accordingly. I'll also check if there are plans to expand the SGV import feature to this platform.

**Comment by theboyknowsclass** [comment]
many thanks!  we'd love to know the timeline (and if this support is also coming to Excel Web)

is there a forum for these types of questions?

**Comment by AlexJerabek** [comment]
[UserVoice](https://officespdev.uservoice.com/) is the best place to post feature requests. There, the community can upvote needed features and we prioritize based on those needs. We also have a [monthly community call for Office Add-ins](https://aka.ms/officeaddinscommunitycall) on the second Wednesday of every month. That's a great forum for chatting with the product team. Finally, I believe @AbidRahman-MSFT is gathering Word-specific needs from the developer community, so I'll tag him for a response.

**Comment by theboyknowsclass** [comment]
thanks @AbidRahman-MSFT would love to liaise with you to talk about my company's requirements going forward!

**Comment by theboyknowsclass** [comment]
@AlexJerabek it would also be amazing to have the contacts for Excel and Powerpoint, as we are targetting integrations with all these products going forward (moving from our existing C# Addins)

**Comment by AlexJerabek** [comment]
@theboyknowsclass, @keyur32 would be the person to talk to about your overall add-ins story. That community call will also be a great resource to connect with the product team.

**Comment by theboyknowsclass** [comment]
thanks, this has been very helpful!

**Comment by AbidRahman-MSFT** [comment]
Hey @theboyknowsclass , I would love to learn more about your experience creating a Word add-in and blockers/challenges you've been facing, can you please fill out the following survery: https://aka.ms/WordExtensibilitySurvey and we can follow up through email. Thanks.

**Comment by AlexJerabek** [comment]
The docs have been updated to properly reflect SVG support as part of #2516. I'll close the issue now.
