### ISSUE TITLE
I tried to test code sample from the page.

### ISSUE THREAD

**Issue by JerryXBear** [OfficeDev/office-js-docs-pr#2526]
[Enter feedback here]
I tried to test code sample from the page, but it doesn't work that  "BASICCUSTOMFUNCTION.GETRANGEVALUE threw an error: ReferenceError: 'Excel' is not defined"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fe047a0-5f60-f407-2ad0-7f4cc8e52082
* Version Independent ID: f2ebc9bd-25f6-cfc2-dbbe-d0090096f656
* Content: [Call Microsoft Excel APIs from a custom function - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/call-excel-apis-from-custom-function)
* Content Source: [docs/excel/call-excel-apis-from-custom-function.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/call-excel-apis-from-custom-function.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for reporting this @JerryXBear. 

@alison-mk, can you please take a look?

**Comment by alison-mk** [comment]
Hi @JerryXBear, thank you for submitting an issue! I did some testing, and the sample on this page doesn't work with Script Lab (with Script Lab, I encountered the same ReferenceError as you). The Excel.RequestContext API described on this page only works when you have a shared JavaScript runtime set up. See [Configure your Office Add-in to use a shared JavaScript runtime](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/configure-your-add-in-to-use-a-shared-runtime) to learn more. 

To avoid this confusion in the future, I've updated the [Call Microsoft Excel APIs from a custom function](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/call-excel-apis-from-custom-function) article to include notes about the shared runtime requirement. This update is currently in a PR and will be live soon, so I will close this issue. 

Please let us know if you have any additional questions. 

Thanks again, 
Alison
