### ISSUE TITLE
Debugging not working and getting stuck when trying to attach to Excel Desktop

### ISSUE THREAD

**Issue by mwchan** [OfficeDev/office-js-docs-pr#2527]
## Article URL
https://docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-with-vs-extension

## Issue
Hi,

I cannot get debugging to work when following the example from https://docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-with-vs-extension. 

- I have VS Code running as admin.
- I have the Office Debugger extension installed.
![image](https://user-images.githubusercontent.com/13030742/109456368-a6abf300-7a93-11eb-864d-d0258d12de75.png)
- I generated a clean sample using `yo office` (React, Typescript & Excel)
- I have the following config in launch.json
![image](https://user-images.githubusercontent.com/13030742/109455719-2a64e000-7a92-11eb-8335-187b95a76079.png)
- Version of Excel - ![image](https://user-images.githubusercontent.com/13030742/109455762-4072a080-7a92-11eb-80ae-3dd0377eabe4.png)
- Version of Windows 10 - ![image](https://user-images.githubusercontent.com/13030742/109455799-5718f780-7a92-11eb-9558-bd96c84fcea1.png)

When doing F5 and launching the debugger console, after opening the task pane, it is getting stuck at `→ To target: "{\"id\":5,\"method\":\"Runtime.run\"}"` before timing out.

Full trace:
![image](https://user-images.githubusercontent.com/13030742/109455930-ae1ecc80-7a92-11eb-8d0a-9a1f7dbc8e83.png)

**Comment by AlexJerabek** [comment]
Thanks for reporting this @mwchan. 

@mscharlock, can you please investigate?

**Comment by mwchan** [comment]
Just wondering if there are any updates.

**Comment by mscharlock** [comment]
Hi @mwchan - I am coordinating with our engineers to figure out why this is not working (we are able to repro). Thanks for being patient during the delay. :)

**Comment by mwchan** [comment]
Thanks for the info.

**Comment by millerds** [comment]
In the launch.json can you change "office-addin" to "edge" and see if that works?

**Comment by mwchan** [comment]
Hi Darren,

Edge does work. For some reason, both Edge and the original "office-addin"
now works. Is this issue intermittent? Any ideas what could have caused it
to stop working?

Thanks!

**Comment by millerds** [comment]
I can't say what happened.  I'm guessing something in the templates got corrected from when you first logged this issue (which was before I was on the project).  Let us know if you run into something like this again.

**Comment by aafvstam** [comment]
There is a lot going on (moving parts) ... I have been looking into this a lot lately. Much of it depends on the WebView used and other context related things like the version of the debug package (office-addin-debugging) version used in your package.json.

What is your output of:
npx office-addin-dev-settings webview .\manifest.xml
in your terminal?

When you set it to "edge" these days with the latest debug package you get EdgeChromium:

![image](https://user-images.githubusercontent.com/5305682/116938744-8bb05780-ac6b-11eb-9ba0-52573df1931d.png)

**Comment by elegault** [comment]
I'm having some many issues with VS Code and WebStorm - on multiple machines - trying to debug add-ins on multiple projects (including basic yo-office generated add-ins to test from scratch) that I'm not even sure where to start.  This isn't even counting the new issues with Edge WebView2 crashing within five seconds - which wasn't happening _last month_...  I'll get back here at some point or post a new issue.  But please, somebody consider creating a new, a start-to-finish tutorial on setting up a complete dev environment in VS Code with deep instructions on launch.json, package.json, tasks.json, debug configurations, necessary plugins, configuration of plugins, scripts for launching ALL Office apps - desktop AND online - so we can just do our jobs as developers instead of being DevOps engineers that our clients hate paying for.

**Comment by jmayermsi** [comment]
> Hi @mwchan - I am coordinating with our engineers to figure out why this is not working (we are able to repro). Thanks for being patient during the delay. :)

Can you update the status on this @mwchan? This would be highly appreciated

**Comment by mwchan** [comment]
Hi jmayermsi,

I am sorry, I thought I have updated that

*Edge does work. For some reason, both Edge and the original "office-addin"
now works. Is this issue intermittent? Any ideas what could have caused it
to stop working?*

I can't get it to "not" work at this point. It's as if the issue fixed
itself. Is there anything else that I have missed or you would like to do?

**Comment by mscharlock** [comment]
Hi @mwchan - Yeah, I think the latest updates have solved this issue - but let me know if you need anything else by commenting on this thread. I'll close for now but if you leave a comment I can reopen and investigate. Thanks!
