### ISSUE TITLE
Authentication error: "Authorization has been denied for this request."

### ISSUE THREAD

**Issue by binhnguyen1984** [OfficeDev/office-js-docs-pr#2539]
## Article URL

https://docs.microsoft.com/en-us/office/dev/add-ins/develop/create-sso-office-add-ins-aspnet
## Issue

 I follow the instruction in the above link, but I got the error: "Authorization has been denied for this request." when trying to make a call to the api "api/values". 
When I removed the [Authorize] attribute from the corresponding controller, I saw that ClaimsPrincipal.Current was empty and the code that gets addinScopes just threw an exception. Can someone give me a hint on how to solve this issue?

**Comment by AlexJerabek** [comment]
Hi @binhnguyen1984, 

Thanks for raising this issue. @davidchesnut, can you please investigate?

**Comment by Max1992** [comment]
Hello all,

Works for me with this configuration
var authConfig = {
    clientId: "...",
    scopes: "**openid**",
    redirectUrl: ".."
};

**Comment by binhnguyen1984** [comment]
@Max1992 : This does not work my case study. But anyway, I have found a simple fix in the meantime.

**Comment by Rick-Kirkham** [comment]
@Max1992 Where do you see an `authConfig` variable in this project? It is not in the article nor in the Complete version of the sample on GitHub.

**Comment by Max1992** [comment]
Hello all, 
sorry, was my fault. I was working on [this](https://github.com/OfficeDev/Outlook-Add-in-SSO) project and i had the similar problem.
Maybe your project might have the same problem

**Comment by davidchesnut** [comment]
Hi @Max1992,

We updated the Outlook SSO sample recently and moved it here: https://github.com/OfficeDev/PnP-OfficeAddins/tree/main/Samples/auth/Outlook-Add-in-SSO. Can you let use know if you are still seeing any issues with this sample, or the documentation? 

Thanks!
