### ISSUE TITLE
Package not found error.

### ISSUE THREAD

**Issue by mdagar** [OfficeDev/office-js-docs-pr#254]
When running following command from package manager console gets error package not found.
command:
Install-Package Microsoft.Identity.Client -Version 1.1.1-alpha0393 -Source https://www.myget.org/F/aad-clients-nightly/api/v3/index.json

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93c00914-b10b-632d-83a9-31a92b480312
* Version Independent ID: 420a6dfe-d17e-1e32-f25b-e6a0daac2101
* Content: [Create an ASP.NET Office Add-in that uses single sign-on](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/create-sso-office-add-ins-aspnet)
* Content Source: [docs/develop/create-sso-office-add-ins-aspnet.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/create-sso-office-add-ins-aspnet.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @mdagar,
Thanks for reporting this issue. I successfully repoed it and will investigate with our engineering team to find a solution.

**Comment by AlexJerabek** [comment]
Hi @mdagar,

It looks like the alpha version is no longer supported. The latest MSA preview is here: https://www.nuget.org/packages/Microsoft.Identity.Client/1.1.4-preview0002

Can you please run the following command in the package manager and let me know if that fixes your issue?
`Install-Package Microsoft.Identity.Client -Version 1.1.4-preview0002`

Thanks!

**Comment by AlexJerabek** [comment]
Hi @loflet, 

Thank you for confirming the updated package works. I have created [PR 264](https://github.com/OfficeDev/office-js-docs-pr/pull/264). I'll close the issue when that gets merged.
