### ISSUE TITLE
Issue making multiple calls

### ISSUE THREAD

**Issue by LiamSolDev** [OfficeDev/office-js-docs-pr#2546]
Hi,

I have been working through the tutorials and have reached a dead end when it comes to expanding the solution to make multiple calls.

I followed the following tutorials to produce the add-in and connect to Graph and edit it.
https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/sso-quickstart
https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/sso-quickstart-customize

I have not been able to find a way to take the SSO example set up through Yeoman and expand it to make multiple different calls as I cannot understand how all the parts of the Office-Addin-SSO fit together and how someone would customise to make multiple calls from the application or to make a post request with a body.

Any assistance would be appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3020ff5d-ee3b-976b-f1ad-0ed378fdb47b
* Version Independent ID: 5de0010a-6435-154b-a7fd-fd2ea05ebc0b
* Content: [Use the Yeoman generator to create an Office Add-in that uses SSO - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/sso-quickstart)
* Content Source: [docs/quickstarts/sso-quickstart.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/quickstarts/sso-quickstart.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by davidchesnut** [comment]
@LiamSolDev The [Office Add-in Node JS SSO sample](https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/auth/Office-Add-in-NodeJS-SSO) was updated to show a pattern for multiple calls. For example, [getFileNamelist](https://github.com/OfficeDev/Office-Add-in-samples/blob/5668fa059457f218570f4347f67d859383b5736e/Samples/auth/Office-Add-in-NodeJS-SSO/Complete/public/javascripts/ssoAuthES6.js#L26) calls the server REST API to get up to 10 filenames from OneDrive. [handleGetFileNameResponse](https://github.com/OfficeDev/Office-Add-in-samples/blob/5668fa059457f218570f4347f67d859383b5736e/Samples/auth/Office-Add-in-NodeJS-SSO/Complete/public/javascripts/ssoAuthES6.js#L43_) handles the response from the REST API (the returned 10 filenames).

You can extend this pattern to call any REST API you want to add. Always have a caller, and a response handler using the pattern shown in this code. Will be rolling out this pattern to the other SSO samples as well.

Hope this helps,
David
