### ISSUE TITLE
Office 365 Business

### ISSUE THREAD

**Issue by rbernardini** [OfficeDev/office-js-docs-pr#255]
I can't get the sample code to run. Excel shows #NAME? in formulas using custom functions. I don't see customfunction.js loading in my http server log. 
It looks like I don't have Office Insider features.
I'm using Office 365 Business, Monthly Channel (Targeted). Up to date (Version 1807 build 10325.20064). As per the documentation I should have the same functionality as an Office Insider which I can't get for this edition.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94ad7803-d4f7-a700-7c7f-204cd8f34e4a
* Version Independent ID: 9c485bae-cab1-bdad-4c8e-baad2b12b22d
* Content: [Create custom functions in Excel (Preview)](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-overview)
* Content Source: [docs/excel/custom-functions-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/custom-functions-overview.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for reporting this @rbernardini. I think @keyur32 should be able to tell you if custom functions are in this build or if the documentation is wrong.

**Comment by AlexJerabek** [comment]
Hi @rbernardini,

We have updated the customer functions samples, as per the discussion in https://github.com/OfficeDev/office-js-docs-pr/issues/258. 
Please try the samples again and reopen this issue if you still encounter problems.
