### ISSUE TITLE
What changes are needed for deployment to a server?

### ISSUE THREAD

**Issue by gullbyrd** [OfficeDev/office-js-docs-pr#2550]
This page and project are very helpful. However, there needs to be a section detailing what, if anything, needs to change when moving the app from Localhost to a server. I assume any reference to "Localhost:44355" needs to be changed to reflect the name of the server URI, but the registration process requires me to use "localhost:44355" in the Application ID URI. Even the server side code in the ValuesController hardcodes "localhost:44355". Can this be correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93c00914-b10b-632d-83a9-31a92b480312
* Version Independent ID: 420a6dfe-d17e-1e32-f25b-e6a0daac2101
* Content: [Create an ASP.NET Office Add-in that uses single sign-on - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/create-sso-office-add-ins-aspnet)
* Content Source: [docs/develop/create-sso-office-add-ins-aspnet.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/create-sso-office-add-ins-aspnet.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
You are correct that the domain needs to be changed in the manifest and the AAD registration portal. I've added a section to the end of the article, it should be published in a few days. Also, I moved the hardcoded `localhost:44355` from the executable code to the web.config. The same change was made in the "Complete" version of the sample.

**Comment by gullbyrd** [comment]
Thanks again for your help. Now I'm having an issue with the accessToken
that is received after login. Here's the message I get:

{"type":"dialogMessageReceived","message":"{\"status\":\"
success\",\"accessToken\":\"EwBwA8l6BAAU6k7+XVQzkGyMv7VHB/
h4cHbJYRAAAS3hSSfQjbyNCWl8Ud18E6uc9pxIXg5r260rdbpN+
GfUTXqSlcWCbRYV7zeaPqV1wKHdg6+HQ7Mo1whjFo35hroCQ/+
Ic9UbQ7tjRyxr05fx2moMhsXerMi+NOMNw4JdRLrBi6oJWEpda/
JqYFWxiIBvIW7AtfibV58Bbi3oEzNmNOKLu+10KDXNMa5MDaLofNIKPHJmUhPSaql8
O1h2bDyNcrnRCvunVU7Ja2w9srTEqYmjWWh9ouE8GfGbaBHlR2saWbbks9Rn
yyDggyavjQxVqrsTNfBOvPU+GRxGXm2J7H1o5oMXCOjt4nxMGq0W73
lCTmmGtbCroARdIw9YkSIDZgAACD2ZH8P3Vwn7QAJN0ac2EUUuIb9FIgy4Ax
93agdskvJTnlKe3thrZeWhKMMJfG1v974bemZ6SOkz1MwZMJhNx2cbuaKoCTPq656RBW+
F6Q34X6tGWVNXGzWxPlcJj5gfN4lMwSchU/ZvhL0ojUR1889WcMc+
4DoowbPU2xrr81dzbdeFLrDw6LLTrJOKRB7o+M2K6ZgwgtfcHACtVYzolGCfkbTO9ME
QxVpnFjfICJjELMKGaMIVLCTpm4vtBRsoCrmUxDoZpaQFemQlcL0s8oLVb6L
GP8mBIZt4FXXFhvXy4YXbgvCA2ILR9l2AqjvV304mLzasW535vkIMjnpbC0H
z3MeEXOZSa7KyQn36gvDsYqSOxm0qm0aBTvmMwaBDHckxsOTeSQB2D4SY4OS
5soQFgRfBU1O1durX6hFZXDj+O2qT9DpZwHNC8Gl5dV1NNu/D5+
6EBR/tq05l6/SM/6OLW7tQlNlLCvw+e1Xu13Rj8Im6yjCU0e/QsfX/
0UNcyHCZLKaL20B2rEI62SnbMGxZQ13/G+/NAh9BOWAHxx8kIw/
FahH6lZhWG5k84PMcaf1EPhCTZz0Z8LLhDE+aFIoVD+xM2NeSqnR5Eh+
thYOCNHrFxgMf3NItsHiWCT6d7uatvnggWFcShZLeC152Uu0tkeqRAjYicX7
GvcAigxqA22wMCdf/3bahJKp6VfisY1YUjR4pDSa5ko4YmgIorp9TB51EZ2B+j0j+l4r+
CjZOEJHSDbQhHsJ7NM5LsIjdqM9BnqoPV8Z1gEqGAg==\"}"}

My understanding is that the accessToken is a JWT, but I've tried a couple
of JWT decoders (including one from MS) and they both say the token is
invalid. What is this format?

**Comment by Rick-Kirkham** [comment]
Since your new issue isn't with the documentation, it should be asked on the [office-js](https://github.com/OfficeDev/office-js/issues) repo. You'll get faster action that way.
