### ISSUE TITLE
Custom XML in article description

### ISSUE THREAD

**Issue by heebinho** [OfficeDev/office-js-docs-pr#2555]
_"WordApi 1.3 added more support for content controls, **custom XML**, and document-level settings."_

For me it looks like the mentioned support for custom XML is not part of 1.3 and still in preview.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bee018a-98f8-befd-4a0f-c9211045af05
* Version Independent ID: 59c3007a-cfd3-7da3-a5ed-85e5fbf6c650
* Content: [Word JavaScript API requirement set 1.3 - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/word-api-1-3-requirement-set)
* Content Source: [docs/reference/requirement-sets/word-api-1-3-requirement-set.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/requirement-sets/word-api-1-3-requirement-set.md)
* Product: **word**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @heebinho, 

Thanks for pointing out this discrepancy. Custom XML for Word-specific APIs is still in preview. We'll update the documentation accordingly.

If you need to use Custom XML in your Word solution, you can use the Common APIs. You can learn more about that and see a sample [here](Working with custom XML parts using the CustomXmlParts and CustomXmlPart objects). If that functionality is not enough, please over to [UserVoice](https://officespdev.uservoice.com/), where feature requests can be made or upvoted.

**Comment by heebinho** [comment]
Hi @AlexJerabek,

Thanks for mentioning the Common APIs. Pretty happy that we already have access to the Custom XML parts there.
