### ISSUE TITLE
example doesn't work

### ISSUE THREAD

**Issue by gspagoni** [OfficeDev/office-js-docs-pr#2558]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fde53b2d-39f8-5b6d-5e37-068b4d93f049
* Version Independent ID: 9c7ff3ef-a188-bd28-65bb-1d620d4a8842
* Content: [Use the Outlook REST APIs from an Outlook add-in - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/use-rest-api)
* Content Source: [docs/outlook/use-rest-api.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/outlook/use-rest-api.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

I'm trying to test the example but it doesn't work, it complains about the access token. what I would like to achieve is calling an API to enable the ouf of office from task pane because I want to invoke also another API that enable out of office for another application. so I would like to create an adding that enable out of office both for outlook and for my application but I cannot find any API to enable ooo for outlook. i would avoid to sign-in as I'm already logged with my user. any help? thanks

**Comment by AlexJerabek** [comment]
Hi @gspagoni,

Thanks for reporting this access token issue. @ElizabethSamuel-MSFT, can you please investigate?

**Comment by ElizabethSamuel-MSFT** [comment]
@gspagoni Sorry that you're facing issues with this. However, can you provide some more details to help us repro? For example, what error are you getting re: the access token? Can you share your sample code and manifest? Which client/platform are you testing with (Windows, Mac, browser, etc)? Which Exchange version are you pointing to (Exchange Online, on-premises)?

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@gspagoni As for an API to set "out of office", I also believe we don't have such an API. I've also tagged this issue as feature request so we can track. @JuaneloJuanelo FYI

**Comment by lindalu-MSFT** [comment]
@ElizabethSamuel-MSFT We should move this feature request to office-js so we can track it with the Feature Request tag there.

**Comment by ElizabethSamuel-MSFT** [comment]
@lindalu-MSFT I'll move to office-js to track the feature request portion after we resolve the issue with REST API example, if possible.

**Comment by gspagoni** [comment]
[My Office Add-in.zip](https://github.com/OfficeDev/office-js-docs-pr/files/6195382/My.Office.Add-in.zip)
thank you for your answer. I have attached my project created with yo generator
my goal as I said is to create an addon which set OOO for outlook and for another external application at the same time. ofc for outlook i don't want to authenticate with oauth2 because I'm already logged in, so I was looking for some API that return the token and pass it to the microsoft.grap API, but the token I can get from outlook.api is not compatible with microsoft.grap API, hope this clarify the scope. thank you

**Comment by ElizabethSamuel-MSFT** [comment]
@gspagoni Thanks for sharing this info.

@exextoc Can you take a look?

Thanks.

**Comment by exextoc** [comment]
@gspagoni - Currently there isn't an Office JS API that allows you to set a OOO message or get a token that can be used against Graph. The getCallbackToken API with isRest set to true that you use in your code only returns a token that can be used against a REST API endpoint, hence the error when using that token against a Graph API. That said, the REST token returned only has item and calendar level scopes, which means that it won't allow you to set OOO message for Outlook through the REST endpoint. To be able to use a Graph API, we recommend looking into authenticating the user with [SSO token](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/authenticate-a-user-with-an-sso-token).

**Comment by gspagoni** [comment]
Hello and thank you for your answer, I tried a piece of code that I read into the the page of the SSO token link


export async function run() {
  /**
   * Insert your Outlook code here
   */   


   try {
    let bootstrapToken = await OfficeRuntime.auth.getAccessToken();
    document.getElementById("token").innerHTML = bootstrapToken

    // The /api/DoSomething controller will make the token exchange and use the
    // access token it gets back to make the call to MS Graph.
    //getData("/api/DoSomething", bootstrapToken);
}
catch (exception) {
    if (exception.code === 13003) {
      document.getElementById("user").innerHTML = exception.code

      // SSO is not supported for domain user accounts, only
        // Microsoft 365 Education or work account, or a Microsoft account.
    } else {
        // Handle error
        document.getElementById("user").innerHTML = exception.message

    }
}

the response is the attached snapshot
![2021-03-29 17_40_01-Posta in arrivo - Giampaolo Spagoni@infor com - Outlook](https://user-images.githubusercontent.com/22134155/112862442-0ce95d00-90b6-11eb-8b4d-219367ad3211.png)

can you tell me how can I get a valid token that I can use with microsoft.graph API?
thank you
GS

**Comment by exextoc** [comment]
Could you share the exception.code that you are running into? Here's a link for reference to troubleshoot and identify the exception.code and what they mean: https://docs.microsoft.com/en-us/office/dev/add-ins/develop/troubleshoot-sso-in-office-add-ins

**Comment by gspagoni** [comment]
the error code is 13000

Modify the source files, then click Run.
Run 

13000

**Comment by exextoc** [comment]
Based on it being the 13000 error code, it's possible that:
- The version of Office does not support SSO. The required version is Microsoft 365 subscription, in any monthly channel.
- The add-in manifest is missing the proper WebApplicationInfo section. 

Could you share your Outlook build number and subscription channel? And make sure that WebApplicationInfo in the manifest.
Please also make sure that the prerequisite steps (e.g. Enable modern authentication, Register your add-in etc.) listed before the "Get SSO Token" instruction are taken care of: https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/authenticate-a-user-with-an-sso-token

**Comment by gspagoni** [comment]
![2021-04-01 10_47_01-Posta in arrivo - Giampaolo Spagoni@infor com - Outlook](https://user-images.githubusercontent.com/22134155/113268747-01757c00-92d8-11eb-9e33-2811d26b08fc.png)
attached the version of outlook

below the manifest file

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<OfficeApp xmlns="http://schemas.microsoft.com/office/appforoffice/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bt="http://schemas.microsoft.com/office/officeappbasictypes/1.0" xmlns:mailappor="http://schemas.microsoft.com/office/mailappversionoverrides/1.0" xsi:type="MailApp">
  <Id>92379c22-6ffc-4880-bd8a-dcb373bd09f9</Id>
  <Version>1.0.0.0</Version>
  <ProviderName>Contoso</ProviderName>
  <DefaultLocale>en-US</DefaultLocale>
  <DisplayName DefaultValue="My Office Add-in"/>
  <Description DefaultValue="A template to get started."/>
  <IconUrl DefaultValue="https://localhost:3000/assets/icon-64.png"/>
  <HighResolutionIconUrl DefaultValue="https://localhost:3000/assets/icon-128.png"/>
  <SupportUrl DefaultValue="https://www.contoso.com/help"/>
  <AppDomains>
    <AppDomain>https://www.contoso.com</AppDomain>
  </AppDomains>
  <Hosts>
    <Host Name="Mailbox"/>
  </Hosts>
  <Requirements>
    <Sets>
      <Set Name="Mailbox" MinVersion="1.1"/>
    </Sets>
  </Requirements>
  <FormSettings>
    <Form xsi:type="ItemRead">
      <DesktopSettings>
        <SourceLocation DefaultValue="https://localhost:3000/taskpane.html"/>
        <RequestedHeight>250</RequestedHeight>
      </DesktopSettings>
    </Form>
  </FormSettings>
  <Permissions>ReadWriteItem</Permissions>
  <Rule xsi:type="RuleCollection" Mode="Or">
    <Rule xsi:type="ItemIs" ItemType="Message" FormType="Read"/>
  </Rule>
  <DisableEntityHighlighting>false</DisableEntityHighlighting>
  <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides" xsi:type="VersionOverridesV1_0">
    <Requirements>
      <bt:Sets DefaultMinVersion="1.3">
        <bt:Set Name="Mailbox"/>
      </bt:Sets>
    </Requirements>
    <Hosts>
      <Host xsi:type="MailHost">
        <DesktopFormFactor>
          <FunctionFile resid="Commands.Url"/>
          <ExtensionPoint xsi:type="MessageReadCommandSurface">
            <OfficeTab id="TabDefault">
              <Group id="msgReadGroup">
                <Label resid="GroupLabel"/>
                <Control xsi:type="Button" id="msgReadOpenPaneButton">
                  <Label resid="TaskpaneButton.Label"/>
                  <Supertip>
                    <Title resid="TaskpaneButton.Label"/>
                    <Description resid="TaskpaneButton.Tooltip"/>
                  </Supertip>
                  <Icon>
                    <bt:Image size="16" resid="Icon.16x16"/>
                    <bt:Image size="32" resid="Icon.32x32"/>
                    <bt:Image size="80" resid="Icon.80x80"/>
                  </Icon>
                  <Action xsi:type="ShowTaskpane">
                    <SourceLocation resid="Taskpane.Url"/>
                  </Action>
                </Control>
                <Control xsi:type="Button" id="ActionButton">
                  <Label resid="ActionButton.Label"/>
                  <Supertip>
                    <Title resid="ActionButton.Label"/>
                    <Description resid="ActionButton.Tooltip"/>
                  </Supertip>
                  <Icon>
                    <bt:Image size="16" resid="Icon.16x16"/>
                    <bt:Image size="32" resid="Icon.32x32"/>
                    <bt:Image size="80" resid="Icon.80x80"/>
                  </Icon>
                  <Action xsi:type="ExecuteFunction">
                    <FunctionName>action</FunctionName>
                  </Action>
                </Control>
              </Group>
            </OfficeTab>
          </ExtensionPoint>
        </DesktopFormFactor>
      </Host>
    </Hosts>
    <Resources>
      <bt:Images>
        <bt:Image id="Icon.16x16" DefaultValue="https://localhost:3000/assets/icon-16.png"/>
        <bt:Image id="Icon.32x32" DefaultValue="https://localhost:3000/assets/icon-32.png"/>
        <bt:Image id="Icon.80x80" DefaultValue="https://localhost:3000/assets/icon-80.png"/>
      </bt:Images>
      <bt:Urls>
        <bt:Url id="Commands.Url" DefaultValue="https://localhost:3000/commands.html"/>
        <bt:Url id="Taskpane.Url" DefaultValue="https://localhost:3000/taskpane.html"/>
      </bt:Urls>
      <bt:ShortStrings>
        <bt:String id="GroupLabel" DefaultValue="Contoso Add-in"/>
        <bt:String id="TaskpaneButton.Label" DefaultValue="Show Taskpane"/>
        <bt:String id="ActionButton.Label" DefaultValue="Perform an action"/>
      </bt:ShortStrings>
      <bt:LongStrings>
        <bt:String id="TaskpaneButton.Tooltip" DefaultValue="Opens a pane displaying all available properties."/>
        <bt:String id="ActionButton.Tooltip" DefaultValue="Perform an action when clicked."/>
      </bt:LongStrings>
    </Resources>
  </VersionOverrides>
</OfficeApp>

**Comment by gspagoni** [comment]
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<OfficeApp xmlns="http://schemas.microsoft.com/office/appforoffice/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bt="http://schemas.microsoft.com/office/officeappbasictypes/1.0" xmlns:mailappor="http://schemas.microsoft.com/office/mailappversionoverrides/1.0" xsi:type="MailApp">
  <Id>92379c22-6ffc-4880-bd8a-dcb373bd09f9</Id>
  <Version>1.0.0.0</Version>
  <ProviderName>Contoso</ProviderName>
  <DefaultLocale>en-US</DefaultLocale>
  <DisplayName DefaultValue="My Office Add-in"/>
  <Description DefaultValue="A template to get started."/>
  <IconUrl DefaultValue="https://localhost:3000/assets/icon-64.png"/>
  <HighResolutionIconUrl DefaultValue="https://localhost:3000/assets/icon-128.png"/>
  <SupportUrl DefaultValue="https://www.contoso.com/help"/>
  <AppDomains>
    <AppDomain>https://www.contoso.com</AppDomain>
  </AppDomains>
  <Hosts>
    <Host Name="Mailbox"/>
  </Hosts>
  <Requirements>
    <Sets>
      <Set Name="Mailbox" MinVersion="1.1"/>
    </Sets>
  </Requirements>
  <FormSettings>
    <Form xsi:type="ItemRead">
      <DesktopSettings>
        <SourceLocation DefaultValue="https://localhost:3000/taskpane.html"/>
        <RequestedHeight>250</RequestedHeight>
      </DesktopSettings>
    </Form>
  </FormSettings>
  <Permissions>ReadWriteItem</Permissions>
  <Rule xsi:type="RuleCollection" Mode="Or">
    <Rule xsi:type="ItemIs" ItemType="Message" FormType="Read"/>
  </Rule>
  <DisableEntityHighlighting>false</DisableEntityHighlighting>
  <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides" xsi:type="VersionOverridesV1_0">
    <Requirements>
      <bt:Sets DefaultMinVersion="1.3">
        <bt:Set Name="Mailbox"/>
      </bt:Sets>
    </Requirements>
    <Hosts>
      <Host xsi:type="MailHost">
        <DesktopFormFactor>
          <FunctionFile resid="Commands.Url"/>
          <ExtensionPoint xsi:type="MessageReadCommandSurface">
            <OfficeTab id="TabDefault">
              <Group id="msgReadGroup">
                <Label resid="GroupLabel"/>
                <Control xsi:type="Button" id="msgReadOpenPaneButton">
                  <Label resid="TaskpaneButton.Label"/>
                  <Supertip>
                    <Title resid="TaskpaneButton.Label"/>
                    <Description resid="TaskpaneButton.Tooltip"/>
                  </Supertip>
                  <Icon>
                    <bt:Image size="16" resid="Icon.16x16"/>
                    <bt:Image size="32" resid="Icon.32x32"/>
                    <bt:Image size="80" resid="Icon.80x80"/>
                  </Icon>
                  <Action xsi:type="ShowTaskpane">
                    <SourceLocation resid="Taskpane.Url"/>
                  </Action>
                </Control>
                <Control xsi:type="Button" id="ActionButton">
                  <Label resid="ActionButton.Label"/>
                  <Supertip>
                    <Title resid="ActionButton.Label"/>
                    <Description resid="ActionButton.Tooltip"/>
                  </Supertip>
                  <Icon>
                    <bt:Image size="16" resid="Icon.16x16"/>
                    <bt:Image size="32" resid="Icon.32x32"/>
                    <bt:Image size="80" resid="Icon.80x80"/>
                  </Icon>
                  <Action xsi:type="ExecuteFunction">
                    <FunctionName>action</FunctionName>
                  </Action>
                </Control>
              </Group>
            </OfficeTab>
          </ExtensionPoint>
        </DesktopFormFactor>
      </Host>
    </Hosts>
    <Resources>
      <bt:Images>
        <bt:Image id="Icon.16x16" DefaultValue="https://localhost:3000/assets/icon-16.png"/>
        <bt:Image id="Icon.32x32" DefaultValue="https://localhost:3000/assets/icon-32.png"/>
        <bt:Image id="Icon.80x80" DefaultValue="https://localhost:3000/assets/icon-80.png"/>
      </bt:Images>
      <bt:Urls>
        <bt:Url id="Commands.Url" DefaultValue="https://localhost:3000/commands.html"/>
        <bt:Url id="Taskpane.Url" DefaultValue="https://localhost:3000/taskpane.html"/>
      </bt:Urls>
      <bt:ShortStrings>
        <bt:String id="GroupLabel" DefaultValue="Contoso Add-in"/>
        <bt:String id="TaskpaneButton.Label" DefaultValue="Show Taskpane"/>
        <bt:String id="ActionButton.Label" DefaultValue="Perform an action"/>
      </bt:ShortStrings>
      <bt:LongStrings>
        <bt:String id="TaskpaneButton.Tooltip" DefaultValue="Opens a pane displaying all available properties."/>
        <bt:String id="ActionButton.Tooltip" DefaultValue="Perform an action when clicked."/>
      </bt:LongStrings>
    </Resources>
  </VersionOverrides>
</OfficeApp>

**Comment by exextoc** [comment]
Based on your build number, it should support SSO. Just as a sanity check can you try calling isSetSupported('IdentityAPI', '1.3') and make sure it returns true.
You seemed to have pasted only a portion of the manifest, can you relink/upload the manifest?
Also again, please make sure that the prerequisite steps (e.g. Enable modern authentication, Register your add-in etc.) listed before the "Get SSO Token" instruction are taken care of: https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/authenticate-a-user-with-an-sso-token

**Comment by gspagoni** [comment]
attached the manifest
[manifest.zip](https://github.com/OfficeDev/office-js-docs-pr/files/6252181/manifest.zip)
thank you

**Comment by gspagoni** [comment]
Hi, i read the article you suggested above. i don't have the rights to register the add-in to the Azure AD, I'm not an IT admin, I'm a solution architect creating Demo. I'm aware of the security stack which is very important, but at the same time I thought once I'm logged in to use a SAML bearer token for my user to setup properties to my account, which seems to be very hard. as I said I'm looking for a simple way to setup the OOO for my user from an add-in using microsoft-graph API because from the same add-in i want to setup an OOO also for another application where now I must use the OAuth2.0 grant flow because I need to access another IDP to get the token. thank you

**Comment by exextoc** [comment]
To unblock your development and demo, you can create a development tenant through the [Microsoft 365 Developer Program](https://developer.microsoft.com/en-us/microsoft-365/dev-program). This will allow you to grant administrator consent to the add-in.

Does this unblock your scenario?

**Comment by gspagoni** [comment]
Hi , i read the MS 365 Developer Program and i tried to create an account using my company account, but I'm denied to switch to the admin center. see the attached snapshot, I think I can create a developer program with my own account but then how can I use it to authenticate add in for my company account?
![2021-04-06 10_22_49-](https://user-images.githubusercontent.com/22134155/113681613-73780780-96c2-11eb-9696-c6f036a9e075.png)

**Comment by exextoc** [comment]
You would log into this developer account [profile page](https://developer.microsoft.com/en-us/microsoft-365/profile) with the account you used to register for the program. And from there, you can setup a tenant (ending in onmicrosoft.com) with its own administrator account (also listed on that page) that can be used to access your developer tenant's admin page.

Typically a website will prompt you for which account you use to access the portal. You can also use different browser profiles to keep the two accounts separate.

If you need to demo using data from your company tenant, in that case, you would need to work your IT department to get your application access to that data. But if you can demo from the developer tenant, using test data, you could setup the application and add-in in that tenant. (Even in the case where you eventually deploy the application to your company tenant, you may find the developer tenant useful to test with your own data and setup).

**Comment by gspagoni** [comment]
can i add the account i used to register for the program in outlook client? in this case can I use it with the adding I'm trying to develop for setting OOO. thank you

**Comment by exextoc** [comment]
This program allows you to create a new email account to test with (you could use the automatically-created admin account, or use the admin account to create a test user within the developer tenant). Either of those accounts, you can add to Outlook. It's a fully-functioning M365 account. It can be used to develop add-ins for any application including Outlook.

For example, you can add the test user to your existing Outlook installation and manually set its out-of-office status, and also install your add-in and use it to set the out-of-office status (Outlook add-ins in particular are tied to a specific email account rather than the client).

The developer program doesn't make any changes to the account you used to register for it. Your personal or company account is only used to create or delete the developer tenant from the [profile page](https://developer.microsoft.com/en-us/microsoft-365/profile) I linked to. (You can also optionally install a sample pack from that page, which will populate the tenant with sample users and emails).

**Comment by gspagoni** [comment]
i cannot progress further with my company account
please close the issue
thank you
GS
