### ISSUE TITLE
Backend question for: Get the whole document from an add-in for Word or PowerPoint

### ISSUE THREAD

**Issue by DiegoSalazar** [OfficeDev/office-js-docs-pr#2562]
## Issue
I am having trouble merging Slices together. I follow [these docs](https://docs.microsoft.com/en-us/office/dev/add-ins/word/get-the-whole-document-from-an-add-in-for-word), using btoa() to encode each slice, the server then b64 decodes and concatenates the slices together but, like @nguruprasanna in [this issue](https://github.com/OfficeDev/office-js-docs-pr/issues/860), I get a large string starting with:
```
80,75,3,4,20,0,6,0,8,0,0,0,33,0,50,100,51,3,232,1,0,0,29,12,0,0,19,0,8,2,91,67,111,110,116,101,110,116,95,84,121,112,101,115,93,46,120,109,108,32,162,4,2,40,160,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
```
I write the above data to a .docx file but it is corrupted when trying to open in Word.

It's unclear from [the docs](https://docs.microsoft.com/en-us/office/dev/add-ins/word/get-the-whole-document-from-an-add-in-for-word) what the correct way to decode/merge these slices is in the backend. 

The link mentioned in the article is dead (https://support.microsoft.com/en-us/help/318425/how-to-send-and-receive-binary-documents-by-using-an-asp-net-web-servi)

## Article
https://docs.microsoft.com/en-us/office/dev/add-ins/word/get-the-whole-document-from-an-add-in-for-word

**Comment by ElizabethSamuel-MSFT** [comment]
@DiegoSalazar Thanks for raising this issue. As you may have seen in the related issue, we have an internal item tracking this work. However, we don't have any timeline yet for when this request may be created and published.

Thanks.

**Comment by DiegoSalazar** [comment]
I figured out the issue on my end. I was incorrectly packing/unpacking the byte array. 

In Ruby, I was doing `bytes = Base64.decode64(slice.data).split(?,).map(&:to_i)` and then writing those `bytes` directly to a file. But I was missing this step: `bytes.pack('C*')`
