### ISSUE TITLE
The schema is not clear enough since the xml element require order

### ISSUE THREAD

**Issue by VitorX** [OfficeDev/office-js-docs-pr#257]
1. The document about [Office app](https://dev.office.com/reference/add-ins/manifest/officeapp) element only list the element must contain. It is very helpful to troubleshoot issue if the document show the exact XML schema. 
2. To pass the XML verification, the **SupportUrl** have to include, however this element in the document is optional. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a89c40a2-3e90-a295-7375-6d52ba597808
* Version Independent ID: 8cd2f086-5c18-ee17-9ced-ffeba1de0b78
* Content: [Validate and troubleshoot issues with your manifest](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/troubleshoot-manifest)
* Content Source: [docs/testing/troubleshoot-manifest.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/troubleshoot-manifest.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
@VitorX 
For #1, we have a work item to document the required order the element must have. In the meantime, you can look at the actual XSD file that defines the schema: https://github.com/OfficeDev/office-js-docs-pr/tree/master/docs/overview/schemas
For #2: SupportUrl is required for add-ins that are submitted to AppSource. But there are other ways of distributing add-ins that don't require a SupportUrl, so it is defined as optional in the XSD.
