### ISSUE TITLE
Link to install webview2 does not work

### ISSUE THREAD

**Issue by splinter** [OfficeDev/office-js-docs-pr#2570]
## Article URL
https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins

## Issue

 The `Microsoft Edge WebView2 / Embed web content ... with Microsoft Edge WebView2` link is broken:

The page which is linked using the above text does not load:

https://developer.microsoft.com/en-us/microsoft-edge/webview2

I am receiving a 431  HTTP error code when accessing the page while logged into a Azure AD tenant (the link works in incognito mode).

**Comment by ElizabethSamuel-MSFT** [comment]
@splinter Thanks for raising this issue about the webview2 page.

@lindalu-MSFT Can take a look at this issue with the developer.microsoft.com page referenced here? Or assign to an appropriate person who can investigate?

Thanks.

**Comment by lindalu-MSFT** [comment]
I've tried this link on multiple browsers and cannot repro. The link opens fine for me. Perhaps it was a temporary outage or somethng.
