### ISSUE TITLE
Support for 'on send' hook in Desktop Outlook (Mac) New UI

### ISSUE THREAD

**Issue by cody-lettau** [OfficeDev/office-js-docs-pr#2571]
The documentation states that the new UI for Mac does not support the 'on send' feature, where we can run an add-in on each message send. This is pretty basic functionality that a lot of add-ins require, so I am curious when this will be supported and ready for use?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5580136-d9ce-515e-dee6-8fae1ba7a185
* Version Independent ID: 08f27b7b-71b5-5ec2-20e6-8390507f700e
* Content: [Compare Outlook add-in support in Outlook on Mac - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/compare-outlook-add-in-support-in-outlook-for-mac#new-outlook-on-mac-preview)
* Content Source: [docs/outlook/compare-outlook-add-in-support-in-outlook-for-mac.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/outlook/compare-outlook-add-in-support-in-outlook-for-mac.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@cody-lettau Thanks for asking about this.

@macOutlookExtensibility Can you take a look?

Thanks.

**Comment by exextoc** [comment]
@cody-lettau Thanks for asking this. We are planning release 'on-send' feature on New UI to Insiders beta by April end. You can get more details on Office Insiders from [here](https://insider.office.com/en-in/join/mac)

**Comment by cody-lettau** [comment]
@exextoc thanks for the update and pointing me to the Office Insiders page! I will keep an eye on this and am looking forward to being able to have our add-in work in the new UI!

**Comment by ElizabethSamuel-MSFT** [comment]
@cody-lettau The new Mac UI preview now supports the on-send feature.

As such, I'll go ahead and close this but if you face any further issue, let us know by creating a new issue or replying on this thread as appropriate.

Thanks.
