### ISSUE TITLE
64 px required, not just recommended

### ISSUE THREAD

**Issue by lucalytton** [OfficeDev/office-js-docs-pr#2572]
We tried to upload a manifest file and it was rejected because it stated that the 64 px icon was missing – please indicate on this page that it is required, and not just recommended – thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60534f1a-0d99-62cf-08d5-ff7770ee1b86
* Version Independent ID: 537fe362-b29a-28a8-8d51-79a05b5f0107
* Content: [Fresh style icon guidelines for Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/design/add-in-icons-fresh)
* Content Source: [docs/design/add-in-icons-fresh.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/design/add-in-icons-fresh.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@lucalytton Thanks for pointing out this issue. We'll take a look and update the documentation as needed.

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@lucalytton The 64 px size is only required if the image represents the add-in's icon (in manifest elements [IconUrl](https://docs.microsoft.com/office/dev/add-ins/reference/manifest/iconurl) or [HighResolutionIconUrl](https://docs.microsoft.com/office/dev/add-ins/reference/manifest/highresolutioniconurl)) depending on if it's a mail/Outlook add-in or a content or task pane add-in. We're in the process of updating the documentation (see PRs referenced). We also welcome your feedback on the updates we're proposing.

Thanks.

**Comment by lucalytton** [comment]
Hi @ElizabethSamuel-MSFT : thanks for this. We didn't actually specify this as the IconUrl or HighResolutionIconUrl (we specified 80 px). Should we have?

Cheers

**Comment by ElizabethSamuel-MSFT** [comment]
> Hi @ElizabethSamuel-MSFT : thanks for this. We didn't actually specify this as the IconUrl or HighResolutionIconUrl (we specified 80 px). Should we have?
> 
> Cheers

@lucalytton IconUrl and HighResolutionIconUrl have specific and different size requirements and depends on if the add-in is Mail/Outlook or content/task pane. For sure, the IconUrl or the HighResolutionIconUrl should reference a 64 px image. I think the changes in [this pull request](https://github.com/OfficeDev/office-store-docs/pull/352) give a good summary of the requirements. See the "Create an icon for your add-in" section of the article:
- [GitHub page](https://github.com/OfficeDev/office-store-docs/blob/master/docs/create-effective-office-store-listings.md#create-an-icon-for-your-add-in)
- [docs.microsoft.com page](https://docs.microsoft.com/office/dev/store/create-effective-office-store-listings#create-an-icon-for-your-add-in) (once publish happens, which should be soon)

Thanks.

**Comment by lucalytton** [comment]
Understood, I think we managed to sort it out now! Thank you for your help.
