### ISSUE TITLE
Command listed in this page seems to be wrong when create add in project with parameters

### ISSUE THREAD

**Issue by Yan-corps** [OfficeDev/office-js-docs-pr#2575]
[Enter feedback here]
When create add in project with yo office, the command should be 
`yo office --projectType excel-functions --name 'Excel shared runtime add-in' --host excel --js true`
your codes in this page seems to lose a "true" in the end, which cannot apply these parameters in this command, and create an empty project.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a1bb1ec-f7c0-61c7-bd50-4018a2726e3a
* Version Independent ID: dabd68f4-f474-1f01-0022-b2fe55eaafa3
* Content: [Configure your Office Add-in to use a shared JavaScript runtime - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/configure-your-add-in-to-use-a-shared-runtime#give-us-feedback)
* Content Source: [docs/develop/configure-your-add-in-to-use-a-shared-runtime.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/configure-your-add-in-to-use-a-shared-runtime.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@Yan-corps Thanks for pointing out this issue.

@davidchesnut Can you take a look?

Thanks.

**Comment by davidchesnut** [comment]
@Yan-corps thanks for noting this! I submitted a PR that fixes the command line options.
