### ISSUE TITLE
Shared Runtime for Desktop now runs on Webview2?

### ISSUE THREAD

**Issue by wynntee** [OfficeDev/office-js-docs-pr#2584]
Hi, I noticed today that the Shared Runtime on Windows desktop now runs on Webview2 instead of IE11. This is great news. When did this happen? And what are the system requirements (e.g. Office version)? The documentation should be updated accordingly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a8cf67b-951d-7bae-5584-565ae9ec45c1
* Version Independent ID: b7b60c57-bcb0-679e-5163-97b62fced5d3
* Content: [Runtimes in the manifest file - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/runtimes)
* Content Source: [docs/reference/manifest/runtimes.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/manifest/runtimes.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
@davidchesnut Could you take a look at this?

**Comment by jordandev** [comment]
I see this as well.

Also because of this, docs about how to debug don't seem to be up to date as I cannot find a way to debug custom functions in desktop Excel with WebView2

**Comment by wynntee** [comment]
The documentation appears to be updated now. Closing.
