### ISSUE TITLE
Office volume versions

### ISSUE THREAD

**Issue by mathiasnielsen0** [OfficeDev/office-js-docs-pr#2585]
Hello! 

I'm currently developing a outlook add-in, for our customers, but they are currently using volume versions of Office, which apparently doesn't yet use Microsoft Edge.

https://docs.microsoft.com/en-us/officeupdates/update-history-office-2019

As i see on the link above, the latest version for volume versions are: 16.0.10371.20060, which is what I can see is installed on my customers pc as well.

Does this mean that you currently cannot update outlook to a version which uses the Edge browser?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00c430f1-bbf5-53b8-a225-4fbe8fc39c3b
* Version Independent ID: 0a069a0d-4d35-71ee-53af-8c55fe8548a0
* Content: [Browsers used by Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins)
* Content Source: [docs/concepts/browsers-used-by-office-web-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/concepts/browsers-used-by-office-web-add-ins.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
That is correct. Your customers will be using IE11. Office 2021 is expected later this year: [Microsoft Office 2021, Office LTSC 2021 announced, to be available for Windows and Mac later this year](https://www.msn.com/en-in/money/news/microsoft-office-2021-office-ltsc-2021-announced-to-be-available-for-windows-and-mac-later-this-year/ar-BB1dPzfc). If your users get a volume license for it, then they will be on a version that uses Edge.
