### ISSUE TITLE
Try zh-cn in this page

### ISSUE THREAD

**Issue by ivooQ** [OfficeDev/office-js-docs-pr#260]
All I see is ???

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37e9991e-98d3-bf56-ffbd-c2d77bfb0820
* Version Independent ID: e568baab-36e7-293e-5d6d-6d3b02931004
* Content: [Authorize to Microsoft Graph in your Office Add-in](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/authorize-to-microsoft-graph)
* Content Source: [docs/develop/authorize-to-microsoft-graph.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/authorize-to-microsoft-graph.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
I can reproduce. I'm investigating.
