### ISSUE TITLE
Spelling mistake 

### ISSUE THREAD

**Issue by loflet** [OfficeDev/office-js-docs-pr#261]
There seems to be a spelling mistake in the last section of the article.  The sentence which has spelling mistake is "Depending on your language and framework, libraries might be available that will simplify the ser-side code you have to write". 

In this sentence the 'ser-side' should be 'server-side'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37e9991e-98d3-bf56-ffbd-c2d77bfb0820
* Version Independent ID: e568baab-36e7-293e-5d6d-6d3b02931004
* Content: [Authorize to Microsoft Graph in your Office Add-in](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/authorize-to-microsoft-graph#)
* Content Source: [docs/develop/authorize-to-microsoft-graph.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/authorize-to-microsoft-graph.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for catching that @loflet. I'll send out a PR with the correction soon.

**Comment by AlexJerabek** [comment]
Fixed with [PR 262](https://github.com/OfficeDev/office-js-docs-pr/pull/262).

This should roll into production later this week.
