### ISSUE TITLE
No link to mentioned "Phone dialer sample Outlook Add-In"

### ISSUE THREAD

**Issue by heebinho** [OfficeDev/office-js-docs-pr#2618]
The article mentions the "Vanilla JavaScript" approach and refers to the "Phone Dialer Sample Outlook add-in". 

_"The phone dialer sample Outlook add-in shows a slightly different approach using only JavaScript to check these same conditions."_

Where can we find the mentioned example?

Thank you in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af6ccc36-8ea8-af6e-8731-059ce81d8628
* Version Independent ID: 2d98dd01-b671-d532-3bcb-88d40d6ef3d1
* Content: [Loading the DOM and runtime environment - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/loading-the-dom-and-runtime-environment)
* Content Source: [docs/develop/loading-the-dom-and-runtime-environment.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/loading-the-dom-and-runtime-environment.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for reporting this @heebinho. That document is referring to an unlinked sample. I suspect this sample has been removed from OfficeDev.

@davidchesnut Do you have any insights on the sample being referenced here?

**Comment by davidchesnut** [comment]
Hi @heebinho,

I just submitted PR #2632 to fix this. I don't know that this sample ever existed. This same subject is better covered in [Initialize your Office Add-in](https://docs.microsoft.com/office/dev/add-ins/develop/initialize-add-in). so I removed the duplicate content from the article. Let us know if you still need more information about onReady or initialize. Thanks!
