### ISSUE TITLE
Documentation seems limited (browser used for internal plugins)

### ISSUE THREAD

**Issue by pi3k14** [OfficeDev/office-js-docs-pr#2620]
I am doing som investigation of MS-OFBA handling in Office, and can't see this documentation correlate to my findings.

When Office (Excel) access a web resource it utilizes a browser with user agent string "Microsoft+Office+Excel+2014".
When Office performs the MS-OFBA login it utilizes a browser with user agent string "Mozilla/4.0+(compatible;+MSIE+7.0;+Windows+NT+10.0;+Win64;+x64;+Trident/7.0;+.NET4.0C;+.NET4.0E;+.NET+CLR+2.0.50727;+.NET+CLR+3.0.30729;+.NET+CLR+3.5.30729;+Tablet+PC+2.0;+Zoom+3.6.0)".

OS 10.0.19043, Office 16.0.11901.20204 - according to this documentation Edge should be used.

Can you extend the documentation to explain these discrepancies?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00c430f1-bbf5-53b8-a225-4fbe8fc39c3b
* Version Independent ID: 0a069a0d-4d35-71ee-53af-8c55fe8548a0
* Content: [Browsers used by Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins)
* Content Source: [docs/concepts/browsers-used-by-office-web-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/concepts/browsers-used-by-office-web-add-ins.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @pi3k14,

I'm a little unclear what you're asking. Are you using Excel for desktop or through a web browser in your scenario? In either case the second string you provide contains "Trident", which indicates Edge (with the original WebView) is being used. What are you observing

**Comment by pi3k14** [comment]
@AlexJerabek - I am using Excel for desktop. 

[MS-OFBA](https://docs.microsoft.com/en-us/openspecs/sharepoint_protocols/ms-ofba/30c7bbe9-b284-421f-b866-4e7ed4866027) is a (Microsoft) standard for performing web based sign in from Office applications.
To me it seems like an internal web handler is used in the first step, and some sort of IE handler used in second step as deleting cookies from IE changes its behavior. Mozilla 4 indicates IE 9, doesn't it?

I also installed this Edge WebView2 package which didn't change anything.

The cause of my investigation is the inability for Office/MS-OFBA to handle `includes` and `const` in javascript on the accessed web pages.

**Comment by AlexJerabek** [comment]
Thanks for the further details @pi3k14.

@Rick-Kirkham, can you please look into this?

**Comment by Rick-Kirkham** [comment]
This article is _only_ about the browser used in Office Web Add-ins. It does not apply to any other Office interaction with the web. I don't think MS-OFBA has any connection to Office Web Add-ins. If you are creating an Office Web Add-in can you tell use what Office application (Excel, Word, etc.) you are extending, and what you are trying to do that involves MS-OFBA?

**Comment by pi3k14** [comment]
For me, external to Microsoft, it is impossible to know what components are used internal to any Office applications.
If you, Microsoft, know that other parts of Office are using other incarnations of a web browser it would be nice to provide pointers to such.

**Comment by Rick-Kirkham** [comment]
I don't know whether Office uses other incarnations of browsers for other purposes. The issues in this repo are for tracking problems with the documentation for Office add-ins, which is where the expertise of the people that monitor this repo lies. As I understand it, you aren't actually making an Office add-in, so I think we should close this issue. But you might be able to get  an answer to your question on [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/products/).

**Comment by pi3k14** [comment]
You ever heard the joke "it's not my table"?
