### ISSUE TITLE
[Documentation] Wrong "document" property in "script", it must be in "config" instead 

### ISSUE THREAD

**Issue by perjerz** [OfficeDev/office-js-docs-pr#2623]
The document states that the document must be in **"scripts"** which is wrong.
![image](https://user-images.githubusercontent.com/5865946/114861036-ef86f380-9e16-11eb-955f-f09e2d32489f.png)

It must be in **"config"** instead of **"scripts"**
![image](https://user-images.githubusercontent.com/5865946/114861364-5dcbb600-9e17-11eb-9e4c-3fa0c269cb7b.png)

From the source code, it shows that it accepts the **"config"** instead of **"scripts"**
https://github.com/OfficeDev/Office-Addin-Scripts/blob/9b6ee01a1102299cd7c32326afbb6187a4a534c7/packages/office-addin-debugging/src/commands.ts#L53

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ab35128-1e97-c6ad-babc-f696f2e7b0fe
* Version Independent ID: cd1bacb1-14d7-a38d-321c-ebc2a526e03b
* Content: [Sideload Office Add-ins in Office on the web for testing - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/sideload-office-add-ins-for-testing#see-also)
* Content Source: [docs/testing/sideload-office-add-ins-for-testing.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/sideload-office-add-ins-for-testing.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @perjerz, 

Thanks for reporting this. This issue appears to be addressed in PR #2621, which is pending review. @mscharlock, can you monitor that PR and this issue?

**Comment by baconbum** [comment]
Just piggybacking on what @perjerz mentioned. He's correct, I was running into the error message

`Error: For sideload to web, you need to specify a document url.`

After putting the document property in config instead of scripts, I no longer received the error.

**Comment by ElizabethSamuel-MSFT** [comment]
@perjerz Thanks for raising this issue! The update should be published next week.
