### ISSUE TITLE
Runtime Environment Informations

### ISSUE THREAD

**Issue by heebinho** [OfficeDev/office-js-docs-pr#2624]
That first Note "When running in Office on Windows, your add-in uses the Internet Explorer 11 browser." means, that as soon as you have specified it, an Add-In will use IE11 **regardless** of the Office version documented in [Browsers used by Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins), right?

So in my case IE11 is used instead of Microsoft Edge with original WebView (EdgeHTML).

How does that look in the future with the chromium based Edge or is this Information already outdated?

Any additional informations regarding this topic would be highly appreciated.
Some design decisions depend on the embedded browser controls. 

Thank you in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a8cf67b-951d-7bae-5584-565ae9ec45c1
* Version Independent ID: b7b60c57-bcb0-679e-5163-97b62fced5d3
* Content: [Runtimes in the manifest file - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/runtimes)
* Content Source: [docs/reference/manifest/runtimes.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/manifest/runtimes.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for reporting this @heebinho. 

@Rick-Kirkham, can you please take a look at the [Runtimes manifest article](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/runtimes)? That note does seem out of date.

**Comment by Rick-Kirkham** [comment]
@heebinho  You are correct. The note is out-of-date. A Shared Runtime will now use Edge (Chromium) on the same Windows and Office version combinations that would support Edge (Chromium) in a task pane. I will get this article updated.
