### ISSUE TITLE
Can a manifest file be loaded in both Excel and Outlook?

### ISSUE THREAD

**Issue by yanli0303** [OfficeDev/office-js-docs-pr#2631]
It is mentioned on [this page](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/specify-office-hosts-and-api-requirements#set-the-hosts-element) that:

> If you don't specify the Hosts element, your add-in will run in all Office applications supported by Office Add-ins.

But it seems a manifest file can't be shared by Excel and Outlook:

1. The `xsi:type` attribute of `OfficeApp` element accepts either, `ContentApp`, `TaskPaneApp `, or `MailApp`. It sounds like we have to make a choice between Outlook and other Office applications.
2. The [`Permissions` element](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/permissions) explicitly separates mail add-in from other add-ins.

Could you confirm and update [the page](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/specify-office-hosts-and-api-requirements#set-the-hosts-element) with a table of what Office applications can share a manifest file?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b7148f0-0384-00d9-16f4-99cdab9c8ecc
* Version Independent ID: 9a7623fd-dd24-267f-a17f-dfcbd496ee0e
* Content: [Specify Office hosts and API requirements - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/specify-office-hosts-and-api-requirements#set-the-hosts-element)
* Content Source: [docs/develop/specify-office-hosts-and-api-requirements.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/specify-office-hosts-and-api-requirements.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@yanli0303 Yes, you're right, the manifest allows you to support Outlook (MailApp) or other Office applications but not both. We'll take a look at updating the documentation.

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@yanli0303 The doc updates should be published by the end of this week. Thanks.
