### ISSUE TITLE
Function name is wrong in documentation

### ISSUE THREAD

**Issue by jpickardsqr** [OfficeDev/office-js-docs-pr#2635]
In the _Register an event handler_ section, the text refers to a `handleDataChange` function:
 > The following code sample registers an event handler for the onChanged event in the worksheet named Sample. The code specifies that when data changes in that worksheet, the handleDataChange function should run.

But the code in the following example actually uses a function called `handleChange`:
```
    worksheet.onChanged.add(handleChange);
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52542c44-015a-746d-5d6f-c43f6e4e6774
* Version Independent ID: dfe8c9fb-4107-e19b-972a-c5a58eeb2646
* Content: [Work with Events using the Excel JavaScript API - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-events)
* Content Source: [docs/excel/excel-add-ins-events.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/excel-add-ins-events.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@jpickardsqr Thanks for raising this issue! The fix should be published next week.
