### ISSUE TITLE
Where's the page on debugging Excel with VS Code?

### ISSUE THREAD

**Issue by VashJuan** [OfficeDev/office-js-docs-pr#2640]
I want to debug a local Excel add-in with MS VS Code.

Why does this article assume/imply I have to get a browser involved, adding to the complexity? Please provide a link to the page I need. I suspect others are getting led here errantly. Thx!
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 614e6992-f9be-4ce5-1f15-0fc6bf285c43
* Version Independent ID: 1b37e38d-06ec-cd00-16bb-3324b1f0048f
* Content: [Microsoft Office Add-in Debugger Extension for Visual Studio Code - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-with-vs-extension)
* Content Source: [docs/testing/debug-with-vs-extension.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/debug-with-vs-extension.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@VashJuan Thanks for asking about this.

@mscharlock Is there existing guidance for this?

Thanks.

**Comment by VashJuan** [comment]
I may have misunderstood. I guess that Excel may be using Edge internally to display the pop-up/control panel? That might be made more clear or even explicitly stated?!

**Comment by mscharlock** [comment]
Hi @VashJuan - The task pane for Office Add-ins is rendered in a browser. The browser depends on the computer's OS and whether the add-in is running in Office on the web, Microsoft 365, or non-subscription Office 2013 or later. For a table that provides a reference to all the possible configurations, see: https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins. 
Let me know if this helps and if you need anything else. Thanks!

**Comment by VashJuan** [comment]
Sure that helps! Maybe just explain that on the original page, so folks know the situation?
