### ISSUE TITLE
Excel only ?

### ISSUE THREAD

**Issue by RStadlmair** [OfficeDev/office-js-docs-pr#2641]
A valuable feature. Is this going to be available for Outlook also in a defined timeframe ?
R.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c7b653d-1bd6-a032-2046-6d6a2ad2b203
* Version Independent ID: 7165a66d-bc9a-dce9-91c4-7c1209d1324e
* Content: [Enable and Disable Add-in Commands - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/design/disable-add-in-commands?source=docs)
* Content Source: [docs/design/disable-add-in-commands.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/design/disable-add-in-commands.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@RStadlmair Thanks for your interest in Office Add-ins! At present, this feature has not been implemented. It would be great if you could submit this request on [Microsoft 365 Developer Platform Ideas](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform). The feature crew considers these suggestions when they plan for upcoming work.

Thanks.
