### ISSUE TITLE
Project Addin & UserLogon

### ISSUE THREAD

**Issue by puentesdiaz** [OfficeDev/office-js-docs-pr#2645]
I'm develop a Office Project Addin with Node.JS

First to all, when execute my MSProject, i need log in with my ActiveDirectory Credentials....

How can i know which user i use (whoiam) since JAVASCRIPT?

**Comment by ElizabethSamuel-MSFT** [comment]
@puentesdiaz Thanks for asking about this.

@BeReasonable Can you help here?

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@BeReasonable Thanks for the offline update.

@NadinMerali Can you take a look at this?

Thanks.

**Comment by AlexJerabek** [comment]
@NadinMerali, any updates?

**Comment by nancy-wang** [comment]
@NadinMerali following up on this - thanks!

**Comment by ElizabethSamuel-MSFT** [comment]
@NadinMerali Thanks. @Rick-Kirkham will take a look.

**Comment by Rick-Kirkham** [comment]
You can call the [Office.auth.getAccessToken](https://docs.microsoft.com/javascript/api/office/office.auth?view=common-js-preview#office-office-auth-getaccesstoken-member(1)). Then open and parse the token that it returns to get the AAD OID of the user and the user's email address.
