### ISSUE TITLE
Removing Side-Loaded Addins from Desktop Office

### ISSUE THREAD

**Issue by theboyknowsclass** [OfficeDev/office-js-docs-pr#2646]
[Enter feedback here]

Is this page correct?  i've cleared the wef folder as stated, but the addins keep re-appearing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e273e29-10ac-440e-634e-588b5208e484
* Version Independent ID: a5a6dc8a-b504-686e-80ce-45aabd6f832b
* Content: [Clear the Office cache - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/clear-cache)
* Content Source: [docs/testing/clear-cache.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/clear-cache.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @theboyknowsclass, 

Thanks for reporting this. I just tried to reproduce your issue and couldn't. Which application are you using (Word, Excel, PowerPoint, etc)? Also, are you additionally deleting the AppData found under `%userprofile%\AppData\Local\Packages\Microsoft.Win32WebViewHost_cw5n1h2txyewy\AC\#!123\INetCache\` ?
