### ISSUE TITLE
Yo Office

### ISSUE THREAD

**Issue by mscaitlina** [OfficeDev/office-js-docs-pr#265]
Step number 3 in the "Create the web app" section appears to be out of date. I get a different set of questions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c4ddde7-f1fd-44ba-fba1-0ae9d0131df7
* Version Independent ID: d946ffe6-f29f-1563-b679-121090ba60a1
* Content: [Build your first Excel add-in using jQuery](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-jquery?tabs=visual-studio-code)
* Content Source: [docs/quickstarts/excel-quickstart-jquery.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/quickstarts/excel-quickstart-jquery.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by mscaitlina** [comment]
Sorry, it looks like my confusion was due to the first question having long answers in the console and being simplified to "jquery" in the documentation. The actual questions are the same :)

**Comment by AlexJerabek** [comment]
Hi @mscaitlina,
I'll get the docs updated to reflect the latest version of yo office.

Just to confirm, the text you're seeing looks like this, right?
? Choose a project type: Office Add-in project using Jquery framework
? Choose a script type Javascript
? What do you want to name your add-in? My Office Add-in
? Which Office client application would you like to support? Excel

**Comment by mscaitlina** [comment]
Yup!

**Comment by AlexJerabek** [comment]
@mscaitlina [PR 287](https://github.com/OfficeDev/office-js-docs-pr/pull/278) is online to address this documentation issue. Please check it out at your earliest convenience.

**Comment by AlexJerabek** [comment]
The PR has been merged into master. It'll be live soon. Thanks again for reporting this issue.
