### ISSUE TITLE
None of this works on Excel for Web

### ISSUE THREAD

**Issue by vicw87** [OfficeDev/office-js-docs-pr#2653]
I guess it's a different API, but I think there should be an update to the page explaining this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf942d54-3ee5-2476-e11f-0b658e0bb189
* Version Independent ID: 2a671958-54a3-f477-6624-f2bdc7c133e5
* Content: [Work with PivotTables using the Excel JavaScript API - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-pivottables)
* Content Source: [docs/excel/excel-add-ins-pivottables.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/excel-add-ins-pivottables.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @vicw87, 

I'm sorry to hear you're having issues with the PivotTable APIs. I just tried out a few [Script Lab](https://docs.microsoft.com/en-us/office/dev/add-ins/overview/explore-with-script-lab) samples for the PivotTable APIs on Excel for the web. They seemed to be working okay. Could you please specify which PivotTable APIs or which pieces of sample code aren't working for you?

Thanks!
