### ISSUE TITLE
The Office Add-in manifest does not support Excel 

### ISSUE THREAD

**Issue by tihomir4** [OfficeDev/office-js-docs-pr#2656]
I am following the steps in this article - https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/outlook-quickstart?tabs=yeomangenerator but when I run "npm start" i get 
Error: Unable to start debugging 
- unable to sideload the Office Add-in
- The Office Add-in manifest does not support Excel 

I thought that by accident I created Excel project, but then tried few more times - making sure that it is Outlook add-in and getting the same error.

**Comment by ElizabethSamuel-MSFT** [comment]
@tihomir4 Thanks for let us know. We'll take a look.

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@tihomir4 I created a new project by following the steps in the quick start but I didn't get this error (e.g., debugging started successfully). Can you share more details about your setup? For example, Node.js version, Outlook version, etc.

@millerds Any thoughts on what may be leading to this error?

Thanks.

**Comment by millerds** [comment]
Can you share your package.json contents?
