### ISSUE TITLE
Event based activation - Are listed events correct / enabled?

### ISSUE THREAD

**Issue by barclayadam** [OfficeDev/office-js-docs-pr#2657]
I'm trying to get some event based add-in working but cannot seem to get anything other than `OnNewMessageCompose` working for email-based events. Neither `OnMessageAttachmentsChanged` nor `OnMessageRecipientsChanged` ever seem to be fired, but based on the table at the top of this document the events seem to be supported.

To eliminate possible problems with my implementation I have a simple HTML file with a simple function to print to console, nothing else. In my manifest.xml I have:

````xml
            <Hosts>
                <Host xsi:type="MailHost">
                    <!-- Event-based activation happens in a lightweight runtime.-->
                    <Runtimes>
                        <!-- HTML file including reference to or inline JavaScript event handlers.
                             This is used by Outlook on the web. -->
                        <Runtime resid="WebViewRuntime.Url">
                            <!-- JavaScript file containing event handlers. This is used by Outlook Desktop. -->
                            <Override type="javascript" resid="JSRuntime.Url"/>
                        </Runtime>
                    </Runtimes>

                    <DesktopFormFactor>
                        <!-- Enable launching the add-in on the included events. -->
                        <ExtensionPoint xsi:type="LaunchEvent">
                            <LaunchEvents>
                                <LaunchEvent Type="OnNewMessageCompose" FunctionName="printToConsole" />
                                <LaunchEvent Type="OnMessageRecipientsChanged" FunctionName="printToConsole" />
                            </LaunchEvents>
                            <!-- Identifies the runtime to be used (also referenced by the Runtime element). -->
                            <SourceLocation resid="WebViewRuntime.Url"/>
                        </ExtensionPoint>
                    </DesktopFormFactor>
                </Host>
            </Hosts>
````

When installing to a preview-enabled OWA installation the function *is* called when a new message is composed, but *is NOT* called when recipients or attachments change.

That seems to be correct based on the document at https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/extensionpoint#launchevent-preview which suggests the only value LaunchEvent types are `OnNewMessageCompose` and `OnNewAppointmentOrganizer`

To be clear on my use case I wish to activate my add-in when a new email is composed, and then continue to react to events such as recipients or subject changing and run some additional code. I have tried to add event handlers directly within the body of the `OnNewMessageCompose` function but that, although claiming to be successful, never actually fires.

Is there something missing from this page that would make it clear _how_ those additional events are supposed to work / be registered?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 193780ba-aa43-dc5c-fc28-adc96a0fdeda
* Version Independent ID: da41da2b-207e-e976-3491-61672d1e3493
* Content: [Configure your Outlook add-in for event-based activation (preview) - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/autolaunch)
* Content Source: [docs/outlook/autolaunch.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/outlook/autolaunch.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@barclayadam Thanks for raising this issue. We're in the process of updating the documentation for the additional events (i.e., besides OnNewMessageCompose and OnNewAppointmentOrganizer).

Thanks.

**Comment by barclayadam** [comment]
@ElizabethSamuel-MSFT Thank you for your response. Does this mean those additional events _are_ supported, but they will be registered in a different manner? Do you have any time scale for the updates?

**Comment by ElizabethSamuel-MSFT** [comment]
I'm actively working on updating the docs this week and hope to be done by the end of this week or early next week. They should be registered the same way. However, the new events may only be available in the Windows client at present.

**Comment by barclayadam** [comment]
OK, great news (well, except it only being available in the desktop clients :))

Is there a known workaround for getting them working in OWA, or is that scenario going to be implemented before go-live with these additional events?

Is there a reason that `addHandler` does not work in commands? i.e. `Office.context.mailbox.item.addHandlerAsync(        Office.EventType.RecipientsChanged, ...` shows a `result` of `successful` but never actually calls back to the update function. Is that something that should work, or should this also be called out as unsupported in event handlers?

At the moment I'm calling a function to check for current recipients every 500ms which works, but I do not know the implications. WOuld be great to have some guidance here on what the differences between for example task pane and this scenario are (i.e. is that OK? What about listening for other changes than recipients and attachments? What happens if the timeout of 300s is hit? What happens if you call event.completed() but continue to do work?)

Sorry for the large number of questions here, but it all feels related to the new functionality and given you are working on the docs feels right to list them out here

**Comment by ElizabethSamuel-MSFT** [comment]
We definitely appreciate your interest in this feature and your feedback! While this feature is in preview is the perfect time for feedback so we can tweak the design if needed before we ship. We expect the additional events to be available in the web client soon and so should be available in both clients before go-live in an official requirement set. There's no workaround for the not-yet-implemented events in OWA.

I'll be updating the walkthrough code sample and will keep these questions and comments in mind.

item.addHandlerAsync only works with task pane (see the [Events section of the Item documentation](https://docs.microsoft.com/office/dev/add-ins/reference/objectmodel/requirement-set-1.9/office.context.mailbox.item#events)).   While the same item events may be involved, we have different listeners for automatic activation (this feature) vs task pane.

**Comment by barclayadam** [comment]
Thanks for the heads-up on events section. It would be great if calling the functions in an unsupported environment would throw an error and not be marked as successful.

I look forward to seeing the updated documentation. Would it be possible to be notified here with your updates so I can check them out? Particularly keen on some answers to things like how timeouts will be handled, what actually happens to the executing function etc.

**Comment by ElizabethSamuel-MSFT** [comment]
I'll pass along that suggestion to the team (re: unsupported behavior). I'll also make sure to link the pull request to this issue. Any feedback you have on the PR is welcome too.

**Comment by ElizabethSamuel-MSFT** [comment]
@barclayadam We recently updated the article to note which clients support which events, how to preview on Windows, etc. There are more updates coming.

Thanks.

**Comment by JuaneloJuanelo** [comment]
@barclayadam  thanks for your proactiveness on testing this, FYI all this is in **preview** right now. As Elizabeth mentioned we only support Windows at this moment, Outlook on the Web will be supported in preview in the near future, and of course will be supported in both when we launch the feature to production. thanks for your patience in the meantime please try it in windows and send us feedback. Thank you!! 

Also can you please clarify what you mean by "addHandler does not work in commands? "  are you saying you are trying to call this method on a UI-less action on the ribbon?  (fyi by commands we understand 2 potential actions: show task pane and ui-less action. I am assuming it is UI-less action is that correct?

**Comment by ElizabethSamuel-MSFT** [comment]
@barclayadam Let us know if you have any feedback on the prospective changes in [this pull request](https://github.com/OfficeDev/office-js-docs-pr/pull/2666). Thanks.

**Comment by barclayadam** [comment]
@JuaneloJuanelo I understand completely this is a preview, just want to get a head start :) We have been testing this out in various builds of Outlook desktop and OWA. Have found that OWA is seemingly much more reliable, but not sure exactly why. Current hunch is we are seeing caching problems but continuing to investigate.

I can confirm that addHandler when in an event-activated flow (i.e. if I call it in a method attached using `Office.actions.associate` as part of a `OnNewMessageCompose` launch) then the method call succeeds insomuch as the result argument to the 3rd method has a status of "succeeded". Nothing is ever actually triggered though.

**Comment by barclayadam** [comment]
@ElizabethSamuel-MSFT I'll take a look at that PR now to see if I have any feedback. Where would be the best place to direct all feedback I've been gathering regarding these previews? I presume this is not an ideal place unless it relates to confusion caused by the docs vs functionality?

**Comment by barclayadam** [comment]
@ElizabethSamuel-MSFT There is nothing specific with the changes on that PR I have comments on. It looks to clarify the eventing which is the confusion of this issue. 

Again, as above, I do have a few other pieces of feedback for both documentation and product. Should I open some more specific issues in this repo for the doc-related questions? Or can I put together a single list and somebody decides on best course of action?

**Comment by ElizabethSamuel-MSFT** [comment]
@barclayadam For now, let's continue to track your feedback here, whether for product or documentation. A single list is fine so we can track what's been addressed and what's still pending.

**Comment by barclayadam** [comment]
Current feedback, in rough priority order for us:

1. The ability to track down _why_ a problem happens trying to launch an add-in using auto-launch seems to be lacking error handling and / or more informative errors / logs on issues when trying to even launch the code for an event. See issue @ https://github.com/OfficeDev/office-js/issues/1861. Note that this is NOT debugging the action once run, this is even getting to the point of it launching at all in response to events

2. It would be great to be able to set a signature as non-editable to avoid our users accidentally changing the one we have set

3. When a signature is set using `setSignatureAsync` it takes away focus. For example, open a menu and have the add-in set the signature in the background and when it does so the menu will auto-close

4. Documentation on the caching / loading behaviour of Outlook Desktop in particular, but also OWA. If I use Fiddler to capture requests I can see that desktop loads taskpane.html every time (it has no `Cache-Control` header), but the js file used for auto launch does NOT appear to be loaded. I'm not sure if that is due to a problem in manifest.xml and whether it's the root cause of my issue from issue above, or because of caching, or something else. I do see a `bundle.js` file downloaded to the `Office\16.0\Wef` folder structure at startup. 
 
This is tied to a manifest version and will never change if the JS file it references change. This is different behaviour to taskpane and to OWA and means we could not automatically keep desktop up to date without manually getting new versions installed

5. Documentation at https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/autolaunch#implement-event-handling states that you should add 2x registrations. Using the `g` global object, and `Office.actions`. That seems to contradict both example and reality, as `Office.actions` exists in OWA, and the launching in OWA does work without the first registration section

6. I experimented with showing a "loading" state as the signature so that we could immediately remove the existing signature if any exists. The problem is then on failure as I could not reset back to original signature. Would be nice to be able to either a) read the existing signature or b) be able to set back to a default

7. https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/runtime appears to be missing information of the `Override` element as a child of `Runtime`, as specified in https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/autolaunch

**Comment by ElizabethSamuel-MSFT** [comment]
@barclayadam Thanks for taking the time to pull this together. We appreciate your feedback so keep it coming! We will make updates where needed.

@JuaneloJuanelo

Thanks.

**Comment by barclayadam** [comment]
I wanted to expand a little on what we are looking for in terms of guidance and (perhaps?) changes for the caching behaviour we are seeing. At the moment I observe:

 - OWA will *always* load taskpane.html and commands.html (commands.html for auto-launch event). If we do not cache those then every load will see a fresh load every time task pane is opened, or message compose is opened

 - Desktop will _always_ load taskpane.html, as OWA does

 - Desktop will NOT reload the commands.js file, the equivalent of commands.html wrapper used by OWA. This is different to the model used in the other 3 cases outlined above. I have yet to figure out exactly when the file is loaded / re-loaded, but it seems like it's tied to a manifest version and does NOT get updated until a user manually updates their add-in, which is less than ideal

I, therefore, would like to know:

  - What is the best practice for adding caching headers to the files served from our server. Manifest, HTML & JS/CSS
      - 	
  - What should we expect in terms of Outlook reloading any of these files?

I would _really_ like to be able to successfully update the files server-side only and have them be pushed out (given a known caching period) without users having to reload the add-in. It's possible in 3 of the 4 scenarios, and therefore feels right to make Desktop behave the same

**Comment by ElizabethSamuel-MSFT** [comment]
@barclayadam It is on our backlog to continue clarifying this and to add more details about the new events. Coming soon. Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@barclayadam We've created a [PnP](https://github.com/OfficeDev/PnP-OfficeAddins/tree/main/Samples/outlook-tag-external) that uses the OnMessageRecipientsChanged event (currently in preview).

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@barclayadam Are you able to access the events that are currently in preview? If you're still not able to access them, can you make sure to follow the instructions in the [How to preview](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/autolaunch#how-to-preview) section of the feature article?

Thanks.

**Comment by barclayadam** [comment]
@ElizabethSamuel-MSFT I have been able to successfully use recipient changed and new mail (now in production). Is it possible to request other events? Would love to see an event when the `From` field is modified

**Comment by edwardforgacs** [comment]
You did better than me, I am about to give up as I have been unable to get OnNewMessageCompose to work with either of the MS samples. To be frank the Outlook JS add-ins are just mind-blowingly unstable, even for the most trivial operations.

**Comment by ElizabethSamuel-MSFT** [comment]
@edwardforgacs Thanks for your feedback about using Office.js. Tagging the feature team @exextoc for awareness about the beta performance issues.

Note that you shouldn't need to set anything in order to use the OnNewMessageCompose event since it is now in production and is generally available (GA) from requirement set 1.10 using a Microsoft 365 subscription. For Outlook on Windows, the minimum required Office version is 2104 (build 13929.20296).

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
> @ElizabethSamuel-MSFT I have been able to successfully use recipient changed and new mail (now in production). Is it possible to request other events? Would love to see an event when the `From` field is modified

@barclayadam So glad you're able to use the events! Regarding the new event request and any other feature suggestions, you can post new ideas or upvote existing ones at the [Microsoft 365 Developer Platform Tech Community site](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform).

Tagging @JuaneloJuanelo @hitmanwar for awareness re: request for new event on changing "From".

**Comment by ElizabethSamuel-MSFT** [comment]
PR adding links to JSON that may also be returned in the handler's `event` arg, if applicable: https://github.com/OfficeDev/office-js-docs-pr/pull/2879

**Comment by sundariragavan** [comment]
@barclayadam 
https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/outlook/autolaunch.md I have referred this document.
I'm able to get the **OnNewMessageCompose**, **OnNewAppointmentOrganizer** event. But unable to get the Preview events.
For example **OnAppointmentAttendeesChanged**, **OnAppointmentTimeChanged**
are you able to get the events.

**Comment by ElizabethSamuel-MSFT** [comment]
Related issue: https://github.com/OfficeDev/office-js/issues/2049

**Comment by ElizabethSamuel-MSFT** [comment]
@barclayadam What is your current status for this issue?

We've since updated the walkthrough to handle some configuration updates. Are folks able to access all the GA events and try the preview ones?

Thanks.

**Comment by barclayadam** [comment]
@ElizabethSamuel-MSFT We have successfully deployed an add-in using the events as listed above, albeit with an ongoing issue with regards to the event-based activation not working for a number of users (as per #1861).

This issue could be closed though from my POV

**Comment by ElizabethSamuel-MSFT** [comment]
@barclayadam Thanks for that update. I'll go ahead and close this issue now.

If folks are still having trouble with this feature, do let us know with a new GitHub issue.

Thanks.
