### ISSUE TITLE
Add-in content is missing

### ISSUE THREAD

**Issue by mscaitlina** [OfficeDev/office-js-docs-pr#267]
I followed the steps through the end and side-loaded my add-in inside Excel online (after getting blocked on windows). However, my add-in is missing content. It has the blue bar and "Welcome" text, but it also says "Please sideload your addin to see app body."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c4ddde7-f1fd-44ba-fba1-0ae9d0131df7
* Version Independent ID: d946ffe6-f29f-1563-b679-121090ba60a1
* Content: [Build your first Excel add-in using jQuery](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-jquery?tabs=visual-studio-code)
* Content Source: [docs/quickstarts/excel-quickstart-jquery.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/quickstarts/excel-quickstart-jquery.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by mscaitlina** [comment]
It looks like this is due to a bug in step 7. First thing to note is that there isn't an app.js so I assumed it was referring to index.js. I blindly copied and pasted the code, but it looks like that meant I lost code at the beginning of the file that I needed.

**Comment by AlexJerabek** [comment]
@ElizabethSamuel-MSFT Did this get fixed with your PR?

**Comment by ElizabethSamuel-MSFT** [comment]
@AlexJerabek I fixed the app.js/index.js bit.

**Comment by AlexJerabek** [comment]
@mscaitlina We've updated the documentation to reflect the current version of yo office and the correct file names. I'll close this issue for now, but please reopen if you think the quick start instructions are still unclear.

**Comment by manish-shukla01** [comment]
I tried to do this on Mac. I am fairly new to node js. I got error enoent ENOENT: no such file or directory, open '/Users/manishmac/Documents/technical/officejs/package.json' when I did npm start

**Comment by manish-shukla01** [comment]
@ElizabethSamuel-MSFT can you check

**Comment by kbrandl** [comment]
@manish-shukla01 this error means that the directory where you ran `npm start` isn't the root directory of the project.  Before running `npm start`, you'll first need to navigate to the directory/folder that contains all of the files that **Yo Office** created for your add-in project (which includes the **package.json** file that's mentioned in the error message you've described).

**Comment by LeslieWongCV** [comment]
Check if you have saved all the edited script.
