### ISSUE TITLE
Nothing working as per the instructions on the page

### ISSUE THREAD

**Issue by kausarp** [OfficeDev/office-js-docs-pr#2693]
I was not able to create Word AddIn project. Stuck for a month. We have Zscalar and I disabled the Zscalar in my test environment. I was able to create a project with lots of errors and warnings. Well, then I tried to run npm start, nothing happens.
Please guide and updates the instructions on this page. So, other developers doesn;t face same issue that I am. I am uploading all the screen shots. i tried to create both Typescript and JavaScript.

<img width="602" alt="BeforeZScalar" src="https://user-images.githubusercontent.com/82678124/118561870-527aeb80-b731-11eb-88c8-7e20182a1aa4.png">
<img width="941" alt="createdbutwerror" src="https://user-images.githubusercontent.com/82678124/118561900-60307100-b731-11eb-98b7-894f9037f775.png">
<img width="910" alt="FailedCommandTS" src="https://user-images.githubusercontent.com/82678124/118561907-632b6180-b731-11eb-8c6a-6bf5e378a16d.png">
<img width="950" alt="FailedCommandTS1" src="https://user-images.githubusercontent.com/82678124/118561935-6de5f680-b731-11eb-8e9a-1b67abc8c09e.png">

Details of my test environment:

Operating System: Windows 10 Enterprise
Node version: 6.14.8
Office version: Office 2016
Tool versio: 3.1.1

Please guide.
Best,
Kausar

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77e380a7-6e2e-ada8-d297-3fd5018a1958
* Version Independent ID: f23490e8-6eeb-f2d5-6c94-69e3c9ed83f4
* Content: [Build your first Word task pane add-in - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/word-quickstart?tabs=yeomangenerator)
* Content Source: [docs/quickstarts/word-quickstart.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/quickstarts/word-quickstart.md)
* Product: **word**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@kausarp Thanks for raising this issue and for sharing your environment details.

> Node version: 6.14.8

Can you try updating Node.js to at least version 8? This is the minimum version required by yo office per [their readme](https://github.com/OfficeDev/generator-office#install). The active [Node.js LTS version](https://nodejs.org/en/about/releases/) is 14.

> Tool versio: 3.1.1

Can you specify which tool you're referring to here?

@millerds Could yo office display an error or warning if the minimum requirements like Node.js version are not met?

Thanks.

**Comment by kausarp** [comment]
@ElizabethSamuel-MSFT  I updated node to v10.23.0 and it stills same.
Good Point @millerds

**Comment by ElizabethSamuel-MSFT** [comment]
@kausarp I was able to create and run the quick start add-in. Here are my details:
- node: v14.16.1
- yo: 4.2.0
- generator-office (i.e. yo office): 1.7.9

Maybe you can try running the node.js window as administrator? The error seems to be complaining about your security policy, unable to download the certificate, etc.

Also, can you share more about your Office version/build/channel? For how to view these details, see [About Office: What version of Office am I using?](https://support.microsoft.com/office/about-office-what-version-of-office-am-i-using-932788b8-a3ce-44bf-bb09-e334518b8b19).

Thanks.
