### ISSUE TITLE
<Runtimes> order sequence matters

### ISSUE THREAD

**Issue by tharshada** [OfficeDev/office-js-docs-pr#2706]
[Enter feedback here]

As per [TaskPaneAppVersionOverridesV1_0.xsd](https://dev.azure.com/office/Office/_git/Office?path=%2Fotools%2Finc%2Fosfclient%2Fappschema%2FTaskPaneAppVersionOverridesV1_0.xsd&version=GBmaster&line=543&lineEnd=554&lineStartColumn=1&lineEndColumn=19&lineStyle=plain&_a=contents)
sequence order of `<Runtimes>` matters which is not mentioned in the documentation. `2` has incorrect schema.
 - # 1
```xml
 <VersionOverrides xmlns="http://schemas.microsoft.com/office/taskpaneappversionoverrides" xsi:type="VersionOverridesV1_0">
    <Hosts>
      <Host xsi:type="Workbook">
        <Runtimes> 👈
          <Runtime resid="Taskpane.Url" lifetime="long" /> 
        </Runtimes>
        <DesktopFormFactor>...</DesktopFormFactor>
      </Host>
    </Hosts>
</VersionOverrides>
```
 - # 2
```xml
 <VersionOverrides xmlns="http://schemas.microsoft.com/office/taskpaneappversionoverrides" xsi:type="VersionOverridesV1_0">
    <Hosts>
      <Host xsi:type="Workbook">
        <DesktopFormFactor>...</DesktopFormFactor>
         <Runtimes> 👈
          <Runtime resid="Taskpane.Url" lifetime="long" />
        </Runtimes>
      </Host>
    </Hosts>
</VersionOverrides>
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a1bb1ec-f7c0-61c7-bd50-4018a2726e3a
* Version Independent ID: dabd68f4-f474-1f01-0022-b2fe55eaafa3
* Content: [Configure your Office Add-in to use a shared JavaScript runtime - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/configure-your-add-in-to-use-a-shared-runtime?source=docs#configure-the-manifest)
* Content Source: [docs/develop/configure-your-add-in-to-use-a-shared-runtime.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/configure-your-add-in-to-use-a-shared-runtime.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for reporting this @tharshada.

@davidchesnut, can you please investigate the runtime manifest documentation?
