### ISSUE TITLE
Will the browser used by office 2019 to run add-ins be replaced by Edge as IE 11 is being retired?

### ISSUE THREAD

**Issue by felixjiang** [OfficeDev/office-js-docs-pr#2719]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00c430f1-bbf5-53b8-a225-4fbe8fc39c3b
* Version Independent ID: 0a069a0d-4d35-71ee-53af-8c55fe8548a0
* Content: [Browsers used by Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins)
* Content Source: [docs/concepts/browsers-used-by-office-web-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/concepts/browsers-used-by-office-web-add-ins.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @felixjiang, 
IE11 will continue to be the browser control for Office 2019. Unless the plan of record changes, the versions listed in the [Browsers article](https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins) will remain the same. To avoid using IE11, you'll need to upgrade to a M365 subscription.

I'm going to close this issue, as there's no actionable changes to make in the documentation. Please let me know if you have any other questions.
