### ISSUE TITLE
updateStatus function typo

### ISSUE THREAD

**Issue by georgesfarah4** [OfficeDev/office-js-docs-pr#2720]
```
function updateStatus(message) {
    var statusInfo = $('#status');
    statusInfo.innerHTML += message + "<br/>";
}
```

should be:

```
function updateStatus(message) {
    var statusInfo = $('#status');
    statusInfo[0].innerHTML += message + "<br/>";
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5f7a698-efa2-3584-6ea0-85fa3718718f
* Version Independent ID: cef6669b-bfc0-840a-ea4e-ebc2ae5cc58a
* Content: [Get the whole document from an add-in for Word - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/word/get-the-whole-document-from-an-add-in-for-word)
* Content Source: [docs/word/get-the-whole-document-from-an-add-in-for-word.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/word/get-the-whole-document-from-an-add-in-for-word.md)
* Product: **word**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for reporting this @georgesfarah4.

@ElizabethSamuel-MSFT, can you please investigate and update the documentation as needed? Thanks!

**Comment by ElizabethSamuel-MSFT** [comment]
@georgesfarah4 Thanks for letting us know about this. The fix should be published soon.

Thanks.
