### ISSUE TITLE
Missing details in tip section

### ISSUE THREAD

**Issue by singhbrijraj** [OfficeDev/office-js-docs-pr#2721]
After step 1 there's mention of tip as "If you aren't using a Yeoman generator based add-in, you need to adjust a registry key. " Please add more details regarding which regkey are we referring here. So that, it would be a lot easier to follow.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5e92a7f-e42d-68ba-cc21-15df8289f5a1
* Version Independent ID: 096a172b-382e-764d-6d7d-88811bb5b96f
* Content: [Debug add-ins on Windows using Microsoft Edge WebView2 (Chromium-based) - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-desktop-using-edge-chromium)
* Content Source: [docs/testing/debug-desktop-using-edge-chromium.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/debug-desktop-using-edge-chromium.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for reporting this @singhbrijraj. 

@mscharlock, can you please investigate and update the documentation accordingly?

**Comment by mscharlock** [comment]
Hi @singhbrijraj - happy to look into this and get back to you. I think if memory serves if you are creating in other systems you are typically prompted to change the registry key via a dialog box but let me confirm at get back to you.

**Comment by mscharlock** [comment]
Closing this issue as PR with tip adjustment is in. If you need anything else, please notify @AlexJerabek and he can reopen this issue for you. Thank you!
