### ISSUE TITLE
add method doesnt exists in presentation class

### ISSUE THREAD

**Issue by amahmadnia** [OfficeDev/office-js-docs-pr#2723]
[Enter feedback here]

async function addSlide() {
  await PowerPoint.run(async function(context) {
    context.presentation.slides.add();

    await context.sync();
  });
}

this code doesnt work
error: Property 'add' does not exist on type 'SlideCollection'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb0c7511-1f0e-76f3-f274-531f13c77621
* Version Independent ID: c305f14b-2b51-8b45-566b-9b33d630c8fd
* Content: [Add and delete slides in PowerPoint - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/powerpoint/add-slides)
* Content Source: [docs/powerpoint/add-slides.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/powerpoint/add-slides.md)
* Product: **powerpoint**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hello @amahmadnia,

Thank you for raising this issue. `SlideCollection.add` is currently is preview. To use that API, you'll need to follow the steps listed [here](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/powerpoint-preview-apis). That will enable preview APIs in your add-in. Please let me know if that fixes your issue.

I'm also going to add the preview-enabling steps to the article you linked. Hopefully, that'll make it more clear.
