### ISSUE TITLE
Appsource not supporting SendEvent note needs more clarity and reasoning

### ISSUE THREAD

**Issue by mikewalker74** [OfficeDev/office-js-docs-pr#2727]
[Enter feedback here]

The note on the Send Event on AppSource is not supported is quite an issue for ISV's wishing to be good Microsoft partners, is this due to the AppSource team limiting the manifest sets and is going to be fixed in time?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e12d688-9620-e8f2-871d-922ec98008b5
* Version Independent ID: a8b409f3-44f7-97e5-d722-cbf04edc0653
* Content: [On-send feature for Outlook add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/outlook-on-send-addins?tabs=modern)
* Content Source: [docs/outlook/outlook-on-send-addins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/outlook/outlook-on-send-addins.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by exextoc** [comment]
As of now, we have blocked the on-send add-ins on store due to Security reasons. However, We are working on an enhancement that will unblock it. Its in our backlog

**Comment by mikewalker74** [comment]
> As of now, we have blocked the on-send add-ins on store due to Security reasons. However, We are working on an enhancement that will unblock it. Its in our backlog

Thanks for the feedback is there a specific reason from a security standpoint as surely if side loading is possible defeats and or creates an observational concern for our clients if deemed a security reason..

**Comment by exextoc** [comment]
Store listing of add-ins allows end users to find and install the add-ins. Currently our security policies don’t allow wide distribution of add-in’s that are invoked automatically from store. On-Sends is one example of that. We currently do not have provisions/control to inform end users about such add-in capabilities at the time of add-in installation or updates. 

With admin installed, side-loading, we leave it to admins to make a conscious choice of installing the add-ins that aligns with their org’s policies. 

Having said that, we are in the process of making updates on this. We are working towards making block on send like add-in’s available on store
