### ISSUE TITLE
Automation Testing of Outlook Add-ins

### ISSUE THREAD

**Issue by sudgarre** [OfficeDev/office-js-docs-pr#2728]
Hi Team - Is there any way of automation testing the add-ins developed under Outlook app ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b2e062e-1a7a-1861-bf20-c23ac64d0d37
* Version Independent ID: ae2d1395-2a87-1bda-00fb-1b30f8e27b66
* Content: [Outlook add-ins overview - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/outlook-add-ins-overview)
* Content Source: [docs/outlook/outlook-add-ins-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/outlook/outlook-add-ins-overview.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by exextoc** [comment]
Unfortunately we do not support test toolkit for addin development.We track Outlook add-in feature requests on our Tech Community Page (https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform) .You can also use ScriptLab Add-in to test outlook Add-in APIs.
