### ISSUE TITLE
[LOC] [CATS] Multiple Invalid links

### ISSUE THREAD

**Issue by OfficeGSX** [OfficeDev/office-js-docs-pr#273]
Hello there are multiple invalid links in an article below you can find the link to the CATS testing:

https://contentqacats/CheckResults/2018072600072/Report/Failed/Broken%20external%20links

Can you please go through the issues and fix them ?

Thank you.

**Comment by Rick-Kirkham** [comment]
#11 through #23 are fixed.

**Comment by AlexJerabek** [comment]
9-10 are fixed.

**Comment by AlexJerabek** [comment]
@ElizabethSamuel-MSFT, @Rick-Kirkham Did we make it through this list and clean up all the CATS links?

**Comment by ElizabethSamuel-MSFT** [comment]
24 was fixed with this PR https://github.com/OfficeDev/office-store-docs/pull/135

**Comment by ElizabethSamuel-MSFT** [comment]
6 and 7 are Won't Fix as we believe the apostrophe in the file name is the issue.

**Comment by ElizabethSamuel-MSFT** [comment]
1-5 fixed with this PR https://github.com/OfficeDev/office-js-docs-pr/pull/277

**Comment by ElizabethSamuel-MSFT** [comment]
@AlexJerabek can you confirm regarding item 8?

**Comment by AlexJerabek** [comment]
8 is still broken. I'll look into it.

**Comment by AlexJerabek** [comment]
I have [PR 303](https://github.com/OfficeDev/office-js-docs-pr/pull/303) for this link.
