### ISSUE TITLE
Adding <Icon> element as a child of <Group> raises exception when trying to install the manifest

### ISSUE THREAD

**Issue by balazserdeszlogmein** [OfficeDev/office-js-docs-pr#2737]
The documentation says, `<Icon>` is a required element under `<Group>`.
But when adding an ``<Icon> element, the manifest cannot be installed, because it says "only Tooltip and Control are acceptable elements in a Group".

The same is true for `<Title>` under `<Action>` by the way. I suspect these are not available in Outlook add-ins, but the documentation do not mention this information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 540ad65e-a396-ce57-34fa-00e490028f0d
* Version Independent ID: d7807a56-e4d6-aa64-0dd8-3af677b9849d
* Content: [Group element in the manifest file - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/group)
* Content Source: [docs/reference/manifest/group.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/manifest/group.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for raising this issue @balazserdeszlogmein.

@Rick-Kirkham, could you please investigate?

**Comment by Rick-Kirkham** [comment]
You are correct. I will update the docs.
