### ISSUE TITLE
How to deploy add-in to Azure App Service?  Getting error 'npm ERR! Exit status 2' or 'You do not have permission to view this directory or page.'

### ISSUE THREAD

**Issue by pnguyenRCUS** [OfficeDev/office-js-docs-pr#2746]
Hello,
How to go about deploying a yeoman generated Office Add-in to Azure App Service?
Need some links for guidance on how to run Add-in from Azure App Service not from localhost under **Next steps** section of https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/outlook-quickstart?tabs=yeomangenerator

I followed this guide https://docs.microsoft.com/en-us/azure/app-service/quickstart-nodejs?pivots=platform-linux to deploy to Azure App Service and getting error 'npm ERR! Exit status 2' on a Linux instance or 'You do not have permission to view this directory or page.' on a Windows instance.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 930ce4fc-c8b8-f756-f03f-a716f1ef7883
* Version Independent ID: 753a2e38-9430-25bb-5409-b7eed9c88e47
* Content: [Build your first Outlook add-in - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/outlook-quickstart?tabs=yeomangenerator)
* Content Source: [docs/quickstarts/outlook-quickstart.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/quickstarts/outlook-quickstart.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@pnguyenRCUS Thanks for your question. Can you take a look at [Publish an add-in developed with Visual Studio Code](https://docs.microsoft.com/office/dev/add-ins/publish/publish-add-in-vs-code) and let us know whether or not it helps?

Thanks.

**Comment by pnguyenRCUS** [comment]
Thanks @ElizabethSamuel-MSFT for the link. The new link is useful and should be added under Next steps section of https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/outlook-quickstart?tabs=yeomangenerator

While your new link helps provide information needed to deploy outside of localhost.
Add-in still failed to install or run outside of localhost.
There are few steps that are not same. I don't have option **Deploy to Static Website** only **Deploy to Web App** or **Deploy to Static Website via Azure Storage**
![image](https://user-images.githubusercontent.com/26148445/121757988-703f3480-cad4-11eb-8489-a46faa4cedf9.png)

If do **Deploy to Static Website via Azure Storage**
Browse storage site url, does give message, "Please sideload your add-in to see app body."
However, when side-load the Add-in using the storage url, got error below:
Installation failed
This app can't be installed. The manifest XML file isn't valid. For security reasons DTD is prohibited in this XML document. To enable DTD processing set the DtdProcessing property on XmlReaderSettings to Parse and pass the settings into XmlReader.Create method..
![image](https://user-images.githubusercontent.com/26148445/121758177-3589cc00-cad5-11eb-92e6-754a324780db.png)

I will continue to search on this error. If you have any resolution for this, please do suggest.


If I do **Deploy to Web App**, when side load the Add-in using the web app url, got a different error.
![image](https://user-images.githubusercontent.com/26148445/121758162-2440bf80-cad5-11eb-955d-932502f4250a.png)
Note: Browse site have error when do this way.
![image](https://user-images.githubusercontent.com/26148445/121758228-6833c480-cad5-11eb-8fe5-ed3e70cf9a68.png)

Question: is Deploy to Web App option supported for Office Add-in or not? 

Thanks

**Comment by ElizabethSamuel-MSFT** [comment]
@pnguyenRCUS Perhaps the following link can help you get unblocked (thanks for sharing this, @davidchesnut):

https://github.com/OfficeDev/Office-Add-in-NodeJS-SSO/issues/61

@davidchesnut is also planning to refine the deployment article so do let us know any other feedback you have about your experience.

Thanks.

**Comment by pnguyenRCUS** [comment]
Thanks for the info but I am still unable to host Add-in outside of development environment.

Without success hosting with App Service and VS Code deployment tool, I attempted to host Add-In on node-js on linux and nginx as reverse proxy server but Add-In does failed to startup on linux: 

![image](https://user-images.githubusercontent.com/26148445/122655080-adbf4580-d104-11eb-9d0a-803b482a1902.png)

After further search, looks like I am not the only one with similar issues, looking at this repo https://github.com/OfficeDev/generator-office/issues?q=is%3Aissue+linux
