### ISSUE TITLE
Visual Studio step

### ISSUE THREAD

**Issue by yowl** [OfficeDev/office-js-docs-pr#2748]
I know that yeoman is your preferred development option.  But VS is good too, so if you are using VS you need to put the 'Requirements' section after 'Hosts' and before 'DefaultSettings'  in the manifest. You could mention that somewhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a1bb1ec-f7c0-61c7-bd50-4018a2726e3a
* Version Independent ID: dabd68f4-f474-1f01-0022-b2fe55eaafa3
* Content: [Configure your Office Add-in to use a shared JavaScript runtime - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/configure-your-add-in-to-use-a-shared-runtime)
* Content Source: [docs/develop/configure-your-add-in-to-use-a-shared-runtime.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/configure-your-add-in-to-use-a-shared-runtime.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for reporting this @yowl. 

@davidchesnut, can you please investigate?

**Comment by AlexJerabek** [comment]
Hi @yowl,

https://github.com/OfficeDev/office-js-docs-pr/pull/2749 will update the docs to address getting the proper manifest in VS.

**Comment by AlexJerabek** [comment]
Hi @yowl, 

#2749 has been checked in and should be live soon. Please let me know if you need anything else. Thanks!
