### ISSUE TITLE
Compatibility Vue3

### ISSUE THREAD

**Issue by jdson** [OfficeDev/office-js-docs-pr#2751]
In reference to: https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-vue

Is there any plan to make it working with Vue3?

**Comment by AlexJerabek** [comment]
Hi @jdson,

I just went through the quick start using the `Default (Vue 3) ([Vue 3] babel, eslint)` option for the vue CLI. That seemed to work fine. Was there a particular issue that you encountered?

Thanks!

**Comment by jdson** [comment]
Hi @AlexJerabek,

The taskpane appears in Excel but remains empty, I can just click on Reload and Security Info.
I get these errors when I load or reload the add-in (Edge DevTools Preview):

HTML1300: Navigation occurred.
taskpane.html (1,1)

[HMR] Waiting for update signal from WDS...

SCRIPT5007: SCRIPT5007: Unable to get property 'config' of undefined or null reference
taskpane.html (18,1)

XML5632: Only one root element is allowed.
taskpane.html (1,1)

[WDS] Disconnected!

0: Office.js has not fully loaded. Your app must call "Office.onReady()" as part of it's loading sequence (or set the "Office.initialize" function). If your app has this functionality, try reloading this page.
office.js (45,28826)

Everything is working well if I generate the project by selecting Vue2.

Thank you

**Comment by AlexJerabek** [comment]
Thanks @jdson.

Could you also let me know the following information:
- Platform? (Desktop, Mac, Web)
- Office [version and build](https://support.microsoft.com/en-us/office/about-office-what-version-of-office-am-i-using-932788b8-a3ce-44bf-bb09-e334518b8b19)?

**Comment by jdson** [comment]
Hi @AlexJerabek,

Windows 10 20H2 (OS Build 19042.1052)
Excel 2016 MSO (16.0.14026.20202) 32-bit

Thank you

**Comment by AlexJerabek** [comment]
Hi @jdson,

Thanks for the information. In testing this on Excel for the web, I think I found the issue. Could you please try the quickstart again, but this time ignore step 2 of "Update the app"? That means your **src/main.js** will not be changed and should look like this:

```js
import { createApp } from 'vue'
import App from './App.vue'

createApp(App).mount('#app')
```

Please let me know if that works and I'll update the documentation. Otherwise, I have this whole theory that this is related to the [IE11 browser control that Excel 2016 uses](https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins).

**Comment by jdson** [comment]
Hi @AlexJerabek,

This is way better now, I can see the Welcome message and I can color cells in green.
However there is still some error messages:

XML5632: Only one root element is allowed.
taskpane.html (1,1)

[WDS] Disconnected!

0: Office.js has not fully loaded. Your app must call "Office.onReady()" as part of it's loading sequence (or set the "Office.initialize" function). If your app has this functionality, try reloading this page.
office.js (45,28826)

Thank you

**Comment by AlexJerabek** [comment]
Oh right, we still need to call `Office.onReady()`. My apologies. Use this **src/main.js**:

```js
import { createApp } from 'vue'
import App from './App.vue'

window.Office.onReady(() => {
    createApp(App).mount('#app');
});
```

Here's the article that details why that step is important: https://docs.microsoft.com/en-us/office/dev/add-ins/develop/initialize-add-in

As for the "one root element" error, based on [this thread](https://www.outsystems.com/forums/discussion/20753/xml5632-only-one-root-element-is-allowed-error-on-windows-edge/), it doesn't seem to be an actual issue that'll affect your add-in.

**Comment by jdson** [comment]
Thanks a lot for you help with this

**Comment by AlexJerabek** [comment]
@jdson Of course, happy to help. Thank you for raising the issue and letting us know about the problem.
