### ISSUE TITLE
Cache busting in react add-ins

### ISSUE THREAD

**Issue by piyumi25** [OfficeDev/office-js-docs-pr#2759]
Can I know any cache busting is possible when deploy the add-in. In angular we can use "npm run build --output-hashing=bundles"  command for cache busting. Is there any way for react add-ins?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ba07460-1e7e-7272-8a36-670a818ef61a
* Version Independent ID: 842eb2f1-4c97-df76-9bf5-75f1dc19f358
* Content: [Fluent UI React in Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/design/using-office-ui-fabric-react)
* Content Source: [docs/design/using-office-ui-fabric-react.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/design/using-office-ui-fabric-react.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by alison-mk** [comment]
Hi @piyumi25, thanks for submitting a question. @Rick-Kirkham can you take a look at this Fluent UI React question? 

Cheers, 
Alison

**Comment by Rick-Kirkham** [comment]
An add-in is just a web app. For the most part, you do things in an add-in exactly the way you would in a web app. So, if cache-busting can be done in a React web app, then it can be done in a React add-in. If not, then not. 

If I search `how to cache bust with react?` in Microsoft Bing, I get a lot of helpful results. It looks like there are multiple ways of doing it in a React web app.
