### ISSUE TITLE
EquivalentAddIns tag support for Outlook Web Add-ins

### ISSUE THREAD

**Issue by JackTheDane** [OfficeDev/office-js-docs-pr#2763]
Hi Team!

We're currently developing a Web Add-in for Outlook to compliment our existing VSTO solution, and are really excited about the possibility of using `EquivalentAddIns` in the Web Add-in manifest to only show the Web Add-in when the VSTO is not present.

However, we have some confusion, as your documentation says that this feature will be available soon, but according to [a recent blog post](https://developer.microsoft.com/en-us/microsoft-365/blogs/whats-new-in-office-platform-at-build-2021/), this API should already be available.

![image](https://user-images.githubusercontent.com/35668734/122936262-4fe36580-d371-11eb-9bd8-4cad6279cfd9.png)

I've also tried using `EquivalentAddIns` using local side-loading, and found that it worked, despite failing to validate during deployment.

Do you have any idea when we can expect this feature to be enabled in Outlook, if it isn't already? ✉

Thanks a lot - Keep up the great work 💪

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e01562c5-ae22-8345-83f5-c1159bbb7cf0
* Version Independent ID: 70835436-060e-807f-3cee-a8ca0f7b6959
* Content: [Make your Office Add-in compatible with an existing COM add-in - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/make-office-add-in-compatible-with-existing-com-add-in)
* Content Source: [docs/develop/make-office-add-in-compatible-with-existing-com-add-in.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/make-office-add-in-compatible-with-existing-com-add-in.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for reporting this discrepancy @JackTheDane.

@ElizabethSamuel-MSFT, can you please investigate?

**Comment by ElizabethSamuel-MSFT** [comment]
@JackTheDane We're still in the process of getting the updated manifest schema out to on-prem Exchange. As such, while it may work for Exchange Online, it may not pass validation as we don't officially support this element in the manifest yet. Also, any users of your add-in may hit errors if their mailbox is on on-prem Exchange. Once the rollout is complete, we'll update the article. Unfortunately, we have not timelines at this moment.

Hope this helps. For now, I'll close this issue but if you have further questions about this, let us know and we can reopen this issue, or you can create a new one.

Thanks.
