### ISSUE TITLE
Clarification on Support for IE11

### ISSUE THREAD

**Issue by andrewgay** [OfficeDev/office-js-docs-pr#2765]
Should new Add-ins continue to support IE11 even with the pending deprecation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00c430f1-bbf5-53b8-a225-4fbe8fc39c3b
* Version Independent ID: 0a069a0d-4d35-71ee-53af-8c55fe8548a0
* Content: [Browsers used by Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins)
* Content Source: [docs/concepts/browsers-used-by-office-web-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/concepts/browsers-used-by-office-web-add-ins.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @andrewgay,

Here's the official statement on IE11's deprecation with regards to Office Add-ins:

> Microsoft is ending support for Internet Explorer, but this doesn't significantly affect Office Add-ins. Some combinations of platforms and Office versions, including all one-time-purchase versions through Office 2019, will continue to use the webview control that comes with Internet Explorer 11 to host add-ins, as explained in this article. Moreover, support for these combinations, and hence for Internet Explorer, is still required for add-ins submitted to AppSource. Two things are changing:
> 
> - AppSource no longer tests add-ins in Office on the web using Internet Explorer as the browser. But AppSource still tests for combinations of platform and Office desktop versions that use Internet Explorer.
> - The Script Lab tool will stop working in Internet Explorer sometime in 2021. 

I think this note was added to the linked document between you creating the issue and me responding. I'm going to close this issue, but I'll tag @Rick-Kirkham in case there's more to say here.
