### ISSUE TITLE
Domains for Access-Control-Allow-Origin header

### ISSUE THREAD

**Issue by wynntee** [OfficeDev/office-js-docs-pr#2771]
Hi, when serving an Office Add-in for Office Online, I currently set the "Access-Control-Allow-Origin" header to a "wildcard" value.

I would like to restrict the header to only the required domains, but I cannot find this information in the docs. For example, is it "officeapps.live.com"? Any other domains?

**Comment by ElizabethSamuel-MSFT** [comment]
@wynntee Thanks for asking about this.

@Rick-Kirkham Is this something you can help with?

Thanks.

**Comment by Rick-Kirkham** [comment]
I'm seeking information internally about this.

**Comment by Rick-Kirkham** [comment]
If you want to try to implement this, here are a couple of articles that might help. But note that new URLs could be added at any time and old ones deprecated. 

[Office 365 URLs and IP address ranges](https://docs.microsoft.com/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide#microsoft-365-common-and-office-online)
[Content Delivery Networks (CDNs)](https://docs.microsoft.com/microsoft-365/enterprise/content-delivery-networks?view=o365-worldwide)
