### ISSUE TITLE
UI for meeting providers

### ISSUE THREAD

**Issue by markdon** [OfficeDev/office-js-docs-pr#2774]
In desktop/web clients our online meeting provider add-in can show a task pane for the user to choose/edit one of their existing meeting rooms or choose settings for a newly created meeting room.

It would seem that this would be possible on mobile by opening a dialog when the user enables the online meeting. 
- Are there any rules relating to what the add-in can do when the enabling the toggle? 

I noticed that if `event.completed({ allowEvent: true });` is not called, the toggle action doesn't complete and eventually times out and notifies the user. 
- Is there a limit on how long the addin can take to add meeting details to the event? 
- Could this timeout occur while the user is in a dialog? e.g. while logging in or selecting a room.

The answers here would be great to include in the docs :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52a55fe4-0fe1-858c-26a4-dddc3ee128ea
* Version Independent ID: 0a643291-936f-b374-37fd-7db497c73cce
* Content: [Create an Outlook mobile add-in for an online-meeting provider - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/online-meeting)
* Content Source: [docs/outlook/online-meeting.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/outlook/online-meeting.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@markdon Thanks for asking about this.

@exextoc Can you respond to these questions?

We can update the docs as appropriate after that.

Thanks.

**Comment by exextoc** [comment]
Hi @markdon, there is a limited set of APIs available for the online meeting scenarios. You can refer to https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/online-meeting for the set of available APIs.
There is a timeout of 1 min for the Add-in to populate the required information. This excludes any time spent on a dialog box launched by Add-in, e.g. authentication dialog box. We will update our document to reflect this.

**Comment by ElizabethSamuel-MSFT** [comment]
@markdon Thanks again for raising this. The updated article should be published soon.

Let us know if we can provide any further help.

Thanks.
