### ISSUE TITLE
invocation code doesn't work.

### ISSUE THREAD

**Issue by zhangxj19** [OfficeDev/office-js-docs-pr#2777]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a30fb645-c853-a93a-4137-1e2bf7398a11
* Version Independent ID: 75fb99ac-72e8-7bdc-ff1b-85e7ed930d50
* Content: [Excel custom functions tutorial - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/excel-tutorial-create-custom-functions?tabs=excel-windows#create-a-custom-function-that-requests-data-from-the-web)
* Content Source: [docs/tutorials/excel-tutorial-create-custom-functions.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/tutorials/excel-tutorial-create-custom-functions.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@zhangxj19 Thanks for letting us know about this. Can you share any additional details about what behavior you're seeing? Also, can you let us know where you're trying this (browser, Windows)?

@alison-mk Can you take a look?

Thanks.

**Comment by alison-mk** [comment]
Hi @zhangxj19, thanks for submitting an issue. I've tested this custom functions tutorial and added a fix for a bug in the *Create a streaming asynchronous custom function* section. It's in PR #2796 now. Once that PR is merged, this issue will automatically close. Let us know if you have any additional questions or concerns. 

Cheers, 
Alison
