### ISSUE TITLE
Manifest file's default Taskpane.Url is incorrect for the example Vue project (Fix issue with Add-in not side loading)

### ISSUE THREAD

**Issue by jadjare** [OfficeDev/office-js-docs-pr#2790]
Having spent sometime attempting to side-load the basic Vue based Excel Office Addin created by following tutorial steps and not being able to figure out why it won't load, I have discovered that the Taskpane.Url is pointing to a .html file that doesn't exist.

To fix the issue it is necessary to update the `manifest.xml` file and find the entry
```xml
<bt:Url id="Taskpane.Url" DefaultValue="https://localhost:3000/taskpane.html" />
```
This entry refers to a non-existant taskpane.html file.  Change the entry so it points to you `index.html` file, thus
```xml
<bt:Url id="Taskpane.Url" DefaultValue="https://localhost:3000/index.html" />
```

Please update the tutorial to either include a step to help the user understand the `manifest.xml` file and check and update the entry where necessary.

Overall, the tutorial could do with more details on the key entries in the `manifest.xml` file, what they're used for, and when the should be changed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea230e95-f483-6d19-8167-2341a03cf396
* Version Independent ID: 3846765f-7587-fec4-711e-84edfce9c30c
* Content: [Build an Excel task pane add-in using Vue - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-vue)
* Content Source: [docs/quickstarts/excel-quickstart-vue.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/quickstarts/excel-quickstart-vue.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for reporting this @jadjare.

@alison-mk, could you please take a look?

**Comment by alison-mk** [comment]
Hi @jadjare, thank you for reporting this issue and providing feedback. I've updated the article to incorporate your suggestions, and those changes are now in PR #2795. Once the PR is merged, this issue will automatically close. Let us know if you have any additional questions or concerns. 

Cheers, 
Alison
