### ISSUE TITLE
Switching to IE is not working for none Yo Neoman generated projects 😒

### ISSUE THREAD

**Issue by ndeeH** [OfficeDev/office-js-docs-pr#2807]
Is there a chance to switch to IE for tests for other type of SPA add ins?

**Comment by ElizabethSamuel-MSFT** [comment]
@ndeeH Thanks for asking about this. However, can you clarify if you're working with SharePoint Add-ins - or what you mean by SPA?

Your response can help us point you in the right direction. This repo is related to Office Add-ins but doesn't include SharePoint Add-ins.

Thanks.

**Comment by ndeeH** [comment]
Hi @ElizabethSamuel-MSFT ,
no SPA means Single Page Application - our add in is a AngularJS SPA. 
The provided information in the documentation does not work for all kind of projects which are not created by the Yo Neoman tooling.
(I cant find the help page to this issue - I simply clicked on a button below to add a feedback - where is the documentation linked=

**Comment by ElizabethSamuel-MSFT** [comment]
@ndeeH Thanks for your response. Can you share more details about your situation? E.g., Office application you're using, the doc page you're looking at, etc.

Thanks.
