### ISSUE TITLE
Access to OData is disabled in Outlook REST API

### ISSUE THREAD

**Issue by clavx** [OfficeDev/office-js-docs-pr#2808]
We have created an add-in that sends requests to the Outlook REST API based on the following document.

https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/use-rest-api

An error occurred when an external server sent a request using the retrieved token.

```
HTTP/1.1 403 Forbidden

{"error":{"code":"ErrorAccessDenied","message":"Access to OData is disabled."}}
```

Based on the error message, we searched and found the following information.

https://blogs.msdn.microsoft.com/wushuai/2017/04/01/how-to-fix-access-to-odata-is-disabled-when-calling-graph-api/

We checked whether `EwsApplicationAccessPolicy` was set or not from the following command, but it was not set for the relevant tenant.

```powershell
Get-OrganizationConfig | select EwsApplicationAccessPolicy, EwsAllowList, EwsBlockList
```

We looked for other related documents, but could not find any.

Could you please provide us with the necessary configuration information or related documentation so that requests to the Outlook REST API are not denied with tokens obtained from the add-in?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fde53b2d-39f8-5b6d-5e37-068b4d93f049
* Version Independent ID: 9c7ff3ef-a188-bd28-65bb-1d620d4a8842
* Content: [Use the Outlook REST APIs from an Outlook add-in - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/use-rest-api)
* Content Source: [docs/outlook/use-rest-api.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/outlook/use-rest-api.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@clavx Thanks for asking about this.

@exextoc Can you take a look?

Thanks.

**Comment by exextoc** [comment]
@clavx Do you hit this error when the add-in is making the REST request or are you using the token provided by the addin (by calling getCallbackTokenAsync with isRest true) and making a REST request through an external server using this token?

**Comment by clavx** [comment]
Thank you for your response. 

> are you using the token provided by the addin (by calling getCallbackTokenAsync with isRest true) and making a REST request through an external server using this token?

We tested only this way.

We didn't check the behavior when the add-in made a REST request.

We would like to confirm this, but the tenant experiencing the issue is a customer environment, so it is expected to take some time.

**Comment by exextoc** [comment]
Just a follow-up here, this documentation page has some useful information that might help with configuring your customer's ApplicationAccessPolicy:
https://docs.microsoft.com/en-us/graph/auth-limit-mailbox-access
