### ISSUE TITLE
Mention Office.onReady as Office.initialize alternative

### ISSUE THREAD

**Issue by nikolay-borzov** [OfficeDev/office-js-docs-pr#282]
Source https://github.com/OfficeDev/office-js/issues/5#issuecomment-382189046

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af6ccc36-8ea8-af6e-8731-059ce81d8628
* Version Independent ID: 2d98dd01-b671-d532-3bcb-88d40d6ef3d1
* Content: [Loading the DOM and runtime environment](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/loading-the-dom-and-runtime-environment)
* Content Source: [docs/develop/loading-the-dom-and-runtime-environment.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/loading-the-dom-and-runtime-environment.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
We are working on this.

**Comment by Rick-Kirkham** [comment]
onReady is now documented here: https://docs.microsoft.com/en-us/office/dev/add-ins/develop/understanding-the-javascript-api-for-office
