### ISSUE TITLE
npm start results in "'office-addin-debugging' is not recognized"

### ISSUE THREAD

**Issue by VashJuan** [OfficeDev/office-js-docs-pr#2826]
Walked through the Excel Add-in Quickstart and get the above error. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c4ddde7-f1fd-44ba-fba1-0ae9d0131df7
* Version Independent ID: d946ffe6-f29f-1563-b679-121090ba60a1
* Content: [Build your first Excel task pane add-in - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-jquery?tabs=yeomangenerator)
* Content Source: [docs/quickstarts/excel-quickstart-jquery.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/quickstarts/excel-quickstart-jquery.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by VashJuan** [comment]
Tutorial neglects this step:
**npm i office-addin-debugging**

**Comment by AlexJerabek** [comment]
Thanks for raising this @VashJuan. 

@millerds, Can you please take a look? Was this change to the yo office flow intentional?

**Comment by millerds** [comment]
The output from yo office I see says “No change to package.json was detected. No package manager install will be executed.” which means 'npm install' was not run like was expected.  I'm not sure why that is yet, but you'll need to run 'npm install' before 'npm start' when this happens.

**Comment by millerds** [comment]
Looks like the new version of yeoman-generator we took a dependency on (fixing vulnerabilities) changed the way it handled calling 'npm install'.  There is a workaround fix coming.  In the mean time, run 'npm install' before running 'npm start'
