### ISSUE TITLE
ambiguous "you"

### ISSUE THREAD

**Issue by Rick-Kirkham** [OfficeDev/office-js-docs-pr#2830]
The term "you" in this article refers to the developer, but in the **Coauthoring** section, it refers to what end users do. Please rewrite that section so that it talks about users, not "you". 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94ad7803-d4f7-a700-7c7f-204cd8f34e4a
* Version Independent ID: 9c485bae-cab1-bdad-4c8e-baad2b12b22d
* Content: [Create custom functions in Excel - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-overview)
* Content Source: [docs/excel/custom-functions-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/custom-functions-overview.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@Rick-Kirkham Thanks for pointing this out.

@alison-mk Can you take a look?

Thanks.
