### ISSUE TITLE
Custom function quickstart not compatible with actual Yo Office behavior

### ISSUE THREAD

**Issue by Rick-Kirkham** [OfficeDev/office-js-docs-pr#2831]
The article says 

> The Yeoman generator will create the project files and install supporting Node components.

This is no longer correct. the generator completes without error, but it does not run `npm intall`. The sentence should be deleted and an additional step to run `npm install` should be added to the article just before the step to run `npm run build`. 

I'm using 
node 14.17.3
npm 6.17.13
Yo 4.2.0
office-generator 1.7.9

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bac6469-78a6-dae9-e6c4-497c953a1576
* Version Independent ID: d860aff2-60ad-c008-2d10-b046f3198f44
* Content: [Custom functions quick start - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-custom-functions-quickstart?tabs=excel-windows)
* Content Source: [docs/quickstarts/excel-custom-functions-quickstart.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/quickstarts/excel-custom-functions-quickstart.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
@Rick-Kirkham This seems to be a problem across all our quick starts, as discovered in #2826. @millerds is investigating why the yo office flow changed.

**Comment by Rick-Kirkham** [comment]
Closing as a dup of 2826.
