### ISSUE TITLE
Note is in the wrong place in custom functions quick start

### ISSUE THREAD

**Issue by Rick-Kirkham** [OfficeDev/office-js-docs-pr#2832]
The article has a note about installing certificate after the step to run `npm run build`, but the prompt doesn't actually come until after the NEXT step to run `npm run start:desktop`.

![image](https://user-images.githubusercontent.com/9088056/127409296-dfa08fae-a17c-4a0d-89b6-cd8e0f711caf.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bac6469-78a6-dae9-e6c4-497c953a1576
* Version Independent ID: d860aff2-60ad-c008-2d10-b046f3198f44
* Content: [Custom functions quick start - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-custom-functions-quickstart?tabs=excel-windows)
* Content Source: [docs/quickstarts/excel-custom-functions-quickstart.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/quickstarts/excel-custom-functions-quickstart.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@Rick-Kirkham Thanks for taking the time.

@alison-mk Can you take a look?

Thanks.
