### ISSUE TITLE
Need to orient the reader and spell out "XLL" and correct support note

### ISSUE THREAD

**Issue by Rick-Kirkham** [OfficeDev/office-js-docs-pr#2837]
This article is confusing because:

1. It never spells out what "XLL" means. 
2. It assumes distinction between XLL user-defined functions, XLL compatible custom functions, and Excel add-in custom functions; but it never spells out what these are or how they are distinct from each other. 
3. The note near the top says that COM add-ins and UDFs are supported on web, Mac, and Windows. This is not true. COM (and I assume UDFs) are not supported on either web or Mac. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e6816e9-a82d-012d-de66-5f802b02dba5
* Version Independent ID: 87992af8-d49e-337a-253c-922d56e1281b
* Content: [Extend custom functions with XLL user-defined functions - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/make-custom-functions-compatible-with-xll-udf)
* Content Source: [docs/excel/make-custom-functions-compatible-with-xll-udf.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/make-custom-functions-compatible-with-xll-udf.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@Rick-Kirkham Thanks for noting this.

@alison-mk Can you take a look?

Thanks.

**Comment by alison-mk** [comment]
Some issues noted here are resolved by PR #2895. The remaining unresolved issues will be tracked in an [internal work item](https://office.visualstudio.com/OC/_workitems/edit/5368630).
