### ISSUE TITLE
Erroneous note and confusing terminology

### ISSUE THREAD

**Issue by Rick-Kirkham** [OfficeDev/office-js-docs-pr#2838]
The note near the top says that IE is always used for custom functions. This is no longer true. If the conditions for using Edge WebView2 are met, as described in the "Browsers used by Office Add-ins" article, then WebView2 is used for custom functions. Else, IE is used.

The phrase "UI-less custom function" is confusing because it implies that there are custom functions that DO have a UI, but that's not the case, as near as I can tell. Beyond the UI that Excel itself provides in the function bar, ALL custom functions are UI-less. There are some _add-ins_ that have a UI (with or without some custom functions too) and there are some _add-ins_ that have only one or more custom functions (so they are UI-less). But using "UI-less" to designate a type of _custom function_ makes no sense to me. 

Both points also apply to https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-debugging

and https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-runtime

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41545a25-b635-de53-a4aa-36ab4108f817
* Version Independent ID: d7ce1841-184d-38f1-b81b-96d5ef887538
* Content: [Authentication for UI-less custom functions - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-authentication)
* Content Source: [docs/excel/custom-functions-authentication.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/custom-functions-authentication.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@Rick-Kirkham Thanks for this update.

@alison-mk Can you take a look?

Thanks.
