### ISSUE TITLE
Puzzles about the code sample

### ISSUE THREAD

**Issue by Rick-Kirkham** [OfficeDev/office-js-docs-pr#2839]
The code sample on this page:

1. Why does the sample use `Excel.RequestContext` instead of `Excel.run`? This conflicts with the normal best practice. If there's a reason for not using Excel.run in an custom function, the article should explain what it is. 
2. The sample has an empty load, `range.load()`, which is a bad practice. I think it should be `range.load("values")`.
3. The sample does exactly what the built-in function `=cell("contents", SOME-CELL-ADDRESS-HERE)` does, so it isn't really an example of a scenario that would require a custom function. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fe047a0-5f60-f407-2ad0-7f4cc8e52082
* Version Independent ID: f2ebc9bd-25f6-cfc2-dbbe-d0090096f656
* Content: [Call Excel JavaScript APIs from a custom function - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/call-excel-apis-from-custom-function)
* Content Source: [docs/excel/call-excel-apis-from-custom-function.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/call-excel-apis-from-custom-function.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@Rick-Kirkham Thanks for clarifying this.

@alison-mk Can you take a look?

Thanks.

**Comment by alison-mk** [comment]
Closing issue as it's partially resolved by #2911. Converted remaining concerns to [internal work item](https://office.visualstudio.com/OC/_workitems/edit/5383233).
