### ISSUE TITLE
NPM Error: missing script: sideload

### ISSUE THREAD

**Issue by laultman** [OfficeDev/office-js-docs-pr#284]
## Issue

Following the steps in: Build your first Excel Add-in.  The documentation here: https://docs.microsoft.com/en-us/office/dev/add-ins/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins
Second bullet on the page has instructions to "npm run sideload" from the root folder of the project. Following the instructions produces the following: (notice the error in line 4 - stops me dead cold)
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'sideload' ]
2 info using npm@5.6.0
3 info using node@v8.11.3
4 verbose stack Error: missing script: sideload
4 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:151:19)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:61:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:115:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:402:5
4 verbose stack     at checkBinReferences_ (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:357:45)
4 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:400:3)
4 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:160:5)
4 verbose stack     at ReadFileContext.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:332:20)
4 verbose stack     at ReadFileContext.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16)
4 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
5 verbose cwd C:\b\Excel-API\Excel-Add-in-Tutorial-master\Excel-Add-in-Tutorial-master\Start
6 verbose Windows_NT 10.0.17134
7 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "sideload"
8 verbose node v8.11.3
9 verbose npm  v5.6.0
10 error missing script: sideload
11 verbose exit [ 1, true ]

This link further down the page: Validate and troubleshoot issues with your manifest
was of no value.  There appears to be a missing file from the clone project on GitHub but I have no way to verify the issue. Thus the getting started tutorial does not work.
Larry

**Comment by AlexJerabek** [comment]
Hi @laultman, 
Sorry to hear you're having problems. Could you please clarify for me which path you took in the [Build your first Excel add-in](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-get-started-overview) quick start? Which editor and framework did you use?

**Comment by laultman** [comment]
I started here: https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/excel-tutorial
Begin: https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/excel-tutorial?tutorial-step=1
I followed the prerequisites verifying that I had the correct version of Excel 2016 (1803) in my case.  I installed Node.js 18.1.3 current and I installed latest Git Bash 2.18.0
Then I followed the Setup steps, downloading the project to my local machine and completing the remainder of the steps in turn.
NEXT: https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/excel-tutorial?tutorial-step=2
I used Visual Studio Code (current version) to edit the files. I completed each step and saved my work in Visual Studio Code. I then started the “Test the add-in”.  I completed steps 1-3 of this section and used the Windows: Sideload Office Add-ins on Windows link. To here: https://docs.microsoft.com/en-us/office/dev/add-ins/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins
The second bullet point on the page.
I opened a second Node.js Command window, navigated to the Start folder in the project where the manifest file is located.
I attempted to execute the “npm run sideload” command.
It failed at that point with the missing script error.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by laultman** [comment]
Courtney,
I did end up using the shared folder steps to get it to work. But the instructions are still incorrect. This was my very first attempt at an Office Add-in so it is disconcerting when you follow the steps and then the test project to validate your setup configuration, itself, does not work.  So you end up trying a couple more times (wasting lots of time) to finally reach the conclusion that the test project is the problem.  What should have been 30 minutes ended up taking an afternoon.
Larry

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by TCourtneyOwen** [comment]
Hi Larry,

I couldn't agree with your more, and thank you for bringing this to our attention.  I will talk to our writers about getting the documentation updated ASAP. I think we should also get a sideload script added to the tutorial project because running "npm run sideload" is much easier than sideloading a manifest via a shared folder.

-Courtney

**Comment by laultman** [comment]
I agree, and I felt comfortable with the npm approach. Shared folders, completely new to me in this context.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Rick-Kirkham** [comment]
I think the problem here is the second bullet at the top of this article https://docs.microsoft.com/en-us/office/dev/add-ins/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins that was added last month. Other articles and sample readmes link to this article, but they do not necessarily have a sideload script, so this article should not suggest that as an alternative. The "npm run sideload" method only works for projects that are created with a sideload script. Very few of our existing samples will meet that criterion. What I think we need to do is 
1) Remove that 2nd bullet from the article

2) Retitle the article "Sideload Office Add-ins for testing from a network share"

Unless I hear objections, I will do that today.

**Comment by TCourtneyOwen** [comment]
Ricky, are you referring to this bullet point:
    **Running the "npm run sideload" command from the root of the add-in project folder.**

I do think we need to have a link somewhere to the documentation for using "npm run sideload", since we recently added the sideload script to all projects generated via Yo Office.

-Courtney

**Comment by Rick-Kirkham** [comment]
Yes. That's the bullet I was referring to. If you want the two articles, that I linked to, to link to each other, then we have to do it in a way that makes clear that these are _not_ two alternatives that will _both_ work for _any_ project. There are in fact very few projects in existence now for which the  "npm run sideload" technique will work. It only works for projects created with `yo office` very recently.

**Comment by Rick-Kirkham** [comment]
This work is done in the source files and should be published soon.
