### ISSUE TITLE
Inconsistent and imprecise guidance

### ISSUE THREAD

**Issue by Rick-Kirkham** [OfficeDev/office-js-docs-pr#2840]
Near the top of the article, "set the cell's number format" is mentioned as an appropriate scenario for calling Excel.js in a custom function, but near the end of article "set properties" is listed as one of the things that should _not_ be done in a custom function. 

"execute most methods" is listed at the end as one of things that should not be done in a custom function. That "most" is not very helpful. Can we have more guidance about what sorts of methods are likely to be problematic and what sorts are likely to be safe? For example, are `get*` methods safe? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fe047a0-5f60-f407-2ad0-7f4cc8e52082
* Version Independent ID: f2ebc9bd-25f6-cfc2-dbbe-d0090096f656
* Content: [Call Excel JavaScript APIs from a custom function - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/call-excel-apis-from-custom-function)
* Content Source: [docs/excel/call-excel-apis-from-custom-function.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/call-excel-apis-from-custom-function.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@Rick-Kirkham Thanks for asking about this.

@alison-mk Can you take a look?

Thanks.

**Comment by alison-mk** [comment]
Converted to [internal work item](https://office.visualstudio.com/OC/_workitems/edit/5383233).
