### ISSUE TITLE
WebSocket code sample for custom functions lacks context

### ISSUE THREAD

**Issue by Rick-Kirkham** [OfficeDev/office-js-docs-pr#2841]
The **WebSockets** section does not provide enough context for the code sample to be of any use. 

Should this code be global in the functions.js file or should it be inside a custom function? 

If the former, then how is this code connected to a custom function?

If the later, then where in the custom function does it go? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 667d1e98-4a95-318f-0df1-182722370ac8
* Version Independent ID: f8265387-ba9d-a5db-ef44-8409441b2ece
* Content: [Receive and handle data with custom functions - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-web-reqs)
* Content Source: [docs/excel/custom-functions-web-reqs.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/custom-functions-web-reqs.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@Rick-Kirkham Thanks for giving custom functions a try and asking about this.

@alison-mk Can you take a look?

Thanks.

**Comment by mscharlock** [comment]
@alison-mk hit me up if you need some context on this article. The web sockets stuff is from way way back in the day.

**Comment by alison-mk** [comment]
Moved to internally-tracked [work item](https://office.visualstudio.com/OC/_workitems/edit/5365817).
