### ISSUE TITLE
Debugging config not available

### ISSUE THREAD

**Issue by Rick-Kirkham** [OfficeDev/office-js-docs-pr#2842]
The section **Use the VS Code debugger for Excel Desktop** says the following for step 5: 

> From the Run drop-down menu, choose **Excel Desktop (Custom Functions)**.

But there is no such option.
![image](https://user-images.githubusercontent.com/9088056/127723943-5451d2a2-51c9-490d-9c29-bd1c2116118b.png)

Choosing **Add configuration** brings a list of options, but none of them is *Excel Desktop (Custom Functions)**.

Also, the dropdown is not called "Run". It is called "RUN AND DEBUG".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0bedd430-d224-565e-c1b1-15f90994aa52
* Version Independent ID: b41539c4-c9ec-c678-e44b-27bd456b9c0b
* Content: [UI-less custom functions debugging - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-debugging)
* Content Source: [docs/excel/custom-functions-debugging.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/custom-functions-debugging.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
@mscharlock, could you please investigate?

**Comment by mscharlock** [comment]
Yep, likely just VS changes since last time we updated this. This was written pre-webview2, so good catch. Thanks for the heads up @Rick-Kirkham and I will add it to my list of things to update.

**Comment by mscharlock** [comment]
@Rick-Kirkham I'm going to temporarily reassign to you, since we do not immediately know the fix.
