### ISSUE TITLE
these instructions  are not working on out-of-the-box windows machine.... tons of dependencies are missing... please check.

### ISSUE THREAD

**Issue by amitlivnat** [OfficeDev/office-js-docs-pr#2858]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 930ce4fc-c8b8-f756-f03f-a716f1ef7883
* Version Independent ID: 753a2e38-9430-25bb-5409-b7eed9c88e47
* Content: [Build your first Outlook add-in - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/outlook-quickstart?tabs=yeomangenerator)
* Content Source: [docs/quickstarts/outlook-quickstart.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/quickstarts/outlook-quickstart.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @amitlivnat,
Thanks for raising this issue. Could you please tell us what step in the quick start is failing for you? Is there any console output you could provide?
