### ISSUE TITLE
Question for mobile meeting add-in 

### ISSUE THREAD

**Issue by jean-wujingyi** [OfficeDev/office-js-docs-pr#2881]
<img width="571" alt="Screen Shot 2021-08-17 at 1 22 41 PM" src="https://user-images.githubusercontent.com/66811843/129668125-49db64c6-7967-4195-9ede-af1ef1d00811.png">
<img width="563" alt="Screen Shot 2021-08-17 at 1 22 53 PM" src="https://user-images.githubusercontent.com/66811843/129668136-f73b62b3-86ac-4329-b380-3ef363ef4b77.png">

If I installed several custom add-in, just like the screenshot. 
Which add-in will be chosen as default when I create a calendar event?

Sometimes it seems that Outlook will set the add-in which was last-time option as default, but sometimes it's not. 
Is there any rules or reference of mobile meeting add-ins sequences and default option?

And I want to confirm that if there is only one admin-installed add-in, will it replace the default Teams or Skype option?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52a55fe4-0fe1-858c-26a4-dddc3ee128ea
* Version Independent ID: 0a643291-936f-b374-37fd-7db497c73cce
* Content: [Create an Outlook mobile add-in for an online-meeting provider - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/online-meeting#available-apis)
* Content Source: [docs/outlook/online-meeting.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/outlook/online-meeting.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
@ElizabethSamuel-MSFT Can you take a look. Might not be a doc issue.

**Comment by jean-wujingyi** [comment]
any updates?

**Comment by ElizabethSamuel-MSFT** [comment]
@jean-wujingyi Thanks for asking about this. At present, we don't have any Office.js API that allows you to set the default provider. As such, the behavior depends on Outlook itself. It's possible that Microsoft Graph has an option you can use but you'd need to check if that's the case.

Adding @exextoc in case they have any idea of Outlook behavior for this feature.

Thanks.

**Comment by jean-wujingyi** [comment]
Thank you~

**Comment by exextoc** [comment]
Any add-ins which are installed by Admins as Online Meeting add-ins will be shown first to the user. However, once a user selects any other meeting provider, that meeting provider is selected by default for the user for that device.
