### ISSUE TITLE
Need TypeScript examples

### ISSUE THREAD

**Issue by timothyhoffmann** [OfficeDev/office-js-docs-pr#2888]
Please consider adding TypeScript examples. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a714626a-058a-789e-6add-5e9dfb21fd1f
* Version Independent ID: 1b88a28c-fc36-4518-2808-7246f08d9753
* Content: [Use the Office dialog API in your Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins)
* Content Source: [docs/develop/dialog-api-in-office-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/dialog-api-in-office-add-ins.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
Thanks for the suggestion. We periodically review whether to use more TypeScript code snippets. In the past, the conclusion we've always reached is that we don't have sufficient staff to create both JavaScript and TypeScript versions of most snippets and, between the two, it is more important for our audience to provide JavaScript snippets. However, we will review this again soon and I will note your vote in favor of more TypeScript.
