### ISSUE TITLE
Outlook add-ins for Gmail accounts

### ISSUE THREAD

**Issue by abhishek1234321** [OfficeDev/office-js-docs-pr#2890]
This page says Outlook add-ins will be supported on Gmail soon, is there any update on this? I think this coming soon message has been there for years now :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 564bc140-d31e-f042-bd30-b8140b7db416
* Version Independent ID: 9953764b-39ca-d5c0-c1f8-5ca44ec2f472
* Content: [Outlook add-ins for Outlook Mobile - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/outlook-mobile-addins)
* Content Source: [docs/outlook/outlook-mobile-addins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/outlook/outlook-mobile-addins.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@abhishek1234321 Thanks for asking. I believe Gmail accounts are still not supported.

@exextoc Can you confirm if Gmail is currently supported for mobile?

We can remove the "coming soon" text in that article and instead note whether or not Gmail is currently supported. If/When Gmail is supported in the future, we can update as appropriate.

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@abhishek1234321 We're working on getting this clarified and hope to update the docs soon where appropriate. Thanks for your patience.

**Comment by ElizabethSamuel-MSFT** [comment]
@abhishek1234321 We're updating the documentation to note that Gmail is not currently supported with mobile. If/When support is added, we'll update the documentation at that time to note support.

**Comment by ElizabethSamuel-MSFT** [comment]
@abhishek1234321 We've merged the PR and the update should be published soon.

Thanks.
