### ISSUE TITLE
Exchange Server 2013 addin install error

### ISSUE THREAD

**Issue by jean-wujingyi** [OfficeDev/office-js-docs-pr#2891]
<img width="638" alt="Screen Shot 2021-08-20 at 5 04 19 PM" src="https://user-images.githubusercontent.com/66811843/130209300-5e438823-f535-4af1-92d0-2109ee8860ea.png">

<img width="1017" alt="Screen Shot 2021-08-20 at 5 05 13 PM" src="https://user-images.githubusercontent.com/66811843/130209426-bcda61eb-3c3d-4dd3-a299-676b5e2d59fe.png">
I'm try to install addins through Exchange Admin Center by following guidance(Which has been published to Office 365 store and works fine). But when they try to install our addin it says:

This app isn't supported by the version of Exchange Server that your account connects to.

I'm using Exchange Server 2013 and the definition of Mailbox is as below: 

<Requirements>
  <bt:Sets DefaultMinVersion="1.1">
    <bt:Set Name="Mailbox" />
  </bt:Sets>
</Requirements>

https://apps.ringcentral.com/integration/office-add-ins/jean/test.xml

This is the manifest, pls take look, thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f64b1bd7-bca4-bd7f-1128-22128c9e7fff
* Version Independent ID: c226c210-6a8a-8eab-4691-f53c9e9576f8
* Content: [Outlook add-in commands - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/add-in-commands-for-outlook)
* Content Source: [docs/outlook/add-in-commands-for-outlook.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/outlook/add-in-commands-for-outlook.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@jean-wujingyi Thanks for asking about this. Your manifest seems to include add-in commands and I believe that feature is not supported in Exchange Server 2013.

Adding feature crew to take a look. @exextoc, can you confirm/deny and provide any other input?

We can clarify in the docs if needed.

Thanks.

**Comment by exextoc** [comment]
App Commands are indeed not supported on Exchange 2013. It should ignore the VersionOverrides section and load the older "gray bar" extension. 

Do you have the latest Updates for Exchange 2013? 

https://docs.microsoft.com/en-us/exchange/updates-for-exchange-2013-exchange-2013-help

**Comment by jean-wujingyi** [comment]
> App Commands are indeed not supported on Exchange 2013. It should ignore the VersionOverrides section and load the older "gray bar" extension.
> 
> Do you have the latest Updates for Exchange 2013?
> 
> https://docs.microsoft.com/en-us/exchange/updates-for-exchange-2013-exchange-2013-help

Thanks for tell about this. 
You mean if I wans to make this Add-in worked, I need to make sure I has installed the latest Updates for Exchange 2013?

**Comment by exextoc** [comment]
The Giant Caveat here is that Exchange 2013 is lacking a lot of features that more recent versions of Exchange/Outlook support. It is possible, that if you connect the current version of Outlook Win32, to Exchange 2013 that your add-in may work, depending on the functions that your add-in calls. In your manifest you are supposed to define the Minimum API Set that your add-in needs. and Exchange will not deliver manifests that are not suppported by your Server/Client Combo. 

To answer your recent question, RTM and older versions of Exchange 2013, did not have support for API Set 1.1, which I believe you may be hitting that error when trying to install your add-in. Updating Exchange 2013 will allow manifests with 1.1 to be installed. 

BUT App Commands will NOT work on Exchange 2013 Outlook Web Access. OWA on Exchange 2013 has no support for App Commands. It is likely that if you connect a client to Exchange 2013 that DOES support App Commands, that the client will be able to read the Version Overrides section, and still display your add-in.... However, if you depend on any APIs that need updated servers (i.e. REST Token, SSO, etc.) It probably won't work. (note that if you DO depend on those APIs you should declare so in your Supported API Set, as mentioned above)

It is also important to know that Exchange 2013 is out of Support, and is not receiving new updates. (in fact Exchange **2016**, recently received it's last CU a few months ago)

**Comment by exextoc** [comment]
Just to clarify further, Exchange 2013 has been out of Mainstream Support since April 10th, 2018.
Extended Support will end on April 11th, 2023.
Source : https://docs.microsoft.com/en-us/lifecycle/products/exchange-server-2013

So if you are on Mainstream Support, please upgrade to a newer version of Exchange.
If you are on Extended Support, everything we have mentioned already applies, so you will be have a restricted experience with certain features/APIs not working as expected.

**Comment by jean-wujingyi** [comment]
After updating latest version of exchange 2013, it is worked now.
