### ISSUE TITLE
Put a warning in the docs that individual developers will get rejected from publishing

### ISSUE THREAD

**Issue by thatusernamenotavailable** [OfficeDev/office-js-docs-pr#2892]
The only way to actually `publish` an Add-in using this repo is to be part of a larger company. Individuals and sole proprietors will get rejected from opening up a developer account at `https://partner.microsoft.com` even after submitting endless documentation. I feel like the README should warn individual developers BEFORE they start developing. 

![verification](https://user-images.githubusercontent.com/66221456/84820334-b4d5e400-afd6-11ea-98fe-3714136a1c45.png)

Please see: https://stackoverflow.com/questions/62416240/how-do-i-verify-a-company-account-so-i-can-publish-an-office-javascript-add-in

**Comment by Rick-Kirkham** [comment]
@thatusernamenotavailable Please specify which article needs the warning. Thanks.
