### ISSUE TITLE
Extend CustomTab in office add-ins with multiple add-ins

### ISSUE THREAD

**Issue by PrashanthReddy7** [OfficeDev/office-js-docs-pr#2903]
## Article URL
https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/customtab

## Issue
I have created a custom tab called "MyAddIns" in outlook, this was created with first add-in called "A" and its working fine.
Now, I have another outlook add-in called "B", I wants to add "B" add-in to exist/already created custom tab "MyAddIns".
How can I do that? Do I needs to use Office Tab or Custom Tab tag in manifest.xml ? If yes, how can we add exist tab reference?

**Comment by Rick-Kirkham** [comment]
I'm sorry, but this cannot be done. There isn't any way for an add-in to add anything to a custom tab that was created with another add-in. Each add-in must have it's own custom tab.
