### ISSUE TITLE
How to open the Office on the web in Internet Explorer

### ISSUE THREAD

**Issue by gummybuns** [OfficeDev/office-js-docs-pr#2904]
> To test your add-in on the Internet Explorer 11 browser, open Office on the web in Internet Explorer and sideload the add-in.

Opening outlook.com (or going through Office365 to get to the Outlook Web Application) immediately opens up an Edge browser instead and redirects IE11 to https://support.microsoft.com/en-us/topic/this-website-works-better-in-microsoft-edge-160fa918-d581-4932-9e4e-1075c4713595?ui=en-us&rs=en-us&ad=us

Is there a way to actually use the Outlook Web Application in an IE11 browser?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47b7b417-12e6-193f-6b89-37e088b31dbc
* Version Independent ID: df705bd2-5f2f-2c84-0519-fca9a3c45d71
* Content: [Internet Explorer 11 testing - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/ie-11-testing)
* Content Source: [docs/testing/ie-11-testing.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/ie-11-testing.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@gummybuns Thanks for asking about this.

@Rick-Kirkham, @exextoc Any guidance here?

Thanks.

**Comment by Rick-Kirkham** [comment]
@exextoc I can reproduce. This is new behavior. Happens with WAC and OWA. 
This appears to make it impossible to test add-ins in IE, but it also blocks end users from running Office on the web in IE. And thus there's no need to test the add-in with Office on the web in IE. 

@exextoc If this seems right, let me know and I'll remove all references to this kind of testing from the docs.

**Comment by gummybuns** [comment]
>  but it also blocks end users from running Office on the web in IE

While this is true, it is also possible for users to run Add-ins through the embedded browser of the Outlook Desktop client. Specifically, we have clients _still_ on Outlook 2013. In the past, the easiest way of quickly seeing any IE11 compatibility (css / es6) issues was to quickly try running our add-in from the IE11 browser and opening the debugging tools. This made it very convenient for debugging in a local environment.

**Comment by exextoc** [comment]
"Unfortunately post 17th August 2021 ,support for M365 apps on IE11 is not available"  Please refer https://techcommunity.microsoft.com/t5/microsoft-365-blog/microsoft-365-apps-say-farewell-to-internet-explorer-11-and/ba-p/1591666 . So we do not have any way to test the add-ins in IE now.

**Comment by exextoc** [comment]
Hope this helps. Kindly feel free to reopen the thread if you have any questions.

**Comment by ElizabethSamuel-MSFT** [comment]
Reopening so @Rick-Kirkham can update the docs accordingly.

**Comment by Rick-Kirkham** [comment]
Docs are fixed.
