### ISSUE TITLE
Automatically Open Taskpane with Document article needs new entry for Wopi catalog

### ISSUE THREAD

**Issue by keyur32** [OfficeDev/office-js-docs-pr#2909]
## Article URL
https://docs.microsoft.com/en-us/office/dev/add-ins/develop/automatically-open-a-task-pane-with-a-document

## Issue
Per the new wopi auto-install feature, we have the ability to install add-ins for approved third party wopi hosts, by setting the storeType="wopicatalog".  This is documented here: https://docs.microsoft.com/en-us/openspecs/office_standards/ms-owexml/d4081e0b-5711-45de-b708-1dfa1b943ad1

I would suggest we:
a) Add a row for it in the main article, per https://github.com/OfficeDev/office-js/issues/422
b) We should also add a link to the instructions on how to setup user's WOPI environment to have add-ins run in them, as described here: https://wopi.readthedocs.io/en/latest/scenarios/hostinstalladdins.html

**Comment by AlexJerabek** [comment]
Hi @keyur32,

Thanks for creating this issue. I'm assuming by "add a row", you're talking about that table for the Open XML values, right? If so, could you please provide the another values? I could only figure out the `storeType` value from the linked thread.

storeType value | id value | store value | version value
-- | -- | -- | --
OMEX (AppSource) | The AppSource asset ID of the add-in (see Note) | The locale of AppSource; for example, "en-us". | The version in the AppSource catalog (see Note)
FileSystem (a network share) | The GUID of the add-in in the add-in manifest. | The path of the network share; for example, "\\MyComputer\MySharedFolder". | The version in the add-in manifest.
EXCatalog (deployment via the Exchange server) | The GUID of the add-in in the add-in manifest. | "EXCatalog". EXCatalog row is the row to use with add-ins that use Centralized Deployment in the Microsoft 365 admin center. | The version in the add-in manifest.
Registry (System registry) | The GUID of the add-in in the add-in manifest. | "developer" | The version in the add-in manifest.
wopicatalog | ??? | ??? | ???
