### ISSUE TITLE
Missing information about Windows Server 2012/2016/2019 environments

### ISSUE THREAD

**Issue by ferrykranenburgcw** [OfficeDev/office-js-docs-pr#2912]
We use this page all the time because we need all our clients te migrate to Office 365 and install the WebView2 plugin so our Outlook add-in will be loaded inside the new Edge browser. The add-in is not compatible with IE11.

There are some issues with the documentation.

- It is not clear what Windows OS our clients are running if they run on terminal/Citrix on Windows Server 2012R2/2016/2019.
- The documentation states: `The embeddable WebView2 control must be installed so that Office can embed it, and it is not installed with Edge automatically. It is installed with Microsoft 365, version 2101 or later`. But in practice the new Edge is only loaded in build 2104 or higher. Also some clients also needed to install the WebView2 control while having build 2108 (so the control is NOT installed automatically.

Another question: is there a way to make the WebView2 plugin work for non-subscription Office apps? Some of our clients still use an Exchange Sever (mostly because a third party hosts it) and can not migrate quickly. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00c430f1-bbf5-53b8-a225-4fbe8fc39c3b
* Version Independent ID: 0a069a0d-4d35-71ee-53af-8c55fe8548a0
* Content: [Browsers used by Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins)
* Content Source: [docs/concepts/browsers-used-by-office-web-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/concepts/browsers-used-by-office-web-add-ins.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@ferrykranenburgcw Thanks for asking about this.

@Rick-Kirkham Can you take a look?

Thanks.

**Comment by slabereemsft** [comment]
Hi @ferrykranenburgcw,

Great questions! 

We don't spend a lot of time with Citrix terminal configurations so apologies if I'm not understanding the terminology correctly.  Generally the factor that determines whether the latest browser control is available is if its running on a guest OS that supports it. 

Windows Server 2012R2 is very similar to Windows 8.1 and so WebView2 is supported on this operating system and later (with the right updates of Office Pro Plus).  

It would be good to get more details on the machines where you're seeing the control not installing on 2101 & especially 2108. We'd like to investigate what's causing that issue.  

For non-subscription users, our WebView2 support is included in Office 2021. 

I hope that helps!
-Sean

**Comment by ferrykranenburgcw** [comment]
Hi @slabereemsft ,

Thanks for clearing that up! Clients on Server OS 2012R2 and up are supported. Good to know.

>It would be good to get more details on the machines where you're seeing the control not installing on 2101 & especially 2108. We'd like to investigate what's causing that issue.

We had one example of a client running on guest OS of Windows Server 2019, Office build 2102 (365 subscription) 32 bit. The Webview2 control add-in was installed seperately. No Edge browser inside Office. After removing the seperate WebView2 control, Office was not picking up the Webview2 control that should be included in the Office build. Upgrading to build 2108 fixed the issue.

We have another client that is running on guest OS of Windows Server 2012R2, Office build 2106 (365 subscription) 32 bit. They also installed the Webview2 control seperately. They see a CPU spike on the server when user logs in the Citrix terminal. 

![image](https://user-images.githubusercontent.com/83816575/131619053-2e26146c-d330-4250-b576-13bb8c36bbab.png)

After removing the seperate Webview2 control the CPU spike issues where fixed. Currently the Webview2 control inside the Office build 2106 is not being picked up. We are currently still looking for a solution with our client why this does not work.

**Comment by ferrykranenburgcw** [comment]
What can we exactly check if we have a client that runs guest OS on Windows Server 2012R2 and running Office 365 build 2106? 

![image](https://user-images.githubusercontent.com/83816575/132024676-972b0551-ae43-4d35-8a7f-6af9b18ed6bf.png)

![image](https://user-images.githubusercontent.com/83816575/132024709-b964a0e1-c78b-447b-b341-bb4dd8a50fdb.png)

According to the documentation the Edge Webview should be active and the Edge browser is used for add-in, but currently it isn't.

**Comment by ferrykranenburgcw** [comment]
The client had PowerBI software installed (64bit) next to a 32bit Office installation. The Webview2 plugin that came with PowerBI was 64bit and not compatible with the 32bit Office installation. This was the root cause of the issue. It is fixed now.

I'm closing this issue for now because it looks like the documentation is correct after all.

**Comment by slabereemsft** [comment]
Hi @ferrykranenburgcw,
That's good news that you were able to determine the root cause. I was about to reply to this case to indicate that we're beyond the support lifecycle for Office Pro Plus on Windows Server 2021 R2 so it would have been difficult to investigate further.  I would advise you/your clients to upgrade to a supported operating system for the best support.
