### ISSUE TITLE
npm install -g yo generator-office - Deprecated and unsupported packages referenced

### ISSUE THREAD

**Issue by timothyhoffmann** [OfficeDev/office-js-docs-pr#2916]
[Enter feedback here]
Looks like the yo generator needs to be updated:
```
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated opn@6.0.0: The package has been renamed to `open`
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 930ce4fc-c8b8-f756-f03f-a716f1ef7883
* Version Independent ID: 753a2e38-9430-25bb-5409-b7eed9c88e47
* Content: [Build your first Outlook add-in - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/outlook-quickstart?tabs=yeomangenerator)
* Content Source: [docs/quickstarts/outlook-quickstart.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/quickstarts/outlook-quickstart.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for reporting this @timothyhoffmann.

@millerds, could you please investigate this issue?

@davidchesnut, could you please transfer this issue to https://github.com/OfficeDev/generator-office?

**Comment by millerds** [comment]
Hmm . . . I'm not getting these warnings, though I can seen in the package.json 2 of the 3 things mentioned here.

**Comment by timothyhoffmann** [comment]
yo office
Choose a project type: Office Add-in Task Pane project using React framework
Choose a script type: TypeScript
What do you want to name your add-in? Test1
Which Office client application would you like to support? Outlook

I agree, I'm not getting those warnings today.
