### ISSUE TITLE
ContosoAddin.Url

### ISSUE THREAD

**Issue by m2mal** [OfficeDev/office-js-docs-pr#2936]
Can you please expleain, why you introduce the "ContosoAddin.Url" element?
Whats it means, what it for?

https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/tutorials/share-data-and-events-between-custom-functions-and-the-task-pane-tutorial.md

**Comment by AlexJerabek** [comment]
Thanks for raising this issue @m2mal.

@davidchesnut, could you please help provide some more clarity here?

**Comment by davidchesnut** [comment]
Hi @m2mal, Thanks for noticing that, as I need to update it. The docs are more descriptive using **Taskpane.url** and describing how it just refers to your task pane HTML page. You can use any name you want as long as it references the task pane HTML page for your add-in. I'll submit a PR to fix this in the sample so it matches the docs. [Configure your Office Add-in to use a shared JavaScript runtime](https://docs.microsoft.com/office/dev/add-ins/develop/configure-your-add-in-to-use-a-shared-runtime)
