### ISSUE TITLE
GetStarted overrides default content

### ISSUE THREAD

**Issue by nrueckmann** [OfficeDev/office-js-docs-pr#2940]
It seems like <GetStarted> is only able to override the default content of the callout. I did not find any option to disable this callout completely. Maybe i missed something, but if not we should make it clear that omitting <GetStarted> will not result in the removal of the callout. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb3c39f4-bf7f-a54b-1671-a3a3a5a4ce92
* Version Independent ID: fa858a5c-a2a7-5cad-c312-f62bcfcd5115
* Content: [DesktopFormFactor element in the manifest file - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/desktopformfactor)
* Content Source: [docs/reference/manifest/desktopformfactor.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/manifest/desktopformfactor.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @nrueckmann,
Thanks for raising this issue. @davidchesnut, could you please investigate?

**Comment by davidchesnut** [comment]
Hi @nrueckmann, I just submitted PR #2944 to add a note about the behavior when omitting GetStarted. It will just use the description and displayname instead.

Thanks!
David
