### ISSUE TITLE
Cross platform sample code

### ISSUE THREAD

**Issue by vault79** [OfficeDev/office-js-docs-pr#2955]
[Enter feedback here]
The document is very clear and provide actionable idea. Thank you very much. If I can add comment, I want to suggest that you can consider to provide cross-platform sample code.

The document guide me [this sample code in GitHub](https://github.com/OfficeDev/PnP-OfficeAddins/tree/main/Samples/auth/Outlook-Add-in-SSO). It requires Windows and Visual Studio because it utilizes .NET Framework instead of .NET Core. I think there are many developers who uses Mac and VS Code (including me). In addition to it, for side loading on Mac based Outlook, we need a cross platform code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53319dc9-a8e9-323e-6ccf-ce169b90abac
* Version Independent ID: 408dbc47-f781-b027-1596-2c91cbbde06b
* Content: [Scenario - Implement single sign-on to your service - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/implement-sso-in-outlook-add-in)
* Content Source: [docs/outlook/implement-sso-in-outlook-add-in.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/outlook/implement-sso-in-outlook-add-in.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thank you for the suggestion @vault79.

@davidchesnut, could you please capture this request and decide the best course of action for enhancing our sample coverage?

**Comment by nancy-wang** [comment]
@davidchesnut - wanted to make sure you were aware of this request. thank you!
