### ISSUE TITLE
Publishing custom functions to azure not working

### ISSUE THREAD

**Issue by MitchHamill** [OfficeDev/office-js-docs-pr#2956]
[Enter feedback here]
I followed the steps of this page to deploy my `dist` folder for an excel functions add in I built with the `yo-office-generator` tool, I was able to successfully deploy the directory to a static site, but when I try and run the manifest on an excel instance (after changing the urls from `localhost:3000` to the path to my static site, I've confirmed all the paths have matching resources) I don't have access to my custom functions, though the taskpane works correctly.

Is there a step I'm missing for deploying custom functions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b9105a4-a164-1e91-11ad-8ccb4f4d6b2d
* Version Independent ID: f4e5fae7-ac16-f852-8529-6b0fdd7bdad4
* Content: [Publish an add-in using Visual Studio Code and Azure - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/publish/publish-add-in-vs-code)
* Content Source: [docs/publish/publish-add-in-vs-code.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/publish/publish-add-in-vs-code.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for reporting this issue, @MitchHamill.

@davidchesnut, could you please take a look?

**Comment by MitchHamill** [comment]
Appreciate the help
If it helps, here are the steps to reproduce:

1. Set up the project with `yo office --projectType excel-functions --name custom-fns-test --host excel --ts true`
2. Create a static site with azure storage using the steps in the above document
3. Update the `urlProd` variable in `webpack.config.js` to the url of the deployed static site, run `npm run build`
4. Deploy the `dist` folder to azure storage using the steps in the above document
5. Run `npm run start` to test at `localhost:3000` and see the default functions are now registered (**Note** I'm going through these steps again while writing this, and the template styles are not being applied to the task pane, not related but worth mentioning)
6. Edit the `Functions.Script.Url`, `Functions.Metadata.Url`, `Functions.Page.Url` Urls in `dist/manifest.prod.xml` removing the `/dist` in the path, as the `dist/` path was deployed to the static site.
7. Confirm all URLs and Assets in the `dist/manifest.prod.xml` (Pointing to the azure static site) match the URLs in `manifest.xml` (Pointing to `localhost:3000`)
8. Sideload the manifest at `dist/manifest.prod.xml` into a web instance of excel using the `Upload my add-in` button, see the taskpane working as expected, though none of the functions in the template are registered.
9. If you're still running the manifest locally aswell, you can then also sideload the manifest at `/manifest.xml` (Pointing at `localhost:3000`) and the functions will be registered for that manifest

Hope this helps, I've attached the `manifest.prod.xml` produced from the above steps, where you can confirm all the URLs point to valid resources

**MANIFEST.PROD.XML:**
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<OfficeApp xmlns="http://schemas.microsoft.com/office/appforoffice/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bt="http://schemas.microsoft.com/office/officeappbasictypes/1.0" xmlns:ov="http://schemas.microsoft.com/office/taskpaneappversionoverrides" xsi:type="TaskPaneApp">
  <Id>e7788f22-1bc4-40b0-9474-242c1c559cf5</Id>
  <Version>1.0.0.0</Version>
  <ProviderName>Contoso</ProviderName>
  <DefaultLocale>en-US</DefaultLocale>
  <DisplayName DefaultValue="custom-fns-test"/>
  <Description DefaultValue="Write your own Excel functions in TypeScript."/>
  <IconUrl DefaultValue="https://testdeploycustomfns.z22.web.core.windows.net/assets/icon-32.png"/>
  <HighResolutionIconUrl DefaultValue="https://testdeploycustomfns.z22.web.core.windows.net/assets/icon-64.png"/>
  <SupportUrl DefaultValue="https://www.contoso.com/help"/>
  <AppDomains>
    <AppDomain>https://www.contoso.com</AppDomain>
  </AppDomains>
  <Hosts>
    <Host Name="Workbook"/>
  </Hosts>
  <Requirements>
    <Sets DefaultMinVersion="1.1">
      <Set Name="CustomFunctionsRuntime" MinVersion="1.1"/>
    </Sets>
  </Requirements>
  <DefaultSettings>
    <SourceLocation DefaultValue="https://testdeploycustomfns.z22.web.core.windows.net/taskpane.html"/>
  </DefaultSettings>
  <Permissions>ReadWriteDocument</Permissions>
  <VersionOverrides xmlns="http://schemas.microsoft.com/office/taskpaneappversionoverrides" xsi:type="VersionOverridesV1_0">
    <Hosts>
      <Host xsi:type="Workbook">
        <AllFormFactors>
          <ExtensionPoint xsi:type="CustomFunctions">
            <Script>
              <SourceLocation resid="Functions.Script.Url"/>
            </Script>
            <Page>
              <SourceLocation resid="Functions.Page.Url"/>
            </Page>
            <Metadata>
              <SourceLocation resid="Functions.Metadata.Url"/>
            </Metadata>
            <Namespace resid="Functions.Namespace"/>
          </ExtensionPoint>
        </AllFormFactors>
        <DesktopFormFactor>
          <GetStarted>
            <Title resid="GetStarted.Title"/>
            <Description resid="GetStarted.Description"/>
            <LearnMoreUrl resid="GetStarted.LearnMoreUrl"/>
          </GetStarted>
          <FunctionFile resid="Commands.Url"/>
          <ExtensionPoint xsi:type="PrimaryCommandSurface">
            <OfficeTab id="TabHome">
              <Group id="CommandsGroup">
                <Label resid="CommandsGroup.Label"/>
                <Icon>
                  <bt:Image size="16" resid="Icon.16x16"/>
                  <bt:Image size="32" resid="Icon.32x32"/>
                  <bt:Image size="80" resid="Icon.80x80"/>
                </Icon>
                <Control xsi:type="Button" id="TaskpaneButton">
                  <Label resid="TaskpaneButton.Label"/>
                  <Supertip>
                    <Title resid="TaskpaneButton.Label"/>
                    <Description resid="TaskpaneButton.Tooltip"/>
                  </Supertip>
                  <Icon>
                    <bt:Image size="16" resid="Icon.16x16"/>
                    <bt:Image size="32" resid="Icon.32x32"/>
                    <bt:Image size="80" resid="Icon.80x80"/>
                  </Icon>
                  <Action xsi:type="ShowTaskpane">
                    <TaskpaneId>ButtonId1</TaskpaneId>
                    <SourceLocation resid="Taskpane.Url"/>
                  </Action>
                </Control>
              </Group>
            </OfficeTab>
          </ExtensionPoint>
        </DesktopFormFactor>
      </Host>
    </Hosts>
    <Resources>
      <bt:Images>
        <bt:Image id="Icon.16x16" DefaultValue="https://testdeploycustomfns.z22.web.core.windows.net/assets/icon-16.png"/>
        <bt:Image id="Icon.32x32" DefaultValue="https://testdeploycustomfns.z22.web.core.windows.net/assets/icon-32.png"/>
        <bt:Image id="Icon.80x80" DefaultValue="https://testdeploycustomfns.z22.web.core.windows.net/assets/icon-80.png"/>
      </bt:Images>
      <bt:Urls>
        <bt:Url id="Functions.Script.Url" DefaultValue="https://testdeploycustomfns.z22.web.core.windows.net/functions.js"/>
        <bt:Url id="Functions.Metadata.Url" DefaultValue="https://testdeploycustomfns.z22.web.core.windows.net/functions.json"/>
        <bt:Url id="Functions.Page.Url" DefaultValue="https://testdeploycustomfns.z22.web.core.windows.net/functions.html"/>
        <bt:Url id="GetStarted.LearnMoreUrl" DefaultValue="https://go.microsoft.com/fwlink/?LinkId=276812"/>
        <bt:Url id="Commands.Url" DefaultValue="https://testdeploycustomfns.z22.web.core.windows.net/commands.html"/>
        <bt:Url id="Taskpane.Url" DefaultValue="https://testdeploycustomfns.z22.web.core.windows.net/taskpane.html"/>
      </bt:Urls>
      <bt:ShortStrings>
        <bt:String id="Functions.Namespace" DefaultValue="CONTOSO"/>
        <bt:String id="GetStarted.Title" DefaultValue="Get started with your sample add-in!"/>
        <bt:String id="CommandsGroup.Label" DefaultValue="Commands Group"/>
        <bt:String id="TaskpaneButton.Label" DefaultValue="Show Taskpane"/>
      </bt:ShortStrings>
      <bt:LongStrings>
        <bt:String id="GetStarted.Description" DefaultValue="Your sample add-in loaded succesfully. Go to the HOME tab and click the 'Show Taskpane' button to get started."/>
        <bt:String id="TaskpaneButton.Tooltip" DefaultValue="Click to Show a Taskpane"/>
      </bt:LongStrings>
    </Resources>
  </VersionOverrides>
</OfficeApp>
```

**Comment by MitchHamill** [comment]
Thanks a bunch @davidchesnut!!
I figured there'd be some simple step I was missing 😃

**Comment by davidchesnut** [comment]
I added instructions to the doc for how to set up CORS for custom functions. BTW: @MitchHamill there is no list for the endpoints that could call you for Mac/Windows etc. There are many and they change from time to time. You could try applying a filter like *.live.com or similar.
