### ISSUE TITLE
Poor Example 

### ISSUE THREAD

**Issue by gksk** [OfficeDev/office-js-docs-pr#2957]
[Enter feedback here]
What is this .For a beginner you have given an Example that runs 10 pages. Its strange that guys like you from a Top firm, doenst provide simple examples to get started. Poor Sense 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a59958d2-f428-9ca2-3440-a5af662386c0
* Version Independent ID: dcaf0b5b-08ea-c437-130b-342a1be62a16
* Content: [Tutorial: Build a message compose Outlook add-in - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/outlook-tutorial)
* Content Source: [docs/tutorials/outlook-tutorial.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/tutorials/outlook-tutorial.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@gksk Thanks for your feedback. We have a quick start that should meet your need.

[Build your first Outlook add-in](https://docs.microsoft.com/office/dev/add-ins/quickstarts/outlook-quickstart)

Can you give this a try?

Thanks.
