### ISSUE TITLE
Using Azure to deploy add-in to other users

### ISSUE THREAD

**Issue by sirfragalot** [OfficeDev/office-js-docs-pr#2958]
So, following this page, I have now deployed my add-in to my university's Azure account. According to the documentation, I can use this to share my add-in with other users (strangely, there is no mention of Azure here: https://docs.microsoft.com/en-us/office/dev/add-ins/publish/publish).

However, the documentation stops at deploying the add-in to Azure and does not go onto to then explain how to get the add-in to other Word users. What do they do now that the add-in is on the Azure website?

The documentation is incomplete.

Regards,

Mark

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b9105a4-a164-1e91-11ad-8ccb4f4d6b2d
* Version Independent ID: f4e5fae7-ac16-f852-8529-6b0fdd7bdad4
* Content: [Publish an add-in using Visual Studio Code and Azure - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/publish/publish-add-in-vs-code#publishing-an-add-in-for-other-users-to-access)
* Content Source: [docs/publish/publish-add-in-vs-code.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/publish/publish-add-in-vs-code.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by davidchesnut** [comment]
Hi @sirfragalot, 

Once you deploy to Azure, the next step would be to determine how your users load the add-in into their version of Office. Basically they need to get the manifest file somehow. You can do this by sideloading, which is manual steps for the user (more for dev and testing scenarios). Or you can put the manifest on a network share and the user can configure Office to see the network share. Or deploy to AppSource, and they can get it from the store. etc...

Perhaps it would help to clarify that this article is really about making your manifest available for your intended user. Typically for dev/testing scenarios you can just send the manifest file to the tester and ask them to sideload it. For an end user you'd probably want to at least have it on a network share, or ask an admin to centrally deploy the manifest file to make it available to all their users. AppSource makes it available to basically everyone from the store. Ultimately an end user is almost always going to be using the Office UI to add your add-in like in [Get an Office Add-in for Excel](https://support.microsoft.com/en-us/office/get-an-office-add-in-for-excel-d3df5854-0a4e-4169-9cc3-25177a288d3d#ID0EBBD=Newer_versions).

Let me know if you think that makes sense to update the article and better clarify.

Thanks!
David

**Comment by sirfragalot** [comment]
Thanks for the response David,

On this page:
https://docs.microsoft.com/en-us/office/dev/add-ins/publish/publish-add-in-vs-code#publishing-an-add-in-for-other-users-to-access

there are statements such as:
"When you're ready to publish it for other users to access, you'll need to deploy the web application and update the manifest to specify the URL of the deployed application."
"When your add-in is working as desired, you can publish it directly through Visual Studio Code using the Azure Storage extension."

and its all related to use of Azure.

Reading that, one could be forgiven for thinking that I can opt to go through Azure (as set up by my university), publish the add-in there (not just the manifest), and other users can then access it. The issue is that there a) is no description on what 'other users' refers to or b) how these 'other users' can then load the app into Word.

For me 'other users' are any users inside or outside my university who wish to make use of the add-in. Reading the documentation gives the impression that those users can access the add-in from my Azure storage but there is no further information on how they do this.

However, your response here clouds the issue further as a) it seems only the manifest is available to other users and b) 'other users' seem to be only those who can sideload (thus have VS code) and so are not actually end-users. (I'm not sure about this last point so may have misunderstood you.)

What I also don't understand is this: "For an end user you'd probably want to at least have it on a network share, or ask an admin to centrally deploy the manifest file to make it available to all their users." That sounds like exactly what I want (especially the first part but the second part is also interesting)—I want end users (no need for VS Code or sideloading, private individuals owning their own Word or companies using a distributed Word for their employees) to be able to download the manifest file and thus get the add-in.

A further confusion is this:
At https://docs.microsoft.com/en-us/office/dev/add-ins/publish/publish, it states that Network Share distribution is not for the production add-ins and is only as part of the development process and the link for Network Share seems to indicate it is only for Windows users (I use a Mac and so will many of my end-users). But your statement above—"by sideloading, which is manual steps for the user (more for dev and testing scenarios). Or you can put the manifest on a network share and the user can configure Office to see the network share"—seems to contradict this.

So, assuming the above can indeed be done, I think the documentation can be improved by adding further steps once the add-in has been published on Azure:
1. List possible ways for end-users and/or testers to access the add-in.
2. Particularly for common-or-garden end-users able to configure Word to access the add-in, how to thus configure Word. You state I can put the "manifest on a network share and the user can configure Office to see the network share." Presumably 'network share' is Azure in this case. I can't see anywhere in my Word settings to do this.

I will quite happily check through any changes and updates to documentation to ensure an ordinary user (like me) can understand it and successfully navigate instructions from Azure deployment to end-user access. Just let me know what I can do to help.

By the way, this might also improve the documentation. Once the add-in was deployed to my Azure space, navigating to the manifest file location (https://wikindx.z6.web.core.windows.net/) in a web browser just gives me an image in a table that is just a part of my add-in taskpane. It's not clear what use to make of that if any.

Also by the way, there are bugs in the VS code build process—I had to copy some files by hand to the build folder before deploying to Azure.

**Comment by AlexJerabek** [comment]
@davidchesnut recently published the article [Host an Office Add-in on Microsoft Azure](https://learn.microsoft.com/en-us/office/dev/add-ins/publish/host-an-office-add-in-on-microsoft-azure). I believe this addresses the original documentation ask, so I'm going to close the issue. Please correct me if I'm mistaken.
