### ISSUE TITLE
Multiple Action Elements within a Control Element

### ISSUE THREAD

**Issue by tanjoht** [OfficeDev/office-js-docs-pr#2978]
Within a control element block in an office plugin, trying to associate 2 action elements associated with it results in a schema error.

Code:

`<Control xsi:type="Button" id="msgReadOpenPaneButton">
  <Label resid="TaskpaneButton.Label"/>
  <Supertip>
    <Title resid="TaskpaneButton.Label"/>
    <Description resid="TaskpaneButton.Tooltip"/>
  </Supertip>
  <Icon>
    <bt:Image size="16" resid="Icon.16x16"/>
    <bt:Image size="32" resid="Icon.32x32"/>
    <bt:Image size="80" resid="Icon.80x80"/>
  </Icon>
  <Action xsi:type="ShowTaskpane">
    <SourceLocation resid="Taskpane.Url"/>
  </Action>
  <Action xsi:type="ExecuteFunction">
    <FunctionName>action</FunctionName>
  </Action>
</Control>`

Error:
This app can't be installed. The manifest file doesn't conform to the schema definition. The element 'Control' in namespace has invalid child element 'Action' in namespace.

Based on the [actions element documentation](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/action), under the taskpaneId section, it seems to imply that you can have 2 action elements. Although it says that the taskpanid element isn't supported in outlook, are multiple action elements supported in general? I'm trying to have it so that when I click the add in button, it triggers both a "ShowTaskpane" and an "ExecuteFunction" action?

The use case I have is to combine 2 custom vendor add-ins in outlook to support our transition from 1 product to another. Since the web apps behind the plugins are built and supported by the vendor, I have no access to change/update the code

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff9684d4-4f86-9287-2cb8-d563fb2deeb9
* Version Independent ID: d4345566-daef-fbe2-c887-615312d44614
* Content: [Action element in the manifest file - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/action)
* Content Source: [docs/reference/manifest/action.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/manifest/action.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
That documentation is misleading. Each of those Action elements must be in different Control parents (or different menu Item parents). You can't have 2 different actions in the same button or menu item.
