### ISSUE TITLE
Error in step #2

### ISSUE THREAD

**Issue by davidreedme** [OfficeDev/office-js-docs-pr#300]
Step #2 indicates replacement of the contents of app.js, but the correct file seems to actually be src/index.js instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77e380a7-6e2e-ada8-d297-3fd5018a1958
* Version Independent ID: f23490e8-6eeb-f2d5-6c94-69e3c9ed83f4
* Content: [Build your first Word add-in](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/word-quickstart?tabs=visual-studio-code)
* Content Source: [docs/quickstarts/word-quickstart.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/quickstarts/word-quickstart.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
Thanks for raising this issue!

This was fixed in PR https://github.com/OfficeDev/office-js-docs-pr/pull/297 and should be published soon.

Apologies for any confusion.
