### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by elegault** [OfficeDev/office-js-docs-pr#3002]
The following links generate 404's:

- [Office Add-ins community call – February 10, 2021](https://developer.microsoft.com/office/blogs/office-add-ins-community-call-february-10-2021/)
- [Office Add-ins community call – January 13, 2021](https://developer.microsoft.com/office/blogs/office-add-ins-community-call-january-13-2021%e2%80%af/)
- [Office Add-ins community call – December 9, 2020](https://developer.microsoft.com/microsoft-365/blogs/office-add-ins-community-call-december-9-2020/)
- [Office Add-ins community call - November 11, 2020](https://developer.microsoft.com/office/blogs/office-add-ins-community-call-november-11-2020/)
- [Office Add-ins community call - October 14, 2020](https://developer.microsoft.com/office/blogs/office-add-ins-community-call-october-14-2020%E2%80%AF/)
- [Office Add-ins community call - September 9, 2020](https://developer.microsoft.com/office/blogs/office-add-ins-community-call-september-9-2020/)
- [Office Add-ins community call - August 12, 2020](https://developer.microsoft.com/office/blogs/office-add-ins-community-call-august-12-2020%E2%80%AF/)
- [Office Add-ins community call - July 8, 2020](https://developer.microsoft.com/office/blogs/office-add-ins-community-call-july-8-2020/)
- [Office Add-ins community call - June 10, 2020](https://developer.microsoft.com/office/blogs/office-add-ins-community-call-june-10-2020/)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a57f1340-d9ee-6bbc-c4ba-104b77840a6a
* Version Independent ID: 82ff44e8-1cdc-20e9-3ce6-d560de532b14
* Content: [Microsoft Office Add-ins community call - Office Add-ins](https://docs.microsoft.com/en-ca/office/dev/add-ins/overview/office-add-ins-community-call)
* Content Source: [docs/overview/office-add-ins-community-call.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/overview/office-add-ins-community-call.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @elegault,

I believe this will be fixed by @davidchesnut's #3001 PR. I'll assign this to him to close when that PR is checked in.
