### ISSUE TITLE
Missing information about Icon scale attribute

### ISSUE THREAD

**Issue by markdon** [OfficeDev/office-js-docs-pr#3017]
In [Additional requirements for mobile form factors](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/icon#additional-requirements-for-mobile-form-factors) regarding the Image element:
> Each size provided must appear three times, with a scale attribute set to 1, 2, or 3.

The example references a different resource for each scale. 

Could this document please either link to or explain what the scale attribute means and the differences between the image supplied for each scale?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d8e5f40-63fe-f71c-a021-4842a26ef9ec
* Version Independent ID: 75dfa44c-08f3-0328-b4a1-26014a305e51
* Content: [Icon element in the manifest file - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/icon)
* Content Source: [docs/reference/manifest/icon.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/manifest/icon.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
The scale attribute specifies the UIScreen.scale property for iOS devices. For more information, see [scale](https://developer.apple.com/documentation/uikit/uiscreen/1617836-scale).

I will update the documentation with this information.

**Comment by markdon** [comment]
Thank you @Rick-Kirkham!
