### ISSUE TITLE
Incorrect meeting provider icon color requirement

### ISSUE THREAD

**Issue by markdon** [OfficeDev/office-js-docs-pr#3018]
Under the [Restrictions](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/online-meeting#restrictions) section:
> The add-in icon should be in grayscale using hex code #919191 or its equivalent in other color formats.

\#919191 does not match the color of the teams logo or the other icons used in the iOS app. They look like they're \#6E6E6E.
Is this doc still accurate?

<img src="https://user-images.githubusercontent.com/9063681/138809309-6a02df57-7c61-48dc-85a2-e8056c6c88ba.png" width="500" />
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52a55fe4-0fe1-858c-26a4-dddc3ee128ea
* Version Independent ID: 0a643291-936f-b374-37fd-7db497c73cce
* Content: [Create an Outlook mobile add-in for an online-meeting provider - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/online-meeting#available-apis)
* Content Source: [docs/outlook/online-meeting.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/outlook/online-meeting.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@exextoc Can engineers working on mobile confirm this?

Thanks.

**Comment by exextoc** [comment]
Yes the docs are accurate, we are still continuing with grayscale using hex code #919191. We will be updating the colored icons with the monochrome ones.

**Comment by markdon** [comment]
Thanks @exextoc!
