### ISSUE TITLE
cannot use these steps if using SharedRuntime?

### ISSUE THREAD

**Issue by jordandev** [OfficeDev/office-js-docs-pr#3022]
[Enter feedback here]
These steps do not work to test our add-in on old versions of Office for IE 11 / Legacy Edge support as our add-in uses SharedRuntime and these versions of Office do not support it. So we cannot install our add-in on these old versions.

Is there any other set of steps to make this easier to test? Otherwise it seems we need to have a perpetual use version of Office 2019 that supports both IE 11 and SharedRuntime?

Not sure what to do here....

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47b7b417-12e6-193f-6b89-37e088b31dbc
* Version Independent ID: df705bd2-5f2f-2c84-0519-fca9a3c45d71
* Content: [Internet Explorer 11 testing - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/ie-11-testing)
* Content Source: [docs/testing/ie-11-testing.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/ie-11-testing.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
The information I have gotten internally is that AppSource should not be testing your add-in on versions <16.0.11629. I see that you have created a ticket with them. So, I'll close this issue for now, but you can still add comments to it and, if needed, ask that it be reopened.
