### ISSUE TITLE
Topic: Debug add-ins using developer tools in Internet Explorer - Missing office-addin-dev-settings webview switch options

### ISSUE THREAD

**Issue by LouMM** [OfficeDev/office-js-docs-pr#3023]
## Article URL
https://docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-add-ins-using-f12-tools-ie

## Issue
The section that relates to IE, it talks about installing a version of Office that will work with only IE Trident. However, there is a  feature in latest versions of Office that allow for a debug flag to be provided for Sideloaded Addin's only.
office-addin-dev-settings script has a webview flag that you can pass a webview type: ('edge' or 'edge-chromium, 'edge-legacy', 'ie', or 'default')
https://github.com/OfficeDev/Office-Addin-Scripts/tree/master/packages/office-addin-dev-settings#webview

`office-addin-dev-settings webview c:\path\addinmanifest.xml ie`

https://docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-add-ins-using-f12-tools-ie#install-a-version-of-office-that-uses-internet-explorer

The reason for this switch was to assist developers so they can verify their add-in using a single workstation, Windows version, and Office Version against different webview types.

**Comment by Rick-Kirkham** [comment]
@LouMM See the internal email thread "npx command to switch runtime broken" I just sent. I'll hold off on this documentation chagne until the issue is resolved.
