### ISSUE TITLE
Incorrect command line example in section "Install and use the debugger"

### ISSUE THREAD

**Issue by lehnerpat** [OfficeDev/office-js-docs-pr#3031]
In the section ["Install and use the debugger"](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-desktop-using-edge-chromium#install-and-use-the-debugger), the "Tip" box suggests running the command `office-add-in-debugging start <your manifest path>`.

1. The command name contains a typo, it should be `office-addin-debugging` (no dash in the word "addin")
2. The command can only be run like that if the office-addin-debugging package is installed globally, which the tutorials don't suggest to do AFAIK. Something like `npx office-addin-debugging start <your manifest path>` should usually work after setting up a project using the `generator-office`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5e92a7f-e42d-68ba-cc21-15df8289f5a1
* Version Independent ID: 096a172b-382e-764d-6d7d-88811bb5b96f
* Content: [Debug add-ins on Windows using Microsoft Edge WebView2 (Chromium-based) - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-desktop-using-edge-chromium)
* Content Source: [docs/testing/debug-desktop-using-edge-chromium.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/debug-desktop-using-edge-chromium.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for pointing this out @lehnerpat. I'll get a PR together to fix that.
