### ISSUE TITLE
Webview2 for "non-subscription Office 2013 to Office 2019"

### ISSUE THREAD

**Issue by g-martinse** [OfficeDev/office-js-docs-pr#3046]
Asking about "non-subscription Office 2013 to Office 2019" of office. When will "Microsoft Edge1 with WebView2 (Chromium-based)" be supported at least for Office 2019 clients?
Which version of these clients need to be installed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00c430f1-bbf5-53b8-a225-4fbe8fc39c3b
* Version Independent ID: 0a069a0d-4d35-71ee-53af-8c55fe8548a0
* Content: [Browsers used by Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins)
* Content Source: [docs/concepts/browsers-used-by-office-web-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/concepts/browsers-used-by-office-web-add-ins.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
Microsoft Edge with WebView2 (Chromium-based) is supported on the non-subscription Office 2021. There are no plans to ever support it on earlier versions of non-subscription Office. Sorry, if this is bad news. I'll close this issue, but you can still make comments.
