### ISSUE TITLE
npx is not supported on MacOS

### ISSUE THREAD

**Issue by DanilKorotenko** [OfficeDev/office-js-docs-pr#3051]
I tried to run the command:
npx office-addin-dev-settings runtime-log --enable
In Terminal app,
But output was:
Error: Platform not supported: darwin.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8a067bb-7974-5742-776c-1d798d9821ad
* Version Independent ID: 9984c542-88a7-b425-0cbd-de8af676bcfd
* Content: [Debug your add-in with runtime logging - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/runtime-logging?view=outlook-js-preview)
* Content Source: [docs/testing/runtime-logging.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/runtime-logging.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @DanilKorotenko,

Thanks for reporting this. Just to confirm, are the instructions under [Runtime logging on Mac](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/runtime-logging?view=outlook-js-preview#runtime-logging-on-mac) working for you?

@millerds, is MacOS support expected here?

**Comment by millerds** [comment]
To clarify a little here . . . it not 'npx' (which is part of the npm which is installed with node) itself that isn't supported and returning the error.  It's the office-addin-dev-settings package that we provide that is reporting the error.

In looking at our code it appears that that command was only made to support Windows so for and the work still needs to be done to make it work on mac.

**Comment by Rick-Kirkham** [comment]
I will clarify in the article, that Mac is not supported by the tool.
