### ISSUE TITLE
Difference from ItemSend event type

### ISSUE THREAD

**Issue by moshikonachmias** [OfficeDev/office-js-docs-pr#3056]
Hello, 
I wanted to know:
1. Will you allow add-ins that use the OnMessageSend in AppSource?
2. How this is different from the ItemSend event type?
https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/outlook-on-send-addins

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08db1c81-31cc-68a0-3912-fb625814aa0f
* Version Independent ID: 08db1c81-31cc-68a0-3912-fb625814aa0f
* Content: [Use Smart Alerts and the OnMessageSend event in your Outlook add-in (preview) - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/smart-alerts-onmessagesend-walkthrough)
* Content Source: [docs/outlook/smart-alerts-onmessagesend-walkthrough.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/outlook/smart-alerts-onmessagesend-walkthrough.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@moshikonachmias Thanks for asking about this.

1. The event-based activation feature is currently allowed in AppSource but with some restrictions (for more details, see [AppSource listing options for your event-based Outlook add-in](https://docs.microsoft.com/office/dev/add-ins/outlook/autolaunch-store-options)). The OnMessageSend event is still in preview and not recommended for production add-ins. Once the event is released, it should have the same AppSource conditions as the event-based activation feature itself.
2. The functionality should be pretty much the same. Some key differences:
    - Instead of one event, there are two: OnMessageSend, OnAppointmentSend
    - The underlying architecture/implementation is different
    - ItemSend is not allowed in AppSource while OnMessageSend should be allowed once it's out of preview (might still be conditionally as previously discussed)

Hope this info helps. Let us know if you have any further questions.

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@moshikonachmias We've added this to our backlog (internal item: 5550483), that we should clarify the difference. However, we'll likely work on that around the time the new events GA.

Thanks.

**Comment by moshikonachmias** [comment]
Thank you for the information.

**Comment by samantharamon** [comment]
Hi @moshikonachmias,

Thank you for your patience. Now that the Smart Alerts feature has been deployed as part of Mailbox requirement set 1.12, we have updated the [Smart Alerts walkthrough](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/smart-alerts-onmessagesend-walkthrough?tabs=xmlmanifest#differences-between-smart-alerts-and-the-on-send-feature) to differentiate this from the on-send feature. I will now close this issue, but please don't hesitate to create a new issue should you require further assistance.
