### ISSUE TITLE
On articles about persisting add-in state and settings

### ISSUE THREAD

**Issue by alexuaua** [OfficeDev/office-js-docs-pr#3066]
The article https://docs.microsoft.com/en-us/office/dev/add-ins/develop/persisting-add-in-state-and-settings seems to be updated recently (09/10/2021) but offers either to save settings within a document (Settings, CustomParts) or to _use techniques provided by browser (localStorage)_.

The issue with localStorage, is that with many modern browsers (namely, Safari and latest Edge builds) even if we use Storage API, this information is not persisted between sessions - I've read similar issues in OfficeDev/office-js (while they were mostly about sharing data between dialog and taskpane) and tested with Safari 15.1, Safari 15.4 and Edge 95: even if `requestStorageAccess` is granted by user (on a click event, as required), for documents in iframe, this permission is reset on browser reload and the worse part is that the localStorage granted to iframe is cleared. Firefox also requires to request a new approval from a user after a browser was closed, but after a new `requestStorageAccess` call the iframe can access all the data from previously used localStorage, so while a user is bothered to click a "Allow Storage"-like button every time the add-in is loaded, it's possible to persist user data and login information in localStorage.

Another relevant article here is https://docs.microsoft.com/en-us/office/dev/add-ins/develop/itp-and-third-party-cookies 
It says:
> Use the Storage Access API so that the third-party can request permission to get access to its first-party cookies. Current versions of Office on Mac and Office on the web both support this API.
> Note
> If you're using cookies for purposes other than authentication, then consider using localStorage for your scenario.

It features nice example (while it does not cover promise rejection), but does not mention that the data won't be preserved.

To my understanding the only solution for Office on the web add-ins would be using `SharedRuntime.storage`.

## Article URL
https://docs.microsoft.com/en-us/office/dev/add-ins/develop/persisting-add-in-state-and-settings
https://docs.microsoft.com/en-us/office/dev/add-ins/develop/itp-and-third-party-cookies

**Comment by AlexJerabek** [comment]
Hi @alexuaua,
Thank you for reporting this. @davidchesnut, could you please take a look and help clarify the data persistence story?

**Comment by alexuaua** [comment]
I've read all latest Storage API specifications and played with Storage API, and found that I got confused by localStorage mention in the article about ITP, while the main phrase points only about cookies:
>Use the Storage Access API so that the third-party can request permission to get access to its **first-party cookies**.
`requestStorageAccess` grants access to cookies in Safari, but local storage is *ephemeral* (cleaned when browser is closed) - this may be worth to mention, if one needs a local storage or indexedDB (for Firebase Auth or auth0), there is no need to play with Storage Access API as it won't grant these. On other side Firefox preserves localStorage contents. 

And I've got it wrong with Edge – with default settings there are no issues with Edge (for Mac, I've not checked Windows yet).

**Comment by davidchesnut** [comment]
Hi @alexuaua,

To be clear are you asking how to persist data that is associated with the user (not the document or session?) Yes, that's correct that you can save data at the browser level, but it is not really persistent as the user can delete it. You can also use the  Settings data, but that is document specific. 

To store data per user you would need to sign in the user and then store their information in a database. For that approach I'd recommend to sign in the user using [SSO](https://docs.microsoft.com/office/dev/add-ins/develop/sso-in-office-add-ins) and call [getAccessToken](https://docs.microsoft.com/en-us/javascript/api/office/office.auth?view=excel-js-preview#getAccessToken_options_) to get the user's identity via the returned access token. Then you can [create a unique id](https://docs.microsoft.com/en-us/azure/active-directory/develop/id-tokens#using-claims-to-reliably-identify-a-user-subject-and-object-id) to store data in a server database for each user. 

Hope I'm understanding your scenario correctly. Please let me know if there are more details I perhaps missed.

Thanks!
David

**Comment by alexuaua** [comment]
Hi @davidchesnut,

My only point here (in office-js-docs) was that it's probably worth to mention that the storage techniques mentioned in the [article](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/persisting-add-in-state-and-settings) are not available on Mac (with default browser, Safari), and [another article](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/itp-and-third-party-cookies) mentions Storage API and ITP with Safari on Mac, but this does not work for iframes (an add-in case). 

And thanks a lot for the idea of using SSO token to exchange for a login token instead of local storage – as I understand (I'm still setting up the example) the sign-in/consent prompt should be displayed only the first time we call `getAccessToken` and an Office app provides it silently on subsequent calls. 
I'm only a bit confused by [this note](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/sso-in-office-add-ins)
>You should not rely on SSO as your add-in's only method of authentication.
Because if we don't have any local storage, we can only rely on SSO token to exchange it (on our back-end) for a token, let's say, from a social login provider.

It still would be great to have a storage API (even a very simple, like [a Google API for Workspace add-ons](https://developers.google.com/apps-script/guides/properties) ) for add-ins to store some user preferences. But this is definitely a feature request for the office-js repo, and offtopic here.

**Comment by alexuaua** [comment]
@davidchesnut as I understand you are the main contributor to the [Node.js add-in with SSO example](https://github.com/OfficeDev/PnP-OfficeAddins/tree/main/Samples/auth/Office-Add-in-NodeJS-SSO), so here looks like a good place to ask you.  
_Every time_ I click the "Get OneDrive Files List" button, I see a "Office Add-in NodeJS SSO wants to display a new window" confirmation dialog inside the taskpane.
Is this a correct behaviour?

Because if there is no bug or some compatibility issue, requiring a user to confirm each time the add-in loaded, unfortunately, makes the scenario with using SSO + getAccessToken useless (vs simply asking user to log-in again) to persist an authorisation or settings.

And thanks in advance for your attention.
Alex

**Comment by davidchesnut** [comment]
Ok, I added PR #3138 to clarify that some browsers may not support localStorage, and also linked to the article on how to test for availability.

Regarding the "Office Add-in NodeJS SSO wants to display a new window" message:
Yes, this is by design. To work around popup blockers the user must be asked for permission. This only happens if:
- The user is not signed into Office.
- The user has not consented to the add-in yet.
- The admin has not consented to the add-in yet. (which can be done in the app registration process to avoid this case.)

Once the user signs in, and consents, you shouldn't see this message anymore. You should just receive the access token. So it should just be a one-time request.

Thanks!
David
