### ISSUE TITLE
IIS?

### ISSUE THREAD

**Issue by Zamdrist** [OfficeDev/office-js-docs-pr#307]
Can you not deploy to a local IIS server or Intranet? If so, could the documentation be updated to add those steps?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2677af5b-e9b8-f962-25ce-8aa285977c90
* Version Independent ID: c31c7ed9-0a0a-7a65-0d1b-70d6a8b33994
* Content: [Deploy and publish your Office Add-in](https://docs.microsoft.com/en-us/office/dev/add-ins/publish/publish)
* Content Source: [docs/publish/publish.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/publish/publish.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
There may be some confusion over the word 'deploy'. This article is about your options for deploying the app manifest. This is something different from where you host the HTML, JavaScript, etc. files of the add-in. You can host these files on a web server anywhere including a local IIS server or a server on your Intranet. Just be sure you use the correct URLs for your resources in the manifest, such as the SourceLocation value.
