### ISSUE TITLE
Discrepancy between documentation and our experience with Exchange server

### ISSUE THREAD

**Issue by derdos-lmi** [OfficeDev/office-js-docs-pr#3073]
Dear Microsoft, Office Developer team,

we're trying to validate how our Outlook integration would work with an Exchange server

In this documentation: https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/outlook-api-requirement-sets#requirement-sets-supported-by-exchange-servers-and-outlook-clients
in the Important box, you wrote that "If your target Exchange server and Outlook client support different requirement sets, then you're restricted to the lower requirement set range.".

We used a Microsoft 365 subscription as a client (which supports up to 1.11 API requirement set) with an Exchange on-premises version 2016 which should only support API requirement set up to version 1.5.
But when we execute this: Office.context.requirements.isSetSupported('MailBox', '1.10'); it returned true.

Based on the features available it seemed like the 1.10 is really supported.
So we would like to know if this documentation is up to date or what could cause this discrepancy between our tests and the documentation.

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8e26a32-7523-2211-bde3-938cf94a76ec
* Version Independent ID: 80ad76d1-8a12-348f-dd6a-2f9392ed1f95
* Content: [Outlook JavaScript API requirement sets - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/outlook-api-requirement-sets#requirement-sets-supported-by-exchange-servers-and-outlook-clients)
* Content Source: [docs/reference/requirement-sets/outlook-api-requirement-sets.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/requirement-sets/outlook-api-requirement-sets.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for reporting this @derdos-lmi.

@exextoc, could you please help provide some clarity here?

**Comment by exextoc** [comment]
Thanks for reporting this issue, we now have a task tracking this for an update. To clear up the confusion, Office.context.requirements.isSetSupported() will only check for the client side for the requirement set supported so returning true is correct here. As for why the APIs you are using actually work, the APIs probably do not require anything recent from the server. 
Internal Tracking ID: 5577639

**Comment by derdos-lmi** [comment]
Hi,

thank you!
Just to be sure... We should determine if our integration will function with exchange server 2016. We tested it, and it seemed to work, but there are two features that are require higher versioning then it is supported with 2016:

- The regexp for highlighting and interacting with phone numbers in an email feature (but this might be a client side feature)
- The Office.Recurrence interface, which has a Mailbox 1.7 API requirement (https://docs.microsoft.com/en-us/javascript/api/outlook/office.recurrence?view=outlook-js-1.7&preserve-view=true)

In native Windows Outlook with Exchange Server 2016 both seemed like working during our tests. Could this be a misconfiguration of the testing environment on our part, or are these features should function with the described setup?

Thank you!

**Comment by derdos-lmi** [comment]
Dear Microsoft, Office development team,

Could you please give us an ETA when you could answer our latest questions? Some of our development and integration roll-out are blocked by it, so a validation if those APIs are usable with Exchange server 2016 would help us tremendously.

Thank you!

Best Regards,
Daniel

**Comment by exextoc** [comment]
These two features are client side only and should work.

**Comment by derdos-lmi** [comment]
Thank you so much for your help!

One last question: Do you have any documentation with maybe a list about what are the server side features that are limited by the Exchange server version, so we can be sure for future development what to look out for?

Thanks!

**Comment by exextoc** [comment]
We are working to update our documentation with the information we have provided you so far.
Unfortunately, we don't have any timelines to share at this moment.
