### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by DanilKorotenko** [OfficeDev/office-js-docs-pr#3075]
[Create add-in commands in your manifest][create-addin-commands.md]

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06f7f7e8-5b8a-e257-74be-77b47f048503
* Version Independent ID: a2851e98-268b-e65e-05eb-7ac3e21fe1ca
* Content: [Office Add-ins XML manifest - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/add-in-manifests?view=outlook-js-preview&tabs=tabid-1)
* Content Source: [docs/develop/add-in-manifests.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/add-in-manifests.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for reporting this @DanilKorotenko. I'll get that fixed.
