### ISSUE TITLE
Explanation of why SSO should not be the only auth mechanism

### ISSUE THREAD

**Issue by sureshjoshi** [OfficeDev/office-js-docs-pr#3082]
I've read through the docs and associated sample code, and I've seen it mentioned and shown (in code), that there should always be a fallback to another auth mechanism (e.g. msal.js).

However, what I don't have a clear idea about is WHY is this necessary? Is the purpose to handle one-off or transient errors (network connectivity?) or is it more focused on permanent problems (ie. this version of Word does not currently allow SSO)?

I think the distinction of why having a fallback is necessary is important to security and auth design. The former would use a re-try, but the latter shows how it's 100% required to have a fallback. 

I say this as someone who is replacing a current auth mechanism with SSO, and has gotten stuck in the docs.

## Article URL

https://docs.microsoft.com/en-us/office/dev/add-ins/develop/sso-in-office-add-ins

## Issue

> You should not rely on SSO as your add-in's only method of authentication. You should implement an alternate authentication system that your add-in can fall back to in certain error situations

The only request I have is explanation what those "certain error situations" are, or just more information in general about why a fallback is a requirement.

**Comment by AlexJerabek** [comment]
Thanks for flagging this documentation gap @sureshjoshi.

@davidchesnut, could you please investigate?

**Comment by davidchesnut** [comment]
Hi @sureshjoshi, This is timely as I'm working on a refresh to the auth documentation! One example would be if your add-in got loaded on an older version of Office that didn't support SSO. But I'll add some additional details there. Thanks!

**Comment by sureshjoshi** [comment]
Thanks @davidchesnut - that was the use case I had imagined, but I didn't know if there were others. I thought maybe if you were at a certain requirement set for the add-in, you could prevent it and use SSO-only or something (which, for my add-in, would be pretty nice).

**Comment by sureshjoshi** [comment]
@davidchesnut If I could add some other points that would be helpful, as I'm re-reading the documentation and trying to design a workflow.

- It would be useful to have a clearer explanation of `allowConsentPrompt` vs `allowSignInPrompt` (perhaps with an image of the UI that shows up when we select one, or the other, or both?). 
  - My guess is that signIn prompts the user to sign-in to word (if they're not), and then consent is for the add-in, but what are the permutations of those two prompts? 
  - Do we manually `getAccessToken` with one prompt, and then another based on error catching? Or will Word handle the workflow of multiple prompts?
- How the user can be locally "logged out" as the documentation states "... redundant calls of getAccessToken because Office caches the bootstrap token and will reuse it, until it expires". 
  - For development (or just if a user wants to), how can we locally expire/delete the cached token? 
  - Revoking consent via myapps.microsoft.com still keeps a several hour token live on the developer/user's machine 

The workflow that is inspiring this (both from a developer's point of view, and a user's) is that my add-in allows sign-in or "continue as guest" (with different functionality as a result). 

If a user signs in, then closes Word and wants to re-open the add-in, we don't want them needing to click sign-in again, so we just try `getAccessToken` - but I'm determining which prompts we need at each scenario (only just one, or both)

Afterwards, if a user (or developer) wants to revoke the JWT to log out and re-test the workflow, or just be satisfied they've logged out, I can't see how that would happen. I mean, in an ideal world, a log-out would also show a pop-up with the myapps.microsoft.com webpage so the user can explicitly revoke consent from the source, and then delete the cached JWT immediately.

Thanks!

**Comment by davidchesnut** [comment]
Hi @sureshjoshi,

Sorry for the very long delay on this work. There's been some iteration on the docs and I think most of what you ask is covered now.

- *How the user can be "logged out"?* I can't find this in the documentation so there may have been a change. But one way to log out is in Word on desktop. A user can use the UI to sign out. At that point if you call getAccesstoken you would need to request "allowSignInPrompt" to force the user to sign in (if that's what you want.)
- *How can we locally expire/delete the cached token?* You can't. They generally expire in about an hour.
- *Revoking consent still keeps a several hour token live on the machine?* True, but my understanding is it will not work when you attempt to use it on a resource (Graph) in which consent for a scope was revoked. If you are seeing unexpected behavior, follow up with the [Microsoft identity team](https://learn.microsoft.com/azure/active-directory/develop/developer-support-help-options). 
- *"continue as guest" scenario.* Yes if you want to do this pass false for "allowConsentPrompt" and "allowSignInPrompt". This will cause Office to silently get the access token, but when it sees the user is not signed in, it returns an error. Handle the error by going into "guest mode" (however your add-in implements that.)
- Signing out is not supported for SSO in the add-in. If the user wants to sign out from the add-in, they would need to close the document and reopen it.

Here are more docs, so please let us know if we are missing anything (or if there is anything confusing.)

`allowSignInPrompt` is documented here:
https://learn.microsoft.com/en-us/office/dev/add-ins/develop/sso-in-office-add-ins#when-to-call-getaccesstoken
https://learn.microsoft.com/en-us/javascript/api/office/office.authoptions?view=common-js-preview

`allowSignInPrompt` is documented here:
https://learn.microsoft.com/en-us/javascript/api/office/office.authoptions?view=common-js-preview
https://learn.microsoft.com/en-us/office/dev/add-ins/develop/authorize-to-microsoft-graph#distributing-sso-enabled-add-ins-in-microsoft-appsource

Cheers,
David

**Comment by davidchesnut** [comment]
Closing, but please reopen if you have any more questions.
