### ISSUE TITLE
Office on Mac ‘one-time purchase’ versions missing from Office applications table in article on ‘Dialog API requirement sets’

### ISSUE THREAD

**Issue by Rinzwind** [OfficeDev/office-js-docs-pr#3085]
## Article URL
- Website: https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/dialog-api-requirement-sets
- Source: https://github.com/OfficeDev/office-js-docs-pr/blob/aacbe26fb231c18a38d758382259d794da1dc165/docs/reference/requirement-sets/dialog-api-requirement-sets.md#dialog-api-requirement-sets

## Issue
The table at the top of the article “lists the Dialog API requirement sets, the Office client applications that support that requirement set, and the build or version numbers for the Office application”. However: the table lists the ‘one-time purchase’ versions of Office on Windows only, those on Mac seem to be missing. For Mac, only ‘Office on Mac (subscription)’ is listed.

Could you extend the table to include the ‘one-time purchase’ versions of Office on Mac? I’m in particular looking for details on support for ‘DialogApi 1.2’ in ‘Office 2021 on Mac (one-time purchase)’.

**Comment by AlexJerabek** [comment]
Thanks for reporting this @Rinzwind.

@Rick-Kirkham, can you please investigate and add the requirement set information as needed?

**Comment by Rick-Kirkham** [comment]
@Rinzwind I found the info for one-time purchase Office on Mac on this page: [Office client application and platform availability for Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/overview/office-add-in-availability). It appears that DialogApi 1.**2** is _not_ supported in Office 2021 on Mac (one-time purchase), only 1.**1**. 

I'm investigating internally why none of our requirement set tables have a column for one-time purchase Office on Mac. There may be a good reason, but I suspect it is just an oversight. If that turns out to be the case, my team will add the column to all the tables where it is needed. In the meantime, I'll leave this issue open.

**Comment by Rinzwind** [comment]
@Rick-Kirkham note that that page also only lists ‘DialogApi 1.1’ for ‘Office 2021 on Windows (one-time purchase)’ as well ([markdown source link](https://github.com/OfficeDev/office-js-docs-pr/blob/aacbe26fb231c18a38d758382259d794da1dc165/docs/overview/office-add-in-availability.md?plain=1#L24)), while the one on ‘Dialog API requirement sets’ says ‘DialogApi 1.2’ is supported in ‘Office 2021 or later on Windows* (one-time purchase)’ in ‘Build 16.0.14326.20454 or later’ ([markdown source link](https://github.com/OfficeDev/office-js-docs-pr/blob/aacbe26fb231c18a38d758382259d794da1dc165/docs/reference/requirement-sets/dialog-api-requirement-sets.md?plain=1#L17)). I had assumed this meant the first page didn’t list ‘DialogApi 1.2’ for Office 2021 on Windows due to it not being supported in the first build. I presumed ‘DialogApi 1.2’ would have similarly been added to Office 2021 on Mac after its first build, but just wanted to make sure. Am I misinterpreting this?

**Comment by Rick-Kirkham** [comment]
Hmmm. It looks like the page that I linked to is not being updated in some cases. I'll research that too.

**Comment by Rick-Kirkham** [comment]
@Rinzwind The experts tell me that, for Mac, the subscription and one-time purchase support for requirement sets and version numbers are always the same. So, you can use the "Office on Mac (subscription)" column for single-purchase too. I will get these column headings corrected and update the out-of-date article too.

**Comment by Rinzwind** [comment]
Ok, thanks for the info!

So, just to make sure I understood correctly: ‘DialogApi 1.2’ *is* supported by the latest build of ‘Office 2021 on Mac (one-time purchase)’?

I assume the requirement set support being the same as for ‘Office on Mac (subscription)’ only applies to the most recent ‘one-time purchase’ release, so Office 2021, but not Office 2019 and earlier? Presumably, ‘DialogApi 1.2’ is *not* supported in any build of ‘Office 2019 on Mac (one-time purchase)’ (it’s not supported in the Windows counterpart either)?

**Comment by Rick-Kirkham** [comment]
Yes. I think you've summarized it accurately.
