### ISSUE TITLE
One Note 

### ISSUE THREAD

**Issue by GUAYMI** [OfficeDev/office-js-docs-pr#3099]
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13002e9d-09c4-6ca4-860a-46b3349c4992
* Version Independent ID: 9946bc42-836f-18fb-8899-08ec3158a9f4
* Content: [Work with OneNote page content - Office Add-ins](https://docs.microsoft.com/en-ca/office/dev/add-ins/onenote/onenote-add-ins-page-content)
* Content Source: [docs/onenote/onenote-add-ins-page-content.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/onenote/onenote-add-ins-page-content.md)
* Product: **onenote**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @GUAYMI,

It's unclear from this issue what the documentation feedback is. If you found a problem or have a question about the linked page, we're happy to look into it. For now, I'm going to close this issue, but please add more detail in the comments and I'll reopen it.

**Comment by GUAYMI** [comment]
Ohh my God please forgive me for this. I have recently decided to learn more about this app.

**Comment by AlexJerabek** [comment]
@GUAYMI, no worries! Enjoy your OneNote learnings.
