### ISSUE TITLE
There may be a small mistake with the steps to modify the task taskpane.html

### ISSUE THREAD

**Issue by JHJ-MS** [OfficeDev/office-js-docs-pr#3104]
[Enter feedback here]
add `<script src="functions.js"></script>` 
before </head> in taskpane.html

should be `<script src="../functions/functions.js"></script> `

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 056e0311-c24e-6342-a3f0-36120930107d
* Version Independent ID: dd406dd4-8384-190a-2385-01324cf1ba3a
* Content: [Tutorial: Share data and events between Excel custom functions and the task pane - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/share-data-and-events-between-custom-functions-and-the-task-pane-tutorial#configure-the-webpackconfigjs-file)
* Content Source: [docs/tutorials/share-data-and-events-between-custom-functions-and-the-task-pane-tutorial.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/tutorials/share-data-and-events-between-custom-functions-and-the-task-pane-tutorial.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thank you for reporting this @JHJ-MS.

@alison-mk, can you please investigate and update the tutorial accordingly?

**Comment by alison-mk** [comment]
Hi @JHJ-MS, thanks for submitting this issue! I've submitted PR #3108 to incorporate your suggestion. Once that PR is merged, this issue will be closed. 

Cheers, 
Alison
