### ISSUE TITLE
Office add-ins on mobile reccommends using deprecated (soon to be decomissioned) REST API

### ISSUE THREAD

**Issue by westconference** [OfficeDev/office-js-docs-pr#3106]
The office add-in mobile documentation directs users to use the Outlook REST APIs with their add-ins. The Outlook REST API was deprecated in 2020 and will be decommissioned in 2022.
* https://devblogs.microsoft.com/microsoft365dev/outlook-rest-api-v2-0-deprecation-notice/

> The makeEwsRequestAsync API is not supported on mobile since the mobile app uses REST APIs to communicate with the server. If your app backend needs to connect to the Exchange server, you can use the callback token to make REST API calls. For details, see Use the Outlook REST APIs from an Outlook add-in.

The deprecation notice recommends MS Graph as an altenative however the getAccessToken method provided by OfficeRuntime is part of the IdentityAPI 1.3 requirement set which is not supported on mobile.

The documentation needs updated with suggestion of what mobile office add-in developers should do instead of using the soon to be decomissioned REST API.
* As a user of the REST API currently I'm not sure what the available migration path here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 564bc140-d31e-f042-bd30-b8140b7db416
* Version Independent ID: 9953764b-39ca-d5c0-c1f8-5ca44ec2f472
* Content: [Outlook add-ins for Outlook Mobile - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/outlook-mobile-addins)
* Content Source: [docs/outlook/outlook-mobile-addins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/outlook/outlook-mobile-addins.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for raising this concern @westconference.

@JuaneloJuanelo and @ElizabethSamuel-MSFT, could you please provide guidance around mobile alternatives for REST APIs?

**Comment by ElizabethSamuel-MSFT** [comment]
Hi @westconference, we are currently reviewing our APIs to determine how they will be impacted by the REST API deprecation planned for 2022. We will communicate recommended guidance broadly in our documentation once we are done with our review.

Thanks.

**Comment by ckollipa-adm** [comment]
Any updates?

**Comment by samantharamon** [comment]
Hi @ckollipa-adm,

We are still in the process of reviewing and updating our API documentation. I will update this issue as soon as this task has been completed.

In the meantime, please be advised that Outlook add-ins using REST V2 created before November 2022 are eligible for an exemption. If this is something you'd like to opt into, please register your add-in at https://aka.ms/RESTCheck.

**Comment by GrumpyAL** [comment]
Hi, @ckollipa-adm!  One note I have for you: you can call an Azure AD login page to get graph access for mobile devices.  However, I will note it is a much degraded user experiences vs using REST tokens or GRAPH SSO tokens.  Especially if you're add-in is meant to do small/quick actions related to the message.  The login page/process becomes the majority of add-in interaction time.

This demo has a login page fallback example: https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/auth/Outlook-Add-in-SSO/AttachmentDemo

Personally, I would much prefer that IdentityAPI 1.3 be added to the mobile clients and manual login only be needed for older clients, such as 2016.

@samantharamon the form you linked, can it be used for Private add-ins or is it only intended for add-ins that are in AppSource?

**Comment by samantharamon** [comment]
Great question, @GrumpyAL . I've verified that the form applies to both private add-ins and add-ins in AppSource.

**Comment by samantharamon** [comment]
@westconference @ckollipa-adm @GrumpyAL Thank you for your patience. Documentation on mobile Outlook add-ins using the REST service is still an ongoing task in review, but I wanted to provide an update. To add to my previous post, active add-ins that use the REST service will be granted an exemption to keep using the service until extended support ends for Outlook 2019 on October 14, 2025. This includes new add-ins that are developed after the decommission date in November. @JuaneloJuanelo provided an update on this in [this month's Office Add-ins community call](https://www.youtube.com/watch?v=KxaE0SLk-lM) and answered questions, including mobile-related ones, which may interest you. Additional questions raised by the community during the call will be answered in a blog post and a link will be posted to [Microsoft Office Add-ins community call](https://docs.microsoft.com/office/dev/add-ins/overview/office-add-ins-community-call?branch=pr-en-us-3588), so watch out for that, too.

**Comment by GrumpyAL** [comment]
@samantharamon after reading through the August community call, I have a question.  Will this exemption process now just apply automatically or do we still need to opt in for any new or existing add-ins using the above form?  Our concern is that we have rare occasions where the appID may get changed before the add-in is deployed.

**Comment by samantharamon** [comment]
@GrumpyAL thanks for raising this question. The team is currently testing automatic add-in traffic identification, so that you won't need to submit the form for your new and existing add-ins to be exempted. During this testing phase, and especially since your add-in has certain conditions, I encourage you to submit a [form](https://aka.ms/RESTCheck) to participate in testing. This will allow the team to identify and account for certain edge cases.

**Comment by samantharamon** [comment]
> The office add-in mobile documentation directs users to use the Outlook REST APIs with their add-ins. The Outlook REST API was deprecated in 2020 and will be decommissioned in 2022.
> 
> * https://devblogs.microsoft.com/microsoft365dev/outlook-rest-api-v2-0-deprecation-notice/
> 
> > The makeEwsRequestAsync API is not supported on mobile since the mobile app uses REST APIs to communicate with the server. If your app backend needs to connect to the Exchange server, you can use the callback token to make REST API calls. For details, see Use the Outlook REST APIs from an Outlook add-in.
> 
> The deprecation notice recommends MS Graph as an altenative however the getAccessToken method provided by OfficeRuntime is part of the IdentityAPI 1.3 requirement set which is not supported on mobile.
> 
> The documentation needs updated with suggestion of what mobile office add-in developers should do instead of using the soon to be decomissioned REST API.
> 
> * As a user of the REST API currently I'm not sure what the available migration path here.

Hi @westconference,

I wanted to provide an update on your original post. Since `getAccessToken` isn't supported in Outlook on mobile devices, we recommend using nested app authentication (NAA) instead to call services such as Microsoft Graph. NAA is currently in preview in Outlook on Android and on iOS. Here are some resources to help you learn more about NAA.

- [Enable SSO in an Office Add-in using nested app authentication (NAA)](https://learn.microsoft.com/office/dev/add-ins/develop/enable-nested-app-authentication-in-your-add-in)
- [Office Add-in Sample: Outlook add-in with SSO using nested app authentication (preview)](https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/auth/Outlook-Add-in-SSO-NAA)
- [Nested app authentication and Outlook legacy tokens deprecation FAQ](https://learn.microsoft.com/office/dev/add-ins/outlook/faq-nested-app-auth-outlook-legacy-tokens)
