### ISSUE TITLE
Broken references to add-in deployment for Exchange server

### ISSUE THREAD

**Issue by markdon** [OfficeDev/office-js-docs-pr#3120]
The [Exchange server](https://docs.microsoft.com/en-us/office/dev/add-ins/publish/publish#outlook-add-in-deployment) link in the table of deployment methods leads to a header that does not provide any details for how to deploy with Exchange server but links to [Install or remove add-ins for Outlook for your Exchange Online organization](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/add-ins-for-outlook/install-or-remove-outlook-add-ins) which is now just a stub that links to [Deploy add-ins in the admin center](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/manage-deployment-of-add-ins). Nowhere in this chain of links is there an explanation for how to deploy with Exchange server. 

Maybe there's supposed to be a link to something like [https://docs.microsoft.com/en-us/exchange/install-or-remove-outlook-add-ins-2013-help](https://docs.microsoft.com/en-us/exchange/install-or-remove-outlook-add-ins-2013-help)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2677af5b-e9b8-f962-25ce-8aa285977c90
* Version Independent ID: c31c7ed9-0a0a-7a65-0d1b-70d6a8b33994
* Content: [Deploy and publish Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/publish/publish)
* Content Source: [docs/publish/publish.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/publish/publish.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@markdon Thanks for raising this issue. We'll take a look.

Thanks.
