### ISSUE TITLE
Documentation needs an update

### ISSUE THREAD

**Issue by matthewfitzmaurice** [OfficeDev/office-js-docs-pr#3126]
The create-addin-commands documentation is out of date. The latest yeoman project contains all the `<VersionOverrides>` required to create an addin command. However the article does NOT explain how to take the yeoman project and modify it to create an addin command.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b73778b8-8dd2-98f5-b4a1-e135a0049011
* Version Independent ID: 25744bd8-6084-00dc-545a-4b3eb87dedd4
* Content: [Create add-in commands in your manifest for Excel, PowerPoint, and Word - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/create-addin-commands)
* Content Source: [docs/develop/create-addin-commands.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/create-addin-commands.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by davidchesnut** [comment]
Hi @matthewfitzmaurice,

Thanks for catching this. I introduced PR #3133 to recommend using the quick starts (yo office of VS) to generate your project. I also updated the samples, and they are now moved to https://github.com/OfficeDev/PnP-OfficeAddins/tree/main/Samples/office-add-in-commands. So you can see how to add a dropdown menu and additional ribbon button.

Let us know if you want a step-by-step of how to do this, or if the samples provide enough info.

Thanks!
David
