### ISSUE TITLE
Taking Microsoft tutorial to make Word add-in fails

### ISSUE THREAD

**Issue by silvanet** [OfficeDev/office-js-docs-pr#3144]
OK, I don't know if this will help. I followed every step in the Visual Studio example. When I ran it in Word to show the Taskpane, I got an error saying the content was blocked because it isn't signed by a valid certificate. I read answers referring to IE settings, but I don't even have that installed anymore. What do I need to do?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77e380a7-6e2e-ada8-d297-3fd5018a1958
* Version Independent ID: f23490e8-6eeb-f2d5-6c94-69e3c9ed83f4
* Content: [Build your first Word task pane add-in - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/word-quickstart?tabs=yeomangenerator)
* Content Source: [docs/quickstarts/word-quickstart.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/quickstarts/word-quickstart.md)
* Product: **word**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@silvanet Sorry to hear you're facing this issue. We'll take a look.

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@silvanet I tried this using VS 2019 and Word on Windows 10, and it worked successfully. It was also using IIS Express.

Can you share details about your Word version/build, subscription or not, OS, etc.?

Thanks.
