### ISSUE TITLE
Limitation: getAttachmentsAsync does not work in on-send?

### ISSUE THREAD

**Issue by kreuli** [OfficeDev/office-js-docs-pr#3147]
Is it a known limitation that getAttachmentsAsync does not work in the context of on-send? If yes, this should be added to the list of Limitations on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e12d688-9620-e8f2-871d-922ec98008b5
* Version Independent ID: a8b409f3-44f7-97e5-d722-cbf04edc0653
* Content: [On-send feature for Outlook add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/outlook-on-send-addins?tabs=windows)
* Content Source: [docs/outlook/outlook-on-send-addins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/outlook/outlook-on-send-addins.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thank you for reporting this @kreuli.

@ElizabethSamuel-MSFT, could you please investigate and update the documentation as needed?

**Comment by ElizabethSamuel-MSFT** [comment]
@exextoc Can you advise about this? Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@kreuli Can you share the error message and behavior you're hitting? Also, please share details about your setup, e.g., Outlook version/build, OS, etc. Thanks.
