### ISSUE TITLE
Angular CLI has changed some of the generated outputs

### ISSUE THREAD

**Issue by WhitWaldo** [OfficeDev/office-js-docs-pr#315]
The instructions for angular.json in step 2 under the "Update the app" indicate that a defaults object should be modified. For one, this file is now called "angular.json", not ".angular-cli.json". For another, this apparently stopped producing a defaults object, so the instructions for #1 need to be updated.

The example to use in the start script specifies that the following should be set: 

"start": "ng serve --ssl true --port 3000"

Rather, I recommend this be updated with the following, and no changes being made to angular.json.

"start": "ng serve --ssl true --ssl-key 'certs/server.key' --ssl-cert 'certs/server.crt' --port 3000"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd013f4f-384b-49b8-152d-023ce8ec5bae
* Version Independent ID: 3700e56b-302c-ae2b-79bf-16702aeadcff
* Content: [Build an Excel add-in using Angular](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-angular)
* Content Source: [docs/quickstarts/excel-quickstart-angular.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/quickstarts/excel-quickstart-angular.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
Thanks. We'll take a look at this. 
MS internal: https://office.visualstudio.com/OC/_workitems/edit/2508542

**Comment by kbrandl** [comment]
@WhitWaldo we've significantly revised this quick start, to reflect that the Yeoman generator for Office Add-ins is now the recommended way of generating an Office Add-in project using the Angular framework. Please give the new instructions a try and feel free to reach out again if you have any trouble.

**Comment by fernandomagrina** [comment]
This is so frustrating!!! This should be simple and consistent, however, apparently a lot of devs can't get the angular to work as explained above. What's really annoying, is that a YouTube video from a random person from 2016 is the "explanation" of one of the key components of the add-in. I've noticed that several devs can't get it to work during my research.

How come Microsoft doesn't offer something more robust? For example, the JQuery Excel add-in is great, however, I really need to use Angular for my project. Well, hours and hours wasted already.

**Comment by VenkatSAP** [comment]
Yo office command throwing an error and unable to generate project template. Any link to working solution highly appreciable.

**Comment by kbrandl** [comment]
@VenkatSAP sorry to hear that you're having trouble. If you can please create a new issue in the [OfficeDev/generator-office](https://github.com/OfficeDev/generator-office) repository (and include info about repro steps and the error message that you're seeing), someone will assist you there.

**Comment by aagamdoshi** [comment]
Is there a way where we can run Angular solution on Visual Studio and not go by Yeomen generator
