### ISSUE TITLE
Documentation for automatically clearing the Office cache

### ISSUE THREAD

**Issue by romglusker** [OfficeDev/office-js-docs-pr#3153]
The documentation here suggests that it is possible to "configure the Office cache to be cleared automatically **every time** Office is reopened." At least based on my testing, it appears this is not really true.

The checkbox for "Next time Office starts, clear all previously-started web add-ins cache" does not get preserved after re-opening Excel, so when I re-open a second time, the cache is not cleared (unless I made sure to check the box again).

Is this expected to be the case? If there is a way to clear the cache automatically every time, I would definitely like to know how!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e273e29-10ac-440e-634e-588b5208e484
* Version Independent ID: a5a6dc8a-b504-686e-80ce-45aabd6f832b
* Content: [Clear the Office cache - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/clear-cache#clear-the-office-cache-on-windows)
* Content Source: [docs/testing/clear-cache.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/clear-cache.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @romglusker,

Thank you for reporting this. I just checked and am observing the same behavior with the cache-clearing setting. Let me tag @jargil to help investigate.
