### ISSUE TITLE
Request location permission when user denied in Outlook addin

### ISSUE THREAD

**Issue by chenxizhang** [OfficeDev/office-js-docs-pr#3155]
[Enter feedback here]

We are developing a outlook add-in, one feature is we need to detect current location information, when we call the API (navigator.geolocation.getCurrentPosition), Outlook will prompt and ask the permission, if user clicked the "allow" button, then everything is ok, but if user clicked the "deny" button, we don't have anyway to request the location in the future.

How to solve this problem? Thanks
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b2e062e-1a7a-1861-bf20-c23ac64d0d37
* Version Independent ID: ae2d1395-2a87-1bda-00fb-1b30f8e27b66
* Content: [Outlook add-ins overview - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/outlook-add-ins-overview)
* Content Source: [docs/outlook/outlook-add-ins-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/outlook/outlook-add-ins-overview.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @chenxizhang,

Thank you for asking this question. Let me tag @exextoc to help provide the necessary information.

**Comment by exextoc** [comment]
Currently there's no solution from our APIs that can help with this, this would have to do with permission settings within the browser itself. Meanwhile, there are threads online mentioning similar issues using geolocation, example: https://stackoverflow.com/questions/20678707/ask-for-geolocation-permission-again-if-it-was-denied
