### ISSUE TITLE
Doc Error/Incomplete in Section: Debug your add-in

### ISSUE THREAD

**Issue by laultman** [OfficeDev/office-js-docs-pr#316]
These steps are incomplete/incorrect:
To open the property pages of a project
1.In Solution Explorer, choose the project name.
2.On the menu bar, choose View, Properties Window.

Step 1 above is confusing because in-fact the properties in the subsequent list are in the different projects of the solution.  The expectation is that only one of the project "names" is selected and the properties are there when the user must select the name of each project to locate the specific property from the list.
Suggest that you add as you did for Outlook specific properties, parenthetical hits to where the property might be located as in the "Web" project or the "Add-in" project.
Small issue but still confusing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad34b5e8-8b67-5dfd-db60-60a9ac3ffc24
* Version Independent ID: b8b446ec-bb85-04f5-d6bf-198ba0288e04
* Content: [Create and debug Office Add-ins in Visual Studio](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/create-and-debug-office-add-ins-in-visual-studio)
* Content Source: [docs/develop/create-and-debug-office-add-ins-in-visual-studio.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/create-and-debug-office-add-ins-in-visual-studio.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
Thanks for bringing this to our attention. I have clarified the instructions. The intention was to open only the basic add-in project, not the web project.

**Comment by Rick-Kirkham** [comment]
Thanks. We'll look into this. 
https://office.visualstudio.com/OC/_workitems/edit/2508285
