### ISSUE TITLE
Is it possible to change the icons on the right side of task pane?

### ISSUE THREAD

**Issue by donlawatch** [OfficeDev/office-js-docs-pr#3168]
When I have multiple add-in task panes open, a new icon group appears on the right side of the task pane, as shown in the image below.

![taskpane](https://user-images.githubusercontent.com/80447115/148673075-482a06b6-214b-4c1f-b0be-9ad356475da0.png)

 Is it possible to change the icons on this new tab?

Additional information:
- On the ribbon, an image is assigned to each task pane. The image definition for sizes 16, 32, and 80 is included in the manifest.
- The manifest contains a definition for a default add-in icon like this: `<IconUrl DefaultValue="icon.png" />`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50a89144-ac19-b28e-2842-5e2cbdb1cb00
* Version Independent ID: cb59df19-9c22-de2c-0c46-7a1403312987
* Content: [Build your first PowerPoint task pane add-in - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/powerpoint-quickstart?tabs=yeomangenerator)
* Content Source: [docs/quickstarts/powerpoint-quickstart.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/quickstarts/powerpoint-quickstart.md)
* Product: **powerpoint**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @donlawatch,

Thank you for raising this question. @Rick-Kirkham, can you please assist?

**Comment by Rick-Kirkham** [comment]
Yes. You can change this. It is defined the [IconUrl](https://docs.microsoft.com/office/dev/add-ins/reference/manifest/iconurl) in element in the manifest. Just set the value of that element to the URL of the icon you want. Then re-sideload the add-in. You may have to [Clear the Office cache](https://docs.microsoft.com/office/dev/add-ins/testing/clear-cache) to get Office to use the new icon file. 

I'll update the docs to note this. In the meantime, since we're tracking it internally, I'll close this.

**Comment by donlawatch** [comment]
Hi @Rick-Kirkham 
A URL value for IconUrl has already been set in the manifest file. The icon appears in the installed version of PowerPoint, but it does not appear on the right side of the task pane in the web version.

- Installed version

![image](https://user-images.githubusercontent.com/80447115/149092676-f5fbc002-5888-4ca1-aaee-e68a777c92e9.png)

- Web version

![image](https://user-images.githubusercontent.com/80447115/149092808-a7b4ed62-521f-41a8-9cce-3a7cfc9c02ee.png)

**Comment by Rick-Kirkham** [comment]
A difference between in behavior between platforms is usually a bug. I suggest that you create an issue in the [office-js](https://github.com/OfficeDev/office-js/issues/new?assignees=&labels=&template=bug_report.md&title=) repo. Give it a title that indicates the feature is broken in **Office on the web**.
