### ISSUE TITLE
Prerequsites section: Instructions incomplete

### ISSUE THREAD

**Issue by laultman** [OfficeDev/office-js-docs-pr#317]
•TypeScript 2.3 for Visual Studio 2017 in the "Note" block immediately following the bullet. The document is out of date and incomplete. If you follow the instruction AND you do not have the TypeScript SDK installed, it gives on link to the SDK nor any instruction to go find it yourself. The current as of 8/2018 is here: https://www.microsoft.com/en-us/download/confirmation.aspx?id=55258

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b888399c-fe96-0934-00ce-86db8fa8cf5b
* Version Independent ID: 2c5d24e8-5639-42b1-4d12-119f89591550
* Content: [Convert an Office Add-in project in Visual Studio to TypeScript](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/convert-javascript-to-typescript)
* Content Source: [docs/develop/convert-javascript-to-typescript.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/convert-javascript-to-typescript.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
Thanks for bringing this to our attention. We're looking into it.

**Comment by kbrandl** [comment]
@laultman thanks again for the feedback; this article has been updated.
