### ISSUE TITLE
Office.auth.getAccessToken always fails with error code 13007.

### ISSUE THREAD

**Issue by glr0221** [OfficeDev/office-js-docs-pr#3177]
Following the steps described in this page results to a display dialog being displayed all the time. After some investigation, I found that the following line of code always yields an error code of 13007. 

`let bootstrapToken = await Office.auth.getAccessToken({ allowSignInPrompt: true, allowConsentPrompt: true, forMSGraphAccess: true }); `

When the error code is 13007, it will go thru the dialogFallback() flow and show the login popup. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c51a742c-4ddb-dd5e-7f67-3242a158378a
* Version Independent ID: b5d96164-bec6-7732-79ad-8c6beef7e0c4
* Content: [Create a Node.js Office Add-in that uses single sign-on - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/create-sso-office-add-ins-nodejs)
* Content Source: [docs/develop/create-sso-office-add-ins-nodejs.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/create-sso-office-add-ins-nodejs.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for reporting this issue. @davidchesnut, could you please investigate?

**Comment by Rick-Kirkham** [comment]
See this while you're waiting for an answer: [13007](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/troubleshoot-sso-in-office-add-ins#13007)

**Comment by davidchesnut** [comment]
Hi @glr0221,

Does Ricky's answer help solve the issue?

Thanks,
David
