### ISSUE TITLE
TypeScript is out of date with the linked files for the Office.d.ts and jQuery.d.ts

### ISSUE THREAD

**Issue by laultman** [OfficeDev/office-js-docs-pr#318]
The project has 181 errors. The tsconfig.json file is out of date. The project called for TS 2.3 which is behind almost 2 years. It is unreasonable to have to uninstall (breaking other projects) the current TS SDK just to get this to work. With VS at 15.8 and TS SDK at 3.0.1 this documentation is practically useless.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b888399c-fe96-0934-00ce-86db8fa8cf5b
* Version Independent ID: 2c5d24e8-5639-42b1-4d12-119f89591550
* Content: [Convert an Office Add-in project in Visual Studio to TypeScript](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/convert-javascript-to-typescript)
* Content Source: [docs/develop/convert-javascript-to-typescript.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/convert-javascript-to-typescript.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by laultman** [comment]
Finally got it to compile. See my later comments.

**Comment by Rick-Kirkham** [comment]
Thanks for bringing this to our attention. We're looking into it.

**Comment by kbrandl** [comment]
@laultman thanks again for the feedback; this article has been updated.
