### ISSUE TITLE
Add-in support for Outlook on the Web on iOS devices is confusingly explained

### ISSUE THREAD

**Issue by atsopuronen** [OfficeDev/office-js-docs-pr#3184]
I was asked today by a colleague whether Outlook add-ins are generally available for iPad users. While I'd like to say a sounding "yes" there are some conflicting information in MS docs.

1. FACT: Outlook add-ins are available for **iPad** users using **Outlook for iOS**.

2. About **iPads** and Outlook add-ins in **Outlook on the Web**:
Based on  the MS article below (updated 29th September 2021), iPads support the use of Outlook add-ins in Outlook on the Web **but only in Safari**.
https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/requirements-for-running-office-add-ins#client-requirements-no[…]-smartphone-and-tablet
<img width="757" alt="Näyttökuva 2022-1-18 kello 12 25 01" src="https://user-images.githubusercontent.com/51625811/149985046-4f2200d2-80e4-4153-a915-f31d9936372a.png">

3. On the other hand, this MS article (also updated 29th September 2021) claims that **modern version** of Outlook on the Web **doesn’t support** Outlook add-ins on **iPads** (nor on any iOS device using any web browser).
https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/outlook-mobile-addins
<img width="758" alt="Näyttökuva 2022-1-18 kello 12 23 12" src="https://user-images.githubusercontent.com/51625811/149985239-191174ea-2aed-47d6-8a80-ef3b46a7e783.png">

**NOTE:** This claim was originally added to the article likely in January 2020, so I have my doubts about its validity.

4. And finally, this MS article claims Outlook add-ins are supported in **both modern and classic version** of Outlook on the Web. However, **mobile devices** using Outlook on the Web **are not mentioned at all**, not related to restrictions nor support.
https://docs.microsoft.com/en-us/office/dev/add-ins/overview/office-add-in-availability#outlook
<img width="781" alt="Näyttökuva 2022-1-18 kello 12 43 05" src="https://user-images.githubusercontent.com/51625811/149985402-29bcaf02-a2c8-4d73-a319-d989cbc307f4.png">

So, my assumption is that the article in point 3 contains out of date information claiming Outlook add-ins are not supported in modern version of Outlook on the Web on iOS devices such as iPads. They are, but only when using Safari. 

The other problem is that it's fairly difficult to come to this conclusion by reading through the documentation.

## Article URL
https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/outlook-mobile-addins

## Issue
Article claims Outlook add-ins are not supported in modern version of Outlook on the Web on iOS devices such as iPad. They are, but only when using Safari.

**Comment by AlexJerabek** [comment]
Thanks for the detailed issue, @atsopuronen.

@ElizabethSamuel-MSFT, can you please take a look and ensure we're being consistent about Outlook on iPad?

**Comment by ElizabethSamuel-MSFT** [comment]
@atsopuronen We'll clarify this in the docs.

My current understanding is that you can use Outlook add-ins in **Outlook for iOS** on iPad. Other options (like other native apps or Outlook in a mobile browser) are unavailable for running Outlook add-ins.

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@atsopuronen We've verified that add-ins work in the Outlook for iOS app and in Outlook on the web in Safari.

We created a [PR](https://github.com/OfficeDev/office-js-docs-pr/pull/3204) to address this. Let us know if we need to make any further clarifications.

Thanks.
