### ISSUE TITLE
404

### ISSUE THREAD

**Issue by krehl** [OfficeDev/office-js-docs-pr#3187]
Signature add-in example URL wrong: https://docs.microsoft.com/en-us/samples/officedev/Office-Add-in-samples/outlook-add-in-set-signature/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56ebcaf3-ab12-f487-7771-402358836379
* Version Independent ID: 0ba17d6d-c2be-134c-f404-44e809fc9e04
* Content: [Office Add-in code samples - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/overview/office-add-in-code-samples)
* Content Source: [docs/overview/office-add-in-code-samples.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/overview/office-add-in-code-samples.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for reporting this @krehl. I'll take a look and fix the link.

**Comment by AlexJerabek** [comment]
While we fix the links, here's the link to the actual sample: https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/outlook-set-signature

**Comment by davidchesnut** [comment]
Thanks for catching this @krehl! The links should all be fixed now.
