### ISSUE TITLE
Code in Sample is Out of Date, Current Excel API Prototype Error

### ISSUE THREAD

**Issue by laultman** [OfficeDev/office-js-docs-pr#319]
The code from the home.ts file here:
    function displaySelectedCells() {
        Office.context.document.getSelectedDataAsync(Office.CoercionType.Text,
            function (result) {
                if (result.status === Office.AsyncResultStatus.Succeeded) {
                    showNotification('The selected text is:', '"' + result.value + '"');
                } else {
                    showNotification('Error', result.error.message);
                }
            });
    }

Visual Studio has error on build.

Error		Build:Type '(result: any) =&gt; void' has no properties in common with type 'GetSelectedDataOptions'.	ExcelWebAddIn1Web	

The getSelectedDataAsync method now has two optional parameters. the above code does not supply the first optional parameter causing the error. Viewing the prototype shows we must supply the first optional to properly provide the second optional. The below change works if you are not trying to use the specified property:
 function displaySelectedCells() {
        Office.context.document.getSelectedDataAsync(Office.CoercionType.Text, null, // added a null value for the missing option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b888399c-fe96-0934-00ce-86db8fa8cf5b
* Version Independent ID: 2c5d24e8-5639-42b1-4d12-119f89591550
* Content: [Convert an Office Add-in project in Visual Studio to TypeScript](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/convert-javascript-to-typescript)
* Content Source: [docs/develop/convert-javascript-to-typescript.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/convert-javascript-to-typescript.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by laultman** [comment]
It does compile and does run but the code does not work as expected. There are thus other problems to deal with. The first is just simply getting VS 2017 to debug the code. (Breakpoints do not work.)

**Comment by Rick-Kirkham** [comment]
Thanks for bringing this to our attention. We're looking into it.

**Comment by kbrandl** [comment]
@laultman thanks again for the feedback; this article has been updated.
