### ISSUE TITLE
parameter for ReplaceShortcuts function should be object

### ISSUE THREAD

**Issue by SongphonRefinitiv** [OfficeDev/office-js-docs-pr#3191]
In Shortcut JSON we can create shortcut with specific platform

"action": "SHOWTASKPANE",
"key": {
                "default": "Ctrl+Alt+Up",
                "mac": "Command+Shift+Up",
                "web": "Ctrl+Alt+1",
            }

And for replaceShortcuts method, it has parameter of type {[actionId:string]: string|null}

So, I am not sure if this API should allow developer to replace new shortcut for specific platform.

Thank you,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fee4083-e0cd-e483-a0d7-c3bd85042c52
* Version Independent ID: 4973703e-1687-4f52-4718-8767aacf566c
* Content: [Custom keyboard shortcuts in Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts)
* Content Source: [docs/design/keyboard-shortcuts.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/design/keyboard-shortcuts.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @SongphonRefinitiv,

Thank you for raising this question. @AbidRahman-MSFT, could you please help provide clarity here?

**Comment by AbidRahman-MSFT** [comment]
Hey @SongphonRefinitiv - when using the `replaceShortcuts()` API, it will only impact the current platform the user is on. For eg. if the user is using the add-in on a Windows machine and the replaceShortcuts() API is called, the shortcut will only be replaced for Windows. It will remain the same for Mac and Web.
