### ISSUE TITLE
Naming: Office Add-Ins, Web Add-Ins

### ISSUE THREAD

**Issue by davidpomerenke** [OfficeDev/office-js-docs-pr#3192]
Office Add-Ins using web technologies are commonly referred to just as "Office Add-Ins" across the documentation. At the bottom of this documentation page under the heading `IT administrators' controls`, there is talk of "Web Add-Ins": 

> Block Web Add-ins | Allows you to prevent users from using web add-ins.

Does "Web Add-In" have the same meaning as "Office Add-In using web technologies"? 

If so, it would be good to point this out in the explaining sentence. Perhaps, the name of the setting itself could also be changed for consistency.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9684853-18cc-37d4-8556-4bfc31f5d7a9
* Version Independent ID: 4cc0db3d-c85f-8176-7629-a5bccf784a0a
* Content: [Privacy and security for Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/privacy-and-security)
* Content Source: [docs/concepts/privacy-and-security.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/concepts/privacy-and-security.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by alison-mk** [comment]
Hi @davidpomerenke, thanks for submitting this question! You are correct, **Web Add-in** has the same meaning as **Office Add-in** and **Office Add-in using web technologies**. I've submitted a PR to clarify the terms in this article. This issue will be closed when that PR is merged. I'll also look into adjusting the name of the setting, that's a good suggestion. 

Thanks again, 
Alison
