### ISSUE TITLE
Is it possible to register a custom cloud provider for mail attachments?

### ISSUE THREAD

**Issue by Odirb** [OfficeDev/office-js-docs-pr#3197]
[Enter feedback here]
Is it possible with Outlook add-ins API to register another cloud provider when an attachment is added in a new message, because it seems that only OneDrive is supported:

![Capture](https://user-images.githubusercontent.com/25641177/151176825-d258a6e5-1201-459a-8d18-e96fda49dd70.PNG)

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b2e062e-1a7a-1861-bf20-c23ac64d0d37
* Version Independent ID: ae2d1395-2a87-1bda-00fb-1b30f8e27b66
* Content: [Outlook add-ins overview - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/outlook-add-ins-overview)
* Content Source: [docs/outlook/outlook-add-ins-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/outlook/outlook-add-ins-overview.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Sreeram-ms** [comment]
@Odirb Could you please elaborate more on what usecase/scenario you are trying to solve. It is possible for 3rd party cloud storage providers to use Outlook extensibility and office-js APIs to interact with attachments in different ways. If you could elaborate more on what you are trying to solve, we might be able to help you better.

**Comment by Odirb** [comment]
Hello Sreeam,
Our company has developed a plugin for the desktop version Outlook (using VSTO) that automatically upload on our servers instead of sending then as regular attachment. For exemple, when the file is too large or contains some AIP sensitivity labels such as "confidential", theses files are uploaded on our servers with the plugin, and a link is added in the message body for download.
We would like to do the same using the javascript API "Office add-ins platform", but the only things that seems possible is creating a panel to manually select files.
So my question is, is it possible to intercept when attachment are added with "Attach / Browse this computer" the same way it was possible with VSTO. 
I have noticed that a popup is already displayed when files are too large, but only OneDrive is the only cloud provider available. Is it possible to register another cloud provider in this popup?
Thanks

**Comment by ElizabethSamuel-MSFT** [comment]
@exextoc Can you take a look? Thx.

**Comment by exextoc** [comment]
Currently the feature to register a custom cloud provider for mail attachments, you requested, is not a part of the product. We track Outlook add-in feature requests on our Tech Community Page. Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.

Github Label: “Type: product feature request”
https://aka.ms/M365dev-suggestions
