### ISSUE TITLE
Guidance for Meeting Provider Add-ins and Automatic Teams Meetings

### ISSUE THREAD

**Issue by markdon** [OfficeDev/office-js-docs-pr#3206]
I have a meeting provider add-in for Outlook. One issue my customers have is Outlook automatically enabling a Teams meeting when composing appointments, which users are not aware of. It's reportedly common for users to send an event with two sets of meeting details attached (Teams and my add-in).

Are there some already know approaches to managing this problem and other conflicts between the Teams integration and third party meeting provider add-ins?

One approach I found is to change the default for automatically adding Teams meetings using some Exchange configuration: 
https://docs.microsoft.com/en-us/powershell/module/exchange/set-organizationconfig?view=exchange-ps
https://docs.microsoft.com/en-us/powershell/module/exchange/set-mailboxcalendarconfiguration?view=exchange-ps

- Is it possible for customers to remove the Teams meeting integration in Outlook? 
- Can an add-in detect that "Teams meeting" has been enabled when composing an Event/Appointment? [I tried reading SkypeTeamsMeetingUrl via EWS](SkypeTeamsMeetingUrl) but this is only available after creating/sending.

Sorry if this isn't a docs issue. I'm not really sure where is best to find this information. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52a55fe4-0fe1-858c-26a4-dddc3ee128ea
* Version Independent ID: 0a643291-936f-b374-37fd-7db497c73cce
* Content: [Create an Outlook mobile add-in for an online-meeting provider - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/online-meeting)
* Content Source: [docs/outlook/online-meeting.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/outlook/online-meeting.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for raising this @markdon.

@ElizabethSamuel-MSFT, could you please take a look?

**Comment by ElizabethSamuel-MSFT** [comment]
@Sreeram-ms Can you provide any guidance with this? Thanks.

**Comment by exextoc** [comment]
To answer your questions:
1. Can the user disable Teams integration - This is possible to do from the Settings option. User can go to File -> Options -> Add-ins -> Deselect Teams add-in from the list
Here is the post which talks about this: https://answers.microsoft.com/en-us/outlook_com/forum/all/how-to-disable-the-teams-meeting-add-in-feature-in/9820e191-49c1-45b3-ba3b-04a0604d19f9

2. Currently it is not possible for Add-ins to detect if a Teams meeting is enabled in OWA/Mac. We track Outlook add-in feature requests on our [Tech Community Page](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2FM365dev-suggestions&data=04%7C01%7CDaniele.Bercovici%40microsoft.com%7C82496bc384404255bc6808d8fe1fde30%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637538760227690968%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=9visic2Ti%2FATFoVGDNcvO86URULWWtAvqsNRK%2BH37G8%3D&reserved=0). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.


Orgs can also remove Teams license for users through powershell commands
https://docs.microsoft.com/en-us/microsoftteams/user-access#:~:text=a%20Teams%20license-,Using%20PowerShell,Microsoft%20Teams%3A%20TEAMS1

**Comment by markdon** [comment]
Thank you @exextoc
