### ISSUE TITLE
Missing error description for error code 9020

### ISSUE THREAD

**Issue by jasonchester** [OfficeDev/office-js-docs-pr#3214]
Encountered as a result of https://github.com/OfficeDev/office-js/issues/2398 while developing an outlook add-in and testing in the browser.

see also: https://stackoverflow.com/questions/59562379/osf-dda-error-9020-on-office-context-mailbox-item-body-getasync

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad14a1fc-e890-3292-0a53-8a755db35f6e
* Version Independent ID: 78e25f2a-c710-6c16-32d7-f16d28b08e31
* Content: [Office Common API error codes - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/javascript-api-for-office-error-codes)
* Content Source: [docs/reference/javascript-api-for-office-error-codes.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/javascript-api-for-office-error-codes.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for reporting this @jasonchester.

@samantharamon, could you please take a look and update the documentation accordingly?

**Comment by samantharamon** [comment]
Thanks again for bringing this to our attention, @jasonchester. We've created a [PR](https://github.com/OfficeDev/office-js-docs-pr/pull/3227) to remedy this. Let us know if we can be of further assistance.
