### ISSUE TITLE
Gaps in article about setting up dev environment

### ISSUE THREAD

**Issue by Rick-Kirkham** [OfficeDev/office-js-docs-pr#3231]
This page doesn't mention Visual Studio as an option.
It doesn't mention Yo Office.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a18f55e3-bc76-a75f-8e0a-c64e342e91e0
* Version Independent ID: e47dd6b7-f6fa-9c01-91fd-a52febd04fb4
* Content: [Set up your development environment - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/overview/set-up-your-dev-environment)
* Content Source: [docs/overview/set-up-your-dev-environment.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/overview/set-up-your-dev-environment.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by nancy-wang** [comment]
@Rick-Kirkham Hey Rick! Did we end up getting around to this issue? Feel free to close it out if so - thanks.
