### ISSUE TITLE
Does Not Cover VS2017

### ISSUE THREAD

**Issue by laultman** [OfficeDev/office-js-docs-pr#324]
The steps in this article based on Visual Studio 2015. If you're using another version of Visual Studio, the procedures might vary slightly.
VS2017 is not even in the same ball park and VS2019 is on the way - good luck. I can't make debugging work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad34b5e8-8b67-5dfd-db60-60a9ac3ffc24
* Version Independent ID: b8b446ec-bb85-04f5-d6bf-198ba0288e04
* Content: [Create and debug Office Add-ins in Visual Studio](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/create-and-debug-office-add-ins-in-visual-studio)
* Content Source: [docs/develop/create-and-debug-office-add-ins-in-visual-studio.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/create-and-debug-office-add-ins-in-visual-studio.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
Thanks. We'll look into this.
For MS internal: https://office.visualstudio.com/OC/_workitems/edit/2508285

**Comment by lindalu-MSFT** [comment]
@Rick-Kirkham Should I assign this to another writer?

**Comment by Rick-Kirkham** [comment]
@lindalu-MSFT Nope. I got it.

**Comment by kbrandl** [comment]
@laultman thanks again for the feedback; this article has been updated.
