### ISSUE TITLE
ModuleNotFoundError after updating webpack config file

### ISSUE THREAD

**Issue by samantharamon** [OfficeDev/office-js-docs-pr#3242]
Prompted with ModuleNotFoundError after adding the following to the webpack.config.js file and running `npm run build` (see [error.txt](https://github.com/OfficeDev/office-js-docs-pr/files/8052936/error.txt) for full error log):
```
new HtmlWebpackPlugin({
  filename: "dialog.html",
  template: "./src/settings/dialog.html",
  chunks: ["polyfill", "dialog"]
})
```
### Specifications
**Document section**
'Update webpack config settings', steps 3-5.

**Platform**
Windows 11 Version 21H2 (OS Build 22000.493)

**Visual Studio Code** 
Version: 1.64.0 (user setup)
Commit: 5554b12acf27056905806867f251c859323ff7e9
Date: 2022-02-03T04:22:20.678Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

**npm**
```
{
  'office-addin-taskpane-js': '0.0.1',
  npm: '8.4.0',
  node: '16.13.2',
  v8: '9.4.146.24-node.14',
  uv: '1.42.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '93',
  nghttp2: '1.45.1',
  napi: '8',
  llhttp: '6.0.4',
  openssl: '1.1.1l+quic',
  cldr: '39.0',
  icu: '69.1',
  tz: '2021a',
  unicode: '13.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
}
```

Was able to repro the error on a VM with the same specs.

### Other notes

The webpack config file generated through yo office doesn't match the code snippets provided in the 'Update webpack config settings' section.

- Step 1
  - Generated file doesn't contain `commands: "./src/commands/commands.js`.
  - Generated file's `polyfill` value is `"@babel/polyfill`.
- Step 2
  - Generated file's `plugins` array doesn't match the tutorial's code snippet:
    
![image](https://user-images.githubusercontent.com/15154970/153701063-ed2fa29c-4c6c-453d-a90e-7edbb475813a.png)

---

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a59958d2-f428-9ca2-3440-a5af662386c0
* Version Independent ID: dcaf0b5b-08ea-c437-130b-342a1be62a16
* Content: [Tutorial: Build a message compose Outlook add-in - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/outlook-tutorial)
* Content Source: [docs/tutorials/outlook-tutorial.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/tutorials/outlook-tutorial.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by samantharamon** [comment]
@ElizabethSamuel-MSFT, when you get a chance, could you go through the Outlook tutorial to see if you can repro the error I'm getting? I was able to replicate it on a VM, but with a similar environment. I'm hoping to get a different set of eyes on this, in case it's related to my setup. Thanks!

**Comment by ElizabethSamuel-MSFT** [comment]
@samantharamon Yes, I'm seeing the same error. It seems that the core.js reference in ./src/settings/dialog.html can't be resolved.

**Comment by samantharamon** [comment]
Thanks, @ElizabethSamuel-MSFT! 

Verified the following from Ricky, Darren, and Adam: Projects created by Yo Office used to use core.js as a polyfill. This has been replaced by babel, which is automatically added to the webpack config file. Due to this, we can remove any reference to core.js from the tutorial.
