### ISSUE TITLE
The ExtendedOverrides element is incorrect. 

### ISSUE THREAD

**Issue by jamaynor** [OfficeDev/office-js-docs-pr#3245]
I am following this article, and it tells the user to:

Link the mapping file to the manifest
Immediately below (not inside) the <VersionOverrides> element in the manifest, add an [ExtendedOverrides](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/extendedoverrides) element. Set the Url attribute to the full URL of a JSON file in your project that you will create in a later step.

XML

Copy
    ...
    </VersionOverrides>  
    <ExtendedOverrides Url="https://contoso.com/addin/shortcuts.json"></ExtendedOverrides>
</OfficeApp>

The compiler in VS 2022 throws an error indicating that this element is not allowed in the xml schema. Also, the schema url is invalid. There is no file there.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fee4083-e0cd-e483-a0d7-c3bd85042c52
* Version Independent ID: 4973703e-1687-4f52-4718-8767aacf566c
* Content: [Custom keyboard shortcuts in Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts)
* Content Source: [docs/design/keyboard-shortcuts.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/design/keyboard-shortcuts.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
This is a known issue. Visual Studio has not kept the manifest definition files that it uses to validate the manifest up-to-date. You have to manually update them. Please follow the instructions in the following section and let us know if that fixes it. 

[Manifese schama validation errors in Visual Studio projects](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/troubleshoot-development-errors#manifest-schema-validation-errors-in-visual-studio-projects)
