### ISSUE TITLE
Can you add on to this PowerPoint add-in tutorial how to insert a pptx slide to an already open presentation?

### ISSUE THREAD

**Issue by mharoot** [OfficeDev/office-js-docs-pr#3259]
In an already opened presentation how can we Insert a pptx slide as a base64 encoded string to work on all platforms of powerpoint?  Is it even possible to insert a pptx slide with this project setup from this tutorial via  base64 encoded string?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18abb533-5be7-d533-8106-c52d458ddc1d
* Version Independent ID: 6af81176-d832-d3d5-5060-5218b2ba75ac
* Content: [PowerPoint add-in tutorial - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/powerpoint-tutorial?view=powerpoint-js-preview)
* Content Source: [docs/tutorials/powerpoint-tutorial.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/tutorials/powerpoint-tutorial.md)
* Product: **powerpoint**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
Yes. Your add-in inserts slides from another PowerPoint presentation into the current presentation with the [Presentation.insertSlidesFromBase64](https://docs.microsoft.com/en-us/javascript/api/powerpoint/powerpoint.presentation#powerpoint-powerpoint-presentation-insertslidesfrombase64-member(1)) method.  This method is supported on any platform that supports the PowerPointApi 1.2 requirement set. This requirement set is not supported on the one-time purchase versions of Office or PowerPoint. Please see [PowerPointApi requirement sets](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/powerpoint-api-requirement-sets) for more information.
