### ISSUE TITLE
How do you get the slide dimensions?

### ISSUE THREAD

**Issue by caredev** [OfficeDev/office-js-docs-pr#3262]
## Issue

When setting the shape's width and height properties, is there an option to set them to the slide's width and/or height ?
Is there any way to get these two sizes?

Also, is there any way to get the information on the Guides of the slide? It would be really useful to place shapes according relative to the guides.

### Example
```
textbox.width = slide.width
textbox.height = slide.height / 10
textbox.left = 0
textbox.bottom = 0
```

Thanks!

## Article URL

https://docs.microsoft.com/en-us/office/dev/add-ins/powerpoint/shapes?view=powerpoint-js-preview#text-boxes

**Comment by AlexJerabek** [comment]
Hi @caredev,

I don't believe this functionality exists today, but I'll have @Rick-Kirkham confirm. Assuming it's not, please create an idea asking for it on our [Microsoft365 Developer Platform Tech Community page](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform). There, other developers can view and upvote the idea. This helps us prioritize feature requests when adding new functionality.

**Comment by Rick-Kirkham** [comment]
Alex is correct. The PowerPoint JavaScript APIs do not provide information about the slide's dimensions or its guides. Please create an idea as Alex suggested. I will close this issue, but if you think it has been closed in error, you can still comment and we will see the comments.

**Comment by jozefizso** [comment]
When this highly requested feature will get implemented?

https://techcommunity.microsoft.com/idea/microsoft365developerplatform/powerpoint-js-api-add-support-for-getting-dimensions-of-slides/3652403

**Comment by AlexJerabek** [comment]
I'll tag @EsterBergen in case it's part of the public plans.
