### ISSUE TITLE
Register the online-meeting template for my add-in

### ISSUE THREAD

**Issue by markdon** [OfficeDev/office-js-docs-pr#3263]
The meeting provider software I'm working with is deployed per-customer on their infrastructure along with a "custom" add-in for each customer. Will we be able to get this functionality working in this case?

Can I provide further details for this privately? ![image](https://user-images.githubusercontent.com/9063681/154878442-fd0670e5-dbb2-4501-b2be-31f4eddf8e31.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52a55fe4-0fe1-858c-26a4-dddc3ee128ea
* Version Independent ID: 0a643291-936f-b374-37fd-7db497c73cce
* Content: [Create an Outlook mobile add-in for an online-meeting provider - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/online-meeting)
* Content Source: [docs/outlook/online-meeting.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/outlook/online-meeting.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for creating this issue @markdon.

@exextoc, could you please follow-up?

**Comment by exextoc** [comment]
The link [Create an Outlook mobile add-in for an online-meeting provider - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/online-meeting) you included is for mobile. To help us get the right team to follow up, could you tell us which Outlook platform you are looking to enable? (Outlook mobile, Outlook on the web, Outlook on Windows, Outlook on Mac, etc?)

**Comment by markdon** [comment]
@exextoc I believe this is only documented for mobile. My add-in does support every platform, so I am interested in enabling this kind of functionality on platforms other than mobile if it's available.

**Comment by markdon** [comment]
Can I continue the conversation about implementing this for our add-in privately? Via email in the PO?

**Comment by exextoc** [comment]
Apparently this was followed up on privately. Closing the issue.
