### ISSUE TITLE
The "Description" for the "Description" in GetStarted looks inaccurate.

### ISSUE THREAD

**Issue by Mayu945** [OfficeDev/office-js-docs-pr#3266]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c09c045-70d5-eb7b-6910-817b0a57f32e
* Version Independent ID: c30c2072-5476-b17b-72d2-ed53bf67a466
* Content: [GetStarted element in the manifest file - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/getstarted#feedback)
* Content Source: [docs/reference/manifest/getstarted.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/reference/manifest/getstarted.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
You are correct. I'll get it fixed.
