### ISSUE TITLE
Tutorial does not work as described

### ISSUE THREAD

**Issue by peternor** [OfficeDev/office-js-docs-pr#3293]
I'll make it short and to the point. I followed the steps to create the Word Add-in using Visual Studio. Upon testing the project I received an error:

JavaScript critical error at line 24, column 11 in https://localhost:44372/Home.js\n\nSCRIPT1004: Expected ';'

After two days of Googling and not getting anywhere I finally found something that makes sense. Word Add-ins use an instance Internet Explorer to load the web page. The Javascript code in your tutorial is not compatible with Internet Explorer and thus the reason for the error. 

If I learned anything from this experience at least now I know I should not be trying to develop a Word Add-in because it relies on IE and any modern javascript code is never going to run in IE so it's a waste of time.

Regards
Peter  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77e380a7-6e2e-ada8-d297-3fd5018a1958
* Version Independent ID: f23490e8-6eeb-f2d5-6c94-69e3c9ed83f4
* Content: [Build your first Word task pane add-in - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/word-quickstart?tabs=visualstudio#feedback)
* Content Source: [docs/quickstarts/word-quickstart.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/quickstarts/word-quickstart.md)
* Product: **word**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @peternor,

Thank you for this feedback. I'm sorry this hurt your productivity.

You are correct that some older versions of Word use IE11, as [documented here](https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins). You will only be limited to ES5 JavaScript if you plan on having your add-in support those versions. In those cases, you can use a [transpiler or polyfill library](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/support-ie-11) to avoid rewriting your code.

I'll leave this issue open as a task to make this clear in the quick start.

**Comment by Rick-Kirkham** [comment]
@AlexJerabek  This is an unexpected side effect of updating the JavaScript inside the Visual Studio tab of our quick starts, which we did just the other day. VS doesn't include a polyfill or transpiler. (Yo Office projects do.) Can we reverse that change, just for code inside a Visual Studio tab on quick starts and tutorials?

**Comment by AlexJerabek** [comment]
I've created PR #3295 to establish a clearer expectation of the version of Office people should be working with for the quick starts and tutorials. I'll close this issue once that change is published to the live site.

**Comment by AlexJerabek** [comment]
Closing the issue, as previously mentioned.
