### ISSUE TITLE
Enabled feature works on Word and PowerPoint as well

### ISSUE THREAD

**Issue by Mayu945** [OfficeDev/office-js-docs-pr#3302]
After adding the same control with the "enabled" feature, the manifest works on Word and PowerPoint as well.
Platform: win32

Is the Enabled feature really supported on Excel only? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c20c6831-2f89-5744-f1c3-5283ac6eb12e
* Version Independent ID: 400d9811-d5cc-1783-68a0-068358c37722
* Content: [Enabled element in the manifest file - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/enabled)
* Content Source: [docs/reference/manifest/enabled.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/reference/manifest/enabled.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
It is now supported on Word and PowerPoint. We are just days away from updating the documentation to reflect this fact.
