### ISSUE TITLE
Inconsistent requirements for Outlook on Android/iOS

### ISSUE THREAD

**Issue by TobiDimmel** [OfficeDev/office-js-docs-pr#3308]
I understand this page that you can use Add-ins with on-prem Exchange Server and Outlook on Android/iOS.
But [here](https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/requirements-for-running-office-add-ins#client-requirements-non-windows-smartphone-and-tablet) and [here](https://docs.microsoft.com/en-us/office/dev/add-ins/overview/office-add-in-availability#outlook) it is suggested that you need a Microsoft 365 subscription respectively Exchange Online.

What is correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9c9b375-5f5a-7a79-d654-e8ca9bcb23e5
* Version Independent ID: ee1bb242-ed4c-5b99-9e85-973f79cd4513
* Content: [Outlook add-in requirements - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/add-in-requirements)
* Content Source: [docs/outlook/add-in-requirements.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/outlook/add-in-requirements.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by samantharamon** [comment]
Hi @TobiDimmel,

Thanks for bringing this to our attention. I am following up on this to get clarification, so that we can provide you with the correct information and update our documentation.

**Comment by samantharamon** [comment]
Thank you for your patience, @TobiDimmel.

After looking into this further, we've confirmed that add-ins are not supported on Outlook on Android, Outlook on iOS, and modern Outlook on the web for on-prem accounts. An exception to this is add-ins on iOS devices accessed through classic Outlook on the web using an on-prem account (see [Client requirements: Non-Windows smartphone and tablet](https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/requirements-for-running-office-add-ins#client-requirements-non-windows-smartphone-and-tablet) for a list of supported iOS devices and OS). We've noted that the information in [Office client application and platform availability for Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/overview/office-add-in-availability#outlook) doesn't reflect this, so we'll work on updating this.

Please let us know if we can assist you with anything else.
