### ISSUE TITLE
Should <Script> element also be modified?

### ISSUE THREAD

**Issue by jakobpn** [OfficeDev/office-js-docs-pr#3312]
I am wondering if there is a bug in the instructions step 5 and whether the <SCRIPT> element should also be modified to:

            <Script>
              <SourceLocation resid="Taskpane.Url"/>
            </Script>

(Pointing to Taskpane.Url instead of Functions.Script.Url)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a1bb1ec-f7c0-61c7-bd50-4018a2726e3a
* Version Independent ID: dabd68f4-f474-1f01-0022-b2fe55eaafa3
* Content: [Configure your Office Add-in to use a shared JavaScript runtime - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/configure-your-add-in-to-use-a-shared-runtime)
* Content Source: [docs/develop/configure-your-add-in-to-use-a-shared-runtime.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/develop/configure-your-add-in-to-use-a-shared-runtime.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for raising this issue @jakobpn.

@davidchesnut, could you please investigate?

**Comment by davidchesnut** [comment]
Hi @jakobpn,

Good catch! Yes you should also change the <Script> tag. I put this on the backlog to fix.

**Comment by parched** [comment]
@davidchesnut what does this do now? I got rid of the `functions.js` entry point (it's now part of `taskpane.js`), and my custom functions still work. It appears I can put any URL with the same authority and it works, but if I actually remove the `<Script>` element, the add-in fails to load.

**Comment by Rick-Kirkham** [comment]
@parched I'm finding your question hard to understand. Also, instead of commenting on this closed issue, could you please create a new issue on this repo and explain your problem thoroughly? For example, what in the documentation seems wrong to you?
