### ISSUE TITLE
Tutorial works for Mac but is missing in documentation

### ISSUE THREAD

**Issue by yifeiyin** [OfficeDev/office-js-docs-pr#3314]
1. In the "Prerequisites" section, last bullet point should be
```diff
- Excel on Windows (version 1904 or later) or Excel on the web.
+ Office connected to a Microsoft 365 subscription (including Office on the web).
+ (with the purple note)
+ If you don't already have Office, you can [join the Microsoft 365 developer program](https://developer.microsoft.com/office/dev-program) to get a free, 90-day renewable Microsoft 365 subscription to use during development.
```
Staying consistent with [Word add-in tutorial - Office Add-ins | Microsoft Docs](https://docs.microsoft.com/en-ca/office/dev/add-ins/tutorials/word-tutorial) and [PowerPoint add-in tutorial - Office Add-ins | Microsoft Docs](https://docs.microsoft.com/en-ca/office/dev/add-ins/tutorials/powerpoint-tutorial) etc.

2. In the "Create a custom functions project" section, last list element
```diff
- 4. Start the local web server, which runs in Node.js. You can try out the custom function add-in in Excel on the web or Windows.
+ 4. Start the local web server, which runs in Node.js. You can try out the custom function add-in in Excel.
```
Since it works for Excel on Mac as well.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a30fb645-c853-a93a-4137-1e2bf7398a11
* Version Independent ID: 75fb99ac-72e8-7bdc-ff1b-85e7ed930d50
* Content: [Excel custom functions tutorial - Office Add-ins](https://docs.microsoft.com/en-ca/office/dev/add-ins/tutorials/excel-tutorial-create-custom-functions?tabs=excel-windows)
* Content Source: [docs/tutorials/excel-tutorial-create-custom-functions.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/tutorials/excel-tutorial-create-custom-functions.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by yifeiyin** [comment]
Just notice the line in [Custom functions quick start - Office Add-ins | Microsoft Docs](https://docs.microsoft.com/en-ca/office/dev/add-ins/quickstarts/excel-custom-functions-quickstart?tabs=excel-windows) which is the preceding article of this one in the **Office / Add-ins / Excel / Custom Functions / Tutorials** folder.
> Excel custom functions are supported in Office on Mac (connected to a Microsoft 365 subscription) and an update to this tutorial is forthcoming.

Hopefully that update will update this article as well

**Comment by AlexJerabek** [comment]
Hi @yifeiyin,

Thank you for reporting this issue. @alison-mk, could you please investigate?

**Comment by alison-mk** [comment]
Hi @yifeiyin, thanks for submitting this suggestion! I've tested and confirmed your changes, and incorporated them into a PR. Once that PR is merged, this issue will close automatically. 

Cheers, 
Alison
