### ISSUE TITLE
Manually register Excel add-in should be part of the tutorial

### ISSUE THREAD

**Issue by yifeiyin** [OfficeDev/office-js-docs-pr#3315]
- Excel on Mac Version 16.58 22021501
- Tested using `yo office` with excel custom function template
- This is really hard to figure out for beginners since the tutorial just doesn't work

Affected articles: (at least these)
- [Custom functions quick start - Office Add-ins | Microsoft Docs](https://docs.microsoft.com/en-ca/office/dev/add-ins/quickstarts/excel-custom-functions-quickstart?tabs=excel-windows#try-out-a-prebuilt-custom-function)
- [Excel custom functions tutorial - Office Add-ins | Microsoft Docs](https://docs.microsoft.com/en-ca/office/dev/add-ins/tutorials/excel-tutorial-create-custom-functions?tabs=excel-windows)

The following instructions should be:
- added to the first article
- moved to **Try out a prebuilt custom function** section, instead of being in **Create a custom function that requests data from the web** section which is one page after
> (From [Excel custom functions tutorial - Office Add-ins | Microsoft Docs](https://docs.microsoft.com/en-ca/office/dev/add-ins/tutorials/excel-tutorial-create-custom-functions?tabs=excel-windows), Section **Create a custom function that requests data from the web**)
> Complete the following steps (for Excel on the web, Windows, or Mac) to re-register the add-in in Excel. You must complete these steps before the new function will be available.
> 1. ...
> 2. ...
> (image)
> 3. In the list of available add-ins, find the Developer Add-ins section and select the starcount add-in to register it. 
> ![list-starcount](https://user-images.githubusercontent.com/13235149/158513896-1134b8d8-59a0-4f27-9420-b60197b91eed.png)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a30fb645-c853-a93a-4137-1e2bf7398a11
* Version Independent ID: 75fb99ac-72e8-7bdc-ff1b-85e7ed930d50
* Content: [Excel custom functions tutorial - Office Add-ins](https://docs.microsoft.com/en-ca/office/dev/add-ins/tutorials/excel-tutorial-create-custom-functions?tabs=excel-windows)
* Content Source: [docs/tutorials/excel-tutorial-create-custom-functions.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/tutorials/excel-tutorial-create-custom-functions.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @yifeiyin,

Thanks for reporting this issue. I'm sorry to hear yo office didn't automatically launch the add-in in Excel. @alison-mk, could you please investigate?

**Comment by alison-mk** [comment]
Hi @yifeiyin, thank you for submitting this feedback! I've tested the custom functions tutorial and quick start and confirmed your findings. I've also opened a PR to incorporate the feedback you suggested. This issue will close once that PR is merged. 

Cheers, 
Alison
