### ISSUE TITLE
Instructions are Not Correct In Sharing Section

### ISSUE THREAD

**Issue by laultman** [OfficeDev/office-js-docs-pr#332]
Section: Specify the shared folder as a trusted catalog 
5. In the Catalog Url box, enter the full network path to the shared folder catalog, and then choose Add Catalog.
The section before this one directs the user to create a directory folder share. Example "C:\b\ExcelApi\TestAddin" is a valid folder and shared with Everyone with read/write access.
Pasting the above address results in an error in step 5. "Sorry, the location you entered isn't correct - did you forget to use "https://"?" Using file://[path] does not work. Using [servername]\[path] does not work.
Does anybody really test this stuff?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ddce0bd-5c66-c2cb-0640-ee4d5bd401c5
* Version Independent ID: b5d4bc26-a43e-4a85-e7d5-fe4fc4ec3d0d
* Content: [Sideload Office Add-ins for testing](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins)
* Content Source: [docs/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by kbrandl** [comment]
Thank you for reaching out about this and sorry to hear that you're having issues with sideloading an add-in.  To identify the *network path* for the shared folder you created:

- In File Explorer, navigate to the location of that folder.
- Right-click on the shared folder you created, then choose **Properties** from the menu that appears.
- In the **Properties** dialog window, select the **Sharing** tab.
- The network path for the folder is displayed on the **Sharing** tab. (Notice that it begins with two backslashes followed by your  `\\MACHINE-NAME` followed by the path to that folder on your machine.)

For example, my machine name is `KBRANDL-2017` and I created a shared folder called `test-sideloading` on my C:\ drive (C:\test-sideloading).  The network path for this shared folder on my machine is:  `\\KBRANDL-2017\test-sideloading` -- which I can see by following the steps outlined above. 

![image](https://user-images.githubusercontent.com/3019529/44418899-813ae780-a52e-11e8-87ca-e7f6998dbdf9.png)

**Comment by maliozer** [comment]
I have done exactly like that, but when I try to insert office add-ins>shared folder, it says "Cannot connect to catalog."

**Comment by kbrandl** [comment]
@maliozer -- please note that the path to the shared catalog should begin with 2 backslashes.  Please verify that your path does begin with 2 backslashes -- i.e., using the *shared folder location* that you referenced in your comment, the path you specify should be:   `\\DESKTOP-SI4UBFB\Manifest`

**Comment by maliozer** [comment]
@kbrandl thanks a lot,  I actually used 2 bslashes, githup autocorrected my comment interestingly, but I detected that the problem exist because of network sharing.
Regards.. :)

**Comment by kbrandl** [comment]
Glad to hear that you figured out the problem -- thanks for the update!
