### ISSUE TITLE
Command doesn't work on Windows in cmd.exe

### ISSUE THREAD

**Issue by tj-aew** [OfficeDev/office-js-docs-pr#3327]
The example command for scaffolding a new project doesn't work correctly in `cmd.exe` and lacks a bit of clarity.

## Article URL

https://docs.microsoft.com/en-us/office/dev/add-ins/develop/configure-your-add-in-to-use-a-shared-runtime

## Issue

The documentation shows this command to scaffold a new project:

```
yo office --projectType excel-functions --name 'Excel shared runtime add-in' --host excel --js true
```

There are a couple of issues with that:

1. It doesn't work in `cmd.exe` with a name with spaces (like the example name). You have to use double quotes around the name, not single quotes. So instead of just doing the scaffolding, the generator walks you through the prompts, which is confusing because it seems like those things have already been specified.
2. It's not clear that you should replace `Excel shared runtime add-in` with your own project name.
3. If you _do_ realize you should replace it with your own project name, and you use a single-word name, it'll create a project directory using the `'` (some command line tools are very picky about quotes, so people tend to use exactly what's shown in the documentation).

I suggest changing it to:

```
yo office --projectType excel-functions --name "YourProjectNameHere" --host excel --js true
```

**Comment by AlexJerabek** [comment]
Thanks for reporting this @tj-aew.

@Rick-Kirkham, could you please take a look?

**Comment by Rick-Kirkham** [comment]
I can reproduce these errors. I will correct the doc.
