### ISSUE TITLE
Update Content to Increase Usability

### ISSUE THREAD

**Issue by laultman** [OfficeDev/office-js-docs-pr#333]
I received an update in response to issue #312 here: https://github.com/OfficeDev/office-js-docs-pr/issues/332 that does answer the question that mere mortals who use this stuff to make a living might not immediately recognize. Therefore I suggest the following improvements to the documentation to make it more clear to readers.  There is no reason not to be complete with instructions.
Section: Share a folder
Bullet 3 add the following text: Click the "Share..." button to open the "Network access" wizard.
Bullet 4 add the following text to the end of the existing text: In the "Network access" wizard click the "Share" button when finished adding people.
Add another bullet before number 5 or make it a note. "Before closing the "Network access" wizard, make a note of the network share address immediately below your shared folder name. You will need this in the next section. Then click the "Done" button to close the "Network access" wizard. Note: the Network Path will be displayed in the folder's Properties dialog.
Change bullet 5 to read: Click Close.

In the next section, Specify the shared folder as a trusted catalog
Change bullet 5 to read:
Using the Network Path you created in the steps above or found in your shared folder's Properties dialog Sharing tab, you will add it to your trusted catalog.  In the Catalog Url box, enter the full network path to the shared folder your catalog, and then choose Add Catalog. It should have the form "\\servername\sharedfoldername".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ddce0bd-5c66-c2cb-0640-ee4d5bd401c5
* Version Independent ID: b5d4bc26-a43e-4a85-e7d5-fe4fc4ec3d0d
* Content: [Sideload Office Add-ins for testing](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins)
* Content Source: [docs/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by kbrandl** [comment]
Thank you for the feedback; there's a work item in our backlog to update this article. We'll respond again via this GitHub issue when the article has been updated. Thanks again!

MS internal: https://office.visualstudio.com/OC/_workitems/edit/2510869

**Comment by kbrandl** [comment]
@laultman This article has been updated with additional details about the sideloading process. Thanks again for the feedback!
