### ISSUE TITLE
Content contradicts API documentation

### ISSUE THREAD

**Issue by PaulBol** [OfficeDev/office-js-docs-pr#3331]
From https://docs.microsoft.com/en-us/office/dev/add-ins/develop/initialize-add-in

> Since Office.js won't load in the browser, **`onReady` won't run** and the `$(document).ready` won't run if it's called inside the Office `onReady`.

From https://docs.microsoft.com/en-us/javascript/api/office?view=common-js-preview#office-office-onready-function(1)

> Note that though this API is intended to be used inside an Office add-in, it can also be used outside the add-in. In that case, once Office.js determines that it is running outside of an Office host application, **it will call the callback** and resolve the promise with "null" for both the host and platform.

I believe the former is wrong and the latter is correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbd18eba-b62e-b9c0-f191-630419efce38
* Version Independent ID: 151e9f51-afd2-017a-8ce7-f1c7c84e79ee
* Content: [Initialize your Office Add-in - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/initialize-add-in)
* Content Source: [docs/develop/initialize-add-in.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/develop/initialize-add-in.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for pointing this out @PaulBol.

@davidchesnut, could you please investigate this?

**Comment by davidchesnut** [comment]
Thanks @PaulBol you are correct! I added this to our backlog tracked as 5928688.

Thanks!
David

**Comment by AlexJerabek** [comment]
@PaulBol, Thank you again for reporting this. The update has been checked into the repo. The live documentation site will be updated soon.

**Comment by PaulBol** [comment]
Great, glad to see the input was helpful to improve the documentation.
