### ISSUE TITLE
What to do with the secret

### ISSUE THREAD

**Issue by SupplyChef** [OfficeDev/office-js-docs-pr#3342]
The page mentions: Generate a client secret to act as a password for your add-in when requesting a token.

There is no other mention of the secret. What do we need to do with it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb06c24b-9d11-9cc5-2e98-561601452638
* Version Independent ID: abda21d9-6e80-8319-c56f-004658014e3c
* Content: [Enable single sign-on (SSO) in an Office Add-in - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/sso-in-office-add-ins#add-client-side-code)
* Content Source: [docs/develop/sso-in-office-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/develop/sso-in-office-add-ins.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for raising this question @SupplyChef.

@davidchesnut, could you please respond and update the documentation accordingly?

**Comment by davidchesnut** [comment]
Hi @SupplyChef,

It gets used on the web server side to send to the Microsoft identity platform as part of the [On-Behalf-Of flow](https://docs.microsoft.com/azure/active-directory/develop/v2-oauth2-on-behalf-of-flow). You can see where in code it gets used by the following walkthroughs:
- [Office Add-in ASP.NET SSO](https://docs.microsoft.com/office/dev/add-ins/develop/create-sso-office-add-ins-aspnet)
- [Office Add-in Node.js SSO](https://docs.microsoft.com/office/dev/add-ins/develop/create-sso-office-add-ins-nodejs)

However, this could be better explained. @SupplyChef was there anything specific you were expecting to see in the article such as code, steps, or just more explanation? Happy to add this to the backlog to improve on.

Thanks!
David

**Comment by SupplyChef** [comment]
Thanks for the pointers. 

I was trying to enable SSO for an existing add-in and I was having troubles making it work. Since there are many moving pieces I was unsure what the problem could be. I thought the secret might have been it since it was not immediately clear to me how to use it. In the end it was unrelated: I had the wrong manifest xml. 

Maybe a line or two on the purpose of the secret would help clarify its use. 

Thanks!

**Comment by davidchesnut** [comment]
Added description for client secret. Will publish live in the next couple of days.
