### ISSUE TITLE
Update Button component example

### ISSUE THREAD

**Issue by nonstdout** [OfficeDev/office-js-docs-pr#3350]
Please update the example to reflect the fact that path of exports of fluentui have changed. As per the below post:

https://www.develop1.net/public/post/2022/03/07/fluent-ui-update-breaks-pcf-path-imports

e.g 

```js
import { PrimaryButton, IButtonProps } from "@fluentui/react/lib/Button";
import { Label } from "@fluentui/react/lib/Label";
```

not 

```
import { PrimaryButton, IButtonProps } from '@fluentui/react/lib/components/Button';
import { Label } from '@fluentui/react/lib/components/Label';
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ba07460-1e7e-7272-8a36-670a818ef61a
* Version Independent ID: 842eb2f1-4c97-df76-9bf5-75f1dc19f358
* Content: [Fluent UI React in Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/design/using-office-ui-fabric-react)
* Content Source: [docs/design/using-office-ui-fabric-react.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/design/using-office-ui-fabric-react.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for reporting this @nonstdout.

@Rick-Kirkham, could you please investigate and update the documentation as needed?
