### ISSUE TITLE
Two small problems in code block

### ISSUE THREAD

**Issue by Rick-Kirkham** [OfficeDev/office-js-docs-pr#3361]
There are two problems in the code block in this section: https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/outlook-tutorial#update-the-function-file-javascript

1. The `reason` parameter is passed to `Office.initialize` but nothing is done with it because `Office.initialize` has no body. This looks amateurish. If `initialize` doesn't have a body, it shouldn't have any parameters passsed to it. 
2. The comment "Add any UI-less function here" should be deleted. It actually appears just above a helper function, not the UI-less function, which comes later in the code block. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a59958d2-f428-9ca2-3440-a5af662386c0
* Version Independent ID: dcaf0b5b-08ea-c437-130b-342a1be62a16
* Content: [Tutorial: Build a message compose Outlook add-in - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/outlook-tutorial)
* Content Source: [docs/tutorials/outlook-tutorial.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/tutorials/outlook-tutorial.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by samantharamon** [comment]
Thanks for catching these, @Rick-Kirkham. I've added this to the backlog for fixing.
