### ISSUE TITLE
Steps to force office to use internet explorer don't seem to work for me

### ISSUE THREAD

**Issue by theboyknowsclass** [OfficeDev/office-js-docs-pr#3372]
[Enter feedback here]
 
Excel etc. seem to still load up with Webview (based on being able to inspect and get the useragent)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47b7b417-12e6-193f-6b89-37e088b31dbc
* Version Independent ID: df705bd2-5f2f-2c84-0519-fca9a3c45d71
* Content: [Internet Explorer 11 testing - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/ie-11-testing#install-a-version-of-office-that-uses-internet-explorer)
* Content Source: [docs/testing/ie-11-testing.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/testing/ie-11-testing.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @theboyknowsclass,

Could you please verify which version of Excel is installed and being used with your environment?
