### ISSUE TITLE
On-send feature for AppSource

### ISSUE THREAD

**Issue by suryakiranchikkala** [OfficeDev/office-js-docs-pr#3382]
[Enter feedback here]
Hello,
I wanted to know:

When add-ins that use the ItemSend will be allowed in AppSource? Is there a timeline ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e12d688-9620-e8f2-871d-922ec98008b5
* Version Independent ID: a8b409f3-44f7-97e5-d722-cbf04edc0653
* Content: [On-send feature for Outlook add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/outlook-on-send-addins?tabs=classic)
* Content Source: [docs/outlook/outlook-on-send-addins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/outlook/outlook-on-send-addins.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @suryakiranchikkala,

I do not believe there is a timeline for ItemSend being supported in AppSource. Let me tag @JuaneloJuanelo to confirm.

**Comment by samantharamon** [comment]
Hi, @suryakiranchikkala. Thank you for your question. Just confirming Alex's response to you. With the OnMessageSend and OnAppointmentSend events being rolled out soon (they're currently in preview), there is no timeline for ItemSend being supported in AppSource. We encourage you to explore and test using these events in your add-in instead. For further guidance, please refer to these links:
- [Use Smart Alerts and the OnMessageSend and OnAppointmentSend events in your Outlook add-in (preview)](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/smart-alerts-onmessagesend-walkthrough)
- [Configure your Outlook add-in for event-based activation](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/autolaunch)
- [AppSource listing options for your event-based Outlook add-in](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/autolaunch-store-options)
