### ISSUE TITLE
OfficeRuntime.Auth.getAccessToken is supported in mobile?

### ISSUE THREAD

**Issue by glr0221** [OfficeDev/office-js-docs-pr#3384]
Hello Microsoft,

I would like to get clarification. Your document talks about SSO working  on top of desktop and mobile using the getAccessToken() function. 

Does Mobile (IOS and Android) already support Identity API 1.3?  Or am I missing something or misunderstanding something?

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb06c24b-9d11-9cc5-2e98-561601452638
* Version Independent ID: abda21d9-6e80-8319-c56f-004658014e3c
* Content: [Enable single sign-on (SSO) in an Office Add-in - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/sso-in-office-add-ins)
* Content Source: [docs/develop/sso-in-office-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/develop/sso-in-office-add-ins.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @glr0221,

Thank you for the question. @davidchesnut, could you please investigate?

**Comment by davidchesnut** [comment]
Hi @glr0221 you are correct. SSO is not currently supported on mobile. I'll make a pass over the docs to be sure they aren't implying that anywhere. The correct list of support is documented at [Identity API requirement sets](https://docs.microsoft.com/javascript/api/requirement-sets/common/identity-api-requirement-sets). Thanks!
