### ISSUE TITLE
Is this page really still in preview after seven months, or does the title need to be updated? No reply needed, just FYI to you.

### ISSUE THREAD

**Issue by emuench** [OfficeDev/office-js-docs-pr#3387]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62a7c8c2-c855-dbcb-8858-4aa616a59a27
* Version Independent ID: c74d3973-0cdc-80b2-c6e1-2542b1be96c3
* Content: [Debug your event-based Outlook add-in (preview) - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/debug-autolaunch)
* Content Source: [docs/outlook/debug-autolaunch.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/outlook/debug-autolaunch.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@emuench Thanks for letting us know. We'll take a look.

Thanks.

**Comment by samantharamon** [comment]
Hi @emuench,

Thank you for bringing this to our attention. We've verified that debugging event-based Outlook add-in is no longer in preview. We'll update this article accordingly.
