### ISSUE TITLE
Get 404 after clicking "Insert Image" button

### ISSUE THREAD

**Issue by kinnplh** [OfficeDev/office-js-docs-pr#3397]
Hi, I followed the steps in the "Insert an Image" section and encountered a problem when trying the add-in. When I clicked the Insert Image button,  it showed an error notification. I set a break-point and found that the ajax returned 404 when getting /api/Photo/.

It seems that the tutorial has not discussed how I can configure the routers and I wonder whether the routers are configured automatically.

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18abb533-5be7-d533-8106-c52d458ddc1d
* Version Independent ID: 6af81176-d832-d3d5-5060-5218b2ba75ac
* Content: [PowerPoint add-in tutorial - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/powerpoint-tutorial#insert-an-image)
* Content Source: [docs/tutorials/powerpoint-tutorial.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/tutorials/powerpoint-tutorial.md)
* Product: **powerpoint**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @kinnplh,

Thanks for reporting this issue. @Rick-Kirkham, could you please investigate?

**Comment by Rick-Kirkham** [comment]
If you paste this URL into the browser, does the image open? http://bing.com/th?id=OHR.LeiDay_EN-US2557797109_1920x1080.jpg&rf=LaDigue_1920x1080.jpg&pid=hp

**Comment by kinnplh** [comment]
> If you paste this URL into the browser, does the image open? http://bing.com/th?id=OHR.LeiDay_EN-US2557797109_1920x1080.jpg&rf=LaDigue_1920x1080.jpg&pid=hp

Thank you for your response! Yes, the image opens. Besides, I modified the `Get()` function in the `PhotoController` and returned a hardcode base64 string (similar to the `getImageAsBase64String` function in the [previous article](https://docs.microsoft.com/zh-cn/office/dev/add-ins/quickstarts/powerpoint-quickstart?tabs=visualstudio)), but I still got the same error. I think there may be something wrong with the routers and the `Get()` function is not called.

**Comment by kinnplh** [comment]
Thank you! I will also try to solve the problem ~

**Comment by kinnplh** [comment]
I found an archived [repo](https://github.com/OfficeDev/Office-Add-in-JavaScript-WebApiService). I add the code in the tutorial to that project and it works.  I compare the codes and it seems that some important files (such as Global.asax and WebApiConfig.cs) are missing in the tutorial.

**Comment by Rick-Kirkham** [comment]
I have reproduced this. I haven't tried to reproduce your workaround yet, but I'm sure you are right. Visual Studio is not creating some of the needed folders and files. I'm not sure when these should be created. It is either when the project is created or when the reader is instructed to add a **Web API 2 Controller - Empty** scaffolding. Probably, the latter. This seems to be a bug in Visual Studio. I will report this. I will also update the doc to add the missing stuff manually.

**Comment by Rick-Kirkham** [comment]
I've found the range of VS 2019 version numbers that have the bug. Instead of giving the reader tedious instructions for manually creating the scaffolding, I'll just have the instructions warn readers not to use the buggy versions. VS 2022 is not affected by the bug.
