### ISSUE TITLE
Debug instructions don't work for office.js on mac

### ISSUE THREAD

**Issue by gullbyrd** [OfficeDev/office-js-docs-pr#3398]
This simply doesn't work. I installed the non-mac store version from the dev program, entered the word command in terminal, multiple times, and nothing will get the context menu to appear when I right-click in the addin. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be179784-5839-3e8f-c131-1f4d89808b03
* Version Independent ID: 69bca101-91a2-3a5e-5177-493723504354
* Content: [Debug Office Add-ins on a Mac - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-office-add-ins-on-ipad-and-mac#debugging-with-safari-web-inspector-on-a-mac)
* Content Source: [docs/testing/debug-office-add-ins-on-ipad-and-mac.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/testing/debug-office-add-ins-on-ipad-and-mac.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @gullbyrd,

Sorry to hear you're having issues. Could you please clarify what you mean by "non-mac store version"? What version of Office are you using to build and test your add-in? Thanks!

Let me also assign @alison-mk to start investigating.

**Comment by gullbyrd** [comment]
This issue has been resolved. As a Windows guy, I didn’t know that you have
to press ctrl-right-click (as opposed to just right-click) to bring up the
context menu in a Mac.
I hate Macs.

**Comment by alison-mk** [comment]
Thanks for reporting back about your solution, @gullbyrd!
