### ISSUE TITLE
Documentation for adding Office types 

### ISSUE THREAD

**Issue by dvanurag1308** [OfficeDev/office-js-docs-pr#340]
The content in step 9
   declare const Excel: any;
Can we get documentation on adding the Office/Excel types as dev dependencies to angular please.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92388aeb-7561-deae-26df-aab50feb71b8
* Version Independent ID: aa282880-d613-d7d8-ddb3-6a61c8a155bf
* Content: [Build an Excel add-in using Angular](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-get-started-angular)
* Content Source: [docs/excel/excel-add-ins-get-started-angular.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/excel-add-ins-get-started-angular.md)
* Product: **office 365**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @dvanurag1308 
Thank you for your feedback. @kbrandl is working on [rewriting the Excel Angular quick start](https://github.com/OfficeDev/office-js-docs-pr/issues/330) to use the latest features of yo office. It that iteration, you select Angular and Typescript as options from yo office. That automatically imports all the types from office-js (including Excel).

Try redoing the yo office step selecting Angular and Typescript and see if that works for you. Please let me know how that goes.

**Comment by dvanurag1308** [comment]
I did that as well but it completely alters the usual project setup of angular like making it's own webpack script which I am not used to.

**Comment by cakriwut** [comment]
Please see pull request #372

**Comment by kbrandl** [comment]
@dvanurag1308 we've significantly revised this quick start, to reflect that the Yeoman generator for Office Add-ins is now the recommended way of generating an Office Add-in project using the Angular framework. Please give the new instructions a try and feel free to reach out again if you have any trouble.

Additional information about the Office.js TypeScript definitions is available in the [OfficeDev/office-js README](https://github.com/OfficeDev/office-js/blob/release/README.md#intellisense-definitions).
