### ISSUE TITLE
please add an example returing a dymanic spill array from a streaming function

### ISSUE THREAD

**Issue by sdbarrington** [OfficeDev/office-js-docs-pr#3411]
please add an example returing a dymanic spill array from a streaming function

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3aa98c9b-159b-fdc6-03e6-283d483e0d3e
* Version Independent ID: 17f6b1ef-ee34-3f1c-2c9d-828c4a3dd950
* Content: [Return multiple results from your custom function - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-dynamic-arrays)
* Content Source: [docs/excel/custom-functions-dynamic-arrays.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/excel/custom-functions-dynamic-arrays.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @sdbarrington,
 
Thank you for the documentation sample request. @alison-mk, can you please investigate and add the request to our backlog as appropriate?

**Comment by alison-mk** [comment]
Hi @sdbarrington, thank you for submitting this request. Here is a GitHub Gist with a code snippet showing a streaming custom function that returns a dynamic spilled array: https://gist.github.com/alison-mk/322b1a3632de8033ead545afbbc8acda. 

I will add this code snippet to our documentation in the near future — that task is in my backlog ([internal tracking link](https://office.visualstudio.com/OC/_workitems/edit/6057195)). I will close this issue now. Let me know if you have any additional questions. 

Cheers, 
Alison

**Comment by sdbarrington** [comment]
thanks!
