### ISSUE TITLE
Missing instruction while testing with Office development tool

### ISSUE THREAD

**Issue by rvab** [OfficeDev/office-js-docs-pr#3412]
Once the Office Deployment Tool(https://www.microsoft.com/download/details.aspx?id=49117) is downloaded. The downloaded file is `officedeploymenttool_15028-20160.exe`. You need to execute the `officedeploymenttool_15028-20160.exe` file in order to get the `setup.exe` file. This instruction was missing. It took me a while to figure this out. Please do mention this. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47b7b417-12e6-193f-6b89-37e088b31dbc
* Version Independent ID: df705bd2-5f2f-2c84-0519-fca9a3c45d71
* Content: [Internet Explorer 11 testing - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/ie-11-testing)
* Content Source: [docs/testing/ie-11-testing.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/testing/ie-11-testing.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for reporting this missing step @rvab.

@Rick-Kirkham, could you please verify and update the documentation accordingly?
