### ISSUE TITLE
A note points to a deprecated link in documentation

### ISSUE THREAD

**Issue by kasturgo** [OfficeDev/office-js-docs-pr#3414]
Under [Authorize the backend Web API](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/implement-sso-in-outlook-add-in#authorize-the-backend-web-api) it is mentioned 

Note

The example add-in at [Outlook Add-in SSO](https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/auth/Outlook-Add-in-SSO) shows how to use the [Dialog API](https://docs.microsoft.com/en-us/javascript/api/office/office.ui#displaydialogasync-startaddress--options--callback-) and the [office-js-helpers library](https://github.com/OfficeDev/office-js-helpers) as options to start the [OAuth2 Authorization Code flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-protocols-oauth-code) for the API.

office-js-helpers link point to deprecated link and seems to use Implicit Auth flow, whereas the note suggests to use Auth code grant flow.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53319dc9-a8e9-323e-6ccf-ce169b90abac
* Version Independent ID: 408dbc47-f781-b027-1596-2c91cbbde06b
* Content: [Scenario - Implement single sign-on to your service - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/implement-sso-in-outlook-add-in#add-in-scenario)
* Content Source: [docs/outlook/implement-sso-in-outlook-add-in.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/outlook/implement-sso-in-outlook-add-in.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by davidchesnut** [comment]
I updated the references in PR #3429  So this should be fixed now.
Thanks @kasturgo!
