### ISSUE TITLE
Error in web command

### ISSUE THREAD

**Issue by sanjgupt** [OfficeDev/office-js-docs-pr#3415]
[Enter feedback here]
Hi when following the instructions to sideload the add-in on the web, I get the following error: 

![image](https://user-images.githubusercontent.com/42555338/167478732-e8139ee8-4631-46aa-8a67-b8a7bb9bd8b3.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c4ddde7-f1fd-44ba-fba1-0ae9d0131df7
* Version Independent ID: d946ffe6-f29f-1563-b679-121090ba60a1
* Content: [Build your first Excel task pane add-in - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-jquery?tabs=yeomangenerator)
* Content Source: [docs/quickstarts/excel-quickstart-jquery.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/quickstarts/excel-quickstart-jquery.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @sanjgupt,

Did you get any errors when running `yo office`? What happens when you run `npm start` (without the web command)?

**Comment by sanjgupt** [comment]
Hi @AlexJerabek , the documentation did not say, but it only worked when I ran the terminal in admin mode.

**Comment by AlexJerabek** [comment]
@Rick-Kirkham, is the requirement to run yo office as an admin new?

**Comment by sanjgupt** [comment]
Hi @AlexJerabek , I would like to take back my previous comment about yo office. I updated node and everything is now working correctly.The npm run start:web command now fails as follows: 
![image](https://user-images.githubusercontent.com/42555338/168653795-13f41b4c-9e3e-4096-914e-533ac7e4c27d.png)

**Comment by Rick-Kirkham** [comment]
I can run Yo Office in non-Admin mode. No problems.

**Comment by AlexJerabek** [comment]
Thanks @sanjgupt. I'm glad you're unblocked. Please let us know if you find any other issues.

It looks like there's a mention of needing to run in admin mode in the quickstart, so I'll close this issue. @Rick-Kirkham, if you think that note needs to be changed in any way to help discoverability, please reopen the issue.

![image](https://user-images.githubusercontent.com/38896772/168669807-8009c8f4-11b9-4cbf-9f5b-8ec22284864b.png)
