### ISSUE TITLE
How to set Title of Office Dialog

### ISSUE THREAD

**Issue by bhattikashif** [OfficeDev/office-js-docs-pr#3425]
This page says that "Include a descriptive title that includes your add-in name along with the current task. " but I am unable to find a way to change Dialog's Title. Can you provide a sample of how one can change it?

<br class="Apple-interchange-newline">
</body>
</html>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c50f3482-ada7-b54a-392f-73b7524cd9dc
* Version Independent ID: 36f8730a-c373-b4da-dbbb-917a7ac54235
* Content: [Dialog boxes in Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/design/dialog-boxes)
* Content Source: [docs/design/dialog-boxes.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/design/dialog-boxes.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for this sample request @bhattikashif. 

@Rick-Kirkham, could you plese help out here?

**Comment by Rick-Kirkham** [comment]
@bhattikashif Good catch. That line in the article is misleading. Currently, you cannot control the title of the dialog. It will always begin with the name of the add-in. It takes this string from the `<DisplayName>` element in the manifest. If the page that is initially opened has a `<title>` element, then the name of the add-in is followed by a dash and then the value of the `<title>` element. We are working on providing greater control over the dialog title, but that won't be available any earlier than late this year. In the meantime, I will remove that misleading line from the article.
