### ISSUE TITLE
Tutorial: Create an Excel task pane add-in does not work (on my machine)

### ISSUE THREAD

**Issue by georgekeeling** [OfficeDev/office-js-docs-pr#3436]
Comment modified 24 May 11:20 CET. What I saw or typed on screen is now in **bold**.
I have installed Visual studio 2022 (this may be irrelevant) and am trying to follow this tutorial which is at 
https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/excel-tutorial
It does not seem to work!

I had to additionally install node.js 16.14-0 LTS Recommended for most users from https://nodejs.org/en/ 
It asks me to close all programs for duration of installation ...

A great deal happens at command prompt then in Windows PowerShell
the last two lines are both 
**[01fc:0020][2022-05-23T11:25:00] ManifestVerifier Result: Success**
I have no idea if node.js is installed OK.

The full powershell output is here [PowerShell1.docx](https://github.com/OfficeDev/office-js-docs-pr/files/8753721/PowerShell1.docx). There were two errors on p 14 of 15. The first one was 
**[01fc:0012][2022-05-23T11:25:00] Error 0x8013153b: [01fc:0012][2022-05-23T11:25:00] Could not update channel "https://aka.ms/vs/16/release/channel"**

I then ran **npm install -g yo generator-office** which seemed to work. 

I then Ran **yo office** and after I answered the questions it did something then said

**Creating My Office Add-in add-in for Excel using JavaScript and Taskpane at C:\Program Files\Microsoft Visual Studio\2022\Community\My Office Add-in**

**Unable to download project zip file for "https://github.com/OfficeDev/Office-Addin-TaskPane-JS/archive/yo-office.zip".**

Is there something missing from github?  Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac7d9e2d-b537-cf1f-95fb-4e216514f3b1
* Version Independent ID: 4a86c93b-70d8-38e4-f62e-83c43a0158dd
* Content: [Excel add-in tutorial - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/excel-tutorial)
* Content Source: [docs/tutorials/excel-tutorial.md](https://github.com/OfficeDev/office-js-d
[PowerShell1.docx](https://github.com/OfficeDev/office-js-docs-pr/files/8753718/PowerShell1.docx)
ocs-pr/blob/main/docs/tutorials/excel-tutorial.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for reporting this @georgekeeling.

@Rick-Kirkham, could you please take a look?

**Comment by Rick-Kirkham** [comment]
@georgekeeling I need some clarification about the issue. You mention Visual Studio 2022 at the beginning, but this tutorial does not use Visual Studio. If you are having difficulty installing node, then you should raise that problem on the node website. Finally, it is hard to tell which lines in your description are your words and which are things you are seeing in a window. Please specify what is the first thing that goes wrong and the steps leading up to it. What do you expect to see and what do you actually see?

**Comment by georgekeeling** [comment]
@Rick-Kirkham Thanks for responding. 
1) I mentioned installing Visual Studio because that is why I arrived here. It max not be relevant.
2) I don't know whether I installed node OK or not. There was 15 pages of output during the install! The last like said **ManifestVerifier Result: Success**, but other lines reported errors as described. I will ask on the node website what the 15 pages mean.
3) I have modified the original post to clarify what appeared on the screen or what I typed on the screen at the time. It is in **bold** as it is here.
4) Right at the end after I ran **yo office** and answered the questions according to the instructions I expected it to say "Congratulations you created an Excel thing" (or similar) but it actually said **Unable to download project zip file for "https://github.com/OfficeDev/Office-Addin-TaskPane-JS/archive/yo-office.zip".**

**Comment by georgekeeling** [comment]
OOPS! I was running **yo office** in a directory where it couldn't create directories / files without some permission. If it had said 
**Unable to download project zip file for "https://github.com/OfficeDev/Office-Addin-TaskPane-JS/archive/yo-office.zip" to C:\Program Files\Microsoft Visual Studio\2022\Community** 
We might have got there quicker.  
My Office Add-in has now been created successfully! Thank you!
