### ISSUE TITLE
Better docs for UI-less custom functions for Excel

### ISSUE THREAD

**Issue by ianengelbrecht** [OfficeDev/office-js-docs-pr#3467]
The section on UI-less custom functions has three subsections: authentication, debugging, and runtime. We need another subsection that explains how to set up a UI-less custom function from scratch. The only information available is in the dubugging section, which says 'To create a UI-less custom function, follow the steps in the Create custom functions in Excel tutorial, and then remove all of the task pane and UI elements that are installed by the Yeoman generator for Office Add-ins'. We need to know exactly what we can remove. Even better would be to have an option in the Yeoman generator for creating a UI-less custom function. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0bedd430-d224-565e-c1b1-15f90994aa52
* Version Independent ID: b41539c4-c9ec-c678-e44b-27bd456b9c0b
* Content: [UI-less custom functions debugging - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-debugging)
* Content Source: [docs/excel/custom-functions-debugging.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/excel/custom-functions-debugging.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by alison-mk** [comment]
Hi @ianengelbrecht, thanks for submitting an issue. We're actually currently in the process of updating the custom functions articles you mention.

The recommended approach for developing custom functions add-ins is to use a [shared runtime](https://docs.microsoft.com/office/dev/add-ins/develop/configure-your-add-in-to-use-a-shared-runtime). A shared runtime allows your add-in to use a task pane or a ribbon button, in addition to running custom function code. 

Can you describe why you'd like to create a UI-less custom function?

Alison

**Comment by ianengelbrecht** [comment]
Thanks @alison-mk , I appreciate the feedback! I originally wrote a custom function for pre-2019 Excel that converts geographic coordinates from a wide range of formats to decimal degrees, which is at https://github.com/ianengelbrecht/geocoordsparserexcel. It was based on a javascript implementation that I wrote for web/node, which I translated to C#. It doesn't work anymore because the signing certificate expired and I haven't worked out how to add a new one yet. The plugin itself is/was available at http://bit.ly/convertcoords. This worked without a task pane, and so I wanted to create the same thing again, but using he original javascript function, for Excel 2019+. I don't think a task pane (and hence shared runtime) is needed, but any advice would be great.

**Comment by alison-mk** [comment]
Hi @ianengelbrecht, 

To create a custom functions add-in that doesn't need to interact with the Excel UI, the recommended process is simply to follow the steps in the [Create custom functions in Excel](https://docs.microsoft.com/office/dev/add-ins/tutorials/excel-tutorial-create-custom-functions?tabs=excel-windows) tutorial. The **Excel Custom Functions Add-in project** in Yo Office creates a lightweight custom functions add-in that has a task pane and uses a streamlined runtime that is not shared runtime.

I realize that this doesn't match the guidance in the current Debugging article. The Debugging article update is in PR #3461. We're also in the process of adjusting the term "UI-less custom function" to more clearly indicate that the current Yo Office template creates the recommended non-shared runtime custom function. I'll leave this issue open until that process is complete.

Thanks, 
Alison

**Comment by alison-mk** [comment]
Hi @ianengelbrecht, 

We've completed the planned documentation updates to clarify the distinction between types of custom functions with PRs #3461 and #3496. The primary distinction is whether or not a custom functions add-in uses a shared runtime, not whether a custom functions add-in has a UI. That said, we do recommend that custom functions add-ins with Excel UI elements use a shared runtime. 

Since our planned updates are complete, I will close this issue. Let us know if you have any further questions. 

Thank you, 
Alison
