### ISSUE TITLE
Initial debug instructions reversed and incomplete, not usable

### ISSUE THREAD

**Issue by petera703** [OfficeDev/office-js-docs-pr#3485]
The first steps include "On the Debug menu, choose Start Debugging." But this fails, owing to the lack of certificate. A certificate is then created in the following step, but the initial debugging is never revisited. If attempted anyway, there is no sign of the add-in, either at the UI or in in My Add-Ins, and there is no information in the article to explain how to show and use the Add-In. This doesn't provide a good starting-point for making changes to the add-in and seeing that it still works, as it cannot be seen working in its original form. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e750012-89a3-3471-06e8-e1410d10568c
* Version Independent ID: 560869f0-c785-56ac-cb4e-94f14d350f2c
* Content: [Tutorial: Share code between both a VSTO Add-in and an Office Add-in by using a shared code library - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/migrate-vsto-to-office-add-in-shared-code-library-tutorial)
* Content Source: [docs/tutorials/migrate-vsto-to-office-add-in-shared-code-library-tutorial.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/tutorials/migrate-vsto-to-office-add-in-shared-code-library-tutorial.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @petera703,

Thanks for reporting this. @Rick-Kirkham, could you please investigate?

**Comment by davidchesnut** [comment]
Hi @petera703, thanks I am looking into this.

**Comment by davidchesnut** [comment]
Hi @petera703, the article is correct but the sample had old certificate references in the project files. They aren't needed so I removed them in this PR: https://github.com/OfficeDev/Office-Add-in-samples/pull/341. If you can check that the PR fixes this, that would be great! Thanks!

**Comment by petera703** [comment]
Hi @davidchesnut. Thanks for your reply. I'll try the steps again when I get a chance. By the way,m you say the article is correct but as I mentioned, there is nothing to explain how to show and use the Add-In. We can see that it is a cell analyzer add-in, but does that mean we type a value in a cell and click some button that appears? Or perhaps it will analyze all the cells in the sheet, and might run every time we press a key? And I couldn't see any screenshots of the add-in, so we don't know what to look out for. Thanks.

**Comment by davidchesnut** [comment]
It's in the explanation after the numbered steps in https://docs.microsoft.com/office/dev/add-ins/tutorials/migrate-vsto-to-office-add-in-shared-code-library-tutorial#the-cell-analyzer-vsto-add-in. You can type text in a cell, and then have the add-in show the Unicode of the text characters.

I also just noticed the steps have you create a test certificate for the signing problem but if I can eliminate the need for any certificate, I'll remove those steps.

Thanks!

**Comment by davidchesnut** [comment]
I've updated the sample and steps in the article, so creating a test certificate is no longer needed. Please reopen if you find any additional issues. Thanks!
