### ISSUE TITLE
Something went wrong and could not start the add-in. Please try again later or contact your system administrator

### ISSUE THREAD

**Issue by Aizaz-Rehman** [OfficeDev/office-js-docs-pr#3486]

**Comment by AlexJerabek** [comment]
Hi @Aizaz-Rehman,

We'd like to help with your issue, but we'll need more information. First, what quick start, tutorial, or sample were you running when you encountered this issue? We'll also need the following system information to help diagnose the problem.

* Platform [PC desktop, Mac, iOS, Office on the web]: ______
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): ______

Thanks!
