### ISSUE TITLE
Enable and Disable Add-in Commands : Not working in word

### ISSUE THREAD

**Issue by nvazhayil** [OfficeDev/office-js-docs-pr#3499]
Referring to https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/word-quickstart?tabs=yeomangenerator and https://docs.microsoft.com/en-us/office/dev/add-ins/design/disable-add-in-commands, I created a **Word task pane add-in**. 

As per the Ribbon API requirement sets, RibbonApi 1.1 should be available in "Office on the Web", But when I tried **Office.context.requirements.isSetSupported('RibbonApi', '1.1')**, it returns false.

I want to use the Enable and Disable Add-in Commands feature on word and I am unable to get started with whatever is in the documentation. Please suggest on how to proceed on this.

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c7b653d-1bd6-a032-2046-6d6a2ad2b203
* Version Independent ID: 7165a66d-bc9a-dce9-91c4-7c1209d1324e
* Content: [Enable and Disable Add-in Commands - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/design/disable-add-in-commands#shared-runtime-required)
* Content Source: [docs/design/disable-add-in-commands.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/design/disable-add-in-commands.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @nvazhayil,

Currently, the RibbonApi requirement sets are only supported in Excel. From the article [Ribbon API requirement sets](https://docs.microsoft.com/en-us/javascript/api/requirement-sets/common/ribbon-api-requirement-sets):

> The Ribbon API is supported for production add-ins only in Excel. It's available as a preview in PowerPoint and Word, but only in Office on Windows (subscription) and Mac.

You can also find a complete list of supported requirement sets for each application and platform on [Office client application and platform availability for Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/requirement-sets).

Please visit our feedback portal to request or upvote support for contextual tabs in Word on the web: https://feedbackportal.microsoft.com/feedback

I'll leave the issue open and tag @Rick-Kirkham to see if there's a way to make this information more apparent in the RibbonApi article.

**Comment by nvazhayil** [comment]
Hi Alex,

I am not trying for a production add-in but a sample project with Office on Web. As per [Ribbon API requirement sets](https://docs.microsoft.com/en-us/javascript/api/requirement-sets/common/ribbon-api-requirement-sets), RibbonApi 1.1 is supported from November, 2020 in **Office on Web**. Right?

**Comment by Rick-Kirkham** [comment]
RibbonApi 1.1 is only supported on Windows and Mac for Word and PowerPoint, not Office on the Web. Note this sentence from the article "It's available as a preview in PowerPoint and Word, but only in Office on Windows (subscription) and Mac."

I'll close this, but you can still make comments and we'll see them.

**Comment by nvazhayil** [comment]
When can we expect this for Office on Web?

**Comment by Rick-Kirkham** [comment]
> When can we expect this for Office on Web?

I'm making inquiries internally.

**Comment by Rick-Kirkham** [comment]
@nvazhayil We are not currently working on supporting this feature on Word on the web, but hope to begin work later this year. We can't give you any dates, but it will be many months at best before this feature is supported in Word on the web.

**Comment by nvazhayil** [comment]
Thanks for the update.
