### ISSUE TITLE
Improvements for macOS add-in sideloading process

### ISSUE THREAD

**Issue by yoonbuck** [OfficeDev/office-js-docs-pr#3502]
It'd be nice to pull the instructions for sideloading an add-in on macOS onto a separate page from iPad, since the process is different and it's not super clear that the reader needs to scroll down so far to get to the instructions - the macOS section is in the collapsed part of the navigation on the right. (It seems more likely that someone is trying to sideload on macOS than on an iPad, but maybe you have data that shows otherwise! 😁)

For the instructions themselves, I think it might be easier to give users instructions that don't use the Terminal, since it isn't really necessary. My recommendation would be:

1. Open Finder, and press Shift-Command-G (Go to Folder)
2. Paste in `~/Library/Containers/com.microsoft.Excel/Data/Documents` (or corresponding folder for other app)
3. If there is no folder called `wef`, create it.
4. Open `wef` and copy the manifest file into that folder.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 589820d2-9925-dc5e-76a7-83921a569137
* Version Independent ID: ab8bde36-096f-81f3-f4d1-9b25fc69e6ee
* Content: [Sideload Office Add-ins on iPad and Mac for testing - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/sideload-an-office-add-in-on-ipad-and-mac#sideload-an-add-in-in-office-on-mac)
* Content Source: [docs/testing/sideload-an-office-add-in-on-ipad-and-mac.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/testing/sideload-an-office-add-in-on-ipad-and-mac.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for the suggestions @yoonbuck.

@alison-mk, could you please investigate these improvements?

**Comment by alison-mk** [comment]
Hi @yoonbuck, thank you for submitting these suggestions! I have opened PR #3515 to incorporate your suggestions. Once that PR is complete and merged, this issue will automatically close. 

Cheers, 
Alison
