### ISSUE TITLE
More detailed explanation of Custom Function Limitations

### ISSUE THREAD

**Issue by david-ps** [OfficeDev/office-js-docs-pr#3506]
The [limitations list](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/call-excel-apis-from-custom-function#limitations-of-calling-excel-javascript-apis-through-a-custom-function) says custom functions should not: "Add names to a workbook" or "Set properties or execute most methods"

It would be great to know more detail about the implications of these actions and what methods can safely be called and why?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fe047a0-5f60-f407-2ad0-7f4cc8e52082
* Version Independent ID: f2ebc9bd-25f6-cfc2-dbbe-d0090096f656
* Content: [Call Excel JavaScript APIs from a custom function - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/call-excel-apis-from-custom-function)
* Content Source: [docs/excel/call-excel-apis-from-custom-function.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/excel/call-excel-apis-from-custom-function.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @david-ps,

Thanks for raising this documentation request. I'll assign this to @alison-mk.

**Comment by alison-mk** [comment]
Hi @david-ps, thank you for submitting this feedback. I will do research internally to determine the answers and then update the article when my research is complete. I'll leave this issue open in the interim.

Cheers,
Alison

**Comment by alison-mk** [comment]
Hi @david-ps, thanks for your patience and for submitting this issue. I've done research internally and have some clarification to offer: 

Custom functions shouldn't change cells outside of the cell running the custom function. Custom functions also should not change the Excel environment (such as by changing Excel's language settings, or by adding worksheets). Custom functions can use Excel JavaScript APIs to *read* information from other cells or the Excel environment, but custom functions shouldn't *write* information to other cells or the Excel environment. 

Using Excel JavaScript APIs to *write* information to other cells or the Excel environment may cause performance issues with the Excel application, such as by causing Excel to crash. If your add-in needs to write information to other cells or the Excel environment, our recommended best practice is to use a task pane or ribbon button.

I've updated the article in PR #3610 to clarify the limitations and will close this issue. 

Thanks again, 
Alison

**Comment by david-ps** [comment]
Thankyou 🙂
