### ISSUE TITLE
Issue with Redirect URI for Vainity/Custom URL

### ISSUE THREAD

**Issue by gagandeepsubbi** [OfficeDev/office-js-docs-pr#3523]
## Article URL
https://docs.microsoft.com/en-us/office/dev/add-ins/develop/sso-in-office-add-ins

## Issue
We are trying to use the article for SSO and getting the attached error for Redirect URI. The error is seen when we are using Vanity URL for OWA. 
![ERROR](https://user-images.githubusercontent.com/108798773/177524474-1a1b8c01-879c-4221-b4a3-844b14555af6.png)

**Comment by AlexJerabek** [comment]
Thanks for reporting this issue @gagandeepsubbi.

@davidchesnut, could you please investigate?

**Comment by gagandeepsubbi** [comment]
Hi @davidchesnut  Did you get a change to take a look at this?

**Comment by davidchesnut** [comment]
Hi @gagandeepsubbi,

Sorry for late reply.  In the Azure portal, go to your app registration, and go to the **Expose an API** page. There is an **Application ID URI** with a value similar to "api://localhost:44351/{app id}" Make sure in your maniifest for the add-in that this value appears exactly in the Resource tag in the WebApplicationInfo section. Also be sure your web server is using the exact port (such as 44351) as specified in the **Application ID URI**. 

Hope this helps,
David

**Comment by gagandeepsubbi** [comment]
Thank you @davidchesnut  for your response. To add more details, we are using Exchange Online and not an On-Prem setup. The redirection URL is not pointing to any server. From the error message, the Redirect URI Mismatch is for the vanity URL on the Microsoft Outlook add-in application with id "bc59ab01-8403-45c6-8796-ac3ef710b3e3" and not the Azure app we created.

**Comment by AlexJerabek** [comment]
Hi @gagandeepsubbi,

Thank you for the response. We are investigating this issue internally. I'm assigning @mattgeim to follow-up with you.

**Comment by AlexJerabek** [comment]
This issue was resolved a few months ago, with fix instructions sent to admins through the Admin Message Center. If folks are still having problems, we can reopen the issue.
