### ISSUE TITLE
Page does not explain how to create a COM Add-In

### ISSUE THREAD

**Issue by BenoitJGirard** [OfficeDev/office-js-docs-pr#3529]
The page keep showing in search results to create a COM Add-In for OneNote, but only refers to a javascript+HTML Add-In. 

I am not interested in developing in HTML and javascript!

And it definitely looks like the OneNote application on Windows still supports COM Add-Ins.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6ed3136-1d12-66c2-a8b1-1e7e43553aae
* Version Independent ID: 0e40308a-2d3d-a27b-04d5-1bdd7c09b501
* Content: [Build your first OneNote task pane add-in - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/onenote-quickstart)
* Content Source: [docs/quickstarts/onenote-quickstart.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/quickstarts/onenote-quickstart.md)
* Product: **onenote**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @BenoitJGirard,

You're right that the information for how to make OneNote add-ins that don't use the current web-based model is difficult to find. I believe what you're looking for is here: https://docs.microsoft.com/en-us/office/client-developer/onenote/onenote-developer-reference?redirectedfrom=MSDN

I'm going to close this issue, as there's nothing actionable here to do in the web add-in documentation.
