### ISSUE TITLE
Show Taskpane doesn't appear under home menu. 

### ISSUE THREAD

**Issue by user135711** [OfficeDev/office-js-docs-pr#354]
## Article URL
https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/excel-tutorial?tutorial-step=3

## Issue

 
Step 4 states:

>  "Reload the task pane by closing it, and then on the Home menu, select Show Taskpane to reopen the add-in." 
I could not find this option under the home ribbon. I even looked under customize the ribbon. I reopened it with insert>My Add-ins> My office Add-in.

**Comment by AlexJerabek** [comment]
Hi @user135711,
Sorry to hear that step was confusing. Did you carry out the sideloading steps linked to in step 4 of "Test the add-in"? If so, which version?

**Comment by user135711** [comment]
@AlexJerabek Yes, I followed all the steps. I made a mistake somewhere because when I click the buttons, nothing happens.

**Comment by user135711** [comment]
If show task pane is missing because of a mistake I made and not a documentation issue, close this and I will debug my mistake on my own. I thought it was a documentation error until the buttons didn't work.

**Comment by AlexJerabek** [comment]
I'll let you debug your code :-)
When you find out the problem, please report back. It's good for us to be aware of common pitfalls so we can warn against them in the documentation.

**Comment by AlexJerabek** [comment]
Hi @user135711,

I'm assuming since I haven't heard back, you found the issue with your code. If not, or you still believe there to be a documentation issue, please reopen this and we'll dive into the problem. Thanks!

**Comment by user135711** [comment]
@AlexJerabek Yes, I have to come back to this, working on something else. I'll open a pull request if it's a doc problem.
