### ISSUE TITLE
Not able to use any Ng commands 

### ISSUE THREAD

**Issue by Viktor1356** [OfficeDev/office-js-docs-pr#3547]
[Enter feedback here]
I need to add a new component for the Add-in however if I try adding a new component, it doesn't work as it is "not available outside an angular workspace. Is there a different way to add a new component?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15f43fe5-03e0-579c-165c-57e16b1a53ea
* Version Independent ID: 15f43fe5-03e0-579c-165c-57e16b1a53ea
* Content: [Create Office Add-in projects using the Yeoman Generator - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/yeoman-generator-overview)
* Content Source: [docs/develop/yeoman-generator-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/develop/yeoman-generator-overview.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
This seems to be a problem with the one of the Angular templates in Yo Office, rather than documentation. I can move the issue to the proper repo, but first tell me if you took the TypeScript or JavaScript option. 

@igor-ribeiiro Could you take a look at this?

**Comment by igor-ribeiiro** [comment]
Yeah, our angular templates are a little outdated. There is a PR already open to fix this issue: https://github.com/OfficeDev/Office-Addin-TaskPane-Angular/pull/93

**Comment by Rick-Kirkham** [comment]
@Viktor1356 It might be some time before we can update our Angular templates. In the meantime, you might consider trying to create a Angular Office Add-in with one of the methods described in these two blog posts:

- [Building Office Add-in using Angular 8+](https://ragavanrajan.medium.com/building-office-add-in-using-angular-8-209624ba61ed)
- [Developing Office add-ins using Angular 10+ and Nrwl Nx](https://javascript.plainenglish.io/developing-office-plugins-using-angular-and-nx-5aaf4461e967)
