### ISSUE TITLE
Outlook 2016 is using WebView (EdgeHTML)

### ISSUE THREAD

**Issue by ChristianGalla** [OfficeDev/office-js-docs-pr#3551]
To reproduce an error on a customer machine, I have set up a new test environment using Windows 10 Pro and Outlook 2016 32 Bit from my Visual Studio Subscription and installed all available updates:

![image](https://user-images.githubusercontent.com/7421161/179466111-25bccc82-51c6-4d11-be73-d33ed57f8be9.png)
![image](https://user-images.githubusercontent.com/7421161/179466417-d996cf99-3bb9-4a72-ab22-c1625adcf320.png)

According to the documentation, Internet Explorer 11 should be used to render Office 2016 Add-Ins, but WebView (EdgeHTML) is used instead:

![image](https://user-images.githubusercontent.com/7421161/179469275-ef75e816-63a2-47f0-85b7-8ea1ebdc5b23.png)
![image](https://user-images.githubusercontent.com/7421161/179467694-075c071c-242d-42f4-bba5-2fdaafcc7360.png)

Is WebView (EdgeHTML) rendering rolling out to old Office versions?
Is this a bug or a new, not yet documented feature?

How can I force Outlook 2016 to use WebView or IE11, so my test environment is the same as the productive environment of the customer?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00c430f1-bbf5-53b8-a225-4fbe8fc39c3b
* Version Independent ID: 0a069a0d-4d35-71ee-53af-8c55fe8548a0
* Content: [Browsers used by Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins)
* Content Source: [docs/concepts/browsers-used-by-office-web-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/concepts/browsers-used-by-office-web-add-ins.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for raising this issue @ChristianGalla. My understanding is that anything in Office 2016 should be using IE11. 

@Rick-Kirkham, could you please investigate?

**Comment by Rick-Kirkham** [comment]
I'm going to consult some internal experts. In the meantime, can you confirm that IE11 is being used on the customer's computer?  If so, what is the Windows version/build and the Office version/build of the customer?

**Comment by Rick-Kirkham** [comment]
Also, if you open the personality menu in the task pane and select Security Info, what does it say is the webview being used?

**Comment by ChristianGalla** [comment]
Unfortunately, the personality menu [is not supported in Outlook](https://docs.microsoft.com/en-us/office/dev/add-ins/design/task-pane-add-ins#personality-menu).
But I was able to identify the used rendering engine by trying to connect via developer tools:

On my test machine I am able to connect via [Microsoft Edge DevTools Preview](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-add-ins-using-devtools-edge-legacy). I have added a screenshot of the tool in my first post.

On the customer machine I was able to debug via [Internet Explorer developer tools](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-add-ins-using-f12-tools-ie). The customer is using Outlook 2016 16.0.5197.1000 MSO 16.0.5278.1000 32Bit on the same Windows 10 version.

--

I have also tried to install Outlook 2016 on a Windows Server 2019.
![image](https://user-images.githubusercontent.com/7421161/179735407-d3dc1ef4-28bb-4d6c-8b44-d1a166d567d9.png)

In this case, Outlook fails to load the Add-In entirely:
![image](https://user-images.githubusercontent.com/7421161/179732615-2a30c171-8a68-4344-a710-8d2b43b2b358.png)

According to the Debug Output Window in Visual Studio here Outlook 2016 even tries to load WebView2:
`WebView2: Failed to find an installed WebView2 runtime or non-stable Microsoft Edge installation.`
Power BI Desktop is installed on this server. Maybe Outlook 32 Bit finds some traces of Power BI's internally used 64 Bit WebView2, but fails to load it?

**Comment by Rick-Kirkham** [comment]
So, as I understand it, your customer's computer is behaving just as the documentation would lead us to expect. The mystery is why you are getting EdgeHTML on your computer. I'm seeking help internally.

**Comment by Rick-Kirkham** [comment]
We think that the reason you are getting EdgeHTML is that your Office 2016 is the "consumer" version, but your customer has the "commercial" version. The consumer version gets updates that the commercial version doesn't get. That would explain why your build number 15330 is so much more recent than Office 2016. To confirm this, can you get the build number of your customer? 

If this turns out to be the case, then if you need to debug agains IE, you should follow the guidance in [Test with IE](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/ie-11-testing#switch-to-the-internet-explorer-11-webview).

**Comment by ChristianGalla** [comment]
How can I verify if I am using a consumer or commercial version of Outlook?
If I remember correctly, there is a hint about a forbidden commercial usage in the Home & Student version?

The customer is using Outlook 2016 16.0.5197.1000 MSO 16.0.5278.1000 32Bit and installed all available updates.

Unfortunately, `npx office-addin-dev-settings webview manifest.xml ie` is not working.
I am receiving the success message `The web view type is set to Microsoft Internet Explorer.`, but Outlook on my test vm is still using Edge legacy to render the Add-In. Maybe this is not working in Outlook 2016 or it only works when sideloading the Add-In?

On my test VM, I have uninstalled Outlook 2016 Standalone and installed Office Professional Plus 2016 from the iso file downloaded from my.visualstudio.com, but the Add-In is still rendered in Edge Legacy...

Maybe there is a difference between the MSI version available via Volume Licensing Portal and the iso version?

**Comment by Rick-Kirkham** [comment]
To get a version of Office that uses IE, I think you need to follow the steps in [Install a version of Office that uses Internet Explorer](https://docs.microsoft.com/office/dev/add-ins/testing/ie-11-testing#install-a-version-of-office-that-uses-internet-explorer). Specify that you want to install version 16.0.10730.20348.

**Comment by Rick-Kirkham** [comment]
@ChristianGalla To find out how the user can tell if he/she is on commercial or consumer, let's see if there's a difference in the **Account** page. Have your customer open the **File** tab on the ribbon. On the **File** page, there should be an **Account** or **Office Account** option. Have the customer select that option and take a screen shot of what they see on the page that opens. If there's an About Office button on the page, they should click that and take a screenshot of the popup that opens. Have them send you both screen shots. Then do the same thing on your computer. Add the 4 screenshots to this discussion and we'll see if we can find something that marks the difference between commercial and consumer.

**Comment by Rick-Kirkham** [comment]
@ChristianGalla I've found out how to tell the difference between consumer and commercial. If the Office 2016 build number has the pattern **16.0.xxxx.xxxx** (with two blocks of 4 digits at the end), then it is commercial. If the build number has the pattern **YYMM (xxxxx.xxxxxx)**, ending with two blocks of 5 digits, e.g., 2206 (Build 15330.20264); then it is consumer.

If you don't have a way of installing a commercial version of Office 2016, then you will need to follow the steps in the section that I linked to earlier to force the machine you are debugging/testing on to use IE.

**Comment by ChristianGalla** [comment]
> To get a version of Office that uses IE, I think you need to follow the steps in [Install a version of Office that uses Internet Explorer](https://docs.microsoft.com/office/dev/add-ins/testing/ie-11-testing#install-a-version-of-office-that-uses-internet-explorer). Specify that you want to install version 16.0.10730.20348.

Unfortunately, the [Office Deployment Tool does not support Outlook 2016](https://docs.microsoft.com/en-us/office365/troubleshoot/installation/product-ids-supported-office-deployment-click-to-run).
Because there may be other differences between the Outlook versions beside the browser engine, this cannot be used to develop or test if an Add-In is running in Outlook 2016 in IE mode.

**Comment by ChristianGalla** [comment]
> I am updating our article about the browsers used to account for this difference.

The list currently only contains Windows client versions. Can you also add the information, which browser is used when a Windows server version is used?
