### ISSUE TITLE
license

### ISSUE THREAD

**Issue by ukv001** [OfficeDev/office-js-docs-pr#3553]
[Enter feedback here]
Hej,

I am looking for the license for this, as the first thing always before starting to read about the capabilities. But I can not find where the license is written anywhere ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdac492e-7568-9c6a-4ac4-1b0e48898141
* Version Independent ID: 8d1c8f9e-1256-8aa5-2b71-284f7b2ec906
* Content: [Excel JavaScript API overview - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/overview/excel-add-ins-reference-overview?view=excel-js-preview)
* Content Source: [docs/reference/overview/excel-add-ins-reference-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/reference/overview/excel-add-ins-reference-overview.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @ukv001,

Our license, the Microsoft Developer Agreement, can be found here: https://docs.microsoft.com/en-us/legal/mdsa

Is that what you're looking for?

**Comment by ukv001** [comment]
if this is the license agreement for using this component in production environment then yes :-) thanks.

**Comment by ukv001** [comment]
But this specific repo have a different license ?
https://github.com/OfficeDev/office-js-docs-pr/blob/main/LICENSE
