### ISSUE TITLE
outlook add-in: An execute function action was defined, but no function file was specified 

### ISSUE THREAD

**Issue by JanTrichter** [OfficeDev/office-js-docs-pr#3565]
## Article URL
[Tutorial: Build a message compose Outlook add-in](https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/outlook-tutorial)

## Issue
I was trying to reinstall the outlook add-in after adding the new markup to the `manifest.xml` ([This step](https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/outlook-tutorial#reinstall-the-add-in)). It wouldn't show the update so I manually removed the add-in and reinstall it with `npm start`. The server starts without issues and I'm prompted to sideload the add-in when I open Outlook. But nothing happen after that. So I tried to install it manually in the web and desktop app. 

When I did this I got the error `An execute function action was defined, but no function file was specified`. 

How can I fix this? I was just following the tutorial and now I have this error.

**Comment by ElizabethSamuel-MSFT** [comment]
@JanTrichter Thanks for letting us know.

@samantharamon Can you take a look?

Thanks.

**Comment by JanTrichter** [comment]
> Hi @JanTrichter,
> 
> 
> 
> Thanks for reaching out. We're sorry to hear that you've run into an error while trying out the Outlook tutorial. I attempted to replicate the issue you're running into, but I'm not able to reproduce it. When you get a chance, could you try [validating your manifest](https://docs.microsoft.com/office/dev/add-ins/testing/troubleshoot-manifest) by running `npm run validate`? This will report any issues with the manifest that will help us troubleshoot this further. Please let us know what results you get.

No error there. I will try to replicate this error again soon.

**Comment by samantharamon** [comment]
Thanks, @JanTrichter. If you still get the error when you try it again, if possible, please provide a copy of your manifest here.
