### ISSUE TITLE
Mention @types/office-js, too

### ISSUE THREAD

**Issue by Zlatkovsky** [OfficeDev/office-js-docs-pr#357]
It would be good to mention on this article that in addition to the CDN JS location, developers can find IntelliSense by doing `npm install --save-dev @types/office-js`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d96e111-017c-a77b-9326-f64e83936921
* Version Independent ID: 5ab2ade4-18c5-ebe1-18d4-abff3d4059df
* Content: [Referencing the JavaScript API for Office library from its content delivery network (CDN)](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/referencing-the-javascript-api-for-office-library-from-its-cdn#feedback)
* Content Source: [docs/develop/referencing-the-javascript-api-for-office-library-from-its-cdn.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/referencing-the-javascript-api-for-office-library-from-its-cdn.md)
* Product: **office 365**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by lindalu-MSFT** [comment]
@Zlatkovsky Do you want to make that change and open a PR to merge it, or do you want one of our writers to do it? @ElizabethSamuel-MSFT

**Comment by Zlatkovsky** [comment]
I'll let one of the dev writers do it :-).  I just noticed it when perusing the docs, so figured I'd try out the "send feedback" button and let you know that it would be a good thing to add.

**Comment by lindalu-MSFT** [comment]
OK, I added them all as assignees.

**Comment by Rick-Kirkham** [comment]
Added note to this effect: https://github.com/OfficeDev/office-js-docs-pr/pull/366

**Comment by AlexJerabek** [comment]
@Zlatkovsky, It appears @Rick-Kirkham added the requested information and that change has gone live. Closing the issue.
