### ISSUE TITLE
Internet headers quota clarification for Outlook Add-In

### ISSUE THREAD

**Issue by jlara005** [OfficeDev/office-js-docs-pr#3580]
We currently have an Outlook Add-in in development and are looking to set [headers ](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/internet-headers)on outgoing emails. Can we get clarity if the quota is based on headers applied to items, therefore every header on every item count towards the quota or is it each unique header registered to the mailbox counts towards the quota? 

If someone could respond to this issue with some more information that would be really appreciated.

Thanks!

**Comment by AlexJerabek** [comment]
Thanks for raising this issue @jlara005.

@samantharamon, could you please investigate?

**Comment by samantharamon** [comment]
Hi, @jlara005. That's a great question. I'm confirming this information with our internal team. I will provide you with an update once I hear back. Thanks!

**Comment by samantharamon** [comment]
Thanks for your patience, @jlara005. I've verified that the quota is based on the total size of headers applied to a message (for more information, see [Message Limits](https://docs.microsoft.com/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#message-limits)). Per the article, the current message header size limit is 256 KB in Exchange Online. The limit for on-premises Exchange environments will depend on the number set by the admin (see [Message size and recipient limits in Exchange Server](https://docs.microsoft.com/exchange/mail-flow/message-size-limits?view=exchserver-2019#types-of-message-size-limits)).

We'll be updating [Get and set internet headers on a message in an Outlook add-in](https://docs.microsoft.com/office/dev/add-ins/outlook/internet-headers) with this information.
