### ISSUE TITLE
args.visibilityMode = "Taskpane"

### ISSUE THREAD

**Issue by chenxizhang** [OfficeDev/office-js-docs-pr#3591]
[Enter feedback here]
The code below should be 

args.visibilityMode == "Taskpane"

```args.visibilityMode = "Taskpane" ```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f28cc49b-7eb3-ce5b-eabc-023134ed411b
* Version Independent ID: f953561c-3aab-c8d0-7f0f-0aa008990f94
* Content: [Show or hide the task pane of your Office Add-in - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/show-hide-add-in)
* Content Source: [docs/develop/show-hide-add-in.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/develop/show-hide-add-in.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for catching this @chenxizhang. I'll update the code snippets accordingly.
