### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by simplestylesun** [OfficeDev/office-js-docs-pr#3601]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 193780ba-aa43-dc5c-fc28-adc96a0fdeda
* Version Independent ID: da41da2b-207e-e976-3491-61672d1e3493
* Content: [Configure your Outlook add-in for event-based activation - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/autolaunch)
* Content Source: [docs/outlook/autolaunch.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/outlook/autolaunch.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @simplestylesun,

Could you please provide more details about how your installation failed? What step in the article were you on? What event are you trying to use? What version and platform of Outlook do you have?
