### ISSUE TITLE
Sample fails with 401 errors due to incorrect ida:Audience value

### ISSUE THREAD

**Issue by ChrisGrove** [OfficeDev/office-js-docs-pr#3602]
Hi,
I have been working, through the sample and after considerable troubleshooting including decoding the JWT token. I have found that unless the ida:Audience value in the Web.config file was set to the Application ID URI set up in Azure that the controller Authorize would fail due to the Token validation looking for the incorrect audience value. The sample says that you should only enter the GUID at this points and not the full URI, which is incorrect.

Also in the Configure the solution section, in items 3 and 4 both of the urls are http and not https.

Kind regards
Chris

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93c00914-b10b-632d-83a9-31a92b480312
* Version Independent ID: 420a6dfe-d17e-1e32-f25b-e6a0daac2101
* Content: [Create an ASP.NET Office Add-in that uses single sign-on - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/create-sso-office-add-ins-aspnet)
* Content Source: [docs/develop/create-sso-office-add-ins-aspnet.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/develop/create-sso-office-add-ins-aspnet.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by davidchesnut** [comment]
Hi @ChrisGrove are you having to specify the full format, like "api://localhost:44355/c6c1f32b-5e55-4997-881a-753cc1d563b7" or do you also have to specify the "access_as_user" scope at the end of that?

I'm checking with the identity folks as I've never seen this behavior. Thanks for lettings us know about this!

**Comment by ChrisGrove** [comment]
Hi David,
              It was just the full format without the scope.

Kind regards
Chris


Mr Chris Grove MCSD (SharePoint), MCP (He/Him) |  Software Developer

+44 (0) 1323 452334<tel:+44%20(0)%201323%20452334>
***@***.******@***.***>
Old Wish Road, Eastbourne, East Sussex, BN21 4JX        [https://webmail.eastbourne-college.co.uk/owa/auth/ECbanner/main-logo.png] <https://youtu.be/J21ASgFnfq4>

[https://webmail.eastbourne-college.co.uk/owa/auth/ECbanner/barEC.jpg]<http://www.eastbourne-college.co.uk>
        [https://webmail.eastbourne-college.co.uk/owa/auth/ECbanner/Fb.jpg] <https://www.facebook.com/EastbourneCollege>
        <https://twitter.com/EBCollegeLife>
        [https://webmail.eastbourne-college.co.uk/owa/auth/ECbanner/Instagram.jpg] <https://instagram.com/eastbournecollege/>
        [https://webmail.eastbourne-college.co.uk/owa/auth/ECbanner/youtube.jpg] <https://www.youtube.com/channel/UC3h1AoprsNXv1VGa59fjokw>
        [https://webmail.eastbourne-college.co.uk/owa/auth/ECbanner/Linkedin.jpg] <https://www.linkedin.com/school/eastbourne-college>


<https://www.eastbourne-college.co.uk/admissions/getting-to-know-us/><https://www.eastbourne-college.co.uk/admissions/getting-to-know-us/>[https://webmail.eastbourne-college.co.uk/owa/auth/ecbanner/22sep.png]<https://www.eastbourne-college.co.uk/admissions/getting-to-know-us/>
<https://eastbourniansociety.org/pages/events/2022/circus>

**Comment by davidchesnut** [comment]
Hi @ChrisGrove, Can you check your app registration for the following?
1. Select the manifest view from the left side when viewing the app registration in the Azure portal.
2. Look for `accessTokenAcceptedVersion`. It must be set to 2. If not, change it to 2.

This can happen if you configured the registration type as "Accounts in any organizational directory (Any Azure AD directory - Multitenant)"

Thanks!

**Comment by ChrisGrove** [comment]
Hi @davidchesnut 

I checked my manifest and the values is null. For reference at this point [Register the add-in through an app registration](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/develop/create-sso-office-add-ins-aspnet.md#register-the-add-in-through-an-app-registration), I chose 'Accounts only in this organizational directory' and then followed the relevant later steps to replace the common part of the authority url with the Tenant Id. I wonder if this is why I have ended up with a null value?

I hope this helps.

![image](https://user-images.githubusercontent.com/25799273/189598564-9401686f-37a5-4b0b-a74f-cef5a8a74889.png)

![image](https://user-images.githubusercontent.com/25799273/189599104-328fd705-06c9-4fbd-8611-709fd8347ff8.png)

**Comment by davidchesnut** [comment]
Yep, it needs to be "accessTokenAcceptedVersion": 2, did you try that value? Thanks!

**Comment by davidchesnut** [comment]
I added how to check the access token version in the docs at:
- [Node.js SSO walkthrough](https://learn.microsoft.com/office/dev/add-ins/develop/create-sso-office-add-ins-nodejs#configure-access-token-version)
- [ASP.NET SSO walkthrough](https://learn.microsoft.com/office/dev/add-ins/develop/create-sso-office-add-ins-aspnet#configure-access-token-version)
