### ISSUE TITLE
Summer 2022??

### ISSUE THREAD

**Issue by JimbobTheSailor** [OfficeDev/office-js-docs-pr#3604]
Please do not use Northern Hemisphere references "Summer 2022", just because it is your summer does not make it our summer. We are in winter. Use proper calendar dates, "June 2022"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a18f55e3-bc76-a75f-8e0a-c64e342e91e0
* Version Independent ID: e47dd6b7-f6fa-9c01-91fd-a52febd04fb4
* Content: [Set up your development environment - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/overview/set-up-your-dev-environment?tabs=yeomangenerator)
* Content Source: [docs/overview/set-up-your-dev-environment.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/overview/set-up-your-dev-environment.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
I have searched that article for "Summer" and got no hits. Could you tell me exactly where on that page you are seeing "Summer 2022"?

**Comment by JimbobTheSailor** [comment]
Hi Rick, thanks for reaching back to me.

The words "Summer 2022" is in the first tab on the page that can be
selected titled "Select the tab for the environment you choose". There are
two tabs "Node.js Environment" and "Visual Studio Environment"

Click the "Visual Studio Environment" and you will see it in the green
highlighted 'Tip", as pasted below

 Tip

As of summer 2022, the XML schemas for the Office Add-in manifest that are
installed with Visual Studio aren't the latest version. This may affect
add-ins, depending on what add-in features they use. So, you may need to
update the XML schemas for the manifest. For more information, see Manifest
schema validation errors in Visual Studio projects
<https://docs.microsoft.com/en-us/office/dev/add-ins/testing/troubleshoot-development-errors#manifest-schema-validation-errors-in-visual-studio-projects>
.
