### ISSUE TITLE
Conflicts and questions about Shared Runtime ( Browser Runtime Type) 

### ISSUE THREAD

**Issue by YasharHeydari** [OfficeDev/office-js-docs-pr#3605]
[Enter feedback here]
Hello, 
     In both Javascript only and Browser Runtime types it's mentioned that Local Storage is supported but in a note is specified that Local Storage won't work in JS Only Runtime. I don't have access to Local Storage in JS Only Runtime and the 1st question is:
    1- Is there any way to share data or use some sort of storage like Local Storage in JS Only Runtime?

    2- In Excel, using shared runtime which is the preferred and suggested runtime, how is the session management done? I expected the session to be shared and things like UNDO Stack won't be cleared! Can you explain a little bit more about the session management and how is it affecting something like UNDO stack if this is the case?! 
   
Thankyou

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73db650a-1e4d-3488-a5b0-3950366a789f
* Version Independent ID: 73db650a-1e4d-3488-a5b0-3950366a789f
* Content: [Runtimes in Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/runtimes?cid=kerryherger)
* Content Source: [docs/testing/runtimes.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/testing/runtimes.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
I am researching your first question, but I suspect that LocalStorage is not supported by the JS-only runtime. Either way, I will clarify the documentation to remove the contradiction. 

Regarding your second question, a shared runtime has a single session with the web app server. I'm not clear on what you mean by the UNDO stack. Could you elaborate?

**Comment by Rick-Kirkham** [comment]
Thanks. Your second issue is being tracked on this issue: [Undo unavailable after running custom functions in Excel](https://github.com/OfficeDev/office-js/issues/2543). It had mistakenly been tagged as inactive. I have fixed the tag and sent an email to the engineer who is working on it. 

I'm still waiting to hear from the engineers about your first question.

**Comment by YasharHeydari** [comment]
Thanks for the update, 
     regarding this [thread ](https://github.com/OfficeDev/office-js/issues/2543) you mentioned, I've seen that and I have shared my videos on that but generally there is a difference between Shared Runtime and JS only Runtime behavior regarding UNDO stack! The repo mentioned in that thread is JS Only Runtime and I don't see such an issue unless I open the Task Pane, but in Shared Runtime every Custom Function Run will cause the UNDO Stack to clear, that's why I'm trying to understand the session management in shared runtime and its relation with UNDO stack.
