### ISSUE TITLE
Creating working navigation links for a tab bar in the taskpane

### ISSUE THREAD

**Issue by jjaronik** [OfficeDev/office-js-docs-pr#3606]
Summary: I've been digging around for a clear answer to this but haven't found anything explicit and all in one place yet. Does a clear explanation exist for what files (e.g., manifest.xml)/code needs to be changed to create links to other .html files from a nav bar within the taskpane? I've been trying to find sample code, but most samples I've found don't include multiple views.

https://docs.microsoft.com/en-us/office/dev/add-ins/design/navigation-patterns

Issue: I created a navigation tab bar in my add in that should allow the user to navigate to other views (.html files) and capabilities but am having trouble figuring out what I need to do to the manifest.xml file so the links work. I get the "Cannot GET /name.html" error when clicking on the navigation links currently. I found an answer at one point that said it should be as easy as any web app, but having the manifest.xml file complicates linking html files, right?

**Comment by Rick-Kirkham** [comment]
If you open the add-ins home page in an ordinary browser window, do the links to other html files work?

**Comment by jjaronik** [comment]
If I open the taskpane.html file in a browser window running on localhost:3000, that file works but the the link to the new html file doesn't.
If I go straight to the new html file from localhost:3000, the server doesn't recognize that the file exists. (i.e., https://localhost:3000/name.html) I get: "Cannot GET /name.html"
I added it in the <AppDomain> element (as below) and re-uploaded the manifest, but the link doesn't work sideloaded or in a browser window.
  <AppDomains>
    <AppDomain>https://localhost:3000/name.html</AppDomain>
  </AppDomains>

commands.html was included by the generator and does work as a link however. It's not referenced in <AppDomain>. It's referenced in the <VersionOverrides> element of the manifest (as is the taskpane.html file), so I thought maybe that had something to do with why the commands and taskpane files work but any new html files don't, but maybe it's just an issue with localhost:3000?

**Comment by Rick-Kirkham** [comment]
So the pages that don't open are in the same domain as your home page. In that case, you don't need to add anything to the `<AppDomands>`. The add-in's domain is always trusted. 

These links that don't work are anchor (`<a> ...</a>`) links, right? 

Based on your symptoms, I think that https://localhost:3000/name.html is not the correct URL for the name.html file. could you provide your propects folder structure? 

Also, how was this project created? With Yo Office? Are you using Webpack?

**Comment by jjaronik** [comment]
Hi! Sorry for the delay in getting back to you on this. I did some more trouble shooting and realized I had to add the new html file to webpack.config.js as a new HtmlWebpackPlugin. You pointed me in the right direction once I realized the issue had to do with the file not running properly on my localhost and when you mentioned Webpack, so thank you!

**Comment by AlexJerabek** [comment]
Reopening since the bot closed this issue.

Glad to hear your project is working @jjaronik. Is there anything more you need on this issue?

**Comment by jjaronik** [comment]
That's all for now. Thanks!
