### ISSUE TITLE
Should I use onReady or initialize

### ISSUE THREAD

**Issue by moshikonachmias** [OfficeDev/office-js-docs-pr#3612]
You used Office.initialize in your example, but you recommended using Office.onReady() in the following document:
https://docs.microsoft.com/en-us/office/dev/add-ins/develop/initialize-add-in

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a59958d2-f428-9ca2-3440-a5af662386c0
* Version Independent ID: dcaf0b5b-08ea-c437-130b-342a1be62a16
* Content: [Tutorial: Build a message compose Outlook add-in - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/outlook-tutorial#feedback)
* Content Source: [docs/tutorials/outlook-tutorial.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/tutorials/outlook-tutorial.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @moshikonachmias,

Thanks for pointing out this discrepancy. @samantharamon, could you please investigate?

**Comment by samantharamon** [comment]
Thanks for reporting this, @moshikonachmias. Please follow the guidance in the document you linked ([Initialize your Office Add-in](https://docs.microsoft.com/office/dev/add-ins/develop/initialize-add-in)). We'll update the Outlook tutorial for consistency.
