### ISSUE TITLE
The default project type(Office Add-in Task Pane project) doesn't work

### ISSUE THREAD

**Issue by martibook** [OfficeDev/office-js-docs-pr#3624]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50a89144-ac19-b28e-2842-5e2cbdb1cb00
* Version Independent ID: cb59df19-9c22-de2c-0c46-7a1403312987
* Content: [Build your first PowerPoint task pane add-in - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/powerpoint-quickstart?tabs=yeomangenerator)
* Content Source: [docs/quickstarts/powerpoint-quickstart.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/quickstarts/powerpoint-quickstart.md)
* Product: **powerpoint**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @martibook,

Thanks for reporting this. I believe I encountered the same errors while running yo office that you did. For completeness, could you please share the errors you received?

```
No change to package.json was detected. No package manager install will be executed.
npm WARN config cache-min This option has been deprecated in favor of `--prefer-offline`.
npm ERR! code ETARGET
npm ERR! notarget No matching version found for typescript@^4.7.4.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\aljerabe\AppData\Local\npm-cache\_logs\2022-09-06T16_40_05_450Z-debug-0.log
```

That said, I was able to get the project working by running `npm install` in the project folder. Does that step unblock you?

**Comment by AlexJerabek** [comment]
Also tagging @igor-ribeiiro for awareness.

**Comment by martibook** [comment]
This is what I choose when creating Add-in project
![image](https://user-images.githubusercontent.com/20094820/188776858-1722f544-8c2d-4166-8a37-45b770a95e45.png)

I run "npm start" without running "npm install" first
![image](https://user-images.githubusercontent.com/20094820/188776995-12910717-ae14-4b9e-b1c0-1c6ddc2ce7f7.png)

Then I immediately run "npm install" and then "npm start" again
![image](https://user-images.githubusercontent.com/20094820/188777153-374cec0b-c82e-4803-b80d-a3507539ab1a.png)

So "npm install" doesn't solve my problem.
And I try other project type, it works.

**Comment by alison-mk** [comment]
Hi @martibook, I encountered the same error as you yesterday while using yo office to set up an add-in (in my case, I was creating an Office Add-in Task Pane with TypeScript, for Excel). Sorry you're having trouble, too! 

I was able to resolve the error by updating my node version, which also updated my npm version. I'm now using: node v16.17.0 and npm v8.15.0. Which versions of node and npm are you using? 

Our yo office projects support the latest LTS version of node (currently node v16), so if you're using a previous version please try updating node and npm, and then running yo office again. 

Thanks, 
Alison

**Comment by davidchesnut** [comment]
You could also try "npm cache clean --force" in case maybe the npm cache has something corrupted in it.
