### ISSUE TITLE
Is it possible to use SVG icons instead of PNG?

### ISSUE THREAD

**Issue by wh1t3cAt1k** [OfficeDev/office-js-docs-pr#3648]
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 994c840a-5e2b-1ae6-3031-ac1b7ac4f5e4
* Version Independent ID: b25f2f7c-1620-35f1-9fc6-b4c08fe87538
* Content: [Create custom contextual tabs in Office Add-ins - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/design/contextual-tabs)
* Content Source: [docs/design/contextual-tabs.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/design/contextual-tabs.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
I'm sorry but SVG icons are not supported. Icons must be GIF, JPG, PNG, EXIF, BMP, or TIFF. Office requires icons to be be rasters of pixels so that they have a clearly defined height, width, and aspect ratio.
