### ISSUE TITLE
PowerPoint is not mentioned in the `.run` documentation

### ISSUE THREAD

**Issue by DominikPalo** [OfficeDev/office-js-docs-pr#3650]
The ***.run function** paragraph mentions only Excel, Word, and OneNote (`Excel.run`, `Word.run,` and `OneNote.run`). I think PowerPoint (`PowerPoint.run`) should also be included there, as PowerPoint supports JS API.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 39717544-9615-86da-c52a-d73a9d295218
* Version Independent ID: 9f33ee54-fe06-d131-7205-3a28ba4f1e2d
* Content: [Using the application-specific API model - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/application-specific-api-model)
* Content Source: [docs/develop/application-specific-api-model.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/develop/application-specific-api-model.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
You are correct. I will update that article.
