### ISSUE TITLE
Please "yo office" version

### ISSUE THREAD

**Issue by ivose** [OfficeDev/office-js-docs-pr#3654]
## Article URL

https://learn.microsoft.com/en-us/office/dev/add-ins/tutorials/powerpoint-tutorial

## Issue

Maybe you can write how to do the same example with 'yo office' command. Using Visual Studio (instead of vs code), requires too much memory - 7 GB.

**Comment by AlexJerabek** [comment]
Hi @ivose,

That's a valid point that most of the other tutorial have options other than Visual Studio. @Rick-Kirkham, could you please investigate and see what it would take to retool the PowerPoint tutorial?

**Comment by Rick-Kirkham** [comment]
@ivose We have a work item to change the PowerPoint tutorial from one that uses the Common APIs to one that uses the PowerPoint-specific APIs. I think we can merge your request into that work item.

**Comment by ElizabethSamuel-MSFT** [comment]
@ivose Thanks for your interest in Office Add-ins! A yo office version of the tutorial is now also available at the same link.

Let us know your feedback about it or if you face any further issues.

Thanks.
