### ISSUE TITLE
Hello World more prominent in Office-Addin documentation.

### ISSUE THREAD

**Issue by kasperkamperman** [OfficeDev/office-js-docs-pr#3677]
I think that the Hello World examples should have a more prominent place on the Office-Addin page (Beginners Guide, or Quick starts).  

Thanks to this tutorial (https://www.youtube.com/watch?v=tLGs9xChvXY) of David Chesnut and this page, I learned that Office Add-ins are actually just an XML manifest with a webpage. 

On the quickstarts the focus lies too much on tooling. Like the Beginners guide mentions tooling in Step 2. While it's perfectly possible, like David shows, to create a barebones add-in with on compiling or what ever. 

Getting this information earlier on, would have helped me better to understand the structure. And it would help me to see, I can easily create an add-in with, in my scenario, Svelte, something that's not promoted right now. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 56ebcaf3-ab12-f487-7771-402358836379
* Version Independent ID: 0ba17d6d-c2be-134c-f404-44e809fc9e04
* Content: [Office Add-in code samples - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/overview/office-add-in-code-samples)
* Content Source: [docs/overview/office-add-in-code-samples.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/overview/office-add-in-code-samples.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by davidchesnut** [comment]
Thanks @kasperkamperman, I added some more mentions of hello world to the docs in this PR:  #3734

Hope this helps,
David
