### ISSUE TITLE
outdated samples

### ISSUE THREAD

**Issue by davidboss4u** [OfficeDev/office-js-docs-pr#3705]
I need Word or Excel taskpane sample
The video is very nice, but when following it, nothing works
Word samples are very old, almost all are "Public archive"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0ddce0bd-5c66-c2cb-0640-ee4d5bd401c5
* Version Independent ID: b5d4bc26-a43e-4a85-e7d5-fe4fc4ec3d0d
* Content: [Sideload Office Add-ins for testing from a network share - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins)
* Content Source: [docs/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
We need more details than just "nothing works". What goes wrong? What do you expect to see and what do you actually see? 
Also, please note that this article is about sideloading. It is not about providing sample add-ins.
