### ISSUE TITLE
Auth0 Integration

### ISSUE THREAD

**Issue by BryantDavis1986** [OfficeDev/office-js-docs-pr#3715]
The Github Repository example provided for Auth0 seems to have been archived and does not reflect what an app looks like when generated by the yo command. Unable to really understand this flow or how to properly provide support for auth0 integration using the React implementation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a714626a-058a-789e-6add-5e9dfb21fd1f
* Version Independent ID: 1b88a28c-fc36-4518-2808-7246f08d9753
* Content: [Use the Office dialog API in your Office Add-ins - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins#use-the-dialog-apis-in-an-authentication-flow)
* Content Source: [docs/develop/dialog-api-in-office-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/develop/dialog-api-in-office-add-ins.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by davidchesnut** [comment]
Hi @BryantDavis1986,

Unfortunately we don't maintain the auth0 sample anymore (thus archived). The most important part of the sample is that you need to use the Office dialog API to open the authentication dialog. See this [section of code](https://github.com/OfficeDev/Office-Add-in-Auth0/blob/3e8dfc424cb4e424b1862dfe6fab5b5d98eedbf4/Scripts/index.js#L69) Other than that you should be able to rely on the Auth0 docs and SDK. For example, in the [Auth0 React] quickstart(https://auth0.com/docs/quickstart/spa/react/interactive), where the login occurs is where you want to be sure to use the Office dialog for the login dialog and not the task pane. There may be some steps from the readme that still apply such as [setting up redirects for your popup dialog](https://github.com/OfficeDev/Office-Add-in-Auth0#create-an-auth0-account-and-configure-it-to-use-google-facebook-and-microsoft-account).

Hope this helps,
David

**Comment by BryantDavis1986** [comment]
> Hi @BryantDavis1986,
> 
> Unfortunately we don't maintain the auth0 sample anymore (thus archived). The most important part of the sample is that you need to use the Office dialog API to open the authentication dialog. See this [section of code](https://github.com/OfficeDev/Office-Add-in-Auth0/blob/3e8dfc424cb4e424b1862dfe6fab5b5d98eedbf4/Scripts/index.js#L69) Other than that you should be able to rely on the Auth0 docs and SDK. For example, in the [Auth0 React] quickstart(https://auth0.com/docs/quickstart/spa/react/interactive), where the login occurs is where you want to be sure to use the Office dialog for the login dialog and not the task pane. There may be some steps from the readme that still apply such as [setting up redirects for your popup dialog](https://github.com/OfficeDev/Office-Add-in-Auth0#create-an-auth0-account-and-configure-it-to-use-google-facebook-and-microsoft-account).
> 
> Hope this helps, David

Good Afternoon,
      Thank you for the quick reply @davidchesnut . So in this instance would I be using React routing to render a popup Component instead of pointing it to a raw static html file? Which inside the dialogue component I would then render or use the Auth0 React hooks?

**Comment by davidchesnut** [comment]
Hi @BryantDavis1986, For complete details on how the Office dialog API works, see https://learn.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins 

As long as the React router is returning the expected URL that you put in (such as `Office.context.ui.displayDialogAsync('https://myDomain/myDialog.html', {height: 30, width: 20});`) then that HTML page will be launched. The page is loaded in a separate browser instance, so you need to call `Office.context.ui.messageParent` to send data (presumably the access token) back to the task pane.

Cheers,
David
