### ISSUE TITLE
Missing warning for usage of the Office.Context at root level of launchevent.js

### ISSUE THREAD

**Issue by bogdanst24** [OfficeDev/office-js-docs-pr#3722]
The documentation for event-based activation in the Outlook add-in is not complete. 

## Article URL

https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/autolaunch?tabs=xmlmanifest#implement-event-handling

## Issue

When accessing the Office.Context at the root level in the launchevent.js, running the add-in in Outlook for Desktop will fail at load time. This requirement/limitation is not specified in the documentation.
Please consider adding it near the actual warning regarding the imports not being supported.

> Windows: At present, imports aren't supported in the JavaScript file where you implement the handling for event-based activation.

**Comment by AlexJerabek** [comment]
Thanks for reporting this @bogdanst24.

@samantharamon, could you please investigate?

**Comment by samantharamon** [comment]
Hi @bogdanst24,

Thank you for the feedback. Suggestions to improve our documentation are always welcome. :)

Would you mind sharing your scenario and the code you used to access Office.context at the root level? Was it via `Office.onReady()` or `Office.initialize` by any chance?

**Comment by bogdanst24** [comment]
`
void Office.onReady(() => {});

Office.actions.associate('onMessageComposeHandler', ......);
Office.actions.associate(
 'onMessageRecipientsChanged',
  (event: Office.AddinCommands.Event) =>
    void onMessageRecipientsChanged(event, insertionOptions)
);`

**Comment by bogdanst24** [comment]
As a short example, this fails on Outlook desktop.

`
void Office.onReady(() => {});

const support = Office.context.requirements.isSetSupported('Mailbox', '1.11');
console.log(support);

Office.actions.associate('onMessageComposeHandler', ......);
Office.actions.associate('onMessageRecipientsChanged', .....);

`

**Comment by samantharamon** [comment]
Thank for providing a code sample, @bogdanst24. I'll update our documentation to note this. I also verified with the team that event-based add-ins in Outlook on Windows don't run the `Office.onReady` and `Office.initialize` functions. Any code that you would normally run here, such as checking for a supported requirement set, should be called within the event handler instead. If you call these functions in your code, your add-in will still load and run, but the code in these functions will not run.

**Comment by samantharamon** [comment]
@bogdanst24, we made the necessary changes based on the feedback you provided (see #3737). Once the changes are merged, this issue will automatically close. Should you have additional feedback, please don't hesitate to re-open this issue. Thank you.
