### ISSUE TITLE
How to create a content add-in using Office.js

### ISSUE THREAD

**Issue by marindedic** [OfficeDev/office-js-docs-pr#3725]
I have read the content add-in docs (https://learn.microsoft.com/en-us/office/dev/add-ins/design/content-add-ins), it has the implementations section. However, the mentioned implementation is 6 years old and doesn't use todays principles. Im looking just for a "hello world" type example or resource that can guide me.

**Comment by Realman78** [comment]
> Thanks for the sample request @marindedic. We should offer a "hello world" style sample for this, akin to how we're doing the [taskpane add-in hello worlds](https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/hello-world/excel-hello-world). That said, the nature of content add-ins themselves has not changed over this time, so there's not any "missing" information, so to speak.
> 
> 
> 
> I'll create an internal work item to make this new sample.  Out of curiosity, what is the scenario you're trying to achieve with your add-in?

Thanks for the reply. It is still in R&D stage where we don't know EXACTLY what to do with a content add-in, but we need to know if it's possible. For example, select a few cells and create a new sheet using those cells as input.

**Comment by marindedic** [comment]
> Thanks for the sample request @marindedic. We should offer a "hello world" style sample for this, akin to how we're doing the [taskpane add-in hello worlds](https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/hello-world/excel-hello-world). That said, the nature of content add-ins themselves has not changed over this time, so there's not any "missing" information, so to speak.
> 
> I'll create an internal work item to make this new sample. Out of curiosity, what is the scenario you're trying to achieve with your add-in?

Thanks for the reply. It is still in R&D stage where we don't know EXACTLY what to do with a content add-in, but we need to know if it's possible. For example, select a few cells and create a new sheet using those cells as input.

**Comment by marindedic** [comment]
Since creating a Content add-in has the same principle as creating a TaskPane add-in, this issue could be closed by listing the minor differences in the manifest xml file. 

- Change `xsi:type="TaskPaneApp"` to `xsi:type="ContentApp"` 
- Add width and height: `<DefaultSettings>
    <SourceLocation DefaultValue="https://localhost:3000/taskpane.html"/>
    <RequestedWidth>1000</RequestedWidth>
    <RequestedHeight>700</RequestedHeight>
  </DefaultSettings>`

**Comment by AlexJerabek** [comment]
Thanks for the suggestion to make the manifest change clearer. We'll make that update soon.

**Comment by ElizabethSamuel-MSFT** [comment]
@marindedic We recently addressed this and there are now quick starts showing how to create content add-ins through Visual Studio.

- [Excel](https://learn.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-content?tabs=basic)
- [PowerPoint](https://learn.microsoft.com/en-us/office/dev/add-ins/quickstarts/powerpoint-quickstart-content)
