### ISSUE TITLE
About the `emailAddress` property of the return value of `enhancedLocation.getAsync`

### ISSUE THREAD

**Issue by clavx** [OfficeDev/office-js-docs-pr#3733]
The `LocationDetails` interface of the return value of `enhancedLocation.getAsync` contains the `emailAddress` property and the `locationIdentifier` property.
In the sample code, the `emailAddress` property is referenced when the value of the `type` property of the `LocationIdentifier` is of type `Room`.

``` ts
if (place.locationIdentifier.type === Office.MailboxEnums.LocationType.Room) {
  console.log("Email address: " + place.emailAddress);
}
```

I understand each property as follows:

```
For Room type
  LocationIdentifier.id = LocationDetails.emailAddress
For Custom type
  LocationIdentifier.id = LocationDetails.displayName
```

I'm not sure what the role of the `emailAddress` property of `LocationDetails` is.
It appears that the `emailAddress` property is set for `Room` and not for `Custom`.
Are both the `emailAddress` and `id` properties exactly the same?
Is there a reason why the sample code references the `emailAddress` property?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8922b63d-51bd-5f4a-0c33-63e9715103c2
* Version Independent ID: 9add94e6-3658-b586-4906-3ff07dd10bf7
* Content: [Get or set the location of an appointment in an add-in - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/get-or-set-the-location-of-an-appointment)
* Content Source: [docs/outlook/get-or-set-the-location-of-an-appointment.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/outlook/get-or-set-the-location-of-an-appointment.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for the question @clavx.

@samantharamon, could you please help provide some clarity?

**Comment by samantharamon** [comment]
Thank you for reaching out, @clavx. The `emailAddress` property provides a direct option to retrieve the email address if the location's a room instead of retrieving it from the `id` property of the `LocationIdentifier` object. The sample includes a location type check and the `emailAddress` property to highlight that only `Room` type locations have an email address. You correctly pointed out that for `Room` type locations, `emailAddress` and `id` return the same value. I'll update our documentation to clarify the `emailAddress` property description.

**Comment by clavx** [comment]
Thank you for your answer.

I'm relieved that my interpretation is right.
My question has been answered.

Thank you!

**Comment by samantharamon** [comment]
No worries! I'm glad we could assist with your query. As promised, we're updating our reference documentation to clarify the `emailAddress` property description (see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63455). I will now close this issue, but should you require further assistance, please don't hesitate to open a new one.
