### ISSUE TITLE
ADD-IN ERROR - The content is blocked because it isn't signed by a valid security certificate

### ISSUE THREAD

**Issue by mohabayman-t** [OfficeDev/office-js-docs-pr#3738]
# ADD-IN ERROR - The content is blocked because it isn't signed by a valid security certificate

Description:  This error shows up when sideloading my React app into desktop Word
![image](https://user-images.githubusercontent.com/103205155/201472720-f06c8177-e28d-44af-ae4c-35e57d56598d.png)

### How to recreate the app?
```
npm install -g yo generator-office
npx yo office 

? Choose a project type: Office Add-in Task Pane project using React framework
? Choose a script type: (Use arrow keys)
? Choose a script type: JavaScript
? What do you want to name your add-in? My Office Add-in
? Which Office client application would you like to support? Word
```

### How to start the app?
either:
```
npm run start
```
or:
```
office-toolbox sideload -m manifest.xml -a Word
```

### What fixed were already tried?
- Deleting the content of folder `C:\Users\{username}\.office-addin-dev-certs` and running command `npx office-addin-dev-certs install` from  [stackoverflow](https://stackoverflow.com/questions/64818707/the-content-is-blocked-because-it-isnt-signed-by-a-valid-security-certificate-e).
- Accessing localhost:3000 then downloading and installing the certificate [stackoverflow](https://stackoverflow.com/questions/21397809/create-a-trusted-self-signed-ssl-cert-for-localhost-for-use-with-express-node).

### Note:
Already tried the answers in this [issue](https://github.com/OfficeDev/office-js-docs-pr/issues/1598).

**Comment by AlexJerabek** [comment]
Hi @mohabayman-t,

I'm sorry to hear you're having issues. To better help you, could you please answer the following questions?

1. What version of Node.js are you using?
2. What version of yo office are you using?
3. Are you having the same problems with yo office created add-ins with different frameworks (like [jQuery](https://learn.microsoft.com/en-us/office/dev/add-ins/quickstarts/word-quickstart?tabs=yeomangenerator)) or different applications (like [Excel](https://learn.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-jquery?tabs=yeomangenerator))?
