### ISSUE TITLE
Should not be installable on macOS clients

### ISSUE THREAD

**Issue by hlprmnky** [OfficeDev/office-js-docs-pr#3744]
I understand that the requirements page for the extension says "Windows 10", but the documents for debugging an add-in literally advise the following:
```
Debug on Mac

The following provides general guidance to debugging on Mac.
If you're using Visual Studio Code, debug using the [Add-in Debugger Extension for Visual Studio Code](https://learn.microsoft.com/en-us/office/dev/add-ins/testing/debug-with-vs-extension).
```
and that URL tells you to install this extension, which then launches your add-in, attaches to the running Webpack process, and _only then_ suffers a fatal error reporting that it's not supported on other than Windows 10 of at least some recent build number.

In the grand scheme of "things on which I have barked my shins trying to write an Excel Add-in this week", this one is actually fairly benign and consumed relatively little time, but if someone would update the docs to _not_ tell macOS users to just march right into a blind alley as Step 1/n, I think that would be a high return for effort on your part. Thanks!

**Comment by Rick-Kirkham** [comment]
This refers to https://learn.microsoft.com/en-us/office/dev/add-ins/testing/debug-add-ins-overview#debug-on-mac

**Comment by Rick-Kirkham** [comment]
This is fixed. Should be published late today.

**Comment by hlprmnky** [comment]
Amazing! Thank you; I realize I came in a little heated and snarky after a long day of frustrations, and I am humbly impressed to see this issue already into and out of the ticket pipeline. I look forward to another day of building cool stuff for my users with these tools you've created.

**Comment by Rick-Kirkham** [comment]
I missed the publication deadline. It will publish late tomorrow (Thursday) in the Pacific USA time zone.

**Comment by Rick-Kirkham** [comment]
I stand corrected. The fixed document is published now.
