### ISSUE TITLE
How to create a prompt that depends on the current user selection

### ISSUE THREAD

**Issue by marindedic** [OfficeDev/office-js-docs-pr#3750]
I have noticed there is no documented way of creating a prompt which lets you select a cell range, display the selected cells in the input field in it, and return the appropriate binding. The closest thing to it is the **addFromPromptAsync** method. I read the documentation: https://learn.microsoft.com/en-us/javascript/api/office/office.bindings?view=excel-js-1.9#office-office-bindings-addfrompromptasync-member(1) - but, it doesn't specify that the binding that is going to be returned is the binding to the cell selection **before** I opened the prompt (BindingType is Matrix btw). What I'm looking for is a way to create that prompt and let the user make their selection while the prompt is opened (also update the input field in the prompt appropriately). Once the user selects the desired cell range, they can press "OK" and the appropriate binding will be returned (so they can get the range selected afterwards). 
<img width="395" alt="image" src="https://user-images.githubusercontent.com/110404686/202736180-fc2e8cfb-96c8-43a5-8deb-fff60238874f.png">

**Comment by samantharamon** [comment]
Thanks for reaching out, @marindedic.

@alison-mk would you be able to assist with this?

**Comment by alison-mk** [comment]
@JuaneloJuanelo Can you help answer this question about Common API bindings from @marindedic?

**Comment by JuaneloJuanelo** [comment]
HEllo Marin, the addFromPromptAsync should give you what you need.  When called the following happens:

1. The user is prompted to select a range.
2. the user is able to select a range 
3. then the expectation is to click OK
4. Result: the binding is created in the selection made by the user.

this is consistent with other Excel range selection experiences (like binding a chart to a range)


is this not working as expected? 

FYI i created[ this snippet ](https://gist.github.com/JuaneloJuanelo/f7343bab000e969a6e29cf7e8f7068bb)to sample how to use it. Please load it in Script Lab 
In that snippet i am adding a selectionChanged event for the resulting binding, the event only gets triggered on the selected cells. (its just writing to the console when the event happens. PLease give it a try!
