### ISSUE TITLE
Global add-in settings

### ISSUE THREAD

**Issue by jkpieterse** [OfficeDev/office-js-docs-pr#3755]
I've read the page about storing settings. It appears we can only store settings in the document for which our add-in (a taskpane add-in in this case) is showing.

However, I have created a document-independent add-in, which the user may use on any document. How would I store settings which are specific to the add-in as a whole, not tied to any document?
Regards,
Jan Karel Pieterse
Excel MVP
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b683480b-a4fe-97ba-64f9-45ecfe829bf4
* Version Independent ID: a0993174-18dd-9594-9c3c-102d078e2217
* Content: [Persist add-in state and settings - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/persisting-add-in-state-and-settings#how-to-save-add-in-state-and-settings-per-document-for-content-and-task-pane-add-ins)
* Content Source: [docs/develop/persisting-add-in-state-and-settings.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/develop/persisting-add-in-state-and-settings.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
We use the Issues in this repo are used to track bugs in the documentation. We recommend that you ask programming questions lie this on StackOverflow and tag it `office-js`, so the whole community benefits from the answer.

**Comment by jkpieterse** [comment]
Fair enough, will do that next time! 

On November 22, 2022 8:23:44 PM GMT+01:00, Rick Kirkham ***@***.***> wrote:
>We use the Issues in this repo are used to track bugs in the documentation. We recommend that you ask programming questions lie this on StackOverflow and tag it `office-js`, so the whole community benefits from the answer.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/OfficeDev/office-js-docs-pr/issues/3755#issuecomment-1324140286
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
Regards, Groetjes,
Jan Karel Pieterse
