### ISSUE TITLE
It does now work

### ISSUE THREAD

**Issue by LionyxML** [OfficeDev/office-js-docs-pr#3756]
I might be doing something REALLY wrong, because I can`t manage to get a variable shared between functions.js and my taskpane (that is actually a React App).

They really look like two separated window environments.

I followed this tutorial from scratch in a separated project (Under Excel for macOS). And no magic makes it works.

OfficeRuntime.storage works tought.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3a1bb1ec-f7c0-61c7-bd50-4018a2726e3a
* Version Independent ID: dabd68f4-f474-1f01-0022-b2fe55eaafa3
* Content: [Configure your Office Add-in to use a shared runtime - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/configure-your-add-in-to-use-a-shared-runtime)
* Content Source: [docs/develop/configure-your-add-in-to-use-a-shared-runtime.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/develop/configure-your-add-in-to-use-a-shared-runtime.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by davidchesnut** [comment]
Hi @LionyxML, thanks for letting us know about this issue. To be clear you followed the shared runtime tutorial and the add-in created by following the steps in the tutorial didn't work? We can retest that article and be sure it doesn't have an error.

Thanks!
David

**Comment by LionyxML** [comment]
I for sure had in mind already had answered this post. Sorry I am a little late.

Thanks for your prompt response @davidchesnut .

That is right. I've followed the instructions, step-by-step of the guide. 

The only thing I made differently was not using `yo` creation in one step cli command but using it interactively since I wanted to generate a `functions.js` file.

What I was aiming to was a way to share some variable like `window.store` between both `taskpane.js` and `functions.js`.

My system:
`Darwin MacBook-Pro.local 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:30 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8103 x86_64`
`MacBook Pro M1`
`MacOS Ventura 13.0.1`
`Excel 16.67 (22111300)`

**Comment by davidchesnut** [comment]
Hi @LionyxML,

With shared runtime, all variables and functions should be shared and accessible anywhere in your project. I think maybe it is not loading for some reason. Can you try adding a console.log statement to one of your custom functions? If it logs to the browser console in debug mode, then you are in shared runtime. otherwise the first step is to figure out why shared runtime is not working.

Also can you please confirm in your manifest you have the following XML configured for Taskpane.Url.

```xml
<Page>
   <SourceLocation resid="Taskpane.Url"/>
</Page>
```

Thanks!
