### ISSUE TITLE
"Insert Image" button click of "Ceate Office Powerpoint Add-in"  shows Error

### ISSUE THREAD

**Issue by GitUserSougata** [OfficeDev/office-js-docs-pr#3758]
Hello everyone,
I followed the Office PowerPoint add-in tutorial from the Microsoft Doc. link below still getting error "Something went wrong" like that. I tried only up to the first "Test the add-in" part which insert bing image into the slide.

Documentation Link:  https://learn.microsoft.com/en-us/office/dev/add-ins/tutorials/powerpoint-tutorial
Image attached.
![Untitlederror](https://user-images.githubusercontent.com/117915558/204254275-a0f67b9c-5e35-4f45-bae1-2628099667e6.png)

**Comment by AlexJerabek** [comment]
Thanks for reporting this @GitUserSougata. 

@alison-mk, could you please investigate?

**Comment by alison-mk** [comment]
Hello @GitUserSougata,

Which version of Visual Studio are you using? Please provide the entire product name and version number, such as: 

Visual Studio 2019, version 16.10.3

Thank you, 
Alison
