### ISSUE TITLE
Links redirect to page different than those linked

### ISSUE THREAD

**Issue by katerinaanton** [OfficeDev/office-js-docs-pr#3766]
In the paragraph about CORS, the links (especially the second one) redirect to pages that are not the ones intended.

Use cross-origin resource sharing (CORS)
For an example of using the cross-origin resource sharing feature of [XmlHttpRequest2](https://dvcs.w3.org/hg/xhr/raw-file/tip/Overview.html), see the "Cross Origin Resource Sharing (CORS)" section of [New Tricks in XMLHttpRequest2](https://www.html5rocks.com/en/tutorials/file/xhr2/).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e24dccf5-3758-3d59-f896-c0a16306a238
* Version Independent ID: 0950c3fd-cdce-9f58-bcfe-baf9930dcd5f
* Content: [Addressing same-origin policy limitations in Office Add-ins - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/addressing-same-origin-policy-limitations)
* Content Source: [docs/develop/addressing-same-origin-policy-limitations.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/develop/addressing-same-origin-policy-limitations.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for flagging this @katerinaanton.

@davidchesnut, could you please investigate and update the links accordingly?

**Comment by davidchesnut** [comment]
Hi @katerinaanton, looks like the XmlHttpRequest2 (level 2) was [abandoned and merged into XmlHttpRequest](https://en.wikipedia.org/wiki/XMLHttpRequest#:~:text=Level%202%20consists%20of%20extended%20functionality%20to%20the,was%20abandoned%20and%20absorbed%20into%20the%20original%20specification.). I'll put in a PR to fix that article. Thanks for catching that!
