### ISSUE TITLE
validate-office-addin passes, Office.context.auth.getAccessTokenAsync still fails with error 13004

### ISSUE THREAD

**Issue by butchmarshall** [OfficeDev/office-js-docs-pr#379]
The doc needs more information in to debug 13004 errors thrown by getAccessTokenAsync.

All Resources are under the same domain (https://butch-dev-vote.polldev.com) with

 ```
   <WebApplicationInfo>
      <Id>70450061-cb7c-41a1-a3bd-0366546edcf7</Id>
      <Resource>api://butch-dev-vote.polldev.com/70450061-cb7c-41a1-a3bd-0366546edcf7</Resource>
      <Scopes>
        <Scope>people.read</Scope>
        <Scope>openid</Scope>
        <Scope>profile</Scope>
        <Scope>offline_access</Scope>
      </Scopes>
    </WebApplicationInfo>
```

```
Office.context.auth.getAccessTokenAsync({forceAddAccount: true, forceConsent: true}, (result) => {
	console.log("result);
})
```
throws
```
error: OSF.DDA.Error
code: 13004
message: "Invalid resource Url specified in the manifest."
name: "Invalid application resource Url provided."
__proto__: Object
status: "failed"
value: undefined
```

The validator says there is no problem with my manifest?
```
sudo -u yeoman validate-office-addin outlook-recognition-manifest.xml 
Calling validation service. This might take a moment...
-------------------------------------
Validation: Passed
Based on the requirements specified in your manifest, your add-in can run on the following platforms; your add-in will be tested on these platforms when you submit it to the Office Store:
  - Outlook 2013 or later
  - Outlook 2016 or later
  - Outlook 2016 for Mac
  - Outlook on the Web
Important: This analysis is based on the requirements specified in your manifest and does not account for any runtime JavaScript calls within your add-in. For information about which API sets and features are supported on each platform, see Office Add-in host and platform availability. (https://dev.office.com/add-in-availability).

*This does not include mobile apps. You can opt-in to support mobile apps when you submit your add-in.
-------------------------------------

```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 554083cc-a1e1-9c9d-da7d-7235b0fff31f
* Version Independent ID: 9923ac3f-0b95-e89f-f4f4-6da8e0a30c36
* Content: [Troubleshoot error messages for single sign-on (SSO)](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/troubleshoot-sso-in-office-add-ins)
* Content Source: [docs/develop/troubleshoot-sso-in-office-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/troubleshoot-sso-in-office-add-ins.md)
* Product: **office 365**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
@butchmarshall What is the value of the **SourceLocation** element in the manifest? Except for protocol, the domain (including any subdomain) should exactly match the domain (and any subdomain) in the Resource element.

What is the **Application ID URI** in the add-in's registration in AAD? It should match the **Resource** value element exactly.

**Comment by butchmarshall** [comment]
Thanks @Rick-Kirkham!  I had **Application ID URI** as `api://70450061-cb7c-41a1-a3bd-0366546edcf7` and not `api://butch-dev-vote.polldev.com/70450061-cb7c-41a1-a3bd-0366546edcf7`

**Comment by jschang19** [comment]
I was dealing with error 13004 when integrating `getAccesstoken` method in Office add-in on my Mac. 

It is worth mentioning that sometimes you have to quit the Word app by using `command` + `q` and reopen it to reload the `manifest.xml` and make your changes applied. I had several times receiving the same error even with the `<Resource>` updated, and then I found out it's my Word caching the old manifest value.
