### ISSUE TITLE
How can I change the page format to 4:3?

### ISSUE THREAD

**Issue by schneiderben** [OfficeDev/office-js-docs-pr#3793]
## Issue

 Hey together,

I currently working on a project, where we want to switch from VBA to an Office AddIn Version. 
For this project I have to change the page layout from 16:9 to 4:3 format - (Din A4).  
Unfortunately, I can't do this with the SlideMasters. 
Also, the PageSetup Class (just like VBA) is not available for JavaScript, 
Is there a way to do this with JavaScript?

Thanks!

Regards, Benedikt

**Comment by AlexJerabek** [comment]
Hi @schneiderben,

Thanks for asking this question. I'm sorry to say, there is not currently a way to adjust the page layout through a PowerPoint JS add-in. Please submit your feature request through [Tech Community](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform). There, it can get upvoted by the community and we use that information to prioritize new feature work.
