### ISSUE TITLE
"Simply clear your browser cache" is not specific enough

### ISSUE THREAD

**Issue by wh1t3cAt1k** [OfficeDev/office-js-docs-pr#3799]
In "Remove a sideloaded add-in" - if my browser has a lot of history, I don't want to lose it all by clearing all cache in the browser.

Please mention specific domains that the cache needs to be cleared for.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0ab35128-1e97-c6ad-babc-f696f2e7b0fe
* Version Independent ID: cd1bacb1-14d7-a38d-321c-ebc2a526e03b
* Content: [Sideload Office Add-ins to Office on the web - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/testing/sideload-office-add-ins-for-testing#remove-a-sideloaded-add-in)
* Content Source: [docs/testing/sideload-office-add-ins-for-testing.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/testing/sideload-office-add-ins-for-testing.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for the feedback @wh1t3cAt1k. I'll try to find some more specific cache instructions for you and the documentation.

**Comment by AlexJerabek** [comment]
One question, do the steps listed here for clearing the cache using Edge developer tools not accomplish what you're trying to do? https://learn.microsoft.com/en-us/office/dev/add-ins/testing/clear-cache#using-the-microsoft-edge-developer-tools
