### ISSUE TITLE
IE11 usage statistics 

### ISSUE THREAD

**Issue by realappie** [OfficeDev/office-js-docs-pr#3804]
## Article URL
[Browsers used by Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins)

## Issue

 
Hey there, I understand from the docs and the several issues posted in this repo that IE11 is still used by a ["a large install base of one-time purchases"](https://github.com/OfficeDev/office-js-docs-pr/issues/2756#issuecomment-862761056). Now it would really help to have some numbers on how many percentage of users are still indirectly using IE11 due their type of license/office version/OS version. 

This would help us prioritise potential IE11 issues, thanks!

**Comment by nkkinariwala** [comment]
@realappie - can you please let us know what host app (word, excel, ppt, outlook) or platform you are dealing with?
Also is this for already published Add-in OR in-development Add-in?

**Comment by realappie** [comment]
This is regarding MS Word. And regarding platform, I think we will be targeting office on windows 2016 and office on mac. Also this is a in-development add-in.

Actually also having this information available per platform would be super helpful, as it will make it easier to make an informed decision on which platforms to support.

**Comment by nkkinariwala** [comment]
Hello @realappie - If I understand correctly, you are looking for the total usage of Microsoft Word on IE11. If that's the case, upon further research, we are unable to provide that information in a way that can be maintained in a compliant manner. However, I can say that, overall usage of IE11 is relatively low in comparison with chrome, edge, firefox and other popular browsers. Does that help?

**Comment by realappie** [comment]
No, I'm not looking for total usage of Microsoft word on IE11. I think you're referring to [office for the web](https://www.microsoft.com/en-us/microsoft-365/free-office-online-for-the-web). I'm more interested in IE11 'embeddable browser controls' usage by the desktop version of MS Word.

According to the [Support older Microsoft browsers and Office versions docs](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/support-ie-11?tabs=ie), IE11 is used in certain scenarios. But it's not clear how often this is the case, which makes prioritisation of IE11 issues on our side hard. 

> If you plan to support older versions of Windows and Office, your add-in must work in the embeddable browser controls used by these versions. For example, browser controls based on Internet Explorer 11 (IE11) or Microsoft Edge Legacy (EdgeHTML-based). For information about which combinations of Windows and Office use these browser controls, see Browsers used by Office Add-ins.

**Comment by AlexJerabek** [comment]
Hi @realappie,

We'll try to track down relevant data for you.

That said, IE11 as a browser control is used when customers are on volume-licensed editions of Office (2019 and older) and older versions of Windows. AppSource doesn't test against these older versions and both Office 2013 and 2016 have reached end-of-life (with [Office 2019's end-of-life approaching soon](https://learn.microsoft.com/en-us/lifecycle/products/microsoft-office-2019)).  [Windows 8 has also reached this point](https://support.microsoft.com/en-us/windows/windows-8-1-support-ended-on-january-10-2023-3cfd4cde-f611-496a-8057-923fba401e93).  These older versions also [lack a lot of functionality from the Office Add-ins platform](https://learn.microsoft.com/en-us/javascript/api/requirement-sets?view=excel-js-preview). 

If you're developing for AppSource and not a specific market, we advise that you have a graceful exit (as documented [here](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/support-ie-11?tabs=ie)). If you're making an add-in for your corporation and know they're still on older versions of Office or Windows, then you should work to support it.

**Comment by nkkinariwala** [comment]
@realappie - I got your ask on the usage after you clarified. Thank you for that. 
the information about the user base you are looking for is around 3-5% of overall userbase. We won't be able to share the actual number on a public forum in a compliant manner. Hope this information helps you to take next steps accordingly.
