### ISSUE TITLE
Multi select not work and never worked

### ISSUE THREAD

**Issue by taoufiqi** [OfficeDev/office-js-docs-pr#3810]
Hi,
I followed all the steps to get my Add-in working for a multiple selection of messages and unfortunetly it doesn't work.
In the Demo seen in the video, it worked but in real life here, no.

Can you please give a complete sample (nodejs project) that works really.

Configuration : Microsoft® Outlook® pour Microsoft 365 MSO (Version 2212 Build 16.0.15928.20196) 32 bits 
Windows 10 pro.

Regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 34daad03-0e48-d846-0c52-9ce4cedd4462
* Version Independent ID: 34daad03-0e48-d846-0c52-9ce4cedd4462
* Content: [Activate your Outlook add-in on multiple messages (preview) - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/item-multi-select?source=recommendations)
* Content Source: [docs/outlook/item-multi-select.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/outlook/item-multi-select.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by samantharamon** [comment]
Hi @taoufiqi,

Thank you for reaching out. I see you've opened a similar issue at https://github.com/OfficeDev/Office-Add-in-samples/issues/473, so I'll go ahead and close this as a duplicate. We will assist you further in the other issue.
