### ISSUE TITLE
Broken Yeoman generator for Excel add-in?

### ISSUE THREAD

**Issue by bbartley** [OfficeDev/office-js-docs-pr#3812]
The current Yeoman generator for an Excel taskpane add-in fails to install required dependencies.  No `package.json` file is created, so following the recommendation to run `npm install` yourself has no result.   As far as I can tell, the resulting project configuration is broken and unrecoverable.

```
I'm all done. Running npm install for you to install the required dependencies. If this fails, try running the command yourself.

No change to package.json was detected. No package manager install will be executed.
npm WARN config cache-min This option has been deprecated in favor of `--prefer-offline`.
npm ERR! code ETARGET
npm ERR! notarget No matching version found for eslint-plugin-office-addins@^2.1.4.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bbartley/.npm/_logs/2023-01-24T19_02_24_604Z-debug-0.log
```

I am running Yeoman version 4.3.1 and npm version 8.18.0 on OS X 10.15.7.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9c4ddde7-f1fd-44ba-fba1-0ae9d0131df7
* Version Independent ID: d946ffe6-f29f-1563-b679-121090ba60a1
* Content: [Build your first Excel task pane add-in - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-jquery?tabs=yeomangenerator)
* Content Source: [docs/quickstarts/excel-quickstart-jquery.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/quickstarts/excel-quickstart-jquery.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @bbartley,

I'm sorry to hear about those difficulties. Let me tag @millerds and @igor-ribeiiro to investigate.

As for a short-term fix, what is the output of running `npm install` in your project's root directory (e.g. "./My Office Add-in")? I was able to get the project working after that manual install.

**Comment by bbartley** [comment]
I think it is working now, and I was perhaps mistaken when I claimed that no `package.json` was being created.  I was looking for it inside my current working directory, one level up from the target directory that Yeoman creates.  When I `cd` into that directory, then I am able to complete the installation and launch the taskpane add-in.  Thanks!

**Comment by AlexJerabek** [comment]
Excellent to hear! I'll close the issue for now, but please comment if you have any other problems with the quick start.
