### ISSUE TITLE
Angular + TypeScript shows "Please sideload your addin to see app body"

### ISSUE THREAD

**Issue by roldengarm** [OfficeDev/office-js-docs-pr#3814]
I've followed the documentation to generate a new Word Add-in. Javascript seems to work fine, but when I create a project with Angular + Typescript, the app won't load when I run `npm start`. 
I get this:
![image](https://user-images.githubusercontent.com/37638588/214432991-b576631a-0ee8-4b1d-8319-40efd57040e2.png)

There are no errors in the webpack console. When I browse to https://localhost:3000/taskpane.html, it seems to load fine.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 77e380a7-6e2e-ada8-d297-3fd5018a1958
* Version Independent ID: f23490e8-6eeb-f2d5-6c94-69e3c9ed83f4
* Content: [Build your first Word task pane add-in - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/quickstarts/word-quickstart?tabs=yeomangenerator)
* Content Source: [docs/quickstarts/word-quickstart.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/quickstarts/word-quickstart.md)
* Product: **word**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by roldengarm** [comment]
> Hi @roldengarm,
> 
> Are you able to manually sideload the add-in after running `npm start`? The instructions can be found here: https://learn.microsoft.com/en-us/office/dev/add-ins/testing/test-debug-office-add-ins#sideload-an-office-add-in-for-testing

Hi @AlexJerabek thanks for your reply. Haven't tried that, as it was working fine for JS only add-ins. 

I found out it may be because I've got a version of Office 2019 that still uses IE11 apparently, which may be causing this.

**Comment by AlexJerabek** [comment]
That might be the case. If you need a version of M365 to develop with, check out the [Developer Program](https://developer.microsoft.com/en-us/microsoft-365/dev-program).

**Comment by ElizabethSamuel-MSFT** [comment]
@roldengarm Let us know if you were able to get past this issue and how (e.g., did a newer version of Office help?). Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
> Hi @roldengarm,
> 
> Are you able to manually sideload the add-in after running `npm start`? The instructions can be found here: https://learn.microsoft.com/en-us/office/dev/add-ins/testing/test-debug-office-add-ins#sideload-an-office-add-in-for-testing

As an aside, we're updating the "sideload" message to link to the sideload article. See PR https://github.com/OfficeDev/Office-Addin-TaskPane/pull/199.

**Comment by ElizabethSamuel-MSFT** [comment]
> I have tried on Office Web, that works fine.

@roldengarm It's good to know you're unblocked from trying the add-in. Thanks for the update. Have you been able to get unblocked when using the Office desktop application?

Thanks.

**Comment by roldengarm** [comment]
@ElizabethSamuel-MSFT I've upgraded to the latest Office version, and then it worked fine. Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@roldengarm Glad to hear that. Thanks for the update.
