### ISSUE TITLE
Overly specific port number

### ISSUE THREAD

**Issue by Rick-Kirkham** [OfficeDev/office-js-docs-pr#3821]
This article uses "localhost:44355" in multiple places in a way that implies the reader should always use that port number. Is that true? Shouldn't they use the port number that's used in their project, which is typically "3000" in projects created by Yo Office?

This user is getting confused by this (among other things): https://stackoverflow.com/questions/75275452/setup-microsoft-identify-platform-and-missing-grant-for-this-add-in-for-localh

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 79094327-e4d3-da9a-e152-18408c0ffde2
* Version Independent ID: 120ecfb2-3d09-21bf-211e-e1e89050b52c
* Content: [Register an Office Add-in that uses SSO with the Microsoft identity platform - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/register-sso-add-in-aad-v2)
* Content Source: [docs/develop/register-sso-add-in-aad-v2.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/develop/register-sso-add-in-aad-v2.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by davidchesnut** [comment]
This was to make it simpler to reuse the include steps on multiple project types. I can rework the article to use a placeholder and different ports so this isn't confusing.

**Comment by davidchesnut** [comment]
This should be fixed now.
