### ISSUE TITLE
Office Apps add on

### ISSUE THREAD

**Issue by ptwqigit** [OfficeDev/office-js-docs-pr#3822]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b73778b8-8dd2-98f5-b4a1-e135a0049011
* Version Independent ID: 25744bd8-6084-00dc-545a-4b3eb87dedd4
* Content: [Create add-in commands in your manifest for Excel, PowerPoint, and Word - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/create-addin-commands)
* Content Source: [docs/develop/create-addin-commands.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/develop/create-addin-commands.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @ptwqigit,

With no issue description, it's unclear what your feedback is. I'm going to close the issue, but we can revisit the problem if you add context with additional comments.
