### ISSUE TITLE
Is there a problem using the Outlook Web Add-In template?

### ISSUE THREAD

**Issue by GermanEZI** [OfficeDev/office-js-docs-pr#3827]
On this page I'm instructed to use Yeoman.   However, there is a template that comes with Visual Studio.  

Are there any examples that use the Web Add-In templates?   I'm writing for Outlook (Office 365)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a59958d2-f428-9ca2-3440-a5af662386c0
* Version Independent ID: dcaf0b5b-08ea-c437-130b-342a1be62a16
* Content: [Tutorial: Build a message compose Outlook add-in - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/tutorials/outlook-tutorial)
* Content Source: [docs/tutorials/outlook-tutorial.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/tutorials/outlook-tutorial.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @GermanEZI,

Thanks for raising this issue. Just to clarify, did following [these quick start instructions](https://learn.microsoft.com/en-us/office/dev/add-ins/quickstarts/outlook-quickstart?tabs=visualstudio) not generate a manifest file for you?

**Comment by GermanEZI** [comment]
I have a feeling that my updated comment wasn't received.  Both the node.js/Yeoman page and the link you left me create a manifest.

However, I see the problem now.
[Build your first Outlook add-in](https://learn.microsoft.com/en-us/office/dev/add-ins/quickstarts/outlook-quickstart?tabs=yeomangenerator)

[Build your first Outlook add-in](https://learn.microsoft.com/en-us/office/dev/add-ins/quickstarts/outlook-quickstart?tabs=visualstudio)

Whenever I perform a search in order to create an Outlook Web Add-In, I'm given the link to the Yeomangenerator.

The link you gave me takes me to visualstudio.

You'll see that the page title is the same.   This is confusing.   Perhaps something in the search result should indicate that one uses Node.js; and on the Node.js page there should be a link for those who reached that page hoping they'd find a Visual Studio example.

Anyway, thanks for the response.  I have what I need now.

**Comment by GermanEZI** [comment]
I'm good to go.

**Comment by AlexJerabek** [comment]
Yeah, the tabs could be more obvious. That's good feedback for the platform team.
