### ISSUE TITLE
npm start command fails in the "Build your first Outlook add-in" article

### ISSUE THREAD

**Issue by elegault** [OfficeDev/office-js-docs-pr#3840]
I followed the steps exactly in the "[Build your first Outlook add-in](https://learn.microsoft.com/en-us/office/dev/add-ins/quickstarts/outlook-quickstart?tabs=yeomangenerator)" article using Visual Studio Code, but it fails at step 1 in the "Try it out" section:

![npm start errors - blurred](https://user-images.githubusercontent.com/4130365/217943974-6abf4c3b-4afd-4c9d-b7dd-5862adac6378.png)

Here's the debug log that's referenced in the console:

[2023-02-08T21_57_22_692Z-debug.log](https://github.com/OfficeDev/office-js-docs-pr/files/10690325/2023-02-08T21_57_22_692Z-debug.log)

Bad luck/environment? Keep trying? Or can this be reproduced by everyone? It seems to be an issue with the office-addin-debugging package:

````
10 silly lifecycle office-addin-taskpane-js@0.0.1~start: Args: [ '/d /s /c', 'office-addin-debugging start manifest.xml' ]
11 silly lifecycle office-addin-taskpane-js@0.0.1~start: Returned: code: 1  signal: null
12 info lifecycle office-addin-taskpane-js@0.0.1~start: Failed to exec start script
13 verbose stack Error: office-addin-taskpane-js@0.0.1 start: `office-addin-debugging start manifest.xml`
````
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 930ce4fc-c8b8-f756-f03f-a716f1ef7883
* Version Independent ID: 753a2e38-9430-25bb-5409-b7eed9c88e47
* Content: [Build your first Outlook add-in - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/quickstarts/outlook-quickstart?tabs=yeomangenerator)
* Content Source: [docs/quickstarts/outlook-quickstart.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/quickstarts/outlook-quickstart.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @elegault,

Does this problem persist if you run `npm install` in the project directory?

**Comment by elegault** [comment]
@AlexJerabek Yes!

**Comment by AlexJerabek** [comment]
@millerds, @samantharamon - Any ideas?

**Comment by millerds** [comment]
What version of node and npm is installed on the box?

**Comment by millerds** [comment]
Update you version of node and npm.  Current LTS version is v18 and we support v18 and v16.  We should add node version checking to our project generation code for yeoman, but it's not currently there and this seems to be the error the comes as a result. (there was probably a npm error earlier in the console as well)

**Comment by elegault** [comment]
Okay, I upgraded to node 18.14.0 and npm 9.3.1. However, I now have a new problem. I get the same error (Cannot find module 'ajv/dist/core'), but the stack trace is different for the faulting file (\\node_modules\\office-addin-debugging\\cli.js):

![npm start errors - node 18 14 - blurred](https://user-images.githubusercontent.com/4130365/217942613-a9f65b32-f99d-4266-aecb-2758adc2b15d.png)

**Comment by millerds** [comment]
Did you run 'npm install' in the project folder after upgrading (should have mentioned that earlier)?

**Comment by elegault** [comment]
Yes, right before I ran `npm start`

**Comment by millerds** [comment]
What's the name of the add-in project you created?

**Comment by elegault** [comment]
"Outlook Web Add-in Testing". Creative, huh?

**Comment by millerds** [comment]
Can you run "npm ls -g" and provide the results?

**Comment by elegault** [comment]
Sure:

````
C:\Program Files\nodejs -> .\
├── corepack@0.15.3
└── npm@9.3.1
````

**Comment by millerds** [comment]
It doesn't look like you have 'yo' and 'office-generator' installed . . . how did you create the project?

**Comment by elegault** [comment]
With the Yeoman generator!! Not sure if this is related, but when I upgraded my node version I used the Windows Installer (as I had previously), but then uninstalled it and reinstalled it using nvm (which I also just installed after uninstalling node). I then ran my last `npm start` command and got the slightly differenct error. Maybe I should just start all over again with a new Yeoman project?

**Comment by millerds** [comment]
OK . . . I believe nvm maintains a different set of global installs for each of the versions is has so you would have to reinstall yo and generator-office.  It shouldn't have any effect on existing projects . . . but that was going to be my next suggestion :-) . . . start with a fresh project.

**Comment by elegault** [comment]
Bingo! Reinstalling yo and generator-office fixed the issue. Thanks Darren!
