### ISSUE TITLE
Cannot set breakpoints in TypeScript version of this project in Visual Studio even though you could in the JavaScript version

### ISSUE THREAD

**Issue by dheine777** [OfficeDev/office-js-docs-pr#3842]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b888399c-fe96-0934-00ce-86db8fa8cf5b
* Version Independent ID: 2c5d24e8-5639-42b1-4d12-119f89591550
* Content: [Convert an Office Add-in project in Visual Studio to TypeScript - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/convert-javascript-to-typescript)
* Content Source: [docs/develop/convert-javascript-to-typescript.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/develop/convert-javascript-to-typescript.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thank you for reporting this @dheine777.

@davidchesnut, could you please investigate?

**Comment by davidchesnut** [comment]
Yes I can repo this behavior. This article needs a refresh. I'll start working on that.

**Comment by dheine777** [comment]
Thanks!

**Comment by davidchesnut** [comment]
Hi @dheine777,

Okay looks like the missing piece is you need to add a tsconfig.json file to the root of the "Web" project folder. Here are values I used:

```json
{
  "compileOnSave": true,
  "compilerOptions": {
    "noImplicitAny": false,
    "noEmitOnError": true,
    "removeComments": false,
    "sourceMap": true,
    "target": "es5"
  },
  "include": [
    "scripts/**/*",
    "**/*"
  ]
}
```

The important thing is that your project folder is listed in the "include" section "**/*". Then when you build, look to see that .js files and .js.map files were generated for debug (use file explorer to check as they probably won't appear in the VS IDE). They should be in the same location as their .ts counterparts. 

I tried this on a new Excel project from VS, and it worked. So hope this works for you too!

Cheers,
David
