### ISSUE TITLE
Add-In button missing in OneNote Web

### ISSUE THREAD

**Issue by Bingomzan** [OfficeDev/office-js-docs-pr#3843]
The page says to add a OneNote Add-In via a button on the Insert tab, the button is missing on the web and desktop versions.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a6ed3136-1d12-66c2-a8b1-1e7e43553aae
* Version Independent ID: 0e40308a-2d3d-a27b-04d5-1bdd7c09b501
* Content: [Build your first OneNote task pane add-in - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/quickstarts/onenote-quickstart)
* Content Source: [docs/quickstarts/onenote-quickstart.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/quickstarts/onenote-quickstart.md)
* Product: **onenote**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @Bingomzan,

I'm sorry to hear you're having difficulties with the quick start. To be clear, Office Add-ins are only supported on OneNote for the web.  Could you please share what you're seeing in your Insert tab on the ribbon? Here's what mine looks like.

![image](https://user-images.githubusercontent.com/38896772/217950060-6f390f73-dbd7-4abe-8794-daa3fed0babd.png)

Additionally, are you able to find the Office Add-ins button in the classic ribbon or by using TellMe?

**Comment by Bingomzan** [comment]
![image](https://user-images.githubusercontent.com/8529469/217952717-6d0b4849-c91e-42ad-8a3f-3a32d35bc73e.png)
This is what my ribbon looks like. I am on a GCC tenant if that makes a difference.

**Comment by AlexJerabek** [comment]
Thanks @Bingomzan. I'm following up internally about the GCC support for sideloading.

**Comment by AlexJerabek** [comment]
Hi @Bingomzan,

It's possible your admin has disabled add-ins or sideloading in some way. Could you please confirm with them if that's the case?
