### ISSUE TITLE
Diagram has unreadable text in dark mode 

### ISSUE THREAD

**Issue by ZhangYiJiang** [OfficeDev/office-js-docs-pr#3846]
The image at https://learn.microsoft.com/en-us/office/dev/add-ins/images/open-in-excel-architecture.svg does not have a solid background, hence the black text becomes unreadable in dark mode. Since it is a SVG it could read CSS variables from the parent page to style its text but the faster solution would just be to add a white background 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7fbd80a3-6de7-bf03-03a5-65386457c43f
* Version Independent ID: c6e6d497-03f4-c840-7929-77af2efbd426
* Content: [Create an Excel spreadsheet from your web page, populate it with data, and embed your Office Add-in - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/excel/pnp-open-in-excel)
* Content Source: [docs/excel/pnp-open-in-excel.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/excel/pnp-open-in-excel.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by alison-mk** [comment]
Hi @ZhangYiJiang, thanks for letting us know! I've opened a PR to fix this issue. Once that PR is merged, this issue will be closed. 

Cheers,
Alison
