### ISSUE TITLE
Latest yeoman install does not appear to be working on Windows

### ISSUE THREAD

**Issue by CDFriend** [OfficeDev/office-js-docs-pr#3849]
Installing the latest version of Yeoman (v4.3.1) does not appear to be working on Windows. We should specify a version of Yeoman which works with Windows and the Office generator. 

Bug logged in the Yeoman project: https://github.com/yeoman/yo/issues/781

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 15f43fe5-03e0-579c-165c-57e16b1a53ea
* Version Independent ID: 15f43fe5-03e0-579c-165c-57e16b1a53ea
* Content: [Create Office Add-in projects using the Yeoman Generator - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/yeoman-generator-overview)
* Content Source: [docs/develop/yeoman-generator-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/develop/yeoman-generator-overview.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
I'm afraid that it would be an impossible maintenance burden for us to keep up with problems in the yeoman tool. There will occasionally be "bad builds" of yeoman, but these will be fixed and a new build released pretty quickly. We don't have the staff to check every yeoman build for bugs and update our docs whenever there's a problem build.
