### ISSUE TITLE
Make explicit that the Insert ribbon should be used, not the Input menu at the top of the screen

### ISSUE THREAD

**Issue by mphisrael** [OfficeDev/office-js-docs-pr#3851]
From the current article it is unclear that side loading the add-in should be done from the Insert *ribbon*.  My initial thought was that I should use the Insert menu, and since there is an identically named menu item "My Add-ins" this led to great confusion as the dropdown option to add the add-in didn't exist. 

Suggestion is to make it explicit in the text (and screenshot) to use the Insert ribbon and not the menu

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1bb09ad2-7df4-ba17-f35e-aa501d3face5
* Version Independent ID: 1bb09ad2-7df4-ba17-f35e-aa501d3face5
* Content: [Sideload Office Add-ins on Mac for testing - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/testing/sideload-an-office-add-in-on-mac)
* Content Source: [docs/testing/sideload-an-office-add-in-on-mac.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/testing/sideload-an-office-add-in-on-mac.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
This is what I see in that article:
![image](https://user-images.githubusercontent.com/9088056/219461736-21ad2564-b10d-47c2-8132-04bf78604a4a.png)
It seems as if there is already a screenshot and an explanatory note. I'll clarify the opening phrase of the step to make clear that readers should start on the Word ribbon.

**Comment by mphisrael** [comment]
Cheers! I did see that note but apparently did not understand it correctly. Thanks for clarifying it in the documentation
