### ISSUE TITLE
Outlook for Desktop - IE11

### ISSUE THREAD

**Issue by moshikonachmias** [OfficeDev/office-js-docs-pr#3852]
After reading [this](https://learn.microsoft.com/en-us/deployedge/edge-learnmore-neededge) article, I was wondering, what is the effect on Outlook versions which are using IE11 as their browser to run the Add-ins.
e.g Volume-licensed, Office 2016

Thanks
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 00c430f1-bbf5-53b8-a225-4fbe8fc39c3b
* Version Independent ID: 0a069a0d-4d35-71ee-53af-8c55fe8548a0
* Content: [Browsers used by Office Add-ins - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins)
* Content Source: [docs/concepts/browsers-used-by-office-web-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/concepts/browsers-used-by-office-web-add-ins.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
What do you mean by "effect" in this context?

**Comment by moshikonachmias** [comment]
@Rick-Kirkham does Outlook for Desktop will still use IE?

**Comment by Rick-Kirkham** [comment]
@moshikonachmias  I've been out sick for a few days and didn't see your question till now. 

The rows in the tables of the article [Browsers used by Office Add-ins - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins) that say "Internet Explorer 11" are still correct, _or at least as correct as they ever were_, and the recent disabling of IE in Windows should not change your plans as an add-in developer. 

The potential for confusion is that, strictly speaking, add-ins never literally used the browser Internet Explorer 11. Saying that they did was a simplification. In reality, add-ins use an embedded web view control. Think of the control as a browser that doesn't have any Menu bar, or ribbon, or status bar; just the pane with a web page visible in it. The web view control that is referred to (a bit misleadingly) in the article I linked to as "Internet Explorer 11" _has **NOT** been disabled_. It is still present in Windows and still works. Accordingly, add-ins still work in volume-licensed Office 2016 just as they always have. There are no plans to disable that web view control. 

I think it is likely that others will have the same question you have, so it is very possible that in the near future the term "Internet Explorer 11" in the article that I linked to will be replaced with something closer to the literal truth.

**Comment by BrendanMayHRB** [comment]
We are facing some issues with IE11 browser on Outlook 2016/Outlook 2013 systems including:

1)  Modal window is often displayed as very translucent / barely possible to see

2)  When clicking on a button in our react add-in, the add-in "jumps" to the top of the page.  

Could you direct me to where we can information on how to resolve these issues since IE11 support has been revoked, we have not been able to get any valid response on this query.

**Comment by Rick-Kirkham** [comment]
@BrendanMayHRB Sorry, I didn't see this till now. You've raised a different issue. Coding problems like your should first be raised on StackOverflow. Be sure and tag your question `office-js`.
