### ISSUE TITLE
differentiate from User-Defined Functions

### ISSUE THREAD

**Issue by rootsmusic** [OfficeDev/office-js-docs-pr#3857]
How do Custom Functions differ from [User-Defined Functions that are installed with add-ins](https://support.microsoft.com/en-us/office/user-defined-functions-that-are-installed-with-add-ins-reference-729ca23f-e362-4d51-9401-a9060011eb9b?ns=xlwaenduser&version=16&ui=en-us&rs=en-us&ad=us)?  Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 94ad7803-d4f7-a700-7c7f-204cd8f34e4a
* Version Independent ID: 9c485bae-cab1-bdad-4c8e-baad2b12b22d
* Content: [Create custom functions in Excel - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-overview)
* Content Source: [docs/excel/custom-functions-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/excel/custom-functions-overview.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @rootsmusic,

Thank you for the question. UDFs are, effectively, the older, COM-version of custom functions. UDFs don't work on Excel for the web. Custom functions do work cross-platform, as they utilize the Office JS infrastructure.

Let me tag @alison-mk, in case there's a more complete answer or there are places in the docs we could explain this distinction.

**Comment by rootsmusic** [comment]
@AlexJerabek wrote:
> Custom functions do work cross-platform, as they utilize the Office JS infrastructure.

Ok I suggest differentiating the terminology, because "custom functions" also refers to [functions that utilize VBA](https://support.microsoft.com/en-us/office/create-custom-functions-in-excel-2f06c10b-3622-40d6-a1b2-b6748ae8231f) and that can be added as an Excel Add-In.

**Comment by alison-mk** [comment]
Hi @rootsmusic, thank you for the feedback. I've opened a PR to help clarify the **custom functions** terminology in the Office Add-ins documentation. We're also investigating updating the support.microsoft.com articles you linked in your comments, to help reduce confusion throughout our documentation. 

This issue will automatically close when PR #3874 is merged.

Cheers, 
Alison

**Comment by rootsmusic** [comment]
Great @alison-mk, that article about the VBA custom functions has [a duplicate](https://support.microsoft.com/en-gb/office/create-custom-functions-in-excel-2f06c10b-3622-40d6-a1b2-b6748ae8231f).

**Comment by alison-mk** [comment]
Those two are actually the same article with different language tags. In the URLs, you can see that they match precisely, except that one includes the tag "en-us" and the other includes the tag "en-gb". One is for readers with their language set to US English, and the other is for readers with their language set to British English. Any other small variations between the two articles is a result of localization to a particular region. 

URLs: 
https://support.microsoft.com/en-gb/office/create-custom-functions-in-excel-2f06c10b-3622-40d6-a1b2-b6748ae8231f
https://support.microsoft.com/en-us/office/create-custom-functions-in-excel-2f06c10b-3622-40d6-a1b2-b6748ae8231f

**Comment by AlexJerabek** [comment]
@alison-mk, should this have closed when #3874 was checked in?

**Comment by alison-mk** [comment]
Yes, that was my goal @AlexJerabek. I thought it would auto-close when the associated PR was merged — perhaps I needed to link the PR for that to work. Will close now. Thanks!
