### ISSUE TITLE
Incorrect URL

### ISSUE THREAD

**Issue by elegault** [OfficeDev/office-js-docs-pr#3858]
In the **Supported setups** section, on the **Web browser - modern Outlook** tab, the following text has an incorrect URL:

>The mailbox owner must first [provide access to a delegate](https://www.microsoft.com/microsoft-365/blog/2013/09/04/configuring-delegate-access-in-outlook-web-app/) by updating...

The incorrect URL (https://www.microsoft.com/microsoft-365/blog/2013/09/04/configuring-delegate-access-in-outlook-web-app/) should be https://support.microsoft.com/en-us/office/allow-someone-else-to-manage-your-mail-and-calendar-41c40c04-3bd1-4d22-963a-28eafec25926.

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 19bf3a5d-1f48-e36e-0a39-ccc8951045ff
* Version Independent ID: b48cd60a-39a7-ea5d-6828-9e4278ee24d3
* Content: [Enable shared folders and shared mailbox scenarios in an Outlook add-in - Office Add-ins](https://learn.microsoft.com/en-ca/office/dev/add-ins/outlook/delegate-access?tabs=modern%2Cxmlmanifest#configure-the-manifest)
* Content Source: [docs/outlook/delegate-access.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/outlook/delegate-access.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for reporting this @elegault.

@samantharamon, could you please verify the link and update the page accordingly?

**Comment by samantharamon** [comment]
Thanks for bringing this to our attention, @elegault. We initially linked to this blog post to provide steps to enable delegate access in Outlook on the web, however, they're now outdated. The link you shared provides guidance on how to do this in Outlook on Windows. I'll work on adding instructions specific to Outlook on the web. Additionally, I'll also mention that as an alternative, users can set up delegate access through the Windows client and provide the link you shared. Thanks for contributing to the docs!

**Comment by samantharamon** [comment]
After investigating this further, it looks like only calendar delegation can be configured through Outlook on the web. Enabling inbox delegation must be done through Outlook on Windows. I've submitted #3890 to update the article accordingly. Let me know if we can improve this further. Thanks again for catching this, @elegault!

**Comment by elegault** [comment]
@samantharamon You are welcome! It is of course also possible for admins to configure delegation on the mailboxes in Exchange admin center (at https://admin.exchange.microsoft.com/#/mailboxes). Mayyy be worth mentioning also?

**Comment by samantharamon** [comment]
Great catch! Added that option and the Microsoft 365 admin center, too.
