### ISSUE TITLE
.search() doesn't work with new lines

### ISSUE THREAD

**Issue by jozefcipa** [OfficeDev/office-js-docs-pr#3903]
## Article URL
https://learn.microsoft.com/en-us/office/dev/add-ins/word/search-option-guidance

## Issue

 
Let's say I have this text in my Word document.

```
This is my test 
```
When I select text and try to search for a substring like follows,

```
const selection = context.document.getSelection()
const searchResult  = selection.search('is my', {
  ignoreSpace: true,
  matchWildcards: true,
})
```

I get one result, which is correct, because substring `is my` is present in the document.

However, when I add a new line in between, like

```
This is 
my test 
```

And I use the same code, it doesn't return anything.

The copied text is in format `This is\rmy test\r` and even if I search for it as `is\rmy` or `is*my` it still doesn't work.

So the question is, whether **searching with new lines** is not supported? Or am I doing it wrong? In any case, I think this should be mentioned in the docs, ideally with an example or a disclaimer that it's not supported.

**Comment by AlexJerabek** [comment]
Hi @jozefcipa,

Thank you for reporting this issue. @ElizabethSamuel-MSFT, could you please investigate?

**Comment by ElizabethSamuel-MSFT** [comment]
@jozefcipa I tried this in the Word UI and `is*my` worked with the "Use wildcards" option turned on.

I'll try the code and let you know what I find.

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@jozefcipa In code, both of the following worked in Word on Windows and should work in Word on Mac.

1. Literal search using `^p` to check for the paragraph (a version of new line in Word).
```js
const searchResults = selection.search('is^pmy');
```

2. Wildcard search as mentioned in earlier comment.
```js
const searchResults = selection.search('is*my', {
      matchWildcards: true
    });
```

Per the [Find and replace text](https://support.microsoft.com/office/c6728c16-469e-43cd-afe4-7708c6c779b7#ID0EBBD=Web) article on support.microsoft.com, Word on the web supports only basic search so these advanced search options won't work there.

Which platform have you been using to test? The Windows, Mac, or web client?

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
We're adding documentation for the notations representing certain special characters in search. See PR https://github.com/OfficeDev/office-js-docs-pr/pull/3912.

**Comment by jozefcipa** [comment]
hey @ElizabethSamuel-MSFT thank you for updating the documentation 🎉 I just tried it now and it still doesn't work. I should've mentioned that I'm using Office 365 via Sharepoint, so maybe it's not supported in the online version?

**Comment by ElizabethSamuel-MSFT** [comment]
Ah, I see. @jozefcipa That's true, the online (web) UI doesn't support advanced search (see [Find and replace text](https://support.microsoft.com/office/c6728c16-469e-43cd-afe4-7708c6c779b7#ID0EBBD=Web) support article). That means, the API also doesn't support it in online/web version.

I'll go ahead and close this issue. If you have further questions or issues, let us know.

Thanks.
