### ISSUE TITLE
appendOnSendAsync() and prependOnSendAsync() methods don't work

### ISSUE THREAD

**Issue by elegault** [OfficeDev/office-js-docs-pr#3904]
My assumption after reading the article was that a specified function would run _automatically_ when the add-in is sent. However, the two sample functions are connected to Add-in commands associated with two Ribbon buttons, which must be clicked by the user to call the relevant `Office.context.mailbox.item.body.appendOnSendAsync` or `Office.context.mailbox.item.body.prependOnSendAsync` functions. Clicking these buttons show informational messages, but the messages don't complete or close and nothing is appended or prepended in the email body after the email is sent (in Outlook for Windows Version 2303 (Build 16227.20004 Click-to-Run).

![image](https://user-images.githubusercontent.com/4130365/224578031-f66f7e39-0d9a-430f-8a96-b8fab630f25b.png)

Is event-based activation with the OnMessageSend event the only way we can automatically run those two functions without user interaction? I tried implementing the WebView and JS runtimes as per event-based activation requirements to see if that would get the functions to work, but it didn't work. If those runtimes aren't needed, then the article should remove the references to WebViewRuntime.Url and JSRuntime.Url in the manifest snippet to alleviate any confusion.

Note also that there is a reference to a commands.js file, but if the user follows the instructions as per [the quick start sample](https://learn.microsoft.com/en-us/office/dev/add-ins/quickstarts/outlook-quickstart?tabs=yeomangenerator) that is referenced, that sample does not have a commands.js file!

I have a full sample project hosted in GitHub Pages in my repo which is based on this article: https://github.com/elegault/PnP-OfficeAddins/tree/outlook-prepend-or-append-on-send/Samples/outlook-prepend-or-append-on-send.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 28320183-499e-5a19-2925-31f73227766f
* Version Independent ID: e998c64b-dc57-fb8d-9959-c4095e32411a
* Content: [Prepend or append content to a message or appointment body on send - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/append-on-send?tabs=xmlmanifest)
* Content Source: [docs/outlook/append-on-send.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/outlook/append-on-send.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @elegault,

Thank you for the question. @samantharamon, could you please investigate?

**Comment by elegault** [comment]
Adding @davidchesnut, as we're working on this as a code sample for the Samples directory

**Comment by samantharamon** [comment]
Thanks for reaching out, @elegault.

The prepend-on-send and append-on-send functions must be initiated via an option or button in the task pane or via a command button on the ribbon. You're correct that event-based activation is needed to enable these functions to occur automatically. You should be able to use other events other than OnMessageSend, e.g., OnNewMessageCompose, to initiate the functions.

Thanks for pointing out the WebViewRuntime.Url and JSRuntime.Url references in the manifest. Those aren't needed to get the walkthrough to work. I'll get a PR going to fix that.

I tested the walkthrough and I'm able to do so without issues. I see that you're on a supported build to preview prepend-on-send. Is your Outlook client on the Beta Channel option by any chance?

The add-in project I created for testing already had the commands.js file in src/commands. The project was created with Yeoman generator per the quick start. Out of curiosity, if you run `npm install -g yo generator-office`, then create a test Outlook add-in project, is the commands.js file still missing?

**Comment by samantharamon** [comment]
Thanks for the feedback! I'll add that as a change as well.

If you haven't already, could you remove the sideloaded add-in from Outlook, [clear the cache](https://learn.microsoft.com/office/dev/add-ins/testing/clear-cache#manually-clear-the-cache-in-outlook), then restart your computer? If the prepend-on-send and append-on-send features still don't work, try creating a new add-in project using yo office.

**Comment by elegault** [comment]
@samantharamon To be clear, I didn't create this project from Yeoman. I created everything manually and tested directly from the deployment of the source code to GitHub Pages. I don't know why it is working for you, but I can reproduce it not working on a second PC:

![image](https://user-images.githubusercontent.com/4130365/226745180-c71cf5d2-b687-4354-b2ac-2e4930b106ea.png)

**Comment by samantharamon** [comment]
Thanks for clarifying. I previously tested through a Yeoman-generated project. This time around, I tested your project hosted on GitHub Pages and I'm able to replicate the issue. When you get a chance, could you try adding the `Office.onReady()` call to the top of your `commands.js` file? I replicated your project and after adding the `onReady` call, I was able to prepend and append content on send.
