### ISSUE TITLE
Can't find variable: callServerAPI

### ISSUE THREAD

**Issue by koenvw** [OfficeDev/office-js-docs-pr#3953]
There is small error in the code sample

`const jsonResponse = await callServerAPI('GET', '/getuserfilenames');`

should be

`const jsonResponse = await callWebServerAPI('GET', '/getuserfilenames');`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c51a742c-4ddb-dd5e-7f67-3242a158378a
* Version Independent ID: b5d96164-bec6-7732-79ad-8c6beef7e0c4
* Content: [Create a Node.js Office Add-in that uses single sign-on - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/create-sso-office-add-ins-nodejs)
* Content Source: [docs/develop/create-sso-office-add-ins-nodejs.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/develop/create-sso-office-add-ins-nodejs.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@koenvw Thanks for letting us know about this.

@davidchesnut Can you take a look?

Thanks.

**Comment by Rick-Kirkham** [comment]
The fixed version will be published late tomorrow in the Pacific USA time zone.
