### ISSUE TITLE
Can't see extension point of type "module"

### ISSUE THREAD

**Issue by JulienPoly** [OfficeDev/office-js-docs-pr#3969]
Hello.

I'm trying to test an module extension point but when I load the manifest I can't see it in the ribbon.
Maybe I'm doing something wrong ?

Here is the sample of my manifest
![image](https://user-images.githubusercontent.com/130761066/233324642-8cec962c-a7f9-49cf-bc14-60e9c2b41ce1.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 34ce721e-c5cd-fe54-38e1-d86085f1e036
* Version Independent ID: 0b5a9711-cb17-bc27-e189-44605656a1ab
* Content: [Module extension Outlook add-ins - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/extension-module-outlook-add-ins)
* Content Source: [docs/outlook/extension-module-outlook-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/outlook/extension-module-outlook-add-ins.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
Several thoughts: 

1. The button for an Outlook module is not supposed to appear on the ribbon. It appears on the Outlook navigation bar, as in this example:
![image](https://user-images.githubusercontent.com/9088056/233475164-66c4e8c9-9b80-43a2-81a7-7e9e4f068cd0.png)

    Please check to see if it is showing up there. 

2. You don't include the `<Resources>` part of your manifest. Problems are often the result of a mismatch in the spelling of "resid"s between the `<Resources>` section where the "resid"s are defined and the sections where the "resid"s are used. Check for that.

3. I suspect that you cannot have a `<Action>` type of `ShowTaskpane` in a module. A ShowTaskpane button opens an embedded browser-like webview on the right side of Outlook. But a module is itself an embedded webview. What would be the point of opening a second webview control inside another webview control? 

4. Are you sure that you want to create an Outlook module? Now that custom Teams tabs can be installed and launched in Outlook, you can provide a virtually identical user experience with a custom tab. For details, see [Extend a Teams personal tab across Microsoft 365 app](https://learn.microsoft.com/microsoftteams/platform/m365-apps/extend-m365-teams-personal-tab), especially the section [Preview your personal tab in other Microsoft 365 experiences](https://learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/extend-m365-teams-personal-tab#preview-your-personal-tab-in-other-microsoft-365-experiences). (Note the screenshots in that section: the tab's button appears on the Outlook navigation pane exactly as it would in an Outlook module.)  Also, the module extension point has seldom been used and it is not supported in the new [unified Microsoft 365 manifest](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/json-manifest-overview) for Outlook add-ins. That manifest is in preview right now, but it will be released in the next few months and it will be the recommended way to create Outlook add-ins. The current XML manifest for Outlook add-ins, and consequently Outlook modules, will still work but will be deprecated.

**Comment by JulienPoly** [comment]
Ok thanks for the answer.
So I'll try with a Teams Tab.
Another thing: is it possible to auto open a task pane with event based activation. I manage to trigger a function but I wish to open a taskpane. How can I do this?

**Comment by Rick-Kirkham** [comment]
There is an `Office.addin.showAsTaskpane()` method. Unfortunately, you can't call it in a launch.js file for an event-based Outlook add-in because it requires using a Shared Runtime and Outlook doesn't support shared runtimes. 

This repo is intended to track problems with the documentation, so I will close this issue.

**Comment by JulienPoly** [comment]
Ok thank you Rick
