### ISSUE TITLE
Incomplete information

### ISSUE THREAD

**Issue by bollaking** [OfficeDev/office-js-docs-pr#3972]
This xml snippet is not very helpful
```
<Action xsi:type="ShowTaskpane">
    <TaskpaneId>Office.AutoShowTaskpaneWithDocument</TaskpaneId>
    <SourceLocation resid="Contoso.Taskpane.Url" />
</Action>
```
Where in the manifest should it be placed. I have tried a number of places and always end up with an invalid manifest file.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: eb729902-e88a-02f7-2f4c-7c5f86a3e87a
* Version Independent ID: d6aab83f-2c52-8517-bc78-3189feb9e361
* Content: [Automatically open a task pane with a document - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/automatically-open-a-task-pane-with-a-document)
* Content Source: [docs/develop/automatically-open-a-task-pane-with-a-document.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/develop/automatically-open-a-task-pane-with-a-document.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
See this article: [Find the proper order of elements](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/manifest-element-ordering).
