### ISSUE TITLE
Debugging client side code using new Outlook One

### ISSUE THREAD

**Issue by carlosb1504** [OfficeDev/office-js-docs-pr#3974]
Debugging client side code using new Outlook One client doesn't seem to be mentioned.

Cannot use usual F12 method from Taskpane to access Chromium Dev Tools. Presume there is some setting somewhere to enable this, can you advise where this is and update docs accordingly please?

Cheers

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fc051b98-1aaa-20ad-b740-6ac4d377529e
* Version Independent ID: fc051b98-1aaa-20ad-b740-6ac4d377529e
* Content: [Debug Office Add-ins - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/testing/debug-add-ins-overview)
* Content Source: [docs/testing/debug-add-ins-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/testing/debug-add-ins-overview.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @carlosb1504,

Thanks for reporting this issue. @samantharamon, could you plese investigate this?

**Comment by samantharamon** [comment]
Hi @carlosb1504,

Thanks for reaching out about this. I'll follow up on this with the team and will get back to you once I learn more.

**Comment by samantharamon** [comment]
Thanks for your patience, @carlosb1504. The team is currently exploring solutions to debug add-ins in the new Outlook on Windows client. As a workaround for now, please [sideload your add-in in Outlook on the web](https://learn.microsoft.com/office/dev/add-ins/outlook/sideload-outlook-add-ins-for-testing) and follow the debugging guidance in [Debug add-ins in Office on the web](https://learn.microsoft.com/office/dev/add-ins/testing/debug-add-ins-in-office-online). We'll update our documentation to reflect this.
