### ISSUE TITLE
Configure the add-in for Vorlon.JS debugging point 3 not clear.

### ISSUE THREAD

**Issue by edlgg** [OfficeDev/office-js-docs-pr#398]
In 'Configure the add-in for Vorlon.JS debugging' point 3 I'm not sure what URL you refer to "https://localhost:1337/vorlon.js" or the URL I'm hosting my add-in on which during development would be "https://localhost:8080".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be179784-5839-3e8f-c131-1f4d89808b03
* Version Independent ID: 69bca101-91a2-3a5e-5177-493723504354
* Content: [Debug Office Add-ins on iPad and Mac](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-office-add-ins-on-ipad-and-mac)
* Content Source: [docs/testing/debug-office-add-ins-on-ipad-and-mac.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/debug-office-add-ins-on-ipad-and-mac.md)
* Product: **office 365**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
Its the URL of the add-in. In your case, https://localhost:8080.
