### ISSUE TITLE
Should the docs teep recommending Script Lab?

### ISSUE THREAD

**Issue by jimfoye** [OfficeDev/office-js-docs-pr#3988]
In my quest to become an "Office.js" developer, using the Script Lab tool recommended by the docs seemed like a good idea. I couldn't even download the thing. It looks to me (and some other reviewers) to be more MS Abandonware. Either MS should update it and address reviewer issues, or else remove it from the Internet (and these docs).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ee989528-eeae-f8f7-cfd8-f57b48b25061
* Version Independent ID: ea8e6b17-15e1-94bf-eee9-e63ddabe0d1b
* Content: [Beginner's guide to Office Add-ins - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/overview/learning-path-beginner)
* Content Source: [docs/overview/learning-path-beginner.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/overview/learning-path-beginner.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by yjoshi-msft** [comment]
Hi Jimfoye,
Sorry for the inconvenience. Could you share screen recording or screenshots of the issue so we can understand it better?

**Comment by AlexJerabek** [comment]
Hi @jimfoye,

Sorry to hear you're having issues getting Script Lab to work. Like @yjoshi-msft, a more detailed description of the errors will help. We could also use the application (Excel, Word, etc) and build number you are working with.

As for the state of Script Lab, Script Lab is in maintenance mode. We believe it's in a stable state where it is a great prototyping tool, but we are not investing in expanding it. We will still fix critical bugs, as appropriate. We are continuing to make samples for Script Lab that showcase new Office.js features.

**Comment by jimfoye** [comment]
@yjoshi-msft 

I attempted to download it from the page linked to by the docs:

https://appsource.microsoft.com/en-US/product/office/WA104380862?exp=ubp8

I clicked on the "Get it now" button, and it displayed a message, something like "Taking you to Office 365 to complete the process" and went to

https://admin.microsoft.com/Adminportal/Home#/Settings/IntegratedApps/:/Redirect/Store/WA104380862/en-US

And from there redirected to a GoDaddy Page (GoDaddy manages this particular Office 365 login that I was using). This is what that page looks like:

![image](https://user-images.githubusercontent.com/4249676/235754400-ddca5310-200d-4bd3-bce9-fe44350dc18c.png)

Clearly, I am not going to be able to download it from that page.

**Comment by jimfoye** [comment]
@AlexJerabek My impression that the tool was abandoned was based on three things.

1. The last release 12/2019, almost 3 1/2 years ago.
2. A number of negative reviews about the tool that have apparently not been addressed (I won't repeat these here, you can read through them on the download page link I posted above).
3. My own inability to even download the product.

To the above I will add, this morning I went to the GitHub page, and I see 143 open issues going back many years, which I don't take as a good sign.

Feel free to close this issue, thanks.

**Comment by AlexJerabek** [comment]
Thanks @jimfoye. Are you also unable to download Script Lab through the **Insert** > **Get Add-ins** option?

![image](https://user-images.githubusercontent.com/38896772/235769118-2ddb3a55-9c5a-4c1a-83b9-7c614b95f177.png)

I realize it's an unsatisfying response, but the links above worked fine for me. Is it possible your admin has blocked Office Add-ins? I'll tag @raulclouse to investigate further.

**Comment by jimfoye** [comment]
![image](https://user-images.githubusercontent.com/4249676/235774370-16e15a2a-c1ec-4548-8ced-e6e7ecbdbeb4.png)

I don't know why my boss would have add-ins disabled, it's a small company and I'm the only IT person. In fact, my main job function is to write add-ins for Excel (which I do with F# and Excel-Dna, currently). Clearly if that is the problem, the download page should handle that more gracefully (well, IMO, anyway).

**Comment by AlexJerabek** [comment]
Are you seeing a **Store** tab next to the **Admin Managed** list?

![image](https://user-images.githubusercontent.com/38896772/235790445-c9a943a7-f853-4c7b-841a-a6513f9ee0f4.png)

**Comment by jimfoye** [comment]
No, I'm missing the other three tabs from your screenshot.

**Comment by AlexJerabek** [comment]
Thanks @jimfoye. I think this might have something to do with GoDaddy-provided Office. Let me do some research internally.

As a workaround, you can get an M365 development tenant through the [Microsoft 365 Developer](https://developer.microsoft.com/en-us/microsoft-365/dev-program). There should be no problems getting and testing add-ins there.

**Comment by AlexJerabek** [comment]
Hi @jimfoye,

The GoDaddy SKUs of Office do not support the store or centrally deployed add-ins. The free developer program will be your best bet for add-in development work, including getting Script Lab, given your current situation.

**Comment by slabereemsft** [comment]
Hi @jimfoye,
You may also call GoDaddy support about this issue. You'll likely need to explain that you want to use features of Microsoft 365 that are not available through your GoDaddy administration. Specifically the Microsoft 365 Admin Center. They'll have a process for "de-federating the tenant" which should also unblock you.
