### ISSUE TITLE
The host name should not be based on already owned domain

### ISSUE THREAD

**Issue by chenxizhang** [OfficeDev/office-js-docs-pr#40]
The sample code (https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/create-sso-office-add-ins-aspnet.md)  is work correct. thank you

But the add-in should be deploy to production environment, not always localhost,. how to change the App Registration information? when I try to change the api registration info to "api://excelwebaddinsample.azurewebsites.net/f7e0154d-1258-42ef-9e89-9857889f4e01" , i got an error with message "The host name should not be based on already owned domain." and can not save this change. 

what can i do ? thank you

**Comment by Rick-Kirkham** [comment]
I'm researching this.

**Comment by chenxizhang** [comment]
is there anything update? @Rick-Kirkham  thank you

**Comment by Rick-Kirkham** [comment]
I'm in a conversation with the product team. Still don't have a definitive answer yet.

**Comment by Rick-Kirkham** [comment]
@chenxizhang 
The product team says they cannot reproduce the issue. They are asking for more information. Are you, by chance, an Microsoft employee working on PPE or are you external working with production Office 365? Could you give us the steps you take that lead up to the error message? Also, can you install the Fiddler tool and give us the fiddler trace of the step that generates the error? Thanks.

**Comment by Rick-Kirkham** [comment]
I can reproduce your error, but the product team says they cannot. I'm still working with them.

**Comment by Rick-Kirkham** [comment]
@chenxizhang 
The product team believes that you are getting this error because your application is configured to be multitenant. SSO is not supported for multitenant apps. If you turn off support for multitenancy, then you should be able to register "api://excelwebaddinsample.azurewebsites.net/f7e0154d-1258-42ef-9e89-9857889f4e01". Also, they suggested that part of this article https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-devhowto-multi-tenant-overview might be helpful, especially the paragraph that begins "Also note, before an application ..." about verified domains.

**Comment by chenxizhang** [comment]
@Rick-Kirkham 
thank you for your help

**Comment by iliev-ilian** [comment]
@Rick-Kirkham 
I have the same problem registering app in https://apps.dev.microsoft.com. When i register the app with localhost it works, but when add the url to be in azure - it does not work: "The host name should not be based on already owned domain." I am also using SSO.

How could I change the app not to be multitenant? I have found this article https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-devhowto-multi-tenant-overview but in Azure I don't the apps registered in https://apps.dev.microsoft.com. How are they related? Could you give more information regarding this subject.

Thank you

**Comment by Rick-Kirkham** [comment]
@iliev-ilian  and @chenxizhang 
It looks like this setting is not surfaced in the UI on https://apps.dev.microsoft.com. 
Go to the registration page for your add-in's web application. 
Scroll down to the botton and click the button to edit the manifest. 
Near the bottom of the manifest there is a "tags" property. One subproperty is "availableToOtherTenants". I *think* (but I'm not sure) that this is the relevant setting. It looks like it defaults to "true", which does no harm when you are working on localhost; but causes the error about "already owned domain" on any other domain. 
Please try setting this value to "false" and then save the manifest. 
See if that fixes the issue. 
PLEASE REPORT BACK HERE THE OUTCOME. If it works, I will add this to the documentation.

**Comment by iliev-ilian** [comment]
@Rick-Kirkham 
It still does not work.
I am changing this property in tags to false, saving the manifest - the manifest is saved. And then I change the Application ID URI of the Web API to app in azure, but still get this error.

Do you have any other suggestions?

**Comment by Rick-Kirkham** [comment]
I'm trying to get some help from the product team.

**Comment by TimMcMSFT** [comment]
AzureWebsites.net addresses cannot be used in Azure AD today, since you cannot prove ownership. You will need to host your add-in on a different domain.

**Comment by tuandomvn** [comment]
I got the same problem and I resolved by adding a custom domain pointing to your AzureWebiste.

**Comment by chenxizhang** [comment]
@Rick-Kirkham  @TimMcMSFT 
Hi team
I found this issue still there. I've add a custom domain name to my app service site,but it looks not work for me. 

![1](https://user-images.githubusercontent.com/1996954/44634770-b46af400-a9d0-11e8-93e5-c154b6c81918.png)
![2](https://user-images.githubusercontent.com/1996954/44634772-b46af400-a9d0-11e8-92c0-306a062c94f2.png)

**Comment by Rick-Kirkham** [comment]
@chenxizhang This seems to be a problem with the AAD registration system, not a problem with the documentation. Please create this issue on the repo [office-js](https://github.com/OfficeDev/office-js).

**Comment by chenxizhang** [comment]
Finally I got the solution and resolved this problem。**it must use the office 365 tenant administartor to register this app.**
