### ISSUE TITLE
com.Microsoft.OsfWebHost does not exist

### ISSUE THREAD

**Issue by mattblackdev** [OfficeDev/office-js-docs-pr#400]
Hi, the folder "com.Microsoft.OsfWebHost" does not seem to exist on my system:

macOS High Sierra 10.13.6 
Word for Mac 16.17

Word is no longer listing my sideloaded add-in in the drop down menu. When I run the office-toolbox utility to sideload a manifest, the Task Pane opens and says:

Add-in Error
This add-in is no longer available. If this add-in's manifest was removed, please restore it to its previous location and try again.

Can't seem to get around this issue so I will try reinstalling Office.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 589820d2-9925-dc5e-76a7-83921a569137
* Version Independent ID: ab8bde36-096f-81f3-f4d1-9b25fc69e6ee
* Content: [Sideload Office Add-ins on iPad and Mac for testing](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/sideload-an-office-add-in-on-ipad-and-mac)
* Content Source: [docs/testing/sideload-an-office-add-in-on-ipad-and-mac.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/sideload-an-office-add-in-on-ipad-and-mac.md)
* Product: **office 365**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
Does the parent folder **Containers** have any child folders at all? I wonder if someone was trying to clear the cache (see the Note at the bottom of the article) and they unintentionally deleted the whole. com.Microsoft.OsfWebHost folder. At any rate, this doesn't seem to be a problem with the article itself, so I will close this.
