### ISSUE TITLE
yo office isn't installing webpack.config.js

### ISSUE THREAD

**Issue by onetalltree** [OfficeDev/office-js-docs-pr#4001]
I followed the instructions.

- "npm start" generated the error:
  - "'office-addin-debugging' is not recognized as an internal or external command, operable program or batch file."
  - did "npm install" to fix that

- doing "npm start" throws new errors
  - Realized that there is no webpack.config.js file 
  - found it at: https://github.com/OfficeDev/Office-Addin-TaskPane-JS/blob/master/webpack.config.js
  -  downloaded webpack.config.js and placed it in the root of my addin project. 
  - Now it works.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ac7d9e2d-b537-cf1f-95fb-4e216514f3b1
* Version Independent ID: 4a86c93b-70d8-38e4-f62e-83c43a0158dd
* Content: [Excel add-in tutorial - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/tutorials/excel-tutorial)
* Content Source: [docs/tutorials/excel-tutorial.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/tutorials/excel-tutorial.md)
* Service: **excel**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by donlvMSFT** [comment]
Hi @onetalltree , thanks for reaching out to us. 
Did you do `npm install`? That would help introduce some libs to your project.
