### ISSUE TITLE
Bad documentation with Debugging the Add-on

### ISSUE THREAD

**Issue by geneLavender** [OfficeDev/office-js-docs-pr#4007]
I'm trying to debug an Add-in for Outlook on Windows.
The below documentation talks about a "bundle.js" which needs clarification.

https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/autolaunch?tabs=xmlmanifest#supported-events

**"bundle.js"**
Where does this come from?
Who creates it? 
Where is it download from and which directory?

"What I'm trying to do"
I'm using the sample code in the documentation to create a OnMessageSend Launch Event handler, but the sample code does not work. I would love to get some information on what is going on.

Because this is not on a task pane sidebar view, there is nothing for Edge browser inspect tool to view.

**Comment by Rick-Kirkham** [comment]
I have transferred this to the repo for documentation.

**Comment by samantharamon** [comment]
Hi @geneLavender,

Thanks for reaching out. The `bundle.js` file is created when you use the [Yeoman generator](https://learn.microsoft.com/office/dev/add-ins/develop/yeoman-generator-overview) (`yo office`) to create your add-in project. Yo office uses [webpack](https://webpack.js.org/) to take care of mapping file dependencies and bundling assets in your add-in project. The `bundle.js` file is created in `%LOCALAPPDATA%\Microsoft\Office\16.0\Wef\{[Outlook profile GUID]}\[Outlook mail account encoding]\Javascript\[Add-in ID]_[Add-in Version]_[locale]` when you run `npm run build` or `npm start` (runs `npm run build` as part of its script).

For guidance with debugging your event-based add-in, please refer to the following to enable runtime logging and set breakpoints in your code:
- [Debug your add-in with runtime logging](https://learn.microsoft.com/office/dev/add-ins/testing/runtime-logging)
- [Debug your event-based Outlook add-in](https://learn.microsoft.com/office/dev/add-ins/outlook/debug-autolaunch?tabs=windows)
