### ISSUE TITLE
How to select grouping row position (e.g. top/bottom)

### ISSUE THREAD

**Issue by theboyknowsclass** [OfficeDev/office-js-docs-pr#4012]
Excel (desktop) has the options here -> 

![image](https://github.com/OfficeDev/office-js-docs-pr/assets/2139941/74d90add-69f3-49f9-a659-883068b485c7)

is there an API to adjust whether the 'group' row for an outline is at the top / bottom.   (or left / right for columns)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 41e591a0-df66-2f91-6193-1d58360e1bd4
* Version Independent ID: 9e63a375-acbb-4824-652a-43873d736ec4
* Content: [Group ranges using the Excel JavaScript API - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-ranges-group)
* Content Source: [docs/excel/excel-add-ins-ranges-group.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/excel/excel-add-ins-ranges-group.md)
* Service: **excel**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@theboyknowsclass Thanks for letting us know about this.

@alison-mk Can you take a look? Or reassign/move as appropriate?

Thanks.

**Comment by Rick-Kirkham** [comment]
@theboyknowsclass I'm afraid that there is no way to programmatically specify where the summary rows and columns appear. But it is a good idea. You can suggest it at [M365 Developer Platform Ideas](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform). 

I'll close this issue for now, but you can still comment and we will see it.
