### ISSUE TITLE
Step 1: Begin with fundamentals

### ISSUE THREAD

**Issue by edthehorse** [OfficeDev/office-js-docs-pr#4021]
I think its called a tautism

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ee989528-eeae-f8f7-cfd8-f57b48b25061
* Version Independent ID: ea8e6b17-15e1-94bf-eee9-e63ddabe0d1b
* Content: [Beginner's guide to Office Add-ins - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/overview/learning-path-beginner?view=excel-js-1.17)
* Content Source: [docs/overview/learning-path-beginner.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/overview/learning-path-beginner.md)
* Service: **microsoft-365**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
Thanks for your interest in Office Add-ins. I believe the word that you are thinking of is "tautology". I don't believe that section title is a tautology. As the text of the section indicates, some people begin by jumping into coding before they've learned the fundamentals. So, it is not tautologous to tell readers that they should not do that.
