### ISSUE TITLE
Excellent

### ISSUE THREAD

**Issue by edthehorse** [OfficeDev/office-js-docs-pr#4024]
This should be more significant as a Starting point for beginners

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 52542c44-015a-746d-5d6f-c43f6e4e6774
* Version Independent ID: dfe8c9fb-4107-e19b-972a-c5a58eeb2646
* Content: [Work with Events using the Excel JavaScript API - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-events)
* Content Source: [docs/excel/excel-add-ins-events.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/excel/excel-add-ins-events.md)
* Service: **excel**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
Thanks for the suggestion. I will make a work item to investigate whether we can work a link to this article into our getting started/beginners documentation.
