### ISSUE TITLE
Outdated VS Code Launch Configuration in "Debug your event-based Outlook add-in" article?

### ISSUE THREAD

**Issue by urig** [OfficeDev/office-js-docs-pr#4035]
## Article URL
https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/debug-autolaunch

## Issue
There seem to be two issues in the Visual Studio Code launch configuration specified in the article. 

The code snippet as copied from the article verbatim is:

```
{
  "name": "Direct Debugging",
  "type": "node",
  "request": "attach",
  "port": 9223,
  "protocol": "inspector",
  "timeout": 600000,
  "trace": true
}
```

Issue 1 - The code contains "invisible" `U+202f` where a single space character is expected.

![Screenshot of the above launch configuration code with a warning overlaid by Visual Studio Code. The warning says "The character U+202f is invisible"](https://github.com/OfficeDev/office-js-docs-pr/assets/350687/671c9040-ed0f-4afa-97a4-d5f8063bb17d)

Issue 2 - Visual Studio Code (v1.78.2) displays a warning that the "protocol" property is not allowed.

![Screenshot of the above launch configuration code with a warning overlaid by Visual Studio Code. The warning says "Property protocol is not allowed".](https://github.com/OfficeDev/office-js-docs-pr/assets/350687/924e3c64-c086-4fe1-8e03-099c5fa0afc6)
 
As a possible result, I am unable to perform step-by-step debugging when following the instructions in the article. Even after replacing the invisible characters with proper space characters, and following the instructions in the article carefully, I find that VS Code will not break on breakpoints set in event action handler code. I've elaborated on this in a [StackOverflow question](https://stackoverflow.com/questions/76351926/what-is-the-right-launch-configuration-to-debug-an-event-based-outlook-add-in).

If I understand correctly, the protocol property has been deprecated in Visual Studio Code launch configurations. It might me advisable to update the article so that it provides a current launch configuration.

**Comment by Rick-Kirkham** [comment]
It looks like someone is working with you on StackOverflow for the basic debugging problem. For the "inspector" question, I'll ask @samantharamon to investigate. It may be an obsolete property or value.

**Comment by samantharamon** [comment]
Hi @urig,

Thanks for reporting these issues. I'll update the article to address the first issue. Regarding the second issue, I'm investigating this further to determine whether we can remove this property from the article. I created an add-in using the [Smart Alerts walkthrough](https://learn.microsoft.com/office/dev/add-ins/outlook/smart-alerts-onmessagesend-walkthrough) and was able to hit the set breakpoints even with the `protocol` property declared. What Outlook version is your client on?
