### ISSUE TITLE
There were deployment errors. Continue?

### ISSUE THREAD

**Issue by RichardD2** [OfficeDev/office-js-docs-pr#4036]
Followed the Visual Studio instructions from this page to the letter. The only difference is that I'm using VS2022 rather than VS2019.

Running the project results in a "401 Unauthorized" error, because we have 2FA enabled.

After changing the "use multi-factor auth" property to "true", I sign in using my Office365 account. Visual Studio then displays "There were deployment errors. Continue?"

![image](https://github.com/OfficeDev/office-js-docs-pr/assets/2158265/c2de7849-541e-46a2-adea-7e2d5e02b940)

There is no information in the output window. There are no logs. There is no way to diagnose what these "deployment errors" are or how to fix them.

Is this "getting started" tutorial incorrect or incomplete? Or is it really not possible to develop add-ins for Microsoft Office using Microsoft's developer tools?!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 930ce4fc-c8b8-f756-f03f-a716f1ef7883
* Version Independent ID: 753a2e38-9430-25bb-5409-b7eed9c88e47
* Content: [Build your first Outlook add-in - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/quickstarts/outlook-quickstart?tabs=yeomangenerator)
* Content Source: [docs/quickstarts/outlook-quickstart.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/quickstarts/outlook-quickstart.md)
* Service: **outlook**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
@samantharamon Could you take a look and see if you can reproduce or diagnose?

**Comment by samantharamon** [comment]
Hi @RichardD2,

I'm sorry to hear you're experiencing issues while testing the Outlook quick start. I followed the steps you took, i.e., pressed F5, received the 401 error, then set the "Use multi-factor auth" property to True. I was able to replicate the deployment errors dialog you received. It looks like it appears after you close the 401 error dialog. It appeared immediately for me, but it may have taken some time to appear on your end. When it appeared, I selected **No**, then configured the "Use multi-factor auth" accordingly. I was able to sign in to my account and run the add-in from there.

When you get a chance, please restart Visual Studio, then try running your project again after ensuring that "Use multi-factor auth" is set to True. Let us know if you still continue to receive the deployment error dialog.

**Comment by samantharamon** [comment]
That could be causing the error you're seeing. On my end, the Start Action option is set to Microsoft Edge. It may be an issue with Visual Studio itself, and not your add-in project, so please try [repairing Visual Studio](https://learn.microsoft.com/visualstudio/install/repair-visual-studio?view=vs-2022) to see if that resolves the error.

**Comment by samantharamon** [comment]
Here are a few other things you could try.
- I believe it's an issue with the Visual Studio client, but just to be sure, could you close any projects you have open in Visual Studio, then create a new add-in project using the same tutorial to see if the issue persists?
- If creating a new project doesn't remedy the issue, try the following to [uninstall and reinstall](https://learn.microsoft.com/visualstudio/install/modify-visual-studio?view=vs-2022) the ASP.NET and web development components.
  1. In Visual Studio, select **Tools** > **Get Tools and Features**.
  2. Select the **Workloads** tab.
  3. If the checkbox for **ASP.NET and web development** isn't selected, select it, then select **Modify**. If it's selected, uncheck the box, then select **Modify** to uninstall the components.
  4. The modification may restart Visual Studio or may prompt you to manually restart it. Once restarted, select **Tools** > **Get Tools and Features**.
  5. In the **Workloads** tab, check the box for **ASP.NET and web development**. Then, select **Modify** to reinstall the components. Visual Studio may restart or prompt you to restart after the installation.
- In **Tools** > **Get Tools and Features**, ensure that **Office/SharePoint development** is checked.
- [Install any Visual Studio updates](https://learn.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2022).
- [Install any extension updates](https://learn.microsoft.com/visualstudio/extensibility/how-to-update-a-visual-studio-extension?view=vs-2022).
