### ISSUE TITLE
Parameter address format isn't well specified.

### ISSUE THREAD

**Issue by parched** [OfficeDev/office-js-docs-pr#4050]
I want to know if a custom function argument is actually 0 or just refers to a blank cell, so I'm using `parameterAddresses` to read the actual cell that an argument refers to. The docs say
> When a custom function calling the `parameterAddresses` property runs, the parameter address is returned following the format `SheetName!RelativeCellAddress`

This made me think I could do this:
```
const [sheet, address] = address.split('!');
const range = context.workbook.worksheets.getItem(sheet).getRange(address);
```
But, that failed on a sheet called `Something&Something`. I observed that parameter address was of the form `'Something&Something'!A1`. So, now I'm using code like this
```
/**
 * Parse an address of the form 'Sheet1'!A1 into a sheet name and cell address
 */
export function parseAddress(address: string): [string, string] {
  const match = address.match(/^'?((?:[^']|'')*)'?!(.*)$/);
  if (!match) throw new Error(`Invalid address ${address}`);
  return [match[1].replace(/''/g, "'"), match[2]];
}
```
I would like to know if this is correct and will work for any possible parameter address.
The docs don't explicitly specify the format, so I've raised the issue first, but if this a actually an Excel bug, please move the issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 17035fc0-ca69-03f2-fe37-8189ff870cc7
* Version Independent ID: 2d43e719-043b-7a62-04bb-66b2cce7bf1d
* Content: [Options for Excel custom functions - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-parameter-options?tabs=javascript)
* Content Source: [docs/excel/custom-functions-parameter-options.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/excel/custom-functions-parameter-options.md)
* Service: **excel**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by parched** [comment]
FWIW, I'm using this now
```
/**
 * Parse an address of the form 'Sheet1'!A1 into a sheet name and cell address
 */
export function parseAddress(address: string): [string, string] {
  const match = address.match(/^'?((?:[^']|'')*)'?!(.*)$/);
  if (!match) throw new Error(`Invalid address ${address}`);
  return [match[1].replace(/''/g, "'"), match[2]];
}
```

**Comment by davidchesnut** [comment]
I apologize for the late response as I am out of the office for a few weeks. @alison-mk would you be able to help here? Thanks!

**Comment by Rick-Kirkham** [comment]
@parched , I can't reproduce the issue. When I run the code sample just above the passage from the article that you quote, the sheet names are not in single quotation marks. I'm working with Excel on Windows. Please try that same function and see if you get the same results.

![image](https://github.com/OfficeDev/office-js-docs-pr/assets/9088056/75f16584-f364-426e-9fe3-06164a653527)

**Comment by parched** [comment]
Hi @Rick-Kirkham, try with some special characters in the sheet name like `hi!` or `can't`.

**Comment by parched** [comment]
@Rick-Kirkham Fair call, I hate it when my users raise issues without specifying the problem they're actually trying to solve, but I just did it to you! I've updated it now.

**Comment by parched** [comment]
Thinking further, the best outcome for me would be that, instead of giving 0 for blank cell, `null` was given instead (when the parameter type is `any`).  That would also make my custom functions as they wouldn't need to call back into Excel, and I wouldn't need to workaround https://github.com/OfficeDev/office-js/issues/2874

**Comment by Rick-Kirkham** [comment]
@parched Thanks. I'll clarify the documentation. Should be published by next Wednesday. In the meantime, if the worksheet name includes any of these characters, then the worksheet name part of the returned value (the part to the left of the "!") will be enclosed in single quotation marks. 

 ~ ` ! @ # $ % ^ & ( ) - _ = + { } | ; : , < . >

**Comment by parched** [comment]
Thanks @Rick-Kirkham. It looks like you missed the situation when the sheet name contains a single quote. I observe that they're replaced with two single quotes.

**Comment by Rick-Kirkham** [comment]
@parched Thanks. I'll add that to the article.
