### ISSUE TITLE
Wrong information

### ISSUE THREAD

**Issue by thoffmann-fms** [OfficeDev/office-js-docs-pr#4060]
The "Attach the debugger" section is wrong.  There is no bundle.js file. `npm run build` generates the application in the "dist" (usually) directory.  The Wef directory is not touched by the npm process.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 62a7c8c2-c855-dbcb-8858-4aa616a59a27
* Version Independent ID: c74d3973-0cdc-80b2-c6e1-2542b1be96c3
* Content: [Debug your event-based Outlook add-in - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/debug-autolaunch?tabs=windows)
* Content Source: [docs/outlook/debug-autolaunch.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/outlook/debug-autolaunch.md)
* Service: **outlook**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
@samantharamon Please take a look.

**Comment by samantharamon** [comment]
Hi @thoffmann-fms,

Thank you for catching this. We're correcting this information in #4074. This issue will automatically close once the changes are merged. Please don't hesitate to reach out if you have any feedback on the change.
