### ISSUE TITLE
Add note clearly indicating that SSO auth does not work in Word for Microsoft Teams (desktop client)

### ISSUE THREAD

**Issue by VelinGeorgiev** [OfficeDev/office-js-docs-pr#4087]
Based on this issue [https://github.com/OfficeDev/office-js/issues/3291](https://github.com/OfficeDev/office-js/issues/3291) there must be a clear note (in RED) indicating that SSO does not work with Word in Microsoft Teams.

When  I am solutioning for clients I heavily rely on proper documentation and notes. For the past month we solution an add-in based on the assumption from the [official SSO documents](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/sso-in-office-add-ins) that it works cross platform (Office online, Word Desktop, Microsoft Teams) until we have to find ourselves it does not.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cb06c24b-9d11-9cc5-2e98-561601452638
* Version Independent ID: abda21d9-6e80-8319-c56f-004658014e3c
* Content: [Enable single sign-on (SSO) in an Office Add-in - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/sso-in-office-add-ins)
* Content Source: [docs/develop/sso-in-office-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/develop/sso-in-office-add-ins.md)
* Service: **microsoft-365**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by VelinGeorgiev** [comment]
@catmanjan if you ask me, I don't know :) . I am seeking for the same answer as you.

**Comment by Rick-Kirkham** [comment]
@VelinGeorgiev and @catmanjan , Thanks for bringing this to our attention. I apologize for the poor internal communication in Microsoft about the lack of support for `getAccessToken` when the Office application is opened with **Edit in Teams**. I will get the documentation updated to reflect this today.
