### ISSUE TITLE
Update docs in "Errors from displayDialogAsync" section

### ISSUE THREAD

**Issue by ATrogolo** [OfficeDev/office-js-docs-pr#409]
This line of code is out of date: 
`if (asyncResult.status === "failed")`

The updated procedure is: 
`if (result.status === Office.AsyncResultStatus.Failed) `

Please update docs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a714626a-058a-789e-6add-5e9dfb21fd1f
* Version Independent ID: 1b88a28c-fc36-4518-2808-7246f08d9753
* Content: [Use the Dialog API in your Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins)
* Content Source: [docs/develop/dialog-api-in-office-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/dialog-api-in-office-add-ins.md)
* Product: **office 365**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by kbrandl** [comment]
@ATrogolo thank you for reporting this issue. I've applied the change to this article (and to another article where the same issue was present) and you should see it reflected in the live docs sometime in the next couple of days (whenever the doc set gets republished). Thanks again!
