### ISSUE TITLE
Organising functions

### ISSUE THREAD

**Issue by SpicerSolutions** [OfficeDev/office-js-docs-pr#4094]
The documentation doesn't appear to cover how a developer might go about organising their functions into separate files that functions.js can then import/require.

Is this functionality supported? Otherwise, it seems like a functions file would get very large and difficult to maintain.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 94ad7803-d4f7-a700-7c7f-204cd8f34e4a
* Version Independent ID: 9c485bae-cab1-bdad-4c8e-baad2b12b22d
* Content: [Create custom functions in Excel - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-overview)
* Content Source: [docs/excel/custom-functions-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/excel/custom-functions-overview.md)
* Service: **excel**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
@SpicerSolutions We don't provide instructions for general programming tasks that transcend Office Add-ins, so we wouldn't provide information about how to organize source files unless there's reason to believe that the standard ways of doing so wouldn't work in an add-in. 

Did you try import/require statements? If so, did it not work?

**Comment by Rick-Kirkham** [comment]
OK. So, it's not the JavaScript bundle file that is missing the something, it's the autogenerated functions.json. Is that right? It might be that the tool that generates that file doesn't traverse. I'll research that internally. In the meantime, Excel custom functions can be made with a manually created functions.json file; you don't have to autogenerate it. See [Manually create JSON metadata for custom functions](https://learn.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-json). Why don't you try that and report back whether it works.

**Comment by Rick-Kirkham** [comment]
@SpicerSolutions I haven't got this 100% nailed down yet, but I'm 99% sure that we added support for multiple function files to the CustomFunctionsMetadataPlugin for WebPack last March, but that didn't get noted in our documentation for some reason. The "input" property of the plugin can now take an array of path strings like this: 

```
plugins: [
  new CustomFunctionsMetadataPlugin({
    output: 'functions.json',
    input: ['./src/functions/a.ts', './src/functions/b.ts],
  }),
```

You *may* have to also explicitly call out the additional source files in the "entry.functions" property of WebPack like in the following, but I *think* that WebPack would read the `import/require` statements and merge these addtional files into the bundle automatically, so this is probably not needed.

![image](https://github.com/OfficeDev/office-js-docs-pr/assets/9088056/942aa8a9-e6fe-4dab-bccf-64f9f6c38a8e)
