### ISSUE TITLE
reinstall sideloaded manifest.xml does not reflect changes

### ISSUE THREAD

**Issue by itsChris** [OfficeDev/office-js-docs-pr#4105]
i followed this tutorial on two different computers, both Win11 with the latest M365 Outlook installed. Yeoman is up-to-date. 
in the section:

### Reinstall the add-in

i implemented the changes, then i restart the webserver, then run _npm start_ . Outlook opens, but the implemented changes _do not appear_

maybe it would be helpful to write some troubleshooting section or if a troubleshooting section already exists, reference it. 

thanks!

Christian

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a59958d2-f428-9ca2-3440-a5af662386c0
* Version Independent ID: dcaf0b5b-08ea-c437-130b-342a1be62a16
* Content: [Tutorial: Build a message compose Outlook add-in - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/tutorials/outlook-tutorial)
* Content Source: [docs/tutorials/outlook-tutorial.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/tutorials/outlook-tutorial.md)
* Service: **outlook**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
@samantharamon Please take a look.

**Comment by samantharamon** [comment]
Hi @itsChris,

We're sorry to hear you're experiencing issues with the Outlook tutorial. I followed the tutorial until the "Reinstall the add-in" section and I was able to see the Git the gist button from the ribbon when I create a new message. Please note that the change may take a couple of seconds to replicate from when Outlook is opened. If you're still unable to see the changes after running `npm start`, please try the following:

1. If the local server is running, run `npm stop` from the root of your add-in project.
2. [Remove your add-in](https://learn.microsoft.com/office/dev/add-ins/outlook/sideload-outlook-add-ins-for-testing?tabs=windows#remove-a-sideloaded-add-in) from Outlook.
3. Close all instances of the Outlook client.
4. From the root of your add-in project, run `npm start'. This starts the localhost server and sideloads the add-in in Outlook.
5. When Outlook opens, wait a few seconds before creating a new message.

Let me know if this helps resolve the issue you're experiencing.

**Comment by itsChris** [comment]
Hi @samantharamon,

I apologize for any trouble and thank you so much for your help. I tried your suggestions and it seems to be working now. It appears that my developer system just needed a reboot. Really appreciate your prompt assistance on this issue.

Best,
Chris

**Comment by samantharamon** [comment]
No trouble at all, @itsChris! I'm glad it's now working for you. Should you require additional assistance, please don't hesitate to open another GitHub issue.
