### ISSUE TITLE
Trying to create an outlook plugin

### ISSUE THREAD

**Issue by virus2016** [OfficeDev/office-js-docs-pr#4117]
# Expected behavior

Outlook opens and I see the plugin

# Current behavior

Used Yo generator. Npm install then npm start. 

```

App type: desktop
The dev server is already running on port 3000.
Sideloading the Office Add-in...
Manifest package saved to /tmp/manifest.zip
running: npx @microsoft/teamsfx-cli@2.0.2-alpha.4f379e6ab.0 m365 sideloading --file-path /tmp/manifest.zip

Using account calum.macrae@medayo.com
Uploading package ...
Acquiring package ...
TitleId: U_870b656c-df83-c3e7-b18b-82c81bbbaf65
AppId: ab1f1cd3-0ca6-4040-ba20-4a69cebdcb0a
Sideloading done.

Successfully registered package! (U_870b656c-df83-c3e7-b18b-82c81bbbaf65)
 STDERR: (!) Warning: This command is in preview.


Error: Unable to start debugging.
Error: Unable to sideload the Office Add-in. 
Error: Sideload to the Outlook app is not supported.

```

## Steps to Reproduce

1. Use Yo office
2. Npm install
3. Npm start

* Operating System: Mac m1
* Node version: 18 lts
* Office version: new outlook

## Failure Logs

N/A

**Comment by Rick-Kirkham** [comment]
Reopening in the repo for documentation.

**Comment by virus2016** [comment]
Will it work with parallels?

**Comment by Rick-Kirkham** [comment]
I'm not familiar with that usage of "parallels". Could you explain?

**Comment by virus2016** [comment]
Also if I make a plugin, can users use it on the outlook mobile app

**Comment by Rick-Kirkham** [comment]
You can create an Outlook Add-in on a Mac with the standard XML manifest. Just take any of the Yo Office options, _except the one for the unified manifest_, which is in preview and is not yet supported on the Mac OS. We have not tested add-ins that use the unified manifest on parallels, so we don't know if that would work. In principle, an Outlook Add-in will run on Android and iOS, but some recent APIs added to the Outlook part of the Office JavaScript Library are not supported on iOS or Android. See [Outlook client support](https://review.learn.microsoft.com/en-us/javascript/api/requirement-sets/outlook/outlook-api-requirement-sets?branch=main&branchFallbackFrom=dup-legacy-metaos&view=word-js-preview&tabs=xmlmanifest#outlook-client-support).
