### ISSUE TITLE
Tutorial is not accurate?

### ISSUE THREAD

**Issue by glr0221** [OfficeDev/office-js-docs-pr#4128]
In your documentation, you mentioned the following : 

**_When you are prompted to upload the manifest file, use the file C:\Users\{your_user_name}\AppData\Local\Temp\manifest.xml._** 

There is no such file. Also running npm start does not install the manifest into outlook. It just creates manifest.zip inside the temp folder. 

It is either I am missing something or there is some disconnect in the docs.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 917e55ab-92cb-928b-2585-f9470038a86a
* Version Independent ID: 917e55ab-92cb-928b-2585-f9470038a86a
* Content: [Build an Outlook add-in with the unified manifest for Microsoft 365 (preview) - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/quickstarts/outlook-quickstart-json-manifest)
* Content Source: [docs/quickstarts/outlook-quickstart-json-manifest.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/quickstarts/outlook-quickstart-json-manifest.md)
* Service: **outlook**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@glr0221 Thanks for letting us know about this.

@Rick-Kirkham Can you take a look?

Thanks.

**Comment by Rick-Kirkham** [comment]
@glr0221 You are correct about the note. It should not be in this article. I will delete it and fix some other problems that I saw. 

However, I can't reproduce your problem with `npm start`. When I run it, it not only creates the manifest.zip, it also opens Outlook and sideloads the add-in. Loading add-ins is the last thing Outlook does when it starts up, so you should wait at least a couple of minutes to be sure Outlook has completely loaded.

**Comment by glr0221** [comment]
@Rick-Kirkham 

Thanks for the response. How long do we have to wait? I have run `npm start`, the webpack window pops up and compiles successfully and then outlook starts/opens. Once outlook is open, I open one of the emails for reading, and wait like 5 minutes but no `contoso addin` was found in the ribbons. Or do I have to wait more?

**Comment by Rick-Kirkham** [comment]
I've never had to wait more than 2 minutes. I haven't worked much with [runtime logging](https://learn.microsoft.com/office/dev/add-ins/testing/runtime-logging), but you might try that to see if you get an helpful information. 

It sounds like you are using a one-time purchase version of Office. Note this sentence from early in the article: "The preview is only supported in Office downloaded from a Microsoft 365 subscription and installed on Windows."

**Comment by glr0221** [comment]
Thank you @Rick-Kirkham .

I missed this line totally :  (a facepalm moment)

 _'The preview is only supported in Office downloaded from a Microsoft 365 subscription and installed on Windows.'_

Thank you so very much for taking a look at my outlook version. I will need to find a suitable environment to run this.
Thanks again.
