### ISSUE TITLE
Following instructions on sideloading office on the web results in error

### ISSUE THREAD

**Issue by justmars** [OfficeDev/office-js-docs-pr#4139]
## Article URL
https://learn.microsoft.com/en-us/office/dev/add-ins/testing/sideload-office-add-ins-for-testing#sideload-a-yeoman-created-add-in-to-office-on-the-web

## Issue

Steps:

1. Create yo office template Word, Javascript
2. Create new file on Office for the Web, copy link to url
3. Run `npm run start:web -- --document '{url}'` with single quotes results in:

    <img width="866" alt="Screenshot 2023-08-17 at 12 33 43 PM" src="https://github.com/OfficeDev/office-js-docs-pr/assets/39538958/a5f0af9f-b107-4d05-8604-0050665bec29">

4. Run `npm run start:web -- --document {url}` without single quotes on the url:

    <img width="389" alt="Screenshot 2023-08-17 at 12 36 23 PM" src="https://github.com/OfficeDev/office-js-docs-pr/assets/39538958/32ee3632-51f1-4924-870b-c78c552e5ddd">

**Comment by Rick-Kirkham** [comment]
@justmars Are you working on a Mac or a Windows computer? Also, are you able to manually sideload the add-in as described in [Manually sideload an add-in to Office on the web](https://learn.microsoft.com/en-us/office/dev/add-ins/testing/sideload-office-add-ins-for-testing#manually-sideload-an-add-in-to-office-on-the-web) ?

**Comment by justmars** [comment]
Hi @Rick-Kirkham , I'm working on a Mac

**Comment by Rick-Kirkham** [comment]
I've barely touched a Mac. I'm going to assign this to someone who works with them. I'm pretty sure this is not a documentation issue anyway.

**Comment by AlexJerabek** [comment]
This issue was likely resolved with #4141. If you're still encountering this problem, we can reopen this issue.
