### ISSUE TITLE
This is wrong example Host doesn't have child for runtime!

### ISSUE THREAD

**Issue by karayakar** [OfficeDev/office-js-docs-pr#4158]
https://learn.microsoft.com/en-us/javascript/api/manifest/launchevent?view=common-js-preview

![image](https://github.com/OfficeDev/office-js-docs-pr/assets/2394360/e8f6fca7-9223-4af6-a3c7-0d34d4b500d8)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 193780ba-aa43-dc5c-fc28-adc96a0fdeda
* Version Independent ID: da41da2b-207e-e976-3491-61672d1e3493
* Content: [Configure your Outlook add-in for event-based activation - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/autolaunch?tabs=xmlmanifest#supported-events)
* Content Source: [docs/outlook/autolaunch.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/outlook/autolaunch.md)
* Service: **outlook**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by David-Barrett-MS** [comment]
Are you using Visual Studio?  It seems that the xsd files shipped with Visual Studio 2022 (I tested up to version 17.6.3) are not up-to-date, and do not include support for event-based activation.

You can update the template as follows:

- Ensure Visual Studio is closed
- Obtain the latest xsd file from the [Exchange Protocol Documents](https://learn.microsoft.com/en-us/openspecs/office_file_formats/ms-owemxml/8e722c85-eb78-438c-94a4-edac7e9c533a) 
- Open Notepad or preferred text editor as Administrator
- Open file C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Xml\Schemas\1033\MailAppVersionOverridesV1_1.xsd
- Replace the contents of this file with the latest downloaded from the Protocol docs, then save
- Visual Studio will now be able to compile the sample [Event-based activation code](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/autolaunch)

**Comment by Rick-Kirkham** [comment]
Visual Studio 17.7 has up-to-date XSDs.
