### ISSUE TITLE
Yeoman method of developing add ins no longer supports debugging

### ISSUE THREAD

**Issue by andreas-deruiter** [OfficeDev/office-js-docs-pr#4175]
Debugging seems to be only supported anymore when developing with Visual Studio. Therefore, the method of using Yeoman is essentially useless.

## Article URL

https://learn.microsoft.com/en-us/office/dev/add-ins/quickstarts/powerpoint-quickstart?tabs=yeomangenerator

## Issue

Debugging an (PowerPoint) add In using Yeoman no longer seems to be supported by Microsoft. When following the steps outlined in the article, the created add in isn't enabled in PowerPoint after running `npm start'. Instead, the following message appears:

```
This add-in is no longer available: add-ins inserted during development are only available during debugging from Visual Studio. Please open your project in Visual Studio and re-run your application, or deploy your add-in into a valid catalog and re-insert.
```

Without the ability to debug your add in prior to submitting it to a catalig, the Yeoman method of developing add ins seems hardly useful anymore. At the very least, this limitation should be mentioned in the documentation.

<img width="690" alt="Screenshot 2023-09-18 122927" src="https://github.com/OfficeDev/office-js-docs-pr/assets/5530699/34e11fe5-41a1-4602-b90c-a1a1a9591ca5">

**Comment by ElizabethSamuel-MSFT** [comment]
@andreas-deruiter Thanks for asking about this.

@millerds Can you take a look?

Thanks.

**Comment by davidchesnut** [comment]
Hi @andreas-deruiter, I've ran into this error myself occasionally. I find [clearing the cache](https://learn.microsoft.com/office/dev/add-ins/testing/clear-cache) fixes it. Curious if that fixes the issue for you as well.

Cheers,
David
