### ISSUE TITLE
SupportsNoItemContext code examples should show diffs

### ISSUE THREAD

**Issue by unhammer** [OfficeDev/office-js-docs-pr#4176]
The code examples at https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/contextless expect the user to have just run through some outlook quick start example, making it hard to know how to use the feature in existing projects. It would be much more helpful if the code examples showed the *diff* required to enable the feature.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6c1ca1e3-adbb-5cb7-93fb-09b258a101b8
* Version Independent ID: 6c1ca1e3-adbb-5cb7-93fb-09b258a101b8
* Content: [Activate your Outlook add-in without the Reading Pane enabled or a message selected - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/contextless)
* Content Source: [docs/outlook/contextless.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/outlook/contextless.md)
* Service: **outlook**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@unhammer Thanks for letting us know about this.

@samantharamon Can you take a look?

Thanks.

**Comment by samantharamon** [comment]
Hi @unhammer,

Thanks for your feedback on this article.

Although the walkthrough uses the Outlook quick start as a base project, the key features needed are highlighted in the 'Configure the manifest' section. To your point, however, let me add a note somewhere in the article to provide further guidance for folks with existing projects.

**Comment by unhammer** [comment]
Well, I've added `<SupportsNoItemContext>true</SupportsNoItemContext>` under 

```
     <Hosts>
       <Host xsi:type="MailHost">
         <DesktopFormFactor>
          <ExtensionPoint xsi:type="MessageReadCommandSurface">
            <OfficeTab id="TabDefault">
              <Group id="msgReadGroup">
                <Control xsi:type="Button" id="msgReadOpenPaneButton">
                  <Action xsi:type="ShowTaskpane">
```

 and the button is still greyed out when no message is selected. What else is required for it not to be greyed out?

**Comment by unhammer** [comment]
I finally got it working by removing the contents of the 1.0 versionoverride. I originally had 

```
  <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides" xsi:type="VersionOverridesV1_0">
      <Requirements>…</Requirements>
      <Hosts>…</Hosts>
      <Resources>…</Resources>
      <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides/1.1" xsi:type="VersionOverridesV1_1">
          <Requirements>…</Requirements>
          <Hosts>…</Hosts>
          <Resources>…</Resources>
      </VersionOverrides>
  </VersionOverrides>
```
Then I changed it to
```
  <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides" xsi:type="VersionOverridesV1_0">
      <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides/1.1" xsi:type="VersionOverridesV1_1">
          <Requirements>…</Requirements>
          <Hosts>…</Hosts>
          <Resources>…</Resources>
      </VersionOverrides>
  </VersionOverrides>
```
and the addon can now show without a message selected. 

However, it no longer shows in outlook for web, only on desktop. I'm not sure I understand https://learn.microsoft.com/en-us/javascript/api/manifest/versionoverrides?view=common-js-preview#namespace-values – is there a full example of a manifest.xml somewhere that enables `SupportsNoItemContext` for desktop while still letting one use the addin without that feature on web?

**Comment by samantharamon** [comment]
Thanks for the update, @unhammer. I'm glad to hear you were able to get it to work in the Outlook desktop client. I've made a note to make sure that we clearly specify that VersionOverrides 1.1 is required in the walkthrough.

Regarding the add-in not showing up in Outlook on the web, due to caching, it may take up to four hours for a sideloaded add-in to appear if any changes were made to it. Did the add-in eventually reappear for you or are you still experiencing issues?

**Comment by unhammer** [comment]
I did eventually get it to reappear, yes. I found out the hard way that I just need to wait a few hours :) 

Similarly when removing the add-on when installed through appsource, it took some time for it to disappear from desktop Outlook. I don't suppose there's a "clear cache" button somewhere?

**Comment by samantharamon** [comment]
I'm glad to hear that the add-in eventually reappeared in Outlook on the web. There isn't a Clear Cache button available, however, you can manually clear the cache per [Clear the Office cache](https://learn.microsoft.com/office/dev/add-ins/testing/clear-cache).

**Comment by samantharamon** [comment]
No worries. I created #4207 to integrate the doc feedback you provided. Once the changes are merged, this issue will automatically close, but please don't hesitate to create another issue if you need additional assistance.

Thank you again for your feedback to help improve our documentation!
