### ISSUE TITLE
French translation error 'CustomXmlParts' instead of 'Bindings'

### ISSUE THREAD

**Issue by glacasa** [OfficeDev/office-js-docs-pr#419]
In the french translation, there are these 2 lines : 

> Les objets CustomXmlParts, CustomXmlPart et les objets associés pour créer et manipuler des parties XML personnalisées dans des documents Word.
> 
> Les objets CustomXmlParts et CustomXmlPart et les objets associés pour créer et manipuler des parties XML personnalisées dans des documents Word.

It's a translation error, the two lines are about `CustomXmlParts`, but in the original version, the first line is about Bindings.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 445e0856-5979-1c2d-8bab-c6294675be79
* Version Independent ID: aa56948e-b70e-43af-8a62-4c6cbfd14335
* Content: [Prise en charge de l’API JavaScript pour Office pour les compléments de contenu et du volet Office dans Office 2013](https://docs.microsoft.com/fr-fr/office/dev/add-ins/develop/support-for-task-pane-and-content-add-ins#feedback)
* Content Source: [docs/develop/support-for-task-pane-and-content-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/support-for-task-pane-and-content-add-ins.md)
* Product: **office 365**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Reezaali** [comment]
@glacasa thank you for notifying us about this error. 

@OfficeGSX - can you review and update please? Thank you!

**Comment by OfficeGSX** [comment]
Hello,

Thank you for flagging this issue, it has been fixed and the change is visible on the live site. See the screenshot below:

![image](https://user-images.githubusercontent.com/16706698/46521432-db460100-c87f-11e8-9552-947e26d7435e.png)

Best regards,

Jiri

**Comment by kbrandl** [comment]
@OfficeGSX thank you for fixing this issue!  @glacasa I am going to close this issue now, but please feel free to comment again here if you think that the issue needs to be reopened for any reason.
