### ISSUE TITLE
SupportsNoItemContext code example doesn't actually work

### ISSUE THREAD

**Issue by miklschmidt** [OfficeDev/office-js-docs-pr#4190]
Following the guide for SupportsNoItemContext to the letter (freshly generated project via `yo office`), under point 3: `Select Show Taskpane from the ribbon.` There is actually no "Show Taskpane" in the ribbon. The add in does not get added to the ribbon at all, it is only available from an opened message.

Is this because the SupportsNoItemContext doesn't work, or because the docs are lacking something?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6c1ca1e3-adbb-5cb7-93fb-09b258a101b8
* Version Independent ID: 6c1ca1e3-adbb-5cb7-93fb-09b258a101b8
* Content: [Activate your Outlook add-in without the Reading Pane enabled or a message selected - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/contextless)
* Content Source: [docs/outlook/contextless.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/outlook/contextless.md)
* Service: **outlook**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by miklschmidt** [comment]
See screenshots:
![image](https://github.com/OfficeDev/office-js-docs-pr/assets/751171/916133e3-dfbe-4cdf-b121-5d78c8e1dc1c)
![image](https://github.com/OfficeDev/office-js-docs-pr/assets/751171/0fccf1b3-fa17-45aa-a08e-eef8f67a161d)
![image](https://github.com/OfficeDev/office-js-docs-pr/assets/751171/9eb9a4b8-47e1-489d-bd05-f0c2687408d8)

**Comment by samantharamon** [comment]
Hi @miklschmidt,

Apologies for missing this last week and thanks for reporting this issue.

I see that you're using the new Outlook client on Windows. To help me troubleshoot this, are you able to get your add-in to work in the classic Outlook client on Windows and Outlook on the web by any chance?

**Comment by miklschmidt** [comment]
@samantharamon Yes, i'm able to get it working in classic Outlook on Windows 11 (i had to manually add the manifest to AppData however), Outlook on the web doesn't work either.

**Comment by samantharamon** [comment]
Thanks for confirming, @miklschmidt. Let me investigate this further and get back to you once I learn more.

**Comment by samantharamon** [comment]
Thank you for your patience as we investigated this further, @miklschmidt.

Because Message Read add-in commands in Outlook on the web and in the new Outlook on Windows appear in the action bar of a message and not the ribbon, an add-in that implements the **SupportsNoItemContext** feature won't activate if the Reading Pane is hidden or a message isn't first selected.

I created PR #4220 to clarify this in the article. Please note that this issue will automatically close once the changes are merged. If you need additional assistance, however, please don't hesitate to reopen this issue or open a new one.

**Comment by miklschmidt** [comment]
@samantharamon Thank you for following up. 

That's very odd - that means a bunch of existing outlook workflows no longer work in "New Outlook". Obviously this discussion isn't docs related, but do you know the reason for changing this behavior / removing this feature? It's hard to see the logic in it from the outside, and i imagine it's not going to go over well with users.

**Comment by samantharamon** [comment]
Thanks for sharing your concern, @miklschmidt. I'm following up on this with the team and will get back to you once I learn more.

**Comment by samantharamon** [comment]
Thanks for your patience, @miklschmidt. I had forwarded your concern to the team. When you get a chance, could you please create a feature request at <https://aka.ms/m365dev-suggestions> to make the add-in button visible on the ribbon of Outlook on the web/new Outlook for Windows? This would help the team review and keep track of your feedback.

I'll go ahead and close this issue, but please don't hesitate to create a new GitHub issue should you need additional assistance.

**Comment by miklschmidt** [comment]
@samantharamon Thank you. I already upvoted the existing reports of the same thing i could find there. It's quite unorganized (can't filter by application for example), and there seems to be very little interaction from MS and no indication of planned features / parity with VSTO plugins. Lots of duplicated or related issues. Anyway. Here's the ones i upvoted, i may have missed some.

https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/new-outlook-owa-supportsnoitemcontext-add-support-for-multiple/idi-p/3952549

https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/allow-outlook-web-add-ins-to-run-without-item-context/idi-p/3136821

**Comment by samantharamon** [comment]
Thanks, @miklschmidt. Will pass these on to the team as well.
