### ISSUE TITLE
Confusing documentation

### ISSUE THREAD

**Issue by MarwanSummakieh** [OfficeDev/office-js-docs-pr#4222]
[Enter feedback here]

This page and every add-in tutorial rely heavily on the code example on github, which is not beneficial at all you cannot use that in a custom application or personal add in, there should be a tutorial that describes how to implement SSO without having to clone a repo with like 20 different projects and having to look through it to find the one that kind of resembles the one you are working with.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cb06c24b-9d11-9cc5-2e98-561601452638
* Version Independent ID: abda21d9-6e80-8319-c56f-004658014e3c
* Content: [Enable single sign-on (SSO) in an Office Add-in - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/sso-in-office-add-ins)
* Content Source: [docs/develop/sso-in-office-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/develop/sso-in-office-add-ins.md)
* Service: **microsoft-365**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by davidchesnut** [comment]
Hi @MarwanSummakieh, just to be sure I understand, is the confusing part getting from the [walkthrough article](https://learn.microsoft.com/office/dev/add-ins/develop/create-sso-office-add-ins-aspnet) to the correct folder of the [accompanying sample](https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/auth/Office-Add-in-ASPNET-SSO)? 

If so, I wonder if it would help to make all the titles line up so:
- [Article](https://learn.microsoft.com/office/dev/add-ins/develop/create-sso-office-add-ins-aspnet) is titled "Create an ASP.NET Office Add-in that uses single sign-on"
- [Sample on GitHub](https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/auth/Office-Add-in-ASPNET-SSO) is also titled "Create an ASP.NET Office Add-in that uses single sign-on"
- [Quick links to auth samples](https://github.com/OfficeDev/Office-Add-in-samples/tree/main#auth-identity-and-single-sign-on-sso) in the readme would alos be titled "Create an ASP.NET Office Add-in that uses single sign-on"

This way after you clone it would help that all these line up so you know you are in the right spot. Let me know what you think or if you have other suggestions.

Thanks!
David
