### ISSUE TITLE
Using wrong property in documentation

### ISSUE THREAD

**Issue by MechaKnightz** [OfficeDev/office-js-docs-pr#4223]
asyncResult.id in the second snippet in the section "How to save custom XML to the document" should be asyncResult.value.id like in the first snippet

![image](https://github.com/OfficeDev/office-js-docs-pr/assets/5016167/731ae1a2-aad9-4c83-b853-dfa2b2723f34)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b683480b-a4fe-97ba-64f9-45ecfe829bf4
* Version Independent ID: a0993174-18dd-9594-9c3c-102d078e2217
* Content: [Persist add-in state and settings - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/persisting-add-in-state-and-settings?view=office-js#how-to-save-custom-xml-to-the-document)
* Content Source: [docs/develop/persisting-add-in-state-and-settings.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/develop/persisting-add-in-state-and-settings.md)
* Service: **microsoft-365**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for flagging this @MechaKnightz.

I've submitted PR #4224 to correct this mistake.
