### ISSUE TITLE
Blazor Support

### ISSUE THREAD

**Issue by bilalchraibi** [OfficeDev/office-js-docs-pr#4238]
[Blazor support]

Is there any news on Blazor Wasm support? I know that Microsoft is pushing a lot Blazor on the developer scene, so it strikes me that the Office team hasn't incorporated Blazor support for Add-ins yet.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9c4ddde7-f1fd-44ba-fba1-0ae9d0131df7
* Version Independent ID: d946ffe6-f29f-1563-b679-121090ba60a1
* Content: [Build your first Excel task pane add-in - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-jquery?tabs=yeomangenerator)
* Content Source: [docs/quickstarts/excel-quickstart-jquery.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/quickstarts/excel-quickstart-jquery.md)
* Service: **excel**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @bilalchraibi,

Have you looked at our sample, [Create a Blazor Webassembly Excel add-in](https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/blazor-add-in/excel-blazor-add-in#create-a-blazor-webassembly-excel-add-in)? I think that will help get you started using these technologies.

If the sample is missing something (or I've missed something in your issue), please reply here and we'll investigate.

**Comment by bilalchraibi** [comment]
Thank you @AlexJerabek for the quick reply and for pointing me to the right place!

Small feedback though, it will be nice to add it to the left panel and in the getting started section and not only in the sample section, similarly to the React, Vue and Angular tutorials.

![image](https://github.com/OfficeDev/office-js-docs-pr/assets/44674415/aefa2f14-64b6-41a9-8382-ec044b46cab5)

**Comment by AlexJerabek** [comment]
Thanks @bilalchraibi! We'll definitely consider how to increase the visibility and discoverability of that sample.
