### ISSUE TITLE
Test integrated spam-reporting add-in on the web version

### ISSUE THREAD

**Issue by TLeiter** [OfficeDev/office-js-docs-pr#4239]
Hello,

Is it possible to test the spam-reporting add-in in the web version of outlook (Switching to new outlook from heavy client or  using office.com) since it is still in preview phase or is it normal behavior not to see the button ?

**Comment by samantharamon** [comment]
Hi @TLeiter,

Currently, the integrated spam-reporting feature is only available in the Outlook on Windows client (non-new version) through the Beta Channel, so a spam-reporting add-in button won't show up on the web or on the new Outlook on Windows clients. The teams are currently working to support this feature on these clients. We'll update [Implement an integrated spam-reporting add-in (preview](https://learn.microsoft.com/office/dev/add-ins/outlook/spam-reporting) once spam reporting is supported in other clients, so be sure to check back.

Thanks for reaching out.

**Comment by TLeiter** [comment]
@samantharamon  thanks for the update.
