### ISSUE TITLE
localStorage not working in chrome because of storage partitioning

### ISSUE THREAD

**Issue by milczuk** [OfficeDev/office-js-docs-pr#4249]
There is a problem with using localStorage on chrome browser
https://developer.chrome.com/en/docs/privacy-sandbox/storage-partitioning/

Recently introduced changes do not allow sharing local storage between the panel and the dialog on OWA

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 90c4b723-92b3-c88e-1fd3-d89bccc8672b
* Version Independent ID: b44c3736-dad2-a9ea-1a0c-8836f663fcf1
* Content: [Alternative ways of passing messages to a dialog box from its host page - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/parent-to-dialog)
* Content Source: [docs/develop/parent-to-dialog.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/develop/parent-to-dialog.md)
* Service: **microsoft-365**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for reporting this @milczuk.

@samantharamon, could you please investigate?

**Comment by samantharamon** [comment]
Hi @milczuk,

Thanks for reaching out. What is the particular error you get when you use the `localStorage` in Chrome? Does this issue also occur in the Edge browser?

**Comment by milczuk** [comment]
Hi

We've been successfully using the alternative way based on localStorage to pass messages to the dialog from the panel. Just like in the example: https://learn.microsoft.com/en-us/office/dev/add-ins/develop/parent-to-dialog#use-local-storage
localStorage.set in panel
localStorage.get in dialog

We were using the localStorage to set the clientId and few other parameters in panel context and open the dialog
https://learn.microsoft.com/en-us/office/dev/add-ins/develop/parent-to-dialog#use-local-storage
we then try to get the params from the dialog context but we are not able to get them (it's null)

Recently chrome introduced storage partitioning. Dialog and panel do not share local storage now.
Panel is inside an iframe src="example.com" that's embeded in side outlook.com website
The dialog is not, we're opening the dialog using Office.context.ui.displayDialogAsync but _without_ the displayInIframe option (we need that for oauth redirect flow).
As a result when setting the values in localStorage from the panel code we are working with 3rd party storage (because the origin is outside of the top-level site) (if you debug it you will see in dev-tools Application->local storage -> example.com:
Is third-party: Yes, because the origin is outside of the top-level site
That is not the case when operating from the dialog (again not using disaplyInIframe option), when example.com is the top-level site.

For now the issue is only on Chrome.
It's fine in desktop (panel is not in an iframe there), Edge, even on IE11 (office 2019).
On OWA our panel is 

Please consider updating the docs so that others are also aware of this risk

I've managed to implement a workaround using messageParent/messageChild but it's also an issue when using dialog API when we already have the token in the panel, when using msal.js for example with cacheLocation: 'localStorage' even though we have the token we can't use the cache for anything in the panel because we don't have access to localStorage.

**Comment by milczuk** [comment]
one more note is that disabling the chrome://flags/#third-party-storage-partitioning solves the issue

**Comment by samantharamon** [comment]
Thanks for providing additional context, @milczuk. I'll pass on this information to the team to look into in case they can provide guidance in addition to what you already found. I'll then update the documentation accordingly.

**Comment by samantharamon** [comment]
Thanks, @milczuk. It looks like it affects all Chromium-based browsers. We have a PR in review to update our docs (see https://github.com/OfficeDev/office-js-docs-pr/pull/4278).

**Comment by milczuk** [comment]
Thanks @samantharamon for addressing this issue :)
