### ISSUE TITLE
Error When Following Tutorial 

### ISSUE THREAD

**Issue by Cauch-BS** [OfficeDev/office-js-docs-pr#4269]
Error when following this tutorial. I get the following error. It prompts me to answer is I should allow localhost loopback for Microsoft Edge WebView. When I answer No, I get the following error. 

```
C:\Users\cauch\Test_Excel Add-In> npm start

> office-addin-taskpane-js@0.0.1 start
> office-addin-debugging start manifest.xml

Debugging is being started...
App type: desktop
? Allow localhost loopback for Microsoft Edge WebView? No
Enabled debugging for add-in df3bf9d0-5111-4263-97f4-7458dbf79d36.
Starting the dev server... (webpack serve --mode development)
The dev server is running on port 3000. Process id: 25424
Sideloading the Office Add-in...
Error: Unable to start debugging.
Error: Unable to sideload the Office Add-in.
Error: Unable to set registry value "df3bf9d0-5111-4263-97f4-7458dbf79d36" to "C:\Users\cauch\Test_Excel Add-In\manifest.xml" (REG_SZ) for key ""HKCU\SOFTWARE\Microsoft\Office\16.0\Wef\Developer"".
ProcessUncleanExitError: ADD command exited with code 1:
```

When I answer yes, I get the following error. 

```
C:\Users\cauch\Test_Excel Add-In> npm start

> office-addin-taskpane-js@0.0.1 start
> office-addin-debugging start manifest.xml

Debugging is being started...
App type: desktop
? Allow localhost loopback for Microsoft Edge WebView? Yes
Error: Unable to start debugging.
����: �׼����� �źεǾ����ϴ�. ������ ������ �������� �����Ͻʽÿ�.


```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9c4ddde7-f1fd-44ba-fba1-0ae9d0131df7
* Version Independent ID: d946ffe6-f29f-1563-b679-121090ba60a1
* Content: [Build your first Excel task pane add-in - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-jquery?tabs=yeomangenerator)
* Content Source: [docs/quickstarts/excel-quickstart-jquery.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/quickstarts/excel-quickstart-jquery.md)
* Service: **excel**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Cauch-BS** [comment]
This error persists when I changed the addon name from Test_Excel Add-In to My Office Add-in as given in the tutorial.

**Comment by Rick-Kirkham** [comment]
Probably a dup of: https://github.com/OfficeDev/Office-Addin-TaskPane-React/issues/134

**Comment by Cauch-BS** [comment]
How should I fix it? Should I re-install yo-office later? Or can I fix it by fiddling around with the xml file? 

cf1) The command line error does seem to prevent the add-in from running when I do it with the installed desktop app version, though it works fine with url web version.

cf2) The error message seems to be in Koean, which is why it doesn't seem to be displaying correctly.

**Comment by AlexJerabek** [comment]
Hi @Cauch-BS,
We've made some updates to yo office. Could you please confirm if you're still seeing this error after updating to the latest version?

**Comment by AlexJerabek** [comment]
Hi @Cauch-BS,

Given the recent updates to yo office, I'm going to close this issue. If you are still encountering problems, let me know and I'll reopen it.
