### ISSUE TITLE
The table describing the multi-select in conversation behaviour is not accurate for Outlook for Web

### ISSUE THREAD

**Issue by CameronDwyer** [OfficeDev/office-js-docs-pr#4284]
The table on this page describing the expected behaviour for multi-select when conversation views are used seems to apply to Outlook for Desktop but is inaccurate for Outlook for Web. Below (and in the attached file) I've added columns for Outlook for Web (OWA).

![image](https://github.com/OfficeDev/office-js-docs-pr/assets/16345690/ebedf447-5689-47e3-8c52-607ca43d7de0)

See attached file for screenshots of observed behaviour (goes into more detail than the table visible here)

[Table describing the multi-select in conversation behaviour is not accurate for Outlook for Web.docx](https://github.com/OfficeDev/office-js-docs-pr/files/13421511/Table.describing.the.multi-select.in.conversation.behaviour.is.not.accurate.for.Outlook.for.Web.docx)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 34daad03-0e48-d846-0c52-9ce4cedd4462
* Version Independent ID: 34daad03-0e48-d846-0c52-9ce4cedd4462
* Content: [Activate your Outlook add-in on multiple messages - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/item-multi-select#multi-select-in-conversations)
* Content Source: [docs/outlook/item-multi-select.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/outlook/item-multi-select.md)
* Service: **outlook**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for reporting this @CameronDwyer.

@samantharamon, could you please investigate?

**Comment by samantharamon** [comment]
Thanks again for reporting this, @CameronDwyer. We've verified the behavior you reported and updated the article to reflect this (see #4405). We've also reworded the description of the message selection use cases to clarify them.

This issue will automatically close once the changes are merged. However, if you require additional assistance, please don't hesitate to open a new GitHub issue.
