### ISSUE TITLE
Are these PowerShell commands copy and paste or not? 

### ISSUE THREAD

**Issue by brcox9090** [OfficeDev/office-js-docs-pr#4285]
There isn't a single PowerShell command included in this page that works. They all throw a minimum 2 errors about commands not existing, even when running the script to download new command sets. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9e12d688-9620-e8f2-871d-922ec98008b5
* Version Independent ID: a8b409f3-44f7-97e5-d722-cbf04edc0653
* Content: [On-send feature for Outlook add-ins - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/outlook-on-send-addins?tabs=classic)
* Content Source: [docs/outlook/outlook-on-send-addins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/outlook/outlook-on-send-addins.md)
* Service: **outlook**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for flagging this issue @brcox9090.

@samantharamon, could you please look into this?
