### ISSUE TITLE
Reference to key requirements and/or link to requirements

### ISSUE THREAD

**Issue by TiJohn0108** [OfficeDev/office-js-docs-pr#4286]
As I understand it, Office Add-ins, non-COM/VSTO add-ins, have an Exchange Online Mailbox requirement no matter what method is used to deploy Office Add-ins and I don't believe that's clear here. Specific pages such as Centralized Deployment and Intergrated Apps I believe do a good job of calling out that requirement but there certain, "top level" pages, such as this one, that make it clear minimum requirements. 

I understand that we don't want to repeatedly note requirements, but it seems there are some pages that could use at least a one liner that notes key minimum requirements, such as an Exchange Online Mailbox and a link out to more specifics.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2677af5b-e9b8-f962-25ce-8aa285977c90
* Version Independent ID: c31c7ed9-0a0a-7a65-0d1b-70d6a8b33994
* Content: [Deploy and publish Office Add-ins - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/publish/publish)
* Content Source: [docs/publish/publish.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/publish/publish.md)
* Service: **microsoft-365**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for raising this question @TiJohn0108.

@samantharamon, could you please investigate?

**Comment by samantharamon** [comment]
Thanks for your feedback, @TiJohn0108.

Changes have been made in #4318. Please note that this issue will automatically close once the changes are merged. However, if you have additional feedback, please don't hesitate to reopen this issue.
