### ISSUE TITLE
Can tokens to custom back-end services be returned to Office Add-in client-side code?

### ISSUE THREAD

**Issue by LapNik** [OfficeDev/office-js-docs-pr#4288]
There is a note on this page saying to always perform the On-Behalf-Of flow on the server-side and that the token should not be returned to client-side code. Why is that? Is there a technical reason why Office Add-ins are more likely to leak client-side variables or should Graph API specifically never be used from single-page applications because a browser context cannot be trusted?

Does this recommendation (or requirement?) also apply for non-Microsoft APIs that I control? If I want to authorize requests to my own back-end services, which would normally be used through single-page applications, can I then return the tokens to the add-in client-side code to use the APIs directly or do I need to implement an API proxy?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2fac8fa3-84ef-73da-686e-ae4149c6b2b0
* Version Independent ID: be12acbf-a656-4c95-02d5-5d1f18c6939b
* Content: [Overview of authentication and authorization in Office Add-ins - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/overview-authn-authz)
* Content Source: [docs/develop/overview-authn-authz.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/develop/overview-authn-authz.md)
* Service: **microsoft-365**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for the question @LapNik.

@davidchesnut, could you please provide some context?

**Comment by LapNik** [comment]
Getting the access token to the client-side code would be a huge help because the back-end services might be in an on-prem private network and inaccessible to the add-in server-side code.

**Comment by davidchesnut** [comment]
Hi @LapNik,

It's mostly about good security practices. web browsers in general are not a safe place to store anything secretive. Also the token issued by the OBO flow will have the audience set to your middle-tier (not the client). Which implies you shouldn't be sharing it anywhere outside the middle-tier. 

It's important to note this is not specific to Office Add-ins. The Microsoft identity documentation provides a good warning note about the pitfalls of sharing an OBO token at https://learn.microsoft.com/entra/identity-platform/v2-oauth2-on-behalf-of-flow#middle-tier-access-token-request.  

In terms of other APIs and tokens it will depend on what you want to achieve. For example, if you want to use SPA with auth code flow you'd want to follow documentation such as the [Tutorial: Sign in users and call the Microsoft Graph API from a JavaScript single-page app (SPA) using auth code flow](https://learn.microsoft.com/entra/identity-platform/tutorial-v2-javascript-auth-code). Note that the MSAL.js package provides caching mechanisms to help protect the token. And this token would have different audience settings and other claims as part of auth code flow.

Hope this helps,
David
