### ISSUE TITLE
Event based activation in mobile addins not yet available

### ISSUE THREAD

**Issue by bogdanst24** [OfficeDev/office-js-docs-pr#4294]
The documentation does not specify the availability of the feature or anything related to it not being yet deployed.

## Article URL

https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/mobile-event-based

## Issue

 After many discussions with the Office JS team, we found out that the rollout for the Web Add-ins in Outlook Mobile for iPhones was stopped and delayed until next year. This information, as the status of the feature availability, should be present in the official documentation.
 
 Discussion here: https://github.com/OfficeDev/office-js/issues/3780#issuecomment-1832342800

**Comment by AlexJerabek** [comment]
Thanks for raising this issue. Let me tag @samantharamon to make the mobile limitations clearer in the documentation.

**Comment by samantharamon** [comment]
Thanks, @bogdanst24. I'm working with the team to correct the iOS support information in our documentation.

**Comment by samantharamon** [comment]
@bogdanst24, we're correcting the documentation in #4300. This GitHub issue will automatically close once the changes are merged. If you require additional assistance, please don't hesitate to open a new GitHub issue.

Thank you again for reporting this documentation discrepancy.
