### ISSUE TITLE
example not work )

### ISSUE THREAD

**Issue by paultino** [OfficeDev/office-js-docs-pr#4297]
There is a strong belief that not a single example presented here works.
There is confirmation in the first paragraph. 
Why use npm if there is a winget?
"npm: The term 'npm' is not recognized as a name of a cmdlet.." what to do next?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ac7d9e2d-b537-cf1f-95fb-4e216514f3b1
* Version Independent ID: 4a86c93b-70d8-38e4-f62e-83c43a0158dd
* Content: [Excel add-in tutorial - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/tutorials/excel-tutorial)
* Content Source: [docs/tutorials/excel-tutorial.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/tutorials/excel-tutorial.md)
* Service: **excel**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @paultino,

If you're getting an error about npm not being recognized, I'm guessing that you need to install node.  Please head over to the [node.js](https://nodejs.org/) site and download the LTS version of node.

If you wish to use winget, instructions for installing node can be found [here](https://nodejs.org/en/download/package-manager#windows-1).

Please let me know if that resolves your issue.
