### ISSUE TITLE
403 Error during tutorial launch

### ISSUE THREAD

**Issue by JacobMembrino** [OfficeDev/office-js-docs-pr#4308]
## Summary

Attempting to deploy the tutorial below on Outlook 2017 with a Microsoft 365 license on any version of node including v18.17.0 as per [the previous issue](https://github.com/OfficeDev/office-js-docs-pr/issues/4304) grants the error message below. It outlines a 403 forbidden error, which indicates a permissions issue somewhere along in the sideloading of the add-in. Running ```npm start``` in an administrator terminal does not prevent the issue, and the Group Policy that prevents the use of non-whitelisted outlook add-ins is not enabled. Manually sideloading the add-in from its manifest file does not work either.

Any help with this would be appreciated.

## Article URL
https://learn.microsoft.com/en-us/office/dev/add-ins/quickstarts/outlook-quickstart?tabs=yeomangenerator

## Issue

office-addin-taskpane-js@0.0.1 start
office-addin-debugging start manifest.xml

Debugging is being started...
App type: desktop
Enabled debugging for add-in 8e5850ac-5a9e-4b92-8fa7-c39575d632b4.
Starting the dev server... (webpack serve --mode development)
The dev server is running on port 3000. Process id: 16540
Sideloading the Office Add-in...
running: npx -p @microsoft/teamsfx-cli@2.0.3-alpha.e5db52f29.0 teamsfx m365 sideloading --xml-path "C:\Users\xxxx\HelpDesk Outlook Addin\manifest.xml"

Warning: We are planning to depreate 'teamsfx' as command signagure and move to 'teamsapp' instead in the next major version of Teams Toolkit CLI.
This command is in preview.
Using account xxxxxxxx.com

Successfully registered package! (??)
 STDERR: (×) Error: Get ServiceUrl failed. Request failed with status code 403
(×) Error: Sideloading failed.
(×) Error: ""
(×) Error: m365.UnhandledError: An unexpected error has occurred while performing the M365 task. {"stack":"Error: {\"message\":\"Request failed with status code 403\",\"detail\":\"\\\"\\\"\",\"tracingId\":\"\"}\n    at createError (C:\\Users\\xxxxx\\HelpDesk Outlook Addin\\node_modules\\@microsoft\\teamsfx-cli\\lib\\index.js:14:300960)\n    at settle (C:\\Users\\xxxxxxx\\HelpDesk Outlook Addin\\node_modules\\@microsoft\\teamsfx-cli\\lib\\index.js:14:305240)\n    at IncomingMessage.handleStreamEnd (C:\\Users\\xxxxxxxx\\HelpDesk Outlook Addin\\node_modules\\@microsoft\\teamsfx-cli\\lib\\index.js:14:290544)\n    at IncomingMessage.emit (node:events:526:35)\n    at endReadableNT (node:internal/streams/readable:1589:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","message":"{\"message\":\"Request failed with status code 403\",\"detail\":\"\\\"\\\"\",\"tracingId\":\"\"}","config":{}}

Launching outlook via C:\Program Files\Microsoft Office\Root\Office16\OUTLOOK.EXE
Debugging started.

**Comment by samantharamon** [comment]
Hi @JacobMembrino. Thanks for reporting this issue. I'll investigate this further and get back to you.

**Comment by samantharamon** [comment]
Hi @JacobMembrino. Thanks for reporting this issue. When you get a chance, could you provide the version of your Outlook client? Out of curiosity, after running `npm start` to start the local web server, are you able to manually sideload the add-in in Outlook on the web? For guidance on manually sideloading an add-in, see [Sideload Outlook add-ins for testing](https://learn.microsoft.com/office/dev/add-ins/outlook/sideload-outlook-add-ins-for-testing?tabs=windows#sideload-manually).

**Comment by JacobMembrino** [comment]
Hey @samantharamon, the version is Microsoft® Outlook® for Microsoft 365 MSO (Version 2311 Build 16.0.17029.20028) 64-bit.

I was unable to manually sideload the add-in from the web app, it wouldn't show up in the "apps" page. 

Again, my domain's outlook accounts are run by and connected to group policies, with other add-ins already being deployed to our org via group policy. The settings responsible for blocking untrusted add-ins, however, are not enabled. That's where I got stuck.

**Comment by DSBloom** [comment]
I'm having the same issue. **Microsoft® Outlook® for Microsoft 365 MSO (Version 2311 Build 16.0.17029.20028) 64-bit**

**Comment by samantharamon** [comment]
Apologies for the delayed response. When you run `npm start` for the first time, you should be prompted to log into your Microsoft 365 account via a dialog or a browser window. If you cancel or close the dialog/window, you'll run into the 403 permissions error. Were you prompted to log into your account by any chance?
