### ISSUE TITLE
December video + January updated calendar invite

### ISSUE THREAD

**Issue by lsmith77** [OfficeDev/office-js-docs-pr#4322]
When will the video from the December call be available?
Also when will the updated calendar invite be available with the updated time starting January?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a57f1340-d9ee-6bbc-c4ba-104b77840a6a
* Version Independent ID: 82ff44e8-1cdc-20e9-3ce6-d560de532b14
* Content: [Microsoft Office Add-ins community call - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/overview/office-add-ins-community-call)
* Content Source: [docs/overview/office-add-ins-community-call.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/overview/office-add-ins-community-call.md)
* Service: **microsoft-365**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by samantharamon** [comment]
Hi @lsmith77. Thanks for reaching out. Let me follow up on when the recording of the December call will be posted. Regarding your other query, the calendar invite has now been updated. You can download it from <https://aka.ms/officeaddinscommunitycall>. Please note that we're updating [Microsoft Office Add-ins community call](https://learn.microsoft.com/office/dev/add-ins/overview/office-add-ins-community-call) in #4325 to reflect this change.

**Comment by lsmith77** [comment]
Thank you. I also noticed that the form to ask questions for the next meeting seems to have expired.

**Comment by samantharamon** [comment]
Thanks for letting us know, @lsmith77.

@preethikakiru, could you please investigate this when you get a chance?

**Comment by lsmith77** [comment]
Any update on how to submit questions to the february call?

**Comment by AlexJerabek** [comment]
Closing, since this should be updated in the docs.
