### ISSUE TITLE
Dialog does not exist

### ISSUE THREAD

**Issue by crgarcia12** [OfficeDev/office-js-docs-pr#4330]
The document says:
_To test this add-in, try signing in again after setting the Use multi-factor auth property to True in the Deployment section of the Web Add-in project properties dialog.

There is no Deployment section in the WebAdd-in project properties:
<img width="1091" alt="image" src="https://github.com/OfficeDev/office-js-docs-pr/assets/27244028/571cb0a3-0a93-407c-a449-6a50a6c34e23">

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 930ce4fc-c8b8-f756-f03f-a716f1ef7883
* Version Independent ID: 753a2e38-9430-25bb-5409-b7eed9c88e47
* Content: [Build your first Outlook add-in - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/quickstarts/outlook-quickstart?tabs=visualstudio)
* Content Source: [docs/quickstarts/outlook-quickstart.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/quickstarts/outlook-quickstart.md)
* Service: **outlook**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for reporting this issue @crgarcia12.

@samantharamon, could you please investigate?
