### ISSUE TITLE
Unable to read hyperlink in Powerpoint and Excel

### ISSUE THREAD

**Issue by adithyasai** [OfficeDev/office-js-docs-pr#4342]
## Article URL
We are trying to read the hyperlink from 

## Issue
We are facing the following issues with OfficeJS and i dont see that mentioned anywhere in the documentation
- Excel - Not able to search “hyperlinks/embedded links” in Excel using OfficeJS Api
- PowerPoint - Not able to search “hyperlinks/embedded links” in PowerPoint using OfficeJS Api

Can you please point me the right place if thats already documented somewhere
https://learn.microsoft.com/en-us/javascript/api/excel/excel.range?view=excel-js-preview#excel-excel-range-hyperlink-member

**Comment by davidchesnut** [comment]
Hi @adithyasai,

You can get the hyperlink for a range in Excel by using the following code:
```
async function run() {
  await Excel.run(async (context) => {
    const sheet = context.workbook.worksheets.getActiveWorksheet();

    const range = sheet.getRange("A1");
    await context.sync();
    range.load("hyperlink");
    await context.sync();
    console.log(range.hyperlink);

  });
}
```

I don't believe PowerPoint has a way to get the hyperlink for various objects. You could submit a feature request for this with more details about your scenario here:  https://aka.ms/m365dev-suggestions.

As a workaround, you may potentially be able to find PowerPoint hyperlinks by examining the Open XML file of the presentation. For more information see the following resources. Many are for Word but the techniques should also apply to PowerPoint.
- [getFileAsync API](https://learn.microsoft.com/javascript/api/office/office.document?view=common-js-preview#office-office-document-getfileasync-member(1))
- [Understand when and how to use Office Open XML in your Word add-in](https://learn.microsoft.com/en-us/office/dev/add-ins/word/create-better-add-ins-for-word-with-office-open-xml)
- [Get, edit, and set OOXML content in a Word document with a Word add-in](https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/word-add-in-get-set-edit-openxml)
- [Load and write Open XML in your Word add-in](https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/word-add-in-load-and-write-open-xml)

Cheers,
David

**Comment by Rick-Kirkham** [comment]
[like]  Ricky Kirkham reacted to your message:
________________________________

**Comment by davidchesnut** [comment]
I updated my previous comment to remove the information on getting and setting OOXML. PowerPoint does not support the OOXML coercion type. For more information on supported coercion types, see the tables in [getSelectedDataAsync](https://learn.microsoft.com/javascript/api/office/office.document?#office-office-document-getselecteddataasync-member(1)).
