### ISSUE TITLE
Show Task Pane button does not appear after using npm start

### ISSUE THREAD

**Issue by deepliar** [OfficeDev/office-js-docs-pr#4344]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a59958d2-f428-9ca2-3440-a5af662386c0
* Version Independent ID: dcaf0b5b-08ea-c437-130b-342a1be62a16
* Content: [Tutorial: Build a message compose Outlook add-in - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/tutorials/outlook-tutorial)
* Content Source: [docs/tutorials/outlook-tutorial.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/tutorials/outlook-tutorial.md)
* Service: **outlook**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @deepliar,

Sorry to hear you're having issues. When you run `npm start`, are you seeing something saying "Error sideloading"? If so, you might be on an old version of yo office (based on [this issue](https://github.com/OfficeDev/Office-Addin-Scripts/issues/815). Make sure your version of yo office is updated and try again. Let me know if you're still having issues (or that error isn't showing up).

**Comment by deepliar** [comment]
> Hi @deepliar,
> 
> Sorry to hear you're having issues. When you run `npm start`, are you seeing something saying "Error sideloading"? If so, you might be on an old version of yo office (based on [this issue](https://github.com/OfficeDev/Office-Addin-Scripts/issues/815). Make sure your version of yo office is updated and try again. Let me know if you're still having issues (or that error isn't showing up).

Yeah I made sure I had the most recent version of yo and didnt have any error when running npm start. I have tried uninstalling and removing all packages and didnt have any luck. I will try it again and let you know. Thank you for your assistance.

**Comment by samantharamon** [comment]
Thanks for the update, @deepliar. Are you testing the tutorial in Outlook on Windows or on the web? If you're testing in Outlook on Windows, you could also try the following:
1. When the Outlook client opens after running `npm start`, close Outlook.
1. Restart Outlook.
1. Wait about 30 seconds for Outlook to load your add-ins.

Let us know if this helps.
