### ISSUE TITLE
Steps aren't quite right

### ISSUE THREAD

**Issue by dazfuller** [OfficeDev/office-js-docs-pr#4359]
In the page the process for sideloading the add-in into Word states the following

```text
5. Select Home > Add-ins from the ribbon, then select Get Add-ins.
```

The actual step should be this however

```text
5. Select Insert from the ribbon, and then select the drop-down next to the "My Add-ins" option in the Add-ins section
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1bb09ad2-7df4-ba17-f35e-aa501d3face5
* Version Independent ID: 1bb09ad2-7df4-ba17-f35e-aa501d3face5
* Content: [Sideload Office Add-ins on Mac for testing - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/testing/sideload-an-office-add-in-on-mac)
* Content Source: [docs/testing/sideload-an-office-add-in-on-mac.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/testing/sideload-an-office-add-in-on-mac.md)
* Service: **microsoft-365**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by alison-mk** [comment]
Hi @dazfuller, thanks for your patience. 

I've tested the [Sideload Office Add-ins on Mac for testing](https://learn.microsoft.com/en-us/office/dev/add-ins/testing/sideload-an-office-add-in-on-mac) article. At step 5, I see steps close to what the article describes: Go to Home, then select Add-ins. Here is a screenshot: 

<img width="1300" alt="image" src="https://github.com/OfficeDev/office-js-docs-pr/assets/7977793/a70d707c-3644-4cc7-87f4-b758c99d4f0d">

I'll update the article steps to match the steps in this screenshot and close this issue. 

Thanks, 
Alison
