### ISSUE TITLE
Add-in Error - Something went wrong and we couldn't start this add-in.

### ISSUE THREAD

**Issue by kenyachan** [OfficeDev/office-js-docs-pr#4364]
Hi, I'm following this tutorial and when it comes to testing using Excel on the Web the add-in I get this error.

![image](https://github.com/OfficeDev/office-js-docs-pr/assets/29541094/95e855d5-9d58-4ff7-8649-454d1c596e9d)

After clicking RETRY, I get this:

![image](https://github.com/OfficeDev/office-js-docs-pr/assets/29541094/04fd7366-5d5f-4b48-9ba7-0a96d965b62b)

And after clicking START, I get this:

![image](https://github.com/OfficeDev/office-js-docs-pr/assets/29541094/0dadae19-24e6-4dee-8612-ce34e2e0ec7f)

macOS 12.7.2, Chrome 120.0.6099.234

When I inspect the page 

![image](https://github.com/OfficeDev/office-js-docs-pr/assets/29541094/1cd0dc4f-f480-4916-a96b-26d3fe7be5d9)

Any ideas on what I might be doing wrong? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ac7d9e2d-b537-cf1f-95fb-4e216514f3b1
* Version Independent ID: 4a86c93b-70d8-38e4-f62e-83c43a0158dd
* Content: [Excel add-in tutorial - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/tutorials/excel-tutorial)
* Content Source: [docs/tutorials/excel-tutorial.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/tutorials/excel-tutorial.md)
* Service: **excel**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @kenyachan,

Thanks for reporting this. @alison-mk, could you please investigate?

**Comment by davidchesnut** [comment]
Hi @kenyachan, from the web log you provided you are getting a certificate error. You can run the following command to ensure the developer certificates are installed for yo office projects. 
`npm install office-addin-dev-certs`

Hope this helps!
David
