### ISSUE TITLE
sample launch.config in appendix A appears to use wrong "type"

### ISSUE THREAD

**Issue by ScottMaxson** [OfficeDev/office-js-docs-pr#4376]
The example `launch.config` here specifies `type: "pwa-msedge"`
this displays an error in the vscode editor, and suggests using type msedge instead.

which should it be?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d5e92a7f-e42d-68ba-cc21-15df8289f5a1
* Version Independent ID: 096a172b-382e-764d-6d7d-88811bb5b96f
* Content: [Debug add-ins on Windows using Visual Studio Code and Microsoft Edge WebView2 (Chromium-based) - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/testing/debug-desktop-using-edge-chromium)
* Content Source: [docs/testing/debug-desktop-using-edge-chromium.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/testing/debug-desktop-using-edge-chromium.md)
* Service: **microsoft-365**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @ScottMaxson,

Thanks for reporting this. I believe the type should be `edge`. Does that work as expected for you?

I'll assign @davidchesnut to follow-up.

**Comment by davidchesnut** [comment]
Hi @ScottMaxson, thanks for bringing this to our attention. I created PR #4378 with updated steps to fix this. Would be great if you could let us know if the revised steps work for you. Thanks!
