### ISSUE TITLE
First Outlook add-in not work correctly

### ISSUE THREAD

**Issue by pawelfranasisk** [OfficeDev/office-js-docs-pr#4380]
I have a problem with a tutorial on creating add-ins for Outlook. I went through all the steps one by one, but when I launch the add-in, I only see a panel with the greeting message, and nothing else. It just displays the "loading" message, and nothing more. I created the add-in using Yeoman.

When attempting to create the add-in through Visual Studio, I couldn't run it. I received the message: "An error occurred while attempting to connect to the server: The autodiscover service couldn't be located."

**Comment by AlexJerabek** [comment]
Hi @pawelfranasisk,

Sorry to hear you're encountering these issues. What platform are you on (Windows, Mac, or Web)?

Let me tag @samantharamon and @exextoc to help follow up.

**Comment by pawelfranasisk** [comment]
I'm on Windows and Web. I've already dealt with this issue. In the project, it was sufficient to enable two-factor authentication, which unfortunately was not mentioned anywhere in the instructions on the Microsoft website or elsewhere. The issue can be considered closed.
