### ISSUE TITLE
Issuer validation

### ISSUE THREAD

**Issue by lsmith77** [OfficeDev/office-js-docs-pr#4385]
We have integrated Microsoft Offic SSO and it works fine on our testing. However when going through the Microsoft Marketplace Review we encountered issues with the token validation, since the issue does not match.

Looking at the documentation on this page it states:
```
Valid SSO tokens will be issued by the Azure authority, https://login.microsoftonline.com. The iss claim in the token should start with this value.
```

The [linked](https://learn.microsoft.com/en-us/entra/identity-platform/access-tokens#validate-the-issuer) document for token validation (and our understanding of best practices here) expect the entire URL match and not just the domain part:
```
[OpenID Connect Core](https://openid.net/specs/openid-connect-core-1_0.html#IDTokenValidation) says "The Issuer Identifier [...] MUST exactly match the value of the iss (issuer) Claim." For applications which use a tenant-specific metadata endpoint (like https://login.microsoftonline.com/8eaef023-2b34-4da1-9baa-8bc8c9d6a490/v2.0/.well-known/openid-configuration or https://login.microsoftonline.com/contoso.onmicrosoft.com/v2.0/.well-known/openid-configuration), this is all that is needed.
```

So is it correct that for Microsoft Office SSO, the expectation is to only validate the issuer domain and not the full URL?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cb06c24b-9d11-9cc5-2e98-561601452638
* Version Independent ID: abda21d9-6e80-8319-c56f-004658014e3c
* Content: [Enable single sign-on (SSO) in an Office Add-in - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/sso-in-office-add-ins)
* Content Source: [docs/develop/sso-in-office-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/develop/sso-in-office-add-ins.md)
* Service: **microsoft-365**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @lsmith77,

Thanks for reaching out. @davidchesnut, could you please investigate?

**Comment by davidchesnut** [comment]
Hi @lsmith77,

Just to be sure I understand, are you getting the token from getAccessToken(), and then passing it to your middle-tier. Is that the point at which you are validating the token?

Also are you using the code from our samples to validate, such as [this validateJwt function](https://github.com/OfficeDev/Office-Add-in-samples/blob/62d41df82fe0546aad729d578d0bee8acf5ad0a2/Samples/auth/Office-Add-in-NodeJS-SSO/Complete/server-helpers/obo-auth-helper.js#L38)? Or a different approach?

Thanks!
David

**Comment by davidchesnut** [comment]
Hi @lsmith77, also can you check that you set the access token version to 2 in your app registration> [configure access token version](https://learn.microsoft.com/office/dev/add-ins/develop/create-sso-office-add-ins-nodejs#configure-access-token-version). I've seen this trip up validation before. Thanks!

**Comment by hellasol** [comment]
Hi @davidchesnut, yes we are using the access token version 2
<img width="429" alt="Screenshot 2024-02-02 at 11 12 01" src="https://github.com/OfficeDev/office-js-docs-pr/assets/45122311/642fc71f-1d14-406c-a9a9-e95e575411bd">

**Comment by lsmith77** [comment]
> Hi @davidchesnut, yes we are using the access token version 2 <img alt="Screenshot 2024-02-02 at 11 12 01" width="429" src="https://private-user-images.githubusercontent.com/45122311/301809237-642fc71f-1d14-406c-a9a9-e95e575411bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NzQ2MzksIm5iZiI6MTcwNjg3NDMzOSwicGF0aCI6Ii80NTEyMjMxMS8zMDE4MDkyMzctNjQyZmM3MWYtMWQxNC00MDZjLWE5YTktZTk1ZTU3NTQxMWJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDExNDUzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0MjkwNTdiOWRmZjkwNjM0MDAwYjBkYzhkMWRmOGNjNDhiNGVjZjNmYTk0NGFhOWE5NjE4M2YwMGY5YmEwMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LOaH6NqkDK0vU7QyqMXdg36TdsluGpis1nkQp3BJWw0">

and yes we are using `getAccessToken()`

**Comment by davidchesnut** [comment]
Okay, so you should be getting this "iss:" claim pattern in the token from getAccessToken() `https://login.microsoftonline.com/{tenantid}/v2.0` That should match. Are you getting a differen "iss:" pattern?

I don't believe Microsoft identity is using the full URL if I'm reading [this correctly](https://learn.microsoft.com/en-us/entra/identity-platform/access-tokens#validate-the-issuer). "Microsoft Entra ID has a tenant-independent version..." etc...

Thanks!
David

**Comment by lsmith77** [comment]
we are getting `iss` but it is different from when we login with our emails and what is in the token when the microsoft review team logs in.

our token validation code looks if the `iss` matches the expected value and since we have configured it to match the value we get when we decide the token after login in ourselves, it naturally means it doesn’t match the different `iss` from the review team.

both do start with `https://login.microsoftonline.com` but it seems like when the microsoft review logs in their issue contains a different tenant id.

**Comment by lsmith77** [comment]
> Okay, so you should be getting this "iss:" claim pattern in the token from getAccessToken() `https://login.microsoftonline.com/{tenantid}/v2.0` That should match. Are you getting a differen "iss:" pattern?
> 
> I don't believe Microsoft identity is using the full URL if I'm reading [this correctly](https://learn.microsoft.com/en-us/entra/identity-platform/access-tokens#validate-the-issuer). "Microsoft Entra ID has a tenant-independent version..." etc...
> 
> Thanks! David

I am still trying to wrap my brain around this tenant-indenpendent-version stuff in those docs. It does sound promising but I find it very confusingly written.

**Comment by lsmith77** [comment]
this is the bit that is confusing me: `the application should replace the {tenantid} value in the issuer metadata with the tenantid that is the target of the current request`

what is the `tenantid that is the target`? they are authenticating against my Add-in, so what is being referred to here with `target`?

**Comment by lsmith77** [comment]
to make it more concrete. this is a pseudo decoded token generated when I was logged-in:
```
{
  "aud": "..",
  "iss": "https://login.microsoftonline.com/XYZ/v2.0",
  "iat": 1706628892,
  "nbf": 1706628892,
  "exp": 1706636789,
  "aio": "..",
  "azp": "…",
  "azpacr": "0",
  "name": "..",
  "oid": "..",
  "preferred_username": "..",
  "rh": "..",
  "scp": "access_as_user",
  "sub": "..",
  "tid": "XYZa",
  "uti": "..",
  "ver": "2.0"
}
```

In the decoded token from the microsoft review team, they obviously have a different email, name etc but most importantly where I have `XYZ` they have something different (with matching different values both in the `iss` and the `tid`).

**Comment by davidchesnut** [comment]
Hi @lsmith77, okay so I checked with the Microsoft identity team on this issue. It looks like what is happening is you have a hardcoded tenant ID in the token validation, and it will not accept tokens issued from any other tenant. So you would need to follow the [multi-tenant guidance](https://learn.microsoft.com/en-us/entra/identity-platform/access-tokens#multi-tenant-applications).

Some more information:
1. For multi-tenant apps, load the `/common` OIDC metadata, cache it according to its cache-control.
2. Validate the incoming token’s signature is signed by one of the keys at the `jwks_uri` of the /common OIDC document to make sure the token is legitimate.
3. String match the `iss` against https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration using the `tid` claim of the inbound token as the replacement for {tenantid} in its (the OIDC doc’s) issuer field.
4. Validate the issuer of the key from the header in the JWT matches the one from the `jwks_uri` where the token's `iss` must also be equal to the signing key's issuer (note that replace {tenantid} applies here as well).
5. Do all the `aud`, `iat`, `nbf` etc... validation (make sure the token is for you, is not expired, and so on).

Hope this helps,
David

**Comment by lsmith77** [comment]
@davidchesnut thank you.
