### ISSUE TITLE
internetHeaders for  Appointments

### ISSUE THREAD

**Issue by DanilKorotenko** [OfficeDev/office-js-docs-pr#4388]
Is there any possibility to set internetHeaders for Appointments?

May be, there is another way to set to outgoing appointment a custom information, that could be read on other side by my addin?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ac0e08e9-b043-1a03-9505-2b3a9ca95e14
* Version Independent ID: e465cfb6-e349-1d24-30b2-2ea4bc56d976
* Content: [Get and set internet headers - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/internet-headers)
* Content Source: [docs/outlook/internet-headers.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/outlook/internet-headers.md)
* Service: **outlook**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @DanilKorotenko,

Let me tag @samantharamon to clarify the internet header scope. If they're not supported for appointments, please head over to [Tech Community](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform) and create or upvote a feature request.

**Comment by samantharamon** [comment]
Thanks for reaching out, @DanilKorotenko. Custom internet headers can only be set on messages. Unfortunately, there currently isn't an alternative to setting and getting custom information on appointments from the recipient's side. You can use CustomProperties or RoamingSettings (see [Get and set add-in metadata for an Outlook add-in](https://learn.microsoft.com/office/dev/add-ins/outlook/metadata-for-an-outlook-add-in)), but the set data isn't preserved after the item is sent. As @AlexJerabek mentioned, if you'd like to have this functionality for appointments in Outlook add-ins, please create or upvote a feature request on [Tech Community](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform).

**Comment by DanilKorotenko** [comment]
Post on Microsoft 365 Developer Platform Tech Community:

https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/add-the-internetheaders-property-to-the-office/idc-p/4102185#M2442
