### ISSUE TITLE
Clarification on REST Deprecation.

### ISSUE THREAD

**Issue by glr0221** [OfficeDev/office-js-docs-pr#4390]
Hello Microsoft team,

I would just like to ask what the following clause means : 

_This exemption applies to privately released and AppSource-hosted add-ins. It also includes new add-ins developed after the decommission date._

Are privately released add-ins non-marketplace addins that are installed by an admin to their m365 domain using a manifest? How do we know if our addin (which has a dynamic set of manifest AppIDs) is exempted from the REST deprecation?

Thank you so very much.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fde53b2d-39f8-5b6d-5e37-068b4d93f049
* Version Independent ID: 9c7ff3ef-a188-bd28-65bb-1d620d4a8842
* Content: [Use the Outlook REST APIs from an Outlook add-in - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/use-rest-api)
* Content Source: [docs/outlook/use-rest-api.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/outlook/use-rest-api.md)
* Service: **outlook**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @glr0221,

Thank you for the question. @samantharamon, could you please investigate?

**Comment by samantharamon** [comment]
Hi @glr0221. Thanks for reaching out. Yes, privately released add-ins refer to those installed by admins. Please note that we no longer use the manifest ID to identify an add-in for exemption. Exemption is now based on traffic from the add-in, which is automatically identified on our end. So even if your add-in has a dynamic set of manifest IDs, it should still be identified for exemption.

We fixed our documentation in #4407. Please note that this issue will automatically close once the changes are merged. If you require further assistance, please don't hesitate to create a new GitHub issue.
