### ISSUE TITLE
AddinCommands 1.3 for Excel and Word

### ISSUE THREAD

**Issue by OfficeAddins** [OfficeDev/office-js-docs-pr#4393]
Can **AddinCommands 1.3** be added to Excel and Word please

(https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/can-addincommands-1-3-be-added-to-excel-and-word-please/idi-p/4049569)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 175d0cdb-4314-fdea-be3c-e0a46fe53076
* Version Independent ID: dbec79fd-ff33-dc51-1599-b52a17df66d0
* Content: [Integrate built-in Office buttons into custom control groups and tabs - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/design/built-in-button-integration)
* Content Source: [docs/design/built-in-button-integration.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/design/built-in-button-integration.md)
* Service: **microsoft-365**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thank you for raising this issue @OfficeAddins. Based on [this page](https://learn.microsoft.com/en-us/javascript/api/requirement-sets?view=common-js-preview), it seems like AddinCommands 1.3 _is_ supported in Word and Excel. Let me assign this to @ElizabethSamuel-MSFT to investigate.

**Comment by ElizabethSamuel-MSFT** [comment]
@OfficeAddins Thanks for asking about this. We're investigating this.

**Comment by OfficeAddins** [comment]
Thank you for such a quick response.
I have added some more info to the following repo

https://github.com/OfficeAddins/AddinCommands/

**Comment by ElizabethSamuel-MSFT** [comment]
@OfficeAddins Thanks again for raising this. We've checked on this internally and confirmed that, for now, PowerPoint clients are the only Office clients that support this feature and requirement set. We're making a couple of updates to the documentation to clarify.

The feature crew considers Ideas when they're planning upcoming work, and the more upvotes, the better. If you can update the Idea with a link this issue and/or provide additional details, that might also help the case for adding other Office clients like Excel and Word by providing a real-life scenario.

Thanks again for your interest in Office Add-ins and in improving the platform.
