### ISSUE TITLE
Misleading variable name

### ISSUE THREAD

**Issue by Rick-Kirkham** [OfficeDev/office-js-docs-pr#4432]
The code sample in the **Delete shapes** section has these two lines:

```
const sheet = context.presentation.slides.getItemAt(0);
const shapes = sheet.shapes;
```

The variable `sheet` is probably copied from an Excel example. It should be `slide`. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9bcbfa95-c75b-102d-2f3f-45935f4c37bd
* Version Independent ID: b1d630f9-c744-5bfb-7288-89573a9efd57
* Content: [Work with shapes using the PowerPoint JavaScript API - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/powerpoint/shapes)
* Content Source: [docs/powerpoint/shapes.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/powerpoint/shapes.md)
* Service: **powerpoint**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by mnjit20** [comment]
Hello @Rick-Kirkham 
I just created a pull request to fix this issue. https://github.com/OfficeDev/office-js-docs-pr/pull/4634

**Comment by AlexJerabek** [comment]
Thanks for the PR @mnjit20! I'll get that checked in soon.

**Comment by mnjit20** [comment]
@AlexJerabek  thanks for approving and merging this PR.
