### ISSUE TITLE
February meeting video

### ISSUE THREAD

**Issue by lsmith77** [OfficeDev/office-js-docs-pr#4438]
I missed the call in February and was hoping to get access to the video recording.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a57f1340-d9ee-6bbc-c4ba-104b77840a6a
* Version Independent ID: 82ff44e8-1cdc-20e9-3ce6-d560de532b14
* Content: [Microsoft Office Add-ins community call - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/overview/office-add-ins-community-call)
* Content Source: [docs/overview/office-add-ins-community-call.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/overview/office-add-ins-community-call.md)
* Service: **microsoft-365**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @lsmith77,

Thanks for reaching out. We are working on uploading the February community call video. I'll assign this to @preethikakiru and @samantharamon, who can let you know when the video is up.

**Comment by samantharamon** [comment]
Hi @lsmith77,

You can find the February community call video at [Office Add-ins community call – February 2024](https://www.youtube.com/watch?v=uN084BPYpfY). I'll go ahead and close this issue, but please don't hesitate to open a new one if you need additional assistance.
