### ISSUE TITLE
Sideloading via Outlook for web is either impossible or at the very least does not work like this anymore.

### ISSUE THREAD

**Issue by jordevorstenbosch** [OfficeDev/office-js-docs-pr#4448]
Trying to sideload (or rather remove old sideloaded "apps")

The guide below does not work for the current web version of Outlook. I was able to resolve my issue through the desktop client, but ever since everything was moved to the new "Apps" section the management of old custom add-ins does not work. You can see them under "Manage your apps", but you do not get an option to remove them.

![Screenshot 2024-02-29 at 17 00 12](https://github.com/OfficeDev/office-js-docs-pr/assets/607106/fe6576c7-bb2e-4b61-a02a-93e017c369b2)

![Screenshot 2024-02-29 at 17 01 22](https://github.com/OfficeDev/office-js-docs-pr/assets/607106/061d6af6-b370-4a29-8b77-6886e65c25df)

I think we should at least have the option to remove lingering sideloaded add-ins even if the new Outlook no longer supports adding them.

The MacOS version still works as described.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3f364ae0-b7dd-edb3-b51b-8f6d0d99afbe
* Version Independent ID: 7dd1ce8f-16e7-88f8-f291-4afbe76baba7
* Content: [Sideload Outlook add-ins for testing - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/sideload-outlook-add-ins-for-testing?tabs=web#modern-outlook-on-the-web-and-new-outlook-on-windows-preview)
* Content Source: [docs/outlook/sideload-outlook-add-ins-for-testing.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/outlook/sideload-outlook-add-ins-for-testing.md)
* Service: **outlook**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for reporting this. @samantharamon, could you please investigate?

**Comment by samantharamon** [comment]
Hi @jordevorstenbosch,

We're currently updating the sideloading article to clarify guidance for each Outlook client. To remove a sideloaded add-in, you'll need to go to <https://aka.ms/olksideload> from a browser (this is the same method to manually sideload an add-in on Outlook on Windows and on the web). This loads Outlook on the web, then displays the Add-Ins for Outlook dialog after a few seconds. In the dialog, go to **My add-ins**, select the ellipsis on the add-in you want to remove, then select **Remove**.

![image](https://github.com/OfficeDev/office-js-docs-pr/assets/15154970/f37a5dad-0a36-4398-b464-21d041b49f43)

**Comment by jordevorstenbosch** [comment]
> Hi @jordevorstenbosch,
> 
> We're currently updating the sideloading article to clarify guidance for each Outlook client. To remove a sideloaded add-in, you'll need to go to https://aka.ms/olksideload from a browser (this is the same method to manually sideload an add-in on Outlook on Windows and on the web). This loads Outlook on the web, then displays the Add-Ins for Outlook dialog after a few seconds. In the dialog, go to **My add-ins**, select the ellipsis on the add-in you want to remove, then select **Remove**.
> 
> ![image](https://private-user-images.githubusercontent.com/15154970/309043001-f37a5dad-0a36-4398-b464-21d041b49f43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MzgzNDcsIm5iZiI6MTcwOTYzODA0NywicGF0aCI6Ii8xNTE1NDk3MC8zMDkwNDMwMDEtZjM3YTVkYWQtMGEzNi00Mzk4LWI0NjQtMjFkMDQxYjQ5ZjQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDExMjcyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlYzljOGZjYTAzYWE1ZGRlMjFlM2Y4MWQ4Yjk5ZjU2MWE2OWU1ZTQ3Zjc0Yjg3ZmY1NmMyMjMzYWE1MGE0MjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nJv22nIlewnGf66ez7GyAKBKYb3JCPrQ5gwZWtWFt3o)

Could have sworn there was a URL like that, so thank you. I spent an hour trying to find it, to no avail.

I'll keep that URL in my bookmarks until everything has been fully transferred.
