### ISSUE TITLE
Inquiry if script tag in commands.html allows use of remote scripts.

### ISSUE THREAD

**Issue by glr0221** [OfficeDev/office-js-docs-pr#4454]
In the documentation, we have the following code for the commands.html file : 
```
<script type="text/javascript" src="https://appsforoffice.microsoft.com/lib/beta/hosted/office.js"></script>
<script type="text/javascript" src="../spamreporting/spamreporting.js"></script>
```

Does this mean that if I add a new src, then I will be able to use the external library? For example : 
```
<script type="text/javascript" src="https://appsforoffice.microsoft.com/lib/beta/hosted/office.js"></script>
<script type="text/javascript" src="../spamreporting/spamreporting.js"></script>
<script src="https://cdn.jsdelivr.net/npm/md5-js-tools@1.0.2/lib/md5.min.js"></script>
```

Then inside the spamreporting.js file, I will invoke the following : 
```
let hashedData = MD5.generate("StringForHashing")
console.log(hashedData)
```

I hope this made sense. Thank you very much.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 695f4ab9-5e6f-3b7a-04fe-3f7769958e98
* Version Independent ID: 695f4ab9-5e6f-3b7a-04fe-3f7769958e98
* Content: [Implement an integrated spam-reporting add-in (preview) - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/spam-reporting)
* Content Source: [docs/outlook/spam-reporting.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/outlook/spam-reporting.md)
* Service: **outlook**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @glr0221,

I believe that should work as expected. Are you seeing behavior to the contrary?

**Comment by glr0221** [comment]
Thanks @AlexJerabek . I will test this once I get the chance and update the ticket with my results one more time. Thanks again.
