### ISSUE TITLE
why Enable Disable not working on web word?

### ISSUE THREAD

**Issue by junaid042** [OfficeDev/office-js-docs-pr#4456]
I have created a taskpane Word add-in using `yo office` and i am using shared runtime in this add-in this is working correctly on desktops Word but Enable and disable not working on online web version this is my manifest.xml file [link](https://drive.google.com/file/d/1inyben_jSvSg8GiqOs1j8YDdUCAlXgSM/view?usp=sharing) 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5c7b653d-1bd6-a032-2046-6d6a2ad2b203
* Version Independent ID: 7165a66d-bc9a-dce9-91c4-7c1209d1324e
* Content: [Enable and Disable Add-in Commands - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/design/disable-add-in-commands)
* Content Source: [docs/design/disable-add-in-commands.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/design/disable-add-in-commands.md)
* Service: **microsoft-365**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@junaid042 Thanks for your interest in this feature. This feature is available for Excel production add-ins. However, although the feature is in preview for Word, it's not available for Word on the web.

To upvote or request this feature, please use [Microsoft 365 Developer Platform Ideas Forum](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform).

Thanks.
