### ISSUE TITLE
npm start gives error in jquery project. it works fine with react project.

### ISSUE THREAD

**Issue by manish-shukla01** [OfficeDev/office-js-docs-pr#446]
here is the error it gives :
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@6.4.1
3 info using node@v8.12.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle my-office-add-in@0.1.0~prestart: my-office-add-in@0.1.0
6 info lifecycle my-office-add-in@0.1.0~start: my-office-add-in@0.1.0
7 verbose lifecycle my-office-add-in@0.1.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle my-office-add-in@0.1.0~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/manishmac/Documents/technical/officejq/my-addin/My Office Add-in/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin
9 verbose lifecycle my-office-add-in@0.1.0~start: CWD: /Users/manishmac/Documents/technical/officejq/my-addin/My Office Add-in
10 silly lifecycle my-office-add-in@0.1.0~start: Args: [ '-c',
10 silly lifecycle   'webpack-dev-server --mode development --https --key ./certs/server.key --cert ./certs/server.crt --cacert ./certs/ca.crt --port 3000' ]
11 silly lifecycle my-office-add-in@0.1.0~start: Returned: code: 1  signal: null
12 info lifecycle my-office-add-in@0.1.0~start: Failed to exec start script
13 verbose stack Error: my-office-add-in@0.1.0 start: `webpack-dev-server --mode development --https --key ./certs/server.key --cert ./certs/server.crt --cacert ./certs/ca.crt --port 3000`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.&lt;anonymous&gt; (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.&lt;anonymous&gt; (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:915:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid my-office-add-in@0.1.0
15 verbose cwd /Users/manishmac/Documents/technical/officejq/my-addin/My Office Add-in
16 verbose Darwin 17.7.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v8.12.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error my-office-add-in@0.1.0 start: `webpack-dev-server --mode development --https --key ./certs/server.key --cert ./certs/server.crt --cacert ./certs/ca.crt --port 3000`
22 error Exit status 1
23 error Failed at the my-office-add-in@0.1.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c4ddde7-f1fd-44ba-fba1-0ae9d0131df7
* Version Independent ID: d946ffe6-f29f-1563-b679-121090ba60a1
* Content: [Build your first Excel add-in using jQuery](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-jquery?tabs=visual-studio-code)
* Content Source: [docs/quickstarts/excel-quickstart-jquery.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/quickstarts/excel-quickstart-jquery.md)
* Product: **office 365**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by kbrandl** [comment]
@manish-shukla01 thank you for reporting this issue and sorry to hear that you've run into problems with using Yo Office to create an Excel add-in; we'll investigate.

**Comment by kbrandl** [comment]
@manish-shukla01 thanks again for reporting this issue. Upon further investigation, I suspect that your problem may be resolved by installing the latest version of Yeoman and the Yeoman generator for Office Add-ins. Please run the following command to install the latest versions of these tools globally, and then try creating/testing a new add-in project afterwards:

    npm install -g yo generator-office

I'm going to close this issue now, but please feel free to re-open it if installing/using the latest versions of Yeoman and the Yeoman generator for Office Add-ins doesn't solve your problem.

**Comment by canciftcioglu** [comment]
i have this issue,too. I try to create an outlook add-in project with yo generator. When ı create a project with jquery  framework npm start gives error. But it works fine with react framework. 
P.S. : i tried to install latest yo and generator office

> @manish-shukla01 thanks again for reporting this issue. Upon further investigation, I suspect that your problem may be resolved by installing the latest version of Yeoman and the Yeoman generator for Office Add-ins. Please run the following command to install the latest versions of these tools globally, and then try creating/testing a new add-in project afterwards:
> 
> ```
> npm install -g yo generator-office
> ```
> I'm going to close this issue now, but please feel free to re-open it if installing/using the latest versions of Yeoman and the Yeoman generator for Office Add-ins doesn't solve your problem.

i have this issue,too. I try to create an outlook add-in project with yo generator. When ı create a project with jquery  framework npm start gives error. But it works fine with react framework. 
P.S. : i tried to install latest yo and generator office

**Comment by vyasrao22** [comment]
@kbrandl I am developing an office addin with Excel and using Yo Office. I am able to do npm start but however the webpack prod mode is giving some issues on es2015, regenerator runtime. I solved this by setting preset as es2015 however, still not able to solve the below error. 
``E:\ADDIN\bfm\models\dist\app.js:32
function(t){var e,n,r,o,i,s,u,a,c,l,f,p,d,h,v,y,g,m,b,x="sizzle"+1*new Date,w=t.document,_=0,j=0,S=st(),O=st(),E=st(),T=function(t,e){return t===e&&(f=!0),0},A={}.hasOwnProperty,k=[],P=k.pop,C=k.push,N=k.push,I=k.slice,D=function(t,e){for(var n=0,r=t.length;n<r;n++)if(t[n]===e)return n;return-1},M="checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped",L="[\\x20\\t\\r\\n\\f]",F="(?:\\\\.|[\\w-]|[^\0-\\xa0])+",R="\\["+L+"*("+F+")(?:"+L+"*([*^$|!~]?=)"+L+"*(?:'((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\"|("+F+"))|)"+L+"*\\]",U=":("+F+")(?:\\((('((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\")|((?:\\\\.|[^\\\\()[\\]]|"+R+")*)|.*)\\)|)",q=new RegExp(L+"+","g"),W=new RegExp("^"+L+"+|((?:^|[^\\\\])(?:\\\\.)*)"+L+"+$","g"),H=new RegExp("^"+L+"*,"+L+"*"),B=new RegExp("^"+L+"*([>+~]|"+L+")"+L+"*"),z=new RegExp("="+L+"*([^\\]'\"]*?)"+L+"*\\]","g"),$=new RegExp(U),V=new RegExp("^"+F+"$"),G={ID:new RegExp("^#(

TypeError: Cannot read property 'document' of undefined
    at Object.<anonymous> (E:\ADDIN\bfm\models\dist\app.js:32:83167)
    at Object.<anonymous> (E:\ADDIN\bfm\models\dist\app.js:32:83291)
    at n (E:\ADDIN\bfm\models\dist\app.js:1:172)
    at Object.defineProperty.value (E:\ADDIN\bfm\models\dist\app.js:7:67766)
    at n (E:\ADDIN\bfm\models\dist\app.js:1:172)
    at E:\ADDIN\bfm\models\dist\app.js:1:964
    at Object.<anonymous> (E:\ADDIN\bfm\models\dist\app.js:1:975)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
``

can you help me out please?

**Comment by kbrandl** [comment]
@vyasrao22 sorry to hear that you're running into this problem. I'm going to reopen this issue and transfer it to the **OfficeDev/generator-office** repository, which the folks who build/manage Yo Office monitor for issues like this.

**Comment by kbrandl** [comment]
@vyasrao22 actually, since you've logged a (new/separate) issue about this problem (https://github.com/OfficeDev/office-js-docs-pr/issues/787) I'm going to close this issue and won't be transferring it to **OfficeDev/generator-office** as I previously indicated. I'll transfer the other issue that repo though, and you should receive feedback from the product team there.
