### ISSUE TITLE
Customizing button text "Send anyway"

### ISSUE THREAD

**Issue by ThanhVuNTQ** [OfficeDev/office-js-docs-pr#4469]
Hi there,

I am using Smart Alerts for my add-in. I would like to be able to customize the text of the **"Send anyway"** button. 
Is it possible to customize the button text?
Please help me. Thanks a lot!

![image](https://github.com/OfficeDev/office-js-docs-pr/assets/152581121/5b3be54e-8768-439e-ac8e-aad7f2fbff5b)

**Comment by AlexJerabek** [comment]
Thank you for your question. @samantharamon, is this possible with the current APIs?

**Comment by samantharamon** [comment]
Hi @ThanhVuNTQ,

Unfortunately, you can't customize the text of the **Send Anyway** button. You can only customize the **Don't Send** button (please note that this is currently in preview). However, if you have a use case for customizing the **Send Anyway** button, we recommend submitting a feature request for this on our [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions).
