### ISSUE TITLE
Don't see Attach Debugger when click top right corner of the task pane add-in

### ISSUE THREAD

**Issue by salingun** [OfficeDev/office-js-docs-pr#447]
Hello,
I had installed Visual Studio 2015 with Update 3 and create MS Project add-in by npm yo office and run it. But when I click top right corner of the task pane the same this guide,  Attach Debugger doesn't appear to choose.
I need a help for this issue, thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8b1badd-9a43-6935-a6e6-76508e7f9741
* Version Independent ID: bdeabb00-8eeb-07a2-0de9-967f018a2c8a
* Content: [Attach a debugger from the task pane](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/attach-debugger-from-task-pane)
* Content Source: [docs/testing/attach-debugger-from-task-pane.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/attach-debugger-from-task-pane.md)
* Product: **office 365**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by salingun** [comment]
Here my screen cap of VS version and running Add-in
![image](https://user-images.githubusercontent.com/21010188/46601192-9be51200-cb16-11e8-969e-0c4d0886ffcd.png)

![image](https://user-images.githubusercontent.com/21010188/46601543-9c31dd00-cb17-11e8-97cb-aaf37ed11acc.png)

**Comment by Reezaali** [comment]
@salingun - can you verify that your version of Office meets the following criteria? 

"In Office 2016 for Windows, Build 77xx.xxxx or later,..."

**Comment by salingun** [comment]
Thanks for replying @Reezaali  . Does it mean can't debug add-in in Office 2013? I need build an add-in for office 2013, maybe I will have difficulty with this.

**Comment by Reezaali** [comment]
Would using IEChooser help? For more information, see [this topic](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-add-ins-using-f12-developer-tools-on-windows-10).

**Comment by salingun** [comment]
My computer isn't available windows 10 but I have decided to install it on a virtual machine and develop my add-in on it because I think that's the only way to debug. Thanks @Reezaali

**Comment by Reezaali** [comment]
@salingun - here are steps to attach the Visual Studio debugger to all of the available Iexplore.exe processes:
1.	In Visual Studio, choose DEBUG, Attach to Process.
2.	In the Attach to Process dialog box, choose all of the available Iexplore.exe processes, and then choose the Attach button.

**Comment by salingun** [comment]
hello @Reezaali , sorry for my late reply, It seems that I can't debug after attach to process the same your guide, but I installed windows 10 and can debug normally on it with F12, Thanks

**Comment by Reezaali** [comment]
I added a note to the topic with the Visual Studio only steps.
