### ISSUE TITLE
Customizing icon in Smart Alert

### ISSUE THREAD

**Issue by ThanhVuNTQ** [OfficeDev/office-js-docs-pr#4475]
Hi there,
I am using Smart Alerts for my add-in. I would like to be able to customize the close icon in Smart Alert.
I couldn't find any ways to change this icon in the document.
Please help me. Thanks a lot!
![image](https://github.com/OfficeDev/office-js-docs-pr/assets/152581121/57948bfe-5d20-41aa-9fbe-db4919a7a32d)

**Comment by AlexJerabek** [comment]
Thanks for reporting this. @samantharamon, can you please investigate?

**Comment by samantharamon** [comment]
Hi @ThanhVuNTQ,

Thanks for reaching out. Unfortunately, you can't change the red 'X' icon in the dialog. If you need this functionality for your use case, we recommend submitting a feature request for this on our [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions).
