### ISSUE TITLE
Can't sideload Add-in to new Outlook for Windows

### ISSUE THREAD

**Issue by ThanhVuNTQ** [OfficeDev/office-js-docs-pr#4476]
Hello,

I am currently experiencing an issue with displaying an add-in on the new Outlook for Windows, even though I have successfully sideloaded the add-in. However, the add-in is not appearing on the Outlook interface. Surprisingly, it is being displayed correctly when using Outlook on the web.
Previously, when the "Get Add-in" button was available in new Outlook for Windows, I was able to sideload add-ins without any problems. However, in the current version of Outlook for Windows, the "Get Add-in" button is no longer present. As a result, I am required to sideload add-ins through the web version in order to synchronize them with Outlook for Windows.

I would like to inquire about any possible solutions to address this problem on Outlook for Windows. Thank you!

https://support.microsoft.com/en-us/office/getting-started-with-the-new-outlook-for-windows-656bb8d9-5a60-49b2-a98b-ba7822bc7627

**Comment by AlexJerabek** [comment]
Hi @ThanhVuNTQ,

According to the information in [Sideload Outlook add-ins for testing](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/sideload-outlook-add-ins-for-testing?tabs=windows-web#sideload-manually), it can take up to 24 hours for sideloaded add-ins to appear in the new Outlook Windows client. If you used the sideloading command at https://aka.ms/olksideload, the add-in should eventually appear in Windows.

Please let us know if that is not the case.

**Comment by ThanhVuNTQ** [comment]
@AlexJerabek  I am developing the Add-in for Outlook by Yo Office tool. In the localhost environment, I used the sideloading command at https://aka.ms/olksideload, the add-in appeared in the new Outlook Windows. But when I click the add-in, it can't show its task pane.

**Comment by ThanhVuNTQ** [comment]
> Hi @ThanhVuNTQ,
> 
> According to the information in [Sideload Outlook add-ins for testing](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/sideload-outlook-add-ins-for-testing?tabs=windows-web#sideload-manually), it can take up to 24 hours for sideloaded add-ins to appear in the new Outlook Windows client. If you used the sideloading command at https://aka.ms/olksideload, the add-in should eventually appear in Windows.
> 
> Please let us know if that is not the case.

@AlexJerabek  I am developing the Add-in for Outlook by Yo Office tool. In the localhost environment, I used the sideloading command at https://aka.ms/olksideload, the add-in appeared in the new Outlook Windows. But when I click the add-in, it can't show its task pane.

**Comment by ThanhVuNTQ** [comment]
> > > Hi @ThanhVuNTQ,
> > > According to the information in [Sideload Outlook add-ins for testing](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/sideload-outlook-add-ins-for-testing?tabs=windows-web#sideload-manually), it can take up to 24 hours for sideloaded add-ins to appear in the new Outlook Windows client. If you used the sideloading command at https://aka.ms/olksideload, the add-in should eventually appear in Windows.
> > > Please let us know if that is not the case.
> > 
> > 
> > @AlexJerabek I am developing the Add-in for Outlook by Yo Office tool. In the localhost environment, I used the sideloading command at https://aka.ms/olksideload, the add-in appeared in the new Outlook Windows. But when I click the add-in, the task pane of the add-in can't be shown.
> 
> Have you found any solution? I am facing the same issue

Hello @digambar2002 
I found a solution.
Please use an admin account used to deploy the manifest.xml to the Microsoft 365 Admin Center instead of sideloading the add-in manually.
I tried using this solution, and the result was that the task pane of the add-in appeared normally.
Thanks !

**Comment by samantharamon** [comment]
Hi @ThanhVuNTQ,

Thanks for reporting this. I'm unable to reproduce this issue. I created an add-in project using the Yo Office tool and tried sideloading it using `npm start` and <https://aka.ms/olksideload>.

I know you tried the latter option, but have you tried `npm start` to automatically sideload the add-in by any chance?

If possible, could you also provide a screenshot of what you're seeing and the version and channel of your new Outlook on Windows client? To determine the version and channel, select **Settings** (gear icon) from the client title bar, then choose **General** > **About Outlook**.
