### ISSUE TITLE
internetHeaders for Appointments

### ISSUE THREAD

**Issue by DanilKorotenko** [OfficeDev/office-js-docs-pr#4490]
Related issue: #4388.

If I obtain Appointment via EWS with GetItem command and IncludeMimeContent flag on, I definitely can see internet headers in the mime content.

If someone send me invitation to event, I recieve an email with internet headers.

How can I add my custom internet headers to this process?

I mean:
1. User with my addin create an appointment.
2. My addin add custom information to that appointment.
3. User send invitation to that apoointment to another user
4. Another user open this appointment 
5. My addin on other user side read the custom information.

How I can implement this scenario?

Content: [Get and set internet headers - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/internet-headers)
Content Source: [docs/outlook/internet-headers.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/outlook/internet-headers.md)
Service: outlook
Sub-service: add-ins

**Describe your scenario**
What is the problem to solve?

**Which APIs or add-in features?**
What should be showcased in the sample? Are there features that need samples to better understand how to use them in add-ins?

**Comment by DanilKorotenko** [comment]
Additional info:
https://learn.microsoft.com/en-us/exchange/client-developer/web-service-reference/extendedfielduri

What ExtendedField is for?
Example XML shows how to set custom property. Ok. But what is next? Can this custom property go outside? For example, if I set custom property to appointment, and send invitation to it to other user. Can that user read that custom property with my addin? What practical use of extended fields?

**Comment by DanilKorotenko** [comment]
Post on Microsoft 365 Developer Platform Tech Community:

https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/add-the-internetheaders-property-to-the-office/idi-p/3660816

**Comment by ElizabethSamuel-MSFT** [comment]
@DanilKorotenko I'm checking with the feature crew to see if there's an EWS workaround.

**Comment by samantharamon** [comment]
Hi @DanilKorotenko,

Thank you for your patience.

Unfortunately, there isn't an EWS workaround for this scenario. After discussing this with the team, we've created a feature request item and added it to our backlog. We're unable to provide a timeline at this time, however, please keep an eye out for this feature in the future.

I will go ahead and close this issue, but if you require further assistance, please don't hesitate to create a new GitHub issue.

**Comment by DanilKorotenko** [comment]
Thank you for information.
