### ISSUE TITLE
Enable SSO in an Office Add-in using nested app authentication (preview) needs a few clarifications

### ISSUE THREAD

**Issue by GrumpyAL** [OfficeDev/office-js-docs-pr#4520]
I believe this document makes some assumptions that we already are familiar with implementing MSAL.  However, some of us coming from Office Add-ins where we invoke OAI functions to get tokens are not familiar with what to do for some of these steps.  For example, under "Initalize the public client application" it shows this line of code:

` pca = await msalBrowser.PublicClientNext.createPublicClientApplication(msalConfig);`

However, I'm not sure where msalBrowser came from here.  I have been able to use npm install and then use import to do something similar but I'm not sure if it's correct.

There is also an undeclared/unexplained variable in the token request "myLoginHint."  A link to the tokenRequest object in documentation may be helpful here, or just clarification that myLoginHint is a string and if it's required.

When working through setting up the app registration, more details would be helpful.  For example, the MSAL config uses the /common end-point but if you set your "supported account type" to single tenant, this will fail.  Also, it's not clear what needs to go in the SPA redirect.

`brk-multihub://your-add-in-domain`

Some clarification around what to put in "your-add-in-domain" would be helpful.  For example, if the add-in is hosted at https://example.com/taskpane.html what do you put for this value?

brk-multihub://example.com
brk-multihub://example.com/taskpane.html
something else?

I am currently stuck (I think) getting this SPA redirect value correct so any clarifications that can be added to the document would be helpful.

**Comment by GrumpyAL** [comment]
Before I posted this I somehow did not notice the code samples at the bottom.  I've only looked at one, (Outlook-Add-in-SSO-NAA) but it has very detailed instructions and is very easy to follow.  I think maybe just linking to this section from one of the early steps (e.g. See [code samples](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/enable-nested-app-authentication-in-your-add-in#code-samples) below for detailed instructions) would help a lot.

**Comment by samantharamon** [comment]
Thanks for reaching out, @GrumpyAL.

@davidchesnut, could you please investigate this?

**Comment by davidchesnut** [comment]
Hi @GrumpyAL, thanks for this feedback! I recently posted an update to that article which might address some of these issues. I'll make another pass based on your feedback and see if I can add more helpful links and descriptions. Thanks!

**Comment by davidchesnut** [comment]
Tracked in #4519

**Comment by davidchesnut** [comment]
Changes should be live by Tuesday.
