### ISSUE TITLE
Is there a url an admin can access to manually authorize the addin on behalf of his entire organization?

### ISSUE THREAD

**Issue by glr0221** [OfficeDev/office-js-docs-pr#4526]
Currently, I am testing the Nested App sample project in github. 
And during first run, a popup asks for the user to authorize the addin.
And if the account is an admin account, the authorize window can allow the authorization on behalf of the entire organization.

I would like to ask then, if it is possible for an admin to access a special url which can show that authorization window and enable/authorize the addin for the entire organization without running the addin. I remember that this is doable for SSO-OBO flow but could not remember the exact url off the top of my head.  What I remember is that it contains something like this : 

https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=xxxxxxxx&scope=yyyyyy&.......

This is assuming that the scope is a fixed value.

Thank you very much.

**Comment by AlexJerabek** [comment]
Hi @glr0221,
Thanks for raising this question. @davidchesnut, could you please investigate?

**Comment by Rick-Kirkham** [comment]
I remember that too, but the URL is no longer in any of our developer docs. Would it suit your purposes to grant consent through the M365 Admin portal?

**Comment by glr0221** [comment]
Thank you @Rick-Kirkham @AlexJerabek 

Yes, consent-granting via the M365 admin portal would be awesome.  We will be showing/teaching these steps to our customer admins.

Thanks again.

**Comment by Rick-Kirkham** [comment]
@glr0221 I think you can do that now. Steps are below. I think there's a reason why that special URL is no longer in our docs. It probably doesn't work anymore. @davidchesnut I'll leave it to you to decide if this should be closed or kept open as a doc request. If the latter, you can assign to me. 

![Get2ConsentUI-1](https://github.com/OfficeDev/office-js-docs-pr/assets/9088056/49ebe929-5c7c-4851-8c69-4ced08723ee0)
![Get2ConsentUI-2](https://github.com/OfficeDev/office-js-docs-pr/assets/9088056/a2421f06-bad0-4f56-b019-1c68ad64caaa)
![Get2ConsentUI-3](https://github.com/OfficeDev/office-js-docs-pr/assets/9088056/14efeedc-b73d-479c-b3c7-24ce92ec2e25)
![Get2ConsentUI-4](https://github.com/OfficeDev/office-js-docs-pr/assets/9088056/1dae8808-46c6-44d2-844b-fff8f2f5586e)
![Get2ConsentUI-5](https://github.com/OfficeDev/office-js-docs-pr/assets/9088056/97c0a214-0477-4d76-bec6-a8de32f4c3c1)
![Get2ConsentUI-6-7](https://github.com/OfficeDev/office-js-docs-pr/assets/9088056/0e46a6fb-8a4b-4552-bd55-67f833c7376e)
![Get2ConsentUI-8-9](https://github.com/OfficeDev/office-js-docs-pr/assets/9088056/6cab2bde-a740-4a61-834b-a256bd3d2eb8)

**Comment by davidchesnut** [comment]
Hi @glr0221, Hope the URL and information above is helpful. Please reopen if this issue is still not resolved. Thanks!

**Comment by glr0221** [comment]
Sorry for the late response. But I just wanted to say THANK YOU to all of you. @Rick-Kirkham  @davidchesnut  @mattgeim @AlexJerabek . I got the response I needed from all the responses you gave me. Thank you again.
