### ISSUE TITLE
Permission Revocation.

### ISSUE THREAD

**Issue by glr0221** [OfficeDev/office-js-docs-pr#4527]
I know this might have been answered in some other Microsoft reference, but can we have a section in the document that guides us how to revoke a granted permission? 

Thank you very much.

**Comment by AlexJerabek** [comment]
Hi @glr0221,

Could you please provide a little more context? Are you talking about permissions [granted through the add-in](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/requesting-permissions-for-api-use-in-content-and-task-pane-add-ins) or through SSO/NAA?

**Comment by glr0221** [comment]
@AlexJerabek 

Thank you for taking a look on this one. As for context, I just used the NAA-SSO sample in your github repository. When you run the said sample, it will ask you for two permissions 'User.read' and 'File.read'. To successfully run the sample, I approved/granted the permissions. Now that I have finished testing, I wanted to revoke the granted permissions without deleting the app. So I went to my azure account and revoked the permissions.

I then went back and re-ran the NAA-SSO sample but unfortunately the application still ran and it seemed that the permissions were not revoked. I was thinking that this might either be because (1) it takes time for the revocation to take effect or (2) I might have revoked it incorrectly. 

So I wrote this ticket to ask for assistance on how to properly revoke permissions granted via NAA-SSO. 

I hope that gave the ticket more context. 

Thank you very much.

**Comment by Rick-Kirkham** [comment]
The steps to revoke consent are in the following screen shots. I've changed this to "doc request". 
@AlexJerabek Reassign to me if you want, or I can send you the screen shots.

![Get2ConsentUI-1](https://github.com/OfficeDev/office-js-docs-pr/assets/9088056/152803c4-814f-48c0-a07f-a480e2037b7e)
![Get2ConsentUI-2](https://github.com/OfficeDev/office-js-docs-pr/assets/9088056/9ebfc2c4-4bab-42ef-b1ba-e126809c570c)
![Get2ConsentUI-3](https://github.com/OfficeDev/office-js-docs-pr/assets/9088056/eed5edb8-b0a6-4b38-840a-282140e2eeb9)
![Get2ConsentUI-4](https://github.com/OfficeDev/office-js-docs-pr/assets/9088056/5ff2a137-bea2-4eed-b5dd-56b1fbc95d17)
![Get2ConsentUI-5](https://github.com/OfficeDev/office-js-docs-pr/assets/9088056/18b3d58f-653b-4967-add6-8fd4b262b93a)
![Get2ConsentUI-6-7](https://github.com/OfficeDev/office-js-docs-pr/assets/9088056/86907bd2-93c4-47c2-aa3d-a6625864d717)
![RevokeConsentUI-8-9-10](https://github.com/OfficeDev/office-js-docs-pr/assets/9088056/9eb704e6-723e-4e15-9022-3488bfb237cf)
