### ISSUE TITLE
Dead link - Get Script Lab for Excel, PowerPoint, and Word

### ISSUE THREAD

**Issue by TDroogers** [OfficeDev/office-js-docs-pr#4529]
The `Get Script Lab for Excel, PowerPoint, and Word` button on [this page](https://learn.microsoft.com/en-us/office/dev/add-ins/overview/explore-with-script-lab) forwards tot a 404 page.

**Comment by Rick-Kirkham** [comment]
I'll fix this. The URL has changed. The term "/product" now precedes "/office".

**Comment by Rick-Kirkham** [comment]
@samantharamon has beat me to it: [PR 4530](https://github.com/OfficeDev/office-js-docs-pr/pull/4530)

**Comment by TDroogers** [comment]
Thanks
