### ISSUE TITLE
update the table  structure 

### ISSUE THREAD

**Issue by charangoldenhills** [OfficeDev/office-js-docs-pr#4531]
i have created a table by using the js api
code is
 create: async (
      columns: string[],
      data: Record<string, TableCell>[],
      metadata?: { [key: string]: any },
      // range: number[] = []
    ) => {
      return Excel.run(async context => {
        const sheet = context.workbook.worksheets.getActiveWorksheet();
        const selectedRange = context.workbook.getSelectedRange();
        selectedRange.load('address');
        await context.sync();
        const userSelectedCell = splitCharAndNumber(selectedRange.address.split('!')[1]);
        let cellRowPoint = userSelectedCell[1];
        let cellColumnPoint = charToNumber(userSelectedCell[0]);
       
        const currentCell = sheet.getCell(cellRowPoint, cellColumnPoint);
        const tableRange = await getTableRange(context, columns, cellRowPoint, cellColumnPoint);
        console.log(tableRange, '--------------------------------------- tabel range');
        // Sheet1!F11:Sheet1!H11 ---------------------------------------
        const table: Excel.Table = currentCell.worksheet.tables.add(tableRange, true);
        const formattedColumns = columns.map(column => formatItemName(column));
        console.log('format data', formattedColumns, 'tabel', table);
        table.getHeaderRowRange().values = [formattedColumns];
        table.load('name');
        const rows = data.map(item => columns.map(key => item[key]));
        rows.length > 0 && table.rows.add(0, rows);
        await context.sync();
        const settings = context.workbook.settings;
        if(metadata){
          metadata.filters.tableName = table.name;
        }
        settings.add(table.name, metadata);
        await context.sync();
        console.log("creating the tabel set ",table)
        return table;
      });
    },
    --------------------------------------
    i want to update the table 
   1. update the range according to the new data set
   2.columns should be loaded according to the new data 
   3. existing table name should be present and data should be new data along with the range i.e, structure is new
   ---------------------
   updateTable: async (
      newColumns: string[],
      newData: Record<string, TableCell>[],
      tableName: string,
      metadata?: { [key: string]: any },
    ) => {
      return Excel.run(async context => {
        const sheet = context.workbook.worksheets.getActiveWorksheet();
        
        // Find the table by name
        const table = sheet.tables.getItem(tableName);
    
        await context.sync();
        table.load("name");
    
        // Clear existing data and format
        table.getDataBodyRange().clear();
        table.getHeaderRowRange().clear();
        // table.getRange().clear();
        console.log("Clearing the existing data");
    
        // Set new column headers
        const formattedColumns = newColumns.map(column => formatItemName(column));
        table.getHeaderRowRange().values = [formattedColumns];
        await context.sync();
    
   
       
    
       
    
        // Add new data to the existing table range
        const rows = newData.map(item => newColumns.map(key => item[key]));
        if (rows.length > 0) {
          table.rows.add(0, rows); // Add new rows to the existing table
        }
    
        // Update metadata if provided
        const settings = context.workbook.settings;
        if (metadata) {
          metadata.filters = { tableName }; // Set the table name in the metadata
          settings.add(tableName, metadata);
        }
    
        await context.sync();
    
        return table;
      });
    }
    ----------------------------------------------
    please suggest the answer for this.....

**Comment by davidchesnut** [comment]
Hi @charangoldenhills, can you please provide more information about what is going wrong? Did the table not get created properly? Is it not updating properly? Also if you can provide which platform you are on (Mac, browser, Windows)? Thanks!
