### ISSUE TITLE
typo in article: Understand when and how to use Office Open XML in your Word add-in

### ISSUE THREAD

**Issue by hyattaw** [OfficeDev/office-js-docs-pr#4578]
[xlmns](https://learn.microsoft.com/en-us/office/dev/add-ins/word/create-better-add-ins-for-word-with-office-open-xml#:~:text=xml%20that%20the-,xlmns,-%3Aa%20namespace%20(the)

there is a typo: xlmns instead of xmlns. The above link should get you there.

**Comment by ElizabethSamuel-MSFT** [comment]
@hyattaw Thanks for raising this issue. We'll get this fixed. Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@hyattaw The fix has been made and should be published by early next week. Thanks again!
