### ISSUE TITLE
Content add-ins for Powerpoint cannot export website inside an iframe in web version

### ISSUE THREAD

**Issue by bienluongdss** [OfficeDev/office-js-docs-pr#4585]
I am developing an add-in for Powerpoint. It's a content add-ins that display an external link in an Iframe.

In the desktop version of Powerpoint, everything works fine, including export and print. But in the web version, when I try to export the slides to PDF or print, the content is always blank.
I find that it happens with every website link, not just the website that I tried to display.

Does anyone know what might have caused this and how to resolve it?
Thanks

**Comment by quangnguyendss** [comment]
Do anyone know this???
