### ISSUE TITLE
How to set a Starting document

### ISSUE THREAD

**Issue by Mahmoud3193** [OfficeDev/office-js-docs-pr#4590]
I need to know how to set an existing excel file to debug my add-in
Can any one please help me?

**Comment by AlexJerabek** [comment]
Hi @Mahmoud3193,

You should be able to sideload an add-in into any existing Excel file. The sideloading instructions can be found [here](https://learn.microsoft.com/en-us/office/dev/add-ins/testing/sideload-office-add-ins-for-testing).

@millerds, is there a way to specify an existing file when running a project created through yo office?

**Comment by Mahmoud3193** [comment]
I'm sorry but the. VS code instructions only applies for the web, is there a way to side load to a desktop file

**Comment by AlexJerabek** [comment]
For desktop, you'll have to follow the instructions for sideloading using a network share, found [here](https://learn.microsoft.com/en-us/office/dev/add-ins/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins).
