### ISSUE TITLE
have error on MessageComposeCommandSurface

### ISSUE THREAD

**Issue by Usamawahabkhan** [OfficeDev/office-js-docs-pr#4599]
we i tried to add MessageComposeCommandSurface (×) Error: {"error":{"code":"BadRequest","message":"Sideloading rejected by Exchange"}}

**Comment by AlexJerabek** [comment]
Hi @Usamawahabkhan,

I'm sorry to hear you're having trouble. Could you please provide some more context? Is there a page in the documentation that you are using? Or is there a sample you started with?

Thanks!
