### ISSUE TITLE
How to deploy Add-in on Azure When you are invited from someone and how

### ISSUE THREAD

**Issue by junaid042** [OfficeDev/office-js-docs-pr#4607]
I don't know How can I Publish my Add-in if someone invited me and gave some permisions. how can I Publish my add-in?

**Comment by junaid042** [comment]
After Accepting Invitation I have this view on Azure

![image](https://github.com/OfficeDev/office-js-docs-pr/assets/134502135/30721f37-17b8-4c3b-829d-83b4b3f64467)

**Comment by AlexJerabek** [comment]
Hi @junaid042,

Have you followed the instructions for [deploying from Visual Studio Code](https://learn.microsoft.com/en-us/office/dev/add-ins/publish/publish-add-in-vs-code) or [deploying from Visual Studio](https://learn.microsoft.com/en-us/office/dev/add-ins/publish/host-an-office-add-in-on-microsoft-azure)?

Beyond that, this sounds like it might be an issue with the Azure permissions in your account. I'm not sure what you mean by someone "invited" you. Could you please clarify?
