### ISSUE TITLE
Conflicting information on deployment options for Outlook add-ins

### ISSUE THREAD

**Issue by johnthad** [OfficeDev/office-js-docs-pr#4613]
The table [Deployment options for Outlook add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/publish/publish#deployment-options-for-outlook-add-ins) implies that Sideloading, AppSource, and Exchange Server are the _only_ deployment options for Outlook add-ins.

However, the table at [What controls are available on the Integrated Apps portal?](https://learn.microsoft.com/en-us/microsoft-365/admin/manage/test-and-deploy-microsoft-365-apps?view=o365-worldwide#what-controls-are-available-on-the-integrated-apps-portal) shows that Outlook add-ins "can be managed from the Integrated apps portal on the Microsoft 365 admin center." Indeed this method of deployment seems to work. So the [Deployment options for Outlook add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/publish/publish#deployment-options-for-outlook-add-ins) should be corrected.

**Comment by AlexJerabek** [comment]
Hi @johnthad,

Thank you for pointing this out. Outlook add-ins can be deployed through Integrated Apps. I'll update the documentation to reflect this.
