### ISSUE TITLE
Angular CLI steps out of date

### ISSUE THREAD

**Issue by jeffkt95** [OfficeDev/office-js-docs-pr#463]
Step 2 under "Update the app" is now out of date with Angular 6. The .angular-cli.json file is deprecated in lieu of angular.json. It is not just a name change; the file format has changed as well. I'm trying to determine how to map your instructions for .angular-cli.json to angular.json.
See the following:
https://stackoverflow.com/questions/42395200/where-is-the-file-angular-cli-json-in-the-new-angular-cli-version
https://blog.angular.io/version-6-of-angular-now-available-cc56b0efa7a4

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92388aeb-7561-deae-26df-aab50feb71b8
* Version Independent ID: aa282880-d613-d7d8-ddb3-6a61c8a155bf
* Content: [Build an Excel add-in using Angular](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-get-started-angular#update-the-app)
* Content Source: [docs/excel/excel-add-ins-get-started-angular.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/excel-add-ins-get-started-angular.md)
* Product: **office 365**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by jeffkt95** [comment]
I found help for where to put the sslKey and sslCert options. Also, "ssl": true is required.
https://stackoverflow.com/questions/49881328/angular-6-angular-json-add-ssl-in-configuration

**Comment by kbrandl** [comment]
@jeffkt95 thanks for reaching out and sorry to hear that you've run into issues with the Excel - Angular quick start. We'll be updating this quick start soon to address the issues that you've described. In the meantime, the new recommended way to create an Excel add-in using the Angular framework is to use Yo Office to create the add-in project and choose `Office Add-in project using Angular framework` when you're asked to choose a project type.

![image](https://user-images.githubusercontent.com/3019529/46886793-b964f500-ce10-11e8-9c81-3ec39d56b1c8.png)

**Comment by kbrandl** [comment]
@jeffkt95 we've significantly revised this quick start, to reflect that the Yeoman generator for Office Add-ins is now the recommended way of generating an Office Add-in project using the Angular framework. Please give the new instructions a try and feel free to reach out again if you have any trouble.
