### ISSUE TITLE
Outlook Exchange Online: When Plan to GA: Enable SSO in an Office Add-in using nested app authentication (preview)

### ISSUE THREAD

**Issue by hello-chenchen** [OfficeDev/office-js-docs-pr#4633]
we notice [Enable SSO in an Office Add-in using nested app authentication (preview)](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/enable-nested-app-authentication-in-your-add-in) is still in preview. but exchange online is will be turned off by default for all Exchange Online tenants in October 2024. https://devblogs.microsoft.com/microsoft365dev/new-nested-app-authentication-for-office-add-ins-legacy-exchange-tokens-off-by-default-in-october-2024/?ocid=microsoft365dev_eml_tnp_autoid106_image

So, what's the plan for this issue?

**Comment by AlexJerabek** [comment]
Hi @hello-chenchen,

Nested app authentication (NAA) is still in preview. Although we are unable to provide a set release date at this time, we are trying to launch the feature as soon as possible. In the interim, we recommend using [Single sign-on with the on-behalf-of flow ](https://learn.microsoft.com/office/dev/add-ins/develop/sso-in-office-add-ins).

I will assign this issue to @davidchesnut, in case there is other guidance we can provide.

**Comment by davidchesnut** [comment]
Hi @hello-chenchen, Sorry cross-posting this from the duplicate issue. We plan to get NAA to GA very soon now. We'll also provide more information as we go on either the [Office Add-ins community](https://aka.ms/officeaddinscommunitycall) call or the [M365 developer blog](https://devblogs.microsoft.com/microsoft365dev). Also we will keep updating the sample with any changes that come along. Please take this time to try out NAA and let us know if you spot any issues. You're in the right location to let us know about any issues, or questions you have! 

Thanks!
David
