### ISSUE TITLE
Insert a built-in control group into a custom tab or into a custom group

### ISSUE THREAD

**Issue by dave-palt** [OfficeDev/office-js-docs-pr#4638]
**Article URL**
https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/design/built-in-button-integration.md

**Describe the problem**
The examples on the documentation above states that in order to have a built-in group inside a custom tab it's just a matter of adding `<OfficeGroup id="GROUP_ID_HERE" />` as child of CustomTab.
I tried using the same exact snippet containing only the OfficeGroup as in the example

```xml
          <ExtensionPoint xsi:type="PrimaryCommandSurface">
            <CustomTab id="Contoso.TabCustom1">
              <OfficeGroup id="Paragraph" />
              <Label resid="customTabLabel1" />
            </CustomTab>
          </ExtensionPoint>
```
But the ribbon is empty

I also tried to use a specific OfficeControl inside a Custom Group as per doc and the result is the same
```xml
          <ExtensionPoint xsi:type="ContosoRibbonTab">
            <CustomTab id="Contoso.TabCustom2">
              <Group id="Contoso.TabCustom2.group1">
                <Label resid="residCustomTabGroupLabel" />
                <Icon>
                  <bt:Image size="16" resid="blue-icon-16" />
                  <bt:Image size="32" resid="blue-icon-32" />
                  <bt:Image size="80" resid="blue-icon-80" />
                </Icon>
                <OfficeControl id="Superscript" />
              </Group>
              <Label resid="customTabLabel1" />
            </CustomTab>
          </ExtensionPoint>
```

short strings:
```xml
      <bt:ShortStrings>
        <bt:String id="customTabLabel1" DefaultValue="TESTTTT" />
      </bt:ShortStrings>
```

I am also confused about "Find the IDs of controls and control groups" which leads to this repo https://github.com/OfficeDev/office-control-ids which only contains the PowerPoint folder as also stated in [this issue](https://github.com/OfficeDev/office-control-ids/issues/1)

I tested with web version of word

**Screenshots**
<img width="926" alt="image" src="https://github.com/OfficeDev/office-js-docs-pr/assets/156987747/093fb119-73f9-4b84-9e0d-05ab2f4db036">

**Comment by AlexJerabek** [comment]
Hi @dave-palt,

Thanks for reaching out. I'm sorry to say that integrating existing Office groups into custom tabs only works in PowerPoint. As stated near the beginning of the linked article "The add-in feature and markup described in this article is only available in PowerPoint on the web, on Windows, and on Mac."

To request support for Word, please create a feature idea on [Microsoft 365 Developer Platform Tech Community](https://aka.ms/m365dev-suggestions) and describe your scenario. Items there help us gauge community need. I'll also tag @EsterBergen for awareness.

I'll leave this issue open until I make that PowerPoint-only note more obvious.
