### ISSUE TITLE
Will NAA-SSO be supported in Outlook with Chakra Javascript engines?

### ISSUE THREAD

**Issue by glr0221** [OfficeDev/office-js-docs-pr#4694]
Hello Office team,

I would just like to ask a question.
As the title suggests, will this be supported in trident systems or systems that use Chakra Javascript engines. 

Thank you very much.

**Comment by AlexJerabek** [comment]
Hi @glr0221,

Could you please clarify which feature you're asking about for support? Thanks!

**Comment by glr0221** [comment]
Hello @AlexJerabek. 

Sorry about the vagueness of the question. I was referring to NAA-SSO. 
Thank you big time!

**Comment by AlexJerabek** [comment]
Thank you for the clarification. Let me ask internally and get back to you.

**Comment by AlexJerabek** [comment]
Hi @glr0221,

No, NAA will not be supported on Chakra. What build and platform are you working with for Outlook that still uses the Edge WebView?

**Comment by glr0221** [comment]
Thank you @AlexJerabek .

The biggest concern I have NAA-SSO for Monthly Enterprise channels and some semi-annual enterprise channels. Like in this ticket : https://github.com/OfficeDev/office-js/issues/4676#issuecomment-2252433432 

Is it safe to assume that the Monthly and Semi-annual channels will be running on v8 before NAA-SSO is released? Sometime before October 2024 (https://devblogs.microsoft.com/microsoft365dev/new-nested-app-authentication-for-office-add-ins-legacy-exchange-tokens-off-by-default-in-october-2024/) ? Or do we need to make a fallback for these outlook channels?

Thanks.

**Comment by AlexJerabek** [comment]
Hi @glr0221,

I'm researching the answer internally and will respond when I have something meaningful to share.

**Comment by AlexJerabek** [comment]
Hi @glr0221,
The general release of V8 will propagate through the Monthly and Semi-annual channels in time for NAA. This shouldn't cause a conflict. I'll update this thread if things change.

**Comment by glr0221** [comment]
Thank you @AlexJerabek. Very much appreciated.
