### ISSUE TITLE
Elaborate the process for Marketplace add-ins 

### ISSUE THREAD

**Issue by jkpieterse** [OfficeDev/office-js-docs-pr#4715]
In this article, the section about add-in updates only "Admins of organizations" are discussed, but it doesn't mention what needs to happen when with Marketplace offered add-ins:

https://learn.microsoft.com/en-us/office/dev/add-ins/publish/maintain-breaking-changes#deploy-updates

Please add what the rules are for updates to add-ins for Marketplace add-ins.

**Comment by AlexJerabek** [comment]
Hi @jkpieterse,

Thanks for reaching out. The information for how to update existing Marketplace offers can be found here: https://learn.microsoft.com/partner-center/marketplace-offers/update-existing-offer.

I'll confirm internally if there is any information specific to add-ins that is missing from that documentation. Either way, I'll update the page you linked to make the process for updating Marketplace add-ins clearer. As you go through the process, please do let me know if there's anything missing that others would benefit from.

**Comment by AlexJerabek** [comment]
The linked PR has been merged. Updates to the documentation should be live in the next couple of days. Please let me know if you have any more suggestions or requests for the docs.

**Comment by jkpieterse** [comment]
Thanks. As soon as I find some time I'll have a look
