### ISSUE TITLE
Is NAA-SSO supported on event-based addins and spam addins?

### ISSUE THREAD

**Issue by glr0221** [OfficeDev/office-js-docs-pr#4724]
Hello Team Microsoft,

I would just like to ask for some clarification regarding the documentation which states the following : 
**_* - NAA for event-based activation in Outlook is currently supported in the Beta Channel._**

Is my understanding correct that NAA-SSO can now be used in the Beta Channel? Given that imports are not allowed in spam addins, how do we then use the NAA-SSO library (azure/msal-browser) within the spam addin body? Do you have a sample app that shows the recommended way of getting this done?

Thank you all so very much.

**Comment by pinverso** [comment]
Hello!
If you're integrating MSAL.js with your Outlook spam-reporting add-in, you can simplify the process by bundling MSAL.js directly with your existing bundle.js file. You have two options: use Webpack to include MSAL.js in your build process or concatenate MSAL.js with your bundle.js file manually. This approach eliminates the need for additional imports, streamlining your authentication setup.

**Comment by glr0221** [comment]
Hello @pinverso,

I hope all is well on your end.
Do we have any update or sample code on how to use the MSAL library with spam addins?
Thank you very much.
