### ISSUE TITLE
How to change the order of slides with js?

### ISSUE THREAD

**Issue by wuhuawei1996** [OfficeDev/office-js-docs-pr#4733]
I want to change the order of existing slides using Office.js. Is this possible? In addition, whether a page of slide can be copied. Thank you.

**Comment by AlexJerabek** [comment]
Hi @wuhuawei1996,

I don't believe this is supported with the current APIs. @EsterBergen, could you please confirm?

**Comment by wuhuawei1996** [comment]
> Hi @wuhuawei1996,
> 
> I don't believe this is supported with the current APIs. @EsterBergen, could you please confirm?

Hi, AlexJerabek. Thank you very much. Would this be supported in the future? I think this is a basic feature.

**Comment by EsterBergen** [comment]
@wuhuawei1996 - Thanks for reaching out! We don't have an API that changes the order of slides directly. However there is a possible workaround that you can to do export a slide as base 64 to local storage, and delete the slide in the presentation, and re-insert that slide from local storage in the new position.  (Export as base64 is a preview API right now)

https://learn.microsoft.com/en-us/javascript/api/powerpoint/powerpoint.slide?view=powerpoint-js-preview#powerpoint-powerpoint-slide-exportasbase64-member(1)
https://learn.microsoft.com/en-us/office/dev/add-ins/powerpoint/add-slides
https://learn.microsoft.com/en-us/javascript/api/powerpoint/powerpoint.insertslideoptions?view=powerpoint-js-preview

For reordering directly and restricting copying, please make a feature request here [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions). Please add your request there. Feature requests on are considered when we go through our planning process. Thanks for highlighting this!

**Comment by wuhuawei1996** [comment]
> @wuhuawei1996 - Thanks for reaching out! We don't have an API that changes the order of slides directly. However there is a possible workaround that you can to do export a slide as base 64 to local storage, and delete the slide in the presentation, and re-insert that slide from local storage in the new position. (Export as base64 is a preview API right now)
> 
> https://learn.microsoft.com/en-us/javascript/api/powerpoint/powerpoint.slide?view=powerpoint-js-preview#powerpoint-powerpoint-slide-exportasbase64-member(1) https://learn.microsoft.com/en-us/office/dev/add-ins/powerpoint/add-slides https://learn.microsoft.com/en-us/javascript/api/powerpoint/powerpoint.insertslideoptions?view=powerpoint-js-preview
> 
> For reordering directly and restricting copying, please make a feature request here [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions). Please add your request there. Feature requests on are considered when we go through our planning process. Thanks for highlighting this!

Thank you, EsterBergen. I thought about that. But exportAsBase64() was an experimental feature, and I couldn't decide which client my users would use, so I dropped it. Thank you. I'll make a feature request.
