### ISSUE TITLE
Custom Function Prerequisites Insider Program (Insider Channel)

### ISSUE THREAD

**Issue by zakhan4** [OfficeDev/office-js-docs-pr#477]
In the documentation for custom functions it is written that the user should be the part of the Insider Program, but no where it is mentioned that the user should used which level of insider channel (either monthly targeted or Insider Channel). And after searching a lot I finally found out that it only works with the Insider Channel (InsiderFast). I think it would be helpful if this is mentioned in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94ad7803-d4f7-a700-7c7f-204cd8f34e4a
* Version Independent ID: 9c485bae-cab1-bdad-4c8e-baad2b12b22d
* Content: [Create custom functions in Excel (Preview)](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-overview)
* Content Source: [docs/excel/custom-functions-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/custom-functions-overview.md)
* Product: **office 365**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by kbrandl** [comment]
@zakhan4 the Excel Custom Functions docs have been updated with this clarification. Thanks again for the raising this issue!
