### ISSUE TITLE
Html not refreshing on add RecipientsChangedEvent trigger

### ISSUE THREAD

**Issue by mahendrakelp** [OfficeDev/office-js-docs-pr#4780]
**Describe your scenario**
I need to update html content in angular outlook add-in, whenever user change recipients. I am about to capture event and values changes but html not refreshing. I tried ngZone also but not working.

**Which APIs or add-in features?**
Event trigger not updating angular html template.

Attaching below sample code

**Controller code**
`
Office.actions.associate('onMessageRecipientsChanged', async (event: Office.RecipientsChangedEventArgs) => {
      await this.onRecipientsChanged(event);
    });
    
async onRecipientsChanged(event: Office.RecipientsChangedEventArgs) {
    console.log('------------------------------ onMessageRecipientsChanged', event);
    let tempContacts: Office.EmailAddressDetails[] = [];
    if (event.changedRecipientFields.to) {
      this.outlookItemService.loadTo(Office.context.mailbox).then((s) => {
        tempContacts = s;
        this.zone.run(() =>{
          this.tempContacts = tempContacts;
          this.ref.detectChanges();
          console.log(this.tempContacts);  
        })
      });
    }
  }
`
**HTML Template**
`
  {{tempContacts | json }}
`

**Comment by samantharamon** [comment]
Hi @mahendrakelp,

Thanks for reaching out. To narrow down the issue further, when debugging your add-in, does the OnMessageRecipientsChanged event occur? To assist you with debugging your add-in, see [Debug your event-based or spam-reporting Outlook add-in](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/debug-autolaunch).
