### ISSUE TITLE
Subject: Inquiry About Task Pane Support for Appointments in Outlook Add-ins

### ISSUE THREAD

**Issue by strtob** [OfficeDev/office-js-docs-pr#4836]
Hi,

I recently read on the Microsoft documentation regarding the limitations of pinning task panes for appointments in Outlook ([link](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/pinnable-taskpane?tabs=xmlmanifest)). As it currently stands, users must manually open the add-in for each appointment, which significantly hinders the user experience.

Given this limitation, developing an Outlook web add-in intended for use in appointment contexts seems impractical. Is there any possibility of displaying the task pane automatically when creating a new appointment? If not, it raises concerns about the viability of such add-ins moving forward.

Thank you for your attention to this matter. I look forward to your response.

Best regards,
Tobias

**Comment by AlexJerabek** [comment]
Thanks for raising this issue @strtob.

@samantharamon is there any additional guidance we can provide here, or should we treat this as a feature request?

**Comment by samantharamon** [comment]
Hi @strtob,

While you can't automatically display a task pane when a new appointment is created, you can leverage the [OnNewAppointmentOrganizer](https://learn.microsoft.com/office/dev/add-ins/outlook/autolaunch#supported-events) event to automatically display information or run tasks as soon as a user creates a new appointment. However, if your scenario does require a task pane to automatically open or be pinned for appointments, we recommend upvoting an existing request or submitting a new one for this feature on our [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions). This request may be related to your scenario: [Pinnable task panes for Appointments/Meetings in Outlook](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/pinnable-task-panes-for-appointments-meetings-in-outlook/idi-p/3091883).
