### ISSUE TITLE
Clarification on Trident outlook.

### ISSUE THREAD

**Issue by glr0221** [OfficeDev/office-js-docs-pr#4839]
Currently, the only way we know to test trident Outlook is by configuring 'config.xml' into the following version and channel : 
```
<Configuration>
  <Add OfficeClientEdition="64" Channel="SemiAnnual" Version="16.0.10730.20348">
    <Product ID="O365ProPlusRetail">
      <Language ID="en-us" />
    </Product>
  </Add>
</Configuration>
```
And judging by the xml entries, it seems to be an older version of the semi-annual channel. 

Since supporting (or not supporting) trident is something we are looking into, may we know the following : 
1. What are the latest versions of Outlook that use trident?
2. Is trident equal to the Microsoft Chakra JScript engine?
3. How do we filter Outlook versions using trident and using edge?

I am asking these questions because we are about to use NAA-SSO for our code. And importing that library in our addin, causes a crash for trident systems. Because of this crashing issue, we are planning to check how many of our customers use trident-outlook before we release our addin with NAA-SSO enabled.

Thank you very much for understanding.

**Comment by emmasab** [comment]
Hi @glr0221

1. What are the latest versions of Outlook that use trident? 
Some combinations of platforms and Office versions, including volume-licensed perpetual versions through Office 2019, still use the webview controls that come with Internet Explorer 11 (called "Trident"). See [Browsers and webview controls used by Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins)

2. Is trident equal to the Microsoft Chakra JScript engine?
No, Trident is the webview control that came with Internet Explorer 11. Chakra is a Javascript engine which has been replaced by the V8 Javascript engine. See [this announcement from Build 2024](https://devblogs.microsoft.com/microsoft365dev/whats-new-for-office-add-ins-at-build-2024/#javascript-runtime-update).

3. How do we filter Outlook versions using trident and using edge?
Please follow documentation on [Support older Microsoft webviews and Office versions](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/support-ie-11?tabs=ie).

Note that NAA is only supported on WebView2 using the V8 Javascript engine, so NAA will not work with Trident.

**Comment by glr0221** [comment]
Thank you very much for all the information @emmasab . That was very enlightening. Currently my problem is that we have an addin that works for trident, edge and webview. This has been using the REST tokens and whenever possible it uses the SSO-OBO flow authentication for GRAPH. 

We want to use the NAA-SSO library ([azure/msal-browser](https://www.npmjs.com/package/@azure/msal-browser)) to be able to use NAA-SSO but each time I import that library, my addin would not load in trident anymore. I totally expect that msal/naa-sso won't work on trident, but I was hoping importing it would not cause the addin to fail in loading.

Point being, with this current state, where importing and using msal-browser causes addin loading failure, how then do we integrate/utilize it? I apologize for having to state the problem here as this is not the proper place. But thank you for listening and answering my questions with finality. Much appreciated @emmasab .
