### ISSUE TITLE
Yeoman generator add-in project for office add-in doesn't load office.js

### ISSUE THREAD

**Issue by mrlund** [OfficeDev/office-js-docs-pr#4876]
I'm following the tutorials to create a new Powerpoint task pane add-in (https://learn.microsoft.com/en-us/office/dev/add-ins/tutorials/powerpoint-tutorial?tabs=yeomangenerator). 

When I run the project, everything looks fine right up until the add-in opens in powerpoint. Here it's stuck with the "loading" screen. In the dev tools console I can see the error: 
```
Uncaught ReferenceError: Office is not defined
    at ./src/taskpane/taskpane.js
```

Inspecting the source files, I can see that the office.js script is referenced in commands.html but not from taskpane.html which is the only one that loads. In fact, the taskpane.html file doesn't have <html> or <head> tags. It looks like maybe it's designed to be inserted into another template file, perhaps using webpack or something, but on my projects that's not the case. 

If i manually add the html, head and script to the taskpane.html I can get the add-in to load and work. 

Repro: follow the tutorial steps and run. 

WIndows 11, node 20.10, using VS Code and Yeoman

**Comment by AlexJerabek** [comment]
Thanks for reporting this @mrlund.

@ElizabethSamuel-MSFT, could you please investigate?

**Comment by ElizabethSamuel-MSFT** [comment]
@mrlund Sorry to hear that you hit some issues with this.

I tried out the tutorial using a similar config to you, but with node 20.18. Yo Office seemed to do the right thing. I've included the <head> section of the taskpane.html I received for your perusal.

```html
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Contoso Task Pane Add-in</title>

    <!-- Office JavaScript API -->
    <script type="text/javascript" src="https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js"></script>

    <!-- For more information on Fluent UI, visit https://developer.microsoft.com/fluentui#/. -->
    <link rel="stylesheet" href="https://res-1.cdn.office.net/files/fabric-cdn-prod_20230815.002/office-ui-fabric-core/11.1.0/css/fabric.min.css"/>

    <!-- Template styles -->
    <link href="taskpane.css" rel="stylesheet" type="text/css" />
</head>
```

It seems like your experience may have been a glitchy download. I checked the change history for the yo office templates but saw nothing that should have caused the Office.js reference to be removed from that html file. I invite you to retry running `yo office` and if you come across this issue again, let us know so we can investigate further.

Thanks.

**Comment by mrlund** [comment]
Thanks - based on your comment I tried first reinstalling the yo generators and then ran yo office again, and now it seems to be generating correctly.
