### ISSUE TITLE
Question: best practices for persisting user-entered values?

### ISSUE THREAD

**Issue by ChemMitch** [OfficeDev/office-js-docs-pr#4884]
**Article URL**
none

**Describe the problem**
In this environment, what's the recommended strategy for persisting values entered by the user so the values  can be loaded next time the add-in starts?

Browser storage works.  Is it secure?

**Comment by AlexJerabek** [comment]
Hi @ChemMitch,

Thanks for the question. Yes, we do recommend [browser storage with storage partitioning](https://learn.microsoft.com/office/dev/add-ins/develop/persisting-add-in-state-and-settings#storage-partitioning) as a secure persistence solution.

I'm going to close this issue, but if you have any further questions, please let me know.

**Comment by ChemMitch** [comment]
Thank you, Alex!
