### ISSUE TITLE
Requesting Clarification on support for NAA-SSO.

### ISSUE THREAD

**Issue by glr0221** [OfficeDev/office-js-docs-pr#4896]
Hello Microsoft, 

I hope you are doing well.

I just wanted to ask for some clarifications on your [FAQ](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/faq-nested-app-auth-outlook-legacy-tokens#when-is-naa-generally-available-for-my-channel) related to the channel schedules. 

My question/request is, can we please also add the other versions of Office/Outlook? Like : 
1. Outlook 2016
2. Outlook 2019
3. Outlook 2021
4. Outlook 2024

The above versions are using lifetime/long-term licenses. Which of these versions will support NAA-SSO as well? 

Thank you very much.

**Comment by davidchesnut** [comment]
Hi @glr0221,

I apologize for the late response here. You can find a list of all platforms supported on Outlook and versions in the [Nested app auth req set](https://learn.microsoft.com/javascript/api/requirement-sets/common/nested-app-auth-requirement-sets) article. Unfortunately we can't backport NAA to some of the older versions such as Outlook 2016 and 2019. But we are looking to support Office 2024 LTSC at some point. We'll update the article as new platforms are supported. 

You can use the `NestedAppAuth` req set to check if an Outlook client supports NAA. If it doesn't there are fallback mechanisms you can use. We've documented how to use fallback in the following samples.

- [Outlook add-in using SSO through NAA](https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/auth/Outlook-Add-in-SSO-NAA)
- [Outlook add-in NAA with fallback for trident (IE11) support](https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/auth/Outlook-Add-in-SSO-NAA-IE)

Cheers,
David

**Comment by glr0221** [comment]
@davidchesnut 

First off, thanks for all the answers. Sorry it took me some time to say thanks. 

Anyways, I have some follow up questions related to IE SSO : 
1. The popup dialog to select the user is inevitable correct?
2. For SSO to work on IE, outlook must support Mailbox 1.4.
3. Is it necessary to sign out even if the addin is closed?

Thank you.
