### ISSUE TITLE
Issue when trying to unregister an event following the documentation examples

### ISSUE THREAD

**Issue by frankybboy96** [OfficeDev/office-js-docs-pr#4909]
### Article URL

https://learn.microsoft.com/en-us/office/dev/add-ins/word/word-add-ins-events#remove-an-event-handler 

### Issue

The documentation gives instructions on how to register and then unregister events, but the provided code example isn't valid and doesn't work even in the most basic sense. 

the `eventContext.context` provided as a param in the `Word.run` has a type mismatch and is not working.
![image](https://github.com/user-attachments/assets/3521839a-be07-4c8c-949c-4322c5aaef2c)

trying to work around the issue by casting doesn't resolve the issue and just leads to the `Word.run` to throw 
![image](https://github.com/user-attachments/assets/fdbcc9a9-bb09-4607-a55f-4b138e6043c6)
![image](https://github.com/user-attachments/assets/72f54fc3-f26d-41f2-8f00-d0228c840294)

also the example provided doesn't take into account the possibility that `eventContext` could potentially be undefined or null, which is also wrong but easily fixed by adding some `if(eventContext)` where needed.

### Questions 
Is there another approved way of registering/unregistering events that I haven't found in the documentation? 

Is there other ways to get notified of document changes that do not rely on the events?

**Comment by frankybboy96** [comment]
When can I expect to get any news relating to this?

**Comment by Rick-Kirkham** [comment]
@frankybboy96 This is a holiday week in the USA. @ElizabethSamuel-MSFT will be back next week. I the meantime, please install the ScriptLab tool from AppSource and try the sample in this screen shot. The code is similar to what is in the article. It will be valuable to see if the sample works in Script Lab or gives you and error. (It works perfectly for me.)

**Comment by ElizabethSamuel-MSFT** [comment]
@frankybboy96 Can you let us know which Word client you're using? Also, do provide the version/build if it's not a browser client. Thanks.

**Comment by frankybboy96** [comment]
I'm sorry, with the holidays I couldn't get back to you sooner, we eventually figured out the issue and it's entirely our fault, we were pointing on the wrong version of the office api CDN, Rick's reccomendation to try scriptLab was invaluable in figuring out the issue

**Comment by ElizabethSamuel-MSFT** [comment]
Thanks for letting us know that you were able to resolve your issue. Happy holidays.
