### ISSUE TITLE
List validation rule type broken

### ISSUE THREAD

**Issue by rohitrewa** [OfficeDev/office-js-docs-pr#492]
I am trying below code to have a list data validation and its giving error. I also made sure to have data in 'nameSourceRange' but it did not help. Please respond ASAP.

```
var sheet = context.workbook.worksheets.getActiveWorksheet();
var range = sheet.getRange("B2:C5");  
var nameSourceRange = context.workbook.worksheets.getItem("Sheet1").getRange("A1:A3");

range.dataValidation.rule = {
    list: {
        inCellDropDown: true,
        source: nameSourceRange
    }
};
await context.sync();
```

 
Error
InvalidArgument: The argument is invalid or missing or has an incorrect format.
```
{
    "code": "InvalidArgument",
    "message": "The argument is invalid or missing or has an incorrect format.",
    "errorLocation": "ListDataValidation.source",
    "statement": "dataValidation.rule=...;",
    "surroundingStatements": [
        "...",
        "// Instantiate {range}",
        "var worksheet=worksheets.getItem(...);",
        "var range1=worksheet.getRange(...);",
        "// Instantiate {range1}",
        "var dataValidation=range.dataValidation;",
        "// &gt;&gt;&gt;&gt;&gt;",
        "dataValidation.rule=...;",
        "// &lt;&lt;&lt;&lt;&lt;"
    ],
    "fullStatements": [
        "Please enable config.extendedErrorLogging to see full statements."
    ]
}        

```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e12c8da9-16ef-b641-aa8a-b5dd37b93d63
* Version Independent ID: e8264f34-086a-65be-d91d-3405159c7bcb
* Content: [Add data validation to Excel ranges](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-data-validation#list-validation-rule-type)
* Content Source: [docs/excel/excel-add-ins-data-validation.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/excel-add-ins-data-validation.md)
* Product: **office 365**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @rohitrewa,
I've reported the issue to the product team and am awaiting a response. In the meantime, can you replace
`source: nameSourceRange` with
`source: '=Sheet1!$A$1:$A$3'`

**Comment by AlexJerabek** [comment]
I'd also recommend raising this issue on the [office-js repo](https://github.com/OfficeDev/office-js/issues). Our engineers may get you a quicker response and escalation there.

**Comment by AlexJerabek** [comment]
Hi @rohitrewa,
It appears ListDataValidation.source does not and cannot support a Range argument. I have submitted a [PR to DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30065) to fix the TypeScript definition file. I'll also be updating our docs accordingly.
Thank you for reporting this issue.

**Comment by AlexJerabek** [comment]
The doc changes have been checked in to master and will be merged into the live branch soon. Closing the issue.
