### ISSUE TITLE
Please add Set-OutlookSignatures Benefactor Circle to the list of publishers that have updated their add-ins to NAA

### ISSUE THREAD

**Issue by GruberMarkus** [OfficeDev/office-js-docs-pr#4929]
Dear Office.js documentation team,

could you please add ExplicIT Consulting's [Set-OutlookSignatures Benefactor Circle](https://explicitconsulting.at/open-source/set-outlooksignatures/) to the list of publishers that already have updated their Outlook add-in to Nested App Authentication at [Is there a list of publishers that have updated their add-ins?](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/faq-nested-app-auth-outlook-legacy-tokens#is-there-a-list-of-publishers-that-have-updated-their-add-ins)?

Thanks in advance!

**Comment by samantharamon** [comment]
Hi @GruberMarkus. Thanks for your post.

@davidchesnut, could you please assist with this request?

**Comment by GruberMarkus** [comment]
@davidchesnut, @samantharamon: Thank you for adding Set-OutlookSignatures to the list of publishers!

Closing this issue, as the request has been fulfilled.
