### ISSUE TITLE
More concise instructions required for how to determine which GUID and encoded string determine the addin you are trying to debug

### ISSUE THREAD

**Issue by LiamWarnes** [OfficeDev/office-js-docs-pr#4931]
This step instructs you to replace text eclosed in [ ] with your applicable add in information, but does not provide instructions for how to obtain these values. Please update documentation with instruction on how to obtain these values.

![image](https://github.com/user-attachments/assets/33565d06-e220-4f6d-bcbd-ae1571f283d6)

https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/debug-autolaunch?tabs=windows

**Comment by samantharamon** [comment]
Hi @LiamWarnes,

Thanks for getting in touch. Unfortunately, there isn't a way to obtain these path values. Currently, the only way to reach the **bundle.js** file of your add-in is to go through each folder until you locate the folder with your add-in's ID. I understand that this can be tedious especially when you have multiple mail profiles and add-ins. The good news is that we're working on improving the developer experience on this. I don't have more information to share at this time, but please keep an eye out for updates on this.

In the meantime, I'll update our documentation to reflect the information I shared in this post.
