### ISSUE TITLE
Mixing Typescript and Javascript

### ISSUE THREAD

**Issue by PeterTippett** [OfficeDev/office-js-docs-pr#504]
This has code in Javascript for some and Typescript for others. Should really have both examples. When debugging on the browser, you are in Javascript not Typescript 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db285f50-5770-e426-47f6-a9f78536cab3
* Version Independent ID: 55778f17-2bdd-898b-41fc-e3f4e5517197
* Content: [Runtime for Excel custom functions](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-runtime)
* Content Source: [docs/excel/custom-functions-runtime.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/custom-functions-runtime.md)
* Product: **office 365**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by sancarn** [comment]
100% agree. Having TypeScript and JavaScript documentation would be advantageous although it's probably more important to have JavaScript examples than typescript in general

**Comment by mscharlock** [comment]
Hi folks! 
Many thanks for the feedback, it's very helpful for us to hear directly what developers want to see in our documentation. We've taken out the mix of TS/JS samples in the custom functions documentation and are discussing on our team about the possibility of integrating TS. :) I'm going to mark this issue as resolved for now, but wanted to let you know that we've heard your feedback and are taking it into consideration!
