### ISSUE TITLE
Where i can find Excel addins connect to SharePoint Online example

### ISSUE THREAD

**Issue by peterremote1980** [OfficeDev/office-js-docs-pr#506]
Where i can find Excel addins connect to SharePoint Online example? thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ddce0bd-5c66-c2cb-0640-ee4d5bd401c5
* Version Independent ID: b5d4bc26-a43e-4a85-e7d5-fe4fc4ec3d0d
* Content: [Sideload Office Add-ins for testing](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins)
* Content Source: [docs/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins.md)
* Product: **office 365**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
The sample here [PowerPoint-Add-in-Microsoft-Graph-ASPNET-InsertChart](https://github.com/OfficeDev/PowerPoint-Add-in-Microsoft-Graph-ASPNET-InsertChart) gets OneDrive files from an Office Add-in. Getting SharePoint data should be essentially the same except that the REST URL will be different. See the MS Graph documentation for details. [Microsoft Graph](https://developer.microsoft.com/en-us/graph)
