### ISSUE TITLE
VersionOverrides Support

### ISSUE THREAD

**Issue by MK-MASTER** [OfficeDev/office-js-docs-pr#507]
Documentation indicates that Content Add-ins can have "VersionOverrides" however I do not think this is the case.

Can you check and correct please 

Thanks

Element	Content	Mail	TaskPane
VersionOverrides	X	X	X

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec89556a-6d87-c17e-4f68-33e1b2abe7f6
* Version Independent ID: 846a32b7-5194-f71e-3efc-0dc2594d2700
* Content: [OfficeApp element](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/officeapp)
* Content Source: [docs/reference/manifest/officeapp.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/manifest/officeapp.md)
* Product: **office 365**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@MK-MASTER: Thanks for raising this issue. We've updated the documentation and the fix should be published soon.
