### ISSUE TITLE
Project

### ISSUE THREAD

**Issue by renkeh** [OfficeDev/office-js-docs-pr#508]
please add Microsoft Project here, too

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7c255e4-d0f9-5b35-bec0-fdd690bdeff1
* Version Independent ID: dae8b049-0f53-ea13-9998-cfb4362b7553
* Content: [Office Add-in host and platform availability](https://docs.microsoft.com/en-us/office/dev/add-ins/overview/office-add-in-availability)
* Content Source: [docs/overview/office-add-in-availability.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/overview/office-add-in-availability.md)
* Product: **office 365**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@renkeh: This change has been made and should be published soon. Thanks!
