### ISSUE TITLE
[Excel Online] [Side loading] Add-In infra show strange behavior

### ISSUE THREAD

**Issue by rohitrewa** [OfficeDev/office-js-docs-pr#516]
Hi Team,

We are developing an Add-In for Excel and are facing issue with Side loading in Excel online. We are not sure if this behavior will continue even after App goes is prod.

Repro and Behavior 
1. Side load an Add-In pointing to [https://sdxvisio.azurewebsites.net/index.html](https://sdxvisio.azurewebsites.net/index.html)
2. Wait for 10 seconds after page loads.
3. You will see Add-In crashing with a reload button
4. Click reload
5. You will see page loaded again.
6. Wait for some time. Add-In will crash with a start button on it.
7. Press start it will work from now.

Screenshots: [https://testtestvize3vol-my.sharepoint.com/:i:/g/personal/visiodvaddinadmin_testtestvize3vol_onmicrosoft_com/EZg6k9jkU7ZIgT4mWdPWmscBihrJCVh1PdJwaG_riT4Okw?e=2sPmKq](https://testtestvize3vol-my.sharepoint.com/:i:/g/personal/visiodvaddinadmin_testtestvize3vol_onmicrosoft_com/EZg6k9jkU7ZIgT4mWdPWmscBihrJCVh1PdJwaG_riT4Okw?e=2sPmKq)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ddce0bd-5c66-c2cb-0640-ee4d5bd401c5
* Version Independent ID: b5d4bc26-a43e-4a85-e7d5-fe4fc4ec3d0d
* Content: [Sideload Office Add-ins for testing](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins)
* Content Source: [docs/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins.md)
* Product: **office 365**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
@rohitrewa We use the issues of this repo to track problems with the documentation. This infrastructure behavior problem would fit better as an issue in the `office-js` repo. Can I ask you to raise the issue there? You can link back to this issue for details, or just copy them. In the meantime, I'll close this issue.
