### ISSUE TITLE
My registry does not have ...Wef\Developer

### ISSUE THREAD

**Issue by wolfmatthewj** [OfficeDev/office-js-docs-pr#521]
Hi, I'm trying to "Use runtime logging to debug your add-in". My Office build is 16.0.9126.2295. But when I use regedit.exe to attempt to add the RuntimeLogging key, my registry doesn't have the right location. I have HKEY_CURRENT_USER\SOFTWARE\Microsoft\Office\16.0\WEF (not Wef as in this documentation). And I do not have a Developer directory under WEF. I have Cache, LastUpdate, PreinstalledApps, Providers, RibbonUiExperiment, and TrustedCatalogs.

For what it's worth, I also tried "Validate your manifest with the Office Add-in Validator" but could not understand the error messages it produced. If anyone is able to correspond with me about those, I would appreciate it. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a89c40a2-3e90-a295-7375-6d52ba597808
* Version Independent ID: 8cd2f086-5c18-ee17-9ced-ffeba1de0b78
* Content: [Validate and troubleshoot issues with your manifest](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/troubleshoot-manifest#validate-your-manifest-with-the-office-add-in-validator)
* Content Source: [docs/testing/troubleshoot-manifest.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/troubleshoot-manifest.md)
* Product: **office 365**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by kbrandl** [comment]
@wolfmatthewj thanks for reaching out and sorry to hear that you've run into this issue. If you manually create the **Developer** folder inside the **WEF** folder (by right-clicking the **WEF** folder, selecting **New** > **Key**, and naming the new key **Developer**) then are you able to successfully proceed with the instructions to enable runtime logging from there?

**Comment by wolfmatthewj** [comment]
Thanks very much--manually adding the Developer key solved the issue.
