### ISSUE TITLE
Where is localhost defined?

### ISSUE THREAD

**Issue by APPSFOROFFICE** [OfficeDev/office-js-docs-pr#531]
On the first day I followed the instructions, built the addin, and was able to side-load it in MS Word 365 for Windows.  Great I thought.  My only issue was that the temp certificate I installed didn't seem to register, and I needed to click the extra link to say "go there anyway".
The next day - the add-in says it loads successfully (down in Word Status Bar), but when I open the TaskPane, I get "Add-in Error Sorry, we can't load the add-in. Please make sure you have network and/or Internet connectivity. Click "Retry" once you're back online"

If I add the URL https://localhost:3002/ into a browser, it now can't find the page.  

It would be really helpful to know how to debug this issue - I'm about to start again from scratch.  It seems to be a Manifest problem re the Source Location...

Thanks!

**Comment by kbrandl** [comment]
@APPSFOROFFICE sorry to hear that you're having trouble. A few questions for you:
- What article in the documentation contains the instructions you followed to create your add-in?  (Please provide the link to the article.) (Issues in this repository are used to track problems with the Office Add-ins documentation.)
- Did you use Yo Office (the Yeoman Generator for Office Add-ins) to create your add-in?
- Assuming you did use Yo Office to create the add-in, did you start the web server (`npm start`) before trying to sideload the add-in in Word?  The (localhost) web server must be running before the add-in will load successfully.
- I don't recall seeing the port **3002** ever used by default for Office Add-in apps, usually it is port **3000**. Are you able to load the URL `https://localhost:3000` in a browser (after you've started the web server)?

**Comment by APPSFOROFFICE** [comment]
Hi Kim
Thanks for the reply – I rebuilt the addin successfully again from scratch yesterday and realised the GitBash component where I run the npm run build and npm start were the critical parts of the process.

As an ex Technical Writer I understand where you might be confused as to how I could have got lost here, where under every Test procedure you outline that this needs to be done to re-initialise the new changes.  I guess, coming from a VBA/VB.NET background this JS world is completely new to me and there is a lot for us to get our head around.

Maybe adding a little bit more context at the first Test would help – even though I had worked through the first four steps on Day 1, I got side-tracked trying to find the solution to the Addin Error, when I woke up on Day 2 and opened Word and couldn’t run the addin.  Or maybe just add this to your Troubleshooting section – because it wasn’t easy to find a solution online, and it wasn’t until, I thought, I’ll just start again which forced me to re-read the documentation.  Seems simple in hindsight!  But we developers think we remember all the useful information…  Grrr.

And the localhost:3002 was me just not having a clue, and playing around to see if that would work. D’oh

Another suggestion I have for your documentation or rather, for the sample, would be to change your example code to work with selection point rather than changing the first, last paragraph.  No one works like that.  My users are wanting to change the paragraph they have selected, insert a table where they have the cursor, at the current selection point.  No one wants to add a graphic or a table at the end, they want to add it, where they want to add it.  Where they are selected.

Otherwise it is a good tutorial, and easy to follow.

Hope that helps.

Cheers Suzy
@APPSFOROFFICE<https://github.com/APPSFOROFFICE>

**Comment by kbrandl** [comment]
@APPSFOROFFICE thanks for the update! Happy to hear that starting the web server (`npm start`) allowed you to successfully run your add-in. Given the significant learning curve involved with coming to JS web development from VBA/VB.NET, I can certainly understand how this solution may not have been obvious to you at first glance.

We really appreciate the feedback about potential improvements to the docs, and we'll consider incorporating your suggestions the next time the [Word add-in tutorial](https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/word-tutorial) is revised. In the meantime, you might want to check out the [Word add-in quick start](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/word-quickstart?tabs=visual-studio-code) for a code sample that shows how to insert text at various points in a document (i.e., at the beginning, at the end, or at the current selection). Thanks again!
