### ISSUE TITLE
Cannot insert add-in in OneNote

### ISSUE THREAD

**Issue by jat255** [OfficeDev/office-js-docs-pr#540]
When getting to the "Try it out" section, I see no option to insert an add-in on OneNote (online or Windows 10 version). The option is there for me in Word Online, and the add-in displays (although obviously fails when clicking "Add Outline") after sideloading. Any idea how to get it into OneNote. `npm run sideload` doesn't work for OneNote either.

Here's what my OneNote Insert tab looks like: 
![image](https://user-images.githubusercontent.com/1278301/47933565-4862ab80-deab-11e8-9f01-daaddd501f27.png)

Conversely, it is there in Word:
![image](https://user-images.githubusercontent.com/1278301/47933659-89f35680-deab-11e8-856a-3873140861a5.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f988b661-2048-e17e-f909-ea83f1dfbe09
* Version Independent ID: adcaffba-438f-c3a2-775d-9b54d5855b61
* Content: [Build your first OneNote add-in](https://docs.microsoft.com/en-us/office/dev/add-ins/onenote/onenote-add-ins-getting-started)
* Content Source: [docs/onenote/onenote-add-ins-getting-started.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/onenote/onenote-add-ins-getting-started.md)
* Product: **office 365**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by kbrandl** [comment]
@jat255 thanks for reaching out about this. As described in the [Office Add-in host and availability](https://docs.microsoft.com/en-us/office/dev/add-ins/overview/office-add-in-availability#onenote) article, Office (web) Add-ins built for OneNote are currently only supported within Office Online. If you'd like to see OneNote add-ins supported within the Windows desktop client, please feel free to add this as a feature request on the [UserVoice](https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback?category_id=163572) site.

**Comment by kbrandl** [comment]
One additional thought -- if you're not seeing the **Office Add-ins** button within the **Insert** ribbon of **OneNote Online**, then is it possible that your tenant admin has somehow disabled Office Add-ins for OneNote Online for users within your Office 365 tenant?  I don't have expertise with the Office 365 Admin Center, but that seems like a reasonable explanation for why you may not be seeing the **Office Add-ins** button.
