### ISSUE TITLE
Document Object missing Open method

### ISSUE THREAD

**Issue by mscaitlina** [OfficeDev/office-js-docs-pr#543]
This page indicates that the Document Object has an Open method. However, the page it links to makes no mention of an Open method (in fact, searching for "open" yields 0 results).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 994db147-1d84-2af7-e6f6-f01a1491ea4c
* Version Independent ID: ccc98f6b-25cc-7d51-4894-d9e31879189d
* Content: [Word JavaScript API requirement sets](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/word-api-requirement-sets)
* Content Source: [docs/reference/requirement-sets/word-api-requirement-sets.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/requirement-sets/word-api-requirement-sets.md)
* Product: **office 365**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by kbrandl** [comment]
@mscaitlina we're still investigating but preliminary info I've uncovered seems to indicate that this is an error in the [Word JavaScript API requirement sets](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/word-api-requirement-sets) article. That is:

- The `open()` method **_is not_** available on the [Document](https://docs.microsoft.com/en-us/javascript/api/word/word.document?view=office-js) object.
- Rather, the `open()` method _**is**_ available on the [DocumentCreated](https://docs.microsoft.com/en-us/javascript/api/word/word.documentcreated?view=office-js) object.

We're still investigating but I wanted to share this info with you now in the hopes that it will unblock you. I'll provide additional info here when there's definitive info to share.

**Comment by kbrandl** [comment]
The article has been updated to reflect that the `open()` method is available on the [DocumentCreated](https://docs.microsoft.com/en-us/javascript/api/word/word.documentcreated?view=office-js) object; thank you for bringing this issue to our attention.
