### ISSUE TITLE
index.html can't be loaded

### ISSUE THREAD

**Issue by WinkyWonky** [OfficeDev/office-js-docs-pr#55]
Article:
index.html can't be loaded

Issue: 
tried to test the tutorial and stopped at 
"Test the add-in", Step 4 although 
certificate is installed and 
manifest-file is copied to shared folder 
but index.html can't be loaded and gets http status code 404

**Comment by Rick-Kirkham** [comment]
@WinkyWonky Sorry that you are having trouble. Please give the URL or title of the article you are working with. We do not have an article named "index.html".

**Comment by WinkyWonky** [comment]
Hi Rick-Kirkham,
here is the url with the description: https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/excel-tutorial-create-table
In Excel the add-in site can't be loaded. I suppose there is a problem with node.js ...
Sad but true, this tutorial doesn't work at the moment. Anayway i'll skip to the next tutorial.

**Comment by Rick-Kirkham** [comment]
@WinkyWonky 
I can't reproduce any problems with the tutorial sample. 
Are you saying that you get 404 in the task pane? 
Also, please try this: Repeat the steps in the **Test the add-in** section, but in step 1, use the **Completed** folder instead of the **Start** folder.
