### ISSUE TITLE
JS api

### ISSUE THREAD

**Issue by Mart-Bogdan** [OfficeDev/office-js-docs-pr#553]
Are there any description of JS API?
I would like to receive events when presentation moves to next slide,or even animation played. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68a73421-2f8d-53e8-3741-551567708be5
* Version Independent ID: 47f867e3-84fd-6519-7c71-7d646c9dd7a0
* Content: [Insert text into a PowerPoint slide using the Office JavaScript API](https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/powerpoint-tutorial-insert-text)
* Content Source: [docs/tutorials/powerpoint-tutorial-insert-text.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/tutorials/powerpoint-tutorial-insert-text.md)
* Product: **office 365**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by kbrandl** [comment]
@Mart-Bogdan the events that you describe are not currently supported / available in Office JS. Please consider adding this as a feature request in [UserVoice](https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback?category_id=163569). The product team considers requests in UserVoice when prioritizing features for future releases of Office JS.
