### ISSUE TITLE
Need link to sideloading info in Fabric React article

### ISSUE THREAD

**Issue by Rick-Kirkham** [OfficeDev/office-js-docs-pr#56]
Article:
https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/design/using-office-ui-fabric-react.md
Issue: 
In the section titled "Step1 ..." there is a step 5 that tells readers to side load the manifest. But there are no instructions on how to do this. There should be a link to instructions.

**Comment by lindalu-MSFT** [comment]
Thanks @mlafleur for updating the topic. The instructions are now linked in step 5 of the topic [Use Office UI Fabric React in Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/design/using-office-ui-fabric-react). Closing.
