### ISSUE TITLE
Confusing use of second button in default yo office react project instructions

### ISSUE THREAD

**Issue by Rick-Kirkham** [OfficeDev/office-js-docs-pr#57]
Article:
https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/design/using-office-ui-fabric-react.md
Issue: 
The instructions begin by telling the user to add a button. This is confusing in two ways:
1. There is already a button on the page that is part of the default project that the generator creates. It is wired up to a (empty) handler. Why do we not simply have the user add code to the existing handler, instead of having the user create a whole new button?
2. The code snippet imports **PrimaryButton** and **IButtonType** from `office-ui-fabric-react`. But the code that is generated imports **Button** and **ButtonType** from `office-ui-fabric-react`. If we go ahead and have the user create a new button, then the text should explain why it is based on different exported classes than the button that yo office generated.

![yoofficereact](https://user-images.githubusercontent.com/9088056/34584104-42175694-f14f-11e7-80e6-c21e20d5e571.png)

**Comment by AlexJerabek** [comment]
@mscharlock Did your changes in https://github.com/OfficeDev/office-js-docs-pr/pull/302 address this as well?

**Comment by mscharlock** [comment]
Yep, it solves this. There's only one button with the new changes, so no weird second component.

**Comment by AlexJerabek** [comment]
@Rick-Kirkham Based on Michelle's work, I'm going to close this issue. Please reopen it if you disagree.
