### ISSUE TITLE
Notify from the outlook addin if the user press send message button  

### ISSUE THREAD

**Issue by GMounir** [OfficeDev/office-js-docs-pr#572]
Hello Everyone.
i'm trying to develop an action that save informations... that the user can use it later.
but the problem i need a notification as a callback. when the message are sent successfully, then i can save data for later usage.
Please someone help me ...

**Comment by ElizabethSamuel-MSFT** [comment]
@exextoc: Can you take a look at this? Thanks.

**Comment by exextoc** [comment]
Getting a notification after an e-mail has been sent successfully is not currently possible.  In Outlook Web Access, you can currently see if this would meet your needs: https://docs.microsoft.com/en-us/outlook/add-ins/outlook-on-send-addins 

this feature is slated for other outlook clients in the future, but I do not have a time table to share when that would be.
