### ISSUE TITLE
Error code 5012 is not documented

### ISSUE THREAD

**Issue by ATrogolo** [OfficeDev/office-js-docs-pr#574]
Hello, my Excel AddIn raises an error with code: 5012 and message: "Your Office Online session has expired or is invalid. To continue, refresh the page." which is not documented here. 
Could you fix the docs? 

Thanks, 
Andrea

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad14a1fc-e890-3292-0a53-8a755db35f6e
* Version Independent ID: 78e25f2a-c710-6c16-32d7-f16d28b08e31
* Content: [JavaScript API for Office error codes](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/javascript-api-for-office-error-codes)
* Content Source: [docs/reference/javascript-api-for-office-error-codes.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/javascript-api-for-office-error-codes.md)
* Product: **office 365**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @ATrogolo, 
Thanks for reporting this information gap. We've updated the master branch with #581. That'll be pushed to live soon. I'll close the issue then.
