### ISSUE TITLE
task pane not showing

### ISSUE THREAD

**Issue by aszwork** [OfficeDev/office-js-docs-pr#575]
Hi
I have been following the example and Im using office 365 
When i run the example word starts up but I cannot see the add in

**Comment by dmahugh** [comment]
Which example are you referring to?

**Comment by kbrandl** [comment]
@aszwork sorry to hear that you're having trouble, but we'll need some more information before we can assist:
- Which example are you referring to?  (please provide the URL)
- Did you create the Word add-in by using Visual Studio or by using the Yeoman generator for Office Add-ins ("yo office")?

**Comment by kbrandl** [comment]
Closing this issue due to lack of response; please feel free to re-open if you can provide the info that's been requested. Thank you.
