### ISSUE TITLE
Wrong keyword used in code block

### ISSUE THREAD

**Issue by Rick-Kirkham** [OfficeDev/office-js-docs-pr#58]
Article:
https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/design/using-office-ui-fabric-react.md
Issue: 
The code block in the section titled "Step 2 ..." uses "var" where it should be "let" or "const". this is TypeScript.
![yoofficereact2](https://user-images.githubusercontent.com/9088056/34585551-0afe56b6-f155-11e7-9d28-0d0fa159c007.png)

**Comment by lindalu-MSFT** [comment]
Fixed and appears in [live topic](https://docs.microsoft.com/en-us/office/dev/add-ins/design/using-office-ui-fabric-react). Closing.
