### ISSUE TITLE
Requirement Set Availability for Office 2016 MSI

### ISSUE THREAD

**Issue by stephenegriffin** [OfficeDev/office-js-docs-pr#580]
## Article URL
This article:
https://github.com/OfficeDev/office-js-docs/blob/master/reference/outlook/tutorial-api-requirement-sets.md

## Issue
Says that 2016 MSI supports 1.4, but this is ONLY true if you have the right updates installed. I don't know exactly when 1.4 flips on, but I've narrowed it down this far:
osfshared.dll v 16.0.4266.1001, Thu Jul 30 2015 supports 1.3
osfshared.dll v 16.0.4702.1000, 15-May-2018 supports 1.4 and can be obtained via
https://support.microsoft.com/en-us/help/4022156/june-5-2018-update-for-office-2016-kb4022156

As we do with 2013, we should highlight which KB must be installed to light up 1.4 on 2016 MSI.

**Comment by ElizabethSamuel-MSFT** [comment]
New doc location: https://docs.microsoft.com/office/dev/add-ins/reference/requirement-sets/outlook-api-requirement-sets?view=office-js

**Comment by ElizabethSamuel-MSFT** [comment]
@stephenegriffin: Thanks for pointing this out. I'll use the KB provided in this stackoverflow response from the Outlook team: https://stackoverflow.com/questions/52306989/cannot-update-outlook-2016-msi-installer-to-support-office-js-requirement-set-1. Documentation update coming soon.
