### ISSUE TITLE
ItemHasRegularExpressionMatch rule with SenderSTMPAddress

### ISSUE THREAD

**Issue by dm-shlandii** [OfficeDev/office-js-docs-pr#586]
Hi,

Regarding "ItemHasRegularExpressionMatch rule". Does "PropertyName" = "SenderSTMPAddress" still valid ? 
manifest does not validated with it.
The manifest file doesn't conform to the schema definition. The 'PropertyName' attribute is invalid - The value 'SenderSTMPAddress' is invalid according to its datatype 'http://schemas.microsoft.com/office/mailappversionoverrides/1.1:PropertyName' - The Enumeration constraint failed... 

UPD:
It's a misstype in documentation Sender**SM**TPAddress instead Sender**ST**MPAddress

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 929c428e-8b80-f372-e75d-a6feb6ac006a
* Version Independent ID: 246b7867-a274-e500-1729-e988f1a11d62
* Content: [Rule element](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/rule?view=office-js)
* Content Source: [docs/reference/manifest/rule.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/manifest/rule.md)
* Product: **office 365**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by kbrandl** [comment]
@dm-shlandii thanks for reporting this documentation issue. I've fixed the typo and the [published doc](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/rule?view=office-js) will be updated later today. I'll plan to close this issue after the fix has been published.
