### ISSUE TITLE
Deploy outlook add-ins for testing 

### ISSUE THREAD

**Issue by GMounir** [OfficeDev/office-js-docs-pr#594]
Hello everyone...
I have a questions about deploying the add-ins for client to test.
I don't know where to put the content  of the application (html, javascript...) and (manifest.xml)
- Can i give the client (manifest.xml) and the source code can be in any server, and just by change 
-> `<SourceLocation DefaultValue="https://localhost:8080/index.html"/>`
the add-ins can work..?
Please help me to make this work.
Thanks for advance.

**Comment by kbrandl** [comment]
@GMounir thank you for your interest in Office Add-ins development. For information about the different ways you can make an add-in available to users, see the [Deploy and publish your Office Add-in](https://docs.microsoft.com/en-us/office/dev/add-ins/publish/publish) article. 

If you're not looking to do an official deployment of your add-in, but rather just want to enable specific people to try out your add-in, then you should be able to do something like this:

- Deploy your (add-in) web application to a web server.

- Update the URLs in the manifest file to point to the web server location (search/replace for the string `https://localhost:8080/` in the manifest -- it appears in the `<SourceLocation>` element as you've noted above, but also in other elements as well.)

- Send the manifest to each person who you want to test your add-in, and instruct them to [Sideload](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/test-debug-office-add-ins) the manifest in the desired Office application to load the add-in.

**Comment by GMounir** [comment]
Thank you for helping me.
i will try this...
