### ISSUE TITLE
Excel custom functions tutorial doesn't load add-in

### ISSUE THREAD

**Issue by evantrimboli** [OfficeDev/office-js-docs-pr#632]
I'm not sure whether this is a documentation issue or an issue with `yo office` however I thought I'd start here.

## Article URL
https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/includes/file-tutorial-excel-custom-functions.md

## Issue
When following the steps to create and run the sample, the add-in fails to load.

The default manifest points to:
`https://localhost:3000/dist/functions.js`
`https://localhost:3000/dist/functions.json`
`https://localhost:3000/dist/functions.html`

However these don't exist until you run `npm run build`. When it tries to side load the addin, it ends up displaying an error indicating it couldn't load the add-in. The runtime logging was indicating that the files could not be found.

**Comment by kbrandl** [comment]
@evantrimboli thanks for reporting this problem; it's most likely a documentation issue (I believe version 1.1.21 and later of Yo Office require that you run `npm run build` before you can successfully sideload the add-in). We'll look into this and update the docs accordingly.

**Comment by kbrandl** [comment]
@evantrimboli The [Excel Custom Functions tutorial](https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/excel-tutorial-create-custom-functions) has been updated with this info. Thanks again for reporting this issue.
