### ISSUE TITLE
Sample mail manifest is not valid

### ISSUE THREAD

**Issue by nedarb** [OfficeDev/office-js-docs-pr#637]
If you run the Office add-in validator against the sample Mail manifest, it reports that the manifest is invalid.
I ran: validate-office-addin MANIFEST.XML
from
https://docs.microsoft.com/en-us/office/dev/add-ins/testing/troubleshoot-manifest#use-runtime-logging-to-debug-your-add-in

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06f7f7e8-5b8a-e257-74be-77b47f048503
* Version Independent ID: a2851e98-268b-e65e-05eb-7ac3e21fe1ca
* Content: [Office Add-ins XML manifest - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/add-in-manifests?tabs=tabid-3)
* Content Source: [docs/develop/add-in-manifests.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/add-in-manifests.md)
* Product: **office 365**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by kbrandl** [comment]
@nedarb you can make the sample Mail manifest valid by applying the following changes:
- In the `OfficeApp` element near the top of the file, change the value of the `xmlns:xsi` attribute to: **"http://www.w3.org/2001/XMLSchema-instance"** 
- Immediately after the `HighResolutionIconUrl` element, add this element:  `<SupportUrl DefaultValue="[Insert the URL of a page that provides support information for the app]" />`

After you apply these changes to the sample manifest, it should pass validation. PR #645 will update the docs with this info later this week. Thanks again for reporting this problem.
