### ISSUE TITLE
I'm unable to see File>New>Project in Visual Studio for Mac - Community

### ISSUE THREAD

**Issue by osamahanif** [OfficeDev/office-js-docs-pr#639]
I'm trying to create a new Office Add-in and I have just downloaded the latest Visual Studio for Mac - Community. However, When I click New Project it asks me to select from the templates and none of those templates have a project template for office add-in.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50a89144-ac19-b28e-2842-5e2cbdb1cb00
* Version Independent ID: cb59df19-9c22-de2c-0c46-7a1403312987
* Content: [Build your first PowerPoint add-in - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/powerpoint-quickstart?tabs=visual-studio)
* Content Source: [docs/quickstarts/powerpoint-quickstart.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/quickstarts/powerpoint-quickstart.md)
* Product: **office 365**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by kbrandl** [comment]
@osamahanif thanks for reaching out about this. Visual Studio for Mac does not support Office (web) Add-in templates. However, you can use the [Yeoman generator for Office Add-ins](https://github.com/officedev/generator-office) to create an add-in on Mac. It'll automatically create the project scaffolding for you, and then you can use the editor of your choice (including Visual Studio for Mac) to modify the code for your add-in. The following "quick starts" in the Office Add-ins documentation contain detailed instructions for how to create an add-in with the Yeoman generator:

- [Excel quick start](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-jquery?tabs=visual-studio-code)
- [Word quick start](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/word-quickstart?tabs=visual-studio-code)
- [OneNote quick start](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/onenote-quickstart)
- [Outlook quick start](https://docs.microsoft.com/en-us/outlook/add-ins/quick-start?tabs=visual-studio-code)
- [PowerPoint quick start](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/powerpoint-quickstart?tabs=visual-studio-code)

**Comment by Radzell** [comment]
@kbrandl How do you deploy the add-in once you're finished

**Comment by kbrandl** [comment]
@Radzell the [Deploy and publish your Office Add-in](https://docs.microsoft.com/en-us/office/dev/add-ins/publish/publish) article contains information about various options for deploying your add-in. As the docs describe, the **Network share** deployment technique is only valid on Windows, the **SharePoint catalog** technique is not supported by Office for Mac, and the **Exchange server** technique only applies to Outlook add-ins -- but the other three methods (**Sideloading**, **Centralized Deployment**, and **AppSource**) are valid for any platform/OS or type of add-in.
