### ISSUE TITLE
Angular Excel Get started not working

### ISSUE THREAD

**Issue by jacqueslareau** [OfficeDev/office-js-docs-pr#64]
Article: https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/includes/file-get-started-excel-angular.md

Issue: 

I just did the walkthrough and it does not work.

First, tsconfig.conf target needs to be changed to es6 or else it wont compile (because of the async usage in app.component.ts).

And then the add-in is just stuck on Loading...

**Comment by Hongbo-Miao** [comment]
Hi @jacqueslareau , can you try [this repo](https://github.com/Hongbo-Miao/office-addin-angular) one? Thanks

**Comment by jacqueslareau** [comment]
@Hongbo-Miao this repo works! What is the difference?

**Comment by Hongbo-Miao** [comment]
@jacqueslareau I don't know.. but I will try to find out today.

**Comment by lindalu-MSFT** [comment]
@Hongbo-Miao This is no longer an issue for the customer so I'm closing for now. If you need to add to this issue, please reopen.
Thanks, linda
