### ISSUE TITLE
Usage of AsyncStorage outside of custom functions is vague

### ISSUE THREAD

**Issue by evantrimboli** [OfficeDev/office-js-docs-pr#658]
The docs refer to `AsyncStorage` as a way to share information between different add-ins. However, it seems as though `AsyncStorage` doesn't come baked into the default JS file when using it outside of custom functions.

## Article URL
https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/custom-functions-runtime.md

## Issue
My Excel addin is loading `office.js` from https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js
There are no references to `AsyncStorage` here. Am I supposed to load it from a different source? Or install a package from npm? I can see references to `AsyncStorage` directly in the custom-functions built file: https://officedev.github.io/custom-functions/lib/custom-functions-runtime.debug.js

**Comment by kbrandl** [comment]
@evantrimboli thanks for reaching out about this. @keyur32 can you please provide some feedback re these questions about `AsyncStorage`?  Thanks!

**Comment by kbrandl** [comment]
@mscharlock and @davidchesnut FYI re feedback about the custom functions docs.

**Comment by davidchesnut** [comment]
Hi @evantrimboli,

You are correct. You need to use the https://officedev.github.io/custom-functions/lib/custom-functions-runtime.js file to use asyncstorage. This feature is currently in preview.

If you follow the steps in the [Create custom functions in Excel tutorial](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Foffice%2Fdev%2Fadd-ins%2Ftutorials%2Fexcel-tutorial-create-custom-functions&data=04%7C01%7Cdavech%40microsoft.com%7C46b57921068b4a81c65808d6711093f0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636820713339286924%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C-1&sdata=HJvNr5zl3RyF0KD7%2BzXkGpK8je6PriaQk6G4yogbVqA%3D&reserved=0)  it will show how to use yo office to create a simple custom function. In the generated index.html file you will see the reference to the custom-functions-runtime.js. 

Hope this helps,
David

**Comment by evantrimboli** [comment]
In this particular case my add-in is using both the task pane and the custom-functions, so there are 2 separate entry points. If I want to use the `AsyncStorage` from the task-pane side, am I supposed to also load custom-functions-runtime.js as part of that as well? I can use `AsyncStorage` fine from the custom-functions entry point, the question is more surrounding how to use it from the other pieces.

**Comment by davidchesnut** [comment]
Hi @evantrimboli ,

In that case use the https://officedev.github.io/custom-functions/lib/office.js version for the task pane part of your add-in.

Cheers,
David

**Comment by davidchesnut** [comment]
I think that file is supposed to pull in one of the others that does have the AsyncStorage object. Not sure why it is not working so I'm digging into this a bit more and will work to get back to you soon.

Cheers,
David

**Comment by davidchesnut** [comment]
Hi @evantrimboli okay I confirmed that you can use the https://officedev.github.io/custom-functions/lib/office.js file to access asyncstorage from the task pane. It will include the asyncstorage object. I have this working in a sample that I will upload soon to help folks out. The JS call should look similar to the following code (which tests entering a token value to send to a custom function). Does this pattern work for you?

```js
function SendTokenToCustomFunction() {
            var token = document.getElementById('tokenTextBox').value;
            var tokenSendStatus = document.getElementById('tokenSendStatus');
            var key = "token";

            OfficeRuntime.AsyncStorage.setItem(key, token).then(function () {
                tokenSendStatus.value = "Success: Item with key '" + key + "' saved to AsyncStorage.";
            }, function (error) {
                tokenSendStatus.value = "Error: Unable to save item with key '" + key + "' to AsyncStorage. " + error;
            });
        }
```

**Comment by davidchesnut** [comment]
Hi @evantrimboli, I uploaded a complete [AsyncStorage sample](https://github.com/OfficeDev/PnP-OfficeAddins/tree/master/Excel-custom-functions/AsyncStorage). This shows code for passing values between custom functions and the task pane. Hope this helps.
