### ISSUE TITLE
Documentation is unclear about how to publish add-ins

### ISSUE THREAD

**Issue by nunon** [OfficeDev/office-js-docs-pr#672]
I followed the documentation to create the very basic Excel Add-in and now I'm trying to figure out how to install it in Excel.

I see everywhere that this is very simple, all you have to do is to upload the XML manisfest file, etc. but using Visual Studio, I chose publish via FTP and I get 3 folders in my website:

Content
Functions
Scripts

These are full of js scripts, but I don't see the manifest file nor the home.css, Home.js and Home.html

Isn't it possible to just upload the files with Filezilla to a folder? Which files?

If so, then how do I install the addin in Excel?

The documentation is unclear. It doesn't say where the files should be uploaded to. It only says that the manifest file has to be stored in a shared folder. How about the other files? And how to point the manifest to the other files location? That isn't written anywhere!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ddce0bd-5c66-c2cb-0640-ee4d5bd401c5
* Version Independent ID: b5d4bc26-a43e-4a85-e7d5-fe4fc4ec3d0d
* Content: [Sideload Office Add-ins for testing - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins)
* Content Source: [docs/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins.md)
* Product: **office 365**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
@nunon Sorry that you're having problems. Please start with this article: [Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/overview/office-add-ins) to get an overview. You will see that there are two main parts to an Office Web Add-in: (1) The manifest and (2) a web application. 
The manifest can be sideloaded or deployed using several methods. This article that you have commented on, describes one of them. For more information on publishing options, see this node of the documentation: [Publish](https://docs.microsoft.com/en-us/office/dev/add-ins/publish/publish)
The web application can be published/hosted using any method or platform that you want. We don't give instructions for most methods because this information is already available on the web. However, this article, [Host an Office Add-in on Microsoft Azure](https://docs.microsoft.com/en-us/office/dev/add-ins/publish/host-an-office-add-in-on-microsoft-azure) , explains how to do it on Azure. I recommend that you try that method of hosting first. Note that in step 6, you edit the manifest to point to the URL of your web app. When you feel familiar with the distinction between hosting the web app and deploying the manifest, you can try an alternate method of hosting the web app. No matter which method you choose, you will edit the manifest in the same way.
I'm not familiar with the FTP method of publishing a web application, so I don't know what went wrong in your case, but the Home.js, Home.html, and Home.css files should be part of it. The manifest file is NOT published in the web app.

**Comment by nunon** [comment]
Hello,

Thank you so much for the feedback, it’s very difficult to get any information about Office Add-ins, so it’s great I can have some help just to get started!
I’ve been developing Add-ins for Google Sheets and other Google Apps Scipts, using Js, Jquery, and GAS for years, so I’m familiar with the process.

Anyway, I’ve read everything about Office Add-ins in the documentation and I still can’t get the most basic Add-in published and running…

I could publish the files in my web server, but since there’s no documentation about it, I’m following the process for publishing in Azure as descibed here.

However, I can’t go through point 3.1. Using Visual Studio, it keeps asking me to sign in over and over:




And using the Azure Portal, it keeps asking me to “switch directories”:



I do have some Clients willing to swtich from Google Sheets to Excel, but this is really complicated, if I can’t even publish the “Hello World” add-in!

Nuno Nogueira



   
Swell - Training and Development, Lda.
Rua Eng. Ferreira Dias
161 E300
4100-247 Porto
Portugal

T: +351 220 927 049

De: Rick-Kirkham
Enviado: 9 de janeiro de 2019 21:36
Para: OfficeDev/office-js-docs-pr
Cc: nunon; Mention
Assunto: Re: [OfficeDev/office-js-docs-pr] Documentation is unclear about howto publish add-ins (#672)

@nunon Sorry that you're having problems. Please start with this article: Office Add-ins to get an overview. You will see that there are two main parts to an Office Web Add-in: (1) The manifest and (2) a web application.
The manifest can be sideloaded or deployed using several methods. This article that you have commented on, describes one of them. For more information on publishing options, see this node of the documentation: Publish
The web application can be published/hosted using any method or platform that you want. We don't give instructions for most methods because this information is already available on the web. However, this article, Host an Office Add-in on Microsoft Azure , explains how to do it on Azure. I recommend that you try that method of hosting first. Note that in step 6, you edit the manifest to point to the URL of your web app. When you feel familiar with the distinction between hosting the web app and deploying the manifest, you can try an alternate method of hosting the web app. No matter which method you choose, you will edit the manifest in the same way.
I'm not familiar with the FTP method of publishing a web application, so I don't know what went wrong in your case, but the Home.js, Home.html, and Home.css files should be part of it. The manifest file is NOT published in the web app.

**Comment by nunon** [comment]
Actually, I’ve managed to figure out how to publish the add-in to a web server, it’s not that difficult with a lot of trial-and-error in Visual Studio. 
It should be included in the documentation.

Nuno Nogueira



   
Swell - Training and Development, Lda.
Rua Eng. Ferreira Dias
161 E300
4100-247 Porto
Portugal

T: +351 220 927 049

De: Nuno Nogueira
Enviado: 10 de janeiro de 2019 12:50
Para: OfficeDev/office-js-docs-pr; OfficeDev/office-js-docs-pr
Cc: Mention
Assunto: RE: [OfficeDev/office-js-docs-pr] Documentation is unclear abouthowto publish add-ins (#672)

Hello,

Thank you so much for the feedback, it’s very difficult to get any information about Office Add-ins, so it’s great I can have some help just to get started!
I’ve been developing Add-ins for Google Sheets and other Google Apps Scipts, using Js, Jquery, and GAS for years, so I’m familiar with the process.

Anyway, I’ve read everything about Office Add-ins in the documentation and I still can’t get the most basic Add-in published and running…

I could publish the files in my web server, but since there’s no documentation about it, I’m following the process for publishing in Azure as descibed here.

However, I can’t go through point 3.1. Using Visual Studio, it keeps asking me to sign in over and over:




And using the Azure Portal, it keeps asking me to “switch directories”:



I do have some Clients willing to swtich from Google Sheets to Excel, but this is really complicated, if I can’t even publish the “Hello World” add-in!

Nuno Nogueira



   
Swell - Training and Development, Lda.
Rua Eng. Ferreira Dias
161 E300
4100-247 Porto
Portugal

T: +351 220 927 049

De: Rick-Kirkham
Enviado: 9 de janeiro de 2019 21:36
Para: OfficeDev/office-js-docs-pr
Cc: nunon; Mention
Assunto: Re: [OfficeDev/office-js-docs-pr] Documentation is unclear about howto publish add-ins (#672)

@nunon Sorry that you're having problems. Please start with this article: Office Add-ins to get an overview. You will see that there are two main parts to an Office Web Add-in: (1) The manifest and (2) a web application.
The manifest can be sideloaded or deployed using several methods. This article that you have commented on, describes one of them. For more information on publishing options, see this node of the documentation: Publish
The web application can be published/hosted using any method or platform that you want. We don't give instructions for most methods because this information is already available on the web. However, this article, Host an Office Add-in on Microsoft Azure , explains how to do it on Azure. I recommend that you try that method of hosting first. Note that in step 6, you edit the manifest to point to the URL of your web app. When you feel familiar with the distinction between hosting the web app and deploying the manifest, you can try an alternate method of hosting the web app. No matter which method you choose, you will edit the manifest in the same way.
I'm not familiar with the FTP method of publishing a web application, so I don't know what went wrong in your case, but the Home.js, Home.html, and Home.css files should be part of it. The manifest file is NOT published in the web app.
