### ISSUE TITLE
Update trusting self-signed certificate docs

### ISSUE THREAD

**Issue by Alex-Mann** [OfficeDev/office-js-docs-pr#678]
# Summary Of Issue
On Office for Mac 2016 (v16.21), when trying to sideload an add-in, you have the ability to trust the certificate without having to manually add it to your keychain. You should describe this as it is a much easier, method if it is possible on all versions of MacOS or Word. I am running on MacOS Mojave, though it could be possible that older versions of MacOS do not support adding trusted certificates this easily.

The bullet point 4 from the link below is the specific instruction step to be updated.

## Article URL
https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/word-tutorial#create-your-add-in-project

**Comment by mscharlock** [comment]
@Alex-Mann Thanks for trying out add-ins and bringing this up to our team! I will go ahead and sync with the folks who are responsible for writing the content about self-signed certificates and get some clearer instructions (if that makes sense given there may be differences between older MacOS versions as you point out).

**Comment by davidchesnut** [comment]
Hi @Alex-Mann I created a PR to update the page with simpler steps. Details at https://github.com/OfficeDev/generator-office/pull/423 

However I noticed you got this to work without using the keychain. I couldn't find a way to do that. Can you provide more info on how to do that? Thanks!

**Comment by davidchesnut** [comment]
Hi @Alex-Mann 
Closing this issue, however if you have more information to share let me know and I’ll be glad to re-open it. Thanks!
