### ISSUE TITLE
Invalid information for the SupportsPinning element

### ISSUE THREAD

**Issue by vtiti** [OfficeDev/office-js-docs-pr#679]
The [SupportsPinning](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/action#supportspinning) section states the feature only available for the Outlook 2016 desktop version, but at this moment it is available for the other platforms also (except older platforms).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff9684d4-4f86-9287-2cb8-d563fb2deeb9
* Version Independent ID: d4345566-daef-fbe2-c887-615312d44614
* Content: [Action element in the manifest file - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/action)
* Content Source: [docs/reference/manifest/action.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/manifest/action.md)
* Product: **office 365**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by kbrandl** [comment]
@vtiti thanks for reporting this; we'll look into it and update the docs as appropriate.

**Comment by kbrandl** [comment]
I've confirmed with the product team that the `SupportsPinning` element is currently supported by Outlook 2016 for Windows (build 7628.1000 or later) and Outlook 2016 for Mac (build 16.13.503 or later). This article will be updated later this week when PR #705 is merged and the docs are refreshed. Thanks again for reporting this issue!
