### ISSUE TITLE
Missing closing tag

### ISSUE THREAD

**Issue by toddcarper** [OfficeDev/office-js-docs-pr#683]
There is a missing &lt;/VersionOverrides&gt; . Where does it belong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9caa983-63bf-9ec7-6885-acc576f18747
* Version Independent ID: b7f72393-be3e-3237-7b2c-b43dc26a2061
* Content: [VersionOverrides element in the manifest file - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/versionoverrides?product=outlook&view=office-js)
* Content Source: [docs/reference/manifest/versionoverrides.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/manifest/versionoverrides.md)
* Product: **office 365**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by kbrandl** [comment]
@toddcarper thanks for reporting this; we'll update the docs soon to address this issue. In the meantime though, I'll answer your question: the second closing tag for the **VersionOverrides** element (`</VersionOverrides>`) should appear immediately after the first closing tag for the **VersionOverrides** element (`</VersionOverrides>`) in the example.

```
<OfficeApp>
...
  <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides" xsi:type="VersionOverridesV1_0">
    <Description resid="residDescription" />
    <Requirements>
      <!-- add information on requirements -->
    </Requirements>
    <Hosts>
      <Host xsi:type="MailHost">
        <!-- add information on form factors -->
      </Host>
    </Hosts>
    <Resources>
      <!-- add information on resources -->
    </Resources>

    <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides/1.1" xsi:type="VersionOverridesV1_1">
      <Description resid="residDescription" />
      <Requirements>
        <!-- add information on requirements -->
      </Requirements>
      <Hosts>
        <Host xsi:type="MailHost">
          <!-- add information on form factors -->
        </Host>
      </Hosts>
      <Resources>
        <!-- add information on resources -->
      </Resources>
    </VersionOverrides>  
  </VersionOverrides>
...
</OfficeApp>
```

**Comment by kbrandl** [comment]
@toddcarper I've resolved this issue in the article and you should see the changes reflected in the live docs sometime in the next couple of days (whenever the doc set gets republished). In the meantime, please see my previous comment for clarification about the proper location of `</VersionOverrides>`. Thanks again!
