### ISSUE TITLE
Child element table and the code mismatching

### ISSUE THREAD

**Issue by AjitHogade** [OfficeDev/office-js-docs-pr#688]
In child element Table its mentioned that the
"Description" Required is "No" 
"Requirements" Required is "No"
"VersionOverrides"	Required is "No"

But in the code:
 &lt;VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides/1.1" xsi:type="VersionOverridesV1_1"&gt;
      &lt;Description resid="residDescription" /&gt;
      &lt;Requirements&gt;
        &lt;!-- add information on requirements --&gt;
      &lt;/Requirements&gt;
      &lt;Hosts&gt;
        &lt;Host xsi:type="MailHost"&gt;
          &lt;!-- add information on form factors --&gt;
        &lt;/Host&gt;
      &lt;/Hosts&gt;
      &lt;Resources&gt;
        &lt;!-- add information on resources --&gt;
      &lt;/Resources&gt;
    &lt;/VersionOverrides&gt;  

"versionOveride" is used ,
"Requirements" is used
"Description" is used

Bit confusion here

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9caa983-63bf-9ec7-6885-acc576f18747
* Version Independent ID: b7f72393-be3e-3237-7b2c-b43dc26a2061
* Content: [VersionOverrides element in the manifest file - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/versionoverrides#implementing-multiple-versions)
* Content Source: [docs/reference/manifest/versionoverrides.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/manifest/versionoverrides.md)
* Product: **office 365**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
The article is actually correct. The example code is intended to show a **typical** VersionOverrides element, including some child elements that are not required. I will add a sentence above the code block making this clear.
