### ISSUE TITLE
Any updates on supported requirement sets in the November 2018 release of Office Online Server?

### ISSUE THREAD

**Issue by dmytrol** [OfficeDev/office-js-docs-pr#696]
Hi,

Would love to see updates on supported requirements sets in the new release of Office Online Server that became available in November 2018.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c7080b5-9791-e1ca-ff77-ae3dbe5f10cc
* Version Independent ID: 1207aec0-6183-53bb-2768-ebb39d09ed99
* Content: [Excel JavaScript API requirement sets - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/excel-api-requirement-sets)
* Content Source: [docs/reference/requirement-sets/excel-api-requirement-sets.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/requirement-sets/excel-api-requirement-sets.md)
* Product: **office 365**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
@dmytrol 
I'm trying to track down this information. I will update the document with whatever I find.
