### ISSUE TITLE
How would caching cookies allow an ASP Site to bypass Same origin policy?

### ISSUE THREAD

**Issue by user135711** [OfficeDev/office-js-docs-pr#709]
I understand the OATH suggestion, but what does it mean "or caches credentials in cookies." The cookie cached will also be subject to domain origin and wouldn't allow any cross origin resource sharing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e24dccf5-3758-3d59-f896-c0a16306a238
* Version Independent ID: 0950c3fd-cdce-9f58-bcfe-baf9930dcd5f
* Content: [Addressing same-origin policy limitations in Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/addressing-same-origin-policy-limitations#implementing-server-side-script-using-a-token-based-authentication-scheme)
* Content Source: [docs/develop/addressing-same-origin-policy-limitations.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/addressing-same-origin-policy-limitations.md)
* Product: **office 365**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
@user135711 
Sorry we didn't get to this earlier. I'm researching but I think this is an error in the article.  

UPDATE: 
It is an error. All the text about cookies in that section is mistaken or irrelevant. A fixed version will be published in the next few days.

**Comment by Rick-Kirkham** [comment]
The source text is fixed. Next republish is scheduled for Tues night, Redmond, WA time; but a snow storm now underway in Redmond may delay things next week.
