### ISSUE TITLE
npm errors, deprecations

### ISSUE THREAD

**Issue by DLOwen** [OfficeDev/office-js-docs-pr#713]
Lots of alarming warnings from the npm command. FYI 

npm WARN deprecated babel-preset-es2016@6.24.1: ??  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
npm WARN deprecated babel@6.5.2: In 6.x, the babel package has been deprecated in favor of babel-cli. Check https://opencollective.com/babel to support the Babel maintainers
npm WARN deprecated express@2.5.11: express 2.x series is deprecated
npm WARN deprecated cryptiles@2.0.5: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated boom@2.10.1: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated connect@1.9.2: connect 1.x series is deprecated
npm WARN deprecated connect@1.9.2: connect 1.x series is deprecated
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN my-office-add-in@0.1.0 No description
npm WARN my-office-add-in@0.1.0 No repository field.
npm WARN my-office-add-in@0.1.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac7d9e2d-b537-cf1f-95fb-4e216514f3b1
* Version Independent ID: 4a86c93b-70d8-38e4-f62e-83c43a0158dd
* Content: [Excel add-in tutorial - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/excel-tutorial)
* Content Source: [docs/tutorials/excel-tutorial.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/tutorials/excel-tutorial.md)
* Product: **office 365**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
Thanks for bringing this up. A long list of WARN messages in normal for `npm install` commands. I've never once run such a command and gotten no WARNs at all. This is an intrinsic characteristic of open source software with its deeply nested dependencies on libraries. When you get an ERROR, you've got a real problem. But I've never had a problem with a WARN. At any rate, we at Microsoft don't control the deeply nested dependencies, so there's little we can do about these warnings.
