### ISSUE TITLE
Custom Functions Runtime article has incorrect dialog API name

### ISSUE THREAD

**Issue by davidchesnut** [OfficeDev/office-js-docs-pr#714]
The API name in the dialog API sample in [Custom Functions Runtime](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-runtime?view=office-js#displaying-a-dialog-box) is incorrect.

The code shows to call `OfficeRuntime.displayWebDialogOptions`.

Correct call is `OfficeRuntime.displayWebDialog`.

**Comment by mscharlock** [comment]
Fixed in a recent PR!
