### ISSUE TITLE
Custom Functions Already Exist

### ISSUE THREAD

**Issue by marcorocca1973** [OfficeDev/office-js-docs-pr#726]
Hi All
i try to create custom functions with visual studio code and Office.js 
All works… but in my environment after I finish my debug session… when I open Excel i continue to see my custom function (all node batch are closed).
I do not understand what happens…
Where custom functions are locally saved?
Can you help me?
Thanks
Marco

**Comment by keyur32** [comment]
Hi there, can you clarify what tool your are using to debug and how? Debugging itself for custom functions won’t be enabled for a few weeks so curious what your are doing today :)


Custom functions are cached for performance and the JavaScript is saved be Microsoft/office/16.0/WEF folder in your %APPDATALOCAL%

**Comment by marcorocca1973** [comment]
Hi
I realized that I expressed myself not very clearly :(
 As "debug" I meant... realize add-ins with Visual Studio Code and try it with command "npm run start" that sideloads my custom function into "temp" Excel file. 
Thanks for the clarification regarding the cache, works perfectly!
