### ISSUE TITLE
Method set not available in Range APIs

### ISSUE THREAD

**Issue by ATrogolo** [OfficeDev/office-js-docs-pr#733]
The example shown in the section **Loading the properties of an object** has a method _set()_ which is not available in Range APIs. 
```javascript
var targetRange = sheet.getRange("B7:E7");
targetRange.set(sourceRange); 
```
Could you fix the example? 

Andrea

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 705a8460-d773-7a5d-cfcf-e6e368497631
* Version Independent ID: 8d78c6a7-b061-aff2-a593-2953da93a9ce
* Content: [Advanced programming concepts with the Excel JavaScript API - Office Add-ins](https://docs.microsoft.com/it-it/office/dev/add-ins/excel/excel-add-ins-advanced-concepts)
* Content Source: [docs/excel/excel-add-ins-advanced-concepts.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/excel-add-ins-advanced-concepts.md)
* Product: **office 365**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@AlexJerabek: Can you take a look? Thx.

**Comment by Rick-Kirkham** [comment]
@ATrogolo That method was left out of the reference article for Range, but it is supported on Range. We've fixed the reference and you should see the fix in the next couple of days.
