### ISSUE TITLE
Tell developers to join the office dev program

### ISSUE THREAD

**Issue by CelticCoder** [OfficeDev/office-js-docs-pr#753]
https://developer.microsoft.com/en-us/office/dev-program stop suggesting getting a 1 month trial for dev, this is not correct. Join the office developer program to get a license to do your development and experiment

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77e380a7-6e2e-ada8-d297-3fd5018a1958
* Version Independent ID: f23490e8-6eeb-f2d5-6c94-69e3c9ed83f4
* Content: [Build your first Word add-in - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/word-quickstart?tabs=visual-studio#feedback)
* Content Source: [docs/quickstarts/word-quickstart.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/quickstarts/word-quickstart.md)
* Product: **word**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by lindalu-MSFT** [comment]
@CelticCoder @Reezaali Fixed and merged to live.

**Comment by lindalu-MSFT** [comment]
Note that this fix was in an include file so it was update in all places! Thanks for catching this, Keith!
