### ISSUE TITLE
Documentation says that custom function names should only contain letters but dots work as well

### ISSUE THREAD

**Issue by logicaloud** [OfficeDev/office-js-docs-pr#760]
Dots are useful and are used elsewhere in Excel function names. Should the documentation be updated to indicate that dots may also be used in function names (i.e. 'Increment.ByTwo') or will dots stop working at some point?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f56cdefe-9a9e-fb95-51d1-02a8c519b03c
* Version Independent ID: 4e4be0b6-b47e-1657-ea69-559877626503
* Content: [Custom functions best practices (preview) - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-best-practices)
* Content Source: [docs/excel/custom-functions-best-practices.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/custom-functions-best-practices.md)
* Product: **excel**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by mscharlock** [comment]
Hi @logicaloud: Yes, dots do work as you point out and (good news!) they will continue to work in the future! We will be publishing some updated info on naming very shortly in a separate "naming guidelines" article. I will go ahead and update this conversation with that link once the article publishes. Let me know if there's anything else I can assist with!

**Comment by logicaloud** [comment]
That's great! Thank you.

**Comment by mscharlock** [comment]
@logicaloud [Here you go!](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-naming) I am in the process of fixing our custom functions overview article to reflect the changes in this new naming guidelines article - but for now, the naming guidelines article is the source of truth. :) Let me know if you need anything else or have other questions, happy to help.

**Comment by mscharlock** [comment]
Just a heads up, I'm going to close this issue - but happy to re-open it if you need anything else. Thanks!
