### ISSUE TITLE
Confusing information about API support

### ISSUE THREAD

**Issue by 4tti** [OfficeDev/office-js-docs-pr#769]
Hi, 
there are incomplete and confusing information on this page.
1. At the top there is 'Note' which is confusing, it appear like that one specific version has that limitation but actually the limitation is for whole Office 2016 (non Office365 subscription)
2. Later the API versions are referencing Office 2016 but again it is incorrect as it actually is for Office365 - at least based on our investigations it seems that Office 2016 API supports only v1.1
3.  Similarly Office 2019 does not contain probably correct information

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7c255e4-d0f9-5b35-bec0-fdd690bdeff1
* Version Independent ID: dae8b049-0f53-ea13-9998-cfb4362b7553
* Content: [Office Add-in host and platform availability - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/overview/office-add-in-availability)
* Content Source: [docs/overview/office-add-in-availability.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/overview/office-add-in-availability.md)
* Product: **non-product-specific**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
Thanks for raising this issue @4tti . We are investigating.

**Comment by AlexJerabek** [comment]
Hi @4tti, 

Thanks for the feedback. We've updated the documentation with PR #771. That change will be pushed to the live branch soon.

I'll close the issue for now. If there's anything else, please comment on this thread and I'll reopen the issue.
