### ISSUE TITLE
Content disparity regarding clients and supported API requirements sets

### ISSUE THREAD

**Issue by adem** [OfficeDev/office-js-docs-pr#774]
Hi,

As of today, Outlook on the Web is listed as only supporting up to requirements set 1.6 while the following page (assuming that Outlook on the Web == Outlook Online) lists it as supporting requirements set 1.7 as well: https://docs.microsoft.com/en-us/office/dev/add-ins/overview/office-add-in-availability#outlook
Where should I look in order to be up-to-date regarding the supported API requirements sets for each client.

A slightly related question: Is there some kind of overview as to when each of the listed clients aim to catch up with the newer requirements sets? For example, I'd like to know when Outlook 2016 / 2019 for Mac will support requirements set 1.7.

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8e26a32-7523-2211-bde3-938cf94a76ec
* Version Independent ID: 80ad76d1-8a12-348f-dd6a-2f9392ed1f95
* Content: [Outlook JavaScript API requirement sets - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/outlook-api-requirement-sets)
* Content Source: [docs/reference/requirement-sets/outlook-api-requirement-sets.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/requirement-sets/outlook-api-requirement-sets.md)
* Product: **outlook**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
Thanks for the feedback, we will update our documentation to be clearer as well. We are in the process of releasing a [new version](https://support.office.com/article/get-help-with-the-new-outlook-on-the-web-017014cd-2ad0-41ab-8473-6bd8c349d4f8) of Old Outlook for Web (OWA). New OWA is live for Outlook.com accounts and is available to all enterprise customers as beta. As such we are making investments in new OWA only which currently supports 1.7 and Old OWA will not support requirement sets beyond 1.6. Support for 1.7 on Mac is in progress and we are targeting to release it in Q2 CY19.

**Comment by adem** [comment]
Great, thanks for the feedback as well!
