### ISSUE TITLE
Document requires objects' gathering examples

### ISSUE THREAD

**Issue by vv7v7** [OfficeDev/office-js-docs-pr#776]
Dear Developers,

Please, could you add some examples of gathering such objects as charts, shapes(not a text values) etc. i.e. as base64 values of images rendered. For example, we can get them from context.document.body.getHtml(), but this will give us only images(their src attribs), but not their content to show/send/modify.

Thank you very much,
Best regards

**Comment by AlexJerabek** [comment]
Hi @vv7v7, 

Thanks for sharing your needs for Office-js examples. Today in Excel, only Charts can be returned as image strings. [Here's the method for charts and a small example](https://docs.microsoft.com/javascript/api/excel/excel.chart?view=office-js#getimage-width--height--fittingmode-).

We're adding [Shape](https://docs.microsoft.com/javascript/api/excel/excel.shape?view=office-js) support in a future release. If you want those APIs, you must use the preview version of the Office JavaScript library from the [Office.js CDN](https://appsforoffice.microsoft.com/lib/beta/hosted/office.js). The [type definition file] (https://appsforoffice.microsoft.com/lib/beta/hosted/office.d.ts) for TypeScript compilation and Intellisense and is also found at the CDN. We do have some [Shape examples](https://github.com/OfficeDev/office-js-snippets/tree/master/samples/excel/85-preview-apis) you can use in [Script Lab](https://github.com/OfficeDev/script-lab).

I'll leave this issue open while I determine how to best update the documentation and make this information clearer. Please let me know if you have more questions in the meantime.

**Comment by AlexJerabek** [comment]
Hi @vv7v7, 
I've written an article about shapes, which includes information about saving shapes as images. This is part of PR #837. Please let me know if there's more information you'd like in there.

**Comment by AlexJerabek** [comment]
The updates to the Chart article are live. The article about shapes will be live within a few days. 

I'll close the issue. Please respond to this thread if there is more information needed. Thanks!
