### ISSUE TITLE
Request samples missing

### ISSUE THREAD

**Issue by 4tti** [OfficeDev/office-js-docs-pr#782]
Hi,

I am missing here complete and detailed sample how to use fetch request and xhr request.
There is piece of code for the xhr sample but the context is missing. Maybe it would be sufficient to just reference some GitHub sample.
Fetch request example is missing completely.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db285f50-5770-e426-47f6-a9f78536cab3
* Version Independent ID: 55778f17-2bdd-898b-41fc-e3f4e5517197
* Content: [Runtime for Excel custom functions (preview) - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-runtime)
* Content Source: [docs/excel/custom-functions-runtime.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/custom-functions-runtime.md)
* Product: **excel**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by mscharlock** [comment]
Hi @4tti - Thanks for alerting me to this! I will go ahead and look into getting a sample updated for this section of our documentation. 
In the meantime, I believe there is a fetch example in the [Custom Functions tutorial,](https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/excel-tutorial-create-custom-functions?tabs=excel-windows) which could be helpful while I update the docs. Additionally, a sample of XHR (but not in a custom function) is available in one of our other repositories, in [this file.](https://github.com/OfficeDev/Office-Add-in-JavaScript-FileDownload/blob/master/FileDownloadSampleWeb/Home.js) :) Let me know if you need anything else in the meantime. I'll update this issue when we update the documentation to reflect some updated samples. Thanks!

**Comment by 4tti** [comment]
@mscharlock  Thank you.
Just and idea -  could you please also provide samples for different methods than GET, e.g. POST?

**Comment by mscharlock** [comment]
@4tti Thanks for the idea! Yes, I can add that to my backlog of things to do but in the meantime, we have updated the custom functions docs. I'll keep this open to remind myself about the GET/POST sample request.

**Comment by mscharlock** [comment]
Samples should be uploaded to the site now - although GET/POST are still on our backlog. Closing the issue for now, happy to reopen if you'd like @4tti.
