### ISSUE TITLE
Document npx commands for how to enable runtime logging

### ISSUE THREAD

**Issue by davidchesnut** [OfficeDev/office-js-docs-pr#788]
## Article URL
https://docs.microsoft.com/en-us/office/dev/add-ins/testing/troubleshoot-manifest?view=office-js#use-runtime-logging-to-debug-your-add-in

## Issue
This article shows how to edit the registry to enable runtime logging for your addin. But an easier way is to use the npx command as follows.

Display whether runtime logging is enabled:    npx office-addin-dev-settings runtime-log 
Enable runtime logging:  npx office-addin-dev-settings runtime-log --enable 
Enable runtime logging for specific file:  npx office-addin-dev-settings runtime-log --enable filename.txt
Disable runtime logging:  npx office-addin-dev-settings runtime-log --disable 
Command-line help:  npx office-addin-dev-settings runtime-log --help 

Should add these steps to the document.

**Comment by lindalu-MSFT** [comment]
@davidchesnut Hi David! Any traction on this issue? Has the document been updated or should I assign this issue to another writer? Thanks, lindalu

**Comment by ElizabethSamuel-MSFT** [comment]
@davidchesnut Any update on this? Thanks.

**Comment by davidchesnut** [comment]
Thanks @mscharlock !
