### ISSUE TITLE
Schemas URI wrong

### ISSUE THREAD

**Issue by jcjolley** [OfficeDev/office-js-docs-pr#791]
A GET request to http://schemas.microsoft.com/office/appforoffice/1.1 returns:
"The resource you are looking for has been removed, had its name changed, or is temporarily unavailable."

Where are they saved now?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06f7f7e8-5b8a-e257-74be-77b47f048503
* Version Independent ID: a2851e98-268b-e65e-05eb-7ac3e21fe1ca
* Content: [Office Add-ins XML manifest - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/add-in-manifests?tabs=tabid-1#feedback)
* Content Source: [docs/develop/add-in-manifests.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/add-in-manifests.md)
* Product: **non-product-specific**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
This is normal. XML namespace names take the form of a URL, but are usually not actual URLs. They function as a structured name. The actual XSD files that define the schemas are found at: https://github.com/OfficeDev/office-js-docs-pr/tree/master/docs/overview/schemas

**Comment by jcjolley** [comment]
Well that's embarrassing.  Sorry for the noise.
