### ISSUE TITLE
Is Microsoft Office necessary for debugging with Safari Web Inspector

### ISSUE THREAD

**Issue by tejeshm** [OfficeDev/office-js-docs-pr#794]
I am using standalone Excel v-16.22 on High Sierra v-10.13.1. 
I enabled OfficeWebAddinDeveloperExtras for excel but still cannot see the option to inspect element on add-in. What am i missing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be179784-5839-3e8f-c131-1f4d89808b03
* Version Independent ID: 69bca101-91a2-3a5e-5177-493723504354
* Content: [Debug Office Add-ins on iPad and Mac - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-office-add-ins-on-ipad-and-mac#feedback)
* Content Source: [docs/testing/debug-office-add-ins-on-ipad-and-mac.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/debug-office-add-ins-on-ipad-and-mac.md)
* Product: **non-product-specific**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by kbrandl** [comment]
@tejeshm seems like [this content](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-office-add-ins-on-ipad-and-mac#debugging-with-safari-web-inspector-on-a-mac) from the article addresses the question that you've posed in the title of this issue: "Is Microsoft Office necessary for debugging with Safari Web Inspector?"

`To be able to debug Office Add-ins on Mac, you must have Mac OS High Sierra or later AND Mac Office version 16.9.1 (Build 18012504) or later. If you don't have an Office for Mac build, you can get one by joining the Office 365 Developer program.`

Sounds like you meet the first requirement (High Sierra), but as the article describes, you also need to have Mac Office version 16.9.1 (Build 18012504) or later. Can you please confirm whether this info resolves this issue?

**Comment by tejeshm** [comment]
Rather than downloading the Office i started using office online for debugging the add-in and it is working perfectly for me. Thank you

**Comment by kbrandl** [comment]
@tejeshm thanks for the update -- happy to hear everything's working well for you now.
