### ISSUE TITLE
Create Add-in for all Excel, Word, PowerPoint and Outlook 

### ISSUE THREAD

**Issue by baoduy** [OfficeDev/office-js-docs-pr#807]
Hello,
How could I create a React Add-in for all Word, Excel, PowerPoint and Outlook?

Thanks and Regards
Duy

**Comment by Rick-Kirkham** [comment]
@baoday Thanks for your interest in Office add-ins. We use the issues of this repo to track problems with the documentation. Please raise this technical question on StackOverflow. That way the whole community will benefit from the answers that you get.

**Comment by baoduy** [comment]
Hi @Rick-Kirkham 
Thanks for your answer. I have post the question to StackOverflown [here ](https://stackoverflow.com/questions/55055564/create-react-add-ins-for-office-2019-and-365)
