### ISSUE TITLE
Power pivots and data model

### ISSUE THREAD

**Issue by jonaskampe** [OfficeDev/office-js-docs-pr#816]
What is the support for power pivots and their data models?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf942d54-3ee5-2476-e11f-0b658e0bb189
* Version Independent ID: 2a671958-54a3-f477-6624-f2bdc7c133e5
* Content: [Work with PivotTables using the Excel JavaScript API - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-pivottables#feedback)
* Content Source: [docs/excel/excel-add-ins-pivottables.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/excel-add-ins-pivottables.md)
* Product: **excel**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @jonaskampe, 
Thanks for your interest in Excel API support. I'll reach out to the product team and find an answer for you.

**Comment by AlexJerabek** [comment]
Hi @jonaskampe,

Power pivots are not currently supported by the Office-js libraries. Please visit [UserVoice](https://officespdev.uservoice.com/) to request that functionality.

I'll leave this issue open until I update the documentation with this support note.

**Comment by AlexJerabek** [comment]
The documentation has been updated. The changes should be live within a few days. 

Closing the issue. Please leave a comment on this thread if there's more to say.
