### ISSUE TITLE
Allow localhost loopback is required also for Custom Functions

### ISSUE THREAD

**Issue by 4tti** [OfficeDev/office-js-docs-pr#820]
Hi,

recently we had issues with Custom Functions Runtime (CFR), it was not sending xhr/fetch requests and after some research we found out that actually the root cause is that CFR is UWP app like sandbox (at least that is what we think) and as a result the custom functions is not working on the same machine where actual addin service is hosted. Developer must enable the localhost loopback and it is not mentioned anywhere except this page where it is in context of side-loading in Office Online using edge! Please add more details about this localhost loopback and custom functions in appropriate sections. Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ab35128-1e97-c6ad-babc-f696f2e7b0fe
* Version Independent ID: cd1bacb1-14d7-a38d-321c-ebc2a526e03b
* Content: [Sideload Office Add-ins in Office Online for testing - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/sideload-office-add-ins-for-testing)
* Content Source: [docs/testing/sideload-office-add-ins-for-testing.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/sideload-office-add-ins-for-testing.md)
* Product: **non-product-specific**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by kbrandl** [comment]
@4tti thanks for providing this feedback; we'll look into incorporating this information into the custom functions docs as you've suggested. 

(@mscharlock and @davidchesnut FYI, assigning this to you.)

**Comment by mscharlock** [comment]
Hi @4tti - Thanks for the feedback, as @kbrandl mentioned we will integrate this into our custom functions docs. In the meantime, you might want to look at [this support article](https://support.microsoft.com/en-us/help/4490419/local-loopback-exemption-does-not-work) which addresses this problem.

**Comment by 4tti** [comment]
Thanks.

**Comment by mscharlock** [comment]
Hi @4tti - our team has included a note about local loopback exceptions into our custom functions docs and it should be up on our site tomorrow. Since the information is the same as the info from the link to the support article, I'm going to close this issue. Happy to reopen if you have other questions though! Thanks.
