### ISSUE TITLE
Office TaskPane Add In: could not be installed in restricted environment

### ISSUE THREAD

**Issue by weird-dreams** [OfficeDev/office-js-docs-pr#821]
Our client wants to install our office add-in at a very restricted environment (group policies and network).
The are not able to use the Office Store - so they tried to use a App Source document for installation.
The add in could not be installed - they get this error (german):
![image](https://user-images.githubusercontent.com/11518242/53392204-fc2b0200-3998-11e9-9694-d1ac24cbf6c8.png)
which means;
`ADD-IN ERROR: We could not load the Add-In because we have no connection to the catalog
`   

**_What network and group policies are necessary to install an office add in?
Is there a documentation we could give the admin at our client?_**

**Comment by AlexJerabek** [comment]
Hi @weird-dreams, 

I've checked in the documentation updates with PR #843. They should be live within a few days.

I'm going to close this issue. Please respond to this thread if there are any concerns or questions. Thanks!
