### ISSUE TITLE
Multiple version overrides in an yo office generated Outlook add-in is not clear

### ISSUE THREAD

**Issue by eurog33k** [OfficeDev/office-js-docs-pr#825]
This is the start of the generated manifest. It does not contain a seperate VersionOverrides tag, but the versionoverride is part of the OfficeApp declaration as such:

&lt;?xml version="1.0" encoding="UTF-8"?&gt;
&lt;OfficeApp
          xmlns="http://schemas.microsoft.com/office/appforoffice/1.1"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns:bt="http://schemas.microsoft.com/office/officeappbasictypes/1.0"
          xmlns:mailappor="http://schemas.microsoft.com/office/mailappversionoverrides/1.0"
          xsi:type="MailApp"&gt;

  &lt;!-- Begin Basic Settings: Add-in metadata, used for all versions of Office unless override provided. --&gt;

It is unclear how to add the versionoverride for 1.1 in this case since there is no seperate tag.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: a9caa983-63bf-9ec7-6885-acc576f18747
* Version Independent ID: b7f72393-be3e-3237-7b2c-b43dc26a2061
* Content: [VersionOverrides element in the manifest file - Office Add-ins](https://docs.microsoft.com/nl-nl/office/dev/add-ins/reference/manifest/versionoverrides#feedback)
* Content Source: [docs/reference/manifest/versionoverrides.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/manifest/versionoverrides.md)
* Product: **non-product-specific**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by eurog33k** [comment]
Just to be clear there is of course a versionoverride tag further in the manifest, but what is unclear is what I need to do with the OfficeApp definition is there is more than 1 overrride. Do I ignore that is says 1.0 there and just add an extra tag with 1.1 or?

**Comment by kbrandl** [comment]
@eurog33k the `VersionOverrides` element with `type="VersionOverridesV1_1"` is a child element of the `VersionOverrides` element with `type="VersionOverridesV1_0"`. This means that the `OfficeApp` element will always contain a child element `VersionOverrides` with `type="VersionOverridesV1_0"`, and that element can contain child element `VersionOverrides` with `type="VersionOverridesV1_1"`.

The XML code sample in [Implementing multiple versions](https://docs.microsoft.com/office/dev/add-ins/reference/manifest/versionoverrides#implementing-multiple-versions) shows the structure that I've described above: 

- the `OfficeApp` element contains child element `VersionOverrides` with `type="VersionOverridesV1_0"` 
- the `VersionOverrides` element with `type="VersionOverridesV1_0"` contains child element `VersionOverrides` with `type="VersionOverridesV1_1"` 

I'm going to close this issue now, but please comment here if you need any additional clarification.
