### ISSUE TITLE
[excel]office-addins web url

### ISSUE THREAD

**Issue by dinglicoding** [OfficeDev/office-js-docs-pr#832]
hi,

i have a question about office-addins in  excel,  when  open a  web url.

i found it is based on ie Kernel。 can i choose chrome Kernel or edge Kernel ?

thanks

![image](https://user-images.githubusercontent.com/3963826/54662429-e680a680-4b18-11e9-9d0e-e72ea5667840.png)

**Comment by ElizabethSamuel-MSFT** [comment]
@AlexJerabek Can you take a look? Thanks.

**Comment by AlexJerabek** [comment]
Hi @dinglicoding,

Thank you for your question about Office add-ins. Add-ins run inside an Internet Explorer control for Windows and iOS. This is not configurable. More information can be found at [Privacy and security for Office Add-ins](https://docs.microsoft.com/office/dev/add-ins/concepts/privacy-and-security).

I'll close the issue for now, but please reply to this thread if the information in that article is incomplete or insufficient. Thanks!
