### ISSUE TITLE
window.location.href stopped working recently on Excel for Mac?

### ISSUE THREAD

**Issue by Zlatkovsky** [OfficeDev/office-js-docs-pr#835]
Opening bug based on a Stackoverflow thread: https://stackoverflow.com/questions/48681380/window-location-href-stopped-working-recently-on-excel-for-mac 

In a Javascript based Excel add-in, it navigates to a third party oauth sign-in page using the following code:
     window.location.href = "https://app.hubspot.com/oauth/authorize";

It has been working well on Excel rich client on Mac (version 16.9 (180116)) until recently. Now it won't navigate to the 3rd party sign-in page anymore. There is no change in add-in manifest XML file and the 3rd party domain is whitelisted in the manifest as below too. The same code and manifest is still working well on PC Excel and Excel Online.

    <AppDomain>https://app.hubspot.com/</AppDomain>

I think the way Excel for Mac supports the the window.location.href was changed recently? Thanks for your help!

**Comment by Rick-Kirkham** [comment]
The reference topic for `<AppDomain>` has been updated to add a note about not putting "/" on the end.
