### ISSUE TITLE
vs2017 can not create excel add-ins

### ISSUE THREAD

**Issue by dinglicoding** [OfficeDev/office-js-docs-pr#848]
hi:

in windows 10,i install vs community 2017. and create an excel addins, then run show me error

![image](https://user-images.githubusercontent.com/3963826/54977370-0a8c2e00-4fd8-11e9-9802-adf31fb3d8da.png)

![image](https://user-images.githubusercontent.com/3963826/54977372-14159600-4fd8-11e9-83ec-6c5cf85049e5.png)

i don't know what's wrong. but if debug with office home and student 2016 is ok.

**Comment by Rick-Kirkham** [comment]
Sorry to see that you are having problems. The issues for this repo are used to track errors in the documentation. For technical problems like this one, please raise the issue on StackOverflow where the whole community will benefit from the answers that you get.
