### ISSUE TITLE
Documentation out of date

### ISSUE THREAD

**Issue by wtftc** [OfficeDev/office-js-docs-pr#851]
The https://docs.microsoft.com/en-us/office/dev/add-ins/publish/publish-task-pane-and-content-add-ins-to-an-add-in-catalog#feedback seems out of date for the section "To set up an add-in catalog on Office 365".

SharePoint admin has a classic and a "new" view. The "new" view is very limited and doesn't offer an "add-ins" or "apps" menu item. The classic view offers a menu item called "apps", not "add-ins". I am also in contact with support because I am seeing a mysterious error saying "The site collection cannot be created because the limit of 0 site collections has been reached.".

Finally, SharePoint is very slow and seemingly unnecessarily complex. It takes a large number of clicks on mysterious menu items and buttons to get what you want.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94198cb6-3426-c33f-6ff9-88f2a327af49
* Version Independent ID: 99fc507e-dc87-9367-fb44-ff1016ec9fe2
* Content: [Publish task pane and content add-ins to a SharePoint catalog - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/publish/publish-task-pane-and-content-add-ins-to-an-add-in-catalog#to-set-up-an-add-in-catalog-on-office-365)
* Content Source: [docs/publish/publish-task-pane-and-content-add-ins-to-an-add-in-catalog.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/publish/publish-task-pane-and-content-add-ins-to-an-add-in-catalog.md)
* Product: **non-product-specific**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@wtftc: Thanks for pointing this out and sharing your feedback.
@davidchesnut: Is this something you can look into? Thx.

**Comment by davidchesnut** [comment]
Hi @wtftc yes I see what you are describing. I'm working to update the article so it refers to the UI steps clearly. Thanks!

**Comment by davidchesnut** [comment]
Hi @wtftc, I updated the article to have correct UI steps for both online and on-premises SharePoint. Please take a look and let us know if you spot anything else. Thanks for letting us know so we could update the article!

**Comment by davidchesnut** [comment]
Hi @wtftc,

Documentation is up-to-date, so I will close this issue now. Please let us know if you find any additional issues.

Thanks!
