### ISSUE TITLE
Can I change my add-in icon at runtime?

### ISSUE THREAD

**Issue by glr0221** [OfficeDev/office-js-docs-pr#854]
Hello MS,

First off, my apologies if this is in the wrong category. I have scoured several documents and found no definitive answer to my question. I am currently researching on how to change the icon and texts of my outlook add-in at runtime. I have read some examples which were implemented in C#, but not in javascript add-ins. I also saw a feature request related to this. The URL of that request is:
https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/32041630-runtime-modifification-to-the-ribbon-command-butto

I also saw this on stackoverflow :
https://stackoverflow.com/questions/47625792/change-icon-with-javascript

Anyways, is it possible to modify icons/texts/captions at runtime, via javascript? If not (or if so), is it possible (or appropriate) that we update documentation for manifest reference to reflect this?

Again my sincerest apologies if this question/issue does not belong here. And thank you in advance for your assistance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fa4bff8-f44c-300a-dea9-0ea73699b3b8
* Version Independent ID: d175a9f9-4aff-5df6-81dd-d582943e98e6
* Content: [IconUrl element in the manifest file - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/iconurl)
* Content Source: [docs/reference/manifest/iconurl.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/manifest/iconurl.md)
* Product: **non-product-specific**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by kbrandl** [comment]
@glr0221 thanks for reaching out about this. The functionality you've described (changing an Office (web) add-in's icon/text/captions at runtime) is not currently supported. If you haven't already done so, I'd suggest that you upvote the User Voice request that you linked to, to indicate your interest in this feature. In the meantime, I'll leave this issue open for now, to track the need for us to update the documentation as you've suggested. Thanks again for the feedback!

**Comment by glr0221** [comment]
Thank you always!! @kbrandl 
I already upvoted that feature request.

**Comment by kbrandl** [comment]
@glr0221 I've submitted PR #1022 to add clarification that setting `IconUrl` at runtime is not currently supported. This change will become visible in the live docs later this week, after the PR is merged and doc updates are published. Thanks again for the feedback!

**Comment by sagarpilkhwal** [comment]
@kbrandl what is the caching policy of the XML manifest and the icon-url present in the xml file. How often will Outlook client (Desktop/Mobile) try to download the XML mainfest file ?
