### ISSUE TITLE
Update docs about clearing cache on Mac

### ISSUE THREAD

**Issue by kbrandl** [OfficeDev/office-js-docs-pr#856]
## Article URLs
At a minimum, the following 4 articles need to be updated:
- [Sideload Office Add-ins on iPad and Mac for testing](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/sideload-an-office-add-in-on-ipad-and-mac#sideload-an-add-in-on-office-for-mac)
- [Debug Office Add-ins on iPad and Mac](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-office-add-ins-on-ipad-and-mac#clearing-the-office-applications-cache-on-a-mac-or-ipad)
- [Validate and troubleshoot issues with your manifest](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/troubleshoot-manifest#clear-the-office-cache)
- [Troubleshoot user errors with Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/testing-and-troubleshooting#changes-to-add-in-commands-including-ribbon-buttons-and-menu-items-do-not-take-effect)

There may be additional articles that need to be updated also -- should be able to identify them by searching globally for `Microsoft.OsfWebHost`.

## Issue
To clear the Office cache on a Mac, docs currently say to delete the content of the folder `/Users/{your_name_on_the_device}/Library/Containers/com.Microsoft.OsfWebHost/Data/`. This folder doesn't exist on newer versions of Mac. Need to update the docs to include info about the new path. See [this SO thread](https://stackoverflow.com/questions/48671008/outlook-add-in-on-outlook-for-mac-clear-cache/48671842#48671842) for details.

**Comment by TheWass** [comment]
In case anyone comes here looking how to clear out the Excel Custom Functions cache on a Mac, it is located here:
~/Library/Containers/com.microsoft.Excel/Data/Library/Application\ Support/Microsoft/Office/16.0/Wef/*

**Comment by kbrandl** [comment]
Submitted PR #1023 to address this issue. Live docs will reflect those changes sometime later this week, after the PR is merged and doc updates are published live.
