### ISSUE TITLE
Let's make the document more clear, Thank you

### ISSUE THREAD

**Issue by chenxizhang** [OfficeDev/office-js-docs-pr#861]
Hi there

What does this note exactlly mean : "This code sends a PowerPoint or Word file to the web server in multiple slices. The web server or service must compile each individual slice into a single .pptx file before you can perform any manipulations on it."

Does it mean the service need to save a single .pptx file for each of slice? and how to merge all the slices?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5f7a698-efa2-3584-6ea0-85fa3718718f
* Version Independent ID: cef6669b-bfc0-840a-ea4e-ebc2ae5cc58a
* Content: [Get the whole document from an add-in for Word - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/word/get-the-whole-document-from-an-add-in-for-word)
* Content Source: [docs/word/get-the-whole-document-from-an-add-in-for-word.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/word/get-the-whole-document-from-an-add-in-for-word.md)
* Product: **word**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
I'll clarify the note. It means that the service appends the slices together in order and saves the resulting file as a pptx or docx file.

**Comment by Rick-Kirkham** [comment]
The revised article should be published by Tuesday night.
