### ISSUE TITLE
Add Button to Main File List

### ISSUE THREAD

**Issue by securityvoid** [OfficeDev/office-js-docs-pr#864]
In Outlook, is there a way to add a button to the main email view page, rather than only on the opening on a message? I'm not seeing a way to do that clearly here.

Looking for a way to add a button where a user can report suspected Phishing by clicking on a button and having it be sent as an attachment to an email address. I don't want the user to have to open the message in order to do this.

I know I can do this as a COM add-in, but I'd prefer the new plugin format, if possible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06e092f1-aa6a-45b5-50ce-a1afca772776
* Version Independent ID: fa9c31b7-b63a-9867-f298-4d579b899c30
* Content: [ExtensionPoint element in the manifest file - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/extensionpoint#events)
* Content Source: [docs/reference/manifest/extensionpoint.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/manifest/extensionpoint.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@exextoc: Can you help with this? thanks.

**Comment by exextoc** [comment]
Currently the feature you requested, is not a part of the product. We track  feature requests on our user-voice page. Please add your request there. Feature requests on user-voice are considered when we go through our planning process. 

https://officespdev.uservoice.com/forums/224641-general/category/131778-outlook-add-ins

**Comment by ElizabethSamuel-MSFT** [comment]
@exextoc: Thanks for your response.

@securityvoid: Please add your feature request to UserVoice as exextoc recommends. I'll go ahead and close this issue.

Thanks.
