### ISSUE TITLE
Schema error when using Requirements element

### ISSUE THREAD

**Issue by MakotoE** [OfficeDev/office-js-docs-pr#879]
I'm getting a XML Schema Violation when I run `validate-office-addin` on my manifest which uses the Requirements tag. Here is a snippet of my manifest:

```
<OfficeApp>
    <Requirements>
        <Sets>
            <Set Name="ExcelApi" MinVersion="1.7" />
        </Sets>
    </Requirements>
</OfficeApp>
```

The error message:

```
XML Schema Violation: Your manifest does not adhere to the current set of XML schema definitions for Office Add-in manifests. (link: https://aka.ms/add-in-manifest-schema-violation)
  - Details: The element 'OfficeApp' in namespace 'http://schemas.microsoft.com/office/appforoffice/1.1' has invalid child element 'Requirements' in namespace 'http://schemas.microsoft.com/office/appforoffice/1
.1'. List of possible elements expected: 'Dictionary' in namespace 'http://schemas.microsoft.com/office/appforoffice/1.1' as well as 'VersionOverrides' in namespace 'http://schemas.microsoft.com/office/taskpane
appversionoverrides' as well as any element in namespace 'http://www.w3.org/2000/09/xmldsig#'.
```

The documentation says that the Requirements element is contained in OfficeApp, so I'm not sure why this error says that Requirements is an invalid child of the manifest namespace. The full manifest is here: https://github.com/Emurasoft/excel-csv-import/blob/master/manifests/dev.manifest.xml. Due to this error, I'm not able to submit my add-in.

Is there something missing or incorrect about my manifest which causes this error? Thank you very much.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2624e97-4bcb-1533-093b-913708c1a65b
* Version Independent ID: b84ab413-311c-f2ca-6010-203a1f31f275
* Content: [Requirements element in the manifest file - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/requirements#feedback)
* Content Source: [docs/reference/manifest/requirements.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/manifest/requirements.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
It might be that the element is simply out-of-order. Please check this article: https://docs.microsoft.com/en-us/office/dev/add-ins/develop/manifest-element-ordering

**Comment by MakotoE** [comment]
@Rick-Kirkham Ah, that is it! Thanks.
