### ISSUE TITLE
365 vs Office Online

### ISSUE THREAD

**Issue by jordandev** [OfficeDev/office-js-docs-pr#887]
This page is a bit confusing about how there is a difference in uploading the add-ins to 365 or Office Online. When I go to my 365 account and open Excel by following the steps under the 365 section, it just opens Excel Online.

There is no "MY ORGANIZATION" tab in the add-ins dialog. Just a "MY ADD-INS" tab. Does that workflow where this a "MY ORGANIZATION" step still exist or is this document outdated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ab35128-1e97-c6ad-babc-f696f2e7b0fe
* Version Independent ID: cd1bacb1-14d7-a38d-321c-ebc2a526e03b
* Content: [Sideload Office Add-ins in Office Online for testing - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/sideload-office-add-ins-for-testing#sideload-an-office-add-in-in-office-online)
* Content Source: [docs/testing/sideload-office-add-ins-for-testing.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/sideload-office-add-ins-for-testing.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
I also have the same UI for them both, and when I'm signed in with a Microsoft Account, I see what you see; but when I'm signed in with an Office 365 account (Work or School account) I see *both* the "MY ADD-INS" and the "MY ORGANIZATION", and I can use either procedure. But it appears that the Office Online procedure will work for everybody, so I'll take the other one out of the article. Thanks for spotting this.

**Comment by jordandev** [comment]
Thanks.

For clarity this is what I get in Excel Online:

![excel365addins](https://user-images.githubusercontent.com/7706784/55968111-3b9f6c00-5c30-11e9-9c9e-b5f368af0329.PNG)

This is on an account on "Office 365 Enterprise E3"

**Comment by Rick-Kirkham** [comment]
Fixed in source. Should be published Tuesday night.
