### ISSUE TITLE
Centralized Deployment for Mac is already available or coming soon?

### ISSUE THREAD

**Issue by zakhan4** [OfficeDev/office-js-docs-pr#895]
In this document it is written in the top that "Deployment to multiple platforms, including Windows and Office Online, with Mac coming soon." While in a related document "Determine if Centralized Deployment of add-ins works for your Office 365 organization" it is mentioned that it is available for Mac. 

I'm a bit confused and wanted to know, that Centralized deployment for Mac is available at this point in time or not?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41508035-2045-1706-9917-cd2da1e99cc7
* Version Independent ID: ea51ce32-18e2-68ed-ddc5-74f0d3d8a3d1
* Content: [Publish Office Add-ins using Centralized Deployment via the Office 365 admin center - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/publish/centralized-deployment)
* Content Source: [docs/publish/centralized-deployment.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/publish/centralized-deployment.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@zakhan4: Thanks for pointing this out. It looks like Mac is supported now. I'll update our docs to reflect that.

**Comment by ElizabethSamuel-MSFT** [comment]
@zakhan4: Our documentation update should go live soon. Thanks again for raising this issue and sorry for the confusion.
