### ISSUE TITLE
Mac Add-in Cache

### ISSUE THREAD

**Issue by TheWass** [OfficeDev/office-js-docs-pr#901]
I'm currently developing an Add-in with custom functions, and I see neither of the two cache folders mentioned in the article:
com.Microsoft.OsfWebHost/Data/
com.microsoft.Office365ServiceV2/Data/Caches/com.microsoft.Office365ServiceV2/

How do we clear the cache on a Mac?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 589820d2-9925-dc5e-76a7-83921a569137
* Version Independent ID: ab8bde36-096f-81f3-f4d1-9b25fc69e6ee
* Content: [Sideload Office Add-ins on iPad and Mac for testing - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/sideload-an-office-add-in-on-ipad-and-mac)
* Content Source: [docs/testing/sideload-an-office-add-in-on-ipad-and-mac.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/sideload-an-office-add-in-on-ipad-and-mac.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Reezaali** [comment]
Hi @TheWass, does this issue have information that unblocks you? [#856](https://github.com/OfficeDev/office-js-docs-pr/issues/856)

**Comment by TheWass** [comment]
Yes.  Thank you.
