### ISSUE TITLE
Supertip does not work in OWA

### ISSUE THREAD

**Issue by davecra** [OfficeDev/office-js-docs-pr#902]
I am not seeing the Supertip in OWA/EXO. I do see it on the command in full-client Outlook. So either this is an OWA defect or the documentation needs to be updated to specify that the Supertip is for full-client only. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b06746f-7a76-abcd-21a8-06340499aab8
* Version Independent ID: 042c9006-4097-8162-6ac3-ced6ececd919
* Content: [Supertip element in the manifest file - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/supertip#feedback)
* Content Source: [docs/reference/manifest/supertip.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/manifest/supertip.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@exextoc: Can you confirm if this is the case? Thanks.

**Comment by exextoc** [comment]
@davecra Yes, Supertip description is not working and is not applicable to Outlook Web. We will be updating our documentation to clarify this. Thanks for reporting this issue.

**Comment by ElizabethSamuel-MSFT** [comment]
@davecra Thanks for raising this issue. The documentation update should go live soon. I'll close this issue now. Thanks.
