### ISSUE TITLE
Office 2016 on Windows, Word incorrect

### ISSUE THREAD

**Issue by rocketraman** [OfficeDev/office-js-docs-pr#906]
Add-in Commands are not listed as supported in Office 2016 on Windows (Word, PowerPoint, and Excel). I believe this is an error?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7c255e4-d0f9-5b35-bec0-fdd690bdeff1
* Version Independent ID: dae8b049-0f53-ea13-9998-cfb4362b7553
* Content: [Office Add-in host and platform availability - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/overview/office-add-in-availability)
* Content Source: [docs/overview/office-add-in-availability.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/overview/office-add-in-availability.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Reezaali** [comment]
Hi @rocketraman, thanks for reaching out with your question. I'm following up with our engineering team and will reply as soon as I have an answer. Thank you.

**Comment by Reezaali** [comment]
Hi @rocketraman, I've confirmed with our engineering team that the [Add-in Commands Requirement Set topic](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/add-in-commands-requirement-sets) has the support information for the requirement set. Only Outlook in Office 2016 for Windows supports the requirement set, whereas Office 365 for Windows supports the requirement set in Word, Excel, PowerPoint and Outlook.

**Comment by Reezaali** [comment]
Hi @rocketraman I'll go ahead and close this issue now. If you need further guidance or clarification, please reopen it. Thank you.

**Comment by rocketraman** [comment]
@Reezaali Thanks for your responses. Perhaps I am confused, but I have Office 2016 on my desktop and the add-in commands appear to be working fine. Also confusing to me is that Office 365 includes Office 2016 on the desktop as part of its product offering, so why would there be a distinction between add-in commands working for Office 365 but not for 2016?

**Comment by ElizabethSamuel-MSFT** [comment]
@rocketraman: Sorry for the confusion. There's a distinction between Office 2016 with an Office 365 subscription and Office 2016 without one. When you use Office without Office 365, you primarily have the features that shipped when it was released. With Office 365, you continue to receive new and updated features.

In our documentation, Office 365 for Windows represents the subscription version while Office 2016 for Windows represents a one-time purchase. We'll clarify this in the documentation. Thanks for bringing up this issue!

**Comment by rocketraman** [comment]
@ElizabethSamuel-MSFT Thanks for the clarification. Here is more information that is potentially confusing -- on this page about add-in commands, https://docs.microsoft.com/en-us/office/dev/add-ins/design/add-in-commands, it says that add-in commands are supported in Office 2016:

> Add-in commands are currently supported on the following platforms:
> 
> * Office 2016 or later for Windows (build 16.0.6769+)
> * Office for Mac (build 15.33+)
> * Office Online
> 
> More platforms are coming soon.

If that particular build number is only available with an O365 subscription, then the information you have given me is consistent. However, the wording there should probably be changed accordingly.

**Comment by kbrandl** [comment]
@rocketraman thanks again for the feedback. We've updated the docs for clarity (PR #914) and you'll see those updates reflected in the live docs as soon as that PR is merged later this week.
