### ISSUE TITLE
Is "SupportUrl" used anywhere?

### ISSUE THREAD

**Issue by yanli0303** [OfficeDev/office-js-docs-pr#915]
The provider name looks like a link but clicks on it nothing happens, I don't think "SupportUrl" is the link for the provider name.
But when and where will "SupportUrl" be used?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f777e5b5-79de-8e78-1b5c-514594de7e8c
* Version Independent ID: 457662b1-da37-8591-b7d2-0c482719b6bc
* Content: [SupportUrl element in the manifest file - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/supporturl#feedback)
* Content Source: [docs/reference/manifest/supporturl.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/manifest/supporturl.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
Yes. It is used by AppSource (formerly the Office Store). When an add-in is accepted in the store a page for it is created in the store. On the left side of that page is some metadata about the add-in. Near the bottom of that is a link to the add-ins support URL. The store is getting this URL from the SupportUrl in the manifest.
