### ISSUE TITLE
Ribbon missing

### ISSUE THREAD

**Issue by ravick4u** [OfficeDev/office-js-docs-pr#921]
I am using Word 2016 and when I hit F5 I do not see ribbon as well as "Office.context.requirements.isSetSupported('WordApi', 1.1)" function returns false.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77e380a7-6e2e-ada8-d297-3fd5018a1958
* Version Independent ID: f23490e8-6eeb-f2d5-6c94-69e3c9ed83f4
* Content: [Build your first Word add-in - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/word-quickstart?tabs=visual-studio)
* Content Source: [docs/quickstarts/word-quickstart.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/quickstarts/word-quickstart.md)
* Product: **word**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ravick4u** [comment]
There is a typo. I am using 2013

**Comment by AlexJerabek** [comment]
Hi @ravick4u,

Word 2013 only supports the [Common API requirement sets](https://docs.microsoft.com/office/dev/add-ins/reference/requirement-sets/office-add-in-requirement-sets) (see the [Host and platform availability article](https://docs.microsoft.com/office/dev/add-ins/overview/office-add-in-availability)). If you would like your add-in to use the WordApi 1.1 functionality, you'll need to use Office 2016, Office 365, or Office Online.

The need for this version is mentioned in the article, but we'll investigate ways to make this clearer. I'll close this issue, but please reply to the thread if you need further assistance.

**Comment by ravick4u** [comment]
I can see the addin on right side but why the Ribbon is missing? Can you please suggest alternet ways to add Ribbon in Office 2013 if this is the not recommended way.
