### ISSUE TITLE
Code updates 

### ISSUE THREAD

**Issue by brugh** [OfficeDev/office-js-docs-pr#926]
The latest version on GitHub is from 2 years ago. The last minor update from 7 months ago. Is this add-in still being developed or are we betting on a dead project if we were to adopt it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 521d6700-a497-1dbc-537e-258222a01699
* Version Independent ID: 831dcf77-f019-be54-1ceb-d3bf51415484
* Content: [JavaScript API for Office - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/javascript-api-for-office#feedback)
* Content Source: [docs/reference/javascript-api-for-office.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/javascript-api-for-office.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Reezaali** [comment]
Hi @brugh, thanks for your question. We're constantly releasing new updates to our APIs and various other features in Office. For example, [here's ](https://docs.microsoft.com/en-us/javascript/api/excel?view=office-js) a list of all of Excel's released APIs & what's currently in Preview. If there's anything in particular you're looking for and can't find, please let us know. Thanks!

**Comment by brugh** [comment]
Hi @Reezaali, thanks for the response. It's good to know that the Excel add-in is in full development. I'm currently trying to rebuild our templating-application in Office.js for Word. But I'm concerned that updates on the Word add-in seem very slow and there's plenty of features that would be needed (like page and style manipulation) to make the switch to the Office.js. If you can let us know that Office.js has the required attention from your Dev team and updates will come, then I feel save using it. If it's just a side-project then I need to look for another way to build an add-in. thanks!
