### ISSUE TITLE
CustomTab example could be enhanced

### ISSUE THREAD

**Issue by f-santos** [OfficeDev/office-js-docs-pr#927]
Lacks a Control example or a comment indicating that Control is necessary inside the CustomTab

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a1c62c2-4463-cfe3-2ecb-f4565204ab89
* Version Independent ID: a8df560c-8653-f5f9-f2aa-63af7e26eb30
* Content: [CustomTab element in the manifest file - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/customtab#feedback)
* Content Source: [docs/reference/manifest/customtab.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/manifest/customtab.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by kbrandl** [comment]
@f-santos thanks for bringing this to our attention. `Control` is not actually a valid child element of the `CustomTab` element -- the fact that it is listed as such is a mistake in the docs. I've submitted a pull request ([#936](https://github.com/OfficeDev/office-js-docs-pr/pull/936)) to address this issue, and you'll see this change reflected in the live docs later this week.  (This doc update will be in the queue for the next publication of doc updates, which should happen tomorrow.) Thanks again!
