### ISSUE TITLE
Not able to active debug mode for Office 16.24

### ISSUE THREAD

**Issue by georgiik-welldone** [OfficeDev/office-js-docs-pr#929]
Platform: Mac OS (10.14.4)
Office Version: 16.24
Product: PowerPoint

After run in terminal `defaults write com.microsoft.Powerpoint OfficeWebAddinDeveloperExtras -bool true` nothing has been changed, inspector still not available.

**Comment by Rick-Kirkham** [comment]
We use the issues in this repo to track problems with documentation. For technical issues, please post a question on StackOverflow, and be sure to tag it `office-js`.
