### ISSUE TITLE
Content Add-In expected consumption model

### ISSUE THREAD

**Issue by shweaver-MSFT** [OfficeDev/office-js-docs-pr#938]
What is the expected consumption model to use content add-ins or get them into the document? If I write for a content Add-In, I can't integrate with TaskPane or Ribbon Commands, correct? Is the expectation that the user goes through the *Insert Tab -&gt; My Add-Ins* for all instances of a Content Add-In?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39d23706-196e-a6e8-4323-c116de27ae2f
* Version Independent ID: dd7cee92-5bc9-5bfe-1e2a-c05bc3810289
* Content: [Content Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/design/content-add-ins#feedback)
* Content Source: [docs/design/content-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/design/content-add-ins.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by kbrandl** [comment]
@shweaver-MSFT thanks for reaching out and for your interest in Office Add-ins development. Currently, users can only insert a Content add-in by going through the _Insert tab -> My Add-ins_ flow as you've described. You're also correct that integration between a Content add-in and the Task Pane and/or Add-in commands (ribbon buttons) is not currently supported. I'm going to go ahead and close this issue now, but please feel free to reach out if I can be of further assistance.
