### ISSUE TITLE
How can we debug with Google Chrome?

### ISSUE THREAD

**Issue by NT-D** [OfficeDev/office-js-docs-pr#947]
Hi, thank you for making good document. I'm now debugging with Safari, but would you please tell me how we can debug with Chrome?

My question backgrounds are:
- Chrome have great debug plugins for react, redux and more for front end development
- VS code have great [Debugger for Chrome](https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-chrome) extension. It's really useful for debugging for many developers.

If possible, I want to load my app in Outlook for Mac and attach debugger from VS Code with Debugger for Chrome extension.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be179784-5839-3e8f-c131-1f4d89808b03
* Version Independent ID: 69bca101-91a2-3a5e-5177-493723504354
* Content: [Debug Office Add-ins on a Mac - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-office-add-ins-on-ipad-and-mac)
* Content Source: [docs/testing/debug-office-add-ins-on-ipad-and-mac.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/debug-office-add-ins-on-ipad-and-mac.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
The capability of debugging with Chrome is an interesting product enhancement request. Please vote up this suggestion at Office Developer Suggestion Box: [Make a tool for debugging javascript api in chrome](https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/37280617-make-a-tool-for-debugging-javascript-api-in-chrome).

**Comment by NT-D** [comment]
Thank you Rick. I'll vote it
