### ISSUE TITLE
Instructions to reload cache on Mac Sideloading page

### ISSUE THREAD

**Issue by jedunn** [OfficeDev/office-js-docs-pr#95]
https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/sideload-an-office-add-in-on-ipad-and-mac.md

The instructions to force a reload of your add-in by clearing your cache on a Mac appear to be incorrect. I'm not sure what the appropriate directions are but I think I was able to clear my cache by navigating to "com.microsoft.Office365ServiceV2/Data/Caches/com.microsoft.Office365ServiceV2/" and removing files.

**Comment by mattblackdev** [comment]
Aha!!! I was about to reinstall Office. Thanks @jedunn!!

**Comment by Reezaali** [comment]
@jedunn @mattblackdev - The [topic](https://github.com/OfficeDev/office-js-docs-pr/commit/a2f11e7fafb000c952dab3a89a395f9a731a5beb#diff-17e32e98e5d3d9177f25492de3b6c9cc) has been updated. Thanks!
