### ISSUE TITLE
Outlook Add-in not working in windows 10 

### ISSUE THREAD

**Issue by kalenikita** [OfficeDev/office-js-docs-pr#953]
I have created Outlook add-in in visual studio 2013 which is working fine in windows 2007 and office 2016, but plugin is not getting Loaded in windows 2010 and office 2016.

1. Add-in is not available under disabled COM add-in list.
2. Its registry value of load behaviour is 3 i.e loaded.

Is any compatibility issue with windows 10?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6cb5f52-dfc5-4fa2-6508-194d6f1c674a
* Version Independent ID: 8f3caf2d-fba3-166f-43bc-1d3e4007abab
* Content: [Troubleshoot user errors with Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/testing-and-troubleshooting#feedback)
* Content Source: [docs/testing/testing-and-troubleshooting.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/testing-and-troubleshooting.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
Thanks for your interest in Outlook Add-ins. The issues in this repo are intended to track errors in documentation. Please raise technical questions like this on StackOverflow. Be sure to tag it `outlook-web-addins`.
