### ISSUE TITLE
Inspect Element does not appear in right click menu on Mac

### ISSUE THREAD

**Issue by misaunde** [OfficeDev/office-js-docs-pr#958]
Using Mac OS 10.14.4 and Office 365 Excel version 16.24 (19041201), and after adding:
`defaults write com.microsoft.Excel OfficeWebAddinDeveloperExtras -bool true` in the terminal, and rebooting, "Inspect Element" does not appear in right click menu inside my Office add-in, in Excel.

Is it because I have a newer OS than High Sierra? Any Ideas?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be179784-5839-3e8f-c131-1f4d89808b03
* Version Independent ID: 69bca101-91a2-3a5e-5177-493723504354
* Content: [Debug Office Add-ins on a Mac - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-office-add-ins-on-ipad-and-mac)
* Content Source: [docs/testing/debug-office-add-ins-on-ipad-and-mac.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/debug-office-add-ins-on-ipad-and-mac.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by mscharlock** [comment]
Hi @misaunde - Thanks again for writing in to us! We really appreciate the questions and feedback. I'm happy to check with engineering and get back to you. Due to the upcoming //build conference on Monday, I just want to let you know that our staff is very busy so an answer will likely come after the weekend. Thanks! I will update this issue with more information when I have it.

**Comment by mscharlock** [comment]
@AlexJerabek Just wanted to ask if Excel team has been able to repro this issue?

**Comment by AlexJerabek** [comment]
One of our engineers tried to repro this and could not. I'll circle back with them about the conditions.

**Comment by mscharlock** [comment]
@Reezaali Can you refile this issue with the office-js repo specifically? I think we might be able to get more eyes on this issue there. Thanks!

**Comment by Rick-Kirkham** [comment]
@mscharlock Can't transfer it now. The beta transfer tool no longer gives `office-js` as an option. I'll try again tomorrow. If you are in a hurry, you might have the OP create a new issue directly in `office-js`

**Comment by misaunde** [comment]
Could @kbrandl move it? If not, I can make a new post in office-js.

I initially posted here because I liked the idea of this specific issue being tied to the documentation that others would likely be reading.

**Comment by misaunde** [comment]
New Issue: https://github.com/OfficeDev/office-js/issues/506
