### ISSUE TITLE
Custom functions state needs correct API name

### ISSUE THREAD

**Issue by davidchesnut** [OfficeDev/office-js-docs-pr#984]
The API to use storage is `OfficeRuntime.storage...` It's not Office.storage. Probably should do a search/replace across several articles to catch any other mentions, but primarily the code sample needs an update in this article: [Custom function save state](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-save-state)

**Comment by mscharlock** [comment]
Thanks - fixed this in the last push to master -> live, should be up to date now.
