### ISSUE TITLE
Force Internet Explorer 11 in Office JS Webviewer

### ISSUE THREAD

**Issue by hdwatts** [OfficeDev/office-js-docs-pr#989]
I notice in an upcoming version of Office the viewer will be forced to use the Edge browser.  For now, our product requires the use of Internet Explorer 11 or below and Edge is unsupported.  Is there anyway to configure our Addin to continue to use Internet Explorer 11 for our users on the latest Windows and Excel versions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d482334-7d96-d9d4-bbfb-9dc70b770c4b
* Version Independent ID: 501af0bc-4192-3cbd-fdb3-7b8b15ba8cce
* Content: [Web viewers used by Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/web-viewers-used-by-office-web-add-ins#feedback)
* Content Source: [docs/concepts/web-viewers-used-by-office-web-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/concepts/web-viewers-used-by-office-web-add-ins.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
There is no way that you can control which browser is used. On O365 for Windows, the version of Windows 10 and of O365 on the user's computer are going to determine what browser is used. I think that you need to make your add-in compatible with Edge as quickly as you can. 

BTW, we use the issues in this repo to track errors in the documentation. Technical questions like this one should normally be raised on StackOverflow, and tagged `office-js`. That way the whole community can benefit from the answers that you get.
