### ISSUE TITLE
Which Edge is meant ?

### ISSUE THREAD

**Issue by ckuetbach** [OfficeDev/office-js-docs-pr#997]
EdgeHtml Edge or Chromium Edge?

The Chromium could also be used at older Windows versions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d482334-7d96-d9d4-bbfb-9dc70b770c4b
* Version Independent ID: 501af0bc-4192-3cbd-fdb3-7b8b15ba8cce
* Content: [Web viewers used by Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/web-viewers-used-by-office-web-add-ins)
* Content Source: [docs/concepts/web-viewers-used-by-office-web-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/concepts/web-viewers-used-by-office-web-add-ins.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
Office Add-ins are agnostic as to what rendering engine is being used by Edge. They will use whatever Edge is on the user's computer. And Edge's evolution is independent of whether or not it is being used by Office Add-ins. At some point in the future, the Edge on the user's machine will be updated to use the Chromium rendering engine.
