### ISSUE TITLE
Bug in tutorial

### ISSUE THREAD

**Issue by charliereese** [OfficeDev/office-js-docs-pr#998]
Hi guys!

I had to run `npm build-dev` before running `npm start` or else I got the following error (and the plugin didn't work for obvious reasons):

```
Unable to start the dev server. Error: The dev server is not running on port 3000.
```

If you are able to reproduce, could you update the tutorial to include the extra step for others?

Loving the tutorial so far; the JS API is a great addition to the Office suite!

Charlie

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49ccc61e-06b1-fd30-63a0-625301ea0bc8
* Version Independent ID: 1fdff452-de8f-5b97-9f53-389eb9576b25
* Content: [Build an Excel task pane add-in using React - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-react#feedback)
* Content Source: [docs/quickstarts/excel-quickstart-react.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/quickstarts/excel-quickstart-react.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @charliereese,
Thanks for pointing this out. I just re-ran the quick start and encountered the same issue you did. I had to accept a certificate being installed. I'll work with the yo office group to provide the right guidance to users.

**Comment by AlexJerabek** [comment]
It appears the text about accepting the certificate installation is already in the QuickStart, though perhaps it's not obvious enough. I'll assign this to @davidchesnut to investigate better display and the yo office text changes.

**Comment by davidchesnut** [comment]
Hi @charliereese, 

If you are running on a Mac you may be seeing the same problem reported in [issue 978](https://github.com/OfficeDev/office-js-docs-pr/issues/978) @akrantz posted a workaround on that issue thread. I recommend giving that a try to see if it works for you. 

This is also being tracked as [issue 129](https://github.com/OfficeDev/Office-Addin-Scripts/issues/129) to look into with the templates.

Hope this helps,
David

**Comment by charliereese** [comment]
Thanks David!

As mentioned above I got it working fine; the documentation simply seemed to be missing a step.

I did do the example on a Mac, if you think that had something to do with needing the missing step.

Cheers

**Comment by ElizabethSamuel-MSFT** [comment]
@charliereese: We updated the certificate note and added Mac guidance (see issue 978 referenced previously). I'll go ahead and close this as you seem to be unblocked. Thanks again for letting us know.
